### ISSUE TITLE
Document testenv environment variables

### ISSUE THREAD

**Issue by DirectXMan12** [kubernetes-sigs/kubebuilder#1000]
We should have reference for how to make use of the various options to testenv, either in the book, in the godoc, or both.

Especially the environment variable to attach control plane output, that one's super useful.

Ref #920 

/kind documentation

**Comment by mariantalla** [comment]
I should be able to add that one, is it ok if I pick it up? Or is there work on it somewhere? 👀

**Comment by DirectXMan12** [comment]
yeah, go ahead.  You'll want to edit the reference section on testing in the KB book (check docs/book/src/testing.md), and possibly double-check the godoc for pkg/envtest in controller-runtime.
