### ISSUE TITLE
Release past v2.0.0

### ISSUE THREAD

**Issue by dholbach** [kubernetes-sigs/kubebuilder#1001]
Quite a few [nice improvements landed since v2.0.0](https://github.com/kubernetes-sigs/kubebuilder/compare/v2.0.0...master) and it'd be great to get them out there in a release.

**Comment by DirectXMan12** [comment]
cc @droot @mengqiy

**Comment by dholbach** [comment]
Might be good to wait for https://github.com/kubernetes-sigs/kubebuilder/pull/1059 to land?

**Comment by dholbach** [comment]
1059 has landed, but missed the v2.1.0 release: https://github.com/kubernetes-sigs/kubebuilder/compare/v2.1.0...master

**Comment by DirectXMan12** [comment]
we'll be doing another before kubecon :-)

**Comment by camilamacedo86** [comment]
Shows that it could be closed @DirectXMan12 @mengqiy

**Comment by dholbach** [comment]
https://github.com/kubernetes-sigs/kubebuilder/releases/tag/v2.2.0 has landed. :rocket:
