### ISSUE TITLE
Golden files test is broken

### ISSUE THREAD

**Issue by mengqiy** [kubernetes-sigs/kubebuilder#1003]
kubebuilder has a test to ensure the files under `/testdata` always reflects what is generated. Test will fail if `/testdata` is out of date.
But it seems to be broken now. See: https://github.com/kubernetes-sigs/kubebuilder/pull/983#pullrequestreview-290262845

/kind bug

**Comment by mengqiy** [comment]
It seems golden file test doesn't cover v2 scaffolding and it's brittle. 
The test requires explicitly specifying which files should be covered. And then check if they match.
If a file is not specified or the `/testdata` directory has more files than what are generated, the test can't catch it.

IMO the test should be generating the scaffolding using the new kubebuilder and diff it against the golden files. It's simpler and more robust.

**Comment by DirectXMan12** [comment]
SGTM
