### ISSUE TITLE
Webhook Patch Template K8s Version Incorrect

### ISSUE THREAD

**Issue by cliveseldon** [kubernetes-sigs/kubebuilder#1006]
The patch for a webhook adds a comment:

https://github.com/kubernetes-sigs/kubebuilder/blob/cd0b10ff1a7966ce3d449ae9fbb8d7029259bc31/pkg/scaffold/v2/crd/enablewebhook_patch.go#L54-L56

But I see `preserveUnknownFields` only in k8s version >=1.15

Running this patch on earlier clusters gives an error.

```
kustomize build config/crd | kubectl apply -f -
error: error validating "STDIN": error validating data: ValidationError(CustomResourceDefinition.spec): unknown field "preserveUnknownFields" in io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.CustomResourceDefinitionSpec; if you choose to ignore these errors, turn validation off with --validate=false

$ kubectl version
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.0", GitCommit:"2bd9643cee5b3b3a5ecbd3af49d09018f0773c77", GitTreeState:"clean", BuildDate:"2019-09-18T14:36:53Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13+", GitVersion:"v1.13.7-gke.8", GitCommit:"7d3d6f113e933ed1b44b78dff4baf649258415e5", GitTreeState:"clean", BuildDate:"2019-06-19T16:37:16Z", GoVersion:"go1.11.5b4", Compiler:"gc", Platform:"linux/amd64"}
```

/kind bug

**Comment by mengqiy** [comment]
Thanks for bring this up!
The patch itself doesn't have the `preserveUnknownFields` field.
It seems this bug is caused by an unexpected defaulting kicks in somehow. My guess there is an undesired roundtrip.
Ref: https://github.com/kubernetes/apiextensions-apiserver/blob/release-1.15/pkg/apis/apiextensions/v1beta1/defaults.go#L72-L74

I need to dig it further.

**Comment by mengqiy** [comment]
@cliveseldon What is your kustomize version?

**Comment by cliveseldon** [comment]
Yes, sorry I think the issue is https://github.com/kubernetes-sigs/controller-tools/issues/279

**Comment by cliveseldon** [comment]
I think this was added by our internal code to get around https://github.com/kubernetes-sigs/controller-tools/issues/279 so am closing unless you think there is still something that needs to be changed in kubebuilder.
