### ISSUE TITLE
Question: how do I enforce only certain properties are updatable in webhooks?

### ISSUE THREAD

**Issue by functicons** [kubernetes-sigs/kubebuilder#1010]
I am following the [example](https://github.com/kubernetes-sigs/kubebuilder/blob/master/docs/book/src/cronjob-tutorial/testdata/project/api/v1/cronjob_webhook.go) to implement validation webook for update. I want to enforce that only certain properties are updatable, so I need to compare the `old` with the `new`, but why is the `old` of type `runtime.Object`? How do I convert it to `CronJob` so that I can compare?

```
// ValidateUpdate implements webhook.Validator so a webhook will be registered for the type
func (r *CronJob) ValidateUpdate(old runtime.Object) error {
	cronjoblog.Info("validate update", "name", r.Name)

	return r.validateCronJob()
}
```

community/question

**Comment by mengqiy** [comment]
> why is the old of type runtime.Object?

The reason is that `ValidateUpdate` is part of the `Validator` interface, which we use to do auto wiring.
To have a deterministic `Validator` interface, we choose to use `runtime.Object` as the argument for `Old`.

**Comment by mengqiy** [comment]
It should be OK for you to do a type assertion.

**Comment by functicons** [comment]
Thanks, that worked!

https://stackoverflow.com/questions/58070974/how-do-i-convert-runtime-object-to-specific-type
