### ISSUE TITLE
RFE: Show a friendly msg when the user try to use kubebuilder and the export  export GO111MODULE=on was not executed before

### ISSUE THREAD

**Issue by camilamacedo86** [kubernetes-sigs/kubebuilder#1013]
/kind feature

WHAT: "Show an error msg with the solution instead of just throw the error"
WHEN: "the user try to use kubebuilder and the export  `export GO111MODULE=on` was not executed before"

**Comment by DirectXMan12** [comment]
/priority backlog

I'm not sure how easy it is for us to detect this exact error.

**Comment by DirectXMan12** [comment]
especially since we can't just check the env, because Go 1.13 doesn't require this.

**Comment by camilamacedo86** [comment]
Closing this one.No longer required with Go .1.13
