### ISSUE TITLE
Kind validation is a bit too strict

### ISSUE THREAD

**Issue by dlespiau** [kubernetes-sigs/kubebuilder#1019]
There are some circumstances where the the CamelCase check is a bit too strict. For instance, the [`AWSCluster` kind](https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/master/PROJECT#L10) doesn't work today:

```
$ kubebuilder create api --group infrastructure --version xxxx --kind AWSCluster
...
2019/09/24 18:21:13 error scaffolding APIs: kind must be camelcase (expected Awscluster was AWSCluster)
```

Acronyms should be handled by the checker, this looks like a valid kind to me.

/kind bug

**Comment by DirectXMan12** [comment]
yeah, we should be matching whatever kube specifies here, I think

/help

**Comment by Azadehkhojandi** [comment]
on another note -> related bug #1091

**Comment by mariantalla** [comment]
Re: matching what kube specifies, one option is to replicate validation logic from core Kubernetes to where validation happens in Kubebuilder ([this file](https://github.com/kubernetes-sigs/kubebuilder/blob/c9f4434235379e1d0ffca9b9cf36d720d7c39014/pkg/scaffold/v1/resource/resource.go), I think). 

Another option is to use the validation logic from "core" Kubernetes directly. I think that logic lives [here](https://github.com/kubernetes/kubernetes/blob/41a413331835d10d68f480e58bee862c6ef4084a/staging/src/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/validation/validation.go#L545). In practice it means importing `apiextensions-apiserver` and calling out to `ValidateCustomResourceDefinitionNames` or similar. Kubebuilder seems to vendor `apiextensions-apiserver` already so it shouldn't be too bad. Does that sound like a reasonable path forward? 🤔

**Comment by DirectXMan12** [comment]
Yeah, that's probably fine.  Just validating the names directly is probably ok since we already vendor that.

**Comment by camilamacedo86** [comment]
HI, @mariantalla  could you please assign the issue to you in order to avoid other dev get it since you gave a PR already one for this one? Also, devs will usually filter for the unassigned ones to know what they can do to contribute with. 

PS.: To do it just add a new comment with `/assign @your user`

**Comment by mariantalla** [comment]
With https://github.com/kubernetes-sigs/kubebuilder/pull/1133 now merged, this should be fixed. Will close, please reopen if it's still a problem.

(PS: @camilamacedo86 I somehow missed your comment above, sorry about that 😕 )

/close
