### ISSUE TITLE
Add support for kubectl categories

### ISSUE THREAD

**Issue by pmorie** [kubernetes-sigs/kubebuilder#102]
Categories are groups of resources (example: `all` is a category). CRDs can be part of categories:

https://kubernetes.io/docs/tasks/access-kubernetes-api/extend-api-custom-resource-definitions/#categories

It would be useful to drive the categories of a resource via a `kubebuilder:categories=foo,bar,zab` annotation.

**Comment by pwittrock** [comment]
Added this for the next Sprint
