### ISSUE TITLE
Update kube-rbac-proxy to v0.4.1 release

### ISSUE THREAD

**Issue by dennisme** [kubernetes-sigs/kubebuilder#1021]
Per https://github.com/brancz/kube-rbac-proxy/issues/26#issuecomment-534159471 has been pushed to `quay.io/brancz/kube-rbac-proxy:v0.4.1`. What is the process to update the `gcr.io/kubebuilder/kube-rbac-proxy`? Is this hand tagged and pushed by a maintainer? 

https://github.com/kubernetes-sigs/kubebuilder/blob/master/pkg/scaffold/v2/metricsauth/kustomize_auth_proxy_patch.go#L55 

I am looking to update this image in hopes to change the tls defaults. Currently they are insecure by default. 

The current work around is to hand edit the config files / deployment post `kubebuilder create ...` or disable the metrics bits all together. 

/kind bug

**Comment by DirectXMan12** [comment]
yeah, it's currently hand-tagged, because we were waiting for a "trusted" source -- there was some talk about sig-auth adopting the project, but we wanted something under kubernetes control in the meantime.

cc @mengqiy

**Comment by mengqiy** [comment]
Pushed `gcr.io/kubebuilder/kube-rbac-proxy:v0.4.1`. 
Also created PR https://github.com/kubernetes-sigs/kubebuilder/pull/1041

**Comment by dennisme** [comment]
Thanks @mengqiy and @DirectXMan12!
