### ISSUE TITLE
Nomenclature adopts are not always representing the same

### ISSUE THREAD

**Issue by camilamacedo86** [kubernetes-sigs/kubebuilder#1025]
/bug

In the user point of view, have the one nomenclature to represent more than one thing is very confusing and an issue. 

For example: Note that in the makefile and docs we can find the operator project called a controller which make the things be NOT very intuitive since it has a Controller actually.  E.g `IMG=<some-registry>/controller`

IMHO: the above should be for example `IMG=<some-registry>/<projectname>:<tag>`

Suggestion 
- call the **project** as **operator** and or **project**
- keep the **controller** word just to represent **Controllers**
- keep the **manger** word just to represent the **Manager** (main.go)

**Comment by DirectXMan12** [comment]
> call the project as operator and or project

Let's not use the term operator, because not all sets of controllers are operators

Otherwise, this seems like a good suggestion

/help

specifically, this is for things like the makefile

**Comment by camilamacedo86** [comment]
HI @DirectXMan12, 

Really thank you for your reply and support. Would not the kubebulder a tool to help us deb projects using the Operator concept? In this way, could we not say that by using it we are creating an Operator project? So, would not make sense call the projects made by it as operators?

**Comment by DirectXMan12** [comment]
KubeBuilder is often used for Operators.  All operators are made of controllers, but not all sets of controllers are operators.

Operators are sets of controllers that encode human operational knowledge for a specific application (e.g. the Prometheus Operator).  Controllers are more general -- for instance, the namespace service account controller isn't an operator because it doesn't have knowledge of a specific application -- it's very general.

KubeBuilder helps constructs sets of controllers.  Some of those are Operators, some might not be.

**Comment by camilamacedo86** [comment]
Really thank you for your clarification and explanation. Then, manager and controller are words which represents other units on it, so I just can think about the nomenclature project to represent it. Please, let me know if you have a better idea.

**Comment by DirectXMan12** [comment]
I like your suggestion of "projectname"

**Comment by camilamacedo86** [comment]
Hi @DirectXMan12, 

I think this one should be linked to Hi scaffolding-v3 milestone as well. WDYT?

**Comment by camilamacedo86** [comment]
I opened it when I started to have contact with the project. Also, IHMO any nomenclature change if/when required would be more assertively made after the integration after we have more feedbacks as well. So, closing it..
