### ISSUE TITLE
Add generation command for the features instead of scaffold all

### ISSUE THREAD

**Issue by camilamacedo86** [kubernetes-sigs/kubebuilder#1026]
/kind feature

**User Story:** As I user, I'd not like to have in the project YAML files of optional features which maybe never will be used by myself. 

**Why**
- Very hard to understand what actually the make commands are applying by default and are doing
- It makes very hard to understand what is or should or not be used
- Make the learning curve bigger than could be to start to use it
- Very hard understand how to enable features as for example "Cert". See that many config files has info comment and it very hard understand what, where and how it should be used. 

**Suggestions**
- As I user, I'd like to run commands to add all that is optional. Note that it could simplify the config/kustomizaton files as well

**Comment by DirectXMan12** [comment]
This is a long-standing issue.  We'd appreciate a comprehensive design around it.  cc @mengqiy for review

**Comment by camilamacedo86** [comment]
Just to clarifies. It is over we found a way to not scaffold ALL and generate the optional code just if the user will use it.

**Comment by mengqiy** [comment]
I'd be happy to review the design if needed.

**Comment by camilamacedo86** [comment]
I raised it a while. Now, it changes a little. However, my idea here is that we could have a plugin to generate the code. I will be working on in an EP.

**Comment by camilamacedo86** [comment]
We have a PR with its proposal now. See: https://github.com/kubernetes-sigs/kubebuilder/pull/1803
In this way, I am closing this one and we can let the discussion to get done in the PR.
