### ISSUE TITLE
Adds namespace to all resources is not replacing all

### ISSUE THREAD

**Issue by camilamacedo86** [kubernetes-sigs/kubebuilder#1027]
/kind bug

## What

The following in the `config/default/kustomization.yaml` is not replacing all namespaces with.

```
# Adds namespace to all resources.
namespace: kubetest-system
```

**Comment by DirectXMan12** [comment]
can you be more specific about what's not working?

cc @mengqiy

**Comment by camilamacedo86** [comment]
Sorry, for don't be so specific but many of them still with system and are not subscribed for the namespace where the project will be deployed. Is this the expected behaviour? Should not all be subscribed?

**Comment by mengqiy** [comment]
@camilamacedo86 Can you provide the GVK and name of the resources that having issue?
Also please ensure your kustomize is up-to-date.

**Comment by camilamacedo86** [comment]
Hi @mengqiy  and @DirectXMan12, 

I am closing this one. Sorry, I did not get before that the replacement is just made when we do make deploy. Thank you for your attention.
