### ISSUE TITLE
improve GitHub templates in order to gather the required information

### ISSUE THREAD

**Issue by camilamacedo86** [kubernetes-sigs/kubebuilder#1028]
/kind feature

WHAT: Improve GitHub templates 
WHERE: in this repo
WHEN: open issues/rfes users 

WHY: 
- A standard make easier to understand and address the needs
- As a user, I'd like to know what info I should provide 
- Avoid issues be opened without the common and minimal info required

Suggestion
- Add PR template 
- Add questions in the templates

**Comment by DirectXMan12** [comment]
I don't want the issue or PR template to be too heavy, because people tend to ignore them and not fill them out anyway, and then I have to fix up the issues.  However, we could add something akin to what we have in controller-runtime

**Comment by camilamacedo86** [comment]
I understand and I agree. I just think that would be great some standard in order to try to avoid miss info here.

**Comment by camilamacedo86** [comment]
Done,
