### ISSUE TITLE
Sample is missing namespace

### ISSUE THREAD

**Issue by camilamacedo86** [kubernetes-sigs/kubebuilder#1029]
/kind bug

WHAT: Unable to apply samples because of namespace
WHEN: we follow the quick start and exec "kubectl apply -f config/samples/"
WHY: Sample has not the namespace created for the project 

Suggestion
Add namespace.

**Comment by DirectXMan12** [comment]
huh?

```shell
~[go:sigs.k8s.io/kubebuilder]/testdata/project-v2 $ k apply -f config/samples/crew_v1_admiral.yaml
admiral.crew.testproject.org/admiral-sample created
```

**Comment by DirectXMan12** [comment]
can you be more specific as to your kubectl version and the error you got?

**Comment by camilamacedo86** [comment]
I think the issue was with my minishift local install then it was complaining about a namespace that was not successfully removed. However, it has not the namespace, should it not be applied in the same namespace of the operator project?

**Comment by camilamacedo86** [comment]
Hi @DirectXMan12,

it is not applied in the same namespace of the project. What is the goal of this sample? How it can be helpful for the users?
