### ISSUE TITLE
Add uninstall Makefile rule

### ISSUE THREAD

**Issue by erictune** [kubernetes-sigs/kubebuilder#1032]
Some people may want to uninstall a CRD after trying out an idea.

Is this just `kustomize build config/crd | kubectl delete -f`.
Or is this too dangerous to make easy?

**Comment by DirectXMan12** [comment]
No, that shouldn't be too dangerous

**Comment by DirectXMan12** [comment]
I seems like a reasonable thing to have

**Comment by camilamacedo86** [comment]
IMHO: As part of this tasks we should have: update the quick start doc with.

**Comment by champak** [comment]
Would it be useful to add a rule to undo the deploy step as well. Something on the lines of 
kustomize build config/default | kubectl delete -f -
Would get rid of the Deployment and Namespace..Thanks.
