### ISSUE TITLE
Support numbers in group names

### ISSUE THREAD

**Issue by nrvnrvn** [kubernetes-sigs/kubebuilder#1037]
## Currently:
```
$ kubebuilder create api --group k8s --version v1alpha1 ...
Create Resource [y/n]
y
Create Controller [y/n]
y
Writing scaffold for you to edit...
api/v1alpha1/redis_types.go
2019/09/25 18:22:12 error scaffolding APIs: group must match ^[a-z-]+$ (was k8s)
```

## Why
Allow users create group names like `k8s.example.com`

/kind feature

**Comment by DirectXMan12** [comment]
we'll need to match whatever kubernetes allows.  I think the answer for that is DNS subdomain, so we should switch to that.

/help

just verify that constraint in the kubernetes docs, and then plumb it through KB

**Comment by nrvnrvn** [comment]
Here are the findings:
https://github.com/kubernetes/apiserver/blob/af8f81df54d7d7a4fbd7634bf54becb5802554af/pkg/apis/audit/validation/validation.go#L102-L108
https://github.com/kubernetes/apimachinery/blob/master/pkg/api/validation/generic.go#L36-L41
https://github.com/kubernetes/apimachinery/blob/master/pkg/util/validation/validation.go#L141-L150

I could open up a PR if it looks ok at first glance and discuss it further there?

**Comment by camilamacedo86** [comment]
The PR https://github.com/kubernetes-sigs/kubebuilder/pull/1048 would solve it. 
/assign @camilamacedo86

**Comment by camilamacedo86** [comment]
Hi @DirectXMan12 and @nrvnrvn,

I understand that we can close it with the merge of PR  #1048. WDYT?

**Comment by nrvnrvn** [comment]
I would say - yes.
But I would also check if there are any more places where the api machinery’s validation could be leveraged in the same manner.

**Comment by camilamacedo86** [comment]
Hi @nrvnrvn, 

So far, just the group is the place which we identify this need. Also, note that each issue/task would deal with a problem/subject/question. So, in this issue, you did an RFE in order to be allowed to `kubebuilder create api --group k8s --version v1alpha1 ...`  Are you able to do it with the master branch? If yes, then IMO we should close this one. 

However, see that we are free to raise new issues/tasks for each need/requirement/problem that we may face. 

Really thank you for your attention and support this matter.

**Comment by DirectXMan12** [comment]
we should file separate follow-ups for separate instances -- it's easier to track that way

**Comment by camilamacedo86** [comment]
Hi @nrvnrvn and @DirectXMan12,

Could you please help me let me know what is missing to do here to get this issue closes? Then, maybe I can help us move forward with.

**Comment by DirectXMan12** [comment]
we can close this issue.  If there are others we can file new issues for them
