### ISSUE TITLE
Add to the generated suite_test

### ISSUE THREAD

**Issue by champak** [kubernetes-sigs/kubebuilder#1039]
The generated suite_test.go is very sparse. Could it not have generated code for instantiating the applicable Reconciler and creating and deleting and CRD instances ? If code generation logistics are too hairy a few comments on useful test patterns would be useful too. Thanks.

/kind feature

**Comment by DirectXMan12** [comment]
we were holding off on this till we figure out how and what we want to scaffold.  We used to scaffold stuff, and people never touched it/got confused by it 

closing in favor of #920  -- please weigh in there
