### ISSUE TITLE
Rename samples for CR 

### ISSUE THREAD

**Issue by camilamacedo86** [kubernetes-sigs/kubebuilder#1046]
/kind feature

## What:
Rename sample for CR

## Why: 
- Samples give the idea of that what is created there is just a sample and is not useful
- It is important devs have a CR with the default values in the project in order to built projects easier to being configured and used, keep easier the understand and the maintenance ability.

**Comment by DirectXMan12** [comment]
I don't think this is more intuitive -- the directory is supposed to be samples of the custom resource that they can use for testing, to guide users as an example, etc.  It's not supposed to be default values -- that's what the default markers are for.

**Comment by camilamacedo86** [comment]
Really thank you for your reply. Also, what do you mean with `default markers`? Could you send me an example/doc over how it works?

Following my current understanding and please let me know what  I am missing here regards the kubebuilder idea/concepts.

Let’s think in the scenario where the operator was developed to install an App and its DB. Then, should not the project always have its CR in order to allow it to occurs? Will the project manage something without a CR? So, the CR attributes can be customised, however, really make sense lead the idea that a CR is just an example/sample and not a requirement?

**Comment by DirectXMan12** [comment]
> What do you mean by "default markers"

See https://github.com/kubernetes-sigs/controller-tools/pull/323

Basically, you do

```go
// +kubebuilder:validation:Default=<some value>
```

and then the kube-apiserver will take care of defaulting for you.

**Comment by DirectXMan12** [comment]
> Then, should not the project always have its CR in order to allow it to occurs? Will the project manage something without a CR? So, the CR attributes can be customised, however, really make sense lead the idea that a CR is just an example/sample and not a requirement?

I'm not entirely certain I'm following, but I'd look at it like this:  you wouldn't say "if you install Kubernetes you need to also use a Deployment object" -- you'd say "once you install Kubernetes, you can use it to manage your deployments with the Deployment type.  There's a sample Deployment in samples/, but you'll want to create your own for whatever you have to do".

**Comment by camilamacedo86** [comment]
Hi @DirectXMan12,

I understand what you mean now and its concepts idea. Really thank you for your explanation. 

Currently, in the SDK, we use the CR's values for example to create the examples/default values for the CSV which is used in OLM. So, understand this idea/concept lead me to think that this an good point to highlight internally since may we need to perform changes it in SDK. 

c/c @joelanford. 

I am closing this RFE as defered as the PR.  Thank you again for your time and support.
