### ISSUE TITLE
Rename Config dir for deploy dir  

### ISSUE THREAD

**Issue by camilamacedo86** [kubernetes-sigs/kubebuilder#1051]
/kind feature

**Is your feature request related to a problem? Please describe.**
The config dir does not reflect that it actually is the dir where has the files which will be applied in the cluster by the command make docker-deploy

**Describe the solution you'd like**
rename it for deploy in order to be more consistent and intuitive

**Comment by DirectXMan12** [comment]
see my comment in the associated PR

**Comment by camilamacedo86** [comment]
Hi @DirectXMan12, 
Just a reminder for we add the issue`scaffolding-v3 milestone`. :-)

**Comment by camilamacedo86** [comment]
I opened it when I started to have contact with the project. I think that the config name make more sense for me now since we have the kustomization files for example. 
Also, IHMO any nomenclature change would be more. assertive after the integration if required. 
Closing it so..
