### ISSUE TITLE
Build error if struct tags missing

### ISSUE THREAD

**Issue by erictune** [kubernetes-sigs/kubebuilder#1061]
KubeBuilder generates files which say `NOTE: json tags are required.  Any new fields you add must have json tags for the fields to be serialized.`

I suggest that KubeBuilder's workflow should cause a build failure users if these are missing from types which will become Kubernetes Kinds.  

The following changes could realize this, I think:

1. Let there be a new `controller-tools` command called `check-tags`.
  1. Let `check-tags` take as a flag a list of type names in this module, like `check-tags --types CronJob`.
  1. Let `check-tags` use `ParseDir` from package `go/parser` to parse everything in this module.
  1. Let `check-tags` recursively inspect each type definition listed by the `--types` flag and print an error if any field is missing tags or has wrong tags.
1. Let there be a new KB command called `kubebuilder lint`
  1. Let `kubebuilder lint` find all the root type names in this module ( types that have the `// +kubebuilder:object:root=true`).
  1. Let  `kubebuilder lint` call `check-tags` with the suitable args.
1.  Let there be a new makefile target called `lint` that runs  `kubebuilder lint`.
  1.  Add a `lint` target to makefile everywhere `fmt` and `vet` targets are listed as deps, so that every time you make all or make run, the apis are checked for correct tags.
  1. When lint fails, your build fails.

/kind feature

**Comment by DirectXMan12** [comment]
I thought we already failed to build the openapi validation if the tags were missing

**Comment by erictune** [comment]
I thought I had a file that wasn't getting errors, but I can't repro now.
