### ISSUE TITLE
Please take this concept diagram

### ISSUE THREAD

**Issue by erictune** [kubernetes-sigs/kubebuilder#1064]
I drew a picture of how the KubeBuilder key types fit together.
I don't know where you would want to put it in the documentation, but I offer it to you if you would like it.

[The diagram in Google Drawings](https://docs.google.com/drawings/d/1xWaYQFU-3d8NGsvraaLcqUZ6G09ROnlUxvKewqpwg2w/view)

Permissions are:
- viewable by anyone on the web 
- editable by kubernetes-kubebuilder@googlegroups.com

Can add other people  if needed.

Can send pull request.  Specify file location within this repo, format (svg, png, etc) and resolution)

/kind documentation

**Comment by DirectXMan12** [comment]
Prefered format is SVG.  Example of an SVG in the book at https://github.com/kubernetes-sigs/kubebuilder/blob/master/docs/book/src/multiversion-tutorial/conversion-concepts.md.

We probably want this one a top-level page.  Probably right after "Quick Start".

So docs/book/src/architecture.md or somesuch.

**Comment by DirectXMan12** [comment]
this is awesome, though

**Comment by DirectXMan12** [comment]
/lifecycle frozen

/help

(for getting this into the right place)
