### ISSUE TITLE
Migrate existing KB project to v1 CRDs and Webhooks with minimal user effort

### ISSUE THREAD

**Issue by erictune** [kubernetes-sigs/kubebuilder#1065]
Facts:
- 1.16 introduced CRD and Webhooks v1 APIs.
- CRD and Webhooks v1beta1 are deprecated and scheduled for removal in v1.19.
- Kubernetes users use wide range of Kubernetes minor versions.   

Consequences:
- In about 12 months, expect clusters running versions 1.15  through 1.19.  
- If KB only generates v1beta1 or only generates v1 CRDs/WHs, then my controller can't be installed on that range of clusters.

Request for KubeBuilder:
- Develop CRD and Webhook generation that can emit both v1beta1 and v1 CRDs/WHs.
- Document how a developer can have a single project and a single release artifact and have it work on v1beta1-only, both, and v1-only clusters.
- Don't decide that KubeBuilder v2.x.0 (or likewise for controller-tools, etc) is going to do a hard switch to generating v1 CRDs/WHs.    I want to get new features and fixes for KB while still releasing controllers work with 1.15 and earlier Kubernetes versions.

Related issues:
- #903 is about using the new features of v1 CRDs and webhooks.  This one is about expressing existing KB projects using v1 types.
- #944 is about APIs being deprecated in 1.16.  This one is about APIs being deprecated in 1.1

Additional Data about Versions:
   - From this slide of the [Kubernetes Apps Survey](https://docs.google.com/presentation/d/1utT0K-u1nl2apXRo29GaBvRV1x7mFLeQSgpw8mI_nGM/edit#slide=id.g3882d9116d_2_34), it appears that most (~95%) of users are running a cluster from one of the 4 most recent minor versions.
  - From the [detailed data of the same survey in column AN](https://docs.google.com/spreadsheets/d/12ilRCly2eHKPuicv1P_BD6z__PXAqpiaR-tDYe2eudE/edit#gid=840936477),  many users have 3 or even 4 minor versions in use concurrently.
- I'd expect this distribution to broaden over time, so having users spread across 5 versions in 2020 seems likely.

/kind feature

**Comment by DirectXMan12** [comment]
> Don't decide that KubeBuilder v2.x.0 (or likewise for controller-tools, etc) is going to do a hard switch to generating v1 CRDs/WHs. I want to get new features and fixes for KB while still releasing controllers work with 1.15 and earlier Kubernetes versions.

Agreed, that seems untenable.  We'll want to continue to generate v1beta1 CRDs in new versions of CT fo quite some time.

**Comment by camilamacedo86** [comment]
Hi @DirectXMan12, 

WDYT about if we keep the  v2 using the no-structural schemas and the next v3 generating it with  `apiextensions.k8s.io/v1`? Would it be a good approach?

c/c @joelanford @hasbro17

**Comment by erictune** [comment]
In that case, v2 needs to still get periodic updates for at least a year,
IMO.

Might be less work for the KB maintainers if you stay at v2 and let the
user select whether to generate v1beta1 or v1 CRDs.

**Comment by DirectXMan12** [comment]
Yep, that's what we're doing in CT now

**Comment by liggitt** [comment]
Is there a plan/timeframe in place for this?

**Comment by DirectXMan12** [comment]
@liggitt can you clarify what, specifically, you're looking for here?

**Comment by DirectXMan12** [comment]
AFAIK, all the pieces are in place.  There's a couple of switches that need to be flipped manually atm to use GA vs beta, but otherwise this is pretty much done

**Comment by liggitt** [comment]
I couldn't tell whether kubebuilder could generate new v1 CRDs, or regenerate existing APIs as v1 CRDs. If that's mostly done, that's good news.

**Comment by DirectXMan12** [comment]
yep -- `controller-tools crd:crdVersion=v1` will do it for you :-)

**Comment by DirectXMan12** [comment]
IIRC, we don't generate it by default because most folks still support (or supported at the time) kubernetes versions that didn't have v1 yet.

**Comment by liggitt** [comment]
makes sense. is there a plan to default to v1, once 1.15 is out of support?

**Comment by camilamacedo86** [comment]
I think would make sense we do it now for the V3. 
/assing @camilamacedo86

**Comment by camilamacedo86** [comment]
Solly in SDK we solve it by adding a flag in order to allow to keep the backwards compatibility. So, it means that by default the resources are scaffold using the latest version but users still able to use the flag in the commands to choose the old one. Do you think that it would be required here? Also, I think this would be a good change to get done now in the V3. WDYT?

**Comment by estroz** [comment]
The SDK needs a flag because it calls controller-gen libraries directly, i.e. you cannot set `crdVersion=<version>` manually. Since controller-gen is being called via `make` recipe in kubebuilder, docs should be sufficient. I didn't see anything discussing CRD API versions in the docs, so I can take this on if we agree it's just a docs issue.

**Comment by camilamacedo86** [comment]
Hi @estroz,

IHMO we need here to change the project as well to start to the scaffold by default all using the V1 not just for CRD's but for webhooks as well. Also, if we do not follow up with the flag ( which I also would not like to), we can just add the steps in the docs for the user how to gen for the old version if required.

**Comment by camilamacedo86** [comment]
Hi @estroz,

IHMO we need to address here: 

- Change the project to the scaffold CRD's and Webhooks using the V1 by default 
- update the docs and etc 

Then, we will have to address the backwards compatibility scenario: 

a)  if possible we could address the steps to manually gen the CRDs and Webhooks in the old version. 

OR 

b) solve it as SDK by creating a flag which allows users to choose if would like to still gen in the old version. 

IHMO: I would prefer `a)` because of simplicity. Is it make sense?

**Comment by DirectXMan12** [comment]
This is totally something we could do in a new `layout` version in v3, and then switch that to the default once 1.15 is out of support.

**Comment by estroz** [comment]
v1 CRDs and webhooks generated by default in `controller-gen`, respectively: https://github.com/kubernetes-sigs/controller-tools/pull/468, https://github.com/kubernetes-sigs/controller-tools/pull/469

**Comment by erictune** [comment]
As the OP, I'm not sure this original issue is closed yet.

Users may be running a wide range of clusters.  From what I gather, 1.14, 1.15, 1.16, 1.17, 1.18 and 1.19 are all moderately widespread at present.  How should a KubeBuilder user produce an release that runs on that range of cluster version?

**Comment by estroz** [comment]
@erictune given the list of 3 things you wanted out of kubebuilder, the only one that doesn't appear to be resolved is

>Document how a developer can have a single project and a single release artifact and have it work on v1beta1-only, both, and v1-only clusters.

Is that correct? Was there something else that needs doing?

To that effect: you can target the v1.14-v1.19 cluster range if you use v1beta1 CRDs/webhooks:

```sh
kubebuilder init --plugins go/v3-alpha
kubebuilder create api --crd-version v1beta1 ...
kubebuilder create webhook --webhook-version v1beta1 ...
```

For v1.14 clusters, you need to remove `crd:preserveUnknownFields=false` from your Makefile.

**Comment by erictune** [comment]
Awesome.  Can the text of your last comment, starting after `To that effect:`, go into the docs somewhere?

I searched but could not find something like it.

**Comment by estroz** [comment]
Definitely! I'll whip something up now.
