### ISSUE TITLE
Adding image secrets for controller image

### ISSUE THREAD

**Issue by champak** [kubernetes-sigs/kubebuilder#1067]
Hi, When attempting to use "make deploy <img>" to deploy to a cluster (after doing the make docker-build docker-push <img>..) I needed to add credentials so that the controller image that I had pushed to a repo could get pulled. The controller pod seems to go to a namespace named <kind>-system with service account "default". So it would seem we need to create and patch a secret to the "default" service account in namespace <kind>-system and then use that secret along with the controller image. I already have a secret that works in the default namespace for the repo but the controller pod needs to reference a secret in its own namespace. I could manually edit the scripts but was wondering if there are script options that I missed. I took a look at the kubebuilder book and did not see any pointers in this regard. I am not interested in a webhook at this point. Merely looking for an effective way to test a controller deployment with the image residing on a remote repo that requires a secret. Thanks

/triage support

**Comment by DirectXMan12** [comment]
I'd probably just add a kustomize patch for this for your own controllers.
Closing for now, but feel free to keep commenting
