### ISSUE TITLE
Add support to kube-state-metrics

### ISSUE THREAD

**Issue by camilamacedo86** [kubernetes-sigs/kubebuilder#1068]
/kind feature

Add support to https://github.com/kubernetes/kube-state-metrics

**Comment by joelanford** [comment]
@shawn-hurley @DirectXMan12 @mengqiy can one of you link this to https://github.com/kubernetes-sigs/kubebuilder/projects/7

Adding hooks in controller-runtime to support kube-state-metrics for CRs is one of the things in SDK we'd be interested in upstreaming.
