### ISSUE TITLE
How to enum poorly documented

### ISSUE THREAD

**Issue by erictune** [kubernetes-sigs/kubebuilder#1071]
There are quite a few ways a user might try to make an enum.   Only one or two ways are "right".

Suggested Fix: 
- Specifically have a section in the KubeBuilder book called "Enums" and show a generic example.
- Explain that the validation and how you chose to define types in Go are not related.  (This is not obvious because some aspect of go syntax do generate OpenAPI, like scalar types.)

# All the ways

## The Right Way

The documentation example for CronJob does an enum like this:
```
// +kubebuilder:validation:Enum=A,B,C
type MyEnum string
const (
    MyEnumA MyEnum = "A"
    MyEnumB MyEnum = "B"
    MyEnumB MyEnum = "C"
)
type MyObjectSpec {
  // 
   Mode MyEnum
}
```
This works right, in that the OpenAPI `enum=` validation is generated in the CRD.
However, a reasonable user might also try to do many other ways, only some of which work right.

## Alternative One
kubebuilder comment on the field in the Object.  
*Works right*
```
type MyEnum string
const (
    MyEnumA MyEnum = "A"
    MyEnumB MyEnum = "B"
    MyEnumB MyEnum = "C"
)
type MyObjectSpec {
  // 
   // +kubebuilder:validation:Enum=A,B,C
   Mode MyEnum
}
```

## Alternative Two
kubebuilder comment on the field in the Object and on the EnumType.  
*Does not work.  They seem to cancel out*
```
// +kubebuilder:validation:Enum=A,B,C
type MyEnum string
const (
    MyEnumA MyEnum = "A"
    MyEnumB MyEnum = "B"
    MyEnumB MyEnum = "C"
)
type MyObjectSpec {
  // 
   // +kubebuilder:validation:Enum=A,B,C
   Mode MyEnum
}
```

## Alternative Three
No kubebuilder comment. 
*does not work*
 User might assume that when you use the Go idiom for an enum that the OpenAPI is inferred.  It isn't.

```
type MyEnum string
const (
    MyEnumA MyEnum = "A"
    MyEnumB MyEnum = "B"
    MyEnumB MyEnum = "C"
)
type MyObjectSpec {
   Mode MyEnum
}
```

## Alternative Four 
Kubebuilder comment and no Go enum idiom 
*works but no static checking in go*
```
type MyObjectSpec {
  // 
   // +kubebuilder:validation:Enum=A,B,C
   Mode string
}
```

/kind documentation

**Comment by DirectXMan12** [comment]
> Does not work. They seem to cancel out

Err... that's a bug

/kind bug

**Comment by DirectXMan12** [comment]
/good-first-issue

on the docs

help wanted on the cancelling out bug.  I'm guessing that our allof resolution logic has a bug.  Start by adding a unit test (`It("should preserve validation when both the field and the type have the same validation")`) and go from there.

**Comment by djzager** [comment]
Looking into the doc portion of this issue it appears that this is already laid out in [Generating CRDs](https://book.kubebuilder.io/reference/generating-crd.html). Specifically, the [section concerning validation](https://book.kubebuilder.io/reference/generating-crd.html#validation) shows the _correct_ way to do this (shortened for simplicity):

```go
type ToySpec struct {
...
	Alias   Alias   `json:"alias,omitempty"`
	Rank    Rank    `json:"rank"`
}

// +kubebuilder:validation:Enum=Lion;Wolf;Dragon
type Alias string
```

**Comment by djzager** [comment]
> help wanted on the cancelling out bug. I'm guessing that our allof resolution logic has a bug. Start by adding a unit test (`It("should preserve validation when both the field and the type have the same validation")`) and go from there.

Maybe this hsould be an issue against https://github.com/kubernetes-sigs/controller-tools ? I don't see anything in kubebuilder related to that, but [searching for `allof` in controller-tools](https://github.com/kubernetes-sigs/controller-tools/search?q=allof&unscoped_q=allof) leads me to believe this should be addressed there.

@DirectXMan12 what do you think?
