### ISSUE TITLE
Recipe for Singleton

### ISSUE THREAD

**Issue by erictune** [kubernetes-sigs/kubebuilder#1074]
I'm sharing a recipe for how to make a singleton with KubeBuilder as of v2.0.1

---
Sometimes you only want to allow a single CR of a controller to exist.
For example, you might want to configure a controller that does things for the whole cluster and there should only be one configuration "file", and CRDs make nice configuration "files".

CRDs allow using validation on `.metadata.name` and `.metadata.namespace`.

For KubeBuilder, if you want to patch the generated CRD, you can do so by adding a new kustomize patch.  Here is how to do that.

```
$ cd $KBPROJECT
# Create this file
$ cat > config/crds/patches/singleton.yaml <<EOF
# The following patch make a CRD be a "singleton".
# Only one CR can be created because validation restricts the value of
# name and namespace.
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: guestbooks.webapp.kubernetic.solutions
spec:
  validation:
    openAPIV3Schema:
      properties:
        metadata:
          properties:
            name:
              type: string
              pattern: "default"
            namespace:
              type: string
              pattern: "REPLACE_WITH_CONTROLLER_NAMESPACE"
EOF
$ kustomize edit add patch config/crds/patches/singleton.yaml
```

When a user tries to create a CR with the wrong name or namespace, they see an error like this:
```
$ kubectl create -f config/samples/group_v1_kind.yaml
The Kind "wrongname" is invalid: <long string>:   validation failure list:
metadata.name in body should match 'default'
metadata.namespace in body should match 'controller-ns'
$
```

* You need to replace "REPLACE_WITH_CONTROLLER_NAMESPACE" with the namespace that you will tell your users to install the controller in. 
* Unfortunately, they won't be able to change this easily.
* If you have multiple CRDs, this patch will affect them all.
* You could also do this with a validation webhook.

---

/kind feature
/kind documentation

**Comment by DirectXMan12** [comment]
Let's add a recipes section to the book for stuff like this.

Adding this in, with a recipe, is a 

/good-first-issue

**Comment by amila-ku** [comment]
i would like to work on this issue.

**Comment by DirectXMan12** [comment]
sounds good!

**Comment by camilamacedo86** [comment]
Hi @amila-ku, 

Please feel free to help on any issue. Just `assign to you` by adding a comment here with `/assign <yourusername>` and submit a PR.  :-)

**Comment by evalsocket** [comment]
Would like to work on this. Can this be assigned to me ? @camilamacedo86

**Comment by camilamacedo86** [comment]
Hi @evalsocket , 

Very cool. :-)  Just do the PR and put /assign @youruser in a comment in this issue that the bot will do that. You will see the instructions in the PR to assign it to a person. It is done here at the same way.

**Comment by evalsocket** [comment]
@camilamacedo86 where do you want that Recipe any specific place ?

**Comment by camilamacedo86** [comment]
Hi @evalsocket,

I do not know. Would be required check in the docs where it would fit better.

**Comment by tiraboschi** [comment]
Hi,
please notice that according to bullet #1 in https://github.com/kubernetes/enhancements/blob/master/keps/sig-api-machinery/20190425-structural-openapi.md#metadata
only `name` and `generateName` metadata properties can be restricted but not the `namespace` so enforcing this kind of restriction will result in a CRD with NonStructuralSchema condition:
```
  - lastTransitionTime: "2020-03-25T15:59:04Z"
    message: 'spec.validation.openAPIV3Schema.properties[metadata]: Forbidden: must
      not specify anything other than name and generateName, but metadata is implicitly
      specified'
    reason: Violations
    status: "True"
    type: NonStructuralSchema
```

**Comment by errordeveloper** [comment]
I think the underlying API should really support singleton CRDs, seems like it would be sensible to have two modes - cluster-wide and per-namespace, but having something in kubebuilder would be a great start!

**Comment by KnicKnic** [comment]
I would like to leave 3 pieces of feedback. @erictune  it would be great for you to include them in your example

1. Enable the CRD at the cluster scope `spec.scope: Cluster` in which namespace does not matter. 
2. Pattern is a regexp, you need to specify start and end tokens. `^default$"
3. You should make name field required, to indicate people cant use generateName 
    1. Not sure if this is needed, as during test it seems generateName still happens and it fails pattern match of name

this leads to the following yaml instead the original top one
```yaml
# The following patch make a CRD be a "singleton".
# Only one CR can be created because validation restricts the value of
# name and namespace.
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: guestbooks.webapp.kubernetic.solutions
spec:
  scope: Cluster
  validation:
    openAPIV3Schema:
      properties:
        metadata:
          properties:
            name:
              type: string
              pattern: "^singleton$"
          required:
          - name
```
