### ISSUE TITLE
Incorrect documentation on webhook order

### ISSUE THREAD

**Issue by ekuefler** [kubernetes-sigs/kubebuilder#1075]
According to https://kubebuilder.io/reference/markers/webhook.html:

> Mutating webhooks are allowed to change the object in their response, and are called *after* all validating webhooks.

According to https://kubernetes.io/docs/reference/access-authn-authz/extensible-admission-controllers/:

> Mutating admission Webhooks are invoked first, and can modify objects sent to the API server to enforce custom defaults. After all object modifications are complete, and after the incoming object is validated by the API server, validating admission webhooks are invoked and can reject requests to enforce custom policies.

/kind documentation

**Comment by DirectXMan12** [comment]
good catch!  Can you file a pr?

**Comment by ekuefler** [comment]
I poked around and actually couldn't find where in github the book was stored. Can you point me at it?

**Comment by DirectXMan12** [comment]
docs/book/src

**Comment by DirectXMan12** [comment]
https://github.com/kubernetes-sigs/kubebuilder/tree/master/docs/book/src

**Comment by DirectXMan12** [comment]
See also https://github.com/kubernetes-sigs/kubebuilder/blob/master/netlify.toml

**Comment by ekuefler** [comment]
Ah, it imports from controller-tools godocs, that's why I was having trouble searching for it. https://github.com/kubernetes-sigs/controller-tools/pull/341.
