### ISSUE TITLE
Structured-merge-diff support

### ISSUE THREAD

**Issue by erictune** [kubernetes-sigs/kubebuilder#1081]
I want KubeBuilder to support these comment tags:
```
// +listMapKey=XXX
// +listType=atomic
// +listType=set
// +listType=map
```

These are supported by https://github.com/kubernetes/kube-openapi (see [here](https://github.com/kubernetes/kube-openapi/blob/master/pkg/generators/extension_test.go) ) and I believe they are supported by Server-side apply for CRDs in 1.16.

KubeBuilder should be able to emit these properties when generating CRDs.

Related issues:
  - Documentation request for these tags: https://github.com/kubernetes/website/issues/16725
  - Issue about checking what happens if a CRD is updated to add these tags after the fact: https://github.com/kubernetes-sigs/structured-merge-diff/issues/115

Requires 1.16

/kind feature

**Comment by erictune** [comment]
Note that uses who are currently referring to code which uses these tags already, such as in pod templates within custom controllers, will see a change to their generated CRD when they upgrade their KubeBuilder version.  

Need to determine how to explain this to users.

To do that, need to understand what will happen.
 kubernetes-sigs/structured-merge-diff#115 is about that.

**Comment by DirectXMan12** [comment]
Does the actual desierialization of CRD validation schemas support it yet?  IIRC, that was the blocker.

**Comment by apelisse** [comment]
I think it's been done in 1.16. Let me double-check that.

**Comment by apelisse** [comment]
https://github.com/kubernetes/kubernetes/pull/77354

**Comment by apelisse** [comment]
Specifically: https://github.com/kubernetes/kubernetes/pull/77354/files#diff-ca188b89d2fc7104865fe95be2114e81

**Comment by apelisse** [comment]
cc @jenny

**Comment by jennybuckley** [comment]
Yes. This is done in 1.16 so this is no longer blocked

**Comment by DirectXMan12** [comment]
cool, we should cross-file on CT then

**Comment by droot** [comment]
I am wondering how we can do a better job of educating the users about using these markers when they use a list in their API definition. One idea that comes to mind is some sort of `linter` command in `controller-tools` that give tips to users when we encounter a field of list-type that doesn't have these markers specified.

**Comment by apelisse** [comment]
(btw, I'm working on the implementation right now)
/assign

Yes, I'm trying to look at the documentation holistically right now, there are lots of gaps in that area. Making it obvious to CRD authors that this is a thing would help by calling out this specifically in CRD docs (I'm also working on this). 

A fairly obvious way to make a linter is to find specific patterns (@pwittrock already used that principle) like search for lists that have a field `name`, etc. You could also search for `map[string]substructure` which is another common pattern. I'm clearly not opposed to the idea.

**Comment by apelisse** [comment]
This was absolutely fixed by https://github.com/kubernetes-sigs/controller-tools/pull/347
