### ISSUE TITLE
Is it possible to watch a Pod which is not created by my controller?

### ISSUE THREAD

**Issue by functicons** [kubernetes-sigs/kubebuilder#1082]
In my controller, I want Reconcile to be triggered by the status change of a Pod which is not created directly by my controller. Is this possible?

More details: my controller creates a Job, which in turn create the Pod I want to watch. The reason is that Pod status is not fully reflected in Job status, when the Pod is Pending for scheduling (maybe never get scheduled), the Job is already considered as Running. That is why I want to watch the Pod to get more accurate information about the job.

/triage support

**Comment by DirectXMan12** [comment]
Yes, that's possible.  You just need to use the `Watch` method on the builder (if you're using that, or just a normal watch if you're using the low-level controller interface directly) with a custom mapper using a [mapper func](https://godoc.org/sigs.k8s.io/controller-runtime/pkg/handler#EnqueueRequestsFromMapFunc) that reads the owner of the pod, finds that job, and then reads the owner of the job.

Closing for now, LMK if you need more details.
