### ISSUE TITLE
Error `common.sh: line 160: kind: command not found` is faced  when run `make test-project-generation` in a  MacOsX

### ISSUE THREAD

**Issue by camilamacedo86** [kubernetes-sigs/kubebuilder#1089]
Following the issue. 

```
$ make test-project-generation
./test.sh
preparing staging dir
fetching tools
x kubebuilder/
x kubebuilder/bin/
x kubebuilder/bin/etcd
x kubebuilder/bin/kubectl
x kubebuilder/bin/kube-apiserver
building kubebuilder
setting up env vars
common.sh: line 160: kind: command not found
```

/kind bug

**Comment by DirectXMan12** [comment]
huh, does fetch-tools not fetch kind?

cc @mengqiy

**Comment by mengqiy** [comment]
No. We do it in https://github.com/kubernetes-sigs/kubebuilder/blob/c54566abca4299edc5d23b2c4f1388104b782db9/scripts/install_and_setup.sh#L19

**Comment by mengqiy** [comment]
https://github.com/kubernetes-sigs/kubebuilder/blob/c54566abca4299edc5d23b2c4f1388104b782db9/Makefile#L39-L40

`./test.sh` should not need a kind cluster, only `./test_e2e.sh` needs one.

**Comment by camilamacedo86** [comment]
Really thank you to share your knowledge with too.  
But it was running locally @mengqiy.
