### ISSUE TITLE
mixed up between camelCase and PascalCase in kind validation

### ISSUE THREAD

**Issue by Azadehkhojandi** [kubernetes-sigs/kubebuilder#1091]
There is typo/bug in the validation message => mixed up between camelCase and PascalCase

`kubebuilder create api --group databricks --version v2beta1 --kind testKind`

The error says camelcase but what is expected is PascalCase
> kind must be camelcase (expected TestKind was testKind)

reference:
https://blogs.msdn.microsoft.com/brada/2004/02/03/history-around-pascal-casing-and-camel-casing/
https://stackoverflow.com/questions/41768733/camel-case-and-pascal-case-mistake

**Comment by DirectXMan12** [comment]
you are technically correct (and well sourced), which is the best kind of correct :-D

/kind bug
/good-first-issue
/priority backlog

**Comment by vishakhanihore** [comment]
@DirectXMan12 Can you point me to the file location ?

**Comment by KaenDagger** [comment]
Could I take up this issue to get started ?

**Comment by Adirio** [comment]
@mariantalla should this be closed by #1133 which just got merged?

**Comment by mariantalla** [comment]
Yep, with #1133 now merged, this should be fixed. `Kind`s are still expected to start with an uppercase character, but the error message should be clearer now.

/close

**Comment by rayudu-gangadhara-rao** [comment]
jhsfjhsdv
