### ISSUE TITLE
Update certmanager to v0.11

### ISSUE THREAD

**Issue by detiber** [kubernetes-sigs/kubebuilder#1093]
Update certmanager to v0.11, to avoid future issues with deploying certmanager once k8s blocks deployment of CRDs using api groups under `k8s.io` 

/kind feature

**Comment by mengqiy** [comment]
Certmanager renamed their API group from `certmanager.k8s.io` to `cert-manager.io`.
That means the manifests we currently generated doesn't work with v0.11 :(

We have to point out in our document that old project need to either update the API group name or using an older certmanager release.

**Comment by detiber** [comment]
The downside to not upgrading to v0.11 is that certmanager will fail to deploy on Kubernetes v1.17+ clusters due to new restrictions on registering CRDs with a *.k8s.io api group.

**Comment by lawrencegripper** [comment]
Is someone working on changes? Was going to look at a PR to fixup. I'll push a draft PR for now and can always remove it it's not useful.
