### ISSUE TITLE
Ignoring Status update for Reconcile requeue

### ISSUE THREAD

**Issue by champak** [kubernetes-sigs/kubebuilder#1103]
I want to avoid re-queueing for CRD Status changes. I saw the issue discussed on #618 but was not clear if we have a succinct resolution. There was a suggestion on using Predicate functions but werent predicate functions considered too low level for kubebuilder operators ?

**Comment by DirectXMan12** [comment]
You can use GenerationChangedPredicate for this.  They're not too low level, you just have to be careful how you use them.
