### ISSUE TITLE
We shouldn't scaffold with raw function literals in zap construction

### ISSUE THREAD

**Issue by DirectXMan12** [kubernetes-sigs/kubebuilder#1105]
Filing this to keep track of it before the release.

See the comment on https://github.com/kubernetes-sigs/kubebuilder/pull/1101

**Comment by camilamacedo86** [comment]
Hi @DirectXMan12, 

I understand that the PR: https://github.com/kubernetes-sigs/kubebuilder/pull/1116 solves this issue as well. Am I right?
