### ISSUE TITLE
Scaffold .dockerignore instead of using COPY many times in scaffolded Dockerfile

### ISSUE THREAD

**Issue by micnncim** [kubernetes-sigs/kubebuilder#1109]
/kind feature

The current scaffolded `Dockerfile` executes `COPY` many times.

https://github.com/kubernetes-sigs/kubebuilder/blob/885f36ec9e61eca21499bda9815f6b0b907dffe6/pkg/scaffold/v2/dockerfile.go#L50-L53

However, for developer experience, it will be useful to scaffold `.dockerignore` and `COPY . .` once because the developers may add some go packages or files, or change the paths, and then forget to add `COPY pkg/ pkg/` to the scaffolded `Dockerfile`.

I hope `kubebuilder` to do this. And if this proposal is accepted, I'll create a PR.

**Comment by Adirio** [comment]
There is a **very small** drawback to bear in mind, a single `COPY . .` would mean there is a single layer, so any change in any file would make Docker unable to use previously cached layers, while multiple `COPY` commands may benefit from it if the change is in further layers.

But I do think it is a good feature.

**Comment by DirectXMan12** [comment]
Is that any change in any file, even ignored ones?  If so, that's mainly why we haven't done this so far.

**Comment by micnncim** [comment]
I see. As @Adirio said, it's inconvenient not to use cache for each unchanged packages.

Thank you for your opinion 😇
