### ISSUE TITLE
Detect duplicate api creation commands

### ISSUE THREAD

**Issue by Adirio** [kubernetes-sigs/kubebuilder#1110]
Executing two times the same `kubebuilder create api ...` with the same group, version and kind did not recognize that it was already in the project. I'm not sure if the changes done to some of the generated files will stay after the second execution of the command, as it was a fresh start. But what I do know is that 3 files got duplicated code:

- `PROJECT`: `resources` lists the GVK twice
- `main.go`: `SetupWithManager` called twice
- `controllers/suite_test.go`: `AddToScheme` checked twice

I expected either an error message telling me that that GVK already exists or a warning that asks me if I want to reset that GVK to the default.

To reproduce:
```
kubebuilder init --my.domain
kubebuilder create api --group mygroup --version v1alpha1 --kind Example
kubebuilder create api --group mygroup --version v1alpha1 --kind Example
```

Versions:
- Golang: `go version go1.12.3`
- kubebuilder: `Version: version.Version{KubeBuilderVersion:"unknown", KubernetesVendor:"unknown", GitCommit:"$Format:%H$", BuildDate:"1970-01-01T00:00:00Z", GoOs:"unknown", GoArch:"unknown"}`
- Scaffolding: `version: "2"`
- controller-runtime: `v0.2.2`
- controller-tools: `v0.2.1`
- Kubernetes: `v1.14.6`
- kubectl: `v1.14.6`

/kind bug

**Comment by DirectXMan12** [comment]
This is a bug.  Sine we track `resources` in PROJECT, we can error out on this (and probably have a force flag to override the error out).

/help
/good-first-issue

**Comment by camilamacedo86** [comment]
HI, could you please assign the issue to you in order to avoid other dev get it since you gave a PR already one for this one? Also, devs will usually filter for the unassigned ones to know what they can do to contribute with.

**Comment by Adirio** [comment]
> HI, could you please assign the issue to you in order to avoid other dev get it since you gave a PR already one for this one? Also, devs will usually filter for the unassigned ones to know what they can do to contribute with.
> 
> PS.: To do it just add a new comment with `/assign @your user`

@hypnoglow
