### ISSUE TITLE
Are reconcile requests for the same CR executed sequentially?

### ISSUE THREAD

**Issue by functicons** [kubernetes-sigs/kubebuilder#1112]
Sometimes, when updating the status of my CR, I got the error "the object has been modified; please apply your changes to the latest version and try again". I am trying to figure out the cause. Wondering are reconcile requests for the same CR executed sequentially or could be concurrently?

/triage support

**Comment by functicons** [comment]
Seems it is, I checked the code of controller-runtime, by default there is only one worker.

**Comment by xm5646** [comment]
I have the same problem as you ,  some resouce modify trigger the reconciler, and some of update operation with error : 

"Operation cannot be fulfilled on deployments.apps \"wsgw-web\": the object has been modified; please apply your changes to the latest version and try again

if only on worker ,why is this happening?

**Comment by yunkunrao** [comment]
I have encoutered the same situation when developed crd. Does anybody know how to fix it?

**Comment by keenJR** [comment]
Hi boy, I have the same problem, How to solve the problem？

**Comment by du86796922** [comment]
@functicons Hello Big Brother, Has this problem been solved after that?

**Comment by xm5646** [comment]
try set which you need the resource  ResourceVersion to a null string， the error was not found again.

**Comment by xm5646** [comment]
i guess that，while you reconciling the resource，the resource was updated by other controller，the resource version was bigger than the version you got ，. Therefore, k8s will not apply an expired version.

**Comment by keshin** [comment]
I had ran into same situation, and I guess it because some cache issue when I return 
`ctrl.Result{Requeue: true}` which put it in queue immediately, so I changed it to `ctrl.Result{RequeueAfter: time.Second}` and the issue is gone.

**Comment by cheng1li** [comment]
In my env, this happens when I run two controller instances ( one runs in a pod by `make deploy`, and the other is run by `make run`).

**Comment by helloxjade** [comment]
I also encountered a similar issue. "name":"image-describe","namespace":"heros-us
er"}, "namespace": "heros-user", "name": "image-describe", "reconcileID": "0dd05b6b-1e4d-42be-ab64-3b6bc7b44b37", "error": "Operation cannot be fulfilled on servers.sy.hedd.ai "image-describe": StorageError: in
valid object, Code: 4, Key: /registry/sy.hedd.ai/servers/heros-user/image-describe, ResourceVersion: 0, AdditionalErrorMsg: Precondition failed: UID in precondition: c8e7ef3b-cdf8-4e3c-a725-f42dc4a61568, UID in o
bject meta: "}, It seems that this issue has not been resolved yet. Can someone tell me what's going on? I have no clue, and sometimes during reconciliation, the same state is reconciled twice, but there are no error messages, and requeue is also false. It feels very strange.
