### ISSUE TITLE
Is there a way to create events for your CRDs?

### ISSUE THREAD

**Issue by ivelichkovich** [kubernetes-sigs/kubebuilder#1117]
Is there a way to create events on your CRDs? I don't mean lifecycle events but rather events like these

LAST SEEN   TYPE     REASON              OBJECT                        MESSAGE
8m39s       Normal   Scheduled           pod/nginx-554b9c67f9-jpz4z    Successfully assigned default/nginx-554b9c67f9-jpz4z to ip-172-24-0-6
8m37s       Normal   Pulling             pod/nginx-554b9c67f9-jpz4z    Pulling image "nginx"
8m31s       Normal   Pulled              pod/nginx-554b9c67f9-jpz4z    Successfully pulled image "nginx"
8m31s       Normal   Created             pod/nginx-554b9c67f9-jpz4z    Created container nginx
8m31s       Normal   Started             pod/nginx-554b9c67f9-jpz4z    Started container nginx
8m39s       Normal   SuccessfulCreate    replicaset/nginx-554b9c67f9   Created pod: nginx-554b9c67f9-jpz4z
8m39s       Normal   ScalingReplicaSet   deployment/nginx              Scaled up replica set nginx-554b9c67f9 to 1

Is there a supported or even hack way of doing this?

/triage support

**Comment by functicons** [comment]
Yes, simply create event resource with event recorder, see example of `createStatusChangeEvent` in Flink Operator [1] and [2].

[1]: https://github.com/GoogleCloudPlatform/flink-on-k8s-operator/blob/2e8743819ddb18c79727cbf04fa607721bce220e/controllers/flinkcluster_controller.go#L71
[2]: https://github.com/GoogleCloudPlatform/flink-on-k8s-operator/blob/2e8743819ddb18c79727cbf04fa607721bce220e/controllers/flinkcluster_updater.go#L155

**Comment by camilamacedo86** [comment]
HI @ivelichkovich, 

Shows that this issue is sorted already. Am I right? If yes, could you please close this one? If not, could you please let us know what is missing for we are able to close it. 

Really tks.
