### ISSUE TITLE
Update scheme handling in the book

### ISSUE THREAD

**Issue by Adirio** [kubernetes-sigs/kubebuilder#1118]
# What do you want to happen?
[Section 1.7.1](https://book.kubebuilder.io/cronjob-tutorial/main-revisited.html) of the book claims that we need to add `k8s.io/api/batch/v1` to the scheme as we are using `Job`s. `k8s.io/client-go/kubernetes/scheme` already does that for us. Update that part to explain that we do not need to add builtin types but we do need to add new types.

/kind documentation

**Comment by Adirio** [comment]
I can submit a PR if the issue gets the aproval of some contributors.

**Comment by camilamacedo86** [comment]
HI @Adirio, 

Could you please add the link of this part of doc here?

**Comment by Adirio** [comment]
@camilamacedo86 Sure!

https://book.kubebuilder.io/cronjob-tutorial/main-revisited.html

**Comment by DirectXMan12** [comment]
yes, please submit a PR for that.

**Comment by camilamacedo86** [comment]
Hi @Adirio, 

Could you please assign it to you since you did the PR for that?
