### ISSUE TITLE
Triggering reconcile on CRD attribute updates

### ISSUE THREAD

**Issue by champak** [kubernetes-sigs/kubebuilder#1121]
Hi folks,
Do we need explicit watch() invocations for causing reconcile to get invoked when a (non-primitive type) CRD spec attribute changes on a CRD ? e.g. If I have
type FooSpec struct {
....
   BarAttr int   `json:"barAttr"`
..
}

And then  
- create a CRD 
- update the value of barAttr and reapply the YAML

I do not see reconcile getting triggered. For k8 native types like PersistentVolumeClaim that are part of FooSpec I do see reconcile triggered. I am wondering if we need explicit watch() for attributes to get updated for changes. Thanks !

**Comment by droot** [comment]
Didn't understand
> Do we need explicit watch() invocations 

Assuming your type is `Foo`, you need to watch `Foo` type to get reconciliation triggered for Foo type.

**Comment by champak** [comment]
Yes Foo is the type/Schema and I would have something on the lines of:
// Foo is the Schema for the foos API
type Foo struct {
	metav1 ......
	Spec   FooSpec   `json:"spec,omitempty"`
	Status FooStatus `json:"status,omitempty"`
}

I was assuming kubebuilder does an implicit watch for Foo objects. I (reconcile..) do get notified when Foo Crds are created or deleted and rbac is setup for it e.g.
//+kubebuilder:rbac:groups=chat.foobar.com,resources=foos,verbs=get;list;watch;create;update;patch;delete

However I do not seem to get reconcile invocations if I write an update (via kubectl ) to an instance of a Foo CRD. Did I need to do anything else to get reconcile calls on updates ? Thanks.

**Comment by champak** [comment]
Located an issue in my code. Closing.
