### ISSUE TITLE
Golden script for Windows

### ISSUE THREAD

**Issue by Adirio** [kubernetes-sigs/kubebuilder#1126]
`./generate_golden.sh` does not work under Windows.

I tried to do some modifications to make the script work in windows, like using `bash ...` instead of `./...` notation and converting all paths to Windows style (including `$PWD` and `$(pwd)` outputs). But I stopped when I saw it was downloading some tools that are only for darwin and linux.

/kind feature

**Comment by camilamacedo86** [comment]
HI @Adirio, 

I have not a Windows system. However, the problem shows that would be solved if we add as pre-requirement use the https://www.cygwin.com/ to work within the windows. 

c/c @joelanford @estroz

**Comment by camilamacedo86** [comment]
Closed in favor of : https://github.com/kubernetes-sigs/kubebuilder/issues/2940
