### ISSUE TITLE
Fire `reconcile()` on a timer?

### ISSUE THREAD

**Issue by cflewis** [kubernetes-sigs/kubebuilder#1131]
Hi there,
I have a controller that I'd like to poll to update a status field inside `reconcile()`, and not just trigger as a result of a custom resource changing.

I thought about requeueing the job at the end of `reconcile()` even when things are successful, but then the work queue would increase for every change to any of the custom resources, eventually leading to the queue exploding.

Is there a way to fire `reconcile()` on a timer, or otherwise inspect the work queue to ensure you only place the job into it one at a time?

/triage support

**Comment by droot** [comment]
[Channel source](https://godoc.org/github.com/kubernetes-sigs/controller-runtime/pkg/source#example-Channel) is the mechanism to trigger reconciler based on some custom logic or based on an external dependency.

**Comment by cflewis** [comment]
Awesome, thank you.

Where would I place this logic? During `SetupWithManager()` on the controller?

**Comment by droot** [comment]
Yes, in controller's `SetupWithManager()`, call `Build` instead of `Complete()` to get the handle of `controller` and then call `controller.Watch` with the channel source.

**Comment by cflewis** [comment]
Thanks!

**Comment by shafeeqes** [comment]
> `SetupWithManager()`, call `Build` instead of `Complete()` to get the handle of `controller` and then call `controller.Watch`

Can you please elaborate?

> Yes, in controller's `SetupWithManager()`, call `Build` instead of `Complete()` to get the handle of `controller` and then call `controller.Watch` with the channel source.
