### ISSUE TITLE
Deprecate v1 projects

### ISSUE THREAD

**Issue by droot** [kubernetes-sigs/kubebuilder#1136]
v2 project structure has been out for a while now. We should deprecate v1 projects and eventually (3 months later) drop the support. It will reduce the maintenance burden of v1 projects.
So as a first step, we should start displaying warning indicating `v1 projects are deprecated` and encourage users to migrate to v2 projects whenever they run KB commands on a v1 project.

**Comment by hypnoglow** [comment]
Hi, I would be glad to help with this. 

Do we have a specific date of sunsetting v1 (so we can specify it in the deprecation output)?

**Comment by Adirio** [comment]
> Do we have a specific date of sunsetting v1 (so we can specify it in the deprecation output)?

droot said 3 months later. Start time should be the first release that includes the warning, so I guess you could say something broad such as "during the first 2020 quarter".

**Comment by DirectXMan12** [comment]
I'd imagine we'd do "print warning for a while, then drop in the next release after a specified date"
