### ISSUE TITLE
Error in the scaffold files when the group name has '.'

### ISSUE THREAD

**Issue by ctiml** [kubernetes-sigs/kubebuilder#1138]
Hello, I'm trying to create apis using kubebuilder v2.1.0 and I got this error message:

```
$ kubebuilder create api --group example.com --version v1alpha1 --kind Foobar

package controllers

import (
        "context"

        ctrl "sigs.k8s.io/controller-runtime"
        "sigs.k8s.io/controller-runtime/pkg/client"
        "github.com/go-logr/logr"
        "k8s.io/apimachinery/pkg/runtime"

        example.comv1alpha1 "test/api/v1alpha1"
)

// FoobarReconciler reconciles a Foobar object
type FoobarReconciler struct {
        client.Client
        Log logr.Logger
        Scheme *runtime.Scheme
}

// +kubebuilder:rbac:groups=example.com.,resources=foobars,verbs=get;list;watch;create;update;patch;delete
// +kubebuilder:rbac:groups=example.com.,resources=foobars/status,verbs=get;update;patch

func (r *FoobarReconciler) Reconcile(req ctrl.Request) (ctrl.Result, error) {
        _ = context.Background()
        _ = r.Log.WithValues("foobar", req.NamespacedName)

        // your logic here

        return ctrl.Result{}, nil
}

func (r *FoobarReconciler) SetupWithManager(mgr ctrl.Manager) error {
        return ctrl.NewControllerManagedBy(mgr).
                For(&example.comv1alpha1.Foobar{}).
                Complete(r)
}

2019/10/29 14:52:52 error scaffolding controller: controllers/foobar_controller.go:26:9: expected 'STRING', found '.' (and 4 more errors)
```

`example.comv1alpha1 "test/api/v1alpha1"` is not valid import alias.

I think this is a follow-up issue of https://github.com/kubernetes-sigs/kubebuilder/pull/1049. It should be replaced when group name has '.' (dot).

go version: go1.13.3 darwin/amd64
kubebuilder version: v2.1.0

/kind bug

**Comment by droot** [comment]
@ctiml This has not been an issue for most Kubebuilder users. Can you share what do you want the API Group for the CRD to look like ? 

For ex.  if the API group we want is `apps.example.com` with Foobar kind in it, we will begin the Kubebuilder project with domain `example.com` by running `kubebuilder init --domain example.com`. And then we add new API by running `kubebuilder create api --group apps --kind Foobar --version v1alpha1`.

Hope this helps.

**Comment by ctiml** [comment]
@droot Thanks for reply.

Our original requirement is to make API Group to be `example.com`, without the subdomain.
We'd love to have the group like `crd.example.com` but we're dealing with our legacy CRDs whose group is set to `example.com`.

There are three ways to do this:
- empty domain name: (`--domain "" --group "example.com"`) failed, results in `example.com.`
- empty group name: (`--domain "example.com" --group ""`) failed, group is a required field.
- workaround: (`--domain "com" --group "example"`). This is the only thing working for us, but this looks strange.

Is there any better way to achieve this? Thanks.

**Comment by Adirio** [comment]
As you already realized, the workaround would be using `com` as the domain and `example` as the group. That would leave a pretty strange GVK (`example`, `v1alpha1`, `Foobar`) but should work out of the box.

The empty domain case you said, fails as the group name followed by the version is used as an alias to import the API, so no dots are allowed. In case you also replace dots in group names as it was done with dashes in the PR you linked, you would still have the issue with the full api version being `example.com./v1alpha1` (note the extra dot).

From a conceptual point of view, the empty group name would be the best option. Kubebuilder does not support this. In the builtin groups, the empty group name is an alias to `core`. IMO, I would not consider this a bug, but s a feature request for empty group names.

**Comment by DirectXMan12** [comment]
we could maybe also support replacing unexpected characters in import paths or something -- it's really just an issue for generating import aliases.

**Comment by camilamacedo86** [comment]
/assing @camilamacedo86 

The solution is done here: https://github.com/kubernetes-sigs/kubebuilder/pull/1172
c/c @DirectXMan12 @droot @ctiml

**Comment by ctiml** [comment]
@Adirio It would be good to support empty group name.
@camilamacedo86 Thanks for fixing the issue.

**Comment by Adirio** [comment]
@camilamacedo86 linked PR above solves the issue with the `.` character in group names but be aware that it will still result in `example.com.` (notice the final `.`) as the domain is being set to the empty string.
