### ISSUE TITLE
kubebuilder version "unknown"

### ISSUE THREAD

**Issue by kevdowney** [kubernetes-sigs/kubebuilder#1141]
/kind bug

`kubebuilder version` returns "unknown" for version and other build keys. 
```bash
Version: version.Version{KubeBuilderVersion:"unknown", KubernetesVendor:"unknown", GitCommit:"$Format:%H$", BuildDate:"1970-01-01T00:00:00Z", GoOs:"unknown", GoArch:"unknown"}
```

* Note: I downloaded this from homebrew: `brew install kubebuilder`
* Downloading release for mac seems to be ok.
```
kubebuilder version
Version: version.Version{KubeBuilderVersion:"2.1.0", KubernetesVendor:"1.15.5", GitCommit:"51b536013c61d87b19e0d3e1d498c4ff3db5bbcf", BuildDate:"2019-10-28T18:25:11Z", GoOs:"unknown", GoArch:"unknown"}
```

**Comment by DirectXMan12** [comment]
We don't maintain the homebrew version.  ping @cblecker or on the homebrew issue tracker.

They'd have to set the appropriate linker flags when building -- that's where the version information comes from.

**Comment by cblecker** [comment]
@DirectXMan12 the formula is just running a `make build`: https://github.com/Homebrew/homebrew-core/blob/master/Formula/kubebuilder.rb#L26

Where are the linker flags being set in your regular release process?

**Comment by DirectXMan12** [comment]
They're listed here: https://github.com/kubernetes-sigs/kubebuilder/blob/master/build/.goreleaser.yml#L6
