### ISSUE TITLE
Extract Resource from the v1 Scaffolding package

### ISSUE THREAD

**Issue by Adirio** [kubernetes-sigs/kubebuilder#1144]
The `Resource` type is being used by both scaffolding versions, but it is placed inside v1, which is missleading. Furthermore, v1 scaffolding is being deprecated (#1136, #1137).

Shouldn't this package be extracted to the root scaffolding package?

/kind feature

**Comment by DirectXMan12** [comment]
yeah, it should be.  cc #1133, in which I think there was confusion about this
