### ISSUE TITLE
Remove duplicated scaffold API validation code

### ISSUE THREAD

**Issue by Adirio** [kubernetes-sigs/kubebuilder#1145]
[`API.Validate()`](https://github.com/kubernetes-sigs/kubebuilder/blob/master/pkg/scaffold/api.go#L60-L68) is reimplementing part of the [`Resource.Validate()`](https://github.com/kubernetes-sigs/kubebuilder/blob/master/pkg/scaffold/v1/resource/resource.go#L57-L65) functionality. Shouldn't it just call the `Resource.Validate()` method?

/kind bug

**Comment by camilamacedo86** [comment]
This change I need to do here #1163 to solve another issue raised by you. Do you mind in close the PR #1146 and we keep all there?

**Comment by Adirio** [comment]
@camilamacedo86 I don't really think you need this to be closed (by 1146) for the `MarkFlagRequired` approach. They should be complimentary changes. In case you need it,1146 should get merged soon and you will be able to rebase your commits.

**Comment by camilamacedo86** [comment]
@Adirio I thought that I removed already my previous comment. I changed the fix and it is no longer fixing it.

**Comment by Adirio** [comment]
Thank you very much.
