### ISSUE TITLE
How to generate client code in v2 version

### ISSUE THREAD

**Issue by Ghostbaby** [kubernetes-sigs/kubebuilder#1152]
Hi,
kubebuilder V1 version use this command to generate client code:
```vendor/k8s.io/code-generator/generate-groups.sh all github.com/ghostbaby/test/pkg/client github.com/ghostbaby/test/pkg/apis database.v1beta1``` 

But How to generate client code in v2 version?

/triage support

**Comment by camilamacedo86** [comment]
HI @Ghostbaby,

It shows exactly the same scenario of https://github.com/kubernetes-sigs/kubebuilder/issues/488. `Do you mind sharing reasons for using the generated client over the one provided by controller-runtime ?`

**Comment by DirectXMan12** [comment]
We don't support generating clients in kubebuilder

**Comment by DirectXMan12** [comment]
you might be able to restructure your project to use the upstream client-gen, but we have no intention of supporting it.

**Comment by Ghostbaby** [comment]
Hi @camilamacedo86 ,
In our environment, our operator needs to be called by other applications, either a management platform or another operator, so we need to provide a client.

**Comment by camilamacedo86** [comment]
Hi @Ghostbaby, 

I still not thinking that a client needs to be provided to achieve this need.  

When you say `our operator needs to be called by other applications` I understand that other applications will "install/uninstall" the operator according to some business requirements. Then, it can be done in many ways, and I'd recommend you use the Makefile targets to achieve it. E.g other applications will exec the command `make install` to apply all resources in the cluster. 

Note that the go-client in the operator project will be used for your operator call the k8s API in order to create/delete/updated/read resources on the cluster. So, I cannot see how it could allow external systems to do calls to the operator itself.

**Comment by DirectXMan12** [comment]
I think @Ghostbaby means they need a Go client, not OLM-style dependency resolution, because other things need to operate on the types.

**Comment by bowei** [comment]
Is there an issue/doc to explain why the generated client was removed?

**Comment by stigsb** [comment]
@Ghostbaby I have a super hacky workaround for generating client from another project that uses kubebuilder v2 at https://gitlab.com/zedge-oss/zeppa/taxman/blob/master/hack/update-client.sh

This approach also locks the version of the code generator.

**Comment by alexeldeib** [comment]
This is in the migration guide, FWIW: https://github.com/kubernetes-sigs/kubebuilder/blob/master/docs/migration_guide.md#copy-and-update-reconcile-function

Is there a reason people want to generate typed clients over using the dynamic client provided by controller-runtime? I find it is much better to work with: https://godoc.org/sigs.k8s.io/controller-runtime/pkg/client#example-Client--Update

**Comment by bowei** [comment]
Generated clients have static, compile-time types and are easier for the consumer-side to deal with.

**Comment by alexeldeib** [comment]
I'm not sure I understand the distinction you're making? You're basically just saying you want the go types to be known at compile time, which is equally true for what I'm suggesting people do? e.g.:

```go
import (
        "log"
        corev1 "k8s.io/api/core/v1"
	ctrl "sigs.k8s.io/controller-runtime"
	"k8s.io/apimachinery/pkg/runtime"
	clientgoscheme "k8s.io/client-go/kubernetes/scheme"
        "sigs.k8s.io/controller-runtime/pkg/client"

        yourCRDScheme "some/import/path"
)
scheme := runtime.New()
_ = clientgoscheme.AddToScheme(scheme)
_ = yourCRDScheme.AddToScheme(scheme)

kubeconfig := ctrl.GetConfigOrDie()
kubeclient, err := client.New(kubeconfig, client.Options{ Scheme: scheme })
if err != nil {
        log.Fatal(err)
}

# replace with some yourCRDScheme type here
var pod corev1.Pod
err = c.Get(context.Background(), client.ObjectKey{
    Namespace: "namespace",
    Name:      "name",
}, &pod)
```

This is fairly similar with the generated code linked by @stigsb, except users no longer need a clientset per type. So if they are already using any sort of k8s client, they can just add the compile-time types to their scheme and save *enormous* amounts of boilerplate generated code.

Does that address your point, or am I misunderstanding?

**Comment by howardjohn** [comment]
One downside for informers is the dynamic client will store things as Unstructured, so when we do List() calls we need to do conversions, which has a large cost. With generated clients the cache stores the object already marshaled which is much more efficient as it happens only once. The alternative,as far as I can tell, is implementing a cache outside of the informer which is error prone

**Comment by shenlanse** [comment]
I want to write one comandLine tool  and do some read/write operator on custom resource. I think `controller-runtime client` is not sufficent. As far as i know(maybe wrong), `controller-runtime client`  will start list-watch background and cache all objects of resource what i do get/list, also APIReader only support `read` operation. 

@DirectXMan12 @camilamacedo86  How can I implement commandLine tool, use which client? Thanks.

**Comment by shenlanse** [comment]
> I want to write one comandLine tool and do some read/write operator on custom resource. I think controller-runtime client is not sufficent. As far as i know(maybe wrong), controller-runtime client will start list-watch background and cache all objects of resource what i do get/list, also APIReader only support read operation.

@DirectXMan12 @camilamacedo86 Any suggestion? Thanks.

**Comment by ryandawsonuk** [comment]
FWIW I’ve tried to capture all the details of migrating from a ClientSet to controller-runtime client in this article[Watch any CRD](https://hackernoon.com/platforms-on-k8s-with-golang-watch-any-crd-0v2o3z1q)

**Comment by gtracer** [comment]
> > I want to write one comandLine tool and do some read/write operation on custom resource. I think controller-runtime client is not sufficent. As far as i know(maybe wrong), controller-runtime client will start list-watch background and cache all objects of resource what i do get/list, also APIReader only support read operation.
> 
> @DirectXMan12 @camilamacedo86 Any suggestion? Thanks.

It looks like client.New(kubeconfig, client.Options{ Scheme: scheme }) actually doesn't set up watches or use caching for get/list. It just sets up a client that directly reads/writes to the apiserver

**Comment by DmitriGekhtman** [comment]
I haven't done a detailed investigation, but `client.New()` seems to take a few seconds to run in my cluster. 
This caused me to consider trying to generate a clientset, but I've given up on that for now.
Any ideas on how to diagnose or mitigate slow controller runtime client initialization?

**Comment by DmitriGekhtman** [comment]
Ok - now, I understand --

A concrete downside of using controller-runtime's client is that, by default, initializing it requires making a call to the API server to get available API resources and instantiate a DynamicRESTMapper. This adds some startup latency to any program that needs access to the client. This latency will depend on the load on the API server.

**Comment by thesuperzapper** [comment]
To help people that stumble across this issue wondering if they should generate a clientset for their CRDs when using Kubebuiler, my recommendation is no.

This is because the recommended way for users to consume CRDs in Go apps is now to use the [`client.Client`](https://pkg.go.dev/sigs.k8s.io/controller-runtime/pkg/client) from [`controller-runtime`](https://github.com/kubernetes-sigs/controller-runtime) (even outside of Kubebuilder apps).

This then lets you simply import the generated CRD interface types from the Kubebuilder app, and you also get the benefit of being able to use [`cache.Cache`](https://pkg.go.dev/sigs.k8s.io/controller-runtime/pkg/cache) if you want to avoid making requests to the Kubernetes API, at the expense of caching them in memory using a ListWatch.

**Comment by thesuperzapper** [comment]
So that people have an example to work from to use `controller-runtime` to manage an app that is not a controller, here is a modified version of what we are doing in Kubeflow Notebooks 2.0's backend API, a Go-based HTTP API which interacts with Kubernetes, but is not a controller.

To see our full code, go to the `kubeflow/notebooks` repo on the [`notebooks-v2` branch under `./workspaces/backend/`](https://github.com/kubeflow/notebooks/tree/notebooks-v2/workspaces/backend).

# Example Code

This is for an HTTP API, but you can manage any other kind of Go app, it just needs to implement [`manager.Runnable`](https://pkg.go.dev/sigs.k8s.io/controller-runtime/pkg/manager#Runnable), like the following `server.Server` does.

## Outer Main

The outer part of your app might look like this.

We are still using the [`manager.Manager`](https://pkg.go.dev/sigs.k8s.io/controller-runtime/pkg/manager#Manager) object to manage the lifecycle of the app. However, we are adding our own non-controller HTTP `server.Server` object which implements [`manager.Runnable`](https://pkg.go.dev/sigs.k8s.io/controller-runtime/pkg/manager#Runnable) interface:

```go
package pkg

import (
	"github.com/envoyproxy/go-control-plane/pkg/server/v3"
	"k8s.io/apimachinery/pkg/runtime"
	clientgoscheme "k8s.io/client-go/kubernetes/scheme"
	"log/slog"
	"os"
	ctrl "sigs.k8s.io/controller-runtime"
	metricsserver "sigs.k8s.io/controller-runtime/pkg/metrics/server"
)

func main() {
	logger := slog.New(slog.NewTextHandler(os.Stdout, nil))
	restConfig := ctrl.GetConfigOrDie()
	scheme := runtime.NewScheme()

	// add default Kubernetes types to the scheme
	if err := clientgoscheme.AddToScheme(scheme); err != nil {
		logger.Error("failed to add Kubernetes types to scheme", "error", err)
		os.Exit(1)
	}
	// add your custom types to the scheme
	//if err := XXXXv1beta1.AddToScheme(scheme); err != nil {
	//	logger.Error("failed to add XXXX types to scheme", "error", err)
	//	os.Exit(1)
	//}

	ctrlOpts := ctrl.Options{
		Scheme: scheme,
		Metrics: metricsserver.Options{
			BindAddress: "0", // not required, just for example
		},
		HealthProbeBindAddress: "0",   // not required, just for example
		LeaderElection:         false, // not required, just for example
	}

	// create a new manager
	mgr, err := ctrl.NewManager(restConfig, ctrlOpts)
	if err != nil {
		logger.Error("unable to create manager", "error", err)
		os.Exit(1)
	}

	// create your app instance
	// NOTE: see the following snippet for a possible implementation
	//       for the purpose of the following example, the only assumption is that
	//       `app` will implement a method called Routes() that returns an http.Handler
	//app, err := myapp.NewApp(cfg, logger, mgr.GetClient(), mgr.GetScheme())
	//if err != nil {
	//	logger.Error("failed to create app", "error", err)
	//	os.Exit(1)
	//}

	// create your server instance
	// NOTE: see the following snippet for a possible implementation
	svr, err := server.NewServer(app, logger)
	if err != nil {
		logger.Error("failed to create server", "error", err)
		os.Exit(1)
	}
	if err := svr.SetupWithManager(mgr); err != nil {
		logger.Error("failed to setup server with manager", "error", err)
		os.Exit(1)
	}

	// start the manager
	logger.Info("starting manager")
	err = mgr.Start(ctrl.SetupSignalHandler())
	if err != nil {
		logger.Error("unable to start manager", "error", err)
		os.Exit(1)
	}
}
```

## Server

Here is an example of what the `server.Server` object might look like from above, its main requirement is that it implements [`manager.Runnable`](https://pkg.go.dev/sigs.k8s.io/controller-runtime/pkg/manager#Runnable) (e.g. has `Start()` method which blocks until it's context is closed).

```go
package server

import (
	"context"
	"errors"
	"fmt"
	"log/slog"
	"net"
	"net/http"
	"time"

	ctrl "sigs.k8s.io/controller-runtime"
)

type Server struct {
	logger   *slog.Logger
	listener net.Listener
	server   *http.Server
}

func NewServer(app *myapp.App, logger *slog.Logger) (*Server, error) {
	port := 1234 // in the real world, read this from your `app` config
	listener, err := net.Listen("tcp", fmt.Sprintf(":%d", port))
	if err != nil {
		return nil, fmt.Errorf("failed to create listener: %w", err)
	}

	svc := &http.Server{
		Addr:              fmt.Sprintf(":%d", port),
		Handler:           app.Routes(),     // app.Routes() is a function that returns an http.Handler
		IdleTimeout:       90 * time.Second, // matches http.DefaultTransport keep-alive timeout
		ReadTimeout:       32 * time.Second,
		ReadHeaderTimeout: 32 * time.Second,
		WriteTimeout:      32 * time.Second,
		ErrorLog:          slog.NewLogLogger(logger.Handler(), slog.LevelError),
	}
	svr := &Server{
		logger:   logger,
		listener: listener,
		server:   svc,
	}

	return svr, nil
}

// SetupWithManager sets up the app with a controller-runtime manager
func (s *Server) SetupWithManager(mgr ctrl.Manager) error {
	err := mgr.Add(s)
	if err != nil {
		return err
	}
	return nil
}

// Start starts the server
// Blocks until the context is cancelled
func (s *Server) Start(ctx context.Context) error {
	serverShutdown := make(chan struct{})
	go func() {
		<-ctx.Done()
		s.logger.Info("shutting down server")
		if err := s.server.Shutdown(context.Background()); err != nil {
			s.logger.Error("error shutting down server", "error", err)
		}
		close(serverShutdown)
	}()

	s.logger.Info("starting server", "addr", s.server.Addr)
	if err := s.server.Serve(s.listener); err != nil && !errors.Is(err, http.ErrServerClosed) {
		return err
	}

	<-serverShutdown
	return nil
}

// NeedLeaderElection returns false because this app does not need leader election from the manager
func (s *Server) NeedLeaderElection() bool {
	return false
}
```

## Inner App

For clarity, here is a toy HTTP app which could be used with the above examples:

```go
package myapp

import (
	"fmt"
	"log/slog"
	"net/http"

	"github.com/julienschmidt/httprouter"
	"k8s.io/apimachinery/pkg/runtime"
	"sigs.k8s.io/controller-runtime/pkg/client"
)

const (
	PathPrefix = "/api/v1"

	// healthcheck
	HealthCheckPath = PathPrefix + "/healthcheck"
)

type App struct {
	Config MY_CONFIG_TYPE
	logger *slog.Logger
	Scheme *runtime.Scheme
	Client client.Client
}

// NewApp creates a new instance of the app
func NewApp(cfg MY_CONFIG_TYPE, logger *slog.Logger, client client.Client, scheme *runtime.Scheme) (*App, error) {

	app := &App{
		Config: cfg,
		logger: logger,
		Scheme: scheme,
		Client: client, // this is a controller-runtime client
	}
	return app, nil
}

// Routes returns the HTTP handler for the app
func (a *App) Routes() http.Handler {
	router := httprouter.New()

	router.GET(HealthCheckPath, a.HealthcheckHandler)

	return a.RecoverPanic(router)
}

// HealthcheckHandler returns the healthcheck status of the app
func (a *App) HealthcheckHandler(w http.ResponseWriter, r *http.Request, _ httprouter.Params) {
	w.WriteHeader(http.StatusOK)
	w.Write([]byte("OK")) // in a real app, this would be a JSON response and handle the error
}

// RecoverPanic recovers from panics and returns a 500 status code
func (a *App) RecoverPanic(next http.Handler) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		defer func() {
			if err := recover(); err != nil {
				w.Header().Set("Connection", "close")
				w.WriteHeader(http.StatusInternalServerError)
				w.Write([]byte(fmt.Sprintf("panic: %v", err)))
			}
		}()

		next.ServeHTTP(w, r)
	})
}
```

**Comment by Adembc** [comment]
> If someone wants to write this into a blog or something, please do, and link it here!
@thesuperzapper I’ve written a [blog](https://adembc.medium.com/kubernetes-access-in-go-choosing-controller-runtime-manager-for-non-controller-apps-2e211cd8111f) post about this topic.
