### ISSUE TITLE
Empty argument for create api command prints wrong error

### ISSUE THREAD

**Issue by Adirio** [kubernetes-sigs/kubebuilder#1153]
As reported by @camilamacedo86 in https://github.com/kubernetes-sigs/kubebuilder/pull/1146#pullrequestreview-311425585, when issuing a `dockerbuilder create api ...` command with an empty value for a command line argument that is not at the end, the error reported does not describe the error properly.

<details><summary><code>$ kubebuilder create api --group webapp --version  --kind Guestbook</code></summary><pre>Create Resource [y/n]
y
Create Controller [y/n]
y
2019/11/05 08:31:42 missing kind information for resource</pre></details>

<details><summary><code>$ kubebuilder create api --group webapp --kind  --version Guestbook</code></summary><pre>Create Resource [y/n]
y
Create Controller [y/n]
y
2019/11/05 08:44:55 missing version information for resource</pre></details>

/kind bug

**Comment by DirectXMan12** [comment]
interesting

/help

**Comment by Adirio** [comment]
I think this may have to do with https://github.com/spf13/cobra

**Comment by debojitkakoti** [comment]
@Adirio So, just need to change the command description for users to use '=' in command or pre-checking arguments ? What is your suggestion? Because it seems like intended behavior in cobra.

**Comment by camilamacedo86** [comment]
/assing @camilamacedo86 

The issue occurs because when we pass --group --version it will set the "--version" as value to the group. I am doing a PR to fix it.
