### ISSUE TITLE
Unable to get info by running kubebuilder version

### ISSUE THREAD

**Issue by camilamacedo86** [kubernetes-sigs/kubebuilder#1154]
**What did you do?**

Try to get use kubebuilder version by using the master branch/source code.

- clone the project
- run `make install`
- run `kubebuilder version`

**What did you expect to see?**

The info based on the version used. E.g as it done when we use SDK and master branch.

```
$ operator-sdk version
operator-sdk version: "v0.12.0-5-g9bc2d204", commit: "9bc2d204564cc6b8883f511b7f4f3f6efa901764", go version: "go1.13.3 darwin/amd64"
```

**What did you see instead? Under which circumstances?**

```
$ kubebuilder version
Version: version.Version{KubeBuilderVersion:"unknown", KubernetesVendor:"unknown", GitCommit:"$Format:%H$", BuildDate:"1970-01-01T00:00:00Z", GoOs:"unknown", GoArch:"unknown"}
```

/kind bug

**Comment by DirectXMan12** [comment]
the version info comes from link-time flags set in our release process.  This is expected if you don't download an official release.
