### ISSUE TITLE
kubebuilder update command broken for v2

### ISSUE THREAD

**Issue by luisdavim** [kubernetes-sigs/kubebuilder#1155]
kubebuilder v2 uses go mods but the `kubebuilder update` command just generates a `Gopkg.toml` file and from the version constraint's there it seems it's for the previous version

I would expect the `go.mod` file to be updated with the new version constraints.

* go version
  `go1.13.4 darwin/amd64`
* kubebuilder version (`kubebuilder version`) and scaffolding version (check your `PROJECT` file)
  ```
  Version: version.Version{KubeBuilderVersion:"2.1.0", KubernetesVendor:"1.15.5", GitCommit:"51b536013c61d87b19e0d3e1d498c4ff3db5bbcf", BuildDate:"2019-10-28T18:25:11Z", GoOs:"unknown", GoArch:"unknown"}
  ```
  scaffolding version: `v1`

/kind bug

**Comment by DirectXMan12** [comment]
cc #1136 I think we might just want to error out on this command

**Comment by luisdavim** [comment]
If you're not going to support this command for v2 what should be the update process between minor versions?

**Comment by Adirio** [comment]
`v2` scaffold is based on go.mod, you would just use the normal `go mod` tool

**Comment by luisdavim** [comment]
If I started with kubebuilder v2.0.0 how do I know what versions to select to use kubebuilder v2.1.0?

**Comment by Adirio** [comment]
An easy eay to find out would be creating a test project with 2.1.0 and watch the generated go.mod file.

**Comment by luisdavim** [comment]
Yeah but don't you think it would make sense for kubebuilder to be able to update the go.mod file instead of having to create a new project and copy over the file?

**Comment by Adirio** [comment]
The problem is that you may have changed the scaffolded go.mod file and by doing that you may loose user made changes.

**Comment by luisdavim** [comment]
That's a good point, but kubebuilder could be smart about it and only update it's own dependencies and leave the rest of the file as is

**Comment by johanneswuerbach** [comment]
ember-cli provides a new project diff with each release, which I found fairly helpful when updating between versions.

Example https://github.com/ember-cli/ember-cli/releases/tag/v3.14.0 > Blueprint Changes https://github.com/ember-cli/ember-new-output/compare/v3.13.2...v3.14.0

**Comment by DirectXMan12** [comment]
In theory, `kubebuilder update` has been replaced with `go get -u sigs.k8s.io/controller-runtime` (and similar for controller-tools).  We could have `kb update` do that, but I'm kinda tempted to just say that we want to encourage users to understand how go modules work and just document that.
