### ISSUE TITLE
Use sigs.k8s.io/yaml over gopkg.in/yaml.v2

### ISSUE THREAD

**Issue by christopherhein** [kubernetes-sigs/kubebuilder#1166]
Kubebuilder currently uses the `gopkg.in/yaml.v2` libraries for parsing `ProjectFiles`, since there is already a `sigs.k8s.io/yaml` which is a fork of `yaml.v2` potentially we can reduce the use of outside packages by using that instead.

/kind feature

**Comment by christopherhein** [comment]
https://github.com/kubernetes-sigs/kubebuilder/pull/1167 implements this.

**Comment by Adirio** [comment]
Just a small note: as you can see above your comment, GitHub already noted that 1167 will close this issue, no need to write down an extra comment for that :)

**Comment by christopherhein** [comment]
> Just a small note: as you can see above your comment, GitHub already noted that 1167 will close this issue, no need to write down an extra comment for that :)

Yup, just making sure it's documented, I've filed issues before and implemented them only to find someone didn't read those updates and also implemented it. :)
