### ISSUE TITLE
kubebuilder-init fails if KB v2.1.0 is used (KB v2.0.1 works fine)

### ISSUE THREAD

**Issue by juanjoku** [kubernetes-sigs/kubebuilder#1170]
I'm just initializing a new project, using KB v2.1.0.
But kubebuilder-init command fails while go-getting to controller-runtime@v3.0.0.

But: KB v2.0.1 works fine.

Steps to reproduce the problem

```
$ go version
go version go1.12.13 linux/amd64

# Creates a new directory and initialize a go project
$ mkdir my-controller
$ cd my-controller/
$ go mod init my-controller

# Initializes a project
$ kubebuilder init --domain mydomain.io
[...]
go get sigs.k8s.io/controller-runtime@v0.3.0
# sigs.k8s.io/controller-runtime/pkg/client/apiutil
/home/myuser/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.3.0/pkg/client/apiutil/apimachinery.go:77:30: undefined: serializer.DirectCodecFactory
2019/11/09 20:44:34 exit status 2
```
/kind bug

**Comment by camilamacedo86** [comment]
HI @mengqiy and @DirectXMan12,

We do not have this issue in the master. May a new release could solve it and could/should update the quick start to use go 1.13 as well which indeed shows that would make the user's life easier. WDYT?

**Comment by juanjoku** [comment]
Hello,

I have the issue... using the master too!!  
¿¿??

```
$ lsb_release -dr
Description:	Ubuntu 18.04.2 LTS
Release:	18.04

$ go version
go version go1.12.13 linux/amd64

$ kubebuilder version
Version: version.Version{KubeBuilderVersion:"master", KubernetesVendor:"1.15.5", GitCommit:"9eeec12fb5e3f02c351d809bc1dde106cfefcf26", BuildDate:"2019-11-08T21:26:32Z", GoOs:"unknown", GoArch:"unknown"}

$ mkdir example
$ cd example
$ go mod init example
go: creating new go.mod: module example

$ kubebuilder init --domain my.domain
go get sigs.k8s.io/controller-runtime@v0.3.0
# sigs.k8s.io/controller-runtime/pkg/client/apiutil
/home/myuser/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.3.0/pkg/client/apiutil/apimachinery.go:77:30: undefined: serializer.DirectCodecFactory
2019/11/10 16:20:49 exit status 2
```

I see a commit in version 2.1.0, which corrects precisely that issue:   https://github.com/kubernetes-sigs/kubebuilder/commit/da0298173907b9be0f4dac1218dfa9b68253e901 ... but it doesn't seem to fix the problem in my environment. 
I have tried to remove the controller-gen executable, to force its regeneration... but I still have the same failure.

Any ideas?

Thanks in advanced.

**Comment by camilamacedo86** [comment]
Hi @juanjoku, 

Could you please use the go version 1.13 and do not run `go mod init example` before the `kubebuilder init`? Following the test with master branch to ensure that all is working fine. 

<img width="854" alt="Screenshot 2019-11-10 at 16 56 09" src="https://user-images.githubusercontent.com/7708031/68547591-3a5b3b00-03db-11ea-9863-d0e16e6bdd97.png">

<img width="979" alt="Screenshot 2019-11-10 at 16 57 20" src="https://user-images.githubusercontent.com/7708031/68547596-4646fd00-03db-11ea-9df4-233de236e49b.png">

**Comment by dgkanatsios** [comment]
had the same issue, was using go 1.12.6. Upgraded to 1.13.3, had to run `go mod init` (wasn't required with 1.12.6) but after that everything worked fine. Thanks!

**Comment by juanjoku** [comment]
Hello @camilamacedo86 and @dgkanatsios,

As you indicated, if I use Go v1.13.4... it works fine :-) Thanks!

PS: Maybe incompatibilities with GO versions should be indicated in the documentation?

```
$ go version
go version go1.13.4 linux/amd64

$ kubebuilder version
Version: version.Version{KubeBuilderVersion:"2.1.0", KubernetesVendor:"1.15.5", GitCommit:"51b536013c61d87b19e0d3e1d498c4ff3db5bbcf", BuildDate:"2019-10-28T18:25:11Z", GoOs:"unknown", GoArch:"unknown"}

# Creates a new directory and initialize a go project
$ mkdir my-controller
$ cd my-controller/
$ go mod init my-controller

$ kubebuilder init --domain mydomain.coim
go get sigs.k8s.io/controller-runtime@v0.3.0
[...]
go build -o bin/manager main.go
Next: Define a resource with: kubebuilder create api

$ kubebuilder create api --group webapp --version v1 --kind Guestbook
Create Resource [y/n]
y
Create Controller [y/n]
y
Writing scaffold for you to edit...
api/v1/guestbook_types.go
controllers/guestbook_controller.go
Running make...
/home/myuser/go/bin/controller-gen object:headerFile=./hack/boilerplate.go.txt paths="./..."
go fmt ./...
go vet ./...
go build -o bin/manager main.go
```

**Comment by camilamacedo86** [comment]
Hi @juanjoku, 

Since the 1.3 is just required for the master branch it will be doc when the PR https://github.com/kubernetes-sigs/kubebuilder/pull/1168/files be merged in the CONTRIBUTION.md. The quick started and etc would be updated when a new release occurs based on the master.

**Comment by DirectXMan12** [comment]
closing since the above is merged
