### ISSUE TITLE
Unused exported functions removal

### ISSUE THREAD

**Issue by Adirio** [kubernetes-sigs/kubebuilder#1178]
Evaluate and remove non-needed exported functions or at least make them non-exported to reduce the API surface.

### Linter message:
> Unused exported function inspection

### Linter description:
> Reports unused exported functions.

Umbrella issue: #1176

/kind cleanup

**Comment by Adirio** [comment]
Before removing a function I will try to contact the author to verify it is not needed.

### `cmd/util/util.go`
@pwittrock The following functions were added with [this commit](https://github.com/kubernetes-sigs/kubebuilder/commit/0d2a3bd57a310f5e13f71263f9da21e92c7a0c7e) 2 years ago but seem to be no longer needed, could you take a look.
- `WriteIfNotFound`
- `Write`
- `WriteString`
- `GetCopyright`
- `create`
- `DoCmd`

@Liujingfang1 You added `IsProjectNotInitialized` in #317 but seems to be no longer needed.

**Comment by camilamacedo86** [comment]
HI, could you please assign the issue to you in order to avoid other dev get it since you gave a PR already one for this one? Also, devs will usually filter for the unassigned ones to know what they can do to contribute with. 

PS.: To do it just add a new comment with `/assign @your user`

**Comment by Liujingfang1** [comment]
> @Liujingfang1 You added IsProjectNotInitialized in #317 but seems to be no longer needed, could it be removed?

Yes, we can.
