### ISSUE TITLE
Package name as exported variable/type/function prefix removal

### ISSUE THREAD

**Issue by Adirio** [kubernetes-sigs/kubebuilder#1181]
Prefixing an exported variable/type/function with the package name is redundant as they will be called as `package.PackageType` and should be avoided.

Umbrella issue: #1176

/kind cleanup

**Comment by Adirio** [comment]
Requires #1186 and #1190 to be merged as they modify the same lines:

- `pkg/scaffold/v1/crd/crd_sample.go:39,51,55`
- `pkg/scaffold/v2/prometheus/monitor.go:15,23`
- `pkg/scaffold/v2/webhook/webhook.go:57,84,89`

**Comment by camilamacedo86** [comment]
HI, could you please assign the issue to you in order to avoid other dev get it since you gave a PR already one for this one? Also, devs will usually filter for the unassigned ones to know what they can do to contribute with. 

PS.: To do it just add a new comment with `/assign @your user`
