### ISSUE TITLE
Unification of receiver names

### ISSUE THREAD

**Issue by Adirio** [kubernetes-sigs/kubebuilder#1182]
### Linter message:
> Receiver has generic name inspection

### Lister description:
> Reports receiver names like me, this, self or different from other receiver names for this type.
> See [Code review comments: receiver names](https://github.com/golang/go/wiki/CodeReviewComments#receiver-names) for details.

Umbrella issue: #1176

/kind cleanup

**Comment by camilamacedo86** [comment]
HI, could you please assign the issue to you in order to avoid other dev get it since you gave a PR already one for this one? Also, devs will usually filter for the unassigned ones to know what they can do to contribute with. 

PS.: To do it just add a new comment with `/assign @your user`
