### ISSUE TITLE
Imports ordering

### ISSUE THREAD

**Issue by Adirio** [kubernetes-sigs/kubebuilder#1183]
### Linter message:
> Unsorted imports inspection

### Linter description:
> Reports unsorted imports.

### References:
- [Imports](https://github.com/golang/go/wiki/CodeReviewComments#imports)

Note: despite being the de facto standard, couldn't find a CodeReviewComments or Effective Go section that talks about the order of imports in each group, but you can see in the example how this rule is being followed.

Umbrella issue: #1176

/kind cleanup

**Comment by camilamacedo86** [comment]
HI, could you please assign the issue to you in order to avoid other dev get it since you gave a PR already one for this one? Also, devs will usually filter for the unassigned ones to know what they can do to contribute with. 

PS.: To do it just add a new comment with `/assign @your user`
