### ISSUE TITLE
Redundant type removal

### ISSUE THREAD

**Issue by Adirio** [kubernetes-sigs/kubebuilder#1188]
Redundancy at type conversion or construction should be avoided.

Umbrella issue: #1176

/kind cleanup

**Comment by camilamacedo86** [comment]
HI, could you please assign the issue to you in order to avoid other dev get it since you gave a PR already one for this one? Also, devs will usually filter for the unassigned ones to know what they can do to contribute with. 

PS.: To do it just add a new comment with `/assign @your user`
