### ISSUE TITLE
CI is broken because prow was changed and is looking for the wrong file

### ISSUE THREAD

**Issue by camilamacedo86** [kubernetes-sigs/kubebuilder#1191]
/kind bug

Following the Prow issue: 

`could not start the process: fork/exec ./test_e2e.sh: no such file or directory`

Note that the file which has been used by so far is: https://github.com/kubernetes-sigs/kubebuilder/blob/master/test_ci.sh and it was changed

**Comment by camilamacedo86** [comment]
c/c @DirectXMan12 @mengqiy @droot

**Comment by Adirio** [comment]
I was going to open a new issue so will just comment here instead:

# Description
PR are failing the `pull-kubebuilder-e2e` test with the following message:
```could not start the process: fork/exec ./test_e2e.sh: no such file or directory```

## Notes:
Some notes that may be relevant aside from what @camilamacedo86 already mentioned:
- The repository has two files with similar names (`test_e2e_v1.sh` and `test_e2e_v2.sh`) but no file with that name.
- #1107 renamed `test_e2e.sh` to `test_e2e_v1.sh`, but it may have leaked somewhere an old reference to that file.

### Example PR:
- #1143
- #1184
- #1185
- #1190

**Comment by camilamacedo86** [comment]
Hi @DirectXMan12 @mengqiy @droot

Note that the error `could not start the process: fork/exec ./test_e2e.sh: no such file or directory` we can solve but now it also is calling 2 jobs one for the tests_ci and other which shows to be for e2e. However, to run the e2e we need to create a specific setup since it cannot be as it is done for the Travis.  The #1151 may make things more clear.

**Comment by mengqiy** [comment]
pull-kubebuilder-e2e doesn't block PRs from merging.
@alexeldeib is working on using Prow for e2e testing.

**Comment by camilamacedo86** [comment]
Closing this one since the default check is solved and pull-kubebuilder-e2e was clarified.

**Comment by alexeldeib** [comment]
Sorry for the confusion, I should have held the test infra PR as well until the refactor in e2e was done. But as it is optional presubmit, it should not block PRs. It will look ugly though 🙁
