### ISSUE TITLE
Artefacts are not updated with the new version gen

### ISSUE THREAD

**Issue by camilamacedo86** [kubernetes-sigs/kubebuilder#1197]
## Feature Request

**Is your feature request related to a problem? Please describe.**

Artefacts are not updated with the new version gen. Following the steps to reproduce the scenario

```shell
$ mkdir $GOPATH/src/example
$ cd $GOPATH/src/example
$ kubebuilder init --domain my.domain
$ kubebuilder create api --group webapp --version v1 --kind Guestbook
$ kubebuilder create api --group webapp --version v2 --kind Guestbook
```
<img width="1146" alt="Screenshot 2019-11-14 at 11 03 58" src="https://user-images.githubusercontent.com/7708031/68853815-b94dbd80-06d2-11ea-90c0-1b566045e19e.png">

**Describe the solution you'd like**
I'd like to see the Artefacts updated to use the v2 when we press `y` to create Controller [y/n]

/kind feature

**Comment by DirectXMan12** [comment]
We generally don't update scaffolded files because we have no way to know if the user has significantly changed them.
