### ISSUE TITLE
Support same Kind for diff groups

### ISSUE THREAD

**Issue by camilamacedo86** [kubernetes-sigs/kubebuilder#1202]
**Description**

Currently, is not support multi-groups and/or the same kind for different groups. However, after the issue #923 be done multi groups will be supported and then, make sense it allows diff kinds if they are not from the same group. Following an example.  

mygroup.example/v1 - kind AppServer
mygroup2.example/v1 - kind AppServer

Since `mygroup.example/v1 ` is not the same api of `mygroup2.example/v1 ` shows that both could have a definition of an AppServer. 

**Proposal Solution**

Add the group in the controller path and scaffold the controller artefacts by the group. (`api/controller/<group>/<kind>_controller.go`)

PS.: In a small test that I did with the control-gen was not able to be executed. Required check further. 

/kind feature

**Comment by camilamacedo86** [comment]
Hi @DirectXMan12, 

Could you please check this one and let us know what do you think. The motivation for this change was identified when I was trying to collab by doing the PR for this one #923 raised by you. 

c/c @mengqiy @christopherhein

**Comment by DirectXMan12** [comment]
we'll have to take this into account for multi-group setups

**Comment by DirectXMan12** [comment]
but multi-group setups need a slightly different scaffolding anyway, so
/shrug

**Comment by mengqiy** [comment]
@camilamacedo86 Modified the description a bit, so that `<group>` and `<kind>` can show up :)

**Comment by camilamacedo86** [comment]
/assign @camilamacedo86 

Solved this in the PR: https://github.com/kubernetes-sigs/kubebuilder/pull/1198 with the solution suggested by @mengqiy
