### ISSUE TITLE
kubebuilder create api --group webapp --version v1 --kind Guestbook error

### ISSUE THREAD

**Issue by jacky-lk** [kubernetes-sigs/kubebuilder#1206]
kubebuilder version
Version: version.Version{KubeBuilderVersion:"2.1.0", KubernetesVendor:"1.15.5", GitCommit:"51b536013c61d87b19e0d3e1d498c4ff3db5bbcf", BuildDate:"2019-10-28T18:25:11Z", GoOs:"unknown", GoArch:"unknown"}

go version go1.13.4 darwin/amd64

when I exec "kubebuilder create api --group webapp --version v1 --kind Guestbook"

![image](https://user-images.githubusercontent.com/50770015/69007822-f689a800-097d-11ea-9fa3-603a5d6c46f6.png)

Error: not all generators ran successfully
2019/11/17 21:03:14 error running make: exit status 2

**Comment by camilamacedo86** [comment]
KubeBuilderVersion:2.1.0 is not supporting 1.13+. You need 1.12+ as described in the quickstarted. The go version 1.13+ will just work with the master branch.

**Comment by Vikash082** [comment]
Same issue on linux.

**Comment by camilamacedo86** [comment]
Hi @Vikash082, 

Did you have more than one go version installed?  Because go doesn't work very well if you have. 

Note that I am unable to reproduce it in Mac and the CI runs these commands in a Linux environment to check the project. So, it shows that is some issue with the local environment setup and not the project.

**Comment by Vikash082** [comment]
Hi @camilamacedo86 . I reinstalled go. But the result is same.

**Comment by Gsantomaggio** [comment]
I think you have some problem on your go installation, I tried with the following enviroment and it works without problems:

```
➜   go version
go version go1.13 darwin/amd64
➜   kubebuilder version
Version: version.Version{KubeBuilderVersion:"2.2.0", KubernetesVendor:"1.15.5", GitCommit:"0824a139f59e109c9e418a0b6e71a53c6e9e144f", BuildDate:"2019-11-20T00:00:24Z", GoOs:"unknown", GoArch:"unknown"}
```

Can you post the begining of the error?

**Comment by camilamacedo86** [comment]
Looking at your error, I think it is some module which is broken in your local env. Could you please try do the following steps. 

- Remove the bins in $GOPATH/bin
- Clean your go mod cache by:

```
$ export GO111MODULE=off
$ go clean --modcache
$ go clean
```

- Re-install kubebuilder
- Try again.

**Comment by DirectXMan12** [comment]
As @camilamacedo86 noted, this is generally caused by using a version of controller-tools that was not compiled with your go version.  Make sure to reinstall controller-tools after updating Go.
