### ISSUE TITLE
Homebrew does not install binary assets

### ISSUE THREAD

**Issue by blacksails** [kubernetes-sigs/kubebuilder#1210]
I couldn't run tests. Got an error because kubebuilder couldn't find etcd.
```
failed to start the controlplane. retried 5 times: fork/exec /usr/local/kubebuilder/bin/etcd: no such file or directory
```

I expected `make test` to work out of the box. This wasn't the case because I had installed kubebuilder using `brew`, which doesn't include the binary assets that `make test` needs.

I would like to see that the brew formula also installs the binary assets so that I can point to them using `KUBEBUILDER_ASSETS`. This could be done using `libexec.install` in the formula. The hard part is probably to port build of the third party binaries so that it works in `brew`.

/kind bug

**Comment by blacksails** [comment]
Also sorry if you would rather have me report this directly in the homebrew repo. I can repo the ticket there if you would prefer that.

**Comment by DirectXMan12** [comment]
Yes, please report this to the homebrew maintainers -- we don't directly maintain the homebrew build.

**Comment by franpog859** [comment]
Could you link the issue here?

**Comment by VoltBit** [comment]
> Could you link the issue here?

https://github.com/Homebrew/homebrew-core/issues/44175
