### ISSUE TITLE
Can create Mutating webhook for k8s native resource in v2?

### ISSUE THREAD

**Issue by quanguachong** [kubernetes-sigs/kubebuilder#1213]
/triage support

**Comment by quanguachong** [comment]
In kubebuilder v2,  you can create mutating webhook for custom resource `Sloop` using following cmd. It's convenient that you only need implement [method Default](https://github.com/kubernetes-sigs/controller-runtime/blob/198197fe0fd7553cadd8afcd3338f8ee4b8a7e3f/pkg/webhook/admission/defaulter.go#L30) for `Sloop`.

```bash
kubebuilder create webhook --kind=Sloop  --version=v1beta1 --defaulting
```

But, How to create mutating webhook for k8s native resource(for example: Pod)

**Comment by mengqiy** [comment]
> I find an example in controller-runtime, is this the best way to create mutating webhook for k8s native resource in kubebuilder v2?

Yes.
We currently doesn't scaffold webhooks for k8s native types.

**Comment by quanguachong** [comment]
Thanks
