### ISSUE TITLE
access to client in mutating webhook

### ISSUE THREAD

**Issue by ryandawsonuk** [kubernetes-sigs/kubebuilder#1216]
I'd like to use the manager's client to reference a configmap when validating my custom resource. But I can't see a way to pass the manager's client through to the webhook code (the [Defaulter](https://github.com/kubernetes-sigs/kubebuilder/blob/3b35bcbed5566b41e1e93e67d80b140c791afd4f/docs/book/src/cronjob-tutorial/testdata/project/api/v1/cronjob_webhook.go#L69)) when using the [`NewWebhookManagedBy` form](https://github.com/kubernetes-sigs/kubebuilder/blob/04c2341643978399570ed565724c98a19ef7935c/testdata/project-v2/api/v1/firstmate_webhook.go#L27):
```
func (r *FirstMate) SetupWebhookWithManager(mgr ctrl.Manager) error {
	return ctrl.NewWebhookManagedBy(mgr).
		For(r).
		Complete()
}
```
A [related question](https://github.com/kubernetes-sigs/kubebuilder/issues/1213) put me on to the [.Register form](https://github.com/kubernetes-sigs/controller-runtime/blob/v0.2.0/examples/builtins/main.go#L75) which I think would [let me pass down the manager's client](https://github.com/kubeflow/kfserving/blob/4240cdcd984a9b8f7c97ce715ac0a0535c50ad46/pkg/webhook/webhook.go#L114) to the code that would be triggered by the webhook. 

I might end up loading the configmap as an env var (I've [read you can do this](https://github.com/kubernetes-sigs/kubebuilder/issues/611) though can't find an example). But I'm wondering is it intended that the SetupWebhookWithManager doesn't let you use a client inside the webhook code? Or perhaps I'm missing something?

**Comment by ryandawsonuk** [comment]
Actually turns out [I don't need to do this anyway](https://github.com/SeldonIO/seldon-core/pull/1118/commits/17520cc47faeec7eb6fe1248f57eb68d8346ae32#diff-e35f762db386aef706a8b20d09081fb9R65)

**Comment by pires** [comment]
If that's what you really want, why not change your `FirstMate` and add a `Client` attribute to its struct, so that then you can...
```go
func (r *FirstMate) SetupWebhookWithManager(mgr ctrl.Manager) error {
    c := ctrl.NewWebhookManagedBy(mgr).
        For(r).
        Build()
    c.Client = mgr.GetClient()
    return nil
}
```

**Comment by ryandawsonuk** [comment]
Wouldn't the client then be an attribute on the custom resource ([FirstMate in this example case](https://github.com/kubernetes-sigs/kubebuilder/tree/04c2341643978399570ed565724c98a19ef7935c/testdata/project-v2/api/v1) and so be treated as part of the CRD and included in the generated CR definition?

**Comment by pires** [comment]
According to the snippet of code you pasted, `FirstMate` is the name of your controller/reconciler.

**Comment by pires** [comment]
Maybe something like...

```go
var (
    firstmatelog = logf.Log.WithName("firstmate-resource")
    client Client
)

func (r *FirstMate) SetupWebhookWithManager(mgr ctrl.Manager) error {
    client = mgr.getClient()

    return ctrl.NewWebhookManagedBy(mgr).
        For(r).
        Build()
}

var _ webhook.Defaulter = &Captain{}

// Default implements webhook.Defaulter so a webhook will be registered for the type
func (r *FirstMate) Default() {
    firstmatelog.Info("default", "name", r.Name)

    // TODO use client to read other resources
    client.Get(...)

    // TODO(user): fill in your defaulting logic.
}

**Comment by pires** [comment]
Do have in mind the `client` will need access to the scheme(s) of the type(s) you'll be interacting with.

**Comment by ryandawsonuk** [comment]
Yeah that approach works - https://github.com/SeldonIO/seldon-core/pull/1118/commits/0202671d8dec00a84b801151043576ba6a4bfdce#diff-e35f762db386aef706a8b20d09081fb9R99

**Comment by DirectXMan12** [comment]
If you need to use a client, I'd reccomend using the lower-level webhook machinery in `pkg/admission/webhook`.

**Comment by DirectXMan12** [comment]
e.g. https://github.com/kubernetes-sigs/controller-runtime/blob/master/examples/builtins/validatingwebhook.go

**Comment by DirectXMan12** [comment]
we really need an FAQ item on this

**Comment by mazzy89** [comment]
https://github.com/kubernetes-sigs/controller-runtime/issues/780 - I get an error doing this.

**Comment by mazzy89** [comment]
solved this. example in here https://github.com/kubernetes-sigs/controller-runtime/issues/780#issuecomment-578515689

**Comment by m-yosefpor** [comment]
What is the best way of doing this in 2021?

Should we do it with @pires solution or as @DirectXMan12 said, using lower level webhook? or is there any better alternative right now?

**Comment by strideynet** [comment]
> What is the best way of doing this in 2021?
> 
> Should we do it with @pires solution or as @DirectXMan12 said, using lower level webhook? or is there any better alternative right now?

I would suggest using the lower level webhooks ( see https://github.com/kubernetes-sigs/controller-runtime/blob/master/examples/builtins/mutatingwebhook.go )

**Comment by calebschoepp** [comment]
I recently ran into this issue. Here's how I solved it (note replace foo with your CR name):

`main.go`
```go
...
	if os.Getenv("ENABLE_WEBHOOKS") != "false" {
		if err = webhook.SetupFooWebhookWithManager(mgr); err != nil {
			setupLog.Error(err, "unable to create webhook", "webhook", "Foo")
			os.Exit(1)
		}
	}
...
```

`internal/webhook/admission.go`
```go
package webhook

import (
	foov1 "github.com/company/foo/api/v1"
	ctrl "sigs.k8s.io/controller-runtime"
)

func SetupFooWebhookWithManager(mgr ctrl.Manager) error {
	return ctrl.NewWebhookManagedBy(mgr).
		For(&foov1.Foo{}).
		WithDefaulter(&Foo{Client: mgr.GetClient()}).
		WithValidator(&FooValidator{Client: mgr.GetClient()}).
		Complete()
}
```

`internal/webhook/validating.go`
```go
package webhook

import (
	"context"

	foov1 "github.com/company/foo/api/v1"
	apierrors "k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/runtime"
	"k8s.io/apimachinery/pkg/runtime/schema"
	"k8s.io/apimachinery/pkg/util/validation/field"
	"sigs.k8s.io/controller-runtime/pkg/client"

	"sigs.k8s.io/controller-runtime/pkg/webhook/admission"
)

//+kubebuilder:webhook:path=/validate-foo-company-com-v1-foo,mutating=false,failurePolicy=fail,sideEffects=None,groups=foo.company.com,resources=foos,verbs=create;update,versions=v1,name=vfoo.kb.io,admissionReviewVersions=v1

// FooValidator validates Foos
type FooValidator struct {
	Client client.Client
}

// ValidateCreate implements webhook.Validator
func (v *FooValidator) ValidateCreate(ctx context.Context, obj runtime.Object) (admission.Warnings, error) {
	foo := obj.(*foov1.Foo)
	return nil, v.validateFoo(foo)
}

// ValidateUpdate implements webhook.Validator
func (v *FooValidator) ValidateUpdate(ctx context.Context, oldObj, newObj runtime.Object) (admission.Warnings, error) {
	foo := newObj.(*foov1.Foo)
	return nil, v.validateFoo(foo)
}

// ValidateDelete implements webhook.Validator
func (v *FooValidator) ValidateDelete(ctx context.Context, obj runtime.Object) (admission.Warnings, error) {
	return nil, nil
}

func (v *FooValidator) validateFoo(foo *foov1.Foo) error {
	// TODO: Your validation logic
	return nil
}
```

`internal/defaulting.go`
```go
package webhook

import (
	"context"

	foov1 "github.com/company/foo/api/v1"
	"k8s.io/apimachinery/pkg/runtime"
	"sigs.k8s.io/controller-runtime/pkg/client"
)

//+kubebuilder:webhook:path=/mutate-foo-company-com-v1-foo,mutating=true,failurePolicy=fail,sideEffects=None,groups=foo.company.com,resources=foo,verbs=create;update,versions=v1,name=mfoo.kb.io,admissionReviewVersions=v1

// FooDefaulter mutates Foos
type FooDefaulter struct {
	Client client.Client
}

// Default implements webhook.Defaulter
func (d *FooDefaulter) Default(ctx context.Context, obj runtime.Object) error {
	foo := obj.(*foov1.Foo)

	// TODO: Your default logic

	return nil
}
```
