### ISSUE TITLE
Resource validation for webhooks

### ISSUE THREAD

**Issue by KeisukeYamashita** [kubernetes-sigs/kubebuilder#1220]
## What

When I try to create API with invalid group name, it throws the error as expected.

```
# Expected Error(ok)
$ kubebuilder create api --group Treasury --version v1 --kind Secret
...
2019/11/24 21:27:09 error scaffolding APIs: group must match ^[a-z]+$ (was Treasury)
```

But for the Webhook, it doesn't throw error.

```
$ kubebuilder create webhook --group treasure --version v1 --kind Secret --defaulting  --programmatic-validation
=> No error
```

Since this happens, sometimes I create webhooks with wrong group name.

I want to ask that is this the expected behavior? Thank you.

/triage support

**Comment by Adirio** [comment]
The problem is that the webhooks may be for resources that are not created by kubebuilder, like builtin reosurces, manually created CRDs, or even by other tools.
