### ISSUE TITLE
How to pod interceptor in kubebuilder webhook?

### ISSUE THREAD

**Issue by withlin** [kubernetes-sigs/kubebuilder#1228]
i just want to interceptor k8s pod resource in kubebuilder webhook. so what should i do in kubebuilder?

**Comment by Adirio** [comment]
1. `kubebuilder init --domain=XXXXXXXXXX`: use the rest of the flags as needed (e.g. `--license` or `--owner`).
2. `kubebuilder create api --resource=false --controller=false --group=Core --version=v1 --kind=Pod`: use the rest of the flags as needed.
3. `kubebuilder create webhook --group=Core --version=v1 --kind=Pod ...`: extra flags will be needed here

**Comment by withlin** [comment]
Hi @Adirio It does not work.
![image](https://user-images.githubusercontent.com/22409551/69801896-420c4380-1213-11ea-8af8-be3090d0bc02.png)
![image](https://user-images.githubusercontent.com/22409551/69801914-4b95ab80-1213-11ea-9bcf-5ba45baac944.png)

**Comment by withlin** [comment]
Ref [issue1213](https://github.com/kubernetes-sigs/kubebuilder/issues/1213)
Not support native types.
Kuberbuilder version: 2.0 latest

**Comment by Adirio** [comment]
I see, you should probably raise a feature request issue to support webhooks for builting types and close this one as the answer by now is: "It can't be done"

Maybe it is possible to scaffold a wrapper around Pod that implements the webhook iterfaces.

**Comment by DirectXMan12** [comment]
If you just want a webhook that intercepts pods, I'd reccomend just using controller-runtime directly -- see https://github.com/kubernetes-sigs/controller-runtime/blob/master/examples/builtins/validatingwebhook.go for an example
