### ISSUE TITLE
GuestbookStatus struct redeclared in quickstart sample code

### ISSUE THREAD

**Issue by iredelmeier** [kubernetes-sigs/kubebuilder#1238]
The `GuestbookStatus` struct is currently declared twice in the sample code of the [Quick Start's Press Options section](https://github.com/kubernetes-sigs/kubebuilder/blob/696e8274156173403a50d319a7af7d0feed8f2ba/docs/book/src/quick-start.md#press-options):

```
// GuestbookStatus defines the observed state of Guestbook
type GuestbookStatus struct {
	// INSERT ADDITIONAL STATUS FIELD - define observed state of cluster
	// Important: Run "make" to regenerate code after modifying this file
	
	// GuestbookStatus is the set of Guestbook node specific statuses: Active or Standby
    GuestbookStatus GuestbookStatus `json:"guestbookStatus"`
    
    // Status of Guestbook Nodes
    Nodes []string `json:"nodes"`
}

type GuestbookStatus struct {

	// PodName of the active Guestbook node. 
	Active string `json:"active"`

	// PodNames of the standby Guestbook nodes.
	Standby []string `json:"standby"`
}	
```

I'm guessing that one declaration (the first?) should be renamed `Guestbook`?

/kind documentation

**Comment by DirectXMan12** [comment]
Something really weird is going on there.  It looks like a merge issue.  Indentation is also off.  Can you check the history and see when that got messed up?

The root guestbook should be something like (being a bit lazy here with the typing; and tabs):

```go
type GuestBook struct {
  // metadata here too
  Spec GuestbookSpec `json:"spec"`
  Status GuestbookStatus `json:"status"`
}
```

**Comment by iredelmeier** [comment]
Looks like the only relevant commit is the [initial one](https://github.com/kubernetes-sigs/kubebuilder/commit/a9860545bb0e6bb56fc4973423eca7fb36d6e08d#diff-e7f384593803dbfd8186105c2163ede5R75-R137).

In any case, it should be a pretty quick fix (famous last words 😅). Happy to submit a PR!
