### ISSUE TITLE
Document Prometheus setup and usage to export metrics

### ISSUE THREAD

**Issue by camilamacedo86** [kubernetes-sigs/kubebuilder#1244]
We change the previous set up in order to support the usage of Prometheus Operator, however, is missing doc it. All steps and information are in the PR: https://github.com/kubernetes-sigs/kubebuilder/pull/1030.

**Comment by mengqiy** [comment]
It seems these 2 pieces are no longer needed.
https://github.com/kubernetes-sigs/kubebuilder/blob/3ec07ea772fe1f392f37347b50c354d3b578f4bb/testdata/project-v2/config/default/kustomization.yaml#L29 and https://github.com/kubernetes-sigs/kubebuilder/blob/3ec07ea772fe1f392f37347b50c354d3b578f4bb/testdata/project-v2/config/default/kustomization.yaml#L35-L36

We need to cleanup comments in kustomization.yaml.

**Comment by camilamacedo86** [comment]
Thanks for point out the places @mengqiy

**Comment by mengqiy** [comment]
The code scoffolding `manager_prometheus_metrics_patch` won't be needed either.
