### ISSUE TITLE
Review tutorial to ensure that it has not outdated code

### ISSUE THREAD

**Issue by camilamacedo86** [kubernetes-sigs/kubebuilder#1251]
This task is tracked in order to follow up all tutorial steps and check if is all updated.
If something was changed then, we could update its steps.

**Comment by awgreene** [comment]
I'll be trying out controller-gen later this week and will be using the tutorials as a starting point, happy to update the docs as I go.

/assign

**Comment by awgreene** [comment]
Working on this now!
