### ISSUE TITLE
dynamically adaptable logging from kubebuilder

### ISSUE THREAD

**Issue by champak** [kubernetes-sigs/kubebuilder#1256]
Hi,
I am looking for a good pattern for logging from logic written into kubebuilder based opeators where we can change the logging level on the fly. Do not want to delve into the philosophical discussion on the number of log levels :) Lets assume there are a few and as is sometimes required for debugging production sw we may e.g. want to change the log level to "debug" without requiring a restart of the operator. Looked like kubebuilder uses go-logr/logr. I did not find a way to change the logging level on the fly with it. Generated logs could of course be filtered with various keys but was wondering what options exist if any for changing the logging level. Think logrus allows for setting the log level programmatically but not sure if we have the means for feeding in log (or any other..) flags to a running operator. If anyone has pointers on this please post. Thanks.

**Comment by DirectXMan12** [comment]
It depends on the *implementation* of logr -- logr is just an interface.  Zap allows this, I believe (see the AtomicLevel type in Zap).  Construct a Zap logger directly, wrap it with `go-logr/zapr`, and call `SetLogger` with that.

**Comment by kylehodgetts** [comment]
We did this, so here's an example if required (by anyone visiting this issue in and beyond 2022)

```
import (
        ...
	"github.com/go-logr/logr"
	"github.com/go-logr/zapr"
	"go.uber.org/zap"
	"go.uber.org/zap/zapcore"
	...
)
func initLogger(development bool, level string) (logr.Logger, error) {
	var l zapcore.Level
	if err := l.UnmarshalText([]byte(level)); err != nil {
		return logr.Logger{}, fmt.Errorf("unable to determine log level: %w", err)
	}

	var config zap.Config

	if development {
		config = zap.NewDevelopmentConfig()
	} else {
		config = zap.NewProductionConfig()
	}

	config.Level = zap.NewAtomicLevelAt(l)
	config.Development = development

	zapLogger, err := config.Build()
	if err != nil {
		return logr.Logger{}, fmt.Errorf("cannot create zap logger: %w", err)
	}

	return zapr.NewLogger(zapLogger), nil
}
```
