### ISSUE TITLE
Not able to `go build` with kubebuilder v2.2 

### ISSUE THREAD

**Issue by rishavcn** [kubernetes-sigs/kubebuilder#1259]
/kind bug

I am getting
`
knative.dev/pkg/metrics
../../pkg/mod/knative.dev/pkg@v0.0.0-20191203221237-94a34e416c44/metrics/stackdriver_exporter.go:128:3: unknown field 'GetMetricPrefix' in struct literal of type stackdriver.Options`

error on `go build` 

`
my
kubectl version - 1.14.8    
go version - 1.13.4
`

This version comes preinstalled with kubebuilder, I tried specifying a different version in go.mod but still getting the same error.

**Comment by droot** [comment]
@rishavcn can you share more context here. How did you create this project ? for ex. what steps did you run to get this error ?

**Comment by DirectXMan12** [comment]
We don't depend on knative or stackdriver in KB, and it's not in any of our go.sum files AFAICT.  I don't think this is a kubebuilder problem.
