### ISSUE TITLE
Option  provided in the create API cannot work

### ISSUE THREAD

**Issue by camilamacedo86** [kubernetes-sigs/kubebuilder#1263]
If we run `kubebuilder create api --group webapp --version v1 --kind Guestbook`

> resource=false
> controller=true

NOTE: It will not work since the controller requires the resource in the scaffold. (it is a bug in the master which should not allow this option)

/kind bug

**Comment by Adirio** [comment]
As i said in the comment in 1198, this is not a bug if the resource already exists, either manual creation or previous command with same GVK and `--resource=true --controller=false`

**Comment by camilamacedo86** [comment]
It is a bug because the option appears for the use and when we choose then an error is outputted. So, it is a problem regards usability and user POV. A possible solution is to handle the error and inform the user what and why and how instead of output its stack trace.

**Comment by Adirio** [comment]
You may want to get a controller without a resource for several reasons.

1- Builtin apis controllers. For example the `Namespace` controller that is being checked in the golden test. You do not need a resource as it is already defined in the k8s api. 
2- You already scaffolded the resource with `--controller=false` but you then realize you do need a controller. The resource is already there so that command is valid.
3- You used other tools to scaffold the resource or did it manually. Same as 2, the resource is already there so the command is valid.

For those cases, and probably more that I may be missing, controllers need to be possible to scaffold even with `--resource=false`.

**Comment by camilamacedo86** [comment]
Hi @Adirio, 

I think has some misunderstand here. 

Please, see the above description and try to reproduce the steps before contribute with. Note that if the user follow these steps an **ERROR** will be outputted. As described above, a valid solution in POV would handle the error and provide a msg to allow the user to knows how they should proceed.

**Comment by Adirio** [comment]
If you run `kubebuilder create api ... --resource false --controller true` in an empty new project, it may yield an error. Haven't tried it. If it does, you should include the error message in the first message of these Issue.

But we can't prevent the use of `--resource false --controller true` together as it may be useful if the resource was somehow created previously. For example by a previous `kubebuilder create api ... --resource true --controller false`.

That combination (`--resource false --controller true`) can also be used for builtin resources such as `Namespace`.

So we can't remove `kubebuilder create api ... --resource false --controller true`. The most we can do is, when we are trying to create a controller and no resource file or builtin resource is found, ask the user if he really wants to create a controller for a non-existent resource.

**Comment by camilamacedo86** [comment]
Hi @Adirio, 

As described in the issue and in the above comments it is about the ERROR outputted and NOT to remove or/change the current possibilities.

**Comment by Adirio** [comment]
In your first comment you state:

> It is a bug in the master which should not allow this option

which doesn't reflect the same as your following comments. Could you please improve the first message to reflect what you are saying now?
IMHO the first message should:
- Have the `--resource` and `--controller` flags in the block of code of the command. Having them below is confusing.
- Include the error that is being output when you run that.
- Explain why that is non intended behavior.
- Remove the part that says that this option should not be allowed.

After the first message gets improved, I would be pleased to remove all my comments to make this issue easier to track as this discussion is only introducing noise.

**Comment by camilamacedo86** [comment]
**Proposal Solution** 

- Note that if the user follows these steps an ERROR will be outputted. A valid solution in POV would handle the error and provide a msg to allow the user to knows how they should proceed.
- It is about the ERROR outputted and NOT to remove or/change the current possibilities.

**Comment by Adirio** [comment]
This would require to consider a lot more things, like core-resources who don't need the resource API or resources whose API was scaffolded before.

**Comment by camilamacedo86** [comment]
Hi @DirectXMan12, @mengqiy 

I think we should NOT allow creating a Controller when the project has not its resource since it will break the scaffold. In this way. WDYT about we change the behaviour of `The command: `kubebuilder create API --group <group> --version <version> --kind <kind>` for: 

- Check if has the resource if not it always will scaffold it
- Users can allow chosen between `[y/n]` to scaffold the controllers. 

WDYT?

**Comment by Adirio** [comment]
That's a backwards incompatible change so I think it would have to be considered for v3 but not for v2

**Comment by camilamacedo86** [comment]
IHMO we can address in the V2 since it is a change in the tool only in order to solve a bug and make its behaviour coherent. I mean it will not change the scaffold/layout of files.

**Comment by Adirio** [comment]
But it will change the CLI. If you automated sending "y" twice the same way some of the tests do, this change will break it.

I think this is another example that proves that we need different versions for the scaffolding and kubebuilder itself, which was already discussed in the plugin implementation.

**Comment by camilamacedo86** [comment]
@droot @mengqiy @DirectXMan12 
Provide a PR with my suggested solution #1362.

@Adirio, 
I do not think that changes in the command without changes in the scaffold/layout has been a motivation to create a new version as V2 for example.  Please, @droot @mengqiy @DirectXMan12  let me know if I am wronng here.

**Comment by mengqiy** [comment]
`--resource false --controller true` this is useful in the following 2 scenarios:
- Resources are already scaffolded before
- No need to scaffold resources for core types
IMO allowing `--resource false --controller true` is NOT a bug.

**Comment by camilamacedo86** [comment]
Hi @mengqiy,

> allowing --resource false --controller true 

Will break the project and will not work successfully when the resource is not found. 

However, I catcher the reason for you NOT consider it a BUG. 

Closing this one.
