### ISSUE TITLE
Golang-ci false duplicates

### ISSUE THREAD

**Issue by Adirio** [kubernetes-sigs/kubebuilder#1267]
The recently added Golang-ci is detecting false duplicates.

Travis builds that fail:
- #1227:
  - https://travis-ci.org/kubernetes-sigs/kubebuilder/builds/625623457?utm_medium=notification&utm_source=github_status
  - https://travis-ci.org/kubernetes-sigs/kubebuilder/builds/625665286?utm_medium=notification&utm_source=github_status

/kind bug

**Comment by camilamacedo86** [comment]
Hi @Adirio, 

Please, first at all do NOT assign an issue raised by you to others. You have no right to decide what someone should or not to do and is or not responsible for. If you need help you can ping others but never assign tasks for someone. 

Also, the lint is complaining and seen duplications in the changes made in your PR. See that it is NOT a bug at all. You should be able to solve the duplication on it and in the case of false affirmations use the annotation for the lint ignore the specific check on some piece of code as, for example,  by using `//nolint:dupl`.

**Comment by camilamacedo86** [comment]
Hi @Adirio, 

Please, first at all do NOT assign an issue raised by you to others. What someone should or not to do, is responsible or not is up to the person. If you need help or believes that some particular issue would be relevant to someone you can ping the person in a comment instead of. Note that when a task in assign for someone, others which could collab with will not as well. 

Also, the lint is complaining and seen duplications in the changes made in your PR. See that it is NOT a bug at all. You should be able to solve the duplication on it and then, in the case of false affirmations use the annotation for the lint ignore the specific check on some piece of code as, for example,  by using `//nolint:dupl`.






 `

**Comment by DirectXMan12** [comment]
That's a weird lint.  I think we might just want to turn it off.

**Comment by camilamacedo86** [comment]
Hi @DirectXMan12, 

The lint is used in the controller-runtime and has been used successfully as well in the SDK. See: https://github.com/kubernetes-sigs/controller-runtime/blob/467c79f45d4fdf61525989b51a5ed5269a6f323a/hack/verify.sh#L43 .

It will show duplications in the code, which means, point out code implementations that probably could be centralized and encapsulated in a function for example. 

Also, note that the error raise here just occurs after the changes made in the open PR done by @Adirio and not in the master branch.

**Comment by DirectXMan12** [comment]
It's not clear to me what it thinks the issue is though -- lines 17-18 are

```go
    input.Input
}
```

Wrapping an existing struct in a new one to customize particular pieces of functionality is pretty common, and forcing us to disable this lint just seems like weird noise.

**Comment by Adirio** [comment]
I agree it is pretty weird. I just added some functions but most of the file is already very similar. Is there anywsy to lower the severity of this lint to warning us but not stopping the build. I mean obviously the 70~ file interface implementations look pretty similar to each other but, you know, they need to be there.

**Comment by DirectXMan12** [comment]
There might be.  The golangci-lint YAML configuration file is pretty robust.  We'd have to switch to using the YAML file instead of flags, but that makes it easier to run by hand too.

**Comment by camilamacedo86** [comment]
HI @DirectXMan12, 

In this scenario I see 2 options: 

a) ignore the dupl lint when it points out false positives with the comment `/nolint: dupl` 
b) remove the dupl check lint
c) try to update the lint version used to check if the false positives will no longer occurs. ( current version is `v1.21.0` and the latest one is `v1.23.3` ( the update is good to be done anyway, so I am doing a PR for it ) 

**Pros to keep**
- This check has been used with success in order projects which allow us to avoid merge duplicate code in many scenarios. 

**Cons**
Kubebuilder has a kind of implementation where may they check lint bring more false positives. 
( scaffolds impl files follows all the same standard) 

How we should address this one?
@DirectXMan12 @mengqiy @Adirio

**Comment by camilamacedo86** [comment]
Hi @Adirio, 

The PR to upgrade the version is done : https://github.com/kubernetes-sigs/kubebuilder/pull/1361
Could you please check your scenario with?

**Comment by Adirio** [comment]
#1227 has been modifed since the whole scaffold package has evolved a lot since then. It is no longer detecting duplicates. However, updating Golang-CI should be fine

**Comment by camilamacedo86** [comment]
HI @Adirio, 

It is great to know. So, I understand that dupl lint is working well too. 
Really tks for your reply.
