### ISSUE TITLE
Allow different directory structure (related: multigroup)

### ISSUE THREAD

**Issue by jaypipes** [kubernetes-sigs/kubebuilder#1268]
I'd like to use `kubebuilder` for the new AWS Service Operator project. However, I'd like the following:

* Put the manager code in `cmd/aws-service-operator/main.go` instead of a main.go in the root project directory  (note: I'd like all command/binary code in a top-level `cmd` directory since that is a Golang best practice IIANM)
* Put the CRDs in `apis/{GROUP}/{VERSION}/{KIND}_types.go` file (similar to multigroup=true planned functionality) -- e.g. `apis/s3/bucket_types.go`
* Put the controller code in `pkg/controllers/{GROUP}/{KIND}_controller.go` (note: I'd like all package code in a top-level `pkg` directory since that is a Golang best practice IIANM)

I could imagine a `kubebuilder create api --api-path-template "apis/{group}/{version}/{kind}" --controller-path-template "pkg/controllers/{group}/{kind}" ...` CLI command having the flexibility to deal with both multi-group and single-group desired directory layouts.

/kind feature

**Comment by jaypipes** [comment]
For the request to put the manager main.go file in a `cmd/{PROJECT}/main.go` location, I note that the `kubebuilder init` CLI command actually infers that the main.go file will be put in a `cmd/manager/main.go` location:

https://github.com/kubernetes-sigs/kubebuilder/blob/19458ba88aa88a2fcc240cd9cf69bc88b4388d5b/cmd/init_project.go#L53

but that isn't accurate AFAICT

**Comment by Adirio** [comment]
I started working towards this goal (for example with #1252) but the syntax I used was `"%[VARIABLE NAME]s"` following package `fmt` `"%[1]s"` format.

**Comment by camilamacedo86** [comment]
HI @DirectXMan12 and @mengqiy, 
WDYT about it? What they are requesting here is not how it was in the V1 layout? 

c/c @joelanford @estroz @hasbro17

**Comment by estroz** [comment]
Relates to #932. Possible solution:
>This seems like a decent candidate to use as a test for plugins phase 2 -- it's mostly a matter of preference, and should be something that's easily doable under our general design currently.

/lifecycle frozen

**Comment by camilamacedo86** [comment]
Hi @jaypipes, 

The items: 

> Put the CRDs in apis/{GROUP}/{VERSION}/{KIND}_types.go file (similar to multigroup=true planned functionality) -- e.g. apis/s3/bucket_types.go
> Put the controller code in pkg/controllers/{GROUP}/{KIND}_controller.go (note: I'd like all package code in a top-level pkg directory since that is a Golang best practice IIANM)

Were addressed by command tool. You can use `kb edit multigroup=true` and then it will allow yu scaffold the APIs in this format. See: https://book.kubebuilder.io/migration/multi-group.html?highlight=multi#single-group-to-multi-group

Regards: 

> Put the manager code in cmd/aws-service-operator/main.go instead of a main.go in the root project directory (note: I'd like all command/binary code in a top-level cmd directory since that is a Golang best practice IIANM)

Then it relates to #932 as well as said. 

@DirectXMan12,

Note that this change was made from V1 to V2 with the purpose to make the things easier but also shows that the community is not really happy with. So, I think would be valid consider. WDYT? Has some specific reason for the `main.go` be moved to the root instead of following the common practice? See for example https://github.com/golang-standards/project-layout#cmd

**Comment by DirectXMan12** [comment]
let's centralize on #932 for those discussions.
