### ISSUE TITLE
How do I provide configs to the operator?

### ISSUE THREAD

**Issue by functicons** [kubernetes-sigs/kubebuilder#1271]
Say I have some configs for the operator, e.g., the number of retries or timeout for something, they can be customized by the user of the operator. How do I provide these configs?

**Comment by droot** [comment]
One way to do this will be:

Expose those configs as commandline flags and document -- how users can specify those flags in the manifests (yaml) [container args in the operator deployment yaml] before running the operator.

Pl. close this issue if this answers your question.
