### ISSUE TITLE
kubebuilder init fails from the getting-started guide

### ISSUE THREAD

**Issue by mithuns** [kubernetes-sigs/kubebuilder#1274]
Just following the tutorial [here](https://book.kubebuilder.io/cronjob-tutorial/cronjob-tutorial.html)
Fails to generate scaffolding

```
mithuns-MBP  ~/go/dev/tutorial.kubebuilder.io  kubebuilder init --domain tutorial.kubebuilder.io
2019/12/19 11:00:47 project name (tutorial.kubebuilder.io) is invalid: ([invalid value for project name (regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?')])

```

* go version

go version go1.13.4 darwin/amd64

* kubebuilder version (`kubebuilder version`) and scaffolding version (check your `PROJECT` file)

Version: version.Version{KubeBuilderVersion:"2.2.0", KubernetesVendor:"1.15.5", GitCommit:"0824a139f59e109c9e418a0b6e71a53c6e9e144f", BuildDate:"2019-11-20T00:00:24Z", GoOs:"unknown", GoArch:"unknown"}

* controller-runtime version (check your `go.mod` file)

* controller-tools version
no file generated

* Kubernetes & kubectl versions (just run `kubectl version` against your API server)

Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.3", GitCommit:"b3cbbae08ec52a7fc73d334838e18d17e8512749", GitTreeState:"clean", BuildDate:"2019-11-14T04:24:34Z", GoVersion:"go1.12.13", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.3", GitCommit:"b3cbbae08ec52a7fc73d334838e18d17e8512749", GitTreeState:"clean", BuildDate:"2019-12-04T07:23:47Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}

/kind bug

**Comment by StiviiK** [comment]
The dots in your directory name are not allowed, as far i can see only alphanumeric characters are allowed.
