### ISSUE TITLE
Validation for relation of CRD fields

### ISSUE THREAD

**Issue by micnncim** [kubernetes-sigs/kubebuilder#1275]
Provide a way of validation for relation of CRD fields.

For example, this spec defines the validation: *The value of MaxNodes is greater than one of MinNodes*.

```go
type FooSpec struct {
	// +kubebuilder:validation:Minimum=1
	MinNodes int32 `json:"minNodes"`

	// +kubebuilder:validation:gt:FooSpec.MinNodes
	MaxNodes int32 `json:"maxNodes"`
}
```

Another example is `// +kubebuilder:validation:lt`.

It should be useful to have such a validation.

/kind feature

**Comment by droot** [comment]
I am afraid this won't be supported by the Kubernetes API Server anytime soon. Here is the link to the upstream doc for CRD validation --> https://kubernetes.io/docs/tasks/access-kubernetes-api/custom-resources/custom-resource-definitions/#validation

For now, such validation needs to be implemented using a custom validating admission webhook. Closing this for now.
