### ISSUE TITLE
Allow resources to be annotated with warnings and notes with `// +kubebuilder:docs`

### ISSUE THREAD

**Issue by pwittrock** [kubernetes-sigs/kubebuilder#130]
`kubebuilder docs` generates a `config.yaml` file that is used to control the table of contents for docs.  The config.yaml can also be used to set warnings and description notes on specific APIs, however since the file is generated, users shouldn't edit it directly.

Instead we should support the following annotations on resource structs:

- `// +kubebuilder:docs:warning`
- `// +kubebuilder:docs:note`

These should be added to the generated config.yaml after *group* [here](https://github.com/kubernetes-sigs/kubebuilder/blob/master/cmd/kubebuilder/docs/gen.go#L100) as is shown [here](https://github.com/kubernetes-incubator/reference-docs/blob/master/gen-apidocs/generators/config.yaml#L93) and [here](https://github.com/kubernetes-incubator/reference-docs/blob/master/gen-apidocs/generators/config.yaml#L139)

**Comment by pwittrock** [comment]
@fanzhangio also reassigning this one

**Comment by pwittrock** [comment]
@fanzhangio please comment on the issue if you have started any work on this.

**Comment by lichuqiang** [comment]
reached out to @fanzhangio , he has started the task.

/unassign @lichuqiang
/assign @fanzhangio

**Comment by fanzhangio** [comment]
Have done this issue with PR #156 
@pwittrock @lichuqiang
