### ISSUE TITLE
Remove Approved label on code change events

### ISSUE THREAD

**Issue by Adirio** [kubernetes-sigs/kubebuilder#1300]
A code change in a non-merged PR removed `lgtm` label but kept the `approved` label.

This behavior is a bit dangerous as after the code change is made, a reviewer can add the `lgtm` label and the PR will be merged without the intervention of an approver.

Example: #1287 (the example is trivial and it should be merged, but the code change could potentially be anything)

**Comment by DirectXMan12** [comment]
This is standard k8s behavior iirc.  The idea is that approval is "is the general idea sound", and so new code *probably* doesn't invalidate that as long as the reviewer signs off on it.  Auto-removing approval generally seems to create more busywork, IMO -- one of `/approve` or `/lgtm` needs to be sticky (and I think approval is probably the right choice here).

**Comment by Adirio** [comment]
Then closing this
