### ISSUE TITLE
Goimports error in Travis

### ISSUE THREAD

**Issue by Adirio** [kubernetes-sigs/kubebuilder#1303]
Travis is failing several PR due to a `goimports` linting error. The error message is:

>$ ./scripts/verify.sh
>running go vet
>running go fmt
>running golangci-lint
>pkg/scaffold/v2/controller/controller_suitetest.go:26: File is not `goimports`-ed (goimports)
>	"sigs.k8s.io/kubebuilder/pkg/scaffold/v2"
>The command "./scripts/verify.sh" exited with 1.

Affected PR:
- #1186: [Travis](https://travis-ci.org/kubernetes-sigs/kubebuilder/jobs/635636861#L249-L255)
- #1248: [Travis](https://travis-ci.org/kubernetes-sigs/kubebuilder/jobs/635638061#L249-L255)
- #1252: [Travis](https://travis-ci.org/kubernetes-sigs/kubebuilder/jobs/635649415#L249-L255)
- #1265: [Travis](https://travis-ci.org/kubernetes-sigs/kubebuilder/jobs/635522824#L249-L255)

/kind bug

**Comment by Adirio** [comment]
#1186 and #1252 do modify that file and #1186 doesn't even touch the import section. Additionally, #1248 and #1265 do not modify that file at all, so the error doesn't seem to be related to anything done in those PR.

The check has been introduced in #1292 and #1198 is the only thing that was merged into master between #1292 branch start and its merge. I have tried to run `gofmt` and `goimports` to that file and they do not modify anything.

@camilamacedo86 Could you please have a look at this as my linter is warning about less things than yours?

**Comment by camilamacedo86** [comment]
@Adirio, 

The error faced is:

![Uploading Screenshot 2020-01-12 at 12.11.41.png…]()
 
**Note that you can use the lint to fix it automatically by adding the flag fix as follows and the running the lint**

<img width="552" alt="Screenshot 2020-01-12 at 12 17 35" src="https://user-images.githubusercontent.com/7708031/72218833-47a9b880-3537-11ea-9576-61ae58bd0af6.png">

**Comment by camilamacedo86** [comment]
It is fixed here: https://github.com/kubernetes-sigs/kubebuilder/pull/1293/files#diff-ec3d96c196a007869f26993a5a8a7492R26

**Comment by Adirio** [comment]
Why does it need to use `v2` as import alias if the package is already called v2?

**Comment by camilamacedo86** [comment]
Hi @Adirio the lint checks are usually based in good practices. I understand that it is suggesting to add the alias in order to make implicit that it came from v2 and not another version. However, I did not check it further. Please, feel free to look for its explanation in its doc and implementation which is here: https://godoc.org/github.com/Go-zh/tools/cmd/goimports.

**Comment by camilamacedo86** [comment]
Hi @Adirio, 

It is fixed. Could we close this one? If not, what is missing to address here?
