### ISSUE TITLE
Update to use the latest kind v0.7.0+

### ISSUE THREAD

**Issue by mengqiy** [kubernetes-sigs/kubebuilder#1308]
kubebuilder currently uses v0.6.0, we should update to use v0.7.0+

**Comment by bharaththiruveedula** [comment]
@mengqiy can I work on it. But I can see kubebuilder already using v0.6.0 version of "kind" https://github.com/kubernetes-sigs/kubebuilder/blob/master/common.sh#L189

Do we need to update to v0.7.0?

**Comment by Adirio** [comment]
I guess he may have seen the 0.5.1 in the latest release, as the line you link hasn't been released yet, it is still only in master.

**Comment by mengqiy** [comment]
@bharaththiruveedula I somehow thought we are using an older version of kind. I updated the issue. We want kind to be the latest.

**Comment by bharaththiruveedula** [comment]
@mengqiy can I take it up the issue?

**Comment by Adirio** [comment]
`help wanted` and `good first issue` labels were set so feel free to work on this.

/assign @bharaththiruveedula
