### ISSUE TITLE
`make deploy` doesn't work with the current defaults, suggested tools and suggested commands from the book

### ISSUE THREAD

**Issue by dionysius** [kubernetes-sigs/kubebuilder#1315]
The issue https://github.com/kubernetes-sigs/kubebuilder/issues/873 is not (anymore) resolved. Happened to me right now.

_**Depends if you want that kubebuilder to be used seamlessly with kind as suggested in the book.**_
> It is recommended to develop your webhook with a kind cluster for faster iteration. Why?
> ...

Without modification the resulting deployment has the following output (which is part of `make deploy`):
```
$ kustomize build config/default/ | grep -B5 -A23 "image: controller"
      - args:
        - --metrics-addr=127.0.0.1:8080
        - --enable-leader-election
        command:
        - /manager
        image: controller:latest
        name: manager
        ports:
        - containerPort: 9443
          name: webhook-server
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 30Mi
          requests:
            cpu: 100m
            memory: 20Mi
        volumeMounts:
        - mountPath: /tmp/k8s-webhook-server/serving-certs
          name: cert
          readOnly: true
      terminationGracePeriodSeconds: 10
      volumes:
      - name: cert
        secret:
          defaultMode: 420
          secretName: webhook-server-cert
---
```

But we have the following issues:
- imagePullPolicy is set to Always, as it seems that's the default in the deployment where this field is not specified. So kind always tries to pull the image from dockerhub and fails

```
$ kubectl get deployments -n foo-system foo-controller-manager -o json | jq '.spec.template.spec.containers[1].imagePullPolicy'
"Always"
```

- in `image: controller:latest` the `:latest` tag forces a pull as well, independent what's written in imagePullPolicy, resulting into the same issue.
  - And the change can't be edited in kustomize (using `kustomize edit image ...`) because https://github.com/kubernetes-sigs/kubebuilder/blob/c9d5a914499df959f06ebf503e9bce0ef848089f/testdata/project-v2/Makefile#L38 sets it back to `controller:latest` as above. Yes, someone could use `make deploy IMG=...`, but I'm talking here about [what the book says](https://book.kubebuilder.io/cronjob-tutorial/running-webhook.html), and it says only `make deploy`

So we either need to fix:
- the defaults
- the tutorial
- the commands
- or maybe all of them a bit to get the desired effect

**Comment by mengqiy** [comment]
`controller:latest` is not a default, but a placeholder. 
I guess we need to change the command in tutorial to:
`make deploy IMG=<some-registry>/<project-name>:tag`
