### ISSUE TITLE
Book updated before feature release

### ISSUE THREAD

**Issue by Adirio** [kubernetes-sigs/kubebuilder#1328]
## Description
The book, which is the official documentation of `kubebuilder`, points to Master. This is an issue because when new features get added to Master, the book gets updated, while that feature isn't still in a released version of `kubebuilder`.

### Example
#1198 added multigroup support and updated the book accordingly. This merge has still not been released. The documentation change is already present in the [official book](https://kubebuilder.io/migration/multi-group.html).

## Solution
First of all, I'm not sure how kubebuilder.io works, and both the provided options will require it to be pinned to a non-default GitHub branch.

Suggested options:
1. Change to the GitFlow model, where all the PR are merged into a `development` branch and they only get to master with releases. IMHO, GitFlow is a really good git pattern and setting the `development` branch as the default in GitHub will mean that it will behave exactly as `master` does now. It will be the default branch when you go to https://github.com/kubernetes-sigs/kubebuilder and it will be the default branch were PR will be pointing to. The book should pin to `master`, which will not be the default branch.
2. Change where the book is poiting to manually each update.

---
/kind bug

**Comment by Adirio** [comment]
@mengqiy @DirectXMan12 @droot

**Comment by mengqiy** [comment]
We can probably have a branch called `book-v2-staging` which maps to `book-v2-staging.book.kubebuilder.io`. This branch and subdomain is where our **unreleased** feature documents lives.
`book.kubebuilder.io` still points to `master` branch, which contains the released features.
When we release new kubebuilder, we create an PR to bulk merge new documents from `book-v2-staging` branch to `master`.

**Comment by mengqiy** [comment]
We are planning to release CR, CT and KB this week.
We can setup the new branch and start to use it after the KB release.

**Comment by Adirio** [comment]
> We can probably have a branch called `book-v2-staging` which maps to `book-v2-staging.book.kubebuilder.io`. This branch and subdomain is where our **unreleased** feature documents lives.
> `book.kubebuilder.io` still points to `master` branch, which contains the released features.
> When we release new kubebuilder, we create an PR to bulk merge new documents from `book-v2-staging` branch to `master`.

If I understood you correctly, I want the exact opposite. Master is the one where unreleased feature live. The thing was having the book pointing to a frozen release branch so that it gets updated only when a new release happens.

**Comment by mengqiy** [comment]
Your approach makes more sense!
The branch name then probably should be called `book-v2`.

**Comment by Adirio** [comment]
What is easier, changing the target branch from releases or making a branch `book-v2` and moving it every release?

**Comment by mengqiy** [comment]
I have created branch `book-v2` and used it as the production branch.
