### ISSUE TITLE
Generate CLI completions for bash/zsh

### ISSUE THREAD

**Issue by hasbro17** [kubernetes-sigs/kubebuilder#1346]
The Kubebuilder CLI doesn't seem to provide bash or zsh completions similar to kubectl: `kubebuilder completion bash`
It should be straightforward enough to generate it via the cobra cmd helpers e.g [`GenBashCompletion()`](https://github.com/spf13/cobra/blob/89c7ffb5129bebd58cd68878c13af2144a5791f3/bash_completions.go#L528).

I can submit a PR to add this in unless there's reasons not to, e.g potentially moving away from cobra CLI in the future, or if any of the incoming plugin and CLI work in #1290 would affect this (which doesn't seem like it would). 

/kind feature

**Comment by mengqiy** [comment]
It's just because no one has asked for this and we have never prioritized it.
Feel free to submit a PR for bash/zsh completion support.

**Comment by hasbro17** [comment]
Yep it's a pretty low priority feature but I've become somewhat used to autocomplete from some of the other CLI tools. I'll submit a PR hopefully soon.

**Comment by evalsocket** [comment]
@hasbro17 It looks pretty much straightforward. I would like to work on this. Can this be assigned to me?

**Comment by bharathi-tenneti** [comment]
working in this.
