### ISSUE TITLE
Controller not reconciling on the child's status subresource update

### ISSUE THREAD

**Issue by prafull11** [kubernetes-sigs/kubebuilder#1347]
/kind bug

**Comment by prafull11** [comment]
I don't know why details did not came in the description. So posting the details here:

I have two controllers where first controller is a parent("owns") of second controller. Now I want to reconcile the first controller based on the subresource status update of second controller which is not happening. I can see no update event in the first reconciler. 

However when I don't use subresource in second controller, and directly update the resource status then the update event comes in first controller. 

According to #618 Even when we update subresource the update event should come into reconcilation. Can anyone help me understand what Am I missing here?

**Comment by prafull11** [comment]
@DirectXMan12 Could you please let me know what I am trying to do is valid scenario. Or should I not use status subresource to get the reconcile of child's status update in parent's reconcile. Thanks for your time. :)

**Comment by Adirio** [comment]
This is definetely not a kubebuilder issue, but controller-runtime's. Would you just create a PR there (linking this one if you want) with the description?

P.S.: If the description didn't appear in the first message, you may need to delete `<!--` and `-->` which are how you delimit comments in HTML. This is, anything written between those two symbols will not be shown in the page.

**Comment by camilamacedo86** [comment]
Hi @prafull11, 

Sorry, but I am not sure if properly understood your scenario. Could you please let us know if you still need help with? If yes, could you please answer the following template with pieces of the code and/r a link for your project in order to allow us to understand better what you are trying to achieve? 

> **What did you do?**
> A clear and concise description of the steps you took (or insert a code snippet).
> 
> **What did you expect to see?**
> A clear and concise description of what you expected to happen (or insert a code snippet).
> 
> **What did you see instead? Under which circumstances?**
> A clear and concise description of what you expected to happen (or insert a code snippet).

**Comment by Adirio** [comment]
In any case this should be reported in controller-runtime as specified [here](https://github.com/kubernetes-sigs/kubebuilder/issues/1347#issuecomment-581859383), closing for house-keeping purposes.

/close

**Comment by wenxinax** [comment]
Maybe you can try `r.Status().Update(ctx, obj)`
