### ISSUE TITLE
Controller-gen lifecycle (install/update) enhancement proposal 

### ISSUE THREAD

**Issue by droot** [kubernetes-sigs/kubebuilder#1351]
This issue proposes a new workflow for managing life-cycle of `controller-gen` for KubeBuilder projects. The ideas in the proposal are inspired from the discussion in [this PR](https://github.com/kubernetes-sigs/kubebuilder/pull/1289).

**Problem:**
In the current workflow of Kubebuilder projects, Makefile checks if `controller-gen` executable is available in the PATH, if not, it installs `controller-gen` using `go get /path/to/specific/version/of/controller-tools/controller-gen` globally. Current workflow leads to following problems:

- If multiple developers are collaborating on a KB project and they all are using different versions of `controller-gen`, will end up with different artifacts (CRDs, deepcopy, RBAC manifests etc.). This is the problem we (KubeBuilder collaborators) are running in to wrt to `test/project-v2` project.

- Makes generated artifacts (CRDs, deepcopy, RBAC etc) environment dependent hurting reproducibility.

**Proposal:**
Introduce `ControllerGenVersion` field in KubeBuilder `PROJECT` file:
```sh

# controller-gen version to use
ControllerGenVersion: v02.4

```

Create a new directory `bin/` in the project to store `controller-gen` binary (and potentially other binaries in the future). Tweak the logic for the Makefile target `controller-gen` to ensure `bin/controller-gen` points to controller-gen version specified in `PROJECT` file. `./bin/controller-gen --version` command can be used to determine the currently installed version.

Ensure that Makefile uses `bin/controller-gen` instead of global `controller-gen` binary.

If a developer wants to bump the version of `controller-gen` in their project, they can simply change the version in `PROJECT` file and run `make controller-gen` to switch to correct version.

**BONUS:**
we can add another target in Makefile to update to latest version of `controller-gen` by introducing new target `update-controller-gen` which can:

- Query github releases for `controller-gen` and show latest available version and prompt to update.
- If user says 'yes`, then updates the `ControllerGenVersion:<new-version>` in `PROJECT` file and runs `make controller-gen`.

/kind feature

I am happy to help with reviews/brainstorm/get-this-merged if someone wants to take this up once we agree if this is a good idea.

/cc  @dionysius @mengqiy @estroz @Adirio @camilamacedo86 @DirectXMan12

**Comment by Adirio** [comment]
How will we keep the Makefile and the PROJECT configuration file synced? Will we parse the PROJECT file from the Makefile?

**Comment by dionysius** [comment]
We could - as proposed - set `ControllerGenVersion` to the `PROJECT` file and additionally define a target to said file:

```
bin/controller-gen: PROJECT
  #... stuff to do to install it to bin/controller-gen

PROJECT:
  # nothing
```

This way `make` will detect changes if the `PROJECT` file has changed, since the date of `PROJECT` is newer than `bin/controller-gen`.

There is a debug flag `-d` for make that can show us what it thinks of the dependent target, if it's current or not.

**Comment by droot** [comment]
> How will we keep the Makefile and the PROJECT configuration file synced? Will we parse the PROJECT file from the Makefile?

Yes, we will parse the PROJECT file from the Makefile. I don't expect parsing to be too complicated (just a grep should be enough). 

I like @dionysius suggestion that leverages Makefile's feature to make the `bin/controller-gen` more efficient.

**Comment by Adirio** [comment]
This approach will probably remove the need of `$GOPATH` in order to find `controller-gen`, but I wanted to mention that the linked issue detects a bug with the current behavior if a multi-path `$GOPATH` is set.

**Comment by Adirio** [comment]
Question: as this would definetely change the scaffolded `Makefile` file, would this be for scaffolding version `3`?

**Comment by mengqiy** [comment]
> Question: as this would definetely change the scaffolded Makefile file, would this be for scaffolding version 3?

This really depends on if it's backward compatible. If so, we can release it in v2.4.0+.

**Comment by Adirio** [comment]
If we are adding a `bin` directory with a `controller-gen` binary that should probably be done in the `kubebuilder init ...` command and that means extra dir and file, so backwards incompatible IMHO. We could add it backwards compatibility by creating an `kubebuilder alpha SOME_NAME` command that creates the directory, downloads the binary and modifies the `Makefile`, but we should probably have a `y/n` confirmation saying that to execute this the `Makefile` is going to be deleted and re-scaffolded as it may delete user-code.

**Comment by RoeeShlomo** [comment]
Any opinion on the way this is done in https://github.com/kubernetes-sigs/application/blob/master/Makefile? seems simple and avoids the problems described here

**Comment by camilamacedo86** [comment]
HI @droot, 

I am ok with the suggestion to add the version in the PROJECT file. Shows very reasonable for me and appears that would simplified the makefile as well. Also, I think if we move forward here we need to add the kustomize version as well.

**Comment by dionysius** [comment]
Can we address that please?

While we're at it, can we also add `etcd`, `kube-apiserver` and `kubectl` to that list?

```
.../controllers/service/suite_test.go:36

  Unexpected error:
      <*fmt.wrapError | 0xc0005949c0>: {
          msg: "failed to start the controlplane. retried 5 times: fork/exec /usr/local/kubebuilder/bin/etcd: no such file or directory",
          err: {
              Op: "fork/exec",
              Path: "/usr/local/kubebuilder/bin/etcd",
              Err: 0x2,
          },
      }
      failed to start the controlplane. retried 5 times: fork/exec /usr/local/kubebuilder/bin/etcd: no such file or directory
  occurred
```

**Comment by DirectXMan12** [comment]
/remove-lifecycle rotten

I think we mentioned this during the most recent meeting

**Comment by sourcedelica** [comment]
Re: the comment from @dionysius - you can now point the `KUBEBUILDER_ASSETS` environment variable to `<kubebuilder_install>/bin`.  For example:
```
KUBEBUILDER_ASSETS=/Users/eric/dev/kubebuilder_2.3.1_darwin_amd64/bin make test
```

**Comment by camilamacedo86** [comment]
Following a summary of the discussion of this in the bug triage meeting. 

A part of this proposal shows that is in the place to go/v3-alpha already. However, shows that this subject requires more discussions. @DirectXMan12 raise an idea of we scaffold tooling via go file that would install all deps globally and @Adirio make a point regards the logic still using the local version instead of installing the specific one as it is done currently via makefile. 

In this way, we need here reach a consensus on how we could address this feature: 

- Should we store the deps versions on the Project file as suggested in this issue? 
- Should we keep the officially supported/tested dep version in a go module that will be tooling with the project whcih would be called such as `cd hack/; go run tooling.go`? 
- Should we keep as the common behaviour install by default globally in the GOPATH/bin or per project in its bin/ directory?
 

c/c @estroz @Adirio @DirectXMan12 please fell free to add your input as well.

**Comment by Adirio** [comment]
As I said in the meeting and you mention above I lean towards having the required versions installed in a known path (`GOPATH/bin` works) and then symlinking them in the project's `bin` directory. Bear in mind that these would require to support multiple versions installed globally so the version needs to be added to the binary path somehow, for example `GOPATH/bin/VERSION/controller-gen` or `GOPATH/bin/controller-gen@0.7.0` (not sure about the support of symbols like `@` in different OS).
