### ISSUE TITLE
We need docs for the low-level webhooks

### ISSUE THREAD

**Issue by DirectXMan12** [kubernetes-sigs/kubebuilder#1356]
We're getting a lot of confusion around how to do webhooks for existing types.  The answer is that you need to use the lower-level machinery, which looks similar to the v1 webhooks, but folks don't know that exists and struggle to find it.  We should have, at the very least, some pointers to the CR examples directory.

/kind documentation

**Comment by mengqiy** [comment]
People trying to do webhooks for core types usually need to access the low-level webhook machinery, I recently added a [doc](https://book.kubebuilder.io/reference/webhook-for-core-types.html) for that.
We probably should have more doc.

**Comment by DirectXMan12** [comment]
This seems largely fixed, but it's listed as "for core types".  We prob want to clarify that a bit.
