### ISSUE TITLE
Ensure the kubebuilder works properly in the supported platform

### ISSUE THREAD

**Issue by camilamacedo86** [kubernetes-sigs/kubebuilder#1363]
To ensure it, we could just ensure that the target `make generate` (golden) script can be executed successfully in mac and Linux. Then, my suggestion here would be doing this test in the CI.

**Comment by camilamacedo86** [comment]
WDYT @droot @mengqiy @DirectXMan12?

**Comment by DirectXMan12** [comment]
Travis was previously doing this, at least.  Not sure how we'd do OSX on Prow -- IIRC there's no way w/o something like Travis.

**Comment by camilamacedo86** [comment]
HI @DirectXMan12, 

Travis was just running test.sh, which just check v1. IHMO, run the golden script with OSX would be enough to check it since it will scaffold the projects and use all common commands.  WDYT? Any objection?

**Comment by camilamacedo86** [comment]
You are right @DirectXMan12, 

I checked it. better and the test.sh has ben executed for both platforms which shows enough. 
c/c @Adirio  

/close
