### ISSUE TITLE
Allow contributors to test locally

### ISSUE THREAD

**Issue by camilamacedo86** [kubernetes-sigs/kubebuilder#1364]
This task is just for we ensure that contributors are able to test their changes locally.

**Suggestion:**

- make target to run the tests
- properly doc it in the CONTRIBUTION.MD
- ensure that the test runs in any platform ( currently, they work just in the Linux. )

**Comment by camilamacedo86** [comment]
WDYT @droot @mengqiy @DirectXMan12?

**Comment by DirectXMan12** [comment]
seems like a good thing to have.  Do you have concrete steps that are missing?

**Comment by camilamacedo86** [comment]
Hi @DirectXMan12, 

The PR  https://github.com/kubernetes-sigs/kubebuilder/pull/1432 covers this one. 

Then, we need a specific issue for:
- To allow contributors to run the e2e tests (test-e2e.sh) locally (makefile target and fix required setup for Linux and OSX)  

PS.: Over the win platform, I have no clue how it works and what is missing. However, I think that may @Adirio uses win and could help us track it in another issue.
