### ISSUE TITLE
Limiting operator role/binding permissions

### ISSUE THREAD

**Issue by champak** [kubernetes-sigs/kubebuilder#1366]
Hi folks,
The current behavior with the generated RBAC roles/rolebindings that we have seems to have the Operator end up with cluster scope CRUD permissions for any resources it owns. If these resources are native K8s like pods I think in effect it might mean a sw bug in an operator could affect any pod on the cluster; that would be something to avoid... Is there any pattern for limiting the operator manager-role to specific namespaces ?  I guess it could be done with manually written role/bindings but was wondering if the existing generation tools can be tweaked to produce the role/rolebindings limited to a set of namespaces. Thanks.

**Comment by Adirio** [comment]
Hi Champak,
Kubebuilder doesn't limit its resources to any namespace (wouldn't make any sense) so the RBAC roles/reolebindings are cluster scope as you said. I don't think there is any plan to change this behavior, as kubebuilder is opinionated, it doesn't try to offer one thousand flags to configure the scaffolded project to be exactly what you want. The idea is that those small tweaks should be done manually.

Changing a cluster scope role and rolebinding to a namespaced one should be pretty easy, just change the `kind` fields and set the namespace.

**Comment by champak** [comment]
@Adirio Thanks for your response ! I had found it took more than just updating the pair of role/role-binding files kube-builder produces. For one it looked like if we are managing native objects like Pods/Services the "manager" needs to be able to do a list operation at cluster scope. I had seen complaints from reflector.go that went like 

reflector.go:123] pkg/mod/k8s.io/client-go@v0.0.0-20190918160344-1fbdaa4c8d90/tools/cache/reflector.go:96: Failed to list *v1.Pod: pods is forbidden: User "system:serviceaccount:foo-system" cannot list resource "pods" in API group "" at the cluster scope

when I limited the roles/rolebindings to a specific namespace

I am guessing this may be from reflector/watches that gets setup when we tell a controller to "own" pods as in ..Owns(&corev1.Pod{})... I did not look further yet to confirm but seemed like controller/manager would need cluster scope roles to at least list the resources it needs to manage even if it only did actual work (create/delete/update ops) on these resources in specific namespaces. Does that sound right ?

**Comment by Adirio** [comment]
If you are right with your assumption that the dependency comes from `For` and `Owns`, you can implement these two with `Watches` and providing your own handler, which may be able to solve the issue. But it may also be the cache the one that requires cluster scope permissions. You could always limit to list and get cluster scope and not prevent any modification but in the desired namespace.

**Comment by champak** [comment]
Limiting to cluster scoped list and watch permissions had seemed to work. get did not seem to be required. 
wrt Owns() I was going off this in controller.go::

// Owns defines types of Objects being *generated* by the ControllerManagedBy, and configures the ControllerManagedBy to respond to
// create / delete / update events by *reconciling the owner object*.  This is the equivalent of calling
// Watches(&handler.EnqueueRequestForOwner{&source.Kind{Type: <ForType-apiType>}, &handler.EnqueueRequestForOwner{OwnerType: apiType, IsController: true})
func (blder *Builder) Owns(apiType runtime.Object) *Builder {
	blder.managedObjects = append(blder.managedObjects, apiType)
	return blder
}

which sounds like it sets up cluster scoped watches on the applicable resource. I am not sure how disruptive it would be to the current kubebuilder control flow to use watches with handlers customized to specific namespaces.

**Comment by Adirio** [comment]
@champak closing this as resolved, if any additional help is needed feel free to comment and reopen it.

/close

**Comment by Shaked** [comment]
Hey @Adirio @champak 

I couldn't find it anywhere else. Is it actually possible to reduce the controller's permissions? 

I'd like to make sure the controller can only access a specific namespace, without the need to have any cluster permissions. 

When I tried to change the ClusterRole and ClusterRoleBinding to Role and RoleBinding, it kept complaining that the ServiceAccount has no permissions to cluster scope commands (e.g list deployments, pods, CustomObject etc). 

I don't need the controller to have access to anything but the specified namespace, so I was wondering what would be the best practice to achieve that. 

Thank you!
Shaked
