### ISSUE TITLE
How to use Kubebuilder with multiple controller binaries in the same project?

### ISSUE THREAD

**Issue by gh67uyyghj** [kubernetes-sigs/kubebuilder#1369]
Thank you for creating this great project. I am still very new to it by as the title says I am not really sure how to create multiple binaries each having controller that watches the same GVR types. Do I just create resources and write controllers inside `/pkg` and `make` will take care of generating everything?

**Comment by Adirio** [comment]
Kubebuilder creates a single binary that contains all the controllers. You have 1 manager (that's how it is called) which contains all the controllers defined in that project. This enables performance enhancements such as only having one shared cache for all the controllers, reducing the number of requests to k8s API. If you want two controllers to be in separate binaries for a specific reason (make sure that this reason is valid) you would have to create two different kubebuilder projects.

**Comment by gh67uyyghj** [comment]
@Adirio thank you for the response! I have a project where I need daemonset controllers and also sidecard controllers for specific deployments. The problem here is that these controllers watch the same resources. These multiple binaries are inside the same project (e.g. istio). Does this mean the kubebuilder is not a good option for me?

**Comment by Adirio** [comment]
A single binary, the manager, will have both controllers, and that way they will use a shared cache reducing the amount of messages that you need to exchange with k8s apiserver. Why do you need to split those two controllers in two different binaries?

**Comment by gh67uyyghj** [comment]
@Adirio yes I have to, the daemonset controllers are running in host network and the sidecar controllers are running each in its pod. Also I need to mention that daemonset and sidecars are not actually watching each resource like it's generated by kubebuilder `main.go`. Some resources are watched by both but others are not. Does this mean I have to go back to https://github.com/kubernetes/code-generator to make the codebase more consistent?

**Comment by Adirio** [comment]
Do you really mean controllers or the resources created by this controllers? Having controllers in each pod sounds a bit strange.

Eitherway, if you really need to have separate binaries, you can always use two different scaffold projects. If there is some shared types (files under `api` folder), they are being sported so your second project can import the types from the first project.

**Comment by gh67uyyghj** [comment]
@Adirio thank you for the quick response.  The architecture can be changed for example to instead of using a controller inside the sidecar, it can be used in a daemonset and then propagate the changes via some custom API to the sidecar. But in either case, I will also need more than one controller binary per project having access to the same CRD. Can kubebuilder be intialized in a project subdirectory via some option or it must be at the root?

**Comment by gh67uyyghj** [comment]
@Adirio ? Canis it possible to initialize kubebuilder inside a subdirectory?

**Comment by Adirio** [comment]
This is the way to go: https://github.com/kubernetes-sigs/kubebuilder/issues/1369#issuecomment-586298366
> Eitherway, if you really need to have separate binaries, you can always use two different scaffold projects. If there is some shared types (files under `api` folder), they are being exported so your second project can import the types from the first project.

**Comment by gh67uyyghj** [comment]
@Adirio thank you but I hope you reconsider this in the future. For example, I think istio has multiple controller binaries watching the same resources and acting differently (i.e. one translates the specs to envoy config and the other controls the envoy authorization services). This can be done with the old way with the code generator, but kubebuilder is far more superior and cleaner especially when it comes to validation
