### ISSUE TITLE
AdditionalProperties CRD validation bug

### ISSUE THREAD

**Issue by crimsonfaith91** [kubernetes-sigs/kubebuilder#137]
When running `kubebuilder create config` to generate a controller image, I encountered a CRD validation
bug that specifies `AdditionalConfiguration` field cannot be set to false.

For instance, I have the bug for `options` field in my `types.go` file:
```
// Options is additional configuration options that will be passed to the pods.
// +optional
Options map[string]string `json:"options,omitempty"`
```

In `zz_generated.kubebuilder.go` file, the `AdditionalConfiguration` field is initialized as follow:
```
AdditionalProperties: &v1beta1.JSONSchemaPropsOrBool{
        Allows: true,
	//Schema: &,
},
```

@Liujingfang1

**Comment by Liujingfang1** [comment]
I've tested locally and confirmed that this is related to https://github.com/kubernetes/kubernetes/pull/62333
The PR was checked in at the beginning of April 2018. To fix the issue, please update kubernetes to the latest version.

**Comment by pwittrock** [comment]
@Liujingfang1 I don't think that PR exists in any released Kubernetes version, and will be many months before it is available on GKE.  We should work around it.

**Comment by Liujingfang1** [comment]
@pwittrock Yep. I just discussed this with Sunil about this and we planned to add a flag to kubebuilder as a workaround. The default will skip `additionProperties` so that the crd can be created. If the flag is set, kubebuilder will generate this field so that we can do testing on our own.
