### ISSUE TITLE
CRD cleanup pattern

### ISSUE THREAD

**Issue by champak** [kubernetes-sigs/kubebuilder#1372]
Hi folks,
I have been looking around for a decent pattern for implementing CRD cleanup. A mechanism to cleanup CRDs no longer in use based on say time and optional logic examining status etc. would be nice. The TTL controller approach looked promising https://kubernetes.io/docs/concepts/workloads/controllers/ttlafterfinished but it is unclear if that will get extended beyond jobs to support custom resources. Scripts can be used to query CRDs and take action but does not seem like an ideal solution. Has anyone had luck with any other automate-able mechanisms for cleaning up ? At scale, unless CRDs only represent very long lived resources, cleaning up would seem to be an important house-keeping task. This is of course not a kubebuilder specific issue but seemed related enough...Thanks

**Comment by champak** [comment]
For anyone looking at similar issues, I did not locate an established pattern. For now I guess its DIY.

**Comment by dejanzele** [comment]
I have seen this getting implemented here or there, I guess it might be good to make it generic.
