### ISSUE TITLE
omit empty for yaml?

### ISSUE THREAD

**Issue by ryandawsonuk** [kubernetes-sigs/kubebuilder#1379]
The generated Go structs [set fields as optional by adding 'omit empty' to the json flags](https://github.com/kubernetes-sigs/kubebuilder/issues/521) next to the fields. But not yaml. We have a use-case where we're using a clientset and want to generate yaml from the structs. Should we be adding these flags ourselves or would it make sense for kubebuilder to do this or are there other ways?

**Comment by Adirio** [comment]
Only JSON tags are being set because the YAML parser used reads the JSON tags:

> In short, this library first converts YAML to JSON using go-yaml and then uses json.Marshal and json.Unmarshal to convert to or from the struct. This means that it effectively reuses the JSON struct tags as well as the custom JSON methods MarshalJSON and UnmarshalJSON unlike go-yaml. For a detailed overview of the rationale behind this method, [see this blog post](http://web.archive.org/web/20190603050330/http://ghodss.com/2014/the-right-way-to-handle-yaml-in-golang/).

Source: https://pkg.go.dev/sigs.k8s.io/yaml?tab=overview

**Comment by ryandawsonuk** [comment]
Thanks!
