### ISSUE TITLE
How to avoid duplicated sub resource

### ISSUE THREAD

**Issue by chenwng** [kubernetes-sigs/kubebuilder#1381]
Hi,

I have two controllers which work like daemonset controller and kubelet. In the parent controller, I need to create specific number of child resource. And I found sometimes after I create the child resource , another reconcile happens and the query result of child resource is empty or less than what I expect ( It looks like the local informer cache is not updated yet), so other child resource was created. After a while, in a new reconcile, the parent controller finds that the total number is more than expected, so extra ones must be deleted. This causes me problem the child controller cannot handle duplicated resource before the duplicated one is deleted. 

So I would like to know if this is the normal situation ( local cache has slower update I assume ) or I am doing something wrong. And if this is normal, is there any way to avoid it? I used the way like forcing name of child resource in a fix pattern (e.g. use the node name) so duplicated child resource creation will fail.  But this doesn't work in all cases. 

Thanks!

/triage support

**Comment by Adirio** [comment]
I couldn't fully understand your issue. DaemonSet controller is just one, kubelet is not a controller. Can you please describe a bit more your CRD and controllers? No need to provide the full spec, only the relevant parts. That way we may be able to know what your controller is doing and how to solve it.

**Comment by chenwng** [comment]
@Adirio Thanks for your reply. Sorry for the confusion. Yes. kubelet is not a controller. Actually I mean I have CRDs working like daemonset/pod and controllers behind  them. The parent CRD  controller is responsible for spawn specific number child CRDs, and controller for child CRD is running on all nodes and responsible for fulfill the job defined in child CRD. In my case, the number of child CRDs must  equal to the number of node. There can be one and only one child CRD for each node. The issue I met is sometimes after the parent controller creates desired number of child CRDs, in the next reconcile the list result of child CRDs is less than desired and he parent controller creates more child CRDs. But actually there are more child CRDs totally than desired. As far as I can tell , there is a cache (informer cache?)  to save the CRDs locally. So I guess the local cache is not updated in the reconcile. I was asking if there is a way to avoid this.

Previously, I tried to use nodename as the name of child CRD, so that no duplicated one can be created. But this doesn't work for non node-related case.

After I posted this, I did some other research. I found the client provided by controller-runtime is a delegatedclient, and it seems resources can be fetched from api-server directly by using unstructured to avoid the local cache.  I haven't tried it to see if it works yet.

If there is other way to solve this issue, please kindly share.

**Comment by Adirio** [comment]
Dodging the cache would be the way to go if you strictly need "fresh" information, but that's more of a controller-runtime related question than kubebuilder itself. Kubebuilder is basically the CLI tool that creates the files you see, the machinery used by the scaffolded files is controllers-runtime.

**Comment by camilamacedo86** [comment]
HI @chenwng, 

As described above by @Adirio, you need to get the "fresh" info. So, according to your description shows that your implementation is not idempotent. In this way, you are creating duplicate objects because you are not verifying if the resource is or not create before performing the operation. 

I believe the detailed explanation made in https://github.com/operator-framework/operator-sdk/issues/2898#issuecomment-619078901 will help you with. 
 
I am closing it as sorted out. However, feel free to re-open if you think that you still requiring help with this subject or raise a new issue with further details for we understand better your scenario as well. Example: 

**What did you do?**

> A clear and concise description of the steps you took (or insert a code snippet).
> 
> **What did you expect to see?**
> A clear and concise description of what you expected to happen (or insert a code snippet).
> 
> **What did you see instead? Under which circumstances?**
> A clear and concise description of what you expected to happen (or insert a code snippet).

/close

**Comment by chenwng** [comment]
@camilamacedo86 Thanks for your answer. You are right about idempotent. But I actually checked the resource before creating new one. The problem here is about the cache. The cache is not always up to date. I found following faq in the controller runtime repo, which describes the exact issue I was facing and provides some useful suggestions. 

I put the link here, in case anyone has the same doubt in the future.
https://github.com/kubernetes-sigs/controller-runtime/blob/master/FAQ.md#q-my-cache-might-be-stale-if-i-read-from-a-cache-how-should-i-deal-with-that
