### ISSUE TITLE
[V3] Marker pattern

### ISSUE THREAD

**Issue by Adirio** [kubernetes-sigs/kubebuilder#1384]
In v2, markers follow `// +kubebuilder:*` pattern.

In v3, we may want to remove the space (`//+kubebuilder:*`) as machine-readable comments should not have spaces by Go conventions.

Code to modify:

https://github.com/kubernetes-sigs/kubebuilder/blob/5dc6055cae706f0b80b05484ffe2632d2de56dd3/pkg/model/file/marker.go#L27-L29

/kind feature

**Comment by camilamacedo86** [comment]
Hi @Adirio, 

I have thought more about this issue and I am not sure if we should do that. See that by default the common practice is to add comments as `// mycomment` with space. Also, note that it has the marker `# ` as well, so this change would not be consistent. 

also, could you add please add the link for we are able to check this Go convection?

**Comment by Adirio** [comment]
/remove-lifecycle stale

@camilamacedo86 You can see in https://github.com/golang/go/issues/37974 how they are even including support in go doc to not document directives (which are machine-readable comments that don't start by a whitespace).

**Comment by kensipe** [comment]
I initially had concerns that this would cause more work due to linters... the gocritic linter does check for spaces after the `//` however it allows for build tags to not have spaces.   
After some research... this makes sense and aligns with recent changes in go conventions
nice recommendation @Adirio !

**Comment by kensipe** [comment]
@camilamacedo86 we can remove the `triage` label (I don't have rights and I don't think we need any more information)

**Comment by Adirio** [comment]
I can take this one
/assign
