### ISSUE TITLE
Homebrew formula should include kubebuilder assets

### ISSUE THREAD

**Issue by EronWright** [kubernetes-sigs/kubebuilder#1397]
While there is a homebrew formula for kubebuilder (#562), it lacks some assets that are generally included in the release tarball.  In particular, `kube-apiserver`, `etcd`, and `kubectl`, which are assumed to reside in `/usr/local/kubebuilder/bin` by the `envtest` package in `controller-runtime` project.  

See [`pks/envtest/server.go`](https://github.com/kubernetes-sigs/controller-runtime/blob/v0.4.0/pkg/envtest/server.go#L65-L73).

I would suggest that the mentioned assets be installed into `/usr/local/Cellar/kubebuilder/x.y.z/bin` but maybe not symlinked by `/usr/local/bin/`.   A user could then set the env variable `KUBEBUILDER_ASSETS` to `/usr/local/Cellar/kubebuilder/x.y.z/bin` to run tests.

/kind feature

**Comment by mengqiy** [comment]
Ideally the 3 testing tools should be included in Homebrew.
Kubebuilder team doesn't officially maintain [Homebrew Formula](https://github.com/Homebrew/homebrew-core/blob/master/Formula/kubebuilder.rb).
They are maintained by hobby contributors. I guess you can go ahead and create PR to update it :)

**Comment by Adirio** [comment]
Closing as out of scope:
> Kubebuilder team doesn't officially maintain Homebrew Formula.

Feel free to reopen if not solved.
/close
