### ISSUE TITLE
Failed to parse the correct GOPATH within the Makefile

### ISSUE THREAD

**Issue by kcswag** [kubernetes-sigs/kubebuilder#1402]
`# Get the currently used golang install path (in GOPATH/bin, unless GOBIN is set)
ifeq (,$(shell go env GOBIN))
GOBIN=$(shell go env GOPATH)/bin
else
GOBIN=$(shell go env GOBIN)
endif`

It takes $GOPATH as the golang install path directly but fails to run controller-gen command if $GOPATH is made of multiple directories like "/usr/local/golang:/usr/local/gopath" which must be separated

**Comment by Adirio** [comment]
Hi kcswag:

First a piece of advice regarding style: using single backquotes (<code>`</code>) to wrap multi-line code fragments prints quite bad, use triple quotes <code>```</code> or even better, provide the perma link:

<details><summary>Triple backquote example:</summary>
<pre>
```make
# Get the currently used golang install path (in GOPATH/bin, unless GOBIN is set)
ifeq (,$(shell go env GOBIN))
GOBIN=$(shell go env GOPATH)/bin
else
GOBIN=$(shell go env GOBIN)
endif
```
</pre>
would look like:

```make
# Get the currently used golang install path (in GOPATH/bin, unless GOBIN is set)
ifeq (,$(shell go env GOBIN))
GOBIN=$(shell go env GOPATH)/bin
else
GOBIN=$(shell go env GOBIN)
endif
```

The `make` is just to specify the language and therefore GitHub will color it properly.
</details>

<details><summary>Link example:</summary>

```
https://github.com/kubernetes-sigs/kubebuilder/blob/9552d129f7d12cc6c7072a1d323ed9f4b461d550/testdata/project-v2/Makefile#L7-L12
```

would look like:

https://github.com/kubernetes-sigs/kubebuilder/blob/9552d129f7d12cc6c7072a1d323ed9f4b461d550/testdata/project-v2/Makefile#L7-L12

</details>

Regarding your issue, controller-gen instalation and finding logic is being discussed in #1351. I will link your issueover there to keep it tracked.

**Comment by camilamacedo86** [comment]
IHMO the best way we solved it is by doing as suggested here: https://github.com/kubernetes-sigs/kubebuilder/issues/1351
