### ISSUE TITLE
[Windows] Document make dependency

### ISSUE THREAD

**Issue by Adirio** [kubernetes-sigs/kubebuilder#1406]
# Description

`make` is not installed in Windows. This dependency should be added to the book.

There are several methods to install `make`, providing some alternatives or a link to useful resources should be considered.

*Please, comment here before taking this task to coordinate development efforts.*

***Note:** this task is tracked in #1405*

**Comment by camilamacedo86** [comment]
Hi @Adirio, 

What is expected here? Only add in the readme [here](https://github.com/kubernetes-sigs/kubebuilder#supportability) that users might be able to try out it in a win SO with  https://www.cygwin.com/ ?

**Comment by Adirio** [comment]
No, you are actually able to build kubebuilder with Windows without cygwin, you do need to install make to run the makefile though. `make` is pre-installed in most systems but not in Windows. It is just one of the pieces needed to achieve full windows compatibility, Makefiles (both the kubebuilder one and the scaffolded one) still need to be tweaked as there are still some Unix-only commands.

**Comment by camilamacedo86** [comment]
In the bug triage meeting, we spoke about to support windows officially and we all agreed that it would be nice. However, we would need help from the community to achieve this goal.

**Comment by camilamacedo86** [comment]
Closed in favor of : https://github.com/kubernetes-sigs/kubebuilder/issues/2940
