### ISSUE TITLE
[Windows] Kubebuilder Makefile

### ISSUE THREAD

**Issue by Adirio** [kubernetes-sigs/kubebuilder#1407]
# Description

Kubebuilders `Makefile` is not compatible with windows as it uses unix-style paths, among other things. Update the Makefile to provide Windows compatibility without loosing Linux and Mac compatibility.

*Please, comment here before taking this task to coordinate development efforts.*

***Note:** this task is tracked in #1405*

**Comment by Adirio** [comment]
#1351 may help with this

**Comment by camilamacedo86** [comment]
In the bug triage meeting, we spoke about to support windows officially and we all agreed that it would be nice. However, we would need help from the community to achieve this goal.

**Comment by MarcosNBJ** [comment]
In the Makefile there are some steps than rely on other scripts, such as "/test/integration.sh" or "/test/e2e/local.sh" for example. Those would also need to be modified in order to make it Windows compatible, right? Or are they already compatible?

**Comment by camilamacedo86** [comment]
Closed in favor of : https://github.com/kubernetes-sigs/kubebuilder/issues/2940
