### ISSUE TITLE
[Windows] Scaffolded Makefile

### ISSUE THREAD

**Issue by Adirio** [kubernetes-sigs/kubebuilder#1408]
# Description

Scaffolded `Makefile` is not compatible with windows as it uses unix-style paths, among other things. Update the Makefile scaffolding to provide Windows compatibility without loosing Linux and Mac compatibility.

This is a backwards incompatible change that will probably require a scaffold version increase to "3".

*Please, comment here before taking this task to coordinate development efforts.*

***Note:** this task is tracked in #1405*

**Comment by Adirio** [comment]
#1351 may help with this

**Comment by camilamacedo86** [comment]
In the bug triage meeting, we spoke about to support windows officially and we all agreed that it would be nice. However, we would need help from the community to achieve this goal.

**Comment by camilamacedo86** [comment]
Closed in favor of : https://github.com/kubernetes-sigs/kubebuilder/issues/2940
