### ISSUE TITLE
[Windows] Tests

### ISSUE THREAD

**Issue by Adirio** [kubernetes-sigs/kubebuilder#1409]
# Description

Test should be runable in Windows systems.

**Additional info:**
- #300
- #1126

*Please, comment here before taking this task to coordinate development efforts.*

***Note:** this task is tracked in #1405*

**Comment by camilamacedo86** [comment]
In the bug triage meeting, we spoke about to support windows officially and we all agreed that it would be nice. However, we would need help from the community to achieve this goal.

**Comment by camilamacedo86** [comment]
Closed in favor of : https://github.com/kubernetes-sigs/kubebuilder/issues/2940
