### ISSUE TITLE
undeclared name: envtest

### ISSUE THREAD

**Issue by caiges** [kubernetes-sigs/kubebuilder#1416]
`kubebuilder create api` generates code with a missing import leading to vetting and build errors.

I've changed the names of the group and controller but in summary:
```
kubebuilder create foo --group bar --version v1 --kind Foo

Create Resource [y/n]
y
Create Controller [y/n]
y
Writing scaffold for you to edit...
api/v1/foo_types.go
controllers/foo_controller.go
Running make:
$ make
which: no controller-gen in (/usr/local/kubebuilder/bin:/home/caiges/.gem/ruby/2.7.0/bin:/home/caiges/.local/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/var/lib/snapd/snap/bin)
go: creating new go.mod: module tmp
go: found sigs.k8s.io/controller-tools/cmd/controller-gen in sigs.k8s.io/controller-tools v0.2.5
/home/caiges/go/bin/controller-gen object:headerFile="hack/boilerplate.go.txt" paths="./..."
go fmt ./...
go vet ./...
# gitlab.com/foo/bar/controllers
vet: controllers/suite_test.go:41:14: undeclared name: envtest
make: *** [Makefile:51: vet] Error 2
2020/03/05 07:22:13 failed to create API: exit status 2
```

Scaffold code produced should build and run without errors.

go: `1.14`
kubebuilder: `2.3.0`
scaffolding version: `2`
controller-runtime: `v0.5.0`
kubernetes: `1.17`
kubectl: `1.16.4`

/kind bug

Adding `"sigs.k8s.io/controller-runtime/pkg/envtest"` to `controllers/suite_test.go` fixes the issue.

**Comment by Adirio** [comment]
You are right, envtest is not scaffolded but I'm not getting any error, the internal `goimports` used at scaffolding seeems to be including it in my case, do not know why yours isn't.

https://github.com/kubernetes-sigs/kubebuilder/blob/800f63a7e41a6a8016d4cb9d583e1705b0812c9d/pkg/scaffold/internal/templates/v2/controller/controller_suitetest.go#L106-L118
