### ISSUE TITLE
Kubebuilder book: Why create a custom metadata field "controller" in job instead of just ownerReferences

### ISSUE THREAD

**Issue by toonsevrin** [kubernetes-sigs/kubebuilder#1422]
I was going through the tutorial in the book for Cronjobs. On [this page](https://book.kubebuilder.io/cronjob-tutorial/controller-implementation.html#2-list-all-active-jobs-and-update-the-status) the concept of a `jobOwnerKey` field is introduced:

```golang
var (
    jobOwnerKey = ".metadata.controller"
```

I don't completely understand why we cannot just rely on the build-in ownerReferences type? Is this because it is not indexable by the cache FieldIndexer and we use the jobOwnerKey solely as an indexable id for it?

**Proposals if this is the case:**
- In the book documentation, explain the function of the jobOwnerKey (If you explain it here, I can also PR it)
- If lists of objects like ownerReferences are not indexable, perhaps start a proposal to make them so?

P.S: I didn't know we could add custom metadata to resources? I assume the jobOwnerKey is only used by the local cache then.

**Comment by Adirio** [comment]
Hi toonsevrin:

I agree with you that better documentation in this sense would help.

If you search for that specific variable you will find it used in two places:

1. To get a filtered list of jobs: [book](https://book.kubebuilder.io/cronjob-tutorial/controller-implementation.html#2-list-all-active-jobs-and-update-the-status)
https://github.com/kubernetes-sigs/kubebuilder/blob/0317c63acfc2fb55a61492817968f09c4f7e20fa/docs/book/src/cronjob-tutorial/testdata/project/controllers/cronjob_controller.go#L121
2. To create the index: [book](https://book.kubebuilder.io/cronjob-tutorial/controller-implementation.html#setup)
https://github.com/kubernetes-sigs/kubebuilder/blob/0317c63acfc2fb55a61492817968f09c4f7e20fa/docs/book/src/cronjob-tutorial/testdata/project/controllers/cronjob_controller.go#L534

In the second code fragment we are creating the index that we are using in the first one, so let's focus on the second one. We are calling [`controller-runtime.Manager.GetFieldIndexer`](https://github.com/kubernetes-sigs/controller-runtime/blob/d0de78d9f1c1de9f8570d67869f7cb47057bca37/pkg/manager/manager.go#L79-L80) which returns a [`controller-runtime/pkg/client.FieldIndexer`](https://github.com/kubernetes-sigs/controller-runtime/blob/d0de78d9f1c1de9f8570d67869f7cb47057bca37/pkg/client/interfaces.go#L115-L126): 

```Golang
// FieldIndexer knows how to index over a particular "field" such that it
// can later be used by a field selector.
type FieldIndexer interface {
	// IndexFields adds an index with the given field name on the given object type
	// by using the given function to extract the value for that field.  If you want
	// compatibility with the Kubernetes API server, only return one key, and only use
	// fields that the API server supports.  Otherwise, you can return multiple keys,
	// and "equality" in the field selector means that at least one key matches the value.
	// The FieldIndexer will automatically take care of indexing over namespace
	// and supporting efficient all-namespace queries.
	IndexField(obj runtime.Object, field string, extractValue IndexerFunc) error
}
```

I think this is pretty clear in-code documentation. Probably some comment could be added to the book in one of the two previously linked places to explain it.

So the answer is, you can use basically any string here to create (and later use) filters. I would not use real paths like `.metadata.name` unless I'm indexing by that field as that may create non-expected issues as you may be shadowing some existing index. Haven't tried it though.

/kind documentation

**Comment by toonsevrin** [comment]
@Adirio thank you for the very thorough and well-documented answer.

If I understand correctly (and correct me if I'm wrong), the index is only created locally, and not on the API?  Would it then not make more sense to use `.local.metadata.controller` or perhaps `.virtual.metadata.controller` as field, ensuring that this field would never ever exist on the server (thus preventing the shadowing behaviour you talked about). 

If not, could you please send some kubernetes documentation regarding the creation of field indices? I was not able to find any.

**Comment by toonsevrin** [comment]
Regarding the documentation update, please confirm that this addition is fine:

The reconciler fetches all jobs owned by the cronjob to delete old jobs. For a more efficient lookup, these jobs will be indexed locally by the controller's name. To do this, a `jobOwnerKey` field is added to the cached job objects, which references the owning controller.


Please feel free to propose something different @Adirio.

**Comment by Adirio** [comment]
I would have to confirm that indexes are not part of kubernetes API to be 100% certain but I'm almost sure that they are not part of k8s.

The text without context is difficult to judge. I would probably modify the comment that can be found the first time it appears as we already mention some of those things:

> To fully update our status, we’ll need to list all child jobs in this namespace that belong to this CronJob. Similarly to Get, we can use the List method to list the child jobs. Notice that we use variadic options to set the namespace and field match (which is actually an index lookup that we set up below).

**Comment by toonsevrin** [comment]
@Adirio I've created PR #1424 for this. I'll close this issue now (we can edit the documentation there).
