### ISSUE TITLE
Remove external kustomize dependency

### ISSUE THREAD

**Issue by toonsevrin** [kubernetes-sigs/kubebuilder#1426]
As kustomize is integrated in kubectl nowadays (without an external dependency), I recommend kubebuilder does the same.

I propose that kustomize becomes an internal go dependency and will provide some documentation here for one of the developers to implement this.

[Here](https://github.com/kubernetes-sigs/kustomize/blob/master/functions/examples/template-go-nginx/) is a simple example of using kustomize as a go dependency. [Here](https://github.com/kubernetes-sigs/kustomize/blob/master/functions/examples/template-go-nginx/image/main.go#L26) is the specific line where a resource is generated with the kustomize go library.

As external behavior shouldn't change for this, it can be implemented in v2. Good luck!

**Comment by Adirio** [comment]
Kustomize dependency is due to the scaffolded Makefile which has some targets that use `kustomize ...` commands. How would you suggest to do this?

P.S.: modifying the scaffolded `Makefile` is definetely a backwards incopatible change that will require a major version bump.

**Comment by toonsevrin** [comment]
I see, I didn't know it was used in the Makefile itself (but makes sense). 

I just took a look at the makefile and why is kustomize not injected like the controller-gen? 

Perhaps this is a good first step? :) Don't understand why this would break any makefile behavior though

**Comment by Adirio** [comment]
I couldn't look the links you provided, if you still have access to `kustomize` command from the `Makefile` it will be backwards compatible, just wanted to note that if you had to modify it it will be for v3.

**Comment by toonsevrin** [comment]
@Adirio all right, please provide me with:
- The location of the Makefile template (so I can update it to add this logic)
- The version of kustomize you would like to use (It should be pinned to a version for consistency and checksum security)

And I'll update the Makefile template, keeping backwards compatibility in mind.

**Comment by Adirio** [comment]
The Makefile template is under `pkg/scaffold/internal/templates/v2/makefile.go`, but do you need to modify it? If you modify it, then this won't be doable for v2.

**Comment by toonsevrin** [comment]
Hm, can you explain why modifying this will require a major release? As long as the signatures and behaviors stay the same, I don't see the problem?On 11 Mar 2020 21:51, Adrián <notifications@github.com> wrote:
The Makefile template is under pkg/scaffold/internal/templates/v2/makefile.go, but do you need to modify it? If you modify it, then this won't be doable for v2.

**Comment by Adirio** [comment]
A project initialized (`kubebuilder init`) will kubebuilder version 2.3.0 (and thus have the old Makefile) should be able to update kubebuilder to 2.4.0 and still behave the same.

**Comment by toonsevrin** [comment]
Hm, I see, @Adirio. Note that the old happy path won't change at all (due to the `which kustomize` check).

Anyways, if you feel that this is for v3 nonetheless, then we can simply add this issue to the roadmap.

**Comment by Adirio** [comment]
If the path doesn't change we won't need an update. It was just a comment, do not take it into account, push a PR and we will be able to eval if it needs a major version bump.

**Comment by toonsevrin** [comment]
All right, the only path that changes is in case kustomize is not installed in your environment (In this case it will be loaded in).

**Comment by toonsevrin** [comment]
This issue should be closed once #1430 (resolves this) merges.
