### ISSUE TITLE
Any reason not set status as subresource by default

### ISSUE THREAD

**Issue by vincent-pli** [kubernetes-sigs/kubebuilder#1438]
I wonder to know the reason behind that: not set `status` as subresource by default.
The `operator-sdk` set it after add new api.

I struggle it for several hours when I try to use client.status().update in `reconscile`, until I found `status` 's subresource is not enable, thanks.

/triage support

**Comment by sarweshsuman** [comment]
Hi @vincent-pli , i am facing same issue. How did you enabled status as subresource ?

**Comment by vincent-pli** [comment]
@sarweshsuman 
Add comment:
`// +kubebuilder:subresource:status`
to your api difinition like this:
```
// +kubebuilder:object:root=true
// +kubebuilder:subresource:status

// Foo is the sample API
type Foll struct {
```

**Comment by camilamacedo86** [comment]
Note. that according to its docs: 

> CRDs can choose to implement the /status and /scale subresources as of Kubernetes 1.13.
> 
> It’s generally recommended that you make use of the /status subresource on all resources that have a status field.
Ref: https://book.kubebuilder.io/reference/generating-crd.html#subresources 

So, I agree with you that by default we could scaffold the recommendation. Doing PR for it. Let's see what the others think about.
