### ISSUE TITLE
Write test to verify the go struct CRD and yaml config CRD are identical

### ISSUE THREAD

**Issue by pwittrock** [kubernetes-sigs/kubebuilder#144]
The go struct CRD generated in the versioned resource package should match the install.yaml CRDs from `create config`.  We should test this against some cases.  Got a report the map[string][string] fields are represented differently.

**Comment by Liujingfang1** [comment]
In my PR #170, I changed the code for parsing the maps like `map[string][string]`. One effect of the change is to fix the different representation in install.yaml and in go struct CRD.

**Comment by pwittrock** [comment]
We should just generate one thing and use it in 2 places.
