### ISSUE TITLE
Ship only kubebuilder binary

### ISSUE THREAD

**Issue by surajssd** [kubernetes-sigs/kubebuilder#1446]
## What broke

I downloaded the release ~binary~ package with the instructions mentioned in: https://book.kubebuilder.io/quick-start.html#installation

And the release package ships with it following binaries:

```
etcd
kube-apiserver 
kubectl
kubebuilder
```

When I just want to download `kubebuilder` binary.

## What did you expect to happen?  What do you think went wrong?

I would like to have a way to just download `kubebuilder` binary only, because I can always download other binaries using the official ways mentioned on the kubernetes docs.

So I would like to request that the release just ships the project binary. Or I would like to know the rationale behind shipping other binaries?

/kind bug

**Comment by camilamacedo86** [comment]
I am not sure if I understood what occurs. Could you please provide the following info for we are able to check the steps executed and why/where you are saying that when you download the kubebuilder binary it will download other as well? 

> 
> **What did you do?**
> A clear and concise description of the steps you took (or insert a code snippet).
> 
> **What did you expect to see?**
> A clear and concise description of what you expected to happen (or insert a code snippet).
> 
> **What did you see instead? Under which circumstances?**
> A clear and concise description of what you expected to happen (or insert a code snippet).
>

**Comment by surajssd** [comment]
I am sorry if I was not very clear before. I wanted to reduce the steps since they are already in the docs. But anyway these are the exact steps to recreate the issue.



> **What did you do?**

I downloaded the release package(tar) with the instructions mentioned in: https://book.kubebuilder.io/quick-start.html#installation. Which were as follows:

```bash
os=$(go env GOOS)
arch=$(go env GOARCH)

# download kubebuilder and extract it to tmp
curl -L https://go.kubebuilder.io/dl/2.3.1/${os}/${arch} | tar -xz -C /tmp/
```


> **What did you see instead? Under which circumstances?**

I saw multiple unrelated binaries(etcd, kube-apiserver, kubectl) shipped with the kubebuilder release package(tar).

```console
$ ll /tmp/kubebuilder_2.3.1_linux_amd64/bin/
.rwxr-xr-x@  19M surajssd  4 Jan  2:21 etcd*
.rwxr-xr-x@ 174M surajssd  4 Jan  2:20 kube-apiserver*
.rwxr-xr-x@  11M surajssd 26 Mar 22:13 kubebuilder*
.rwxr-xr-x@  46M surajssd  4 Jan  2:19 kubectl*
```

I don't need etcd and kube-apiserver because I have a running cluster. And I don't need kubectl because I can download it (following the canonical docs) from [here](https://kubernetes.io/docs/tasks/tools/install-kubectl/).

> **What did you expect to see?**

I expect to see only one binary and that of `kubebuilder`.

```console
$ ll /tmp/kubebuilder_2.3.1_linux_amd64/bin/
.rwxr-xr-x@  11M surajssd 26 Mar 22:13 kubebuilder*
```

**Comment by camilamacedo86** [comment]
HI @surajssd, 

Really tks for the info provided. I checked in the code which gen the releases [here](https://github.com/kubernetes-sigs/kubebuilder/blob/master/build/thirdparty/linux/Dockerfile) and then, they are added.  

@DirectXMan12 @mengqiy @droot  do you know if has any reason for them be added in the bin?

**Comment by camilamacedo86** [comment]
HI @surajssd, 

By looking in the open issues I found: https://github.com/kubernetes-sigs/kubebuilder/issues/686
then it means that this RFE has been planned as well. I will add this issue therefor we know that +1 is looking for it. 

However, shows quite safe we close this one since we have another task for it. I will be closing, but please feel free to re-open if you see that would be required for any reason keep both.
