### ISSUE TITLE
GitHub is not getting the result of the Travis

### ISSUE THREAD

**Issue by camilamacedo86** [kubernetes-sigs/kubebuilder#1457]
**Problem**
When we check the CI jobs. in the Travis, all finished successfully.  However, we are unable to merge since the GB is showing that it still pending.

NOTE: It happens with a few PR's. We can use #1454 as an example.

**Comment by camilamacedo86** [comment]
c/c @estroz @mengqiy @DirectXMan12 @Adirio

**Comment by Adirio** [comment]
It used to happen before but it seems to have increased the number of times we see this error. It usually gets solved with a simple close and re-open. Let's see if this is just a transient problem.

**Comment by camilamacedo86** [comment]
Hi @Adirio, 

Many PR's are facing that and yes, I already tried close and re-open as re-tests. Another example is: https://github.com/kubernetes-sigs/kubebuilder/pull/1449
 
Hi @mengqiy and @DirectXMan12, 

See that the suggested solution to solve it is to revoke the access and authorising it again. 
- https://travis-ci.community/t/github-pr-is-being-built-but-result-is-not-shown/7025/2

Let's try it?

**Comment by DirectXMan12** [comment]
we'd need a github admin for that, I think.  Can't at-mention the github admins team here b/c it's defined in the kubernetes org.  Let me figure out a person to ping.

**Comment by DirectXMan12** [comment]
cc @mrbobbytables

**Comment by mrbobbytables** [comment]
/assign
I'll see what I can do 👍

**Comment by mrbobbytables** [comment]
Okay, there definitely was something funky going on. The webhooks were in place, but there was no app enabled for the repo (or authorized for the org itself...). I've re-authorized it for kubebuilder. Let me know if there continues to be a problem. 👍

**Comment by camilamacedo86** [comment]
Really tks @mrbobbytables. 
I think is safe we close this one. if the same scenario issue started to be faced again we can re-opening it.
