### ISSUE TITLE
API extension support?

### ISSUE THREAD

**Issue by fengye87** [kubernetes-sigs/kubebuilder#1468]
I've tried out webhooks both with & without kubebuilder. It's amazing how kubebuilder can make it so simple and easy to implement webhooks. Since I'm also using [K8s API extension mechanism](https://kubernetes.io/docs/concepts/extend-kubernetes/api-extension/apiserver-aggregation/) to add some custom API endpoints beyond classic CRUD, I'm wondering if kubebuilder can help in this area too, just like how it eases webhook implementation. Any thoughts?

/kind feature

**Comment by johanneswuerbach** [comment]
While not in kubebuilder directly, there is already  https://github.com/kubernetes-sigs/apiserver-builder-alpha
