### ISSUE TITLE
pkg/scaffold: move machinery and filesystem out of internal

### ISSUE THREAD

**Issue by estroz** [kubernetes-sigs/kubebuilder#1472]
Move machinery and filesystem packages out of internal. These packages are useful to [plugin](https://github.com/kubernetes-sigs/kubebuilder/blob/master/designs/extensible-cli-and-scaffolding-plugins-phase-1.md) authors writing plugins that scaffold code.

If this change is acceptable I will make a PR.

/kind feature

**Comment by joelanford** [comment]
This definitely seems like it would be helpful for developing custom plugins. One possible concern I see would be that we would expose `model.Plugin` in the function signatures. (e.g. [`NewScaffold()`](https://github.com/kubernetes-sigs/kubebuilder/blob/abb49b494e5da4f84c90146edeac5393422f514c/pkg/scaffold/internal/machinery/scaffold.go#L58))

As part of the plugin phase 2 work, will we be re-working `model.Plugin` and its interaction with the scaffolding machinery or do we expect those function signatures to remain unchanged?

**Comment by estroz** [comment]
I expect `model.Plugin` to implement `plugin.Base` in phase 2, although the point at which they have access to project state may change. This depends on whether project state is passed during or after scaffolding: #1378.
