### ISSUE TITLE
leader-election-role does not allow patch verb on events 

### ISSUE THREAD

**Issue by wallrj** [kubernetes-sigs/kubebuilder#1474]
It was my understanding that the eventrecorder  patches existing events to help reduce the number of event objects that are stored to etcd.

But the leader-election-role, generated by kubebuilder only allows the create verb on events.
 * https://github.com/kubernetes-sigs/kubebuilder/blob/master/pkg/scaffold/internal/templates/v2/leaderelectionrole.go#L69

The v1 Kubebuilder book also documented that both create and patch verbs are required for events:
 * https://book-v1.book.kubebuilder.io/beyond_basics/creating_events.html

AFAICS the client-go leader-election code calls into this event recorder code which may patch or create and event:
 * https://github.com/kubernetes/kubernetes/blob/v1.18.1/staging/src/k8s.io/client-go/tools/events/event_broadcaster.go#L206

**Comment by camilamacedo86** [comment]
It shows reasonable for me to allow the verb patch by default as well.  Let's if someone has some reason for we do not move forward with. Done a PR:
