### ISSUE TITLE
Let's create a cookbook with useful patterns

### ISSUE THREAD

**Issue by hendrikmaus** [kubernetes-sigs/kubebuilder#1475]
Hey everyone, I would like to get some feedback from the community on an idea I had, which is to start a cookbook with useful patterns for operator development.

What I immediately appreciated about the kubebuilder project was the git book - fantastic effort. Makes the entry into the operator realm very smooth and creates a good understanding of the basics.
Now, correct me if I am wrong, often enough the real life use cases stretch beyond the very basics and this is where I want to hook in and start to collect more knowledge as I could not find anything out there.

For example: I specifically searched for the involvement of external resources. May it be reconciling a load balancer of a cloud provider, listening to a message queue, watching a GitHub PR, you name it.
This kind of problem is never touched in the tutorials out there, but I think it is pretty common - at least that is what my gut feeling says.

I will cut it here and would be very happy to discuss your ideas.

**Comment by alexeldeib** [comment]
Dynamically adding new controllers at runtime would be a good cookbook example, as well as showcasing alternative structures for projects as they grow.

I'm happy to help write some samples if we develop a list of desired recipes 🙂

**Comment by otakumike** [comment]
I think this is a fantastic idea. I've been writing operators for a little while now and even though the git book is very helpful, it leaves me wondering if I'm following best practices and designing my controllers well. Having a resource I can look to for examples of real-world scenarios would be a great help I think

**Comment by alexeldeib** [comment]
As far as implementation, I think this can _probably_  be as simple as adding a top level section (maybe near reference) to https://book.kubebuilder.io/ and adding full source code back in github

**Comment by hendrikmaus** [comment]
Ok, initial PR is opened. Should we continue to collect recipes in this issue for now?
I'd also be happy to write some samples.

**Comment by drpaneas** [comment]
> I'd also be happy to write some samples.

+1 -- I think at least one example would be great for the beginning, so to establish what kind of contributions are expected in some sort of way.
