### ISSUE TITLE
Kubebuilder scaffolding for "external" webhooks

### ISSUE THREAD

**Issue by sethp-nr** [kubernetes-sigs/kubebuilder#1476]
We have a few small controllers that operate exclusively over types defined in other projects:

- A webhook-only system that decorates corev1 Service objects with TLS certificate annotations
- A reconciler for a cluster-api Machine that decorates the associated Node with information from the Machine object
- A webhook & reconciler combo that looks for PDBs associated with Deployments and provides some auditing / defaulting behaviors

These share the common attribute that they don't define any types within the project, but import them from elsewhere. In building these projects with Kubebuilder we've run into a few rough edges so far:

- `make generate` and `make manifests` both expect an `api/` directory to exist
- The `kustomize` that's templated out by `kubebuilder init` expects a `config/crd` directory, which causes `make deploy` to fail
- We didn't find a subcommand for adding a webhook or controller for a type defined elsewhere
- & likely others that I'm forgetting or we haven't found yet

Does generating controller/webhook-only projects that  make sense as a responsibility for kubebuilder to take on? If you believe it is, I'd be glad to start breaking this up into more specific tickets and doing work against them.

**Comment by camilamacedo86** [comment]
Hi @sethp-nr, 

I am not sure if I understood properly your issue. However, note that you are able to customize the path where the CRD's and webhook will be generated and the commands as you wish in the Makefile created for your project. See:

> Generate manifests e.g. CRD, RBAC etc.
> manifests: controller-gen
> 	$(CONTROLLER_GEN) $(CRD_OPTIONS) rbac:roleName=manager-role webhook paths="./..." output:crd:artifacts:config=config/crd/bases

> Uninstall CRDs from a cluster
> uninstall: manifests kustomize
> 	$(KUSTOMIZE) build config/crd | kubectl delete -f -

Is it that you are looking for? If not, could you please provide the info as follows? I think it will make easier understand what is your scenario and what you are looking for.  

> **What did you do?**
> A clear and concise description of the steps you took (or insert a code snippet).
> 
> **What did you expect to see?**
> A clear and concise description of what you expected to happen (or insert a code snippet).
> 
> **What did you see instead? Under which circumstances?**
> A clear and concise description of what you expected to happen (or insert a code snippet).
>

**Comment by sethp-nr** [comment]
I think I'm asking a slightly different question: where do you feel use-cases like [webhooks for core types](https://book.kubebuilder.io/reference/webhook-for-core-types.html) falls in terms of kubebuilder's responsibility? As it stands, it is possible to use kubebuilder to make a process that intercepts core types, but there's definitely a feeling of "fighting the tool."

Put another way:

> What did you do?

```
kubebuilder init
# followed the docs linked above and added a "pod annotator" to the project
make deploy # this command fails 
```

> What did you expect to see?

That the steps above would produce a "pod annotator" that I could deploy to my clusters. That's sort of the first issue, but there's a lot of separate use-cases that go beyond that too.

> What did you see instead? Under which circumstances?

The docker build and deploy steps both fail for the reasons described above. 

----------------

If you feel this is within kubebuilder's scope of responsibility, then I think my next steps are to turn this into an "umbrella" issue of sorts and create tasks/PRs for a few different things:

- Get the current thing working (make it so that the steps above produce a running container)
- Scaffolding assistance around cert-manager & turning the "right" things on or off in the kustomize config
- Scaffolding assistance like  `kubebuilder create webhook --for pods` that would replace most of the setup steps listed in the documentation
- Scaffolding assistance like `kubebuilder create controller --for poddisruptionbudgets.policy` that would set me up with a Reconcile function for `PodDisruptionBudget`s from the `k8s.io/api/policy/v1beta1` package
- Getting both the `create webhook` and `create controller` subcommands to work with Go types external to both the core kubernetes project and the current kubebuilder project: maybe something like `kubebuilder create controller --for machines.cluster.x-k8s.io --from sigs.k8s.io/cluster-api` ?

This seems like a not-small amount of work, which is why I wanted to ask what you thought before I started slinging PRs or very fine-grained issues. The kubebuilder community meetings are kind of hard for me to make, but I could try to attend one of those if you'd rather discuss synchronously.
