### ISSUE TITLE
Is there a binary release available for zlinux s390 ?

### ISSUE THREAD

**Issue by apasrini** [kubernetes-sigs/kubebuilder#1491]
Wanted to know if there is a release specific for s390 zlinux platform ?

Release page does not have a s390x build https://github.com/kubernetes-sigs/kubebuilder/releases

**Comment by camilamacedo86** [comment]
HI @apasrini, 

The available one for kubebuilder is in https://github.com/kubernetes-sigs/kubebuilder/releases. 
IHMO would be ok add supportability for other archs. @DirectXMan12 @mengqiy wdyt? Could we accepted as RFE improve the release script to gen an s390x as well?

Also, if you would like to check SDK has been gen a binary for x390x. See: https://github.com/operator-framework/operator-sdk/releases.

**Comment by camilamacedo86** [comment]
/kind feature 

Add support to gen x390x bin in the release.

**Comment by DirectXMan12** [comment]
... are people actually running the scaffolder itself directly on a mainframe?  (genuine question)

**Comment by camilamacedo86** [comment]
Hi @DirectXMan12, 

I know that the IBM folks have been asking it as a requirement for SDK. See: https://github.com/operator-framework/operator-sdk/search?q=s390x&type=Issues  

My guess is that their cloud services are using this architecture. See: https://www.ibm.com/uk-en/marketplace/cloud-private-on-z-and-linuxone also see https://www.ibm.com/blogs/systems/red-hat-openshift-now-available-ibm-z-linuxone/

**Comment by estroz** [comment]
Travis can build against s390 so this is possible. We release `operator-sdk` for this arch in this manner. I will say that trying to support not-often-used architectures can be a pain. Perhaps it would be best to link docs on how to compile for a specific arch instead of supporting more than amd, arm, and darwin.

**Comment by DirectXMan12** [comment]
my concerns are largely around testing, reproduction, etc.  

>  link docs on how to compile for a specific arch instead of supporting more than amd, arm, and darwin

:+1: this sounds reasonable to me.

**Comment by camilamacedo86** [comment]
/kind documentation

A user would need to fork the project and built the image using the arch type wished. If someone would like to contribute with this doc see [here](https://sdk.operatorframework.io/docs/contribution-guidelines/developer-guide/#how-the-operator-sdk-binaries-are-built) the SDK which described how to add a new binary build and test it. It might help you see the required steps to doc how to do it for kubebuider.
