### ISSUE TITLE
Kubebuilder validation markers are documented multiple times

### ISSUE THREAD

**Issue by tamalsaha** [kubernetes-sigs/kubebuilder#1513]
Kubebuilder book defines the same marker multiple times. https://book.kubebuilder.io/reference/markers/crd-validation.html

Is that by mistake? If yes, can you please fix this? It is very confusing to a new user of these markers.

/kind bug

**Comment by camilamacedo86** [comment]
Hi @tamalsaha, 

Could you please give an example of what marker is defined duplicated? See that, for example, the marker `kubebuilder:validation:MaxItems` is not equals `kubebuilder:validation:MaxLength` and the idea here is to allow users to check all options.

**Comment by hasbro17** [comment]
Pretty much the entire block of markers is duplicated after `//+optional` from what I can see.
Might be something with the marker generation script.

**Comment by camilamacedo86** [comment]
I see what you mean 👍 . Note that first, all options are (on field) then it has (on type). 
However, I agree that it is something that requires attention.

**Comment by gabbifish** [comment]
These duplicated markers are actually not duplicated, but correspond to markers used for types vs fields. We can amend the documentation to deduplicate the appearance of markers and specify that a marker can be used on types and fields.

**Comment by Adirio** [comment]
IMO, we should make clear that markers are grouped by targets (field, type, ...), and therefore if a marker is valid for different targets it will appear in both sections, instead of removing them (or deduplicating them). Maybe even explicitly splitting them into targets using second-level titles.
