### ISSUE TITLE
Webhook Defaulter does not throw error

### ISSUE THREAD

**Issue by ifilonenko** [kubernetes-sigs/kubebuilder#1514]
```
var _ webhook.Defaulter = &MyCrd{}

// Default implements webhook.Defaulter so a webhook will be registered for the type
func (r *MyCrd) Default() {
    ...
}
```

There is no way to catch errors that occur from mutations that you wish to apply. Example, say you wish to grab information from the ownerReferences and apply some kind of default mutation. As a result of the return type, there is no way to catch a `k8sClient()` error

kubebuilder version: v0.6.0 (master)

/kind bug

**Comment by camilamacedo86** [comment]
HI @ifilonenko, 

Sorry, but it is not clear for me the goal of this task. Could you please provide the following information? 

> #### What did you do?
> 
> #### What did you expect to see?
> 
> #### What did you see instead? Under which circumstances?
> 

Also, if it is a bug could you plea help us and check if it is not something that is already fixed on the master branch with the plugin `go/v3-alpha`? For you check it, you can create a new project with `kubebuilder init --plugins=go/v3-alpha` and do the steps required to reproduce the issue. Also, could you please add these steps in this issue as well?

**Comment by ifilonenko** [comment]
The goal is to have the Default() method throw an error so that I can return nil when no error and return errors when they appear, like in the validator

**Comment by prafull01** [comment]
Hi @ifilonenko 

This can not be done on the kubebuilder side as kubebuilder only implements the method defined in the interface of controller-runtime.
Please see the defaulting interface here in the controller-runtime: https://github.com/kubernetes-sigs/controller-runtime/blob/9975e296899a4843fe69e9d1675fee10957ab694/pkg/webhook/admission/defaulter.go#L28

**Comment by camilamacedo86** [comment]
Hi @ifilonenko, 

As @prafull01 described above, could you please raise this RFE in the [controller-runtime]( https://github.com/kubernetes-sigs/controller-runtime)? Also, I'd like to suggest you add the use case where it is required to illustrate better what kind of problem it would address. 

In this way, I hope that it fine we close this one. However, please feel free to ping us if you think that it should be re-opened.
