### ISSUE TITLE
Add envtest example for CronJob controller

### ISSUE THREAD

**Issue by hasbro17** [kubernetes-sigs/kubebuilder#1518]
As I was reading the docs for envtest I see the following:

> Until more documentation has been written, your best bet to get started is to look at some existing examples, such as:
> - Azure Databricks Operator: see their fully fleshed-out [suite_test.go](https://github.com/microsoft/azure-databricks-operator/blob/0f722a710fea06b86ecdccd9455336ca712bf775/controllers/suite_test.go) as well as any *_test.go file in that directory [like this one](https://github.com/microsoft/azure-databricks-operator/blob/0f722a710fea06b86ecdccd9455336ca712bf775/controllers/secretscope_controller_test.go).

I assume `more documentation` probably meant the following sub-section that was added later on which covers the setup and configuration of envtest but references no example test for users to look at.
https://book.kubebuilder.io/reference/testing/envtest.html

While the Azure Databricks Operator example seems sufficient I was wondering if it would be beneficial to have a envtest example for the [CronJob controller](https://github.com/kubernetes-sigs/kubebuilder/blob/f07a0146a40b1dc4048b1caaf075efcf1312aa00/docs/book/src/cronjob-tutorial/testdata/project/controllers/cronjob_controller.go) itself so that we have a canonical example to reference within the repo.

Low priority but I wanted to see if there's interest in this before trying to write any tests for the CronJob controller.

/kind documentation

**Comment by gabbifish** [comment]
I’ve been working on docs for a generalized approach to envtest in the context of writing tests for the CronJob example :) Planning on opening a PR for it tomorrow morning, and I’ll reference it here. (It will be my first kubebuilder project PR so I will especially appreciate feedback/guidance on it).

**Comment by gabbifish** [comment]
Entrypoint docs for envtest, in the context of the cronjob tutorial, were put into the production kubebuilder book with PR https://github.com/kubernetes-sigs/kubebuilder/pull/1579. I think we can consider this issue closed :)
