### ISSUE TITLE
can we add more detailed example in metrics doc?

### ISSUE THREAD

**Issue by caneGuy** [kubernetes-sigs/kubebuilder#1522]
After following https://book.kubebuilder.io/reference/metrics.html?highlight=metr#metrics i can not see the registered metrics on prometheus UI. Some suggestion:
1.  add a ServiceMonitor yaml example?
2.  add a complete example for additional metrics?
3. the picture in the doc only show original metrics of prometheus.IIUC, all the metrics can also be seen if we do not deploy a servicemonitor

**Comment by caneGuy** [comment]
@camilamacedo86 thanks!

**Comment by camilamacedo86** [comment]
HI @caneGuy, 

It is not clear for me if you are looking for improvements in the docs based on your experience following it or help to achieve your goal and use the Prometheus Operator to export the metrics. Could you please let us know? 

Also, if you are looking for help with, could you please to provide the following info:

> **What did you do?**
> A clear and concise description of the steps you took (or insert a code snippet).
> 
> **What did you expect to see?**
> A clear and concise description of what you expected to happen (or insert a code snippet).
> 
> **What did you see instead? Under which circumstances?**
> A clear and concise description of what you expected to happen (or insert a code snippet).
> 

Also, did you installed the Prometheus Operator? If yes, did you follow you the install [doc](https://github.com/coreos/kube-prometheus#installing)? Are you using minikube? If yes, did you follow-ups its pre-requisites describe in the Prometheus Operator [see](https://github.com/coreos/kube-prometheus#minikube)?

**Comment by camilamacedo86** [comment]
/close 
since it achieves the time without having no reply provide further info for we know how we can address it.
