### ISSUE TITLE
[book] KUBEBUILDER_ASSETS env var not used anywhere

### ISSUE THREAD

**Issue by tengqm** [kubernetes-sigs/kubebuilder#1555]
The current kubebuilder book, in its [quick start](https://book.kubebuilder.io/quick-start.html) section, mentions that an environment variable `KUBEBUILDER_ASSETS` should be set to something when installing `kubebuilder`. However, this environment is not used anywhere in the code base (including Go and scripts). Is it something we forgot to remove? 

> (you'll need to set the KUBEBUILDER_ASSETS env var if you put it somewhere else)

**Comment by DirectXMan12** [comment]
it's used by controller-runtime's envtest: https://github.com/kubernetes-sigs/controller-runtime/blob/master/pkg/envtest/server.go#L37

**Comment by tengqm** [comment]
Thanks for the info.
