### ISSUE TITLE
Kustomize support for config/samples

### ISSUE THREAD

**Issue by joelanford** [kubernetes-sigs/kubebuilder#1573]
**What do you want to happen?**
When I run `kubebuilder create api`, a sample CR gets created in `config/samples`. I'm wondering if there is any appetite for `config/samples` to be a valid kustomize directory, such that one could run `kustomize build config/samples` to get kubectl-appliable yaml.

If we were to add such a feature, I think we would add a scaffold that supports updates via a marker such that `kubebuilder create api` would append the new sample file to the `resources` list in `config/samples/kustomization.yaml`.

**Use cases:**
- After running `make deploy`, I want to be able to quickly spin up a sample set of CRs using `kustomize build config/samples | kubectl apply -f -`
- I want to be able to utilize all of the benefits of kustomize with the samples, e.g. to set a namePrefix, commonLabels, overlays, etc.
- I want to include samples in other kustomize scenarios. E.g.:
  - Generating Operator Lifecycle Manager (OLM) manifests where the combination of `config/default` and `config/samples` is useful.
  - Executing schema validation of samples by building CRDs and samples and verifying CRDs exist for each sample and that each sample validates against the CRD schema. This would combine `config/crd` and `config/samples`.

**Is there currently another issue associated with this?**
Not that I could find.

**Does it require a particular kubernetes version?** No

/kind feature

**Comment by Adirio** [comment]
Just a note: #1831 approach may be also considered

**Comment by joelanford** [comment]
/lifecycle frozen

Since this has label `triage/accepted`

**Comment by camilamacedo86** [comment]
It should be done in the kustomize/v2-alpha plugin.

**Comment by camilamacedo86** [comment]
@estroz I unassigned this one since we have no longer with and others might able to help with this one.
