### ISSUE TITLE
Provide helper function for conditions

### ISSUE THREAD

**Issue by woohhan** [kubernetes-sigs/kubebuilder#1574]
Kubernetes seems to have chosen Conditions as the standard instead of Phase.
<https://github.com/kubernetes/kubernetes/issues/50798>

 Operator SDK provides functions for Condition. It's also useful if Kubebuilder provides these features.
<https://github.com/operator-framework/operator-sdk/blob/master/pkg/status/conditions.go>

/kind feature

**Comment by camilamacedo86** [comment]
Hi @woohhan,

It shows done now in https://github.com/kubernetes/kubernetes/pull/92717. So, could we not close this one?

**Comment by woohhan** [comment]
> Hi @woohhan,
> 
> It shows done now in [kubernetes/kubernetes#92717](https://github.com/kubernetes/kubernetes/pull/92717). So, could we not close this one?

Thanks for the reply, I will close the issue.
