### ISSUE TITLE
Remove the word "sanity" from our codebase

### ISSUE THREAD

**Issue by vincepri** [kubernetes-sigs/kubebuilder#1585]
- https://github.com/kubernetes-sigs/kubebuilder/blob/38343942a397a02559bfdd46f3d31257d1561f98/test/e2e/v2/e2e_suite.go#L272
- https://github.com/kubernetes-sigs/kubebuilder/blob/38343942a397a02559bfdd46f3d31257d1561f98/test/e2e/v2/e2e_suite.go#L281
- https://github.com/kubernetes-sigs/kubebuilder/blob/38343942a397a02559bfdd46f3d31257d1561f98/test/e2e/v3/e2e_suite.go#L272
- https://github.com/kubernetes-sigs/kubebuilder/blob/38343942a397a02559bfdd46f3d31257d1561f98/test/e2e/v3/e2e_suite.go#L281

/wg naming
/kind cleanup

**Comment by camilamacedo86** [comment]
@vincent-pli done, to small for we keep an issue open for that, so I decide to do asap 👍 
/assign @camilamacedo86
