### ISSUE TITLE
unable to run the tests scaffold for the projects without the kb bin in /usr/local/kubebuilder/bin

### ISSUE THREAD

**Issue by camilamacedo86** [kubernetes-sigs/kubebuilder#1599]
The following error is faced when the KB is installed from master or its bin be added in another place when the tests are executed via the makefile targets:

```
  Unexpected error:
      <*fmt.wrapError | 0xc000109ec0>: {
          msg: "failed to start the controlplane. retried 5 times: fork/exec /usr/local/kubebuilder/bin/etcd: no such file or directory",
          err: {
              Op: "fork/exec",
              Path: "/usr/local/kubebuilder/bin/etcd",
              Err: 0x2,
          },
      }
      failed to start the controlplane. retried 5 times: fork/exec /usr/local/kubebuilder/bin/etcd: no such file or directory
  occurred
```

Root cause explained in: https://github.com/kubernetes-sigs/kubebuilder/issues/686#issuecomment-647376924

**Comment by camilamacedo86** [comment]
An possible solution is to setup the bins as: 

```
OS=$(uname -s | tr '[:upper:]' '[:lower:]')
ARCH=$(uname -m | sed 's/x86_64/amd64/')
curl -fsL "https://storage.googleapis.com/kubebuilder-tools/kubebuilder-tools-1.16.4-${OS}-${ARCH}.tar.gz" -o kubebuilder-tools
tar -zvxf kubebuilder-tools
sudo mv kubebuilder/ /usr/local/kubebuilder
```

**Comment by georgettica** [comment]
if these files are required, integrating into `brew` is also helpful

**Comment by camilamacedo86** [comment]
Hi @georgettica, 

If you run brew install kubebuilder it will install the binaries because they are shipped with Kubebuilder currently. The goal here is in the long term we do not need to ship them.

It was solved for v3+. See: https://github.com/kubernetes-sigs/kubebuilder/pull/1626 

So, when we are able to removed the support for v2 and removed it from the projects as was done for v1 it will be solved.

**Comment by georgettica** [comment]
@camilamacedo86 I installed kubebuilder and they were not installed
