### ISSUE TITLE
Add boilerplate support for generation commands

### ISSUE THREAD

**Issue by pmorie** [kubernetes-sigs/kubebuilder#160]
...so that we can generate artifacts with the correct boilerplate text for projects that require it.

Found while reviewing https://github.com/kubernetes/cluster-registry/pull/225.

cc @perotinus

**Comment by pmorie** [comment]
Oh, nice

**Comment by pwittrock** [comment]
Updated the documentation:

http://book.kubebuilder.io/beyond_basics/boilerplate.html
