### ISSUE TITLE
CRD listers with lister-gen

### ISSUE THREAD

**Issue by champak** [kubernetes-sigs/kubebuilder#1605]
I was looking for generated listers with kubebuilder version 2.2.0 and do not see the CRD lister apis. I think in an earlier version I had seen the tag +genclient trigger generation of the lister apis. Is there a new tag to use ? I could not locate one in the list and do not see a reference in the docs.  The basic List apis are simple but would rather use the generated versions than manually created versions.

**Comment by camilamacedo86** [comment]
Hi @champak, 

Sorry, but your question is not clear to me. Could you please provide the following info?  

```
#### What did you do?

<!-- A clear and concise description of the steps you took (or insert a code snippet). -->

#### What did you expect to see?

<!-- A clear and concise description of what you expected to happen (or insert a code snippet). -->

#### What did you see instead? Under which circumstances?

<!-- A clear and concise description of what you expected to happen (or insert a code snippet). -->

#### Environment

**Kubernetes cluster type:**

<!-- The type of cluster used for testing/deployment, ex. "vanilla", "OpenShift" -->

`$ kubebuilder version`

<!-- Insert the output of `kubebuilder version` here. -->

#### Possible Solution

<!-- Only if you have suggestions on a fix for the bug -->

#### Additional context

<!-- Add any other context about the problem here. -->
````

**Comment by camilamacedo86** [comment]
Hi @champak, 

I am closing this one because it is for while open without the required info be provided. However, if you still facing problems with feel free to raise a new issue with all details for we are able to help you with. 

Really thank you.
