### ISSUE TITLE
Add comments for exported methods in generated controllers

### ISSUE THREAD

**Issue by bvwells** [kubernetes-sigs/kubebuilder#1606]
It would be great to have the exported methods in the generate controllers documented.

i.e. 
```
// Reconcile ...
func (r *...) Reconcile(req ctrl.Request) (ctrl.Result, error) {
...

// SetupWithManager ...
func (r *...) SetupWithManager(mgr ctrl.Manager) error {
...
```

Would be happy to submit a PR.

/kind feature

**Comment by camilamacedo86** [comment]
Hi @bvwells, 

Please,  feel free to push a PR with against master. Note that we can just update/change the v3+ plugin which means that your changes in the scaffold should be performed just in : https://github.com/kubernetes-sigs/kubebuilder/tree/master/pkg/plugin/v3
