### ISSUE TITLE
confusing about build config in netlify.toml 

### ISSUE THREAD

**Issue by hzliangbin** [kubernetes-sigs/kubebuilder#1607]
Hi, I noticed that kubebuilder-book use netlify to preview PR request. 
I have a question about build config in netlify.toml.
According to [docs](https://docs.netlify.com/configure-builds/file-based-configuration/#sample-file), publish dir is relative to the base directory if one has been set. So it would be docs/book/docs/book/book as netlify.toml presents.  In fact it should be docs/book/book.

I am new to netlify. Please let me know if I mistake something. thanks.
 

/triage support

**Comment by camilamacedo86** [comment]
Hi @hzliangbin, 

I am unable to face any issue to check the preview of the PR's pushed against the master or the production docs. So, what problem with Kubebuilder and its docs preview you are facing that you require help with?

**Comment by hzliangbin** [comment]
@camilamacedo86 thanks for your reply. I managed to  make it work now. but the config is a little different. not a big deal.
