### ISSUE TITLE
Question about kubebuilder and apiserver-builder

### ISSUE THREAD

**Issue by devdattakulkarni** [kubernetes-sigs/kubebuilder#161]
Following commit added example of memcached-api-server.

https://github.com/kubernetes-sigs/kubebuilder/commit/0724374cb7c03cad6807580497ae52520d32c977

Just so that I understand, this is an example of adding an add-on api server behind the kube api aggregator, correct?

If so, should kubebuilder be used for creating such apis or should we be using apiserver-builder for that?

https://github.com/kubernetes-incubator/apiserver-builder

**Comment by pwittrock** [comment]
kubebuilder is CRD based.  Do you need AA or are CRDs sufficient?

**Comment by pwittrock** [comment]
Feel free to reach out on the slack channel (kubebuilder) and mention @droot to follow up.
