### ISSUE TITLE
why not add MaxConcurrentReconciles as an option when initialize the controller?

### ISSUE THREAD

**Issue by lut777** [kubernetes-sigs/kubebuilder#1616]
I found that the controller defines MaxConcurrentReconciles, and provides the ability to start multiple goroutines to run Reconcile. 
But I couldn't find any place in the scaffolding to configure this parameter.
So, why not provide such a configuration point in the scaffolding?
how about adding a controller.Options in Reconciler.SetupWithManager with the builder.WithOptions? I tried and verified that there are multiple reconcilers running.

/kind feature

**Comment by camilamacedo86** [comment]
Hi @lut777, 

You have the ability to configure the  `MaxConcurrentReconciles ` in the `main.go` where the [Manager](https://godoc.org/sigs.k8s.io/controller-runtime/pkg/manager#Manager) is defined, such as:


```go
	mgr, err := ctrl.NewManager(ctrl.GetConfigOrDie(), ctrl.Options{
		Scheme:             scheme,
		MetricsBindAddress: metricsAddr,
		Port:               9443,
		LeaderElection:     enableLeaderElection,
		MaxConcurrentReconciles: runtime.NumCPU(),
		LeaderElectionID:   "dd1da13f.testproject.org",
	})
	if err != nil {
		setupLog.Error(err, "unable to start manager")
		os.Exit(1)
	}
```

In this way, I am closing this one as solved. However, feel free to re-open if you see that it still required. 

/assign @camilamacedo86 
/close
