### ISSUE TITLE
Inconsistent sample code for cronJob tutorial

### ISSUE THREAD

**Issue by Colstuwjx** [kubernetes-sigs/kubebuilder#1630]
Hi team,

I'm learning how to use kubebuilder with the tutorial, and I've seen the [SetupWithManager](https://book.kubebuilder.io/cronjob-tutorial/controller-implementation.html#setup)  func inside the book is:

```
func (r *CronJobReconciler) SetupWithManager(mgr ctrl.Manager) error {
    ...
    if err := mgr.GetFieldIndexer().IndexField(&kbatch.Job{}, jobOwnerKey, func(rawObj runtime.Object) []string {
        // grab the job object, extract the owner...
        job := rawObj.(*kbatch.Job)
        owner := metav1.GetControllerOf(job)
        if owner == nil {
            return nil
        }
        // ...make sure it's a CronJob...
        if owner.APIVersion != apiGVStr || owner.Kind != "CronJob" {
            return nil
        }

        // ...and if so, return it
        return []string{owner.Name}
    }); err != nil {
        return err
    }
    ...
}
```

But the sadly truth is that it didn't work, and would build fail. What's more, I've searched the sourcecode in our repo, and it's different to the book! See the following code snippet ( which source code is [here](https://github.com/kubernetes-sigs/kubebuilder/blob/master/docs/book/src/cronjob-tutorial/testdata/project/controllers/cronjob_controller.go#L547) ):

```
func (r *CronJobReconciler) SetupWithManager(mgr ctrl.Manager) error {
        ...
	if err := mgr.GetFieldIndexer().IndexField(context.Background(), &kbatch.Job{}, jobOwnerKey, func(rawObj runtime.Object) []string {
		// grab the job object, extract the owner...
		job := rawObj.(*kbatch.Job)
		owner := metav1.GetControllerOf(job)
		if owner == nil {
			return nil
		}
		// ...make sure it's a CronJob...
		if owner.APIVersion != apiGVStr || owner.Kind != "CronJob" {
			return nil
		}

		// ...and if so, return it
		return []string{owner.Name}
	}); err != nil {
		return err
	}
        ...
}
```

We may need to update this part!

/kind bug

**Comment by Colstuwjx** [comment]
@camilamacedo86 @DirectXMan12 I've checkout the repo on my laptop, after I typed `cd docs/book; bash ./install-and-build.sh`, I found it generates a `book` dir under the `docs/book` directory. See the following output:

```
➜  book git:(master) ✗ cat cronjob-tutorial/testdata/project/controllers/cronjob_controller.go|grep -i "mgr.GetFieldIndexer()"
	if err := mgr.GetFieldIndexer().IndexField(context.Background(), &kbatch.Job{}, jobOwnerKey, func(rawObj runtime.Object) []string {
```

It seems same to the source code! But our [website](https://book.kubebuilder.io/cronjob-tutorial/controller-implementation.html#setup) did NOT!

Do we need to update netlify content? Or sth caused the netlify build broken?
Thanks!

**Comment by DirectXMan12** [comment]
Oh!  A while ago we switched to using a staging branch for the published version of the book.  https://master.book.kubebuilder.io/ has the "nightly" content.  The book is actually built off of the book-v2 branch, which is supposed to be updated on each release.

It may be out of date, though.

**Comment by gabbifish** [comment]
Hi @Colstuwjx! @DirectXMan12 is right, the current version of the book in the `book-v2` branch (what you see on http://kubebuilder.io/) is slightly outdated. 

What do folks think about having automated cherry-picks of typo/docs bugfix PRs from the staging branch to the production branch, so we can more efficiently propagate minor fixes like this to production? 

We could use the new PR label scheme introduced in https://github.com/kubernetes-sigs/kubebuilder/pull/166 to distinguish between which docs changes are tied to a new feature (:docs:) vs which docs changes are patch fixes (:bug:), so we could avoid pushing docs for new features into production while still letting important docs fixes through.

**Comment by DirectXMan12** [comment]
@gabbifish if you can get that working reliably, I'm all for it :-).  That wounds wonderful.

**Comment by camilamacedo86** [comment]
Hi @gabbifish, 

I will move on this for v3-alpha for we remember to update the samples used in docs before we release an stable version. However,  wdyt about we raise a new issue as RFE specifically to track this idea over the docs cherry-pick?

**Comment by camilamacedo86** [comment]
Hi @gabbifish, 

As we spoke about it and agreed on the RFE for the docs is tracked in: https://github.com/kubernetes-sigs/kubebuilder/issues/1836.
Also, we added a new issue to update the samples in the docs with the v3+ plugin and solve the issues. See: https://github.com/kubernetes-sigs/kubebuilder/issues/1835 

Since the problem that was raised here is sorted out I am closing this one.
