### ISSUE TITLE
would be nice the edit multi-group:true fixes the layout of the project and move the pre-existing api's

### ISSUE THREAD

**Issue by camilamacedo86** [kubernetes-sigs/kubebuilder#1640]
Currently, when we use the command edit --multigroup=true it will update the Dockerfile and the PROJECT file and then the new API's will be scaffolded in a diff layout where the group is use in the path. 

However, if the project has API's scaffolded already users requires to move them and create the path with the group name manually. I think would be nice if the command could do all process instead of requires manually changes.

**Comment by camilamacedo86** [comment]
c/c @estroz

**Comment by prafull01** [comment]
@camilamacedo86 If no one is working on it, I would be happy to pick it up.

**Comment by camilamacedo86** [comment]
Hi @prafull01, 

Your help is more than welcome 👍 it is great . Please, feel free to help and work on in any issue that pleases you.

**Comment by camilamacedo86** [comment]
Hi @prafull01, 

I think would be easier if we could to do first: https://github.com/kubernetes-sigs/kubebuilder/issues/1689. WDYT?

**Comment by camilamacedo86** [comment]
Another ticked that is related and could make easier we keep the current behaviour for v2 and new behaviour for v3 only would be the issue https://github.com/kubernetes-sigs/kubebuilder/issues/1639 to make the edit to be a plugin as well. See that we have a plugin to [create the api](https://github.com/kubernetes-sigs/kubebuilder/blob/master/pkg/plugin/v3/api.go), other to [init the project](https://github.com/kubernetes-sigs/kubebuilder/blob/master/pkg/plugin/v3/init.go) and another to scaffold the [webhooks](https://github.com/kubernetes-sigs/kubebuilder/blob/master/pkg/plugin/v3/webhook.go). 

So, feel free to analyse and see the best approach for we address that. However, just to share and try to help the following sequence might simplify its implementations:

- Make the init command be a plugin with v2, v3 having the same implementations (copy and paster):  https://github.com/kubernetes-sigs/kubebuilder/issues/1639
- Then, we could simplify the current implementation for the paths onlyfor v3 #1689
- after that shows that would be easier to make the edit plugin be smart enought to do the replaces and move the files.

**Comment by prafull01** [comment]
Sounds perfect.

**Comment by camilamacedo86** [comment]
Closing this one.

**Comment by camilamacedo86** [comment]
It was deferred since we consider in the bug triage meeting hard to keep the RFE maintained because users might customize their files which would be hard to edit after the scaffold.

Also, the multi-group feature is used in more advanced and specific scenarios so shows fine in this case users do the required changes manually when required.
