### ISSUE TITLE
Create testing solution for existing "test" projects

### ISSUE THREAD

**Issue by pwittrock** [kubernetes-sigs/kubebuilder#165]
Make it so we can create "test" projects and run kubebuilder commands and go tests against them using the local kubebuilder code.

**Comment by droot** [comment]
Tasks:
  - Opinion on the structure of test projects
  - test methods for exec'ing KB with test dir
  - Root test runner and integrate with Travis test.

**Comment by pwittrock** [comment]
@pmorie Yes, that is the goal
