### ISSUE TITLE
Kubebuilder init error on Windows

### ISSUE THREAD

**Issue by sonaysevik** [kubernetes-sigs/kubebuilder#1650]
Hello,

I am working on Windows, trying to run kubebuilder and build my first Kubernetes operator. I took the following steps so far:

- Downloaded Kubebuilder from github repo
- Ran `go build -o kubebuilder.exe ./cmd/`
- Then  in the directory that I want to create operator ->`go mod init kubetest `
-  ` PATH_TO_KUBEBUILDER/kubebuilder.exe  init --domain example.com `

And after some other logs, got following error:

> go: creating new go.mod: module tmp
> go: downloading sigs.k8s.io/controller-tools v0.3.0
> go: found sigs.k8s.io/controller-tools/cmd/controller-gen in sigs.k8s.io/controller-tools v0.3.0
> go: downloading github.com/spf13/cobra v0.0.5
> go: downloading k8s.io/apiextensions-apiserver v0.18.2
> go: downloading k8s.io/apimachinery v0.18.2
> go: downloading github.com/fatih/color v1.7.0
> go: downloading k8s.io/api v0.18.2
> go: downloading github.com/gobuffalo/flect v0.2.0
> go: downloading github.com/mattn/go-isatty v0.0.8
> go: downloading github.com/mattn/go-colorable v0.1.2
> go: downloading golang.org/x/tools v0.0.0-20190920225731-5eefd052ad72
> go: downloading k8s.io/utils v0.0.0-20200324210504-a9aa75ae1b89
> go: downloading golang.org/x/sys v0.0.0-20191022100944-742c48ecaeb7
> go: downloading gopkg.in/yaml.v3 v3.0.0-20190905181640-827449938966
> go: downloading github.com/json-iterator/go v1.1.8
> go: downloading golang.org/x/net v0.0.0-20191004110552-13f9640d40b9
> go: downloading golang.org/x/text v0.3.2
> **_C:\Users\sonay\go/bin/controller-gen object:headerFile="hack\\boilerplate.go.txt" paths="./..."
> /usr/bin/sh: C:Userssonaygo/bin/controller-gen: No such file or directory_**
> make: *** [Makefile:55: generate] Error 127
> Error: failed to initialize project with version "3-alpha": exit status 2
> Usage:
>   kubebuilder init [flags]

I guess the problem is with the following issue but just cant figure out how to fix it:
> **_C:\Users\sonay\go/bin/controller-gen object:headerFile="hack\\boilerplate.go.txt" paths="./..."
> /usr/bin/sh: C:Userssonaygo/bin/controller-gen: No such file or directory_**

Any help would be very appreciated.

Thanks.

**Comment by camilamacedo86** [comment]
Hi @sonaysevik, 

The project is officially supported just on Linux and Mac OS X.  However, shows that all problems regard the win SO would be solved if we add as pre-requirement use the https://www.cygwin.com/ to work with. Could you please help us by verifying it?

Also, we have some issues raised to make it works with Win. Then, please let knows it if worked and your help/contribution to it would be very welcome. WDYT?

**Comment by camilamacedo86** [comment]
Closing this one as sorted out. However, please feel free to contribute to the project and/or raise new issues as well if you need.
