### ISSUE TITLE
upgrade to use the latest version of kustomize

### ISSUE THREAD

**Issue by camilamacedo86** [kubernetes-sigs/kubebuilder#1657]
## WHAT
- Upgrade to use the latest version of kustomize 
- The latest version is 3.8.2 currently.
- Sheck if the kb workflow will be impacted by kubernetes-sigs/kustomize#2742. (See if the namespace will still be created or not). If not, it is required to investigate if it means a breaking change required in the kb scaffold project or if it should be addressed in the kustomize. 

NOTE: The change should be made only for v3+

## Motivation
- Solve technical debts
- Ensure that an issue/or new bahaviour was not introduced to kustomize which affects kb projects.

**Comment by rmb938** [comment]
That kustomize change makes it so namespaces no longer use the name prefix...

So when  I go and `kustomize build` the files kubebuilder generates the namespace no longer has the prefix.

**Comment by camilamacedo86** [comment]
Confirmed that: 
> With kustomize 3.7.0 the patched namespace has name:example-system while in 3.8.2 this is kept as name:system

see: https://github.com/kubernetes-sigs/kustomize/issues/3005

**Comment by camilamacedo86** [comment]
Another scenario that required be checked/fixed with the upgrade is: https://github.com/kubernetes-sigs/kubebuilder/issues/1633

**Comment by estroz** [comment]
>when I go and kustomize build the files kubebuilder generates the namespace no longer has the prefix.

I'm not seeing this behavior with kustomize v3.8.7. `kubebuilder init` scaffolds a `config/default/kustomization.yaml` with `namespace: {{ .ProjectName }}-system`, which gets applied to every namespaced object.
