### ISSUE TITLE
Missing book reference docs for creating custom events 

### ISSUE THREAD

**Issue by codeblooded** [kubernetes-sigs/kubebuilder#1659]
I was looking at creating events for my custom resource, but I did not see docs on this topic in the v2 book. I see a page from the old book that was deleted in #692. Would we want to add some reference docs for the new book, or has advice changed on using events?

/kind documentation

**Comment by camilamacedo86** [comment]
Hi @codeblooded, 

Could you please add the link for the page/file in   #692 which has the information that you are looking for? Could you please clarify better what info the docs are missing? What do you mean with `creating events for my custom resource`?

**Comment by codeblooded** [comment]
@camilamacedo86 Sure, I meant creating Kubernetes event resources from a reconciler. In the old book, this page addressed the issue. In the new book, this page is missing:

https://github.com/kubernetes-sigs/kubebuilder/blob/52ba0c36d023f5cc53646307cbe5a500c171d3b4/docs/book/beyond_basics/creating_events.md

**Comment by camilamacedo86** [comment]
Thank you for share. Would you like to collab with it? IMO it would fit well in the references section, wdyt?

**Comment by codeblooded** [comment]
@camilamacedo86 Sure. I'd love to collaborate, and I agree about the references section. 🙂

**Comment by camilamacedo86** [comment]
This sound great 🥇 Please, feel free to ping me if you need help with and/or to review your PR. 
I am assigning this issue to you so.

**Comment by shaneutt** [comment]
Sorry to bother, but is there any status update on adding this documentation back for V2 (and V3)?

**Comment by shaneutt** [comment]
Is there any status update on adding this documentation back for V2 (and V3)? If others have dropped it I might have some free time to help with this documentation, just don't want to start anything if others already have.

**Comment by codeblooded** [comment]
@shaneutt You are free to take it if you want. I got backlogged on some work for the controller I'm writing at work, and so that's delayed this for me. I planned to submit something this week or next as I added some events to it, but I'm totally fine with a hand-off. 😄

**Comment by evenh** [comment]
I would love some docs for creating custom events 🙏🏻

**Comment by evenh** [comment]
This helped me: https://github.com/kubernetes-sigs/kubebuilder/issues/549#issuecomment-613506558

**Comment by codeblooded** [comment]
Sure @evenh, you can take a swing at it. I have a bit on my plate as I transition to a new role.
