### ISSUE TITLE
e2e test for kubebuilder

### ISSUE THREAD

**Issue by pwittrock** [kubernetes-sigs/kubebuilder#166]
- building images
- creating config
- installing into a cluster
- creating resource object, making sure it gets reconciled
- controller creates other objects, verify RBAC rules are good
- controller listens to other objects, verify watches

**Comment by lichuqiang** [comment]
Glad to work on the part.

btw, I noticed we have another issue https://github.com/kubernetes-sigs/kubebuilder/issues/124 about e2e framework, shall we have an unified umbrella issue for better tracking?

and is there any ongoing effort I can refer to/avoid duplication of work?

/assign
