### ISSUE TITLE
Some fields of `kubebuilder version` output are missing or unknown

### ISSUE THREAD

**Issue by liuming-dev** [kubernetes-sigs/kubebuilder#1660]
**kubebuilder (installed by brew)**

```bash
# apple @ liuming-dev in ~/.kube [15:13:42]
$ brew reinstall kubebuilder
==> Downloading https://homebrew.bintray.com/bottles/kubebuilder-2.3.1.catalina.bottle.tar.gz
Already downloaded: /Users/apple/Library/Caches/Homebrew/downloads/72e1d125d7c23869f212d404701ec4831a651b2efedf8fac9ec328194af177fe--kubebuilder-2.3.1.catalina.bottle.tar.gz
==> Reinstalling kubebuilder
==> Pouring kubebuilder-2.3.1.catalina.bottle.tar.gz
🍺  /usr/local/Cellar/kubebuilder/2.3.1: 5 files, 14.0MB

# apple @ liuming-dev in ~/.kube [15:14:25]
$ kubebuilder version
Version: version.Version{KubeBuilderVersion:"unknown", KubernetesVendor:"unknown", GitCommit:"$Format:%H$", BuildDate:"1970-01-01T00:00:00Z", GoOs:"unknown", GoArch:"unknown"}
```

**kubebuilder(downloaded from [kubebuilder_2.3.1_darwin_amd64.tar.gz](https://github.com/kubernetes-sigs/kubebuilder/releases/download/v2.3.1/kubebuilder_2.3.1_darwin_amd64.tar.gz))**

```bash
# apple @ liuming-dev in ~/.kube [15:20:12] C:137
$ /Users/apple/Downloads/kubebuilder_2.3.1_darwin_amd64/bin/kubebuilder version
Version: version.Version{KubeBuilderVersion:"2.3.1", KubernetesVendor:"1.16.4", GitCommit:"8b53abeb4280186e494b726edf8f54ca7aa64a49", BuildDate:"2020-03-26T16:42:00Z", GoOs:"unknown", GoArch:"unknown"}
```

Some fields of `kubebuilder version` output missing or are unknown, are there some mistakes when building？ 

/kind bug

**Comment by camilamacedo86** [comment]
Did you not clone it before from master? Shows that you have a kubebuilder bin locally that was built via `make install`.

**Comment by liuming-dev** [comment]
> master

Thanks for reply, but I did not build it via `make install`,  you can try this from the release asserts https://github.com/kubernetes-sigs/kubebuilder/releases/download/v2.3.1/kubebuilder_2.3.1_darwin_amd64.tar.gz

**Comment by theishshah** [comment]
I believe this is an issue with the binary uploaded to Brew not with the version command itself. Have you looked at opening a ticket with Brew itself?

**Comment by camilamacedo86** [comment]
Hi @liuming-dev, 

I found the formula it is here; https://github.com/Homebrew/homebrew-core/blob/master/Formula/kubebuilder.rb . See that it is not using the binary. in this way, the issue is on it as described by @theishshah. we could change the formula to use the binary instead of git chec out the tag. Would you like to contribute with this fix there?

**Comment by liuming-dev** [comment]
Sorry, @camilamacedo86 , I'm not familiar with brew formula.

**Comment by gabbifish** [comment]
#1814 should fix this issue, and if this issue still persists, please contact the maintainer of the kubebuilder homebrew formula (which is maintained independent of this repository).
