### ISSUE TITLE
Bug in multigroup suite_test generation

### ISSUE THREAD

**Issue by antonincms** [kubernetes-sigs/kubebuilder#1665]
**What broke (please include exact error messages if you can):**
When generating a basic multigroup project, the generated `suite_test.go` is wrong and does not register CRD correctly during integration tests.

**Step to reproduce:**
- bootstrap the project with `kubebuilder init --domain "example.io"`
- modifying the PROJECT file to add `multigroup: true`
- creating an API with `kubebuilder create api --group webapp --version v1 --kind Guestbook`

**What did you expect to happen?**
The file `suite_test.go` contains 
```go
CRDDirectoryPaths: []string{filepath.Join("..", "config", "crd", "bases")}
```
where it should contains
```go
CRDDirectoryPaths: []string{filepath.Join("..", "..", "config", "crd", "bases")}
```

**What versions of software are you using?**
* go version : 1.14.6
* kubebuilder version (`kubebuilder version`) : `Version: version.Version{KubeBuilderVersion:"2.3.1", KubernetesVendor:"1.16.4", GitCommit:"8b53abeb4280186e494b726edf8f54ca7aa64a49", BuildDate:"2020-03-26T16:42:00Z", GoOs:"unknown", GoArch:"unknown"}`
* scaffolding version (check your `PROJECT` file) : tried `2` and `3-alpha`

/kind bug

**Comment by camilamacedo86** [comment]
The solution of this issues was made in the PRs: https://github.com/kubernetes-sigs/kubebuilder/pull/1673 and  https://github.com/kubernetes-sigs/kubebuilder/pull/1682
