### ISSUE TITLE
Create apiserver-runtime repo for apiserver-builder-alpha subproject

### ISSUE THREAD

**Issue by pwittrock** [kubernetes-sigs/kubebuilder#1678]
@DirectXMan12 @camilamacedo86 @gabbifish 

# Background

The [apiserver-builder-alpha](https://github.com/kubernetes-sigs/apiserver-builder-alpha) project pre-dates kubebuilder and was an early prototype for kubebuilder.  Its implementation relied heavily on code generation to mirror the samples, rather than using interfaces and libraries.  apiserver-builder-alpha provided a solution for building resources types using apiserver aggregation rather than CRDs.

The controller pieces of apiserver-builder-alpha were rebased on controller-runtime instead of the original code generation approach, however the resource implementations are still done as code-generation today.

There are still valid cases for using apiserver aggregation instead of CRDs -- for instance if the resources should not be backed by etcd storage (metrics is an example of this).  apiserver-builder-alpha has active customers and is maintained by @yue9944882.

# Proposal

This issue proposes implementing apiserver-builder-alpha libraries that more closely reflect the controller-runtime techniques, using libraries and interfaces rather than code generation.  These libraries would live in the repo apiserver-runtime, mirroring the structure of kubebuilder & controller-runtime.

# Example

An example what the libraries would look like can be seen here:

https://github.com/pwittrock/apiserver-runtime/tree/public/pkg/builder

**Comment by yue9944882** [comment]
thanks @pwittrock! btw for now one issue on the code-generation approach is that the original kubernetes code-generator framework -- gengo -- is getting [extremely slow](https://github.com/kubernetes/gengo/issues/177) when running under go mod --- which is now a standard approach for dep management. apiserver-builder will run more than 5 standalone code-generators from different repos by spawning new child processes and each of them is doing downloading/listing mod dependencies redundantly. in bad cases, the whole code-generation process for apiserver-builder will take more than 10 min. so am +1000 that we should get rid of these heavy code-generation as much as we can. controller-runtime successfully helped us getting rid of client/informer/lister generators, and as far as i can see the apiserver-runtime will help us from removing deepcopy/default/conversion/openapi generators.

besides, by the new repo we can also provide developers SDK utilities to develop non-ETCD aggregated apiservers. over the years there were a number of voices looking for building their customized apiserver upon SQL-storage/MongoDb/Firebase or webhooks or even simply [host-paths](https://github.com/kubernetes-sigs/apiserver-builder-alpha/pull/533). i believe it's really valuable to empower developers to customize AA storage.

**Comment by DirectXMan12** [comment]
I think any code generation required for the new repo can probably be handled by controller-tools anyway (which is way faster), but the generation for the new repo is fairly minimal.

overall :+1:

**Comment by pwittrock** [comment]
Ack.  The code generation is a lot faster for the apiserver-runtime AFAICT.  Right now only the DeepCopy and OpenAPI need to be generated, and both of those could be addressed by introducing proper protosupport.  Generating the go types from the proto would be very rapid.
