### ISSUE TITLE
Generated controller fields have inconsistent casing

### ISSUE THREAD

**Issue by danp** [kubernetes-sigs/kubebuilder#168]
In generated code such as this in the memcached example:

https://github.com/kubernetes-sigs/kubebuilder/blob/5ba5473b44dd6f6b16a5101afefe3f332794cbfc/samples/memcached-api-server/pkg/controller/memcached/controller.go#L104-L106

Lister is capitalized but client and recorder (missing here) are not.

Can submit a PR to fix around here but wanted to make sure this is not intentional:

https://github.com/kubernetes-sigs/kubebuilder/blob/5ba5473b44dd6f6b16a5101afefe3f332794cbfc/cmd/kubebuilder/create/controller/controller.go#L84-L89

**Comment by pwittrock** [comment]
I don't think this is intentional.  Please file the PR to fix, and add a test to `test.sh`.

**Comment by pwittrock** [comment]
We are going to fix this another way by moving away from generated clients.
