### ISSUE TITLE
Question on external CRDs document and best practices for testing

### ISSUE THREAD

**Issue by steveQuadros** [kubernetes-sigs/kubebuilder#1685]
I was checking out [this doc on external types](https://github.com/kubernetes-sigs/kubebuilder/commits/master/docs/using_an_external_type.md) following from https://github.com/kubernetes-sigs/kubebuilder/issues/369 which lead me to https://github.com/kubernetes-sigs/kubebuilder/pull/752
There is also an [issue that mentions this exists](https://github.com/kubernetes-sigs/kubebuilder/issues/538#issuecomment-501827481) in the kubebuilder book/Cronjob tutorial, but I couldn't find it.

Are there established best practices for including external CRD definitions?

The [doc](https://github.com/kubernetes-sigs/kubebuilder/issues/538#issuecomment-501827481) mentions having them in `vendor`, but `config` isn't a go pkg, and isn't included by default. I wanted to check if there was something obvious I was missing.

I'd be happy to update the docs to clarify if there is already a solution.

/triage support

**Comment by camilamacedo86** [comment]
HI @steveQuadros, 

By running the command `create api` is generate the Custom Resource (CR) in the [config/samples](https://github.com/kubernetes-sigs/kubebuilder/tree/master/testdata/project-v3/config/samples) and Custom Resource Definition (CRD) in [config/crds/bases](https://github.com/kubernetes-sigs/kubebuilder/tree/master/testdata/project-v3/config/crd/bases) for the Kind provided. This command is creating the API for the project. In this way, we can create our APIs and objects that will represent our solutions on these platforms and it can have as many Kinds as needed (1…N). Basically, the CRDs are a definition of our customized Objects, and the CRs are an instance of it.

However, we can also use third-APIs in the projects. For that, we need to register the API with the scheme to the manager as described in the doc [Using an External Type](https://github.com/kubernetes-sigs/kubebuilder/blob/master/docs/using_an_external_type.md#edit-the-api-files) and such as in the `main.go`:

```go
      import (
            myextrenalschema "pathimport"
      ) 
 
       if err := myextrenalschema.AddToScheme(mgr.GetScheme()); err != nil {
		log.Error(err, "")
		os.Exit(1)
	}
```

In this way, if we add the schema we are able to use them in the controllers which mean to create, to delete, to get, to update an etc resources of these types. But if you would like to reconcile CR's of this external kind and have a controller for it then, you can also `create api` for the external kind with its controller in the way that shows described in the doc. Might give a look in the [here](https://developers.redhat.com/blog/2020/02/04/how-to-use-third-party-apis-in-operator-sdk-projects/) can help you with.  

Regards: 

> The doc mentions having them in vendor, but config isn't a go pkg, and isn't included by default. I wanted to check if there was something obvious I was missing.

I understand that you are speaking about: 

```go
// Get a config to talk to the apiserver
	t := &envtest.Environment{
		Config:             cfg,
		CRDDirectoryPaths:  []string{
		  filepath.Join("..", "..", "..", "config", "crds"),
		  filepath.Join("..", "..", "..", "vendor", "github.com", "theiruser", "theirproject", "config", "crds"),
        },
		UseExistingCluster: true,
	}
```

This part of the code is describing how to add the external CRDs to the [suite_test.go](https://github.com/kubernetes-sigs/kubebuilder/blob/master/testdata/project-v3/controllers/suite_test.go#L56-L58) based on the steps informed. Note that in the `suite_test.go` it is required to inform the path for the CRD's for the [envttest](https://pkg.go.dev/sigs.k8s.io/controller-runtime/pkg/envtest) setup. More info: https://book.kubebuilder.io/cronjob-tutorial/writing-tests.html

Please, let me know if it is what you were looking for.

**Comment by DirectXMan12** [comment]
We get asked this question quite a bit -- we should have a short tutorial or a cookbook/short-recipes section that describes this, among other things, and explains how external types related to local types (they're mostly the same).

/help
