### ISSUE TITLE
snapshot/release cloudbuild config is b0rked

### ISSUE THREAD

**Issue by DirectXMan12** [kubernetes-sigs/kubebuilder#1694]
The cloudbuild configs in build/cloudbuild.yaml & build/cloudbuild_snapshot.yaml are b0rked -- they use Go 1.12 to build, and we've long since required Go 1.13.  We should fix them up.

While we're at it, they seem to still be using go-releaser, which I think we wanted to switch off of.  We should start populating kubernetes-sigs/kubebuilder-release-tools with common releasing infrastructure, and maybe consider moving over to that where possible

cc @vincepri who I think had some ideas around this

**Comment by vincepri** [comment]
Does this affect the ability for us to release new kubebuilder-tools for testenv? Or is this separate?

**Comment by DirectXMan12** [comment]
separate -- we've got 4 cloudbuild triggers currently:

- (tools-releases:build/cloudbuild_tools.yaml) on **push** to `release-tools` --> build darwin/amd64 envtest bundle --> upload to GCR
- (tools-releases:build/cloudbuild_tools.yaml) on **push** to `release-tools` --> build linux/amd64 envtest bundle --> upload to GCR
- (master:build/cloudbuild.yaml)  on **tag** to `master` --> build linux/amd64, darwin/amd64 kubebuilder executable --> upload to GitHub release
- (master:build/cloudbuild_snapshot.yaml) on **push** to `master` --> build linux/amd64, darwin/amd64 kubebuilder executable --> upload to snapshots GCS bucket

**Comment by DirectXMan12** [comment]
the ones that are broken are the last two, although the tag one hasn't manifested since we haven't done a release in a while

**Comment by vincepri** [comment]
got it, thanks for the info 🤔, have to take a deeper look

**Comment by camilamacedo86** [comment]
Hi @vincepri and @DirectXMan12, 

> they use Go 1.12 to build, and we've long since required Go 1.13.

Might valid consider using Go 1.15. See that controller-runtime is already updated and we have an open to do it here as well. see; https://github.com/kubernetes-sigs/kubebuilder/pull/1716

**Comment by DirectXMan12** [comment]
:+1:
