### ISSUE TITLE
Customize the listwatcher to select CRDs with specific label

### ISSUE THREAD

**Issue by githubbot-eric** [kubernetes-sigs/kubebuilder#1700]
I think this might not be a case suitable for CRD + Controller but we are using it. We have huge number of CRDs created, and all of them can be ignored after reconciled to a status we can say it is completed. 

During the controller restart, it needs to load all CRDs and populate the local cache, this is extremely slow (>5mins) as the total number of CRDs is very huge.

We want to put a label like "status:done" and "status:working" in the CRD and make our controller only list & watch those CRDs with label "status:working".

What should I do to customize the listwatcher? looks like there is no place we can fill the options in.

**Comment by agarwalpradeep123** [comment]
I also have a usecase of watching pods running on a node and not watch all the pods in the cluster.
This will significantly improve both memory and cpu requirements.

How can this be achieved?

**Comment by camilamacedo86** [comment]
Hi @githubbot-eric and @pagarwal-tibco,

The idea of operators is that you write solutions which are idempotent which means that will always result in the same expected result.

Note that the reconcile is NOT re-trigged ONLY by the watches. By default, the reconciliation will be called for the CR's each every 10 hours.  See the Options Struct which is used to create the Manager: https://pkg.go.dev/sigs.k8s.io/controller-runtime/pkg/manager#Options

In this way, I'd recommend in this case you create predicates that will stop the reconciliation when all is the desired/wished state which shows that in your case is when the CR.status is == N: 


```go
func (r *MemcachedReconciler) Reconcile(req ctrl.Request) (ctrl.Result, error) {
	ctx := context.Background()
	log := r.Log.WithValues("memcached", req.NamespacedName)

	// Fetch the Memcached instance
	memcached := &cachev1alpha1.Memcached{}
	err := r.Get(ctx, req.NamespacedName, memcached)
	if err != nil {
		if errors.IsNotFound(err) {
			// Request object not found, could have been deleted after reconcile request.
			// Owned objects are automatically garbage collected. For additional cleanup logic use finalizers.
			// Return and don't requeue
			log.Info("Memcached resource not found. Ignoring since object must be deleted")
			return ctrl.Result{}, nil
		}
		// Error reading the object - requeue the request.
		log.Error(err, "Failed to get Memcached")
		return ctrl.Result{}, err
	}

        // stop the reconciliation when the status is N 
        if memcached.Status.X = "valueN" {
                 return ctrl.Result{}, nil
        }
```

Se that the reconcile function is responsible for synchronizing the resources and their specifications according to the business logic implemented on them. In this way, it works like a loop, and it does not stop until all conditionals match its implementation. The following is pseudo-code with an example that clarifies it.

```go
reconcile App {

   // Check if a Deployment for the app exists, if not create one
   // If has an error, then go to the beginning of the reconcile
   if err != nil {
       return reconcile.Result{}, err 
   } 
   
   // Check if a Service for the app exists, if not create one 
   // If has an error, then go to the beginning of the reconcile
   if err != nil {
       return reconcile.Result{}, err 
   }  

   // Looking for Database CR/CRD 
   // Check the Database Deployments Replicas size
   // If deployment.replicas size != cr.size, then update it
   // Then, go to the beginning of the reconcile
   if err != nil {
       return reconcile.Result{Requeue: true}, nil
   }  
   ...
   
   // If it is at the end of the loop, then:
   // All was done successfully and the reconcile can stop  
   return reconcile.Result{}, nil

}
```

I hope that it helps you with. Please, let me know if we can close this in one?

**Comment by pagarwal-tibco** [comment]
Hi camilamacedo86,


My concern is more about limiting the number of kubernetes resources needs to cached/watched and processed. My use case is of having daemon-set watching pods on current node, hence I am looking for a solution like having a fieldSelector for the resources being watched/cached and reconciled.

I see that kubernetes client-go library provides similar functionality with `func NewListWatchFromClient(c Getter, resource string, namespace string, fieldSelector fields.Selector) *ListWatch` in package <client-go>/tools/cache. Is there a similar way to achieve this using kubebuilder?

It would be very useful to have this feature which I think is already supported by underlying kubernetes client-go library. This will also help in reducing cache, memory footprint and CPU requirements when there are huge number of pods in the cluster.

I hope this helps you to understand the use case.

**Comment by camilamacedo86** [comment]
Hi @pagarwal-tibco,

The Kubebuilder is only a CLI tool which helps users by scaffolding the files. The [controller-runtime](https://github.com/kubernetes-sigs/controller-runtime) is the project which implements the controller implementation and the watches feature. See that you can use Predicates to filter. 

```go
// Watch takes events provided by a Source and uses the EventHandler to
// enqueue reconcile.Requests in response to the events.
//
// Watch may be provided one or more Predicates to filter events before
// they are given to the EventHandler.  Events will be passed to the
// EventHandler if all provided Predicates evaluate to true.
Watch(src source.Source, eventhandler handler.EventHandler, predicates ...predicate.Predicate) error
```

See the doc https://pkg.go.dev/sigs.k8s.io/controller-runtime/pkg/controller and might be helpful check an example by looking [here](https://github.com/kubernetes-sigs/cluster-api/blob/cb8f8e40d3a013a9cf8328f7a3df5553501f7baf/util/util.go#L542-L554) and [here](https://github.com/kubernetes-sigs/cluster-api/blob/master/controllers/machine_controller.go#L94-L101). Also, see that the builder provides [WithEventFilter](https://pkg.go.dev/github.com/kubernetes-sigs/controller-runtime/pkg/builder#Builder.WithEventFilter) which can let you filter events:

```go
return ctrl.NewControllerManagedBy(mgr).
	For(&cachev1alpha1.Memcached{}).
	Owns(&appsv1.Deployment{}).
	WithEventFilter(<here you will pass your predicate to filter>)
	Complete(r) 
```

The doc https://sdk.operatorframework.io/docs/building-operators/golang/references/event-filtering/#using-predicates an example to know how to use it.  

**NOTES:** As an example of the possibilities, in the [operator-lib](https://github.com/operator-framework/operator-lib) you also can check the implementation of [EnqueueRequestsFromMapFunc](https://pkg.go.dev/sigs.k8s.io/controller-runtime/pkg/handler#example-EnqueueRequestsFromMapFunc) in https://github.com/operator-framework/operator-lib/blob/main/handler/enqueue_annotation.go which is based in annotations. This subject that you have been looking for shows be discussed in the issue: https://github.com/kubernetes-sigs/controller-runtime/issues/244. 

I hope that it helps you with. Please, let me know if it answers your question.

**Comment by camilamacedo86** [comment]
Hi @pagarwal-tibco, 

I saw that you cut and paste your previous comment in the controller-runtime issue. however, see that in the previous comment here was added examples over how you can solve this problem using the Predicates or by doing an implementation of EnqueueRequestsFromMapFunc if you wish. Could you please let us know why the Predicates do not solve your problem?

**Comment by pagarwal-tibco** [comment]
Hi @camilamacedo86,

As far as I understand, predicates will help in filtering out resource which we don't want to be processed by reconciler. But those resource will still be cached, right?

I would like them to be filtered completely(not have them in cache) and make it very lightweight

**Comment by githubbot-eric** [comment]
Thanks for your reply!

Same case with @pagarwal-tibco 

We have huge number of CRDS which make the controller take extremely long time (always fail before we adjust the timeout) to startup.
What we really want to achieve is we don't even want the controller to build local caches for the CRDs if status is completed, this is why I'm asking if kube-builder has the option to customize the listwatcher to list & watch resources with given label...

**Comment by camilamacedo86** [comment]
HI @githubbot-eric and  @pagarwal-tibco, 

The predicates can help you to not trigger the reconcile when the CR as described in https://github.com/kubernetes-sigs/kubebuilder/issues/1700#issuecomment-707063707. However, shows that you are really looking for is the kubernetes-sigs/controller-runtime#244. 

PS.: It might help you out as well, the SDK has a specific implementation for another reason to skip the cache. See [here](https://github.com/operator-framework/operator-sdk/blob/master/internal/ansible/proxy/cache_response.go)

It was discussed in the bug triage meeting and then, it shows more a controller-runtime issue. So, we will close this one and kindly ask for you to follow up kubernetes-sigs/controller-runtime#244. However, please feel free to ping us and/or to raise new issues.
