### ISSUE TITLE
Controllers on Core reosources

### ISSUE THREAD

**Issue by Jiajing-Hu** [kubernetes-sigs/kubebuilder#1706]
Hello, Kubebuilder Contributors
i meet a question while use kubebuilder , Is it possible to create a controller on core resources ? 
I followed the v2 version of the guide, but did not find relevant information.

i NOTECED that this issue is mentioned in [Controllers for Core Resources
](https://book-v1.book.kubebuilder.io/beyond_basics/controllers_for_core_resources.html)

but there are no more details. 

So, I wonder how to create to controller on core resources such as Pod or Storageclass. Thank you

**Comment by camilamacedo86** [comment]
Hi @Jiajing-Hu, 

With the master version of the Kubebuilder tool and the v3+ plugin is possible to do it after the PR https://github.com/kubernetes-sigs/kubebuilder/pull/1679. 

Could you please test it with `kubebuilder init --plugins=go.kubebuilder.io/v3-alpha`? 
Also, after that WDYT about contribute with a doc explaining it? We could add a new link in https://book.kubebuilder.io/reference/reference.html.

**Comment by camilamacedo86** [comment]
I am closing this one since shows solved. Hoover fell free to ping if you need to.

**Comment by Jiajing-Hu** [comment]
> I am closing this one since shows solved. Hoover fell free to ping if you need to.

sorry for late response. 

```
kubebuilder init --plugins=go.kubebuilder.io/v3-alpha
```
do not work 

but, I found it work with 
kubebuilder create api --group "core" --kind "Pod" --version "v1" . 

anyway, thanks for your help .
