### ISSUE TITLE
"Race condition" on deletion of owned object

### ISSUE THREAD

**Issue by alekc** [kubernetes-sigs/kubebuilder#1722]
/triage support

Hi all, I am observing some weird issue in a situation when a child object is deleted. 

To give a bit of context:

As per doc my controller uses following pattern to watch for changes on created configmaps
```go
func (r *RunnerReconciler) SetupWithManager(mgr ctrl.Manager) error {
	// setup indexers on configmap created by x
	if err := mgr.GetFieldIndexer().IndexField(&v1.ConfigMap{}, ownerKey, func(rawObj runtime.Object) []string {
		// grab the configMap object, extract the owner...
		configMap := rawObj.(*v1.ConfigMap)
		owner := metav1.GetControllerOf(configMap)
		if owner == nil {
			return nil
		}

		// ensure that we dealing with a proper object
		if owner.APIVersion != gitlabv1alpha1.GroupVersion.String() || owner.Kind != "Runner" {
			return nil
		}

		return []string{string(owner.UID)}
	}); err != nil {
		return err
	}
	return ctrl.NewControllerManagedBy(mgr).
		For(&gitlabv1alpha1.Runner{}).
		Owns(&v1.ConfigMap{}).
		Complete(r)
}
```
then, in my reconcile loop I have
```go
func (r *RunnerReconciler) Reconcile(req ctrl.Request) (ctrl.Result, error) {
...
var configMaps v1.ConfigMapList

	// fetch children configmap
	err = r.Client.List(
		ctx,
		&configMaps,
		client.InNamespace(runnerObj.Namespace),
		client.MatchingFields{ownerKey: string(runnerObj.UID)},
	)
	if err != nil {
		logger.Error(err, "cannot list dependent configmaps")
		return ctrl.Result{}, err
	}
...
```
if the count of `configMaps.Items` is 0, then I create a new ConfigMap

This pattern works well for the general creation, restart of the controller, etc. However, when I delete the child config map, for some reason, the list comes up empty, but the creation fail because such object already exists. 

I do realize that this is probably because the config map is in some kind of phase of soft deletion which causes this issue, so my question is: is there a better way to deal with such situation besides throwing an error and attempting to reconcile once again? Should I just check for the type of error returned and in case it's duplicated object just throw a silent reconcile request?

Cheers.

**Comment by camilamacedo86** [comment]
Shows that in the [doc](https://book.kubebuilder.io/cronjob-tutorial/controller-implementation.html) the motivation of the example is to `Watch` a resource which is not managed by the controller. Is that your case scenario as well? 

However, note that one of the attributes that can be informed is `IsController` to the watches: 


```go

      err := c.Watch(&source.Kind{Type: obj}, &handler.EnqueueRequestForOwner{
		IsController: isConttroller,
		OwnerType:    owner,
	})

```

More info: https://pkg.go.dev/sigs.k8s.io/controller-runtime/pkg/handler#EnqueueRequestForOwner

I have a personal project with this example, see https://github.com/dev4devs-com/postgresql-operator/blob/master/pkg/controller/backup/controller.go#L60-L63 where I am watching a resource that is managed by another controller. See [here](https://pkg.go.dev/sigs.k8s.io/controller-runtime@v0.6.3/pkg/builder#Builder.Watches) that the builder also allows set the Watches. Did you try to solve it in this way?

**Comment by camilamacedo86** [comment]
Hi @alekc, 

I hope that the above info clarifies your question. Since it is without interaction for I a while shows that you could figure out already. So, I am closing this one but feel free to ping us if you think that it needs to be re-opened as to raise new issues if you need.
