### ISSUE TITLE
We should have an FAQ / common issues book section

### ISSUE THREAD

**Issue by DirectXMan12** [kubernetes-sigs/kubebuilder#1723]
There's all sorts of weird k8s API server issues (and a few KB-specific ones :wink:) that folks can run into, and we should document them somewhere.

Off the top of my head:

- Weird issues when a v1beta1 CRD is already installed in the cluster (invisibly set `preserveUnknownFields`, refusal to chance certain fields, etc)

/kind docs

**Comment by camilamacedo86** [comment]
Following a few examples to help who will work on in this task:
- controller-runtime; https://github.com/kubernetes-sigs/controller-runtime/blob/master/FAQ.md
- sdk: https://sdk.operatorframework.io/docs/faqs/faqs/

**Comment by camilamacedo86** [comment]
We can explain that and link https://book.kubebuilder.io/cronjob-tutorial/gvks.html.

**Comment by camilamacedo86** [comment]
We can close this one because we have a FAQ section now, see: https://github.com/kubernetes-sigs/kubebuilder/pull/3044

Regards the need:

> Weird issues when a v1beta1 CRD is already installed in the cluster (invisibly set preserveUnknownFields, refusal to chance certain fields, etc)

It seems outdated since v1beta1 CRD is no longer supported. 

So, it seems fine we close this one.
