### ISSUE TITLE
The manifest config/default/webhookcainjection_patch.yaml ought to be scaffold in the webhook plugin

### ISSUE THREAD

**Issue by camilamacedo86** [kubernetes-sigs/kubebuilder#1727]
#### What did you do?

Init a project with kubebuider init

#### What did you expect to see?

Only manifest which are part of the init domain of responsibility be scaffolded. 

#### What did you see instead? Under which circumstances?

The file `config/default/webhookcainjection_patch.yaml` be scaffold as well.  

#### Describe the problem you would like to resolve

- I am an operator dev would like to see specific manifests which are required/useful for the webhooks only/if my project has webhooks  
- I am a consumer of the kubebuilder plugins would like that each plugin only scaffold manifests which are related to its domain so that, I can decide what plugins I'd like to consume or not. Example: I would like to consume the init and create api one, however, the webhook plugins are not important for me, so that I would NOT like that the init plugin do scaffolds that are only useful for the webhooks.

#### Describe the solution you'd like.

The boilerplate for this manifest is [here](https://github.com/kubernetes-sigs/kubebuilder/blob/master/pkg/plugin/v3/scaffolds/internal/templates/config/kdefault/enablecainection_patch.go). I'd like that it would be scaffold when the command `kb create webhook` is executed instead of it. We can check if exist and if not then, do the scaffold.  

/kind bug

**Comment by camilamacedo86** [comment]
c/c @estroz

**Comment by prafull01** [comment]
@camilamacedo86 I can pick this up, if no one is working on it..

**Comment by camilamacedo86** [comment]
Hi @prafull01, 

Feel free to get any issue that is not assigned to anybody as this one. 
Really thank you for your contribution and help on that.

**Comment by camilamacedo86** [comment]
As discussed in the bug triage meeting, it should be addressed only for v3+.
