### ISSUE TITLE
Is that a better way to watch pod without calling Reconcile() too many times?

### ISSUE THREAD

**Issue by lianghao208** [kubernetes-sigs/kubebuilder#1737]
I hava over 3000 pods in my cluster, and I need to watch Pods status by calling SetupWithManager() function like this:
```go
return ctrl.NewControllerManagedBy(mgr).
		For(&kmpv1.ClusterOverview{}). // my CR
		Watches(&source.Kind{Type: &corev1.Pod{}}, &handler.EnqueueRequestForObject{}).
		Complete(r)
```
everytime I start this controller, it starts to **list** every single Pods. It calls Reconcile() function as many times as the number of Pods, which takes a long time.
Is that a way to **list** all Pod resource  by calling Reconcile() at the begining just once? And of course calling Reconcile() whenever the Pods ` Status updated after it complete listing.
/triage support

**Comment by camilamacedo86** [comment]
Hi @lianghao208, 
 
The goal of the Watch feature is observer the resources on the Cluster and then, call/trigger the reconcile if any event for them be raised. I mean, when the resource is created/updated/deleted/edited.

The code shared shows that you are Watching all Pods which are managed by the controller of the resource `ClusterOverview`. So, do you need to trigger the reconcile when any pod with its owner be created/updated/deleted/edited? Have you any conditional related to it? if yes, you can use predicates to filter the resources that should trigger the reconcile such as described in https://github.com/kubernetes-sigs/kubebuilder/issues/1700#issuecomment-707063707. Would not it solve your problem?

**Comment by lianghao208** [comment]
> Hi @lianghao208,
> 
> The goal of the Watch feature is observer the resources on the Cluster and then, call/trigger the reconcile if any event for them be raised. I mean, when the resource is created/updated/deleted/edited.
> 
> The code shared shows that you are Watching all Pods which are managed by the controller of the resource `ClusterOverview`. So, do you need to trigger the reconcile when any pod with its owner be created/updated/deleted/edited? Have you any conditional related to it? if yes, you can use predicates to filter the resources that should trigger the reconcile such as described in [#1700 (comment)](https://github.com/kubernetes-sigs/kubebuilder/issues/1700#issuecomment-707063707). Would not it solve your problem?

Thanks for the reply! I actually need to watch all the Pods in my controller, but when the controller starts, it has to list all the pods by calling Reconcile() first (one pod at a time), then observer the changes. I am ok with the observing part, but is that a better way to list all the pods at the beginning of the controller without calling Reconcile() too many times?

**Comment by camilamacedo86** [comment]
Hi @lianghao208, 

I am not sure if I could understand what you are looking for. if you watch the Pods then the reconcile will be trigged for each resource of this Kind when an event is raised.  I mean, when the Pod(s) is created/updated/deleted/edited.

> but is that a better way to list all the pods at the beginning of the controller without calling Reconcile() too many times?

The `r.client.List()` to get all Pods in the reconcile do NOT re-trigger the reconcile. It will just return a list for it.

**Comment by lianghao208** [comment]
Hi @camilamacedo86,
Thanks, the thing is I can`t control the trigger of reconcile

>  if you watch the Pods then the reconcile will be trigged for each resource of this Kind when an event is raised. I mean, when the Pod(s) is created/updated/deleted/edited.

when the controller starts, it will trigger the reconcile even if there is no created/updated/deleted/edited event of the resources. Because the controller needs to get the initial state of the resources first. I can`t disable it.

**Comment by camilamacedo86** [comment]
Hi @lianghao208, 

We are not up to tell you how better you can address your needs because it is up to the requirements of your solution. However, the first operation in the Reconcile usually would be to check if has or not a CR for that, if not it will stop. See: https://github.com/operator-framework/operator-sdk/blob/master/testdata/go/memcached-operator/controllers/memcached_controller.go#L50-L68

Then, note that after the reconcile will be trigged by the Watches and via the manager: If you do not change the default code then, the Reconcile will be trigged every 10 hours.  See the `SyncPeriod` attribute in the [Options Struct](https://pkg.go.dev/sigs.k8s.io/controller-runtime/pkg/manager#Options) which is used to create the Manager of the operator project.  

In this way, the recommendation is that the solutions are idempotent. So, it has no Pods created already the list can return empty and you can stop the reconcile. Is it make sense?

**Comment by lianghao208** [comment]
Hi @camilamacedo86 ,
Have you met a situation like this? Let`s say you have over 3000 pods running in your cluster, your operator job is to count the number of pods in each namespace and record the result in the Status feild of your CR. So you have to watch every single pod in the cluster. And the manager code would be like this:
 ```go
return ctrl.NewControllerManagedBy(mgr).
		For(&kmpv1.ClusterOverview{}). // my CR
		Watches(&source.Kind{Type: &corev1.Namespace{}}, &handler.EnqueueRequestForObject{}).
		Watches(&source.Kind{Type: &corev1.Pod{}}, &handler.EnqueueRequestForObject{}).
		Complete(r)
```
by the time the operator starts, for every single pod and namespace remaining in the cluster, they will trigger the reconcile once at a time. So the reconcile would be triggered over 3000 times even if there is no created/updated/deleted/edited event exists. Is that a way to avoid this at the start stage of the operator?

**Comment by camilamacedo86** [comment]
Hi @lianghao208 , 

Would be acceptable in your requirement check the information after X time? If yes, you can not watch the Pods and then do such as:

- fetch the CR :  https://github.com/operator-framework/operator-sdk/blob/master/testdata/go/memcached-operator/controllers/memcached_controller.go#L50-L68
- Get the pods
- update the CR
- and then, reconcile again after X time. E.g `return ctrl.Result{RequeueAfter: nextRun.Sub(r.Now())}, nil`

**Comment by maheshrajrp** [comment]
@lianghao208 Curious, how you were able to move pass this ? what was the solution ?
