### ISSUE TITLE
Add test to ensure the the logs are outputted with zap in the manager

### ISSUE THREAD

**Issue by camilamacedo86** [kubernetes-sigs/kubebuilder#1739]
**What do you want to happen?**
It is a follow up of https://github.com/kubernetes-sigs/kubebuilder/pull/1721. Would be nice to add a test to ensure that the logs are outputted with zap as described in https://github.com/kubernetes-sigs/kubebuilder/pull/1721#issuecomment-714301930

**Notes**
- The change was done only for v3+ so the test should only cover the projects built with v3-alpha plugin.

**Comment by estroz** [comment]
Why do we need to test the output format of an external package for correctness here? This should be done in controller-runtime.

**Comment by camilamacedo86** [comment]
HI @estroz, 
The idea here is only to ensure that the controller-runtime/manager is setup with the zap properly and not ensure that it works as expected. However, you are right it might be too much for e2e. So, I am closing this one.
