### ISSUE TITLE
Migrate to travis-ci.com

### ISSUE THREAD

**Issue by camilamacedo86** [kubernetes-sigs/kubebuilder#1752]
Our current CI on travis-ci.org will be EOL on December 31, 2020. 

travis-ci.com will still have free builds for open source projects but we need to migrate.

More info:

- [the newsletter](https://mailchi.mp/3d439eeb1098/travis-ciorg-is-moving-to-travis-cicom)
- [migration docs](https://docs.travis-ci.com/user/migrate/open-source-repository-migration)

**Comment by camilamacedo86** [comment]
Hi @alexeldeib @mengqiy @pwittrock @droot 

I have no permission to do that. But it is something that we need to do.

**Comment by estroz** [comment]
The queue for travis.org linux/amd64 builds is huge, preventing jobs from being run for about an hour each. This should definitely happen sooner than later.

**Comment by camilamacedo86** [comment]
Hi @estroz, 

@Adirio has ben working on to push a change for we migrate from Travis to GA. If we are not be able to merge it soon we will do the migration.
