### ISSUE TITLE
printcolumn can't print when use --watch

### ISSUE THREAD

**Issue by nfyxhan** [kubernetes-sigs/kubebuilder#1753]
I defined a crd named `example` use kubebuilder, and set it has a printcollumn `column` with 
```
+kubebuilder:printcolumn:name="column",type=string,JSONPath=`.status.column`
```

i use `kubectl get example` it return like that has no `age`
```
NAME                 COLUMN
sample                column                
```
and i use `kubectl get example -w` it return like that has no `column`
```
NAME                 AGE
sample                17m
sample                 1s
```

* go version: 1.13
* kubebuilder version: 2.3.1 
  scaffolding version: 2
* controller-runtime version: v0.5.0
* controller-tools version: 
* Kubernetes & kubectl versions : v1.13.0

/kind bug

**Comment by gabbifish** [comment]
This is a known upstream Kubernetes apiserver error/feature request, and may be fixed by using a later version of Kubernetes (1.13.0 is quite old!) If you still run into problems, please file an upstream issue on kubernetes/kubernetes.
