### ISSUE TITLE
Extract CRD yaml generation into distinct tool

### ISSUE THREAD

**Issue by pmorie** [kubernetes-sigs/kubebuilder#176]
After talking with some folks who work on kubebuilder and the operator SDK it was identified that one common element is to have a tool (possibly eventually living in kubernetes codegen) that generates the CRD yaml from a Go type. This issue is to refactor this projects current capabilities in that area into a distinct tool.

**Comment by pwittrock** [comment]
@pmorie Feel free to re-assign

**Comment by pwittrock** [comment]
@pmorie Are you thinking as a library, separate binary, or both?  Should we generate both the go struct and yaml, or just the yaml?  We've been thinking of building a tool called `ktc` (kubernetes type compiler) that encapsulates the `*types.go` -> *generated files*.

- `ktc gen crds -o yaml`
- `ktc gen crds -o go`

**Comment by munnerz** [comment]
I for one would love to see a tool that simply spits out the CustomResourceDefinition YAML from my projects sources, preferably similar to how the docs generation works (i.e. not requiring a project be 'kubebuilder managed').

More generally, I think a less monolithic model for kubebuilder would be awesome if it were possible (i.e. kubebuilder becomes a wrapper around the many tools it is comprised of to make it easier for people to perform tasks like getting a controller built quickly).

**Comment by droot** [comment]
This is implemented under controller-tools --> https://github.com/kubernetes-sigs/controller-tools/blob/master/cmd/controller-gen/main.go

>More generally, I think a less monolithic model for kubebuilder would be awesome if it were possible (i.e. kubebuilder becomes a wrapper around the many tools it is comprised of to make it easier for people to perform tasks like getting a controller built quickly).

Thats the approach we have taken. High level libs are moved to controller-runtime and independent tools exist in controller-tools now. Kubebuilder is just a distribution of these tools/libs.

Closing this issue, pl. reopen or create new issue if there is more to be done here.
