### ISSUE TITLE
Make manifests is not working when  only the controller is scaffolded by the create api

### ISSUE THREAD

**Issue by camilamacedo86** [kubernetes-sigs/kubebuilder#1767]
**What broke**

After creating a project and scaffold just the controller the make manifests target will fail :

- `kubebuilder int` or `kubebuilder init --plugins=go/v3-alpha`
- $ kubebuilder create api --group ship --version v1beta1 --kind Frigate

```
Create Resource [y/n]
n
Create Controller [y/n]
y
```

What did you expect to happen?  What do you think went wrong?

The controller-gen is falling with the files scaffolded in this scenario: 

```
Users/camilamacedo/go/bin/controller-gen object:headerFile="hack/boilerplate.go.txt" paths="./..."
main.go:33:2: package testv2/api/v1beta1 is not in GOROOT (/usr/local/go/src/testv2/api/v1beta1)
Error: not all generators ran successfully
run `controller-gen object:headerFile=hack/boilerplate.go.txt paths=./... -w` to see all available markers, or `controller-gen object:headerFile=hack/boilerplate.go.txt paths=./... -h` for usage
make: *** [Makefile:62: generate] Error 1
```

- master commit 9c02d557f01bce86ce7df48a85f0e93aa3f39661

**Comment by prafull01** [comment]
Just checked this one myself.
/assign
