### ISSUE TITLE
Support for Application CRD 

### ISSUE THREAD

**Issue by liyinan926** [kubernetes-sigs/kubebuilder#179]
Depending on the nature of the applications or workloads controller deal with, they may need to create multiple types of resources, e.g., StatefulSets, services, ConfigMaps, etc., to support the applications to run. Those resources comprise naturally an application that can be modeled using an [Application](https://github.com/kubernetes-sigs/application) object. Examples of such applications include Redis, ZooKeeper, Spark, etc. It would be very useful to have first-class support for the Application CRD in the kubebuilder, e.g., having support for auto-generating references to the Application informer in `InjectArgs`.

@kow3ns

**Comment by droot** [comment]
Implementing this will be lot more easier once we add support for dynamic k8s client in KB.

**Comment by liyinan926** [comment]
@droot What would you suggest we should do short-term? For now, I just manually add the informer to `InjectArgs`. Is there a better way of doing this?

**Comment by pwittrock** [comment]
Adding the informer to the inject args seems like the way to go.  Be sure to start the informer in the inject package.

**Comment by pwittrock** [comment]
Closing to keep issue count from inflating.  Will track through milestone and project.
