### ISSUE TITLE
Improve go modules fulfillment

### ISSUE THREAD

**Issue by Adirio** [kubernetes-sigs/kubebuilder#1791]
- [x] Kubebuilder uses semantic versioning
- [x] Kubebuilder has a v2 or higher
- [x] Kubebuilder versions are listed on [pkg.go.dev](https://pkg.go.dev/mod/sigs.k8s.io/kubebuilder?tab=versions)

# Description
Although kubebuilder follows semantic versioning as required by go modules, only versions with major version 0 or 1 are actually obtainable by version with go modules. This can be seen in the link provided above.

The solution is to use a non-existent version and use the timestamp and commit hash to refer to a specific version. For example, [operator SDK](https://github.com/operator-framework/operator-sdk/blob/fd6179279e1cadf031bf857947b473e1ea414c2c/go.mod#L37) uses `sigs.k8s.io/kubebuilder v1.0.9-0.20201021204649-36124ae2e027` which refers to https://github.com/kubernetes-sigs/kubebuilder/commit/36124ae2e027c2643152f0d6b5bc7321c1417895.

In order to solve this, `go.mod` file needs to be changed to include `/v2` at the package name (`module sigs.k8s.io/kubebuilder/v2`) and internal imports need to reference to this same package.

I think it should definetely be implemented for future versions. However, I'm not sure what should be done with previous v2 versions. As previous versions are released, they are tagged and have their code compressed (it would change imports).

/kind feature

**Comment by camilamacedo86** [comment]
I think it is totally fine we leave the previous versions as it is. See that kb has not been provided as lib before the plugins be offered.

**Comment by pwittrock** [comment]
FYI -- for some reason this breaks pkger

**Comment by camilamacedo86** [comment]
The v2 branch was updated with that already.See: https://github.com/kubernetes-sigs/kubebuilder/pull/1878
Then, for the next patch release, it will be done.
