### ISSUE TITLE
Change module to v3 (can be done only when we will cut the 3.0.0-alpha release)

### ISSUE THREAD

**Issue by Adirio** [kubernetes-sigs/kubebuilder#1798]
- [ ] Update module name in `go.mod` to `sigs.k8s.io/kubebuilder/v3`
- [ ] Update the build command in `generate_testdata.sh` to `go build -o ./bin/kubebuilder sigs.k8s.io/kubebuilder/v3/cmd`
- [ ] Update imports to v3: `sigs.k8s.io/kubebuilder/v2` -> `sigs.k8s.io/kubebuilder/v3`
- [ ] Update `-ldflags` paths to v3 in `common.sh` and `build/.goreleaser.yml`

Equivalent v2 PR: #1792

**Comment by Adirio** [comment]
@camilamacedo86 could you add this to the `v3.0.0` milestone?

**Comment by camilamacedo86** [comment]
Besides we are unable to push a patch release from master the import of the pkg will still v2.3.1-abc-123. See; https://github.com/operator-framework/operator-sdk/blob/master/go.mod#L37

**Comment by camilamacedo86** [comment]
Hi @Adirio and @estroz, 

We should get it done before release the alpha one. However, I think we can move forward here now as well.

**Comment by camilamacedo86** [comment]
Done.
