### ISSUE TITLE
Scheme conflict with runtime.Encode

### ISSUE THREAD

**Issue by kqzh** [kubernetes-sigs/kubebuilder#1810]
/kind bug

go version 1.15
kubebuilder version: 2.3.1
controller-runtime version: v.0.6.3
kubernetes version: v1.18.9

hi, I'm worried about a strange problem. When I make run my code, it successfully entered in my crd's reconcile, can do something like get or update cr with client.Client , however, when I use the func runtime.Encode In "k8s.io/apimachinery/pkg/runtime" package, it cause the error: **no kind is registered for the type v1alpha1.crd in scheme "pkg/runtime/scheme.go:101"**

I guess it must something wrong with register scheme.

I make sure I register my scheme successfully, or I shouldn't be able to get in reconcile. I want to know what causes this problem.

**Comment by snowplayfire** [comment]
@kqzh I meet the same problem. 

Can you tell me how to solve it? Thanks!
