### ISSUE TITLE
Question: How to use klog as the logging library?

### ISSUE THREAD

**Issue by alok87** [kubernetes-sigs/kubebuilder#1819]
How to use klog library for the controller?
Please share an example.. if it is possible or not.

/triage support

**Comment by justinsb** [comment]
I do this by replacing the line `ctrl.SetLogger(zap.New(zap.UseDevMode(true)))` in main.go with `ctrl.SetLogger(klogr.New())`; the import is `"k8s.io/klog/klogr"`

**Comment by camilamacedo86** [comment]
I understand that it is sorted out as described above. So, I am closing this one. However, please feel free to ping us if you think that it should be re-opened.

**Comment by alok87** [comment]
It works, thanks @justinsb :)
