### ISSUE TITLE
Structured logging in JSON should be the default

### ISSUE THREAD

**Issue by max-rocket-internet** [kubernetes-sigs/kubebuilder#1820]
It's not 2013 so let's log in JSON by default 🚀

It looks like `controller-runtime.controller` logs partly in JSON anyway? For example I see this when my controller starts:

```
2020-11-13T12:29:15.573+0100	INFO	controller-runtime.controller	Starting EventSource	{"controller": "datadogmonitor", "source": "kind source: /, Kind="}
2020-11-13T12:29:15.678+0100	INFO	controller-runtime.controller	Starting Controller	{"controller": "datadogmonitor"}
2020-11-13T12:29:15.678+0100	INFO	controller-runtime.controller	Starting workers	{"controller": "datadogmonitor", "worker count": 1}
```

Currently in `main.go` there is `ctrl.SetLogger(zap.New(zap.UseDevMode(true)))`, I think we just need to change this to use a JSON encoder? How would that look? Does anyone have an example for people with existing projects?

/kind feature

**Comment by justinsb** [comment]
My 2c: let's switch to use klogr by default - we are a k8s project.

We can then decide whether klogr should use json by default :-)

**Comment by camilamacedo86** [comment]
Kubebuilder tool scaffold the controller-runtime logger. For the future versions/plugin, the logger impl will be changed. See; https://github.com/kubernetes-sigs/kubebuilder/commit/4eee159c9873718a4016ea0b264b7ff1218836c2

Controller-runtime does not use `klog`. See: https://github.com/kubernetes-sigs/controller-runtime/blob/master/pkg/log/zap/zap.go#L42. 

However, users are able to customize and change their scaffold as they wish. See: https://github.com/kubernetes-sigs/kubebuilder/issues/1819

In this way, if you would like that KB uses klog by default, I think we need to make it the default behaviour of [controller-runtime](https://github.com/kubernetes-sigs/controller-runtime) first. In this way, wdyt about raise this suggestion against [controller-runtime](https://github.com/kubernetes-sigs/controller-runtime) and we close this one here?

**Comment by max-rocket-internet** [comment]
@justinsb 

> We can then decide whether klogr should use json by default :-)

k8s has already started to move to structured logging, starting in 1.19 😉
https://kubernetes.io/blog/2020/09/04/kubernetes-1-19-introducing-structured-logs/

@camilamacedo86 

I don't want to use klog, I just think `kubebuilder init && kubebuilder create api ...` should create a project that logs in JSON by default. And also tell me how that would look so I can update my existing controllers 🙂

**Comment by Adirio** [comment]
Two different scopes here:
- `kubebuilder`: the cli library and actual CLI
- Scaffolded projects

If you refer to the second one, starting with a JSON based logger may increase the learning curve. I think this may be a good fit for a plugin once they can be piped one into another (phase 2). You would add the `json.logger` plugin at the end of your plugin pipe that would change the current logging to a JSON based one.

**Comment by camilamacedo86** [comment]
Hi @max-rocket-internet,  

As described in https://github.com/kubernetes-sigs/kubebuilder/issues/1820#issuecomment-728136843, in this case, Kubebuilder scaffolds what is provided by [controller-runtime](https://github.com/kubernetes-sigs/controller-runtime). Users are able to change it and do customization as they wish. However, if you would like to change the default behaviour by suggestion any change then, in POV it would need to be addressed on controller-runtime. I hope that it clarifies and help you with.

**Comment by max-rocket-internet** [comment]
OK thanks comrades, I will open an issue in the controller-runtime repo.
