### ISSUE TITLE
Make project version == 3 instead of 3-alpha (only for the stable release)

### ISSUE THREAD

**Issue by camilamacedo86** [kubernetes-sigs/kubebuilder#1832]
**What do you want to happen?**
update master branch for we have project version equals 3 instead of 3-alpha for the next release 

/kind feature

c/c @joelanford @DirectXMan12 @estroz

**Comment by camilamacedo86** [comment]
We discussed it in the bug triage meeting and then we agreed in:
- We will do first releases such as 3.0.0-alpha and then it should be done for we are able to release 3.0.0 stable
- Also, for the 3.0.0 stable, we need to make the v3-alpha plugin as stable.

**Comment by Adirio** [comment]
Done in #1968 
/close
