### ISSUE TITLE
Project version 2 deprecation

### ISSUE THREAD

**Issue by camilamacedo86** [kubernetes-sigs/kubebuilder#1837]
**What do you want to happen?**
As part of the 3.0.0 release, we ought to deprecate the v2 project in favour of v3. 

**Motivations**
See that after the [plugin design](https://github.com/kubernetes-sigs/kubebuilder/blob/master/designs/extensible-cli-and-scaffolding-plugins-phase-1.md) is in place the projects scaffolded with --project-version=2 will not add the plugins info into the PROJECT file. So, make sense we deprecated it with 3.0.0 release in order to keep its maintainability.

**Comment by estroz** [comment]
I remember discussing plugin deprecation during one of the community meetings. Did we decide on deprecating the N-1 or N-2 plugin? The biggest pro of the former is less painful plugin upgrades due to users being informed that they should upgrade to the Nth plugin rather than the N-1 plugin first. Conversely the latter gives people a longer grace period to switch, which could be considered "nice".

/ping @DirectXMan12 @joelanford

**Comment by camilamacedo86** [comment]
Hi @estroz, 

I agree with the policy definition `N-2` as well. 👍 

By looking it further in my POV what we essentially need to deprecated with the release 3.0.0 is the **`project-version=2`** since projects scaffolds with will NOT add the plugin info the Project file. So, I am updating this task accordingly. 

Regards the policy definition I raised a specific issue for we reach a consensus whcih ought to result in a doc statement. I do not think that it needs to be decided here at all. See: https://github.com/kubernetes-sigs/kubebuilder/issues/1848

**Comment by DirectXMan12** [comment]
does deprecate `N-1` mean "deprecate N as soon as N+1 is released"?  That potentially seems a bit aggressive of a timeline, but I'm not sure

**Comment by estroz** [comment]
>That potentially seems a bit aggressive of a timeline, but I'm not sure

I think so, or at least soon after. I would be more ok with this timeline if we had migration guides per commit that required them.

**Comment by brightzheng100** [comment]
The industry conversion is really about **N-2**, but it's okay to go more aggressive to be **N-1** as it's community driven.

But how we define **N-1** here, assuming we're going through `v2.2.x`, `v2.3.x`, `v3.0.x`?
- **N** means `v3.0.x` once `v3.0.x` is released
- **N-1** means `v2.3.x`

So do we support only `v2.3.x` (and `v3.0.x` of course) once `v3.0.x` is out?

**Comment by camilamacedo86** [comment]
Regards the plugin policy (N-1 or N-2) we have an issue to define that #1284. However, regards the Project version (Config) which is what I have in mind to discuss here. The plugins have [SupportedProjectVersions](https://github.com/kubernetes-sigs/kubebuilder/blob/b22ff1269cf5e11e8ae168189694204f3d1a07e1/pkg/plugin/interfaces.go#L35) and the project file will be naturally deprecated as well then, IMO it can be kept as simple as possible such as [KISS it](https://en.wikipedia.org/wiki/KISS_principle) 

- So, when a plugin version N be removed from the code source ( no longer supported ) all that is specific and valid ONLY for the plugin N should be removed from the code as well which means the Project version 

Example: 

- The project version V2 and all related/required for it will be removed when we remove v2 plugin.

**Comment by camilamacedo86** [comment]
It was discussed in the latest `Kubebuilder, Controller Runtime, and Controller Tools Meeting` and we reach the consensus that the project versions would be automatically deprecated with the plugin versions deprecations such as described in the above comment. 

So, I am closing this one as sorted out.
