### ISSUE TITLE
❓ / 🌱 Flag names and messages on built-in flag messages

### ISSUE THREAD

**Issue by christopherhein** [kubernetes-sigs/kubebuilder#1839]
Should we follow any of the standard Kubernetes flag names and messages for the built-in flags like `--leader-elect` instead of `--enable-leader-election`

https://kubernetes.io/docs/reference/command-line-tools-reference/kube-controller-manager/
```
--leader-elect     Default: true
Start a leader election client and gain leadership before executing the main loop. Enable this when running replicated components for high availability.
```

https://kubernetes.io/docs/reference/command-line-tools-reference/kube-proxy/
```
--metrics-bind-address ipport     Default: 127.0.0.1:10249
The IP address with port for the metrics server to serve on (set to '0.0.0.0:10249' for all IPv4 interfaces and '[::]:10249' for all IPv6 interfaces). Set empty to disable.
```

/kind feature

**Comment by christopherhein** [comment]
@camilamacedo86 @DirectXMan12 @estroz since we're doing the component config work, do you think it would be advantageous to also change the v3-alpha flag names and values when component config is off to match other standard kubernetes resources like Kube-proxy for `metric-bind-address` and `leader-elect` like kube-scheduler, kube-controller manager etc?

**Comment by estroz** [comment]
sgtm
