### ISSUE TITLE
Finalizer docs use invalid finalizer name

### ISSUE THREAD

**Issue by salaxander** [kubernetes-sigs/kubebuilder#1854]
https://github.com/kubernetes-sigs/kubebuilder/blob/2c3ae8fd18aa9c39326bd9f8776cc1f4db71fb0c/docs/book/src/cronjob-tutorial/testdata/finalizer_example.go#L54

Finalizers have to be qualified with a `/` in the name. The book currently uses `storage.finalizers.tutorial.kubebuilder.io` as an example finalizer. This should be changed to something like `tutorial.kubebuilder.io/finalizer`.

Happy to open a PR, just wanted to start with an issue to confirm that folks were ok with that!

**Comment by gabbifish** [comment]
Hi @salaxander! Thanks for bringing this up :) I think this is an important fix for us to have, and one I'd be happy to review when you have it ready! 

Consistent with the [finalizer example in the kubernetes docs](https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/#finalizers), where the CRD's group is used in the finalizer, perhaps we should rename the finalizer in this example to `batch.tutorial.kubebuilder.io/finalizer`?

**Comment by estroz** [comment]
Closed by #1877

/close
