### ISSUE TITLE
conversion webhook, crd config not updated, missing documentation ?

### ISSUE THREAD

**Issue by kidiyoor** [kubernetes-sigs/kubebuilder#1855]
Following instructions at https://book.kubebuilder.io/multiversion-tutorial/conversion.html
However crd conversion section is not updated
```
spec:
  conversion:
    strategy: None
```

Maybe a marker/annotation in the type.go is missing ? but documentation doesn't seem to point that out. I have already added the marker `// +kubebuilder:storageversion`
```
$ kubebuilder version
Version: version.Version{KubeBuilderVersion:"2.2.0", KubernetesVendor:"1.15.5", GitCommit:"0824a139f59e109c9e418a0b6e71a53c6e9e144f", BuildDate:"2019-11-20T00:00:24Z", GoOs:"unknown", GoArch:"unknown"}
```
```
$ controller-gen --version
Version: v0.3.0
```

/kind documentation

**Comment by estroz** [comment]
Did you also read the [deployment section](https://book.kubebuilder.io/multiversion-tutorial/deployment.html#deployment-and-testing)? Conversion webhooks won't work unless you follow the full set of docs for multiversion.

**Comment by DirectXMan12** [comment]
closing as per the above comment

**Comment by kidiyoor** [comment]
I see strategy being populated after uncomment a line in crd/config/patches dir under `patchesStrategicMerge:` section. Thanks. 

I set CRD_OPTIONS back to `CRD_OPTIONS ?= "crd:trivialVersions=true"`, since I was facing below error
```
kustomize build config/default > ../manifests.yaml
Error: accumulating resources: recursed accumulation of path '/Users/gautham/work/go/src/prod/k8s-controllers/provisioning/config/crd': failed to apply json patch '[{"op":"replace","path":"/spec/validation/openAPIV3Schema/properties/spec/properties/template/properties/spec/properties/containers/items/properties/ports/items/required","value":["containerPort","protocol"]},{"op":"replace","path":"/spec/validation/openAPIV3Schema/properties/spec/properties/template/properties/spec/properties/initContainers/items/properties/ports/items/required","value":["containerPort","protocol"]}]': replace operation does not apply: doc is missing path: /spec/validation/openAPIV3Schema/properties/spec/properties/template/properties/spec/properties/containers/items/properties/ports/items/required: missing value
```
