### ISSUE TITLE
Support to install kubebuilder on windows 

### ISSUE THREAD

**Issue by girishgouda** [kubernetes-sigs/kubebuilder#1857]
Support to install kubebuilder on windows

**Comment by camilamacedo86** [comment]
Hi @girishgouda, 

We have already a few open issues to achieve this goal. See: https://github.com/kubernetes-sigs/kubebuilder/issues/1405.
Your help with is very welcome. Shows that only use as a pre-requirement  https://www.cygwin.com/  on win let you work in the winos with it. 

So, I am closing this one as a duplicated issue of the others. However, feel free to raise new issues as well.
