### ISSUE TITLE
Generate README.md file explaining make targets and overall strategies for using operator 

### ISSUE THREAD

**Issue by wtrocki** [kubernetes-sigs/kubebuilder#1866]
Hi

It is quite common for generators to explain project structure and available commands in README.md
I'm quite happy to contribute that change to the repository if that is something that will be valuable. 

## What readme can have

- [x] Links to getting started
- [x] Explanation of the make commands (this can be done also using make help)`
- [x] Folder structure
- [x] Links to general information about tools used in the framework. Think https://github.com/kubernetes-sigs/kustomize 
- [x] General required reading https://kubernetes.io/docs/setup/

**Comment by camilamacedo86** [comment]
Bug Triage : After the issue, https://github.com/kubernetes-sigs/kubebuilder/issues/1867 get done we could add at the end of the scaffold command output to make clear that users can check the help or a link for the docs.

**Comment by camilamacedo86** [comment]
closing this one, since we will address the output as part of  #1867 .
