### ISSUE TITLE
[Suggestion] Make help printing available operations 

### ISSUE THREAD

**Issue by wtrocki** [kubernetes-sigs/kubebuilder#1867]
Generated makefile has a lot of commands for various tasks. 
It will be amazing for the tool to self-document (as any edit in the file can be reflected in help as well). This pattern is being widely used in Makefiles 

``` 
> make help

Welcome in the kubebuilder.
Available commands:

make build ... 
make install ...

```

**Comment by wtrocki** [comment]
Happy to contribute this change

**Comment by camilamacedo86** [comment]
This was accepted in the bug triage meeting. As part of this one,  we need to add at the end of the scaffold command output to make clear that users can check the help.
