### ISSUE TITLE
Add golangci-lint to the projects

### ISSUE THREAD

**Issue by camilamacedo86** [kubernetes-sigs/kubebuilder#1887]
**What do you want to happen?** 

- I am as a kubebuilder user, I'd like to check the projects scaffolds with the tool integrated/configured with golangci-lint so that, I could ensure the projects syntax 
- I am as a kubebuilder user, I'd like to have a makefile target to check my projects with golangci-lint so that, instead of call `go vet` and `go fmt` on the targets as execute other checks as well. 
- I am as a maintainer of kb, I'd to like to ensure that the projects built with the tool are "_linted_" automatically so that, if they have any syntax error checked by golangci-lint would fail in the CI

**Is there currently another issue associated with this?**

- https://github.com/kubernetes-sigs/kubebuilder/pull/805

**Implementation Details/Notes/Constraints**

- The Makefile scaffolded by the tool could have the same targets that we use for Kubebuillder. See: https://github.com/kubernetes-sigs/kubebuilder/blob/master/Makefile#L66-L73 
- The golangci-lint bin could also be downloaded in the project/bin directory
- We can call `make` in the [generate_testdata](https://github.com/kubernetes-sigs/kubebuilder/blob/master/generate_testdata.sh) after the projects are scaffolded so that, we can ensure in the CI that all make targets are working succefully as expected, and we will also be calling this new one. 

/kind feature

**Comment by camilamacedo86** [comment]
This issue was discussed in the bug triage meeting and we need to raise that as part of the agenda of the `Kubebuilder, Controller Runtime, and Controller Tools Meeting`. 

The main concern here is over we provide a tool/helper for a third-part project.

**Comment by Adirio** [comment]
This was already discussed and we didn't feel confortable forcing users to use a third-party development tool (in this case golangci-list) in their own project. In any case, it should be a plugin either golangci-lint or community maintained.

/close

**Comment by camilamacedo86** [comment]
This issue should not be closed. 
> This was already discussed and we didn't feel confortable forcing users to use a third-party development tool (in this case golangci-lint) in their own project. In any case, it should be a plugin either golangci-lint or community maintained.

The above is true. However, we agreed that we would linter the scaffolds in the tests (make generate) and CI to ensure that the code which is generated by the tool is passing in the lint.

**Comment by camilamacedo86** [comment]
It is done now.
