### ISSUE TITLE
Add coveralls integration 

### ISSUE THREAD

**Issue by camilamacedo86** [kubernetes-sigs/kubebuilder#1889]
**What do you want to happen?**

- I am as an Operator Developer,  I'd like to check the projects scaffolds with the tool integrated with [Coveralls](https://coveralls.io/)  and with a GA to call it so that,  I could easily persuade the goal to QA my projects and check its coverage as know how to integrate them with GA in the CI. 

**Implementation Details/Notes/Constraints**
- If the community decide that it would not be a good fit to the default scaffold via the init subcommand then, it might be a good fit to a plugin that could be called to add it as optional to the projects
- To achieve this goal we could scaffold the [GA](https://github.com/kubernetes-sigs/kubebuilder/blob/master/.github/workflows/ci.yml#L68-L89)  and then, ensure that the [Makefile target test](https://github.com/kubernetes-sigs/kubebuilder/blob/master/testdata/project-v3/Makefile#L21) is generating the file with the test coverage see the [example](https://github.com/kubernetes-sigs/kubebuilder/blob/master/Makefile#L96)   

/kind feature

**Comment by coderanger** [comment]
Is this for kb itself or the generated projects? I don't think integration with a commercial SaaS product would be appropriate for the output of kbuebuilder but for the project itself that's mostly an internal question. I personally prefer codecov.io but both are fairly interchangeable once the coverage report code is in place.

**Comment by Adirio** [comment]
> Is this for kb itself or the generated projects? I don't think integration with a commercial SaaS product would be appropriate for the output of kubebuilder but for the project itself that's mostly an internal question. I personally prefer codecov.io but both are fairly interchangeable once the coverage report code is in place.

She must mean the scaffolded projects because `kubebuilder` itself already uses coveralls. I already mentioned moving to codecov.io but we will probably do that once v3.0.0 is out, if we choose to migrate.

About the scaffolded projects, I kind of share @coderanger point. I know kubebuilder is opinionated but enforcing third-party tools may be too much. If we do it, it should be an option of the `cmd init ...` command and support at least the two mentioned in this issue.

**Comment by coderanger** [comment]
Every time we've had vendor-specific code in Kubernetes it's been a mistake, I see no reason this would end up any differently :) On top of the issues with vendor favoritism (are you ready to accept integration PRs from every vendor that wants to be included?), letting vendors control their own release cycles is usually for the best. Personally I wouldn't even want this under Kubernetes at all, I would put it in a 100% personal plugin, or get the vendor to own it.

**Comment by Adirio** [comment]
Making it a plugin and letting the vendor own it seems like a very good approach

**Comment by camilamacedo86** [comment]
Hi @coderanger and @Adirio, 

Thank you for your input following some considerations: 
- +1 to make a plugin instead of add in the default scaffold 👍 
- IMO the plugin ought to use the same coverage tool used in KB project. So, I am raising an issue for we move forward to use codecov.io  instead of coveralls on KB repo.

**Comment by camilamacedo86** [comment]
It was not accepted in the bug triage meeting as part of the kubebuilder project. however, would be fine if it got done and maintained by the vendors as suggested above.
