### ISSUE TITLE
Generated controller test for core-type resources cannot work

### ISSUE THREAD

**Issue by lichuqiang** [kubernetes-sigs/kubebuilder#189]
Most of the in-tree resources has extra validation, which can not be satisfied by the simple instance in the generated file "controller_test.go"

Take resource Deployment as an example, when running the test, I got error:
```
Deployment.apps "instance-1" is invalid: [spec.selector: Required value, spec.template.metadata.labels: Invalid value: map[string]string(nil): `selector` does not match template `labels`, spec.template.spec.containers: Required value]
```

I tried with kubebuilder 0.1.9, not sure if it still an issue in the latest code.

**Comment by pwittrock** [comment]
@lichuqiang This is working as intended.  The empty object isn't valid for a most core resource types.  File #192 to update the docs.
