### ISSUE TITLE
add check to ensure that any new file has the license in the header

### ISSUE THREAD

**Issue by camilamacedo86** [kubernetes-sigs/kubebuilder#1891]
**What do you want to happen?**

I am as maintainer would like to automatically ensure that any new file added to the project has a license. 

**Possible Solution**
Use the same check that we have in the SDK https://github.com/operator-framework/operator-sdk/blob/master/hack/check-license.sh. 

/kind feature

**Comment by Adirio** [comment]
We could also do this with a GitHub action.

**Comment by camilamacedo86** [comment]
We might like to add this one to the kubebuilder-tools and provide it across the board.

**Comment by sanya301** [comment]
Hi I'm new to open source contributions and working on a script similar to operator-sdk. I noticed that the sdk script is only checking `.go` files in certain directories. Did you want to maintain that behavior or also add checks for other file types such as `.sh` and `.yaml`?
