### ISSUE TITLE
move this into `config/manager`

### ISSUE THREAD

**Issue by georgettica** [kubernetes-sigs/kubebuilder#1894]
I am trying to create a bundle from operator-sdk and I need to put this file inside of the bundle (taking a different route than using `make bundle-build`)

if the reasoning is unclear I can elaborate further

https://github.com/kubernetes-sigs/kubebuilder/blob/c52c3679810a40a5ea09ab89d3a12fb228c1cfa4/pkg/plugins/golang/v3/scaffolds/internal/templates/config/rbac/auth_proxy_service.go#L35

**Comment by estroz** [comment]
Kubebuilder has no knowledge of bundles. As we discussed offline this will stay in config/rbac because it is tightly coupled to RBAC proxying.

/close

**Comment by georgettica** [comment]
thanks for the quick response though
