### ISSUE TITLE
Start using cert-manager v1.0.x

### ISSUE THREAD

**Issue by fabriziopandini** [kubernetes-sigs/kubebuilder#1896]
I would like to user cert manager v1.0.x, so I can benefit from latest features/better API stability

AFAIK there are different manifests and some gotchas for kuberentes < 1.6 https://cert-manager.io/docs/installation/kubernetes/#installing-with-regular-manifests

/kind feature

**Comment by camilamacedo86** [comment]
Hi @fabriziopandini, 

It is addressed for the plugin go/v3 in the PR https://github.com/kubernetes-sigs/kubebuilder/pull/1840  already. To use v3+ and check it so far you need to: 

- Use kubebuilder from master branch (it is not released yet)
- Create projects with the go/v3-alpha plugin via  `kubebuilder init --plugins=go/v3-alpha`

Also, you can migrate your project by following the doc in the master branch. However, note that itis in an alpha stage. See: https://github.com/kubernetes-sigs/kubebuilder/blob/master/docs/book/src/migration/project/v2_v3.md

The next release will be provided very soon as well. More info: https://github.com/kubernetes-sigs/kubebuilder/milestone/21

**Comment by camilamacedo86** [comment]
Closing it as sorted out. However, please feel free to raise new issues or ping us if you need it.
