### ISSUE TITLE
Error when executing "create config" repeatly

### ISSUE THREAD

**Issue by lichuqiang** [kubernetes-sigs/kubebuilder#190]
Seems when generating the config file (hack/install.yaml), kubebuilder will not check if the file already exist,
but overwrite the content in the file directly. 

Thus, if I generate the config once (image the file is of 150 lines), and then modify something in the controller (say remove some handle logic of extra resources), and create config again, then the content is expected to be shorter then it was the first time (say 100 lines). But in fact, kubebuilder will only overwrite the front 100 lines, and not remove the back 50 lines as expected, and the output file is broken.

I think it more reasonable to remove existing files and create a new one. Maybe we need to check if the same thing happens to other generated files.

**Comment by pwittrock** [comment]
@lichuqiang This is weird.  I would expect the file to be truncated.  Is this reproducible by hand?  Are tests being run in parallel?

**Comment by pwittrock** [comment]
That definitely isn't expected.  Would you be willing to take a look at why it might be doing this and submit a fix?

**Comment by lichuqiang** [comment]
sure thing
