### ISSUE TITLE
bump kube-apiserver version to 1.19

### ISSUE THREAD

**Issue by KnicKnic** [kubernetes-sigs/kubebuilder#1902]
With the graduation of ingress form beta to stable, I went to update my controller. It did not work because the test suite loaded a version of kubernetes that did not have ingress in stable. I think we should just move included kube-apiserver to 1.19.

**Btw** 1.20 removes insecure port. v1.19 of env test references this flag.

/kind bug

**Comment by camilamacedo86** [comment]
The binaries for the latest k8s releases are already generated. See: https://github.com/kubernetes-sigs/controller-runtime/blob/master/hack/setup-envtest.sh#L65

It will be part of the next kubebduiler release. However, before that, you also can use the script to download the latest versions available.  See: https://github.com/kubernetes-sigs/kubebuilder/blob/master/testdata/project-v3/Makefile#L17-L21

In this way, I am closing this one.
