### ISSUE TITLE
Extend custom metrics paragraph

### ISSUE THREAD

**Issue by jackap** [kubernetes-sigs/kubebuilder#1906]
Documentation on custom metrics https://book.kubebuilder.io/reference/metrics.html does not provide a comprehensive overview of how to implement the feature.
What I think should be added:
- Does the feature require running the CRD inside the cluster (i.e., run with `make deploy` instead of `make run`) ?
- Where does the `init()` function should be added (controllers/, api/, main.go) ?
- What is an alternative to `ServiceMonitor` in case another metrics-server is installed?

/kind documentation

**Comment by jackap** [comment]
Also, it seems that when building custom metrics with rbac, you need to instrument the ServiceMonitor to access https ports because http is the default.

**Comment by camilamacedo86** [comment]
It shows solved with https://github.com/kubernetes-sigs/kubebuilder/pull/2065.
However, please feel free to pig us to re-open if not.
