### ISSUE TITLE
Failed to start controller-manager with the built image

### ISSUE THREAD

**Issue by lichuqiang** [kubernetes-sigs/kubebuilder#191]
The container of  controller-manager failed with error message:
```
log: exiting because of error: log: cannot create log: open /tmp/controller-manager.kubeships-controller-manager-0.unknownuser.log.INFO.20180521-143551.1: no such file or directory
```
Seems the controller tries to write log into /tmp path, which does not exist in the base image scratch.
I replaced the base image with ubuntu in Dockerfile, and rebuild the image, and the controller-manager pod can work normally.

I tried with kubebuilder 0.1.9, not sure if it still an issue in the latest code.

**Comment by pwittrock** [comment]
:( . Would you change the image back to ubuntu until we have sufficient e2e testing?

**Comment by pwittrock** [comment]
@droot
