### ISSUE TITLE
gcr.io/distroless/static:nonroot fails with x509

### ISSUE THREAD

**Issue by kotyara85** [kubernetes-sigs/kubebuilder#1928]
Hello,
We do have our own CA.

I added this code into docker file to add certificates - 

```
FROM debian AS certs
RUN apt update && apt install curl -y
RUN curl <CERT> -o /usr/local/share/ca-certificates/cert.crt && update-ca-certificates
```

and then copy the whole directory to distroless container - 

```
COPY --from=certs /etc/ssl/certs /etc/ssl/certs
```

But still getting x509 signed by unknown authority error. Is there a way to fix this?
Thank you

**Comment by camilamacedo86** [comment]
What is your cluster vendor? It might be related to your environment. See for example: https://github.com/rancher/k3s/issues/1148.

**Comment by camilamacedo86** [comment]
Closing this one since we have not any feedback for a while. However, please feel free to create a new issue with further information if you need your help with.

**Comment by gangyi89** [comment]
Hi, we are facing the same issue. @kotyara85 did u manage to resolve it?
