### ISSUE TITLE
Error><Code>NoSuchKey</Code><Message>The specified key does not exist.</Message><Details>No such object:

### ISSUE THREAD

**Issue by eric-w-hart** [kubernetes-sigs/kubebuilder#1931]
When trying to download Kubebuilder with curl I am getting the above error. 
Have tried this on a 2019 Macbook with OS Mojave.

**Comment by camilamacedo86** [comment]
could you please provide more info? such as what version you are trying to download? 
Could you please add here all commands used to do that for we try to reproduce?

**Comment by Adirio** [comment]
We have been unable to reproduce this error as there is not enough information, feel free to reopen the issue with the requested information so that we can reproduce and help solve it.

/close

**Comment by Twistedredhead** [comment]
https://www.facebook.com/profile.php?id=100008571769043....what is this
