### ISSUE TITLE
Support for arm macOS

### ISSUE THREAD

**Issue by codeblooded** [kubernetes-sigs/kubebuilder#1932]
Now that docker and go have some support on arm macOS, do we plan to support development using kubebuilder on Apple Silicon?

----

Notes, add the following to the raised ticket to clarify its status:
To support Apple Silicon arm64, we need to:

- [x] : Begin to produce the Kubebuilder bin for this format **( done since the 3.4.0 release )**

However, we still need to:

- [x] :Produce the kubebuilder-tools for this format see: (https://storage.googleapis.com/kubebuilder-tools). For we are able to address this need, the issue: https://github.com/kubernetes-sigs/kubebuilder/issues/2664 was created.  (we need to have etcd binary for this architecture, see: https://github.com/operator-framework/operator-sdk/issues/5654)
- [ ] :Have kustomize v3 bin in this architecture (see: https://github.com/kubernetes-sigs/kustomize/issues/4612) 
AND/OR (no longer required with the PR: https://github.com/kubernetes-sigs/kubebuilder/pull/2758)
- [x] : be able to use kustomize v4. See the proposal PR with kustomize v4:  https://github.com/kubernetes-sigs/kubebuilder/pull/2583  **( will be available from the next release 3.5)**

PS.: We also might need to build the images with the arch/so, see: https://github.com/kubernetes-sigs/kubebuilder/issues/2695

/kind feature

**Comment by camilamacedo86** [comment]
Hi @codeblooded, 

I understand that what you are looking for is to kubebuilder provide kubebuilder_darwin_arm64 binaries as well. Am I right? It is not provided currently(https://github.com/kubernetes-sigs/kubebuilder/releases).

**Comment by codeblooded** [comment]
@camilamacedo86 Yes, I assume this will be blocked by the release of [Go 1.16](https://tip.golang.org/doc/go1.16) which adds support for darwin arm64. I just wanted to create the bug and see if it is a target that kubebuilder intends to support. 😄

**Comment by Adirio** [comment]
Just a comment, to include it in the automatic release process, we would also probably need to include it in the CI and I don't think this arch is supported by neither Prow nor GH Actions (except hosting our own runners).

**Comment by codeblooded** [comment]
That's true. I'm curious to see what they do for kubernetes/kubectl#988 which still needs triage. 

I'm sure actions will eventually support it, but I haven't seen a bug for it. I know some other CNCF projects are looking at or already using MacStadium. They now have racks of m1 minis in their data centers.

**Comment by Adirio** [comment]
Self hosted runners should support whatever OS/arch combination you want. But we are not using self hosted runners (neither for Prow nor fot GH Actions) in kubebuilder.

**Comment by joelanford** [comment]
Do we know if cross-compilation will be possible from linux_amd64 to darwin_arm64 when go 1.16 is released?

I have an M1 Mac, btw, so I am interested in this as well. I'm also a willing guinea pig :).

**Comment by Adirio** [comment]
> Do we know if cross-compilation will be possible from linux_amd64 to darwin_arm64 when go 1.16 is released?

Cross-compilation has never been an issue in Go so I don't expect it to be one now, but with these things, as I said yesterday in the triage meeting, you never know.

**Comment by schegi** [comment]
Any news about this?

**Comment by jpfourny** [comment]
Any progress on this? I hate having to use Rosetta on my M1 to compensate for lack `darwin-arm64` release. More and more organizations are replacing old Intel Macs with M1.

**Comment by imxw** [comment]
> 
you can use homebrew to download it.
 `brew install kubebuilder` 
[This version](https://formulae.brew.sh/formula/kubebuilder) supports Apple Silicon

**Comment by camilamacedo86** [comment]
See that for v3.4.0 we are building kubebuilder CLI for arm64.
Also, we have now: kubebuilder-tools-1.23.5-darwin-amd64.tar.gz as well. (https://storage.googleapis.com/kubebuilder-tools)
However, we still not able to fully support Apple Silicon because of the kustomize.
Kustomize v3 does not build versions for this. 

More info: 
- https://github.com/kubernetes-sigs/kubebuilder/releases/tag/v3.4.0
- https://github.com/kubernetes-sigs/kubebuilder/pull/2583

**Comment by camilamacedo86** [comment]
I am adding this one as a priority since it has been requested a lot. 
c/c @rashmigottipati @varshaprasad96 @jmrodri @ryantking @everettraven

**Comment by camilamacedo86** [comment]
removing the assignment to @gabbifish since she has no longer working on this one.

**Comment by imilchev** [comment]
+1 for this

**Comment by jwx0925** [comment]
+1 for this

**Comment by akutz** [comment]
@camilamacedo86 , do you want to close this, or leave it open as a way to track the etcd artifact?

**Comment by camilamacedo86** [comment]
Yes, I think we can close this one. 👍

**Comment by camilamacedo86** [comment]
To work with Apple Silicon users can:

> Update the kustomize version on the default scaffold with go/v3 to use kustomize v4.5.5
OR
> Try to experiment it with the new kustomize/v2-alpha plugin by currently running `kubebuilder init --plugins="kustomize/v2-alpha,base.go.kubebuilder.io/v3"`

We cannot say that we officially support the platafom until we generate a new golang plugin as `go/v4-alpha` OR we verify that we can move forward with  https://github.com/kubernetes-sigs/kubebuilder/pull/2758. Note that the kustomize docs about what is a breaking change or not from v3 to v4 is not very clear and seems like it might have changes not mapped or a bug.

**Comment by camilamacedo86** [comment]
Looking for PTAL https://github.com/kubernetes-sigs/kubebuilder/pull/2785 to close this one.
