### ISSUE TITLE
Enhance Generated Makefile

### ISSUE THREAD

**Issue by droctothorpe** [kubernetes-sigs/kubebuilder#1940]
The [Makefile](https://github.com/kubernetes-sigs/kubebuilder/blob/022fe5baf087326eaf8c2c094d3152b483583807/pkg/plugins/golang/v2/scaffolds/internal/templates/makefile.go) supplied by `kubebuilder init` could benefit from some additional functionality. 

For example:
* An automatically updated `help` target that prints all of the targets and a description of what they do.
* A controller delete target. Something along the lines of:
```bash
undeploy: manifests
	cd config/manager && kustomize edit set image controller=${IMG}
	kustomize build config/default | kubectl delete -f -
```
* A target to apply and a target to delete the auto-generated sample CR.

I would be happy to submit a PR in short order pending a green light from the team.

Thanks!

/kind feature

**Comment by Adirio** [comment]
- [x] The automatically updated help target SGTM. We already have this for kubebuilder (the project) Makefile. Ssafe to be applied to the v3 plugin. Mixed feelings about applying it to the v2 plugin though.
- [ ] We already have a `undeploy` target in v3 plugin.
- [ ] I dont feel like samples should have Make targets, but I don't have a strong opinion either.

**Comment by droctothorpe** [comment]
Thanks for the input, @Adirio ! 

PR submitted: https://github.com/kubernetes-sigs/kubebuilder/pull/1947

It might be nice to bring in the `lint` and `lint-fix` targets from the base Makefile into the makefile template as well. Happy to implement that if you think it makes sense.

**Comment by Adirio** [comment]
We already discussed it. We dont want to scaffold the golanggci-lint dependency, using it for our code is one thing, but scaffolding it for user generated projects is another.

In any case, it would be a plugin mantained by golangci-lint themselves.

**Comment by Adirio** [comment]
#1947 implemented this

/close
