### ISSUE TITLE
kubebuilder generation commands could have a validation flag

### ISSUE THREAD

**Issue by perotinus** [kubernetes-sigs/kubebuilder#195]
It would be helpful if `kubebuilder`'s generation commands had a flag that would allow them to be run in "validation" mode; i.e., running `kubebuilder generate --validate` would not touch any files, but would print out a diff and return error if the code in the repo does not match what it would be after a run `kubebuilder generate`. This could be made into a presubmit check on projects that use `kubebuilder`.

This could be done by each project, but it would be easier and more consistent if `kubebuilder` integrated this.

**Comment by pwittrock** [comment]
The ideal way to do this would be by adding a validation flag to each of the code generators called by kubebuilder.
