### ISSUE TITLE
Move branches tools-releases and kube-rbac-proxy-releases to kubernetes-sig/kubebuilder-release-tools

### ISSUE THREAD

**Issue by Adirio** [kubernetes-sigs/kubebuilder#1950]
[Branch `tools-releases`](https://github.com/kubernetes-sigs/kubebuilder/tree/tools-releases) is used to create the control plane binaries needed for tests. [Branch `kube-rbac-proxy-releases`](https://github.com/kubernetes-sigs/kubebuilder/treekube-rbac-proxy-releases) is used to create the kube RBAC proxy images needed for the controllers. This functionality should probably be moved to the repo [kubernetes-sigs/kubebuilder-release-tools](https://github.com/kubernetes-sigs/kubebuilder-release-tools).

/kind feature
/kind cleanup

**Comment by Adirio** [comment]
Mentioned during kubebuilder/controller-runtime/controller-tools meeting and positive feedback received about this movement.

**Comment by Adirio** [comment]
Once https://github.com/kubernetes-sigs/kubebuilder-release-tools/issues/31 is closed, we can delete this branch from this repo.

**Comment by camilamacedo86** [comment]
Hi @DirectXMan12 @pwittrock, 

Could you please give a hand to us regarding this one?
