### ISSUE TITLE
Unable to access external web address

### ISSUE THREAD

**Issue by tsurog** [kubernetes-sigs/kubebuilder#1962]
It seems that  GOPROXY parameter is invalid, China still can't access the specified URL, and kubebuilder version is the master branch.

root@DESKTOP-BFJMH29:/mnt/e/GoLang/project/src/example# docker build --no-cache . -t docker.io/manager:v1
Sending build context to Docker daemon  118.8MB
Step 1/14 : FROM golang:1.15 as builder
 ---> 5f46b413e8f5
Step 2/14 : WORKDIR /workspace
 ---> Running in 8345799db523
Removing intermediate container 8345799db523
 ---> 8542c7dbc00b
Step 3/14 : COPY go.mod go.mod
 ---> 14dbc8e3fdeb
Step 4/14 : COPY go.sum go.sum
 ---> 1fcc54a40dd9
Step 5/14 : RUN go mod download
 ---> Running in 5ff64f5da188
go: github.com/go-logr/logr@v0.3.0: Get "https://proxy.golang.org/github.com/go-logr/logr/@v/v0.3.0.mod": dial tcp 172.217.27.145:443: connect: connection refused
The command '/bin/sh -c go mod download' returned a non-zero code: 1
root@DESKTOP-BFJMH29:/mnt/e/GoLang/project/src/example# go env GOPROXY
https://goproxy.cn,direct
root@DESKTOP-BFJMH29:/mnt/e/GoLang/project/src/example# go env GONOPROXY
none
root@DESKTOP-BFJMH29:/mnt/e/GoLang/project/src/example# go env GOPRIVATE
none

**Comment by camilamacedo86** [comment]
The GOPROXY value is the default one for 1.15 go versions which are GOPROXY="https://proxy.golang.org,direct". If you are in a restrictive newtwork or using a private repo for your modules you need to ensure that you will have access to all modules required.

**Comment by camilamacedo86** [comment]
Closing this one since we have not any feedback for a while. However, please feel free to create a new issue with further information if you need your help with.
