### ISSUE TITLE
Best practice of dynamic ConcurrentReconciles

### ISSUE THREAD

**Issue by HamzaZo** [kubernetes-sigs/kubebuilder#1966]
My controller watches for created CR and starts to reconcile, in the reconcile loop I do some business logic using Terraform. If I create two CR at the same time :

* The reconcile loop get the first item from the workqueue and do the business logic which is what I expect. However, the second CR gets blocked until the first one succeeded. 

Afterwards, I noticed that the default value of concurrent reconciles is `worker.count=1`, so I modify ```SetupWithManager``` as follows:
```
func (r *PostgreSqlReconciler) SetupWithManager(mgr ctrl.Manager) error {
	pred := predicate.GenerationChangedPredicate{}
	return ctrl.NewControllerManagedBy(mgr).
		For(&cloudv1alpha1.PostgreSql{}).
		WithEventFilter(pred).
		WithOptions(controller.Options{
			MaxConcurrentReconciles: 10,
		}).
		Complete(r)
```
But I'm wondering, what is the best practice for dynamic concurrent reconciles? and how to let my controller handles differents request at the same time without hardcoding the value of `MaxConcurrentReconciles` ?  Also, If I create more than one replicas how to handle this ?

Any help is appreciated?
Thanks

/triage support

**Comment by camilamacedo86** [comment]
In general, it’s recommended to have one controller responsible for manage each API created for the project to properly follow the design goals set by controller-runtime. 

Regard your question see that It is not possible to have two reconcile loops that handle the same object at the same time. 

> how to let my controller handles differents request at the same time without hardcoding the value of MaxConcurrentReconciles 

By default, the MaxConcurrentReconciles will be 1 so you need to set another value if you are looking for that in the manager when the project is initialized.

It is not a k8s doc, however, might help you: http://openkruise.io/en-us/blog/blog2.html

**NOTE** It is not about your specific question, however, I'd like to share that regards the best practices over the controllers/reconciliation in general I'd say the main one would be to develop idempotent solutions. The idea is that when you reconcile a resource of our API(crd/cr) you are looking to do a collection of operations until it has the desired state on the cluster. I want to suggest you check doc [Groups and Versions and Kinds, oh my!](https://github.com/kubernetes-sigs/kubebuilder/blob/master/docs/book/src/cronjob-tutorial/gvks.md) to understand better what APIs means and be able to design better solutions.

I am closing this one as sorted out. However, if you still with doubts about it then, I'd suggested you raise a question in https://github.com/kubernetes-sigs/controller-runtime. Also, it would be very nice get your help for we are able to provide further information for MaxConcurrentReconciles [here](https://github.com/kubernetes-sigs/controller-runtime/blob/master/pkg/controller/controller.go#L37) for we have a better go doc [here](https://pkg.go.dev/sigs.k8s.io/controller-runtime/pkg/controller#Options).
