### ISSUE TITLE
Wrong CRD plural generated

### ISSUE THREAD

**Issue by benjaminhuo** [kubernetes-sigs/kubebuilder#1993]
- What broke (please include exact error messages if you can)
Wrong CRD plural generated, the following CRD is generated when running `kubebuilder create api --group openfunction.io --version v1alpha1 --kind FunctionBuild` or `make manifests`

![image](https://user-images.githubusercontent.com/18525465/107020772-3dabc500-67de-11eb-982b-351b2d8ece02.png)

- What did you expect to happen?  What do you think went wrong? 
`plural: functionbuilds` should be generated instead of  `plural: functionbuildren`

- What versions of software are you using?  Specifically, the following are often useful:

* go version 
   v1.14
* kubebuilder version (`kubebuilder version`) and scaffolding version (check your `PROJECT` file)
  v2.3.1
* controller-runtime version (check your `go.mod` file)
  v0.6.4
* controller-tools version
  controller-gen@v0.2.5

/kind bug

**Comment by Adirio** [comment]
In `kubebuilder` v2.3.1 plurals can not be manually provided and use `flect.Pluralize(strings.ToLower(<KIND>))` to obtain the plural form. v3.0.0 which will be released shortly offers a `-plural` flag that allows users to specify other plural forms.

**Comment by benjaminhuo** [comment]
Got it, thanks for the reply @Adirio 
Close this issue for now.

Ben
