### ISSUE TITLE
bump controller-runtime 0.8.0

### ISSUE THREAD

**Issue by camilamacedo86** [kubernetes-sigs/kubebuilder#1997]
Update the go/v3 plugin to use the latest version of controller-runtime.

**Comment by camilamacedo86** [comment]
blocker by https://github.com/kubernetes-sigs/kubebuilder-declarative-pattern/pull/146

**Comment by irvifa** [comment]
I think the aforementioned PR is already merged, is there anything else need to be done for this issue?

**Comment by camilamacedo86** [comment]
Hi @irvifa, 

The PR for this task is: https://github.com/kubernetes-sigs/kubebuilder/pull/1961
It will be only released as 3.1.0 after the 3.0.0 stable release and then, only will be merged after that as well.

**Comment by irvifa** [comment]
Thanks for the confirmation!

**Comment by estroz** [comment]
Closed by #1961
