### ISSUE TITLE
Dep is not installed. But Dep is a deprecated project.

### ISSUE THREAD

**Issue by jgallucci32** [kubernetes-sigs/kubebuilder#2006]
When running `kubebuilder init --domain my.domain` the following error is shown
```
2021/02/10 18:05:58 Dep is not installed. Follow steps at: https://golang.github.io/dep/docs/installation.html
```

Per the [project home page](https://github.com/golang/dep), Dep is an archived project and no longer supported
> Dep was an official experiment to implement a package manager for Go. As of 2020, Dep is deprecated and archived in favor of Go modules, which have had official support since Go 1.11. For more details, see https://golang.org/ref/mod.

Recommend the documentation be updated to reflect this and workarounds for best way to install Dep.

kubebuilder version
```
Version: version.Version{KubeBuilderVersion:"1.0.8", KubernetesVendor:"1.13.1", GitCommit:"1adf50ed107f5042d7472ba5ab50d5e1d357169d", BuildDate:"2019-01-25T23:14:29Z", GoOs:"unknown", GoArch:"unknown"}
```

/kind bug

**Comment by camilamacedo86** [comment]
For the next release and v3 projects will use go 1.15 and dep is no longer supported. 
This link does no longer exist in master. So it shows stored out already. Also, shows that you are using a very old version. So, I would recommend you check the latest release and upgrade your project as well. 

I am closing this one, however, feel free to ping us if you still needing help with.

**Comment by jgallucci32** [comment]
Thanks for the info. I ended up getting it working but you should be aware the Install and Setup documentation out of date. It currently lists 1.0.8 as the latest stable version
https://book-v1.book.kubebuilder.io/getting_started/installation_and_setup.html

I installed v2.3.1 which appeared to be the latest stable release and the problem is resolved.
