### ISSUE TITLE
Support for `resourceNames` in RBAC markers

### ISSUE THREAD

**Issue by phenixblue** [kubernetes-sigs/kubebuilder#2017]
Would like for Kubebuilder RBAC markers to also support the `resourceNames` field for further scoping of permissions in the scaffolded clusterrole

[K8s Docs: Referring to resources](https://kubernetes.io/docs/reference/access-authn-authz/rbac/#referring-to-resources)

/kind feature

**Comment by Adirio** [comment]
Just to make sure I understood you correctly, you want the `//+kubebuilder:rbac` marker to also support that field, right?

In that case, you should raise this issue in https://github.com/kubernetes-sigs/controller-tools.

**Comment by phenixblue** [comment]
Yes, that's correct. Thanks for the info, will open the issue on that project.

**Comment by phenixblue** [comment]
Just an FYI to anyone else that comes along...

The [controller-tools](https://github.com/kubernetes-sigs/controller-tools/releases/tag/v0.2.8) package implemented this in v0.2.8. From reading it looks like Kubebuilder 2.3 uses controller-tools v0.2.5, so it's not currently supported. Kubebuilder v3.x seems to jump to controller-tools 0.4.x and does include this.
