### ISSUE TITLE
Don't recommend using manager.GetClient in tests

### ISSUE THREAD

**Issue by moolen** [kubernetes-sigs/kubebuilder#2018]
Using the `manager.GetClient()` in tests is a bad idea and should not be recommended by the documentation. The manager's client is a cached `client.Reader` which is fine for a controller - but in tests you probably want a strongly consistent client.

This is the documentation i am referring to:
https://github.com/kubernetes-sigs/kubebuilder/blame/master/docs/book/src/cronjob-tutorial/testdata/project/controllers/suite_test.go#L115-L116

There's an older issue that explains the problem in more detail: https://github.com/kubernetes-sigs/controller-runtime/issues/343

I'd suggest updating the documentation about that. What do you think? Did anybody else run into that issue yet?

/kind bug
/kind documentation

**Comment by Adirio** [comment]
Any help with the documentaiton is appreciated
/help
/good-first-issue

P.S.: the most relevant part of the linked conversation is https://github.com/kubernetes-sigs/controller-runtime/issues/343#issuecomment-469435686

**Comment by leovct** [comment]
Hello @Adirio, I would like to contribute to the project by working on this issue :)

**Comment by Adirio** [comment]
Sure, help is always apreciated. Feel free to submit a PR and assign me so that I can review it.

**Comment by DirectXMan12** [comment]
To be clear for posterity (because the follow-up PR broke the tests): You shouldn't use the manager's client in *assertions* in tests.  You *should* use the manager's client in your reconciler.
