### ISSUE TITLE
✨ Export scaffolding machinery

### ISSUE THREAD

**Issue by Adirio** [kubernetes-sigs/kubebuilder#2036]
The scaffolding machinery is not being exported as it is placed in an `internal` directory (from older kubebuilder versions when it was not designed to be a library. We should probably move this package outside of `internal` so that it can be used by third-party developers.

As an example, [operator SDK](https://github.com/operator-framework/operator-sdk) is [copying this folder](https://github.com/operator-framework/operator-sdk/tree/master/internal/kubebuilder).

/kind feature

**Comment by camilamacedo86** [comment]
+1 for me.

**Comment by camilamacedo86** [comment]
@Adirio will also check if nobody has any objections to it before move forward ( controller-tools meeting and @DirectXMan12 )

**Comment by DirectXMan12** [comment]
Seems like the public part of these interfaces is fairly minimal, so it seems pretty reasonable to expose these without them being restrictive to internal refactor.
