### ISSUE TITLE
How to create distribution like kubebuilder-2..3.2.tar.gz from source code

### ISSUE THREAD

**Issue by averma111** [kubernetes-sigs/kubebuilder#2038]
Hi Team,

I am looking for solution where I need to build something like   kubebuilder-2..3.2.tar.gz from source code. That a requirement not just bin/kubebuilder from make install.

Any help is highly appretiated.

Thanks,
Ashish

**Comment by averma111** [comment]
Hi Team nay help will be appreciated.

Thanks,
Ashish

**Comment by Adirio** [comment]
v2 used to create a tarball that included envtest binaries. v3, however, fetches those binaries when needed:
https://github.com/kubernetes-sigs/kubebuilder/blob/2b464030b6e3f52756e3a1f4c01369ebd58e6dcf/testdata/project-v3/Makefile#L46-L50

Therefore, releases from now on will only contain the binary, and that is what is listed in the GitHub releases page.

**Comment by camilamacedo86** [comment]
Hi @averma111, 

You can use the source code. See the [How to build kubebuilder locally](https://github.com/kubernetes-sigs/kubebuilder/blob/master/CONTRIBUTING.md#how-to-build-kubebuilder-locally) in the Contribution guide.

The `kubebuilder-2..3.2.tar.gz` is the Kubebuider bin + the Envtest binaries requires to implement the tests. Forgo/v3 as described above the binaries are no longer required and their are fetch from the makefile target.

In this way, you can use the Kubebuilder code to build it as any other Go project. See [here](https://github.com/kubernetes-sigs/kubebuilder/blob/tools-releases/build/thirdparty/linux/Dockerfile) how the kubebuilder tools gen the tar.gz. 

I am closing this issue as sorted out. Feel free to open a new issue if you need it.
