### ISSUE TITLE
Add go-apidiff check and make sure we don’t make breaking changes.

### ISSUE THREAD

**Issue by camilamacedo86** [kubernetes-sigs/kubebuilder#2042]
Add go-apidiff check and make sure we don’t make breaking changes after the stable release. 
Note it is used by controller-runtime and we do the same here.

**Comment by goutamtadi1** [comment]
Hello @camilamacedo86,

I would like to request to assign this issue to me? I am interested in taking up this issue and fix it.

Thanks,
Goutam Tadi.

**Comment by camilamacedo86** [comment]
That is great. You can just run a comment /assign your name and the bot will do that for you.
