### ISSUE TITLE
Dockerfile template not updated after running 'kubebuilder edit --multigroup=true'

### ISSUE THREAD

**Issue by mijos** [kubernetes-sigs/kubebuilder#2049]
Docker build fails when changing to multigroup

...
Step 7/14 : COPY api/ api/
COPY failed: file not found in build context or excluded by .dockerignore: stat api/: file does not exist
make: *** [Makefile:59: docker-build] Fehler 1
...

1. kubebuilder init --domain my.test.com
2. kubebuilder edit --multigroup=true
3. make docker-build     // will succeed

The created Dockerfile scaffold didn't get updated after running `kubebuilder edit --multigroup=true` 
Changing the Dockerfile accordingly to use 'apis' instead works as expected.
Would be helpful to create a Dockerfile template for the multigroup case and updated it when updating the PROJECT file to also update the Dockerfile with the multigroup template.

Index: mtest/Dockerfile
===================================================================
--- mtest.orig/Dockerfile
+++ mtest/Dockerfile
@@ -11,7 +11,7 @@ RUN go mod download
 
 # Copy the go source
 COPY main.go main.go
-COPY api/ api/
+COPY apis/ apis/
 COPY controllers/ controllers/
 
 # Build

I've run into this with version 2.3.1. Also tested it with 2.3.2

[mijo@localhost mtest]$ kubebuilder version
Version: version.Version{KubeBuilderVersion:"2.3.1", KubernetesVendor:"1.16.4", GitCommit:"8b53abeb4280186e494b726edf8f54ca7aa64a49", BuildDate:"2020-03-26T16:42:00Z", GoOs:"unknown", GoArch:"unknown"}
[mijo@localhost mtest]$ ../kubebuilder version
Version: version.Version{KubeBuilderVersion:"2.3.2", KubernetesVendor:"1.16.4", GitCommit:"5da27b892ae310e875c8719d94a5a04302c597d0", BuildDate:"2021-02-16T19:31:47Z", GoOs:"unknown", GoArch:"unknown"}

/kind bug

**Comment by camilamacedo86** [comment]
It is solved in master and you can use the latest beta release to check out if you wish. See: https://github.com/kubernetes-sigs/kubebuilder/releases/tag/v3.0.0-beta.0

Closing that as sorted out for 3.0.0
