### ISSUE TITLE
README.md: Sprint Dashboard link seems unused and outdated

### ISSUE THREAD

**Issue by goutamtadi1** [kubernetes-sigs/kubebuilder#2051]
Hello,

I found that the Sprint Dashboard [link](https://github.com/kubernetes-sigs/kubebuilder/projects/1) in [Resources](https://gus.lightning.force.com/a07B00000097kQ9IAI) section is outdated. If this is unused, can I go ahead and delete this?

If there is any alternative link, please let me know. I will make an update and create a PR to fix this.

Thanks,
Goutam Tadi

**Comment by camilamacedo86** [comment]
Hi @goutamtadi1, 

We have been using the https://github.com/kubernetes-sigs/kubebuilder/milestones to track the next work planned for the project. Yes, it is outdated and actually closed already. 

So, shows that we close this issue as sorted out. WDYT?

**Comment by goutamtadi1** [comment]
Cool! thanks. 
A quick question: Can we update the corresponding link to use https://github.com/kubernetes-sigs/kubebuilder/milestones instead of the Closed Sprint Dashboard?
