### ISSUE TITLE
Is there any ways to specify what version of controller-runtime to be used in kubebuilder?

### ISSUE THREAD

**Issue by richard-liu-2020** [kubernetes-sigs/kubebuilder#2053]
When I use "kubebuilder init“ command，it always generate go.mod like this:
module webapp

go 1.13

require (
        k8s.io/apimachinery v0.17.2
        k8s.io/client-go v0.17.2
        sigs.k8s.io/controller-runtime v0.5.0
)

My envs are as following:
os: CentOS Linux release 7.5.1804
kubebuilder: 2.3.1
go: go1.15.2 linux/amd64

Is there any ways to specify what version of controller-runtime to be used in kubebuilder? Or I must modify go.mod manually?

**Comment by camilamacedo86** [comment]
See: https://github.com/kubernetes-sigs/kubebuilder/blob/master/docs/book/src/quick-start.md#versions-and-supportability

The versions which are defined in the Makefile and go.mod files are the versions tested and therefore is recommended to use the specified versions.

So, for each CLI and go plugin version you will find the recommended and tested dependencies. The controller-runtime is bumped in the go.mod. In this way, by using beta.0 release of the CLI (more info: https://github.com/kubernetes-sigs/kubebuilder/releases):

- You will get the version suggested
- You will get the scaffolds prepared to work with 

You can also check the migration guide from the previous version to the latest. It will be published after the stable release. See: https://github.com/kubernetes-sigs/kubebuilder/blob/master/docs/book/src/migration/v2vsv3.md

Also, note that we are close to release a 3.0.0 stable. More info: https://github.com/kubernetes-sigs/kubebuilder/issues/2029

In this way, I am closing this one as sorted out. However, please feel free to raise new issues if you need.

**Comment by XuPengfei-1020** [comment]
How can I speificy k8s version v0.21.2 with the newest kubebuilder?
If it can`t, what version of kubebuilder shoud I choose?
Thanks.

**Comment by XuPengfei-1020** [comment]
> See: https://github.com/kubernetes-sigs/kubebuilder/blob/master/docs/book/src/quick-start.md#versions-and-supportability
> 
> The versions which are defined in the Makefile and go.mod files are the versions tested and therefore is recommended to use the specified versions.
> 
> So, for each CLI and go plugin version you will find the recommended and tested dependencies. The controller-runtime is bumped in the go.mod. In this way, by using beta.0 release of the CLI (more info: https://github.com/kubernetes-sigs/kubebuilder/releases):
> 
> * You will get the version suggested
> * You will get the scaffolds prepared to work with
> 
> You can also check the migration guide from the previous version to the latest. It will be published after the stable release. See: https://github.com/kubernetes-sigs/kubebuilder/blob/master/docs/book/src/migration/v2vsv3.md
> 
> Also, note that we are close to release a 3.0.0 stable. More info: #2029
> 
> In this way, I am closing this one as sorted out. However, please feel free to raise new issues if you need.

So, how can I speificy k8s version v0.21.2 with the newest kubebuilder?
If it can`t, what version of kubebuilder shoud I choose?
Thanks.
