### ISSUE TITLE
[Documentation] Links in stylesheet for docs are invisible unless hovered over

### ISSUE THREAD

**Issue by erikh** [kubernetes-sigs/kubebuilder#2055]
I expect the link here to be underlined, or distinguished in some way from the other text. Happened on it by accident and it would have saved me some time knowing it was there prior. That's all. :)

![image](https://user-images.githubusercontent.com/18923/109764708-bc5f0c80-7ba8-11eb-9994-2af55bf5707d.png)

/kind documentation

**Comment by erikh** [comment]
https://book.kubebuilder.io/cronjob-tutorial/cronjob-tutorial.html is a link to the page, fwiw.

**Comment by Adirio** [comment]
Links do have different styles:
![image](https://user-images.githubusercontent.com/522770/109773347-61a4cf80-7bff-11eb-8c3b-69dac15c6b2f.png)

**Comment by Adirio** [comment]
I'm closing this as it doesn't seem to be reproducible, and, in any case doesn't seem related to kubebuilder. If you still need help don't hesitate to reopen it.

/triage not-reproducible
/close
