### ISSUE TITLE
prow jobs failing due to prow config go1.16 bump

### ISSUE THREAD

**Issue by estroz** [kubernetes-sigs/kubebuilder#2063]
https://github.com/kubernetes/test-infra/pull/21094 automatically bumped the infra presubmit config to go1.16, which is causing prow breakage due to some implicit module error. Until kubebuilder's dependencies (specifically controller-runtime) update to go1.16, it doesn't make sense to update kubebuilder's go version. For now I suggest the infra PR changes be reverted until the bump to go1.16 is made here.

/kind failing-test
/label testing

**Comment by estroz** [comment]
Fixed by https://github.com/kubernetes/test-infra/pull/21173.

**Comment by Adirio** [comment]
@estroz did you mean to write 1.19 for one and 1.18 for the rest or did you mean to write their correspondinjg version for each? Asking without knowing anything about those images just to check that it was not just a typo.

**Comment by estroz** [comment]
Yes. The 1.18 image uses go1.13, while 1.19 uses go1.15.

**Comment by estroz** [comment]
This isn't quite fixed. The go version used to build kubebuilder and run tests, and that needed for projects differ. I'm going to pin all versions to go1.15 since that worked previously until a compartmentalized solution comes up.

**Comment by estroz** [comment]
https://github.com/kubernetes/test-infra/pull/21196

**Comment by Adirio** [comment]
They are working now, closing

/close
