### ISSUE TITLE
[META] Go 1.16

### ISSUE THREAD

**Issue by Adirio** [kubernetes-sigs/kubebuilder#2067]
This issue aims to tracks all the changes that need to/can be done once moving to go 1.16. This is obviously gated by dependencies.

- [ ] [cleanup] Go 1.16 sets `GO111MODULES` to `on` by default instead of `auto`. There are several remanents of this env variable that we should remove throughout the codebase.
- [ ] [enhancement] Go 1.16 includes a new `embed` package that allows to embed files into the binary using `//go:...`-style comments. This allows to split the files template from their logic offering way better support by IDEs (templates will no longer be a string, so they will be styled, auto-completed, and all the goodness of IDEs).

If there is any other feature enabled/required by go 1.16 that you will like to see in this list, please comment and I will update the list.

**Comment by camilamacedo86** [comment]
We also need before that just to clarify, have the same bump in controller-runtime, declarative-kb and k8s-api before we are able to address that here.

**Comment by kuritka** [comment]
The `go install` command can install go programs without affecting mod file dependencies. For example, executing `go install github.com/dummy/myapp@v0.1.2` is enough. Will you plan to update Makefile  ?
something like this :
```Makefile
# would work in GO1.16
generate: 
	## Download controller-gen locally if necessary.
	go install sigs.k8s.io/controller-tools/cmd/controller-gen@v0.4.1
	## Generate code containing DeepCopy, DeepCopyInto, and DeepCopyObject method implementations.
	controller-gen object:headerFile="hack/boilerplate.go.txt" paths="./..."
```





or you plan to support older GO versions (stay with `go get...` / [go-get-tool](https://github.com/kubernetes-sigs/kubebuilder/blob/master/testdata/project-v3-addon/Makefile#L92)), 
like this:
```Makefile
# without GO1.16
generate: controller-gen ## Generate code containing DeepCopy, DeepCopyInto, and DeepCopyObject method implementations.
	$(CONTROLLER_GEN) object:headerFile="hack/boilerplate.go.txt" paths="./..."

CONTROLLER_GEN = $(shell pwd)/bin/controller-gen
controller-gen: ## Download controller-gen locally if necessary.
	$(call go-get-tool,$(CONTROLLER_GEN),sigs.k8s.io/controller-tools/cmd/controller-gen@v0.4.1)

# go-get-tool will 'go get' any package $2 and install it to $1.
PROJECT_DIR := $(shell dirname $(abspath $(lastword $(MAKEFILE_LIST))))
define go-get-tool
@[ -f $(1) ] || { \
set -e ;\
TMP_DIR=$$(mktemp -d) ;\
cd $$TMP_DIR ;\
go mod init tmp ;\
echo "Downloading $(2)" ;\
GOBIN=$(PROJECT_DIR)/bin go get $(2) ;\
rm -rf $$TMP_DIR ;\
}
endef

```

**Comment by DirectXMan12** [comment]
@kuritka AFAIK, `go install-ing` something is still global, so while we could potentially switch to using `go install` instead of `go mod init; go get`, we'd still have to have the `GOBIN` trick to avoid clobbering the user's existing configuration, unfortunately

**Comment by estroz** [comment]
I believe I found a blocker: our test matrix. I think some bug fixes (features?) in go 1.16 made module installation more strict (see https://github.com/kubernetes-sigs/kubebuilder/pull/2182/checks?check_run_id=2614771863#step:6:520), which results in errors in go/v2 tests. For full backwards-compatibility, we'll likely want to start running all tests in `golang:{x}.{y}` containers like in prow.

**Comment by sonnysideup** [comment]
I'm slightly confused. Is this still an issue now that [3.1.0](https://github.com/kubernetes-sigs/kubebuilder/releases/tag/v3.1.0) is out? It seems like https://github.com/kubernetes-sigs/kubebuilder/pull/2182 updates kubebuilder to Go 1.16 but perhaps that's related to building the CLI vs what the CLI supports?

**Comment by estroz** [comment]
Both the `kubebuilder` binary and projects created by the binary use go 1.16, so I'm going to close this.

/close
