### ISSUE TITLE
Scaffolded `.dockerignore` does not do what it claims

### ISSUE THREAD

**Issue by busser** [kubernetes-sigs/kubebuilder#2073]
When running `make docker-build` for an operator scaffolded with kubebuilder v3, the entire directory is included in the Docker build context.

I expected only Go source files to be included in the Docker build context. Here is the scaffolded `.dockerignore` file:

```
# More info: https://docs.docker.com/engine/reference/builder/#dockerignore-file
# Ignore all files which are not go type
!**/*.go
!**/*.mod
!**/*.sum
```

To reproduce, build a dummy Docker image containing the entire build context:

```bash
docker image build -t build-context -f - . <<EOF
FROM busybox
COPY . /build-context
WORKDIR /build-context
CMD find .
EOF
```

Now run it:

```bash
docker container run --rm build-context
```

Or explore the images contents:

```bash
docker container run --rm -it build-context /bin/sh
```

I've traced the issue to this source code:
https://github.com/kubernetes-sigs/kubebuilder/blob/2018a4f1c8dbcff9b868b80af03c7879c707edbe/pkg/plugins/golang/v3/scaffolds/internal/templates/dockerignore.go#L41-L46

For reference, this is my Docker version:

```bash
Client: Docker Engine - Community
 Cloud integration: 1.0.7
 Version:           20.10.2
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        2291f61
 Built:             Mon Dec 28 16:12:42 2020
 OS/Arch:           darwin/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.2
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       8891c58
  Built:            Mon Dec 28 16:15:28 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.3
  GitCommit:        269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc:
  Version:          1.0.0-rc92
  GitCommit:        ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

```

/kind bug

**Comment by busser** [comment]
It seems to me that the `.dockerignore` file has unexpected behavior. It does not handle a directory wildcard `**` properly when it is right after an exclamation `!`.

For instance, If I replace the `.dockerignore`'s contents with these:

```
# More info: https://docs.docker.com/engine/reference/builder/#dockerignore-file
# Ignore all files which are not go type
*
!**/*.go
```

The contents of the `controllers/` directory are not included in the Docker build context. However, with this `.dockerignore` file:

```
# More info: https://docs.docker.com/engine/reference/builder/#dockerignore-file
# Ignore all files which are not go type
*
!controllers/**/*.go
```

The Go files in the `controllers/` are properly included.

**Comment by busser** [comment]
I figure that the easiest way to work around this issue is to change the scaffolded `.dockerignore` file to ignore all files expect those referenced in the scaffolded `Dockerfile`. The `.dockerignore` file would thus contain:

```
# More info: https://docs.docker.com/engine/reference/builder/#dockerignore-file
# Ignore all files which are not go type
*
!go.mod
!go.sum
!main.go
!controllers/**/*.go
!api/**/*.go
```

If that's OK with you, I can open a PR to make the change.

**Comment by camilamacedo86** [comment]
It is great. Please, feel free to collab with the solution.
