### ISSUE TITLE
undeclared name: logf

### ISSUE THREAD

**Issue by nagou** [kubernetes-sigs/kubebuilder#2076]
hi Team,
       how can we resolve following :

controllers/suite_test.go:51:2: undeclared name: logf

**Comment by leovct** [comment]
Hello @nagou, do you have the line `logf "sigs.k8s.io/controller-runtime/pkg/log"` in the `import()` section of `suite_test.go` ? If not, add it and it should solve your issue.

**Comment by nagou** [comment]
My bad while raising issue :

Actual issue is : 
controllers/suite_test.go:53:21: LoggerTo not declared by package zap

**Comment by nagou** [comment]
sigs.k8s.io/controller-runtime v0.8.3

**Comment by leovct** [comment]
Switch to `v0.5.0` and you are good to go 😉

**Comment by nagou** [comment]
With the latest package of sigs.k8s.io/controller-runtime v0.8.3 (or even earlier), "sigs.k8s.io/controller-runtime/pkg/log/zap" has deprecated function "zap.LoggerTo". New API is "zap.New".

After using this new API, I mitigated it.

logf.SetLogger(zap.New(zap.WriteTo(GinkgoWriter), zap.UseDevMode(true)))

**Comment by Adirio** [comment]
@nagou just bear in mind that being a 3 major-ish (until v1.0.0, minor version updates can be breaking, thats why I am calling them "major-ish") version bump, you will probably find additional conflicts on your way.
