### ISSUE TITLE
E2E test for prometheus metrics

### ISSUE THREAD

**Issue by johanneswuerbach** [kubernetes-sigs/kubebuilder#2087]
In https://github.com/kubernetes-sigs/kubebuilder/pull/2065 it was discovered that only the availability of the `/metrics` is tested https://github.com/kubernetes-sigs/kubebuilder/blob/73cda2b4333d221d9074c15110eac35c9bd7efc9/test/e2e/v3/plugin_cluster_test.go#L170-L177, but whether the `ServiceMonitor` is actually configured correctly is not test covered.

Add an e2e tests, which validates that prometheus can actually scrape the `/metrics` endpoint.

/kind feature

**Comment by camilamacedo86** [comment]
Thank you for raise it. Could you please let us know how can we check that` ServiceMonitor is actually configured correctly`? What are the steps done manually? 

See that the test/check is made [here](https://github.com/kubernetes-sigs/kubebuilder/blob/73cda2b4333d221d9074c15110eac35c9bd7efc9/test/e2e/v3/plugin_cluster_test.go#L313) where we check that is possible curl the metrics endpoint. So, could you please describe what test/step should be done?

**Comment by Adirio** [comment]
Further context: https://github.com/kubernetes-sigs/kubebuilder/pull/2065#discussion_r589267678

@estroz mentioned he may be able to work on this so pinging him

**Comment by camilamacedo86** [comment]
Hi @Adirio, 

I am afraid that the comment added here does not clarifies my questions.  @johanneswuerbach, maybe my question is silly. however, would be very good if you already have the steps then be able to add them here.
