### ISSUE TITLE
Document how people can create their own plugins

### ISSUE THREAD

**Issue by camilamacedo86** [kubernetes-sigs/kubebuilder#2098]
The goal here is to document what is possible with this plugin architecture so that end-users can start building their own plugins for special use cases or languages. 

It is blocked by: #2060, #1941, #2015

Note that after we get merged #2015 we can for example run `kb init --plugins=config/v1` and get the common base and then, and wee can indeed scaffold the files with any language that pleases us and without using the KB go lib and still compatible/following the same base structure for the scenarios where for example we would like to use generic common plugins such as we have in SDK.

**Comment by camilamacedo86** [comment]
Hi @lander2k2, 

The PR : https://github.com/kubernetes-sigs/kubebuilder/pull/2115 for this issue is done. Then, would be very nice indeed get your help in its review.

**Comment by lander2k2** [comment]
Awesome news @camilamacedo86 - will check it out Monday morning
