### ISSUE TITLE
Include etcd, kube-apiserver and kubectl binaries in linux_arm64 tar ball

### ISSUE THREAD

**Issue by fengye87** [kubernetes-sigs/kubebuilder#2117]
I've noticed that there are no etcd, kube-apiserver or kubectl binary in linux_arm64 tar ball. Is this intentional? I mean it could save a lot of troubles in testing controller-runtime projects on ARM64 platform if the tar ball includes them, just like the AMD64 one does.

/kind feature

**Comment by Adirio** [comment]
`kubebuilder version` output, please

**Comment by fengye87** [comment]
@Adirio Sorry about that, the output:

```
Version: version.Version{KubeBuilderVersion:"2.3.1", KubernetesVendor:"1.16.4", GitCommit:"8b53abeb4280186e494b726edf8f54ca7aa64a49", BuildDate:"2020-03-26T16:42:00Z", GoOs:"unknown", GoArch:"unknown"}
```

**Comment by Adirio** [comment]
Makes sense. Version 3 no longer is provided as a tar ball, the corresponding binaries are downloaded as needed. It should work for the specified platform. Closing as this feature request should already be implemented in v3. Feel free to comment if it doesn't meet your needs.

**Comment by jessemillar** [comment]
@Adirio Are you implying `kubebuilder` is capable of downloading the `etcd`, etc. binaries at runtime? Or is there some Makefile target that needs to be invoked?

**Comment by Adirio** [comment]
> @Adirio Are you implying `kubebuilder` is capable of downloading the `etcd`, etc. binaries at runtime? Or is there some Makefile target that needs to be invoked?
> 
> **Edit:** I'm assuming that it's `make test` that installs the binaries based on [this documentation](https://book.kubebuilder.io/reference/envtest.html#configuring-your-test-control-plane)? That's a somewhat annoying change for those of us installing `kubebuilder` on builder machines as part of automated build pipelines especially since it appears to require Go version 1.16.+ which I am not currently capable of running on my build agents.

Yes, `make test` downloads the required binaries for testing.
Go 1.16 was recently supported but is not required afaik.

**Comment by fengye87** [comment]
From what I can tell, `make test` is leveraging [this script](https://github.com/kubernetes-sigs/controller-runtime/blob/v0.7.2/hack/setup-envtest.sh) from the controller-runtime project. Though there's nothing special other than downloading or unpacking things in the script, it is relying a Go env at [line 66](https://github.com/kubernetes-sigs/controller-runtime/blob/v0.7.2/hack/setup-envtest.sh#L66) to get machine arch and OS info. But this should not be a Go 1.16 only thing, any reasonably recent Go versions should support this.

@jessemillar
