### ISSUE TITLE
Regression: extra commands require a valid PROJECT file again

### ISSUE THREAD

**Issue by jmrodri** [kubernetes-sigs/kubebuilder#2125]
https://github.com/kubernetes-sigs/kubebuilder/blob/master/pkg/cli/cli.go#L194 returns an error when it can not parse the config file. This means that extra commands will no longer work. This affects the `operator-sdk` because we have a command `alpha config-3alpha-to-3` that will convert `3alpha` PROJECT config to valid 3 config. But the error prevents this command from ever running.

Similarly, `version` also no longer works if we can't parse the PROJECT config file which is a regression.

What versions of software are you using?  Specifically, the following are often useful:

* go version
* kubebuilder version (`kubebuilder version`) and scaffolding version (check your `PROJECT` file): *v3.0.0-beta.1`
* controller-runtime version (check your `go.mod` file)
* controller-tools version
* Kubernetes & kubectl versions (just run `kubectl version` against your API server)

/kind bug

**Comment by Adirio** [comment]
I would not consider this a regression as the previous case was when the config file didn't exist.
