### ISSUE TITLE
`make test` fails in docs/book/src/cronjob-tutorial/testdata/project

### ISSUE THREAD

**Issue by dashpole** [kubernetes-sigs/kubebuilder#2128]
From HEAD, running `make test` from docs/book/src/cronjob-tutorial/testdata/project fails with:

`SideEffects is required for creating v1 {Mutating,Validating}WebhookConfiguration`

If I fix that by adding the `sideEffects=None` tag to webhooks, it fails with:

`AdmissionReviewVersions is mandatory for v1 {Mutating,Validating}WebhookConfiguration`

If I fix that by adding the `admissionReviewVersions=v1` tag to webhooks, it fails during the e2e test with:

```
2021-04-07T07:50:46.247-0700	ERROR	controller-runtime.manager.controller.cronjob	Reconciler error	{"reconciler group": "batch.tutorial.kubebuilder.io", "reconciler kind": "CronJob", "name": "test-cronjob", "namespace": "default", "error": "field label \".metadata.controller\" not supported for batchv1.Job"}
```

And thats where I got stuck.  Any pointers would be appreciated.  I ran into the "field label not supported" issue on my own project, and don't know how to proceed.

* go version: 1.16
* kubebuilder version (`kubebuilder version`) and scaffolding version (check your `PROJECT` file): kubebuilder 2.3.2, [PROJECT file](https://github.com/kubernetes-sigs/kubebuilder/blob/master/docs/book/src/cronjob-tutorial/testdata/project/PROJECT)
* controller-runtime version (check your `go.mod` file): [go.mod](https://github.com/kubernetes-sigs/kubebuilder/blob/master/docs/book/src/cronjob-tutorial/testdata/project/go.mod) v0.7.0
* Kubernetes & kubectl versions (just run `kubectl version` against your API server): kubectl v1.16.4

/kind bug

cc @DirectXMan12

**Comment by camilamacedo86** [comment]
Hi @dashpole, 

We need to update the projects in the book dir. 
See that we have shell scripts to re-generate them and then we can use an IDE to compare with the master branch and put back all comments/docs text on top. 

Would you like to work on that ?

**Comment by dashpole** [comment]
Which script?

I'm mostly interested in figuring out how to fix the error: `"field label \".metadata.controller\" not supported for batchv1.Job"`, since i'm hitting that in my own project.

**Comment by camilamacedo86** [comment]
You did not execute `make install` first. Let me know if you are able to do that after it.

**Comment by dashpole** [comment]
After that, I get:
```
removing project ...
starting to generate the cronjob ...
creating tutorial.kubebuilder.io base  ...
Error: unknown flag: --domain
...
```

**Comment by DirectXMan12** [comment]
> I'm mostly interested in figuring out how to fix the error

This looks like for some reason the fake field selector that we use as an index key is being used against the API server as a real field selector.

**Comment by DirectXMan12** [comment]
https://github.com/kubernetes-sigs/kubebuilder/pull/2066 broke the tests by misinterpreting the "don't use the manager's client in the tests" reccomendation.  I'll comment there and suggest a fix

**Comment by dashpole** [comment]
Thanks @DirectXMan12!  Thats what I need to unblock my work.

**Comment by camilamacedo86** [comment]
Closing that as solved in the master branch.
