### ISSUE TITLE
logr@v.01.0 dependency failing to complete create API 

### ISSUE THREAD

**Issue by AlexsJones** [kubernetes-sigs/kubebuilder#2135]
I apologise if this belongs in controller tools but I cannot differentiate whether this is actually a dependency issue or a controller issue.

Here is a recording...

[![asciicast](https://asciinema.org/a/IjN1dFYArWURISiWZPu4NtU1j.svg)](https://asciinema.org/a/IjN1dFYArWURISiWZPu4NtU1j)

```
/Users/alexjones/Code/go/bin/controller-gen object:headerFile="hack/boilerplate.go.txt" paths="./..."
Error: go [list -e -json -compiled=true -test=false -export=false -deps=true -find=false -tags ignore_autogenerated -- ./...]: exit status 1: go: github.com/AlexsJones/metadata-crd/controllers: package github.com/go-logr/logr imported from implicitly required module; to add missing requirements, run:
	go get github.com/go-logr/logr@v0.1.0
```

I expected this command to run successfully...

```
kubebuilder create api --group metadata --version v1alpha1 \
 --kind MetaDataContext --resource=true --controller=false --namespaced=false
```

Software versions:

- `go version go1.16.3 darwin/arm64`
- `Darwin Alexs-MacBook-Pro.local 20.3.0 Darwin Kernel Version 20.3.0: Thu Jan 21 00:06:51 PST 2021; root:xnu-7195.81.3~1/RELEASE_ARM64_T8101 arm64`
- `Version: version.Version{KubeBuilderVersion:"2.3.2", KubernetesVendor:"unknown", GitCommit:"5da27b892ae310e875c8719d94a5a04302c597d0", BuildDate:"2021-02-22T21:16:26-08:00", GoOs:"darwin", GoArch:"arm64"}`
- `sigs.k8s.io/controller-runtime v0.5.0`
* `Client Version: version.Info{Major:"1", Minor:"20+", GitVersion:"v1.20.4-dirty", GitCommit:"e87da0bd6e03ec3fea7933c4b5263d151aafd07c", GitTreeState:"dirty", BuildDate:"2021-03-15T09:51:17Z", GoVersion:"go1.16.2", Compiler:"gc", Platform:"darwin/arm64"}`

/kind bug

**Comment by Adirio** [comment]
Go 1.16 is not officially supported yet, go1.15 should work. Lastest unstable releases should also solve this issue but Go 1.16 is still not supported so it may fail in other places.
