### ISSUE TITLE
`create webhook`: return error when used with a core type

### ISSUE THREAD

**Issue by estroz** [kubernetes-sigs/kubebuilder#2141]
When I run `kubebuilder create webhook` on a core type, ex. `v1.Pod`, the command attempts to define methods on a non-existent locally-defined type. Instead, the command should return an error explaining that core types are not supported by this command.

```console
$ go version
go version go1.15.2 linux/amd64
$ kubebuilder version
Version: main.version{KubeBuilderVersion:"v3.0.0-alpha.0-195-g37485126", KubernetesVendor:"unknown", GitCommit:"37485126f95ceb2e92a86497c31f400c8b89f957", BuildDate:"2021-04-12T18:30:56Z", GoOs:"linux", GoArch:"amd64"}
$ cat go.mod | grep controller-runtime
sigs.k8s.io/controller-runtime v0.7.2
```

/kind bug

**Comment by camilamacedo86** [comment]
IHMO, we ought to support that. 
So, that means: 

- create api properly work with core/external types: RFE: https://github.com/kubernetes-sigs/kubebuilder/issues/2141

AND that means

- change here: https://github.com/kubernetes-sigs/kubebuilder/blob/master/pkg/plugins/golang/v3/webhook.go#L107 for:

- If is core type then update the PROJECT file accordingly and scaffold the webhook
- if is external-type (we need a new flag for that) then, do the same. 

So, IMO we should **not** spend effort in change the message but actually in moving forward with the RFE https://github.com/kubernetes-sigs/kubebuilder/issues/2141

**Comment by estroz** [comment]
This solution is more of a holdover until something like what is suggested [here](https://book.kubebuilder.io/reference/webhook-for-core-types.html) is implemented and kustomize-able resources are generated correctly for core/external types.

Alternatively the holdover can be skipped entirely if the `Handler` implementation can be completed without an EP, which I think it can.

@kopiczko if you'd like to work on either this and/or implement core/external type support in `create webhook`, feel free to assign yourself!

**Comment by kopiczko** [comment]
Cool, thanks, I'll look into this and check what I can do in the following days. Possibly starting wit the error message is a good warmup for me.

**Comment by kopiczko** [comment]
Hi @estroz,

I was trying to think what would be the good way to fix this and found that doesn't only apply to the core types.

In general:

```
$ kubebuilder create api --group "mygroup" --version "v1" --kind "MyKind" --controller=true --resource=false
Writing scaffold for you to edit...
controllers/mykind_controller.go
Update dependencies:
$ go mod tidy

$ kubebuilder create webhook --group "mygroup" --version "v1" --kind "MyKind" --defaulting
Writing scaffold for you to edit...
api/v1/mykind_webhook.go

$ tree api
api
└── v1
    ├── mykind_webhook.go
    └── webhook_suite_test.go

1 directory, 2 files
```

Setting `--controller=false` gives the same output. You can replace `--group "mygroup"` with `--group ""` and the output will be the same.

So I'd say the issue is that webhook methods are generated on non-existent resource in general?

**Comment by Adirio** [comment]
More than an issue, they are a unsupported feature. We only support webhooks for types we have scaffolded ourselves.

**Comment by kopiczko** [comment]
Shouldn't generating scaffolding for the resource also be forbidden in `kubebuilder create api`?

**Comment by estroz** [comment]
Theoretically `create api` can create a controller for a core type. When I run `kubebuilder create api --controller`, I get a controller for no resource, so technically it does work right now. I propose better handling of this situation by accepting some import path that can then be used in a controller in #1999. The `--resource` flag should generate an error though.

**Comment by cloudziu** [comment]
Hello, do you plan to add scaffolding webhooks for core resources?

**Comment by camilamacedo86** [comment]
> Hello, do you plan to add scaffolding webhooks for core resources?

Yes, we should do that as we do for controllers.
we are able to scaffold controllers for Core Types nowadays so we should do the same for webhooks.
