### ISSUE TITLE
Extend files whitelist for init cmd v3

### ISSUE THREAD

**Issue by w3st3ry** [kubernetes-sigs/kubebuilder#2159]
### What do you want to happen?

This issue is related to [this one from `operator-sdk`](https://github.com/operator-framework/operator-sdk/issues/4796).

The allowed/whitelisted files for init cmd (in v3) are quite restricted, I would like to extend the list by whitelisting `.md` files extension + capitalized files name (like OWNERS, SECURITY, WORKSPACE...).

A PR will follow.

**Comment by camilamacedo86** [comment]
In the bug triage meeting, we discussed it and seems that would be fine. However, that could not allow has the PROJEC file already.
