### ISSUE TITLE
v2 to v3 migration guides 404

### ISSUE THREAD

**Issue by hdonnay** [kubernetes-sigs/kubebuilder#2167]
### What broke? What's expected?

These links:

* https://book.kubebuilder.io/migration/migration_guide_v2tov3.html
* https://book.kubebuilder.io/migration/manually_migration_guide_v2_v3.html

which are found in the body of the documentation as well as in the sidebar, shouldn't 404.

### KubeBuilder (CLI) Version

N/A

### Extra Labels

/kind documentation

**Comment by daenney** [comment]
Both links you provided work for me.

```
~/D/p/g/d/kubebuilder ❯❯❯ curl -I https://book.kubebuilder.io/migration/migration_guide_v2tov3.html                                                    daenney/ver-constraint
HTTP/2 200 
cache-control: public, max-age=0, must-revalidate
content-length: 0
content-type: text/html; charset=UTF-8
date: Sun, 02 May 2021 16:42:42 GMT

~/D/p/g/d/kubebuilder ❯❯❯ curl -I https://book.kubebuilder.io/migration/manually_migration_guide_v2_v3.html                                            daenney/ver-constraint
HTTP/2 200 
cache-control: public, max-age=0, must-revalidate
content-length: 0
content-type: text/html; charset=UTF-8
date: Sun, 02 May 2021 16:42:49 GMT
```

There's been a couple of PRs to fix things for the book, which I suspect probably resolved your issue too: https://github.com/kubernetes-sigs/kubebuilder/pulls?q=is%3Apr+is%3Aclosed+book

**Comment by camilamacedo86** [comment]
that seems solved. closing this one. However, please feel free to ping us if required to re-open this one.
