### ISSUE TITLE
Cannot scaffold with Go 1.16

### ISSUE THREAD

**Issue by daenney** [kubernetes-sigs/kubebuilder#2172]
### What broke? What's expected?

I can't scaffold a project if my Go version is 1.16 without using `--skip-go-version-check`. Using `--skip-go-version-check` results in a perfectly functional project.

Though I'm sure there are improvements in Go 1.16 that kubeduilder could take advantage of, given the Go 1 compatibility guarantee I'm a little puzzled as to why kubebuilder choses to enforce an upper boundary on supported Go versions.

Given Go 1.16 was released 2.5 months before the kubebuilder 3 release it also seems a bit strange the current version of Go isn't supported.

### Reproducing this issue

Have the `go` command on your path resolve to a Go version of 1.16

```
2021/05/02 16:00:09 failed to initialize project: unable to run pre-scaffold tasks of "base.go.kubebuilder.io/v3": go version 'go1.16.3' is incompatible because 'requires 1.13 <= version < 1.16'. You can skip this check using the --skip-go-version-check flag
```

### KubeBuilder (CLI) Version

3.0.0

**Comment by Adirio** [comment]
Go 1.16 is not supported and already documented. There is a meta issue tracking some of that info: #2067
