### ISSUE TITLE
"changes since" links in releases are broken since v3.0.0-rc.0

### ISSUE THREAD

**Issue by daenney** [kubernetes-sigs/kubebuilder#2174]
### What broke? What's expected?

When going through the releases on GitHub, the "changes since previous_version" links are broken since v3.0.0-rc.0

### Reproducing this issue

Go to https://github.com/kubernetes-sigs/kubebuilder/releases/tag/v3.0.0-rc.0 and look at the link that gets pointed to for "changes since v3.0.0-beta.1".

It worked for previous releases. It looks like whatever is generating the changelog is no longer interpolating the repository organisation and name.

### KubeBuilder (CLI) Version

3

### Extra Labels

/kind documentation

**Comment by Adirio** [comment]
I fixed them manually, these links are being generated and #2031 is already tracking that issue.
