### ISSUE TITLE
Make it easy to build multi-platform images

### ISSUE THREAD

**Issue by daenney** [kubernetes-sigs/kubebuilder#2175]
### What do you want to happen?

Right now the Docker image generated by the scaffolder hardcodes `GOARCH=amd64` when building. This results in the image always containing an amd64 binary. This will probably also result in a broken image if one were to build this on a non-amd64 host. With Arm gaining momentum in the server space, it would be nice if easily building for a different architecture and building multi-platform images becomes possible with the same Dockerfile.

It's probably better if the Docker image doesn't hardcode the `GOARCH`. For folks that then want to build arm64 or s390 images, they can then use the same Dockerfile, and use [buildx](https://docs.docker.com/buildx/working-with-buildx/) to properly build multiarchitecture images.

**Comment by camilamacedo86** [comment]
Would like to propose a solution on this one? Please, feel free to raise a PR against master.
