### ISSUE TITLE
Create api is not calling make manifests

### ISSUE THREAD

**Issue by camilamacedo86** [kubernetes-sigs/kubebuilder#2188]
### What broke? What's expected?

The full description can be checked in: 
https://github.com/operator-framework/operator-sdk/issues/4928

### Reproducing this issue

Just run create api and see that the CRD is not generated. 

### KubeBuilder (CLI) Version

3.0.0

### PROJECT version

3.0.0

### Plugin versions

```yaml
v3
```

### Other versions

master

### Extra Labels

/kind regression

**Comment by estroz** [comment]
I don't think this is a bug. Looking at the blame, when the go/v3 plugin was [created 12 months ago](https://github.com/kubernetes-sigs/kubebuilder/blame/14b27b4e24ba476b19de776f7a05fc56edf993cd/pkg/plugins/golang/v3/api.go#L236), `make all` was called on `kubebuilder create api` which [ran](https://github.com/kubernetes-sigs/kubebuilder/blame/1cd45e2a727fc5579c0195dc5397a9b418c5d7e7/pkg/plugins/golang/v3/scaffolds/internal/templates/makefile.go#L83) `generate`, `vet`, and `fmt` targets. That call was scoped down to [just `make generate`](https://github.com/kubernetes-sigs/kubebuilder/blame/faff1482f454cabffb4e685a138a72a3ca040324/pkg/plugins/golang/v3/api.go#L239) as the most recent change.

If this is a feature request, that's a different story and warrants discussion.

**Comment by Adirio** [comment]
No, this was totally intentional.
The scaffolded types file needs to be modified. This means that the generated CRD if you run `make all` during `k9r create api` it will create a partial CRD that will have to be updated, so there is no reason to create it. And by "needs to" and "will have to be" I'm not saying that the user MAY update it, I'm saying that it MUST update it. If a plugin would create a full types file, it could run `make manifests` at the post-scaffold hook.

**Comment by camilamacedo86** [comment]
After discussion in the bug triage meeting was decided:
- do not gen the samples (cr) by default
- then, add a nice msg to let the user knows that is required to gen the target to get the manifests.

**Comment by estroz** [comment]
@digambar15 just be aware that the relevant implementation is captured in https://github.com/kubernetes-sigs/kubebuilder/issues/2188#issuecomment-852345561 and not the title/description.

/assign @digambar15

**Comment by digambar15** [comment]
> @digambar15 just be aware that the relevant implementation is captured in [#2188 (comment)](https://github.com/kubernetes-sigs/kubebuilder/issues/2188#issuecomment-852345561) and not the title/description.
> 
> /assign @digambar15

Thanks @estroz  I will go through it

**Comment by digambar15** [comment]
@guhaneswaran has fixed the issues- Here is the PR - https://github.com/kubernetes-sigs/kubebuilder/pull/2233

**Comment by guhaneswaran** [comment]
Look at #2236 instead of #2233
