### ISSUE TITLE
Migration guide for minor releases

### ISSUE THREAD

**Issue by camilamacedo86** [kubernetes-sigs/kubebuilder#2191]
### What do you want to happen?

After the 3.1.0 release, a user asked the info over how to upgrade/update their project with the latest changes from 3.0.0 to 3.1.0. In SDK we work with migration guides for the minor releases as well (e.g. https://sdk.operatorframework.io/docs/upgrading-sdk-version/v1.7.1/) Also, we have a process to add the steps in each PR (see its [template](https://github.com/operator-framework/operator-sdk/blob/master/changelog/fragments/00-template.yaml)). 

Then, I'd like to know if the community and others think that would be beneficial for kubebuilder to provide similar guides and have a similar process as well.

**Comment by camilamacedo86** [comment]
Let's raise it in the Kubebuilder, Controller Runtime, and Controller Tools Meeting (Agenda doc: https://docs.google.com/document/d/1Ih-2cgg1bUrLwLVTB9tADlPcVdgnuMNBGbUl4D-0TIk/edit#heading=h.dp4gt7gj3cn )

**Comment by estroz** [comment]
From ^: a starting point is kubernetes' [release-notes](https://github.com/kubernetes/release/tree/master/cmd/release-notes) tool.

**Comment by camilamacedo86** [comment]
Summary of the discussion in Kubebuilder, Controller Runtime, and Controller Tools Meeting the idea is OK:
- No objections over we have the migration guide for that or ask for contributors to fill the steps in this case
- The complexity here is only find a way to put this in place without effects or requires a big effort to adjust the current process to release.

**Comment by camilamacedo86** [comment]
lifecycle/stale
