### ISSUE TITLE
README badges are broken (build of book-v2)

### ISSUE THREAD

**Issue by camilamacedo86** [kubernetes-sigs/kubebuilder#2193]
### What broke? What's expected?

See: 

<img width="515" alt="Screen Shot 2021-05-28 at 09 36 21" src="https://user-images.githubusercontent.com/7708031/119955701-33355700-bf98-11eb-9040-38c0d0f732ee.png">

### Reproducing this issue

https://travis-ci.org/github/kubernetes-sigs/kubebuilder

### KubeBuilder (CLI) Version

0

**Comment by vorburger** [comment]
I had a quick look at this, thinking it may just be a broken URL, but seeing https://api.travis-ci.org/kubernetes-sigs/kubebuilder.svg?branch=master also show _build: unknown_, suspect that this may be related (I'm not sure) to the big banner on top at https://travis-ci.org/github/kubernetes-sigs/kubebuilder saying:

_Please be aware travis-ci.org will be shutting down by end of May 2021. Please consider migrating to travis-ci.com._

Not sure if this project's maintainer can switch it to travis-ci.com? Or time for something else? (E.g. Google Cloud Build?) Perhaps something that needs to be looked at more globally accross https://github.com/kubernetes-sigs, not per project...

**Comment by camilamacedo86** [comment]
Hi @vorburger, 

yes, for the master branch and v3 we are no longer using travis.  (imo) we can disable the build of v2 on Travis also, I do not think that would be valid the effort to change that since seems unlike we push any 2.x release. 

@DirectXMan12 wdyt? PS.: I do not think that we have access to disable that and we would need your help. 

c/c @estroz @jmrodri
