### ISSUE TITLE
Doc about Logging in "What’s in a controller" chapter is outdated?

### ISSUE THREAD

**Issue by vorburger** [kubernetes-sigs/kubebuilder#2194]
### What broke? What's expected?

https://book.kubebuilder.io/cronjob-tutorial/controller-overview.html's doc re. logging seems inconsistent with the code I'm seeing produced by the latest `kubebuilder` release _v3.1.0_... there is no import for `"github.com/go-logr/logr"` and the `*Reconciler` doesn't have a `Log logr.Logger` field - anymore, presumably that was removed and doc is out of date?

Do you want a PR that juts removes that? (Or is it other way around and that will be generated in a future release?)

### Reproducing this issue

https://github.com/vorburger/LearningKubernetes-CodeLabs/blob/develop/docs/kubebuilder.md

https://github.com/vorburger/LearningKubebuilder/blob/develop/controllers/foo_controller.go

### KubeBuilder (CLI) Version

3.1.0

### PROJECT version

3

### Plugin versions

```yaml
go.kubebuilder.io/v3
```

### Other versions

go.mod (as generated, I didn't touch this):

```
require (
        github.com/onsi/ginkgo v1.14.1
        github.com/onsi/gomega v1.10.2
        k8s.io/apimachinery v0.20.2
        k8s.io/client-go v0.20.2
        sigs.k8s.io/controller-runtime v0.8.3
)
```

### Extra Labels

/kind documentation

**Comment by dharmjit** [comment]
Hi Folks, Is it something still to work upon. I could work on this if nobody is.

**Comment by varshaprasad96** [comment]
@dharmjit sure, please feel free to assign this to yourself. Looks like the issue revolves around updating the kubebuilder doc section (ref: https://book.kubebuilder.io/cronjob-tutorial/controller-overview.html) with the latest changes appearing after a kb project is scaffolded (especially the reconciler and the imports).

**Comment by camilamacedo86** [comment]
/remove-lifecycle stale

Any progress in this one?

**Comment by dharmjit** [comment]
@camilamacedo86 Sorry, I got caught up with work. I just looked at this and found that this [doc](https://github.com/kubernetes-sigs/kubebuilder/blob/master/docs/book/src/cronjob-tutorial/testdata/emptycontroller.go) is already improved for imports/logs in #2273 and the same is reflected in local `mdbook serve`.  But it's not updated in the [kubebuilder book](https://book.kubebuilder.io/cronjob-tutorial/controller-overview.html). Are there any additional steps required to be performed to update the content on netlify.
