### ISSUE TITLE
Doc: Chapter "You said something about main?" should be moved to previous chapter?

### ISSUE THREAD

**Issue by vorburger** [kubernetes-sigs/kubebuilder#2195]
### What broke? What's expected?

The https://book.kubebuilder.io/cronjob-tutorial/main-revisited.html which is currently §1.7.1 *AFTER* (under) §1.7 _Implementing a controller_ reads like it may have been meant to rather be a §1.6.1 in/after §1.6 _What’s in a controller?_.

At least to me it seems like that's the order one would want to read that.

Would you like a PR to move it?

### KubeBuilder (CLI) Version

3.1.0

### Extra Labels

/kind documentation

**Comment by camilamacedo86** [comment]
c/c @rashmigottipati

**Comment by camilamacedo86** [comment]
/remove-lifecycle stale

Any progress in this one?
