### ISSUE TITLE
How to build operator for multi architectures?

### ISSUE THREAD

**Issue by alex-arica** [kubernetes-sigs/kubebuilder#2206]
### What do you want to happen?

Hello,

I am managing the project [Kubegres](https://github.com/reactive-tech/kubegres) which is an operator allowing to enable clusters of PosgreSql instances by enabling replication, failover and backup.

It was developed using Kubebuilder version 3. 

I had [a request from the community](https://github.com/reactive-tech/kubegres/pull/16) to build and push Docker images of the operator for multiple architectures. I looked into the official doc and it does not seem like there is a way to generate multi-architecture images of the operator from one source code. 

Is there a plan to have such feature?

**Comment by anthr76** [comment]
```json
skopeo --override-arch=arm64 inspect docker://gcr.io/kubebuilder/kube-rbac-proxy:v0.8.0
{
    "Name": "gcr.io/kubebuilder/kube-rbac-proxy",
    "Digest": "sha256:db06cc4c084dd0253134f156dddaaf53ef1c3fb3cc809e5d81711baa4029ea4c",
    "RepoTags": [
        "v0.4.0",
        "v0.4.1",
        "v0.5.0",
        "v0.8.0",
        "v0.8.0-amd64",
        "v0.8.0-arm64",
        "v0.8.0-ppc64le",
        "v0.8.0-s390x"
    ],
    "Created": "2020-11-04T16:22:18.100348695Z",
    "DockerVersion": "18.06.0-ce",
    "Labels": null,
    "Architecture": "amd64",
    "Os": "linux",
    "Layers": [
        "sha256:5c7fe08dec514a5105d43dfcae1a5a45be002bcd3251dd178ced702aecfb7531",
        "sha256:9d443775309fe30cb1c2b25750352e70004cf26baaf32c81daff7f5a05375845"
    ],
    "Env": [
        "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
        "SSL_CERT_FILE=/etc/ssl/certs/ca-certificates.crt"
    ]
}
```

It looks as though in it's current state kubebuilder isn't built with a "fat-manifest" though multi-arch images are being built which is greatly appreciated. When running a multi-arch cluster though this becomes a problem. It would be great if we can not tag the different architectures! 

semi related PR: https://github.com/kubernetes-sigs/kubebuilder/pull/2197

**Comment by camilamacedo86** [comment]
We need to create a doc about it in the Kubebuilder docs.
The content of https://github.com/operator-framework/operator-sdk/pull/5178/files can be used as help for it or linked.

**Comment by camilamacedo86** [comment]
Other related issue is: https://github.com/kubernetes-sigs/kubebuilder/issues/2298
