### ISSUE TITLE
Add migration instructions for Tests and test suites from kubebuilder v2 to v3

### ISSUE THREAD

**Issue by subodh-dharma** [kubernetes-sigs/kubebuilder#2209]
### What do you want to happen?

Currently, the kubebuilder book has migration instructions for controllers, CRDs and APIs. It would be nice to have a section for the migration of test files as well.

Some of the tests scaffolded during the kubebuilder v2 need to be updated.

I believe the same applies for migration from kubebuilder v1 to v2, depending on the number of requests, this migration path can also be documented.

### Extra Labels

/kind documentation

**Comment by camilamacedo86** [comment]
Hi @subodh-dharma, 

Thank you for raise that. Note that in the testdata dir we have samples. In this way, the steps to solve this one seems like:

- compare the tests scaffolds with 2.3.1 (https://github.com/kubernetes-sigs/kubebuilder/tree/v2.3.2/testdata)
- with the tests scaffolds with master (https://github.com/kubernetes-sigs/kubebuilder/tree/master/testdata/)

Then, after that update the migration doc. Would you like to help with that? What do you think bout push a PR with it?

**Comment by subodh-dharma** [comment]
That sounds like a good first issue. I have worked on migrating these tests recently on a project I developed at my org. I can use that experience as well to document these migration steps.
