### ISSUE TITLE
`kubebuilder create webhook --conversion` not creating needed scaffolding piece

### ISSUE THREAD

**Issue by jberkhahn** [kubernetes-sigs/kubebuilder#2231]
### What broke? What's expected?

I'm trying to use kubebuilder to scaffold a conversion webhook while making a new crd version (v1alpha1 to v1beta1) for my operator. I run the command `kubebuilder create webhook --conversion --version v1beta1 --kind Memcached --group cache`, which generates a bunch of scaffolding pieces in config/, the webhook in api/, and adds it to the manager bootup sequence in main.go. I then mark v1beta1 as the storage version, and implement the Hub and Convert interfaces in the types.go files for my crds. I also uncomment out all the sections in config/ that are marked with WEBHOOK and CERTMANAGER, per the kubebuilder docs. However, when I try to `make deploy` my operator, I get the following kustomize error:
```
/Users/jberkhahn/workspace/projects/memcached-operator/bin/controller-gen "crd:trivialVersions=true,preserveUnknownFields=false" rbac:roleName=manager-role webhook paths="./..." output:crd:artifacts:config=config/crd/bases
cd config/manager && /Users/jberkhahn/workspace/projects/memcached-operator/bin/kustomize edit set image controller=docker.io/jberkhahn/banana:v3.0.0
/Users/jberkhahn/workspace/projects/memcached-operator/bin/kustomize build config/default | kubectl apply -f -
Error: accumulating resources: 2 errors occurred:
	* accumulateFile error: "accumulating resources from '../webhook': '/Users/jberkhahn/workspace/projects/memcached-operator/config/webhook' must resolve to a file"
	* accumulateDirector error: "recursed accumulation of path '/Users/jberkhahn/workspace/projects/memcached-operator/config/webhook': accumulating resources: 2 errors occurred:\n\t* accumulateFile error: \"accumulating resources from 'manifests.yaml': evalsymlink failure on '/Users/jberkhahn/workspace/projects/memcached-operator/config/webhook/manifests.yaml' : lstat /Users/jberkhahn/workspace/projects/memcached-operator/config/webhook/manifests.yaml: no such file or directory\"\n\t* loader.New error: \"error loading manifests.yaml with git: url lacks orgRepo: manifests.yaml, dir: evalsymlink failure on '/Users/jberkhahn/workspace/projects/memcached-operator/config/webhook/manifests.yaml' : lstat /Users/jberkhahn/workspace/projects/memcached-operator/config/webhook/manifests.yaml: no such file or directory, get: invalid source string: manifests.yaml\"\n\n"
```

After some investigating, I determined this issue was due to a line in the generated`config/webhook/kustomization.yaml ` that imports the file `config/webhook/manifests.yaml` as a resource, and that file doesn't exist. I was able to get my webhook working by commenting out the line importing it, so it doesn't seem to be strictly necessary. Once deployed, the conversion webhook seems to work fine. Are the docs omitting that I'm supposed to have to comment out that line? Is there a step I'm missing that is supposed to generate that file? 

### KubeBuilder (CLI) Version

3.1.0

### PROJECT version

3

### Plugin versions

```yaml
go.kubebuilder.io/v3
```

### Other versions

go 1.16.5

**Comment by camilamacedo86** [comment]
As we discussed in the bug triage meeting; 

- We need to understand why / when / how the manifest is used
- Then, if we reached out the consensus that is required only for some specific type of webhooks the best approach would be to fix the CLI to scaffold that accordingly. Following some options.  

a) Check if the project has none of the type Y which requires the files. Then, comment on the manifest after the scaffold when the flag N is used

Seems like not the best option because we are adding by default something that is not really required. 

b) Only scaffold the file and the line when the specific webhook type Y which requires that is used. 

IMPORTANT: Before we choose option a or b or any other one we really need to understand better how to works and see if that is really the best approach/ fix to get done here.

**Comment by camilamacedo86** [comment]
/remove-lifecycle stale

Any progress on this one?

**Comment by camilamacedo86** [comment]
I am moving this one from the milestone since we have no progress and we would like to a release sooner.

**Comment by vboulineau** [comment]
> As we discussed in the bug triage meeting;
> 
> * We need to understand why / when / how the manifest is used
> * Then, if we reached out the consensus that is required only for some specific type of webhooks the best approach would be to fix the CLI to scaffold that accordingly. Following some options.
> 
> a) Check if the project has none of the type Y which requires the files. Then, comment on the manifest after the scaffold when the flag N is used
> 
> Seems like not the best option because we are adding by default something that is not really required.
> 
> b) Only scaffold the file and the line when the specific webhook type Y which requires that is used.
> 
> IMPORTANT: Before we choose option a or b or any other one we really need to understand better how to works and see if that is really the best approach/ fix to get done here.

Hey @camilamacedo86,

Faced the same issue today when started implementing conversion webhook. I think there's not much to do. The generation of `config/webhook/manifests.yaml` is not necessary as the Webhook settings for conversion is specific and set only in the CRDs through the `config/crd/patches/webhook_in_foo.yaml`.
Also in `config/default/kustomization.yaml`, the `webhookcainjection_patch.yaml` piece is not required as there's no `Mutating|ValidatingWebhookConfiguration` generated.

I think a better documentation could be enough.

**Comment by DmitriGekhtman** [comment]
Docs would be great -- ran into this issue while attempting a hello world conversion example.

**Comment by DmitriGekhtman** [comment]
Just slightly tricky to figure out how to format the marker for conversion, but I can probably figure it out from https://book.kubebuilder.io/reference/markers/webhook.html

**Comment by DmitriGekhtman** [comment]
Ok, now I got the point, which I'm explaining to myself: You don't need markers for a converting webhook, because you don't need to generate MutatingWebhookConfiguration or AdmissionWebhookConfiguration objects for a converting webhook -- converting webhooks are configured _in the CRD_. For the same reason, you don't need config/webhooks/manifests.yaml which is means to contain webhook configuration objects.

**Comment by BradleyMcCallionCOT** [comment]
Why has this been closed? I've recently updated to the latest kubebuilder and still seeing this?
