### ISSUE TITLE
Scaffolding Makefile using controller-runtime v0.9.1

### ISSUE THREAD

**Issue by BostjanBozic** [kubernetes-sigs/kubebuilder#2235]
### What do you want to happen?

It would be great if we can adjust scaffolding to use `sigs.k8s.io/controller-runtime v0.9.1`.

With `v0.9.0` new way of setting up environment test has been done. Instead of using .sh script, go module is used now (https://github.com/kubernetes-sigs/controller-runtime/pull/1488). This means that `Makefile` scaffolding (test target) would have to be adjusted.

I am not sure if there is anything else in scaffolding though that would have to be changed with new controller-runtime version.

**Comment by varshaprasad96** [comment]
@BostjanBozic yes, the go/v3 plugin needs to be bumped to use latest version of controller runtime and 1.21 k8s dependencies. This is in progress, and would be done in #2208

**Comment by camilamacedo86** [comment]
it is done. thank you for raise that.
