### ISSUE TITLE
Line in book referencing kubebuilder annotation unclear

### ISSUE THREAD

**Issue by ChaosInTheCRD** [kubernetes-sigs/kubebuilder#2237]
Hi! I am in the process of reading the kubebuilder book and while I am enjoying it so far, there is a reference to the following kubebuilder annotation:

https://github.com/kubernetes-sigs/kubebuilder/blob/52a8c1272ed928c332dd714a70fdfd5d841591e3/docs/book/src/cronjob-tutorial/testdata/emptymain.go#L83

```
While we don't have anything to run just yet, remember where that
`+kubebuilder:scaffold:builder` comment is -- things'll get interesting there
soon.
```

While this became apparent once I had rest the entire page, for a little while I scoured the code above and below this line to make sense of the reference. A subtle change in this sentence could be to make it clear as to where this annotation is. Alternatively, could the annotation just be moved up in `emptymain.go` to make it fit in with the surrounding text?

**Comment by ChaosInTheCRD** [comment]
@camilamacedo86 would you like me to create a PR with a suggestion? More than happy to 😊

**Comment by yuswift** [comment]
> @camilamacedo86 would you like me to create a PR with a suggestion? More than happy to 😊

Any pr is welcomed. I guess @camilamacedo86  just missed the message.
