### ISSUE TITLE
Reference-style links in the book are wrongly parsed and does not contain the link itself

### ISSUE THREAD

**Issue by SeriyBg** [kubernetes-sigs/kubebuilder#2240]
### What broke? What's expected?

For the reference-style link in the markdown in the `mdbook` generated book the link is missing:

```
[Go modules blogpost][go-modules-blogpost]
...
[go-modules-blogpost]: https://blog.golang.org/using-go-modules
```
![image](https://user-images.githubusercontent.com/3988842/123770378-ec0def00-d8d2-11eb-9fe5-7ded122252a2.png)

### KubeBuilder (CLI) Version

3.1.0

### Extra Labels

/kind documentation

**Comment by JulienBreux** [comment]
Hello @SeriyBg 👋🏻 

Do you've the link of this page please?

Thanks, and have a good day :)

**Comment by rashmigottipati** [comment]
#2219 fixed the blog post link in documentation but the typo still exists in the website and needs to be fixed.

**Comment by camilamacedo86** [comment]
It is solved in the master and the fix will appear in the prod docs after the next release.
