### ISSUE TITLE
Artifacts documentation appears to be out of date

### ISSUE THREAD

**Issue by spkane** [kubernetes-sigs/kubebuilder#2244]
### What broke? What's expected?

The documentation at https://book.kubebuilder.io/reference/artifacts.html appears to be out of date.

I am unable to pull images from any of these:

```
docker pull go.kubebuilder.io/images/linux/amd64/v3.1.0
docker pull go.kubebuilder.io/images/linux/amd64/3.1.0
docker pull gcr.io/kubebuilder/thirdparty-linux-amd64:v3.1.0
docker pull gcr.io/kubebuilder/thirdparty-linux-amd64:3.1.0
```

I would expect these to work, based on the documentation.

### Reproducing this issue

Try to run any of these:

```
docker pull go.kubebuilder.io/images/linux/amd64/v3.1.0
docker pull go.kubebuilder.io/images/linux/amd64/3.1.0
docker pull gcr.io/kubebuilder/thirdparty-linux-amd64:v3.1.0
docker pull gcr.io/kubebuilder/thirdparty-linux-amd64:3.1.0
```

### KubeBuilder (CLI) Version

N/A

### PROJECT version

N/A

### Plugin versions

```yaml
N/A
```

### Other versions

 https://book.kubebuilder.io/reference/artifacts.html as of June 30, 2021.

### Extra Labels

/kind documentation

**Comment by yuswift** [comment]
This doc was updated in #2062. Please execute `docker pull gcr.io/kubebuilder/thirdparty-linux-amd64 -
a` and you will find that all the tags that are available. 
/cc @estroz 
I think this document needs a clearer explanation of the image usage.

**Comment by estroz** [comment]
`version` in the docs refers to Kubernetes version, not kubebuilder version. The following works:
```sh
docker pull gcr.io/kubebuilder/thirdparty-linux-amd64:1.21.2
```

**Comment by estroz** [comment]
I believe I closed this too soon, as the `Container Images` paragraph does not contain "Kubernetes version" even though the preceding paragraph does.
