### ISSUE TITLE
v3.1.0/install.sh : impossible to download "kubebuilder_3.1.0_linux_amd64.tar.gz"

### ISSUE THREAD

**Issue by yilas** [kubernetes-sigs/kubebuilder#2248]
### What broke? What's expected?

The installation with the script `install.sh` failed. The tarball `kubebuilder_3.1.0_linux_amd64.tar.gz` doesn't exist.

### Reproducing this issue

```
# bash  install.sh
/tmp/tmp.4hMLX5yKJd ~/virtualcluster/cluster-api-provider-nested/virtualcluster
Downloading kubebuilder_3.1.0\nfrom https://github.com/kubernetes-sigs/kubebuilder/releases/download/v3.1.0/kubebuilder_3.1.0_linux_amd64.tar.gz\n
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100     9  100     9    0     0     50      0 --:--:-- --:--:-- --:--:--    50

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
Downloaded executable files
ls: cannot access 'kubebuilder_3.1.0_linux_amd64/bin': No such file or directory
Moving files to /usr/local/kubebuilder folder\n
mv: cannot stat 'kubebuilder_3.1.0_linux_amd64': No such file or directory
Add kubebuilder to your path; e.g copy paste in your shell and/or edit your ~/.profile file
export PATH=$PATH:/usr/local/kubebuilder/bin
~/virtualcluster/cluster-api-provider-nested/virtualcluster

```

```
# wget https://github.com/kubernetes-sigs/kubebuilder/releases/download/v3.1.0/kubebuilder_3.1.0_linux_amd64.tar.gz
--2021-07-02 09:20:21--  https://github.com/kubernetes-sigs/kubebuilder/releases/download/v3.1.0/kubebuilder_3.1.0_linux_amd64.tar.gz
Resolving github.com (github.com)... 140.82.121.4
Connecting to github.com (github.com)|140.82.121.4|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2021-07-02 09:20:21 ERROR 404: Not Found.
```

### KubeBuilder (CLI) Version

kubebuilder is not installed

### PROJECT version

kubebuilder is not installed

### Plugin versions

```yaml
kubebuilder is not installed
```

### Other versions

```
# go version
go version go1.10.4 linux/amd64
```

**Comment by yuswift** [comment]
Hi, @yilas. I found that this script hasn't been updated for two years. There is an installation [document](https://book.kubebuilder.io/quick-start.html#installation), hope it is useful for you.

**Comment by maxsmythe** [comment]
@yuswift Unfortunately that installation document is insufficient.

I've been using Kubebuilder for a while and needed to do a fresh install. Previously the `tar.gz` file bundled other binaries, like etcd and the api server in. These files are critical dependencies for running the default generated controller tests. For example, if I create a controller and run `make test`, I get the following error:

```
  Unexpected error:
      <*fmt.wrapError | 0xc000130760>: {
          msg: "failed to start the controlplane. retried 5 times: fork/exec /usr/local/kubebuilder/bin/etcd: no such file or directory",
          err: {
              Op: "fork/exec",
              Path: "/usr/local/kubebuilder/bin/etcd",
              Err: 0x2,
          },
      }
      failed to start the controlplane. retried 5 times: fork/exec /usr/local/kubebuilder/bin/etcd: no such file or directory
  occurred
```

**Comment by yuswift** [comment]
> @yuswift Unfortunately that installation document is insufficient.
> 
> I've been using Kubebuilder for a while and needed to do a fresh install. Previously the `tar.gz` file bundled other binaries, like etcd and the api server in. These files are critical dependencies for running the default generated controller tests. For example, if I create a controller and run `make test`, I get the following error:
> 
> ```
>   Unexpected error:
>       <*fmt.wrapError | 0xc000130760>: {
>           msg: "failed to start the controlplane. retried 5 times: fork/exec /usr/local/kubebuilder/bin/etcd: no such file or directory",
>           err: {
>               Op: "fork/exec",
>               Path: "/usr/local/kubebuilder/bin/etcd",
>               Err: 0x2,
>           },
>       }
>       failed to start the controlplane. retried 5 times: fork/exec /usr/local/kubebuilder/bin/etcd: no such file or directory
>   occurred
> ```

I'm not sure if this [document](https://book.kubebuilder.io/cronjob-tutorial/writing-tests.html) is helpful to you. What happens if you run `go test ./...`? Do the tests still rely on etcd?

**Comment by maxsmythe** [comment]
Yep, the reliance on the barebones K8s infra (api server, etcd, etc.) being able to run locally comes from `envtest.Environment{}.Start()`, which is mentioned in the document you linked.

Here is an example of some Gatekeeper test code that results in starting up those binaries (generated by an older version of kubebuilder):

https://github.com/open-policy-agent/gatekeeper/blob/ecb280fbe4954319659cc49dd09fc50afab49c5c/pkg/controller/config/config_controller_suite_test.go#L42-L65

**Comment by maxsmythe** [comment]
I should also mention that I tried generating a new project using the most recent version of kubebuilder... the dependency was still there.

**Comment by camilamacedo86** [comment]
Hi @maxsmythe, 

The error https://github.com/kubernetes-sigs/kubebuilder/issues/2248#issuecomment-890677500 is faced because it is missing the binaries. You are not using the latest releases.

I'd suggest you follow the docs and download the latest version of the tool and then scaffold a project. You will see that this error will no longer be faced. 

You can fix it by following the step in the migration guide from v2 to v3 as well. See: https://book.kubebuilder.io/migration/manually_migration_guide_v2_v3.html#to-allow-automatic-downloads

Closing that as solved, However, feel free to ping if you think that it should be re-open.

**Comment by davidkarlsen** [comment]
> Hi @maxsmythe,
> 
> The error [#2248 (comment)](https://github.com/kubernetes-sigs/kubebuilder/issues/2248#issuecomment-890677500) is faced because it is missing the binaries. You are not using the latest releases.
> 
> I'd suggest you follow the docs and download the latest version of the tool and then scaffold a project. You will see that this error will no longer be faced.
> 
> You can fix it by following the step in the migration guide from v2 to v3 as well. See: [book.kubebuilder.io/migration/manually_migration_guide_v2_v3.html#to-allow-automatic-downloads](https://book.kubebuilder.io/migration/manually_migration_guide_v2_v3.html#to-allow-automatic-downloads)


That doc refers to `    test -f ${ENVTEST_ASSETS_DIR}/setup-envtest.sh || curl -sSLo ${ENVTEST_ASSETS_DIR}/setup-envtest.sh https://raw.githubusercontent.com/kubernetes-sigs/controller-runtime/v0.8.3/hack/setup-envtest.sh
`

but this script is not present for the latest release:
https://github.com/kubernetes-sigs/controller-runtime/tree/v0.9.6/hack

**Comment by kzap** [comment]
I am on a M1 Mac and the env-test binaries are not available in arm64 nor does the auto download tool account for this

I was able to manually download them by following the instructions [here](https://book.kubebuilder.io/reference/envtest.html) except for the first step I downloaded the `amd64` binaries.

```sh
export K8S_VERSION=1.22.1
curl -sSLo envtest-bins.tar.gz "https://go.kubebuilder.io/test-tools/${K8S_VERSION}/$(go env GOOS)/amd64"
```

after that, running `make test` worked

**Comment by yuswift** [comment]
> I am on a M1 Mac and the env-test binaries are not available in arm64 nor does the auto download tool account for this
> 
> I was able to manually download them by following the instructions [here](https://book.kubebuilder.io/reference/envtest.html) except for the first step I downloaded the `amd64` binaries.
> 
> ```shell
> export K8S_VERSION=1.22.1
> curl -sSLo envtest-bins.tar.gz "https://go.kubebuilder.io/test-tools/${K8S_VERSION}/$(go env GOOS)/amd64"
> ```
> 
> after that, running `make test` worked

This script has been removed. The instructions is the right way to install kubebuilder.

**Comment by guiguan** [comment]
I am on M1 as well. I have changed the following lines in `Makefile` to make it work

```makefile
.PHONY: test
test: manifests generate fmt vet envtest ## Run tests.
	KUBEBUILDER_ASSETS="$(shell $(ENVTEST) --arch amd64 --bin-dir $(PWD)/bin use $(ENVTEST_K8S_VERSION) -p path)" go test ./... -coverprofile cover.out
```
