### ISSUE TITLE
What is the purpose of global variables in main() in the example of the book?

### ISSUE THREAD

**Issue by vadimeisenbergibm** [kubernetes-sigs/kubebuilder#2252]
### What broke? What's expected?

Why global variables (and as a result of that, init() function) is used in main() in [the example](https://github.com/kubernetes-sigs/kubebuilder/blob/master/docs/book/src/cronjob-tutorial/testdata/project/main.go#L50) of [the book](https://book.kubebuilder.io/cronjob-tutorial/empty-main.html)?

Why these variables cannot be just local variables of main() and why initializing the scheme cannot be performed in main()?

Here are some opinions that global vars and init() functions should not be used in general:
https://peter.bourgon.org/blog/2017/06/09/theory-of-modern-go.html
https://leighmcculloch.com/posts/tool-go-check-no-globals-no-inits/

There are linters, ran by [golangci-lint](https://github.com/golangci/golangci-lint) check for global variables and init functions:
* [gochecknoglobals](https://github.com/leighmcculloch/gochecknoglobals)
* [gochecknoinits](https://github.com/leighmcculloch/gochecknoinits)

This is definitely not a bug, but it would help to at least explain in the book or in the code, why these are global variables. Or just move them into main() and avoid questions/linting errors.

### KubeBuilder (CLI) Version

master

**Comment by dharmjit** [comment]
Hi, Same question that @vadimeisenbergibm got. I recently unknowingly refactored(move init code to main) for one of the project I am working on and later found that this is scaffolded by `kubebuilder`. Is there some reasonings behind this? Thanks
