### ISSUE TITLE
Allow controllers to modify finalizers without modify permissions on parent

### ISSUE THREAD

**Issue by rainest** [kubernetes-sigs/kubebuilder#2264]
### What do you want to happen?

**Overview**

I'd like the documentation examples and template controller code to grant permissions to finalizer subresources directly, rather than relying on permissions to the parent. This would allow controllers with read-only permissions to resources to utilize finalizers still. I believe [this changeset](https://github.com/rainest/kubebuilder/commit/3b8a0c4399b74c1a1b21b15d6f97e7f861cd6951) should accomplish that, though am looking for input to see if there's something I've overlooked.

Not sure if it'd make sense to provide additional context as to why this adds permissions on top of the parent resource permissions--the additional finalizer sub-resource permissions are superfluous if you can already modify the parent, but documentation currently only has the single example.

**Background**

Currently, examples and template controller code grant several permissions to a resource and only grant the `update` permission on its finalizer sub-resources, e.g.

```
// +kubebuilder:rbac:groups=batch.tutorial.kubebuilder.io,resources=cronjobs,verbs=get;list;watch;create;update;patch;delete
// +kubebuilder:rbac:groups=batch.tutorial.kubebuilder.io,resources=cronjobs/finalizers,verbs=update
```
The finalizer `update` permission was originally added in https://github.com/kubernetes-sigs/kubebuilder/pull/1688 to address a separate issue.

If you wish to create a controller that only has read permissions to a resource, but can manipulate that resource's finalizers, you might try to remove permissions from the resource, e.g.

```
// +kubebuilder:rbac:groups=batch.tutorial.kubebuilder.io,resources=cronjobs,verbs=get;list;watch
// +kubebuilder:rbac:groups=batch.tutorial.kubebuilder.io,resources=cronjobs/finalizers,verbs=update
```
Afterwards, you'll find that your `Reconcile()` fails if it adds and removes finalizers. A call like `obj.SetFinalizers(append(finalizers, myFinalizer))` will result in errors like:

```
time="2021-07-09T01:19:57Z" level=error msg="Reconciler error" error="resource "resourceName" is forbidden: User "system:serviceaccount:namespace:whatever" cannot update resource "resources" in API group "" in the namespace "default"" logger=controller-runtime.manager.controller.resource name=resourceName namespace=default reconciler group= reconciler kind=Resource
```
We encountered this when limiting most of our controllers to read-only permissions, e.g. with [this set of permissions](https://github.com/Kong/kubernetes-ingress-controller/blob/2.0.0-alpha.2/railgun/controllers/configuration/zz_generated_controllers.go#L194-L196) on a resource where we [still used a finalizer](https://github.com/Kong/kubernetes-ingress-controller/blob/2.0.0-alpha.2/railgun/controllers/configuration/zz_generated_controllers.go#L213-L231).

My understanding of the underlying Kubernetes RBAC implementation is imperfect, but my intuition is that you need the additional permissions because finalizers are a list under the resource metadata (versus status, which is a single object and only requires `update`). While you'll be able to edit that list if you have modify permissions to the parent resource, you cannot modify finalizers with `update` alone if you lack modify permissions on the parent.

I was able to clear the forbidden permissions error by adding `create`. Based on the rest of the interface [exposed by controller-runtime](https://github.com/kubernetes-sigs/controller-runtime/blob/v0.9.2/pkg/controller/controllerutil/controllerutil.go#L351-L383) and the [Operator SDK examples](https://sdk.operatorframework.io/docs/building-operators/golang/advanced-topics/#handle-cleanup-on-deletion), I'm guessing the rest are necessary, though I haven't tested it fully (we actually removed finalizers from our controller for other reasons, so I didn't go further to confirm that the delete code needed `list` and `delete`).

### Extra Labels

/kind documentation

**Comment by camilamacedo86** [comment]
Hi @estroz, 

Since you are checking this one and it was discussed already in the triage meeting I am adding triage accepted regards its analyse and checks.

**Comment by camilamacedo86** [comment]
@rashmigottipati @varshaprasad96 @ryantking could someone get this one?
