### ISSUE TITLE
Could i requeue old object in reconcile, now seems only can requeue current object

### ISSUE THREAD

**Issue by ZhengJuCn** [kubernetes-sigs/kubebuilder#2267]
### What do you want to happen?

Could i requeue old object in reconcile, now seems only can requeue current object

i have do some dig with manager code, 

as i know queue is belong to controller, cannot access by reconcile

so now seems only can requeue current object, but not old object

any possible to requeue old object

**Comment by camilamacedo86** [comment]
Could you please let us know what do you mean by old objects? Could you please clarify your question by providing an example?

**Comment by ZhengJuCn** [comment]
@camilamacedo86 for example， current in reconcile i deal with obj A. with some state of A，i think i may need to deal obj B，which not change yet.

could i requeue obj B ?

**Comment by camilamacedo86** [comment]
Hi @ZhengJuCn,  

The idea is that you should ensure a desired state on the cluster. You can use the watch features to re-queue some objects always that the k8s api raises an event such as update/deletion/edition/creation. 

So, if you create a watch to observe the state of the B you will re-trigger the reconcile always by default when B be updated/deleted/edited/created. Is that the answer that you are looking for? See the PR: https://github.com/kubernetes-sigs/kubebuilder/pull/2000
