### ISSUE TITLE
Code generated by kubebuilder init doesn't match code in book

### ISSUE THREAD

**Issue by cgillum** [kubernetes-sigs/kubebuilder#2273]
### What broke? What's expected?

I'm running into compilation problems trying to follow along in the book. Specifically, the [Implementing a controller](https://book.kubebuilder.io/cronjob-tutorial/controller-implementation.html) chapter.

The problem seems to be that the code generated by `kubebuilder init` is different from the code in the book. A few examples:

* The kubebuilder command generates the `batchv1 "tutorial.kubebuilder.io/project/api/v1"` import, but the book shows a `batch "tutorial.kubebuilder.io/project/api/v1"` import in _controllers/cronjob_controller.go_ (`batch` vs. `batchv1`).
* The book shows getting a `log` object from the `CronJobReconciler` struct, but the generated code instead uses `_ := log.FromContext(ctx)`. It's unclear to me which way of assigning `log` is correct, or how to resolve this inconsistency.

There may be other issues, but I decided to stop here and file an issue once I realized that this might be a doc issue.

As someone relatively new to Go, it took me a while to figure out how to work around these inconsistencies. My expectation was that the code in the book would match the code generated by `kubebuilder init`, and that I could copy/paste the code into my project as I went along.

### Reproducing this issue

Follow the steps in [Tutorial: Building CronJob](https://book.kubebuilder.io/cronjob-tutorial/cronjob-tutorial.html).

See below for the versions of the tools that I'm using.

### KubeBuilder (CLI) Version

Version: main.version{KubeBuilderVersion:"3.1.0", KubernetesVendor:"1.19.2", GitCommit:"92e0349ca7334a0a8e5e499da4fb077eb524e94a", BuildDate:"2021-05-27T17:54:28Z", GoOs:"linux", GoArch:"amd64"}

### PROJECT version

3

### Plugin versions

```yaml
- go.kubebuilder.io/v3
```

### Other versions

* go version go1.15.7 linux/amd64
* sigs.k8s.io/controller-runtime v0.8.3
* (no controller-tools in `go.mod` file)

### Extra Labels

/kind documentation

**Comment by rashmigottipati** [comment]
I did notice these inconsistencies too when I was trying out steps in the book. @camilamacedo86 would the book documentation need these fixes or is there anything I am missing here?

**Comment by armsnyder** [comment]
I am also struggling a bit with the intended logging approach due to the inconsistencies. It looks like it needs to be updated with examples since #2181 was merged. @estroz fyi.

**Comment by MaxThom** [comment]
Ive' simply changed ```_ := log.FromContext(ctx)``` to ```log := log.FromContext(ctx)```

**Comment by camilamacedo86** [comment]
We need to update the code samples automatically by:
- running: https://github.com/kubernetes-sigs/kubebuilder/blob/master/docs/book/src/cronjob-tutorial/testdata/generate_cronjob.sh and https://github.com/kubernetes-sigs/kubebuilder/blob/master/docs/book/src/multiversion-tutorial/testdata/generate_multiversion.sh whcih will re-scaffold all based on the latest version
- Then we nee compare with master and ensure that we added all code/examples on top again. 

Note that the docs description might be outdated. After doing that we need to update the docs descriptions.

To share the info with @rashmigottipati @varshaprasad96 @estroz

**Comment by hickeyma** [comment]
I would be willing to give this a go. Is that ok or is someone else working on it?

**Comment by rashmigottipati** [comment]
@hickeyma Feel free to assign this to yourself and work on this.

**Comment by hickeyma** [comment]
Thanks @rashmigottipati 

/assign

**Comment by rashmigottipati** [comment]
@camilamacedo86 @hickeyma is working on this and has a WIP PR open. could you please add the label `triage/accepted` to this issue?
