### ISSUE TITLE
Bump the version of golangci-lint to v1.41.1

### ISSUE THREAD

**Issue by davidlanouette** [kubernetes-sigs/kubebuilder#2274]
### What do you want to happen?

The version of the linter is 2 minor versions old.  The currently used version (v1.39.1) is 2 minor versions old, and has a few bundled linters that are obsolete.

Done:
Running `make lint` or `make lint-fix` will use the latest version (as of commit time) of the linter.
Running `make golangci-lint` downloads the latest version of the linter.

### Extra Labels

/kind cleanup

**Comment by rashmigottipati** [comment]
There's a PR submitted for this issue, so can we add the label triage accepted for this? @camilamacedo86
