### ISSUE TITLE
Incorrect plurals generated following Quickstart

### ISSUE THREAD

**Issue by cg2p** [kubernetes-sigs/kubebuilder#2283]
### What broke? What's expected?

This is a re-occuring bug like [#1993](https://github.com/kubernetes-sigs/kubebuilder/issues/1993)

Out of the box, following the Quickstart, the plurals are generated incorrectly
```
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.4.1
  creationTimestamp: null
  name: helloworldren.hello.acme.com
spec:
  group: hello.acme.com
  names:
    kind: HelloWorld
    listKind: HelloWorldList
    plural: helloworldren
    singular: helloworld
```

So when you get to the `make install` step it runs and shows these errors - which you can see are related to expected plurals yaml of `hello.acme.com_helloworlds.yaml` when actually the generated yaml is `hello.acme.com_helloworldren.yaml`
```
Error: accumulating resources: 2 errors occurred:
	* accumulateFile error: "accumulating resources from 'bases/hello.acme.com_helloworlds.yaml': evalsymlink failure on '/Users/jeremycaine/code/github.com/hello-node-operator/config/crd/bases/hello.acme.com_helloworlds.yaml' : lstat /Users/jeremycaine/code/github.com/hello-node-operator/config/crd/bases/hello.acme.com_helloworlds.yaml: no such file or directory"
	* loader.New error: "error loading bases/hello.acme.com_helloworlds.yaml with git: url lacks host: bases/hello.acme.com_helloworlds.yaml, dir: evalsymlink failure on '/Users/jeremycaine/code/github.com/hello-node-operator/config/crd/bases/hello.acme.com_helloworlds.yaml' : lstat /Users/jeremycaine/code/github.com/hello-node-operator/config/crd/bases/hello.acme.com_helloworlds.yaml: no such file or directory, get: invalid source string: bases/hello.acme.com_helloworlds.yaml"
```

### Reproducing this issue

Following the Install and Quickstart [here](https://book.kubebuilder.io/quick-start.html)

In a clean working directory `hello-node-operator`
```
kubebuilder init --domain acme.com --repo acme.com/hello-node-operator
kubebuilder create api --group hello --version v1alpha1 --kind HelloWorld --resource --controller
make install
```

### KubeBuilder (CLI) Version

Version: main.version{KubeBuilderVersion:"3.1.0", KubernetesVendor:"1.19.2", GitCommit:"92e0349ca7334a0a8e5e499da4fb077eb524e94a", BuildDate:"2021-05-27T17:54:28Z", GoOs:"darwin", GoArch:"amd64"}

### PROJECT version

version: "3"

### Plugin versions

```yaml
- go.kubebuilder.io/v3
```

### Other versions

go version go1.16.6 darwin/amd64

go.mod
```
module acme.com/hello-node-operator

go 1.16

require (
	github.com/onsi/ginkgo v1.14.1
	github.com/onsi/gomega v1.10.2
	k8s.io/apimachinery v0.20.2
	k8s.io/client-go v0.20.2
	sigs.k8s.io/controller-runtime v0.8.3
)
```
kubectl
```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.3", GitCommit:"ca643a4d1f7bfe34773c74f79527be4afd95bf39", GitTreeState:"clean", BuildDate:"2021-07-15T20:58:09Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-05-21T23:01:33Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"linux/amd64"}
```

Using KinD
```
kubectl cluster-info
Kubernetes control plane is running at https://127.0.0.1:54252
CoreDNS is running at https://127.0.0.1:54252/api/v1/namespaces/kube-system/services/kube-dns:dns/proxy
```

**Comment by rashmigottipati** [comment]
@cg2p I was able to reproduce this issue as well. The generated yaml has the file name `hello.acme.com_helloworldren.yaml` when it is supposed to be `hello.acme.com_helloworlds.yaml` which is why `make install` fails as it's unable to find the yaml file `hello.acme.com_helloworlds.yaml`.

**Comment by camilamacedo86** [comment]
You are using `controller-gen.kubebuilder.io/version: v0.4.1` when the issue was solved in `controller-gen.kubebuilder.io/version: v0.5.0`

That seems solved on master: https://github.com/kubernetes-sigs/kubebuilder/blob/master/testdata/project-v3/config/crd/bases/crew.testproject.org_admirales.yaml#L7

Could you please try to check if the same issue is or is not reproducible with the master branch? If not, that would be solved for the next release.

**Comment by cg2p** [comment]
Yes I can check this - @camilamacedo86 how do I update my install to use `controller-gen.kubebuilder.io/version: v0.5.0`?

Just to confirm - in the [instructions](https://book.kubebuilder.io/quick-start.html) there is this step that I followed:
```
# download kubebuilder and install locally.
curl -L -o kubebuilder https://go.kubebuilder.io/dl/latest/$(go env GOOS)/$(go env GOARCH)
chmod +x kubebuilder && mv kubebuilder /usr/local/bin/
```
and that results in the config and versions as per my original bug post

**Comment by cg2p** [comment]
@camilamacedo86 I figured out the workaround. You need to edit the Makefile after running `kuberbuilder init...`

--
Build api
```
kubebuilder init --domain acme.com --repo acme.com/hello-node-operator
```

Edit the Makefile to workaround the plurarls [bug #2283](https://github.com/kubernetes-sigs/kubebuilder/issues/2283)
Change `v0.4.1` to `v0.5.0`
```
CONTROLLER_GEN = $(shell pwd)/bin/controller-gen
controller-gen: ## Download controller-gen locally if necessary.
	$(call go-get-tool,$(CONTROLLER_GEN),sigs.k8s.io/controller-tools/cmd/controller-gen@v0.5.0)
```

Install it
```
kubebuilder create api --group hello --version v1alpha1 --kind HelloWorld --resource --controller

kubectl cluster-info

make install
make run
```

In another shell, create an instance of the CRD
```
kubectl apply -f config/samples/
kubectl describe helloworld.hello.acme.com/helloworld-sample
```
