### ISSUE TITLE
could i use kubebuilder create webhook for subresource( x/status ), no docs found

### ISSUE THREAD

**Issue by ZhengJuCn** [kubernetes-sigs/kubebuilder#2291]
### What do you want to happen?

use kubebuilder create webhook for subresource( x/status )

i may want to mutating x/status subresource to match spec

or i may want to validate status

but i do not found any docs about this

**Comment by rashmigottipati** [comment]
@ZhengJuCn could you please provide an example of webhook for subresource? We would like to understand what you are trying to do.
