### ISSUE TITLE
"kubebuilder init" command changed go 1.15 in go mod becomes 1.16 

### ISSUE THREAD

**Issue by 011d** [kubernetes-sigs/kubebuilder#2292]
### What broke? What's expected?

"kubebuilder init" command changed go 1.15 in go mod becomes 1.16 . 
but,my env only 1.15

quick-start of official doc :
![image](https://user-images.githubusercontent.com/42208084/128991533-9d5a441f-6d0c-48ce-afa1-d85ba006867e.png)

go version go1.15.15 linux/amd64

before execute kubebuilder init, go.mod : 
```
module guestbook

go 1.15
```

after execute kubebuilder init, go.mod : 
```
module guestbook

go 1.16

require sigs.k8s.io/controller-runtime v0.8.3
```

kubebuilder init log:
```
Writing kustomize manifests for you to edit...
Writing scaffold for you to edit...
Get controller runtime:
$ go get sigs.k8s.io/controller-runtime@v0.8.3
Update dependencies:
$ go mod tidy
go mod tidy: go.mod file indicates go 1.16, but maximum supported version is 1.15
Error: failed to initialize project: unable to run post-scaffold tasks of "base.go.kubebuilder.io/v3": exit status 1
Usage:
  kubebuilder init [flags]

Examples:
  # Initialize a new project with your domain and name in copyright
  kubebuilder init --plugins go/v3 --domain example.org --owner "Your name"

  # Initialize a new project defining an specific project version
  kubebuilder init --plugins go/v3 --project-version 3


Flags:
      --component-config         create a versioned ComponentConfig file, may be 'true' or 'false'
      --domain string            domain for groups (default "my.domain")
      --fetch-deps               ensure dependencies are downloaded (default true)
  -h, --help                     help for init
      --license string           license to use to boilerplate, may be one of 'apache2', 'none' (default "apache2")
      --owner string             owner to add to the copyright
      --project-name string      name of this project
      --project-version string   project version (default "3")
      --repo string              name to use for go module (e.g., github.com/user/repo), defaults to the go package of the current working directory.
      --skip-go-version-check    if specified, skip checking the Go version

Global Flags:
      --plugins strings   plugin keys to be used for this subcommand execution

2021/08/11 15:28:31 failed to initialize project: unable to run post-scaffold tasks of "base.go.kubebuilder.io/v3": exit status 1
```

### Reproducing this issue

1. mkdir guestbook
2. cd guestbook/
3. go mod init guestbook
4. kubebuilder init

### KubeBuilder (CLI) Version

3.1.0

### Other versions

go version go1.15.15 linux/amd64

GOROOT=/usr/local/go
GO111MODULE=auto

**Comment by yuswift** [comment]
ref https://github.com/kubernetes-sigs/kubebuilder/pull/2257

**Comment by rashmigottipati** [comment]
@011d As you are on Kubebuilder version `3.1.0`, the go version needs to be `v1.16+`. Below are the updated prerequisites from the quickstart documentation:

<img width="500" alt="Screen Shot 2021-08-23 at 7 49 45 PM" src="https://user-images.githubusercontent.com/3925702/130533847-410e767d-a88e-42cc-ac69-5e498b9d0a97.png">

https://book.kubebuilder.io/quick-start.html

**Comment by rashmigottipati** [comment]
Closing this issue as we think it's been solved with the cherry-picked PR. Please feel free to re-open this issue if it still persists.
