### ISSUE TITLE
Exiting operator honoring deferred calls

### ISSUE THREAD

**Issue by kuritka** [kubernetes-sigs/kubebuilder#2293]
### What do you want to happen?

The operator `main` function does not allow calling the deferred function in case of an error. For example, I would like to add something like this to the `main` function:

```go
defer mymetrics.Unregister()
```
The preceding line will not be called if any error occurs, because all errors are handled in such way:

```go
if err != nil {
	setupLog.Error(err, "some message")
	os.Exit(1)
}
```

`os.Exit()` will exit the program immediately and the deferred functions will be ignored.

I'd like to prepare a PR that would terminate the program perhaps a little more elegantly.

Simplified, it would be to implement something like code below, [or more concrete diff here](https://github.com/k8gb-io/kubebuilder/commit/2bc02fb87a1d041d5486ac7ca6882c1a41340713):

```go
func main() {
    var exitCode = 1
    defer func() {
        os.Exit(exitCode)
    }()
      
    defer f2()
    defer f1()

    err := .....
    if err != nil {
       // executes all previous deferred statemets in order f1(), f2(), os.Exit(1)
       return
    }

    err = ....
    if err != nil {
       // executes all previous deferred statements in the order f1(), f2(), os.Exit(1)
       return
    }

    exitCode = 0
    // Everything went fine, 
    // executes all previous deferred statements in the order f1(), f2(), os.Exit(0)
}
``` 
 
 What do you all think?

Thanks!

**Comment by rashmigottipati** [comment]
@kuritka We are looking into this issue. We will respond to this soon. 

/cc @camilamacedo86 @rashmigottipati

**Comment by camilamacedo86** [comment]
Hi @kuritka, 

The program is exit `os.Exit()` because the issue faced does not allow continue. So, in these cases, the program should be executed. So, could please provide an example of action in the main that has been causing the manager panic/exit when should not?

**Comment by kuritka** [comment]
Hi @camilamacedo86,
Thank you for answer. `os.Exit()` fails fast, but does not allow me to exit the program properly. 


If I simplify it a lot, this is the situation I handle:
```go
func main() {
    // `defer`s will _not_ be run when using `os.Exit`, so
    // this `fmt.Println` will never be called.
    defer fmt.Println("free garbage, unregister......")
    // sometimes ones might use defer to do critical operations
    // like unregister, free memory
    // Exit with status code.
    os.Exit(1)
}
```

If I used `os.Exit()` , the deferred functions in `main` would not be called. In general it's a good practice to be able to free allocations using external libraries, terminate connections (in case you want them to be long-lived) or unregister from external services, etc... All garbage created in `main` must be cleared before `main` exits, no matter if it pass or fails. 



here is a concrete example where I register/unregister prometheus in the `main` function. In case something crashes, it is always calls Unregister().

```go
func main() {
	var exitCode = 1
	defer func() {
		os.Exit(exitCode)
	}()

         // initialize config, logger
	// ...

	mgr, err := ctrl.NewManager(ctrl.GetConfigOrDie(), ctrl.Options{
		Scheme:             runtimescheme,
		MetricsBindAddress: config.MetricsAddress,
		Port:               9443,
		LeaderElection:     false,
		LeaderElectionID:   "8020e9ff.absa.oss",
	})
	if err != nil {
		log.Err(err).Msg("unable to start manager")
		return
	}

	// registering componets.... 

	log.Info().Msg("starting metrics")
	m := metrics.Get(config)
	defer m.Unregister()  // <--- HERE: defer will be skipped when os.Exit()
	err = metrics.Register()
        // ....

	reconciler := &controllers.GslbReconciler{
		Config:      config,
		Client:      mgr.GetClient(),
		DepResolver: resolver,
                 Metrics: m,
		Scheme:      mgr.GetScheme(),
	}

        // ....

	if err = reconciler.SetupWithManager(mgr); err != nil { // HERE: if error occurs, deferred functions are skipped.
		log.Err(err).Msg("unable to create controller Gslb")
		return
	}
	// +kubebuilder:scaffold:builder
	if err := mgr.Start(ctrl.SetupSignalHandler()); err != nil { // HERE: if error occurs, deferred functions are skipped.
		log.Err(err).Msg("problem running manager")
		return
	}
	// time to call deferred functions including the exit one with code=0
	exitCode = 0
}

```

It's not critical, but it would be a pity to not to be able to terminate main func properly.

Thanks

**Comment by estroz** [comment]
Using `defer` in the same scope as `os.Exit()` is erroneous for sure, but like @camilamacedo86 says the default `main()` does not use `defer`. It would be fairly trivial for a user to change function scope if `defer` is needed, so this isn't a high priority change imo. However if someone wanted to work on this, I would accept this change:
```go
package main

func main() {
	if err := run(); err != nil {
		os.Exit(err)
	}
}

func run() error {

	// Current main() code with logs

	return nil
}
```
As this is a common pattern in Go programs.
