### ISSUE TITLE
Local Test Suite Environment not working on Apple M1 (arm64). Broken archive? 

### ISSUE THREAD

**Issue by afritzler** [kubernetes-sigs/kubebuilder#2295]
### What broke? What's expected?

Running `make test` on an Apple M1 results in 

```
fetching envtest tools@1.19.2 (into 'PATH_TO_MY_PROJECT/testbin')

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
make: *** [test] Error 2
```

Setting the GOARCH to amd64 in `testbin/setup-envtest.sh` results in fetching a valid archive

```
  goarch=amd64
```

It looks like the `tar.gz` of the local test environment is broken for arm64.

### Reproducing this issue

Run `make test` on an Apple M1.

### KubeBuilder (CLI) Version

3.1.0

### PROJECT version

3

### Plugin versions

```yaml
layout:
- go.kubebuilder.io/v3
```

### Other versions

go version go1.16.6 darwin/arm64

**Comment by m1schka** [comment]
:
```
fetching envtest tools@1.19.2 (into '/XXX/testbin')
tar: Error opening archive: Unrecognized archive format
```

when outputting what it tries to fetch, I get:
https://storage.googleapis.com/kubebuilder-tools/kubebuilder-tools-1.19.2-darwin-arm64.tar.gz

accessing that results in key not found. I assume no one build it for darwin-arm64 yet

**Comment by afritzler** [comment]
Yep, that is exactly what I did now.

**Comment by swartz-k** [comment]
Hello, any progress? If too busy, I would like to make a pr about this.

**Comment by camilamacedo86** [comment]
The ENV TEST was changed. So, we need to update the docs to clarifies that as add the new instructions.
See https://github.com/kubernetes-sigs/controller-runtime/tree/master/tools/setup-envtest#where-does-it-put-all-those-binaries.

See the task to track this need: https://github.com/kubernetes-sigs/kubebuilder/issues/2389

Also, please see the info added in the PR to the master:

https://github.com/kubernetes-sigs/kubebuilder/pull/2386/files#diff-85357511e8db1dbd5aa2ea424027ee512ea9a395629f61c1e8bb111320bfedc6R42-R49)

It will be published in the prod docs soon. (for the next release)

Closing this one as a duplicate.
