### ISSUE TITLE
🐛 go.kubebuilder.io has broken for downloading kubebuilder releases

### ISSUE THREAD

**Issue by FillZpp** [kubernetes-sigs/kubebuilder#2311]
### What broke? What's expected?

Failed to download kubebuilder releases, including:

```
https://go.kubebuilder.io/dl/2.3.1/linux/amd64
https://go.kubebuilder.io/dl/3.1.0/linux/amd64
```

But `master` is fine:

```
https://go.kubebuilder.io/dl/master/linux/amd64
```

### Reproducing this issue

`curl -L https://go.kubebuilder.io/dl/3.1.0/linux/amd64`

### KubeBuilder (CLI) Version

nil

**Comment by mugli** [comment]
Experiencing the same with `https://go.kubebuilder.io/dl/2.3.2/linux/amd64` too.

**Comment by AzureMarker** [comment]
Here's a short-term (or long-term?) fix from the linked PRs: Change the URL you use to
`https://github.com/kubernetes-sigs/kubebuilder/releases/download/v${version}/kubebuilder_${version}_${os}_${arch}.tar.gz`

**Comment by poadhika** [comment]
Experiencing the same with https://go.kubebuilder.io/dl/3.1.0/linux/amd64 too. The proposed short term fix works for version 2.3.1 but not for 3.1.0. Please advise.

**Comment by AzureMarker** [comment]
@poadhika it looks like they just removed the version from the filename: https://github.com/kubernetes-sigs/kubebuilder/releases/tag/v3.1.0

**Comment by rashmigottipati** [comment]
cc @rashmigottipati @camilamacedo86

**Comment by poadhika** [comment]
> @poadhika it looks like they just removed the version from the filename: https://github.com/kubernetes-sigs/kubebuilder/releases/tag/v3.1.0

Yes removing the version solved my issue.

**Comment by camilamacedo86** [comment]
HI folks, 

The assets are available in the release page: https://github.com/kubernetes-sigs/kubebuilder/releases

https://github.com/kubernetes-sigs/kubebuilder/releases/download/v3.1.0/kubebuilder_linux_amd64

And you can curl this links. So, I do not understand why your trying to use:

https://go.kubebuilder.io/dl/2.3.1/linux/amd64
https://go.kubebuilder.io/dl/3.1.0/linux/amd64

Where did you check that links should be used?

**Comment by AzureMarker** [comment]
@camilamacedo86 The go.kubebuilder.io links are from the documentation: https://book.kubebuilder.io/quick-start.html#installation

**Comment by camilamacedo86** [comment]
Could you please help us out by pushing a PR for we update it asap? 
We should use the links in https://github.com/kubernetes-sigs/kubebuilder/releases/ e.g: https://github.com/kubernetes-sigs/kubebuilder/releases/download/v3.1.0/kubebuilder_linux_amd64 .

**Comment by fspaniol** [comment]
Hi @camilamacedo86 , I've opened. https://github.com/kubernetes-sigs/kubebuilder/pull/2320, although I'm not sure it the change is good, any proposals would be welcome :)

**Comment by jmrodri** [comment]
So https://go.kubebuilder.io/dl is a redirect to https://github.com/kubernetes-sigs/kubebuilder/releases

Here's the path:
https://wheregoes.com/trace/20219211407/

**Comment by jmrodri** [comment]
The release artifacts changed.
