### ISSUE TITLE
Create testdata/sample for the declarative plugin (go/v3 only)

### ISSUE THREAD

**Issue by camilamacedo86** [kubernetes-sigs/kubebuilder#2324]
### What do you want to happen?

I'd like to see in the testdata samples for the optional plugins. 
After we remove the declarative one here https://github.com/kubernetes-sigs/kubebuilder/pull/2319/files we have no longer this option. 

However, we cannot add a lot of samples. So, my suggestion here would be for now we add :
testdata/project-v3-declarative only.

**Comment by camilamacedo86** [comment]
c/c @justinsb

**Comment by rashmigottipati** [comment]
@justinsb are you planning to work on this issue?

**Comment by sunny-b** [comment]
@camilamacedo86 Is this still needed? It looks like there is already a [v3 sample project that has the declarative pattern](https://github.com/kubernetes-sigs/kubebuilder/blob/master/test/testdata/generate.sh#L131)

**Comment by camilamacedo86** [comment]
It is done: https://github.com/kubernetes-sigs/kubebuilder/tree/master/testdata/project-v3-addon

Thank you 👍
