### ISSUE TITLE
scheme marker in suite_test.go generates duplicate code

### ISSUE THREAD

**Issue by armsnyder** [kubernetes-sigs/kubebuilder#2326]
### Expected

The `//+kubebuilder:scaffold:scheme` marker that kubebuilder includes in the scaffolded `controllers/suite_test.go` file should only generate new code when there is a new scheme to add. This is how the marker behaves in main.go.

### Actual

Every time you run `kubebuilder create api` to add a new CRD to an existing API group, the marker adds the same code block, and you end up with a lot of unnecessary duplicate code, like:

```go
err = myappv1.AddToScheme(scheme.Scheme)
Expect(err).NotTo(HaveOccurred())

err = myappv1.AddToScheme(scheme.Scheme)
Expect(err).NotTo(HaveOccurred())

//+kubebuilder:scaffold:scheme
```

### Reproducing this issue

```shell
mkdir kubebuilder-test
cd kubebuilder-test
go mod init myapp.example.com
kubebuilder init --domain example.com
kubebuilder create api --version=v1 --resource --controller --group=myapp --kind Foo
kubebuilder create api --version=v1 --resource --controller --group=myapp --kind Bar
cat controllers/suite_test.go
```

### KubeBuilder (CLI) Version

Version: main.version{KubeBuilderVersion:"3.1.0", KubernetesVendor:"unknown", GitCommit:"92e0349ca7334a0a8e5e499da4fb077eb524e94a", BuildDate:"2021-05-29T05:57:53+01:00", GoOs:"darwin", GoArch:"amd64"}

### PROJECT version

version: "3"

### Plugin versions

```yaml
layout:
- go.kubebuilder.io/v3
```

**Comment by manu12miskin** [comment]
Hey @armsnyder, I would like to work on this issue. Can you please assign it to me?

**Comment by armsnyder** [comment]
The problem appears to be this function.

https://github.com/kubernetes-sigs/kubebuilder/blob/1ed4de20ac328ee151888597f067e4ae7dad97a4/pkg/machinery/scaffold.go#L357-L358

**Comment by armsnyder** [comment]
@manu12miskin I'm also interested in trying to fix this myself. I hope it's ok if I open a PR if I find a fix. Let me know if you're already far along with it.

**Comment by manu12miskin** [comment]
@armsnyder Sure, I am unassigning myself.
