### ISSUE TITLE
Configuring EnvTest documentation suggets non-working binary installation directory.

### ISSUE THREAD

**Issue by Birdrock** [kubernetes-sigs/kubebuilder#2331]
### What broke? What's expected?

On [Configuring EnvTest](https://book.kubebuilder.io/reference/envtest.html#installation), the documentation for installation specifies creating the directory `/opt/kubebuilder/testbin` and extracting the envtest binaries to that directory. It then suggests that the `test` target can be changed to (omitting prerequisites/dependencies) `go test ./... -coverprofile cover.out`. When the `test` target is run, the following error occurs:
```
 Unexpected error:
      <*fmt.wrapError | 0xc00048f500>: {
          msg: "failed to start the controlplane. retried 5 times: fork/exec /usr/local/kubebuilder/bin/etcd: no such file or directory",
          err: {
              Op: "fork/exec",
              Path: "/usr/local/kubebuilder/bin/etcd",
              Err: 0x2,
          },
      }
      failed to start the controlplane. retried 5 times: fork/exec /usr/local/kubebuilder/bin/etcd: no such file or directory
  occurred
```
The instructions place the binaries in a location that is not the expected default for `controller-runtime`. For a working installation, without providing a `KUBEBUILDER_ASSETS` environment variable, the target directory for the extraction should be `/usr/local/kubebuilder`.

### KubeBuilder (CLI) Version

3.1.0

### PROJECT version

3

### Plugin versions

```yaml
layout:
- go.kubebuilder.io/v3
```

### Other versions

Go version: go version go1.16.4 linux/amd64

controller-runtime: sigs.k8s.io/controller-runtime v0.8.3

controller-gen: sigs.k8s.io/controller-tools/cmd/controller-gen@v0.6.1

kubectl version:
```
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.1", GitCommit:"632ed300f2c34f6d6d15ca4cef3d3c7073412212", GitTreeState:"clean", BuildDate:"2021-08-19T15:45:37Z", GoVersion:"go1.16.7", Compiler:"gc", Platform:"linux/amd64"}
```

Not interacting with a Kubernetes cluster for this.

### Extra Labels

/kind documentation

**Comment by camilamacedo86** [comment]
The ENV TEST was changed. So, we need to update the docs to clarifies that as add the new instructions.
See https://github.com/kubernetes-sigs/controller-runtime/tree/master/tools/setup-envtest#where-does-it-put-all-those-binaries.

I task to track this need was tracked: https://github.com/kubernetes-sigs/kubebuilder/issues/2389

Closing that as duplicated.
