### ISSUE TITLE
Tutorial Section 1.2 Missing Colon

### ISSUE THREAD

**Issue by marshmallory** [kubernetes-sigs/kubebuilder#2337]
https://book.kubebuilder.io/cronjob-tutorial/empty-main.html

`    mgr, err = ctrl.NewManager(ctrl.GetConfigOrDie(), ctrl.Options{
        Scheme:                 scheme,
        Namespace:              namespace,
        MetricsBindAddress:     metricsAddr,
        Port:                   9443,
        HealthProbeBindAddress: probeAddr,
        LeaderElection:         enableLeaderElection,
        LeaderElectionID:       "80807133.tutorial.kubebuilder.io",
    })`

The colon after err is missing.

This is my first time working in this space. Happy to submit a PR if the documentation is managed.

**Comment by stevemcquaid** [comment]
#2358 & #2359 fixed this
/close
