### ISSUE TITLE
Outdated build from master

### ISSUE THREAD

**Issue by Tarick** [kubernetes-sigs/kubebuilder#2348]
### What broke? What's expected?

Binary downloaded from https://go.kubebuilder.io/releases/master/linux/amd64 for Linux is way older than the last released version and commits in master.

```
Version: main.version{KubeBuilderVersion:"v0.0.0-SNAPSHOT-c82530b", KubernetesVendor:"1.19.2", GitCommit:"c82530b1d30e9713adbd34241dd2549b317ea421", BuildDate:"2021-02-11T20:39:56Z", GoOs:"linux", GoArch:"amd64"}
```
If builds from master are not supported, I'd suggest removing the possibility to download them from the documentation.

### KubeBuilder (CLI) Version

Version: main.version{KubeBuilderVersion:"v0.0.0-SNAPSHOT-c82530b", KubernetesVendor:"1.19.2", GitCommit:"c82530b1d30e9713adbd34241dd2549b317ea421", BuildDate:"2021-02-11T20:39:56Z", GoOs:"linux", GoArch:"amd64"}

**Comment by camilamacedo86** [comment]
It seems that you need to update your local/fork master branch. You need to get the latest changes made into the repository. Then, run make install.
