### ISSUE TITLE
Include base.go.kubebuilder.io plugin

### ISSUE THREAD

**Issue by armsnyder** [kubernetes-sigs/kubebuilder#2349]
### What do you want to happen?

On my team we bundle our operator config using Helm instead of Kustomize. It would be useful if we could use kubebuilder for golang code generation only.

However, the `go.kubebuilder.io` plugin in the `kustomize` CLI extends the `kustomize.common.kubebuilder.io` plugin, so it generates config that we do not need.

Can we get the `base.go.kubebuilder.io` plugin into the `kustomize` CLI please?

**Comment by camilamacedo86** [comment]
Hi @armsnyder, 

Not sure if I could understand your motivations. In this way, I'd like to share:

a) The KB can be used as lib. You do not need to use the CLI to generate a base for your projects. One example of its usage is the SDK project (https://github.com/operator-framework/operator-sdk)
b) Also, would like to recommend you to check : https://book.kubebuilder.io/plugins/plugins.html

**Comment by armsnyder** [comment]
Hi @camilamacedo86 ! Thanks for taking time to understand the use case. I read the plugin docs and my understanding is that Kubebuilder can be used as a library for building your own custom CLI, and that there are planned changes in Kubebuilder "plugin phase 3" which will allow external plugins without needing to build a custom CLI. Is that correct?

To be clear, this issue was about having the option to run kubebuilder without the kustomize scaffolding. Our team's workaround was to add a step in our project's Makefile that would delete the config directory. I see adding Helm scaffolding as a separate issue, since in the meantime my team is happy to maintain the Helm chart on our own.
