### ISSUE TITLE
Make targets should be PHONY or point to the files they create

### ISSUE THREAD

**Issue by JustinKuli** [kubernetes-sigs/kubebuilder#2377]
### What do you want to happen?

Many targets in the [Makefile](https://github.com/kubernetes-sigs/kubebuilder/blob/master/pkg/plugins/golang/v3/scaffolds/internal/templates/makefile.go) do not create files, but aren't labelled as [PHONY targets](https://www.gnu.org/software/make/manual/make.html#Phony-Targets). This is probably a "best practice" that some users want in their Makefile, for example: https://github.com/gatekeeper/gatekeeper-operator/pull/25.

Similarly, the way some of the tools (ie `kustomize`) are downloaded using the `go-get-tool` function could be using built-in make capabilities if the targets were named correctly for the files they fetch. Again, see the example in https://github.com/gatekeeper/gatekeeper-operator/pull/25 for a possible approach.

**Comment by camilamacedo86** [comment]
Hi @JustinKuli, 

Thank you for track your idea. +1 for that. 
WDYT about pushing a PR with? 

The change would not be addressed in the bollerplate of go/v3 : https://github.com/kubernetes-sigs/kubebuilder/blob/master/pkg/plugins/golang/v3/scaffolds/internal/templates/makefile.go also it seems fine to be added in the previous version as well see: https://github.com/kubernetes-sigs/kubebuilder/blob/master/pkg/plugins/golang/v2/scaffolds/internal/templates/makefile.go
