### ISSUE TITLE
Introducing ENV instead of flags for operator's `main.go` skeleton manifest

### ISSUE THREAD

**Issue by AlmogBaku** [kubernetes-sigs/kubebuilder#2388]
### What do you want to happen?

Configuring operators with Environment Variables instead of `flags` is considered as best practice, especially due to the limitation to provide dynamic configurations over the flags (i.e. Secrets, ConfigMaps, etc.)

Using flags can allow easier extensibility of the scaffold `main.go`, and compatibility with the [12factor](https://12factor.net/) manifest.

In addition, I highly recommend the usage of [`caarl0s/env`](https://github.com/caarlos0/env) repository for simplicity or

**Comment by coderanger** [comment]
I think you are overstating it env vars are a best practice. 12factor was an important step in the ops journey for many but it is neither dogma nor overall applicable in a modern setting. I think the more important "best practice" is consistency with all other Kubernetes daemons which use CLI flags rather than env vars. That said, if wanted to introduce Viper to the default skeleton to support both transparently, maybe that would be nice?

**Comment by camilamacedo86** [comment]
+ 1 for the @coderanger POV and suggestion.
@AlmogBaku, please feel free to contribute with PRs.

Your help is more than welcome.

**Comment by jeesmon** [comment]
Isn’t `ComponentConfig` the approach to solve this problem?

https://book.kubebuilder.io/component-config-tutorial/tutorial.html

https://docs.google.com/document/d/1FdaEJUEh091qf5B98HM6_8MS764iXrxxigNIdwHYW9c/edit#heading=h.yrvizvdexvtq

**Comment by AlmogBaku** [comment]
Hey,
Since this is a design feature, let's try to agree upon the design before I'll jump to implementation.

I see that the `ComponentConfig` was contributed by @pwittrock, are you available on Slack for a brief chat?

**Comment by AlmogBaku** [comment]
@k8s-ci-robot /remove-lifecycle stale

**Comment by AlmogBaku** [comment]
@k8s-ci-robot /remove-lifecycle stale

**Comment by AlmogBaku** [comment]
@camilamacedo86 should we add it to go/v4 or also for go/v3?

**Comment by AlmogBaku** [comment]
note: make sure viper can handle one dash arguments as go flags (to support backward compatibility)
