### ISSUE TITLE
EnvTest setup docs need to be updated

### ISSUE THREAD

**Issue by camilamacedo86** [kubernetes-sigs/kubebuilder#2389]
### What do you want to happen?

The ENV TEST was changed. So, we need to update the docs to clarifies that as add the new instructions.
See: https://github.com/kubernetes-sigs/controller-runtime/tree/master/tools/setup-envtest#where-does-it-put-all-those-binaries

Then, would be very nice instead of removing the current instructions make it clear when it loses its supports. 
 
Also, note that we probably have related steps in the migration guide from v2 to v3 which seems that needs to be revisited. 

### Extra Labels

/kind documentation

**Comment by camilamacedo86** [comment]
c/c @varshaprasad96

**Comment by afritzler** [comment]
Running `make test` on the kubebuilder project itself on my Apple M1 (darwin/arm64) results in this: 

```
Running kubebuilder integration tests
Building kubebuilder
Installing e2e tools with setup-envtest
unable to fetch checksum for requested version: unable fetch metadata for kubebuilder-tools-1.23.1-darwin-arm64.tar.gz -- got status "404 Not Found" from GCS
make: *** [test-integration] Error 2
```

Is there any progress on the darwin/arm64 for the kubebuilder-tools? I couldn't find any issue on that. I could of course locally hack it and force envtest to use amd64 instead but that is a rather nasty solution.

**Comment by camilamacedo86** [comment]
We have now for 1.23.5 and the latest release see: https://storage.googleapis.com/kubebuilder-tools
 However, note that we cannot fully support arm 64 for mac yet. More info can be found on the release page for 3.4.0. 
So, I am closing this one.

**Comment by rumstead** [comment]
Can I suggest that we download the envtest tools to [a relative dir](https://github.com/kubernetes-sigs/controller-runtime/blob/bcde6f084dd15ef93bee2a2e4668184e7472eddd/tools/setup-envtest/main.go#L50)? It's clear and obvious where the binaries are downloaded and would get automatically cleaned up if run in a CI pipeline. 

```Makefile
.PHONY: test
test: manifests generate fmt vet envtest ## Run tests.
	KUBEBUILDER_ASSETS="$(shell $(ENVTEST) use $(ENVTEST_K8S_VERSION) --bin-dir $(LOCALBIN) -p path)" go test ./... -coverprofile cover.out
```

Happy to contribute if there is agreement.

**Comment by camilamacedo86** [comment]
Hi @rumstead,

Thank you for looking to contribute, see that it is done already ( you have an old scaffold version ): 

https://github.com/kubernetes-sigs/kubebuilder/blob/f2e7a0e214ab4f2bd21b4c3f2ef32eb6f4391445/testdata/project-v4/Makefile#L129-L132

**Comment by rumstead** [comment]
@camilamacedo86 Sorry my comment was unclear. I am actually talking about this line which downloads the k8s binaries to use for the integration tests:

https://github.com/kubernetes-sigs/kubebuilder/blob/f2e7a0e214ab4f2bd21b4c3f2ef32eb6f4391445/testdata/project-v4/Makefile#L59

I am using the project-v3 scaffolding which also has that for `envtest`.

**Comment by camilamacedo86** [comment]
sorry for my mistake. In the past, we need to add the KUBEBUILDER_ASSETS in a specific location. We need to check how it is implemented now in controller runtime and if we can have the KUBEBUILDER_ASSETS in any place. Anyway, please feel free to check it out and open PR with our prosal solution. Then we can discuss that easily.
