### ISSUE TITLE
Writing controllers without generating api

### ISSUE THREAD

**Issue by swiftslee** [kubernetes-sigs/kubebuilder#2398]
### What do you want to happen?

Sometimes the users don't need to create an API for themselves(e.g. implementing a loadbalancer svc provider only needs to watch kubernetes native service), how to do that? Any suggestions would be appreciated!

**Comment by camilamacedo86** [comment]
Hi @swiftslee, 
 
Have you any position about this one? 
Are you working on this/ If not could you please remove the assign for another person be able to contribute with?

**Comment by Nivedita-coder** [comment]
Hi @camilamacedo86 @swiftslee, is this issue open can I work on this? :slightly_smiling_face:

**Comment by AshwinRamachandran2002** [comment]
Hi, I found this issue interesting. @Nivedita-coder could I work along with you on this PR?

**Comment by swiftslee** [comment]
> Hi @swiftslee,
> 
> Have you any position about this one? Are you working on this one? If not that is OK. However, could you please remove the assignment for another person to be able to contribute?

Sorry for the miss. <br> I don't have much time recently. Let's assign it to @AshwinRamachandran2002.
/unassign
/assign @AshwinRamachandran2002

**Comment by Sajiyah-Salat** [comment]
Hey @AshwinRamachandran2002 are you working on this ?

**Comment by ashutosh887** [comment]
I would like to work on this
/assign

**Comment by Sajiyah-Salat** [comment]
hello, @camilamacedo86 I have understood the issue. If this issue is still valid I would like to work on this.

**Comment by ashutosh887** [comment]
I worked on this a bit but a bit confused @camilamacedo86 

Do you mean we need to extend the content in **resources.path** and update the mentioned **here** part with another link/url.

**Comment by camilamacedo86** [comment]
This one is about document the explanation give in https://github.com/kubernetes-sigs/kubebuilder/issues/2398#issuecomment-952709317

See that we have the issue and a PR that we need to finish which cover it already, see: https://github.com/kubernetes-sigs/kubebuilder/issues/3210

Also, please feel free to contribute for we finish the open pr (address the comments so we can get that merged) And if you see any other point where we are missing to doc please feel free to open prs to provide suggestions for we improve the documentation. 

In this way, I am closing this one in favor of https://github.com/kubernetes-sigs/kubebuilder/issues/3210
