### ISSUE TITLE
V2: Implement Predicates

### ISSUE THREAD

**Issue by pwittrock** [kubernetes-sigs/kubebuilder#240]
**Note**: Use the kubernetes-sigs/controller-platform repo

Port over the Predicates from [predicates](https://github.com/kubernetes-sigs/kubebuilder/tree/master/pkg/controller/predicates) to the [new predicate package](https://github.com/kubernetes-sigs/kubebuilder/tree/controller-platform/pkg/ctrl/predicate).

- [ ] Implement Predicates
- [ ] Implement unit tests
- [ ] Implement integration tests in `controller_integration_test.go`

**Comment by pwittrock** [comment]
@lichuqiang Would you be interested in looking at various controllers from kubernetes and the example and coming up with a list of collection of standard Predicates?

**Comment by lichuqiang** [comment]
sure :)
