### ISSUE TITLE
Automatically build from for kube-rbac-proxy

### ISSUE THREAD

**Issue by camilamacedo86** [kubernetes-sigs/kubebuilder#2414]
### What do you want to happen?

Currently, these builds have been done manually and added to the google cloud via Solly.
This project is a process to be donated to k8s org. Seems that if the project be donated we could automatically generate the builds. 

So, the goal of this task is to check how we can do that and if we can help.

**Comment by estroz** [comment]
The build itself is performed automatically by cloudbuild (just change [this version](https://github.com/kubernetes-sigs/kubebuilder/blob/kube-rbac-proxy-releases/build/cloudbuild_kube-rbac-proxy.yaml#L17)). We are still working out access to the cloudbuild account, but that's an admin issue.
