### ISSUE TITLE
failed to initialize project: unable to run pre-scaffold tasks of "base.go.kubebuilder.io/v3": open config: permission denied

### ISSUE THREAD

**Issue by MaxThom** [kubernetes-sigs/kubebuilder#2416]
### What broke? What's expected?

Hi,

im trying to run the quickstart guestbook app or the cronjob app, and I got this error when running `kubebuilder init`:

`failed to initialize project: unable to run pre-scaffold tasks of "base.go.kubebuilder.io/v3": open config: permission denied`.

I tried those commands:
 - `kubebuilder init`
 - `kubebuilder init --domain my.domain --repo my.domain/guestbook`
 - `go mod init example.com/guestbook` && `kubebuilder init --domain my.domain`.

### KubeBuilder (CLI) Version

Version: main.version{KubeBuilderVersion:"3.2.0", KubernetesVendor:"1.22.1", GitCommit:"b7a730c84495122a14a0faff95e9e9615fffbfc5", BuildDate:"2021-10-29T18:32:16Z", GoOs:"linux", GoArch:"amd64"}

### Other versions

- go version: go1.17.2 linux/amd64
- kubectl version: 1.22
- k8s version: v1.21.5-k3s2
- docker version: 20.10.10

**Comment by camilamacedo86** [comment]
It shows like the tool has no permission to write in the directory where you are trying to scaffold the project.

**Comment by MaxThom** [comment]
Thanks you, restarting my pc solved the issue. Thats wierd I dont know lol. Anyway, ty :)
