### ISSUE TITLE
How to generate config/certmanager/kustomization.yaml and kustomizeconfig.yaml

### ISSUE THREAD

**Issue by safejob** [kubernetes-sigs/kubebuilder#2419]
Version: main.version{KubeBuilderVersion:"3.2.0", KubernetesVendor:"1.22.1", GitCommit:"b7a730c84495122a14a0faff95e9e9615fffbfc5", BuildDate:"2021-10-29T18:32:16Z", GoOs:"linux", GoArch:"amd64"}

I follow the book about cronjob steps, all run well , but could not generate config/certmanager/kustomization.yaml and kustomizeconfig.yaml . Can you tell me where is wrong?

-------------------------------------------
# make deploy IMG=localhost:5000/controller:latest
/mnt/d/golang-mod/kubebuilder/cronjob/bin/controller-gen rbac:roleName=manager-role crd webhook paths="./..." output:crd:artifacts:config=config/crd/bases
cd config/manager && /mnt/d/golang-mod/kubebuilder/cronjob/bin/kustomize edit set image controller=localhost:5000/ontroller:latest
/mnt/d/golang-mod/kubebuilder/cronjob/bin/kustomize build config/default | kubectl apply -f -
Error: accumulating resources: 2 errors occurred:
        * accumulateFile error: "accumulating resources from '../certmanager': '/mnt/d/golang-mod/kubebuilder/cronjob/config/certmanager' must resolve to a file"
        * accumulateDirector error: "couldn't make target for path '/mnt/d/golang-mod/kubebuilder/cronjob/config/certmanager': unable to find one of 'kustomization.yaml', 'kustomization.yml' or 'Kustomization' in directory '/mnt/d/golang-mod/kubebuilder/cronjob/config/certmanager'"

error: no objects passed to apply
make: *** [Makefile:97: deploy] Error 1

**Comment by jmrodri** [comment]
/cc @camilamacedo86 
label: triage support

**Comment by camilamacedo86** [comment]
It shows that your project has some customizations that is causing the issue with kustomize.
See: https://stackoverflow.com/questions/60298445/kubernetes-kustomize-command-giving-error-when-we-specify-base-manifest-files-in

It does not seem to be related to the KB project itself then, I hope that you do not mind we close this one.
Hoewver, please feel free to ask for help if you need in the kubebuilder channel as well.
