### ISSUE TITLE
Exit Controller on certain Errors

### ISSUE THREAD

**Issue by barney-s** [kubernetes-sigs/kubebuilder#242]
Using a script to create a ClusterRoleBinding and controller Deployment.

For some reason, the ClusterRoleBinding is not being applied or a race condition exists when the controller starts. As a result when the controller is starting, it throws an error registering informers for the CustomResources. But since the controller process did not exit, the controller pod was not restarted and ended up being non-functional (the main loop was not started).

A manual restart of the controller-pod fixed the issue.

Shouldn't we exit on such errors so that the controller pod could be restated by k8s resolving external dependancies ?

2018/05/31 16:58:20 Provide Controller for Something
E0531 16:58:21.928445       1 reflector.go:205] k8s.io/some-operator/vendor/github.com/kubernetes-sigs/kubebuilder/pkg/controller/informers/informersindex.go:65: Failed to list *v1alpha1.SomeResource: the server could not find the requested resource (get someresource.something.k8s.io)

**Comment by droot** [comment]
This should not happen with the recent build, so closing it. Pl. reopen if you observe this.
