### ISSUE TITLE
Upgrade go to 1.17

### ISSUE THREAD

**Issue by ryantking** [kubernetes-sigs/kubebuilder#2421]
This issue will track updating kubebuilder to go version 1.17.

I could not find any language or toolchain changes in the [release notes](https://golang.org/doc/go1.17) that will require changes to the source or any build scripts/CI.

K8s dependencies (check indicates they have been bumped to 1.17):

- [ ] [k8s.io/apimachinery](https://github.com/kubernetes/apimachinery)
- [ ] [sigs.k8s.io/kustomize/kyaml](https://github.com/kubernetes-sigs/kustomize/tree/master/kyaml)
- [x] [sigs.k8s.io/controller-runtime](https://github.com/kubernetes-sigs/controller-runtime)
- [x] [sigs.k8s.io/controller-tools](https://github.com/kubernetes-sigs/controller-tools)

For reference: [go 1.16 update PR](https://github.com/kubernetes-sigs/kubebuilder/pull/2182)

**Comment by ryantking** [comment]
CC: @camilamacedo86

**Comment by camilamacedo86** [comment]
The go version supported is 1.16
We need first bump the upper version in the projects;
- k8s
- controller-runtime
- sigs.k8s.io/kubebuilder-declarative-pattern

then we can bump kubebuilder and by latest SDK. 

Could you please check if the pre-requirements are done and if not, see if is possible to move with them first?

**Comment by rashmigottipati** [comment]
@ryantking We discussed this in the triage meeting and the go version doesn't have to be bumped in kustomize. I believe it was bumped in k8s, controller-runtime and also kb-declarative-pattern, so the next step will be to open a PR against kubebuilder bumping the go version to 1.17.

**Comment by robbie-demuth** [comment]
For my own edification, what is this ticket tracking exactly? As far as I can tell, both Kubebuilder itself and projects scaffolded using Kubebuilder now use 1.17 (as of #2446)

**Comment by ankitm123** [comment]
This should be closed.

**Comment by camilamacedo86** [comment]
Doing that now.
