### ISSUE TITLE
Add to the contribution.md the guidance to create docs

### ISSUE THREAD

**Issue by camilamacedo86** [kubernetes-sigs/kubebuilder#2423]
### What do you want to happen?

I'd like to share with contributions the k8s guidance to contribute with the docs: https://kubernetes.io/docs/contribute/style/style-guide/

So, it shows that would be great we have this one in the CONTRIBUTION.md

### Extra Labels

/kind documentation

**Comment by sayantani11** [comment]
I would like to work on it.
/assign

**Comment by sayantani11** [comment]
I would like to work on it.
/assign

**Comment by sayantani11** [comment]
I would like to work on it.
/assign
