### ISSUE TITLE
Expired link in "Defining your Config" page

### ISSUE THREAD

**Issue by aoi1** [kubernetes-sigs/kubebuilder#2424]
Hi! I was looking at [Defining your Config](https://book.kubebuilder.io/component-config-tutorial/define-config.html) Page, and clicked the link "ControllerManagerConfiguration" but the TODO page appeared.
Seems like the link is already expired, so it would be helpful if there is the correct link on the page. (Tried to find the correct page, but I couldn't.😢)
Thank you!

**Comment by varshaprasad96** [comment]
@aoi1 Thanks for bringing up this issue! https://github.com/kubernetes-sigs/kubebuilder/pull/2436 should fix the link.
