### ISSUE TITLE
kube-rbac-proxy scaffolding should not have debug logging enabled by default

### ISSUE THREAD

**Issue by geezyx** [kubernetes-sigs/kubebuilder#2434]
https://github.com/kubernetes-sigs/kubebuilder/blob/4ef2eb6b64bac803d181eeec3f1b84f2935b475a/pkg/plugins/common/kustomize/v1/scaffolds/internal/templates/config/kdefault/manager_auth_proxy_patch.go#L63

We noticed that the kube-rbac-proxy logging was really verbose and upon inspection, `--v=10` is actually logging the bearer token of the service account that kube-rbac-proxy is using.

**Comment by rashmigottipati** [comment]
@geezyx Thanks for your contribution! We discussed this in triage meeting and we wanted to make a suggestion on the PR to leave the line as commented out instead of removing it altogether. @camilamacedo86 will make a specific comment on the PR with the suggestion.

**Comment by geezyx** [comment]
@rashmigottipati thank you, I'm responding to the PR feedback now.

Just curious - in the future, is it useful to have both an issue and a PR or would y'all prefer just a PR? I wasn't sure the additional issue was redundant.

Appreciate y'all maintaining a great project!

**Comment by camilamacedo86** [comment]
Hi @geezyx, 

The issue usually tracks the need. Not necessary who tracks the need to work in the solution. 
Also, we try to do the backlog triage where the issues are discussed. 
 
However, if you wish to contribute with something and just send the PR it is fine.
If we see that the info in the description is not enough to understand your motivations and help in the review, or if we see that is a topic that requires more discussion which would be nice have the issue we will let you know.

**Comment by camilamacedo86** [comment]
It is done.
