### ISSUE TITLE
asking for a small change of book

### ISSUE THREAD

**Issue by ycyaoxdu** [kubernetes-sigs/kubebuilder#2439]
### What do you want to happen?

Asking for a very small change

while following the tutorial 1.9.2 , i found the command [here](https://book.kubebuilder.io/cronjob-tutorial/running-webhook.html#build-your-image) is not very clear for beginners. 

so i think it can be better if we add a link of the usage of the command we using. 

example: `kind load docker-image your-image-name:your-tag` [usage](https://kind.sigs.k8s.io/docs/user/quick-start/#loading-an-image-into-your-cluster)

so the user could quickly find out what his command would be.

**Comment by camilamacedo86** [comment]
@ycyaoxdu, 

WDYT about update it as we have in the quickstart: https://book.kubebuilder.io/quick-start.html#run-it-on-the-cluster?  (`some-registry>/<project-name>:tag`)

Also, we could add a note in all places that we ask for build/push the image to the registry explaining that it ought to be published in the personal registry and that is required to have access to pull the image from the env where the operator will be executed. 

Would you like to contribute to this PR?

**Comment by ycyaoxdu** [comment]
i'm glad to contribute to this PR, and i will make modify these docs ASAP.
