### ISSUE TITLE
Small typo in docs. 

### ISSUE THREAD

**Issue by anfoxtrot** [kubernetes-sigs/kubebuilder#2444]
### What broke? What's expected?

Under the "Examples:" of `kubebuilder init --help` the sentence "Initialize a new project defining an specific project version" should be "Initialize a new project defining a specific project version". 

### Reproducing this issue

install kubebuilder 

on the terminal type: 
`kubebuilder init --help`. 

### KubeBuilder (CLI) Version

3.2.0

### Extra Labels

/kind documentation

**Comment by camilamacedo86** [comment]
Hi @anfoxtrot, 

Would you like to collab with this fix by raising a PR? See the required places : https://github.com/kubernetes-sigs/kubebuilder/search?q=Initialize+a+new+project+defining

**Comment by anfoxtrot** [comment]
@camilamacedo86 #2445
