### ISSUE TITLE
The operator deployed by kubebuilder has an event create reject error

### ISSUE THREAD

**Issue by moluzhui** [kubernetes-sigs/kubebuilder#2457]
### What broke? What's expected?

My problem is that an unexpected error occurred. After I used `kubebuilder` to build my operator and passed the test, I hope it will become `helm chart`. At this time, I modify the Makefile to modify make install and make deploy
```
chart: manifests kustomize
	$(KUSTOMIZE) build config/crd --output contrib/helm/my_operator/templates
	cd config/manager && $(KUSTOMIZE) edit set image controller=${IMG}
	$(KUSTOMIZE) build config/default --output contrib/helm/my_operator/templates
```
After again, I executed `helm install -n my-operator my_operator/ --debug` which is helm2. At this time, when I was running to add an event, an event permission problem occurred unexpectedly, as shown below
```
event.go:264] Server rejected event '&v1.Event{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"pause-example-extender.16c35e80553bfa67", GenerateName:"", Namespace:"default", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:v1.Time{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, DeletionTimestamp:(*v1.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Finalizers:[]string(nil), ClusterName:"", ManagedFields:[]v1.ManagedFieldsEntry(nil)}, InvolvedObject:v1.ObjectReference{Kind:"MyExtender", Namespace:"default", Name:"pause-example-extender", UID:"9e88de73-deba-4536-83e4-8e11169cc02c", APIVersion:"test.com/v1", ResourceVersion:"45009446", FieldPath:""}, Reason:"SuccessfulUpdate", Message:"Update pause-example.para to 3", Source:v1.EventSource{Component:"MyExtender", Host:""}, FirstTimestamp:v1.Time{Time:time.Time{wall:0xc06934e8a2152667, ext:152115012537, loc:(*time.Location)(0x230bb80)}}, LastTimestamp:v1.Time{Time:time.Time{wall:0xc06934e8a2152667, ext:152115012537, loc:(*time.Location)(0x230bb80)}}, Count:1, Type:"Normal", EventTime:v1.MicroTime{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, Series:(*v1.EventSeries)(nil), Action:"", Related:(*v1.ObjectReference)(nil), ReportingController:"", ReportingInstance:""}': 'events is forbidden: User "system:serviceaccount:my-operator-system:my-operator-controller-manager" cannot create resource "events" in API group "" in the namespace "default"' (will not retry!)
```
This seems to be an event permission issue. I check the clusterrole and the results are as follows
```
# get clusterrole
[root@test ~]# kubectl describe clusterRolebinding my-operator-manager-rolebinding -n my-operator-system
Name:        my-operator-manager-rolebinding
Labels:       <none>
Annotations:  Role:
  Kind:       ClusterRole
  Name:       my-operator-manager-role
Subjects:
  Kind            Name                            Namespace
  ----            ----                            ---------
  ServiceAccount  my-operator-controller-manager  my-operator-system

# describe clusterrole
[root@test ~]# kubectl describe clusterRole my-operator-manager-role
Name:                                         my-operator-manager-role
Labels:                                       <none>
Annotations:                                  PolicyRule:
  Resources           Non-Resource URLs  Resource Names  Verbs
  ---------                                   -----------------  --------------  -----
  test.com             []                 []              [create delete get list patch update watch]
  test.com/status      []                 []              [get patch update]
  test.com/finalizers  []                 []              [update]
```

This does not have the event permission, **but I am sure that before I build the helm chart package, I can use make deploy to create an Event without reporting an error**

**And when I used make deploy again to deploy, I reported the same error as helm deployment**

And I use git to manage my project, I am sure that I **only** modified a condition of Makefile and webhook (a bug found) and created a helm chart using helm create.

**My question is exactly what I have encountered. Why does it suddenly have event permissions? ** 

**Is this a bug with extremely low probability?**  If I want to solve it, what do I need to modify？

### Reproducing this issue

As mentioned earlier, I seem to be unable to reproduce this error, but it only appears when using helm to test

### KubeBuilder (CLI) Version

Version: main.version{KubeBuilderVersion:"3.1.0", KubernetesVendor:"1.19.2", GitCommit:"92e0349ca7334a0a8e5e499da4fb077eb524e94a", BuildDate:"2021-05-27T17:54:28Z", GoOs:"linux", GoArch:"amd64"}

### PROJECT version

version: "3"

### Plugin versions

```yaml
domain: ys7.com
layout:
- go.kubebuilder.io/v3
projectName: my-operator
repo: test/my-operator
resources:
- api:
    crdVersion: v1
    namespaced: true
  controller: true
  domain: test.com
  group: my
  kind: MyCRD
  path: my/my-operator/api/v1
  version: v1
  webhooks:
    defaulting: true
    validation: true
    webhookVersion: v1
version: "3"
```

### Other versions

go version go1.16.9 linux/amd64

**Comment by camilamacedo86** [comment]
Hi @moluzhui, 

It shows that you do have not the permissions to create the events in the default ns.
`'events is forbidden: User "system:serviceaccount:my-operator-system:my-operator-controller-manager" cannot create resource "events" in API group "" in the namespace "default"' (will not retry!)` 

See that you customize the scaffold to work with helm and it is related to your customizations. 
It is not actually a bug with the KB project. 

By using the default scaffold, kb will create an ns with the project name and deploy it there.
Also, for Golang you can use the markers to add and update the RBAC permissions, see: https://book.kubebuilder.io/reference/markers.html. They will update accordingly when you run the make targets calling controller-gen.

You must to ensure that you have the permissions. See that they are scaffold at config/RBAC dir.

So, I am closing this one as sorted ut but feel free to ping in the kubebuilder channel as well if you need a help.

**Comment by stevenkitter** [comment]
When use go run main.go all is ok, but when i deploy it in k8s by image, it will show xx is forbidden.
