### ISSUE TITLE
support array type for printcolumn

### ISSUE THREAD

**Issue by damnever** [kubernetes-sigs/kubebuilder#2466]
### What do you want to happen?

Support custom separator, default to comma, e.g. "a,b,c".

**Comment by camilamacedo86** [comment]
Hi @damnever, 

It ought to be a request for https://github.com/kubernetes-sigs/controller-tools. KB only uses this project. Could you please raise this RFE there and close this one?

**Comment by damnever** [comment]
https://github.com/kubernetes-sigs/controller-tools/issues/652
