### ISSUE TITLE
How to structure a polyglot project?

### ISSUE THREAD

**Issue by camilamacedo86** [kubernetes-sigs/kubebuilder#2475]
Created by @mamachanko as a discussion topic and moved to an issue. 

Hi! 👋 We've got a project that has components in written in different languages:
* an operator in Go
* a CRD-managed application in Java
* an init container image in Go

kubebuilder initialises a project with the operator/controller at its center. There's a main.go in the root of the project. In a multi-component project I would like to tug each away into its own directory.

My idea is to customize the initial project layout to meet a polyglot, multi-component project. Could that be ill-advised? I fear that venturing too far off would make it hard to catch up on kubebuilder releases.

Do you have a recommendation from the trenches?

Do you know of projects that have similar needs?

Thanks a lot!

**Comment by camilamacedo86** [comment]
Hi @mamachanko, 

I am not sure if I properly understood your questions. However, I hope that sharing with you the following docs can help you understand better its ideas and how it works. Anyway, if your idea would be have a manager for each controller then, that seems to me that you need to have more the one project. 

In the main.go the Operator/Manager is initialized. Then, it will manage all controllers that you create in your project to reconcile the APIs.  You can have any controllers and APIs in order to represent the domains of your solution. This https://book.kubebuilder.io/cronjob-tutorial/gvks.html#ah-do-you-have-an-example might help you have a better idea of its concepts.

Also, I'd like to recommend checking the doc: https://sdk.operatorframework.io/docs/best-practices/common-recommendation/ .

By the latest, see that SDK can help you by allowing you to create projects using the Java language via its plugin. See: https://github.com/java-operator-sdk/java-operator-sdk

I hope that helps you out.
Also, it might be easier to follow up with this kind of question in the slack channel #kubebuilder  (kubernetes.slack.com).

In this way, I hope that you do not mind we close this one.
However, feel free to re-open if you see that fits.

**Comment by mamachanko** [comment]
Thanks @camilamacedo86 !

Moving the conversation here from the discussion.

I have found a multi-component project; the now archived [Project Riff](https://github.com/projectriff/system). It is, however, not polyglot. But it’s a good starting point to work off of I think.

In the meantime I will take time to look into the links and info you shared. Ty!

**Comment by camilamacedo86** [comment]
Hi @mamachanko,

By looking at  [Project Riff](https://github.com/projectriff/system) it will create 4 Operators/Managers/Pods.
So, why not create one project for each manager according to its domain? Is that because one operator depends on another? Are they really about the same domain? Could not each piece work standalone?
