### ISSUE TITLE
Install setup-envtest module version which matching with the controller-runtime version instead of latest

### ISSUE THREAD

**Issue by camilamacedo86** [kubernetes-sigs/kubebuilder#2480]
### What do you want to happen?

**Motivation**

The concern/motivation to raise this one is that in Kubebuilder, we are: ([here](https://github.com/kubernetes-sigs/kubebuilder/blob/master/testdata/project-v3/Makefile#L113-L116)) 

```sh
ENVTEST = $(shell pwd)/bin/setup-envtest
.PHONY: envtest
envtest: ## Download envtest-setup locally if necessary.
	$(call go-get-tool,$(ENVTEST),sigs.k8s.io/controller-runtime/tools/setup-envtest@latest)
```

Then, a KB user scaffolds the project today. The scaffold is done with controller-runtime version X.
Afterwards, we are still producing new releases and versions. Thus, this target can begin to download a version of this module that is no longer compatible. 

**Proposed solution**

- Scaffold the package tools with the module import:

```golang
//go:build tools
// +build tools

/*
YOUR_COPYRIGHT
*/

// This package imports things required by build scripts, to force `go mod` to see them as dependencies
package tools

import (
	_ "sigs.k8s.io/controller-runtime/tools/setup-envtest"
)
```

- Change the makefile target to go install the setup-envtest mod version which matches with the controller-runtime version in the go.mod, e.g.:

```sh
ENVTEST = $(shell pwd)/bin/setup-envtest
.PHONY: envtest
envtest: ## Download envtest-setup locally if necessary.
	$(call go-get-tool,$(ENVTEST),sigs.k8s.io/controller-runtime/tools/setup-envtest)
```

Then, the command `go install sigs.k8s.io/controller-runtime/tools/setup-envtest` ought to install its version which  
corresponding with the C+R version used into the project. More info: https://github.com/kubernetes-sigs/controller-runtime/issues/1670

**Comment by NikhilSharmaWe** [comment]
@camilamacedo86 I would like to work on this.
/assign

**Comment by camilamacedo86** [comment]
Adding here what was discussed in for : 

From @joelanford : 

This setup is going to result in the project's CI dependencies being added to the main project's go.mod file, which has implications on:
how underlying dependencies get resolved when a build tool and the main project share a transitive dependency (e.g. the build tool might unnecessarily hold back the transitive dependency on a lower version due to Go's MVS algorithm)
how other projects consume this project as a dependency (external projects will end up with this project's build tool dependencies in their go.mod files and might impact their transitive dependency selection also due to MVS)
TL;DR: At a minimum, I think we need to put the tools dependencies in a separate go module. However see also this issue for background about why even that might not be a great idea: https://github.com/kubernetes-sigs/cluster-api/issues/5569

From @camilamacedo86 : 

Note that the main reason/motivation for them do not add the dep as an import in the issue shared is Also this helps to make the version of our dependencies visible top-level (in the Makefile instead of hack/tools/go.mod) which does not seems our case; we are only trying to use this approach with the env-test to ensure that its version is compatible with the controller-runtime one scaffold in the project and not all scenarios. The approach was the solution provided by the controller-runtime maintainers, see: https://github.com/kubernetes-sigs/kubebuilder/issues/2480

However, what would be your suggestion for us do not to scaffold to use env-test from the latest by default in this case?

@From @joelanford :

**Comment by rumstead** [comment]
Is there a recommendation on how to get the dependencies?

I have a `tools/tools.go` with the required dependencies

```
sigs.k8s.io/controller-runtime/tools/setup-envtest: module sigs.k8s.io/controller-runtime@latest found (v0.12.3), but does not contain package sigs.k8s.io/controller-runtime/tools/setup-envtest
```

**Comment by jroper** [comment]
The dependency on latest has just caused our build to suddenly fail without us changing anything:

```
22:45:19 > Downloading sigs.k8s.io/controller-runtime/tools/setup-envtest@latest
go: downloading sigs.k8s.io/controller-runtime/tools/setup-envtest v0.0.0-20231008020014-968daa8964f9
go: downloading go.uber.org/zap v1.26.0
go: downloading github.com/go-logr/zapr v1.2.4
go: downloading github.com/go-logr/logr v1.2.4
go: downloading golang.org/x/text v0.12.0
go: downloading go.uber.org/multierr v1.10.0
# go.uber.org/multierr
/home/circleci/go/pkg/mod/go.uber.org/multierr@v1.10.0/error.go:224:20: undefined: atomic.Bool
note: module requires Go 1.19
make[1]: *** [Makefile:171: envtest] Error 2
make: *** [Makefile:114: test] Error 2
```

This violates the principle of repeatable builds. We shouldn't be forced to upgrade to Go 1.19 before we are ready. There needs to be a better way.

**Comment by yangsoon** [comment]
> The dependency on latest has just caused our build to suddenly fail without us changing anything:
> 
> ```
> 22:45:19 > Downloading sigs.k8s.io/controller-runtime/tools/setup-envtest@latest
> go: downloading sigs.k8s.io/controller-runtime/tools/setup-envtest v0.0.0-20231008020014-968daa8964f9
> go: downloading go.uber.org/zap v1.26.0
> go: downloading github.com/go-logr/zapr v1.2.4
> go: downloading github.com/go-logr/logr v1.2.4
> go: downloading golang.org/x/text v0.12.0
> go: downloading go.uber.org/multierr v1.10.0
> # go.uber.org/multierr
> /home/circleci/go/pkg/mod/go.uber.org/multierr@v1.10.0/error.go:224:20: undefined: atomic.Bool
> note: module requires Go 1.19
> make[1]: *** [Makefile:171: envtest] Error 2
> make: *** [Makefile:114: test] Error 2
> ```
> 
> This violates the principle of repeatable builds. We shouldn't be forced to upgrade to Go 1.19 before we are ready. There needs to be a better way.

I also encountered this issue just now. You can temporarily fix it by using the command 
```
go install sigs.k8s.io/controller-runtime/tools/setup-envtest@v0.0.0-20230620070423-a784ee78d04b
```

**Comment by Huang-Wei** [comment]
Use `@latest` leads to downloading deps that may need higher version of Go, which breaks my CI:

```console
     go: downloading go.uber.org/multierr v1.10.0
     # go.uber.org/multierr
     /go/pkg/mod/go.uber.org/multierr@v1.10.0/error.go:224:20: undefined: atomic.Bool
     note: module requires Go 1.19
```

As @jroper mentioned above, it violates the principle of repeatable builds.

**Comment by zeeke** [comment]
> > The dependency on latest has just caused our build to suddenly fail without us changing anything:
> > ```
> > 22:45:19 > Downloading sigs.k8s.io/controller-runtime/tools/setup-envtest@latest
> > go: downloading sigs.k8s.io/controller-runtime/tools/setup-envtest v0.0.0-20231008020014-968daa8964f9
> > go: downloading go.uber.org/zap v1.26.0
> > go: downloading github.com/go-logr/zapr v1.2.4
> > go: downloading github.com/go-logr/logr v1.2.4
> > go: downloading golang.org/x/text v0.12.0
> > go: downloading go.uber.org/multierr v1.10.0
> > # go.uber.org/multierr
> > /home/circleci/go/pkg/mod/go.uber.org/multierr@v1.10.0/error.go:224:20: undefined: atomic.Bool
> > note: module requires Go 1.19
> > make[1]: *** [Makefile:171: envtest] Error 2
> > make: *** [Makefile:114: test] Error 2
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > This violates the principle of repeatable builds. We shouldn't be forced to upgrade to Go 1.19 before we are ready. There needs to be a better way.
> 
> I also encountered this issue just now. You can temporarily fix it by using the command
> 
> ```
> go install sigs.k8s.io/controller-runtime/tools/setup-envtest@v0.0.0-20230620070423-a784ee78d04b
> ```

As an alternative, not sure if it's better than referencing a specific commit, you can target a branch:
```
 go install sigs.k8s.io/controller-runtime/tools/setup-envtest@release-0.13
go: downloading sigs.k8s.io/controller-runtime/tools/setup-envtest v0.0.0-20231026160510-6ffcf19a340d
go: downloading sigs.k8s.io/controller-runtime v0.13.2
go: downloading golang.org/x/text v0.3.6
```
