### ISSUE TITLE
Initializing a project does not work with 3.3.0

### ISSUE THREAD

**Issue by antonincms** [kubernetes-sigs/kubebuilder#2488]
### What broke? What's expected?

I don't know if it is a corner-case related to some of my config, or some kind of PEBCAK because it seems so big, 
but when I try to initialize a new project it simply fails for me (cf *Reproducing this issue*). 

### Reproducing this issue

```
me@t490:~$ mkdir -p ~/projects/guestbook
me@t490:~$ cd ~/projects/guestbook
me@t490:~$ kubebuilder init --domain my.domain --repo my.domain/guestbook
Writing kustomize manifests for you to edit...
Writing scaffold for you to edit...
Get controller runtime:
$ go get sigs.k8s.io/controller-runtime@v0.11.0
# sigs.k8s.io/json/internal/golang/encoding/json
../../go/pkg/mod/sigs.k8s.io/json@v0.0.0-20211020170558-c049b76a60c6/internal/golang/encoding/json/encode.go:1249:12: sf.IsExported undefined (type reflect.StructField has no field or method IsExported)
../../go/pkg/mod/sigs.k8s.io/json@v0.0.0-20211020170558-c049b76a60c6/internal/golang/encoding/json/encode.go:1255:18: sf.IsExported undefined (type reflect.StructField has no field or method IsExported)
Error: failed to initialize project: unable to scaffold with "base.go.kubebuilder.io/v3": exit status 2
```

### KubeBuilder (CLI) Version

Version: main.version{KubeBuilderVersion:"3.3.0", KubernetesVendor:"1.23.1", GitCommit:"47859bf2ebf96a64db69a2f7074ffdec7f15c1ec", BuildDate:"2022-01-18T17:03:29Z", GoOs:"linux", GoArch:"amd64"}

### PROJECT version

The project is not scaffolded yet.

### Plugin versions

```yaml
The project is not scaffolded yet.
```

### Other versions

me@t490:~$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 21.10
Release:	21.10
Codename:	impish

me@t490:~$ go version
go version go1.16.12 linux/amd64

me@t490:~$ kubectl version --client
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.1", GitCommit:"86ec240af8cbd1b60bcc4c03c20da9b98005b92e", GitTreeState:"clean", BuildDate:"2021-12-16T11:41:01Z", GoVersion:"go1.17.5", Compiler:"gc", Platform:"linux/amd64"}

**Comment by camilamacedo86** [comment]
Hi @antonincms, 

The problem is the go version. You must use go 1.17 with 3.3.0+ 
Can you please upgrade the go version installed and check it out?

**Comment by camilamacedo86** [comment]
Hi @antonincms, 

That is true, We did not updated : https://book.kubebuilder.io/quick-start.html

<img width="435" alt="Screenshot 2022-01-20 at 14 00 51" src="https://user-images.githubusercontent.com/7708031/150353119-5ed729a3-b687-445c-937d-bff4efc59a53.png">

Could you help us by pushing a PR to fix that? 
We also need to cherry-pick it to the branch book-v3.

**Comment by antonincms** [comment]
> Could you help us by pushing a PR to fix that?
I will, but i'm waiting for support on my CLA agreement :smile:
