### ISSUE TITLE
kubebuilder docs refers to pkg/controller even when a controller has not been generated

### ISSUE THREAD

**Issue by perotinus** [kubernetes-sigs/kubebuilder#249]
See https://github.com/kubernetes-sigs/kubebuilder/blob/561e4da021cdee17759d74580829ab1e9a6eb6cb/cmd/kubebuilder/docs/gen.go#L25

If the code generation did not include a controller, it seems that this package should not be referenced when doing doc generation. Perhaps the search can optionally add this package if it exists?

**Comment by pwittrock** [comment]
I think we can just remove the controller.  It shouldn't be required.  Feel free to file a PR to remove it, otherwise I can get to it later.

**Comment by perotinus** [comment]
@pwittrock Thank you! This seems easy enough, I'll push a PR out today.
