### ISSUE TITLE
Update/fix EnvTest config doc

### ISSUE THREAD

**Issue by camilamacedo86** [kubernetes-sigs/kubebuilder#2499]
### What broke? What's expected?

See: https://book.kubebuilder.io/reference/envtest.html

- k8s versions are outdated

Then, it also shows to be missing:

- how to run/config the env test to run the tests without the makefile target. E.g via an idea to debug
- how to use the module: https://github.com/kubernetes-sigs/controller-runtime/tree/master/pkg/envtest
- how to use other paths: https://github.com/kubernetes-sigs/controller-runtime/blob/master/pkg/internal/testing/process/bin_path_finder.go#L35
- how the makefile target scaffold by default works: https://github.com/kubernetes-sigs/kubebuilder/blob/master/testdata/project-v3/Makefile#L113-L116 - See that we will change that: https://github.com/kubernetes-sigs/kubebuilder/issues/2480 / https://github.com/kubernetes-sigs/kubebuilder/pull/2486

### Reproducing this issue

Run the tests without using the target and check the docs

### KubeBuilder (CLI) Version

3.+

### PROJECT version

3

### Plugin versions

```yaml
v3
```

### Extra Labels

/kind documentation

**Comment by camilamacedo86** [comment]
@varshaprasad96 if you have time could you please give a hand in this one?
If we updated the docs and add the missing info we also could close the SDK issues such as https://github.com/operator-framework/operator-sdk/issues/5090.

**Comment by acechef** [comment]
i cannot find binary for darwin/arm64 @camilamacedo86

**Comment by shintard** [comment]
I am facing the same problem.
Do you have any solution?

**Comment by camilamacedo86** [comment]
It seems done here: https://github.com/kubernetes-sigs/kubebuilder/pull/2900

We can open another issue if we find that something still missing.
