### ISSUE TITLE
Missing struct fields and import issues

### ISSUE THREAD

**Issue by crimsonfaith91** [kubernetes-sigs/kubebuilder#25]
Some generated structs have missing fields.
For instance, `InjectArgs` struct does not have some necessary fields such as `Clientset`:
```
arguments.Clientset undefined (type args.InjectArgs has no field or method Clientset)
``` 

There are several import issues after generating the codes too.
For instance, in `/cmd/controller-manager/main.go`, there is a conflicting import for `k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1` due to 2 `vendor` packages in the repo (one is `<pkg>/vendor`, another is `<pkg>/cmd/vendor`).

Same errors happened after re-downloading kubebuilder and re-generating the files.

**Comment by crimsonfaith91** [comment]
@pwittrock

**Comment by pwittrock** [comment]
Which version are you using?  Can you provide steps to reproduce from an empty repo?

**Comment by crimsonfaith91** [comment]
Sorry for not making it clear enough.
I am using release `v1beta1.1`. The steps are as follow:
1. download `kubebuilder-release-v1beta1.1-linux-amd64.tar.gz` and put it into `/usr/local/kubebuilder`
2. download tar.gz source codes and extract it into workspace
3. `kubebuilder init --domain google.com`
4. `kubebuilder create resource --group operator --version v1beta1  --kind RedisReplicas`
5. `GOBIN=$(pwd)/bin go install <PROJECT_PACKAGE>/cmd/controller-manager`

The missing field error happens at step 5:
`arguments.Clientset undefined (type args.InjectArgs has no field or method Clientset)`

**Comment by pwittrock** [comment]
Which tar.gz are you referring to in step 2?  I don't think this step should be required.  Does the documentation say to do this?

**Comment by crimsonfaith91** [comment]
It is the `Source code (tar.gz)` under release page.

**Comment by crimsonfaith91** [comment]
I think the source code download step (step 2) is unnecessary. I always downloaded both `tar.gz` and `bin` files for previous versions, which worked all the time before. I didn't realize `bin` file alone suffices for newest `v1beta1.1` version.

**Comment by crimsonfaith91** [comment]
Oops, I was misled by `Download the latest release _and_ extract the tar.gz...` since from the beginning. I thought _latest release_ is the _source code_, and `tar.gz` is the `bin` file.
