### ISSUE TITLE
Controller test generator doesn't handle the cluster-scoped resources correctly

### ISSUE THREAD

**Issue by mengqiy** [kubernetes-sigs/kubebuilder#250]
The template is at:
https://github.com/kubernetes-sigs/kubebuilder/blob/83156c1279897cde2339eaacb024a9eb73d94836/cmd/kubebuilder/create/controller/controllertest.go#L164
The cause seems to be that we haven't set `NonNamespacedKind` anywhere, it is defaulted to `false`.

It currently generates
```
client = ks.AdmissionregistrationV1beta1().MutatingWebhookConfigurations("default")
```
But it should generate
```
client = ks.AdmissionregistrationV1beta1().MutatingWebhookConfigurations()
```

**Comment by droot** [comment]
@mengqiy Can you pl. confirm if this issue exist in recent versions ?

**Comment by mengqiy** [comment]
I believe so. It's a bug in v0.

**Comment by droot** [comment]
@mengqiy Can you pl. confirm if it still exists ?
