### ISSUE TITLE
e2e tests should fail if default skeleton began to be incompatible with the k8s versions used

### ISSUE THREAD

**Issue by camilamacedo86** [kubernetes-sigs/kubebuilder#2504]
### What do you want to happen?

The changes in the PR https://github.com/kubernetes-sigs/kubebuilder/pull/2498 make the default skeleton began to be incompatible with the k8s versions used to do the tests but the tests do not fail as should be.

The goal of this task is to improve the e2e test to ensure that we will not introduce breaking changes like this one. See: https://github.com/kubernetes-sigs/kubebuilder/pull/2498#issuecomment-1026698929

**Comment by NikhilSharmaWe** [comment]
@camilamacedo86 Could you please elaborate. The issue you mentioned above is related to the kustomize version, but the goal of this issue is related to making tests fail based on kubernetes version. 

Could you please explain what are we trying to achieve here.

**Comment by camilamacedo86** [comment]
Hi @NikhilSharmaWe, 

We open this one because we thought that our e2e test should get that.
However, by analysing it deeper we could realize that does not happened because:
a) Our default scaffolds still compatible with V4
b) For now at least, and to help authors customize maintainers are keep what is deprecated so the things will still working

In this way, we have nothing to do in our e2e test and I am closing this one as sorted out.
