### ISSUE TITLE
build kubebuilder-tools for darwin/arm64

### ISSUE THREAD

**Issue by Huang-Wei** [kubernetes-sigs/kubebuilder#2505]
### What do you want to happen?

More and more developers are starting to use M1 MacBook for daily development, is it possible to build kubebuilder-tools for darwin/arm64? Currently it's not available: https://storage.googleapis.com/kubebuilder-tools

**Comment by dntosas** [comment]
Hey team! cc @camilamacedo86 @Huang-Wei 

Pushed a PR to init the mitigation of this, you can check in here --> https://github.com/kubernetes-sigs/kubebuilder/pull/2516

**Comment by avizov** [comment]
when do you plan to release a new version which includes this fix?
