### ISSUE TITLE
Is the Using Finalizers doc up-to-date?

### ISSUE THREAD

**Issue by rayterrill** [kubernetes-sigs/kubebuilder#2508]
### What broke? What's expected?

Attempted to follow the documentation to configure a finalizer for my controller:
```
    controlPlane := *controlplanev1beta1.AWSManagedControlPlane
    if err := r.Get(ctx, req.NamespacedName, controlPlane); err != nil {
```

This was resulting in the following:
```
expected pointer but got nil
```

I flipped this to the following (looking at the controller-runtime docs here: https://github.com/kubernetes-sigs/controller-runtime/blob/f236f0345ad2933912ebf34bfcf0f93620769654/example_test.go#L123):
```
	controlPlane := &controlplanev1beta1.AWSManagedControlPlane{}
	if err := r.Get(ctx, req.NamespacedName, controlPlane); err != nil {
```

This works fine.

### KubeBuilder (CLI) Version

Version: main.version{KubeBuilderVersion:"3.3.0", KubernetesVendor:"unknown", GitCommit:"47859bf2ebf96a64db69a2f7074ffdec7f15c1ec", BuildDate:"2022-01-17T18:05:10Z", GoOs:"darwin", GoArch:"amd64"}

### PROJECT version

3

### Plugin versions

```yaml
go.kubebuilder.io/v3
```

**Comment by camilamacedo86** [comment]
Hi @rayterrill, 

It shows that when you face the error you declare a nil var versus the fix that is an empty instance.

Sorry, but I do not see how it can be related to the project itself or how can we improve the docs in this case. 
I hope that you do not mind we close this one. However, please feel free to raise new questions or report new issues.

**Comment by cmssczy** [comment]
Controller will indeed panic if we follow the documentation to configure a finalizer.
Because `cronJob` is nil pointer. I think we shoud change `var cronJob *batchv1.CronJob` to `cronJob := new(batchv1.CronJob)`.
```go
var cronJob *batchv1.CronJob
if err := r.Get(ctx, req.NamespacedName, cronJob); err != nil {
    log.Error(err, "unable to fetch CronJob")
    // we'll ignore not-found errors, since they can't be fixed by an immediate
    // requeue (we'll need to wait for a new notification), and we can get them
    // on deleted requests.
    return ctrl.Result{}, client.IgnoreNotFound(err)
}
```

**Comment by sj14** [comment]
Indeed, what @cmssczy said or `cronJob := &batchv1.CronJob{}`
@camilamacedo86 please consider reopening the issue until the docs are fixed.

**Comment by camilamacedo86** [comment]
HI @rayterrill,

We can update it for: 
cronJob := &batchv1.CronJob{}

Could you please create a new issue where we will describe the place where the update should occur and why?
Also, would you like to contribute to this one? Please, feel free to push the PR.
