### ISSUE TITLE
[ci]- Add e2e test against 1.23 k8s version

### ISSUE THREAD

**Issue by camilamacedo86** [kubernetes-sigs/kubebuilder#2509]
### What do you want to happen?

See that we test the changes against specific k8s versions clusters: 

<img width="1040" alt="Screenshot 2022-02-11 at 13 59 28" src="https://user-images.githubusercontent.com/7708031/153635104-9928df04-5723-4f19-8777-8d1087fe4ed3.png">

This task is for us to add the checks against 1.23

**Comment by camilamacedo86** [comment]
HI @ryantking would you like to check this one out? 
WDYT?

**Comment by sunny-b** [comment]
@camilamacedo86 I'd be happy to take this on.

**Comment by sunny-b** [comment]
@camilamacedo86 Just to clarify, in order to add the 1-23 e2e test, we need to add it to the `test-infra` repo in [this file](https://github.com/kubernetes/test-infra/blob/master/config/jobs/kubernetes-sigs/kubebuilder/kubebuilder-presubmits.yaml#L22-L51)? And update the `KIND_K8S_VERSION` to 1.23.1?

**Comment by camilamacedo86** [comment]
Hi @sunny-b,

That is the file/repo. I think we can check what is the latest 1.23 version available and use it. I think that would be 1.23.3.

**Comment by sunny-b** [comment]
Looks like it's [1.23.4](https://kubernetes.io/releases/). I'll use that.

**Comment by sunny-b** [comment]
@camilamacedo86 FYI I have an open PR with test-infra: https://github.com/kubernetes/test-infra/pull/25594

**Comment by camilamacedo86** [comment]
Done: 
<img width="937" alt="Screenshot 2022-03-15 at 20 32 24" src="https://user-images.githubusercontent.com/7708031/158467240-ecf0c6e9-6d5d-468b-bf20-d2a295872dd1.png">
