### ISSUE TITLE
Kubebuilder inits in go1.16 and pkgs miss methods later on

### ISSUE THREAD

**Issue by nikfot** [kubernetes-sigs/kubebuilder#2518]
### What broke? What's expected?

I am followin the basic tutorial documentation, just instead of creating a CronJob I try it out with a deployment. It initiates the env with go1.16 in `go.mod`.

Later on, when running `kubebuilder create api --group apps --version v1 --kind Deployment` I get errors saying Deployment struct is missing DeepCopy method.

When changing the version in `go.mod` and running `go mod tidy` it fixes all issues.

### Reproducing this issue

1. `kubebuilder init --domain tutorial.kubebuilder.io --repo tutorial.kubebuilder.io/project`
2. `kubebuilder create api --group apps --version v1 --kind Deployment`

### KubeBuilder (CLI) Version

Version: main.version{KubeBuilderVersion:"v3.0.0-alpha.0-411-gf4dbb5c8", KubernetesVendor:"unknown", GitCommit:"f4dbb5c82e436c6943d81abb2bf0b5b2b3478921", BuildDate:"2021-12-14T07:10:30Z", GoOs:"linux", GoArch:"amd64"}

### PROJECT version

3

### Other versions

`go version go1.17.7 linux/amd64`

**Comment by camilamacedo86** [comment]
Hi @nikfot, 

You are using Kubebuilder v3.0.0 right? So, the go version supported for it is 1.15 : https://github.com/kubernetes-sigs/kubebuilder/blob/v3.0.0/go.mod#L3

Please, see the comment:  https://github.com/kubernetes-sigs/kubebuilder/issues/2512#issuecomment-1047787916

Also, could you please check if your issue scenario can be reproduced with the latest KB release and go 1.17+?
