### ISSUE TITLE
`kubebuilder create api` failed

### ISSUE THREAD

**Issue by bestgopher** [kubernetes-sigs/kubebuilder#2527]
### Discussed in https://github.com/kubernetes-sigs/kubebuilder/discussions/2526

<div type='discussions-op-text'>

<sup>Originally posted by **bestgopher** March  5, 2022</sup>
I am new to kubebuilder. When I follow the book add a new api by `kubebuilder create api` command, an error raised.
<img width="949" alt="image" src="https://user-images.githubusercontent.com/36840497/156880662-df97fcdf-0ac5-4e65-932c-1e3835f6b618.png">
<img width="303" alt="image" src="https://user-images.githubusercontent.com/36840497/156880690-a05690c7-00b2-4d0a-a7d3-3aa6c3d12068.png">
</div>

**Comment by camilamacedo86** [comment]
Could you please let us know what is the KB version and the go version used by you?

**Comment by camilamacedo86** [comment]
See: https://github.com/kubernetes-sigs/kubebuilder/issues/2530

**Comment by bestgopher** [comment]
@camilamacedo86 
➜  ~ go version
go version go1.17.6 darwin/amd64
➜  ~ kubebuilder version
Version: main.version{KubeBuilderVersion:"3.3.0", KubernetesVendor:"1.23.1", GitCommit:"47859bf2ebf96a64db69a2f7074ffdec7f15c1ec", BuildDate:"2022-01-18T17:03:29Z", GoOs:"darwin", GoArch:"amd64"}

**Comment by camilamacedo86** [comment]
Following some questions:

1. Are you trying to use the latest release with a previous scaffold?
2. Could you please copy and paste here the PROJECT file of your project? 
3. Did you make any change in the default scaffold such as versions used?
4. Can you run `make controller-gen` and let us know what happens? 
5. Did you change the. Makefile or is it identical to : https://github.com/kubernetes-sigs/kubebuilder/blob/master/testdata/project-v3/Makefile?

**Comment by bestgopher** [comment]
Hi, thanks for your help. I think I found the cause of my bug. The golang version of my goland configuration is 1.18,  this version changed the behavior of go get and no longer builds or installs packages in module-aware mode.

**Comment by camilamacedo86** [comment]
Hi @bestgopher, 

Thank you for letting us know. 
I am closing this one but see that I tracked https://github.com/kubernetes-sigs/kubebuilder/issues/2530 for we working on to avoid this scenario.
