### ISSUE TITLE
KB is not failing for go versions not supported 

### ISSUE THREAD

**Issue by camilamacedo86** [kubernetes-sigs/kubebuilder#2530]
### What broke? What's expected?

Currently, the go version supported is 1.17.x. See that we check the versions supported but we have not been updating it:
- https://github.com/kubernetes-sigs/kubebuilder/blob/master/pkg/plugins/golang/go_version_test.go#L128-L198 
- https://github.com/kubernetes-sigs/kubebuilder/blob/master/pkg/plugins/golang/go_version.go

We have been facing many issues because people are using versions < 1.17 so we need to fix it. 

### Reproducing this issue

Try to create an api with go version < 1.17

### KubeBuilder (CLI) Version

3.3.0

**Comment by camilamacedo86** [comment]
E.g: https://github.com/kubernetes-sigs/kubebuilder/issues/2527#issuecomment-1062429396

**Comment by Abhra303** [comment]
We have to modify only the `v3/into.go` file right? The `v2/init.go` doesn't need modification if I am not wrong.

**Comment by camilamacedo86** [comment]
This issue has a PR already: https://github.com/kubernetes-sigs/kubebuilder/pull/2537

**Comment by camilamacedo86** [comment]
It seems done for the latest releases. So, I am closing this one.
