### ISSUE TITLE
For go/v4, remove the option to create v1beta1 CRD and Webhooks

### ISSUE THREAD

**Issue by camilamacedo86** [kubernetes-sigs/kubebuilder#2531]
### What do you want to happen?

For go/v4, remove the option to create v1beta1 CRD and Webhooks.
These APIs are no longer supported since k8s 1.22 and with versions upper than controller-gen v0.6.2 and controller-runtime v0.9.2. As a workaround to allow users to move forward and not break the backwards compatibility we have been trying to downgrade the versions, see: https://github.com/kubernetes-sigs/kubebuilder/blob/master/pkg/plugins/golang/v3/commons.go#L38

Places that need to be cleaned up for go/v4: 

**For webhooks**
- https://github.com/kubernetes-sigs/kubebuilder/blob/master/pkg/plugins/golang/v3/webhook.go#L72-L73
- https://github.com/kubernetes-sigs/kubebuilder/blob/master/pkg/plugins/golang/v3/webhook.go#L131-L135

**For CRDs**
- https://github.com/kubernetes-sigs/kubebuilder/blob/master/pkg/plugins/golang/v3/api.go#L109-L110
- https://github.com/kubernetes-sigs/kubebuilder/blob/master/pkg/plugins/golang/v3/api.go#L190-L197

**Comment by NikhilSharmaWe** [comment]
@camilamacedo86 Could you please respond to my [previous](https://github.com/kubernetes-sigs/kubebuilder/issues/2531#issuecomment-1066653961) comment.

**Comment by NikhilSharmaWe** [comment]
@camilamacedo86 Could you please respond to my https://github.com/kubernetes-sigs/kubebuilder/issues/2531#issuecomment-1066653961 comment.

**Comment by camilamacedo86** [comment]
Hi @NikhilSharmaWe,

All issues under the milestone  https://github.com/kubernetes-sigs/kubebuilder/milestone/26 are breaking changes and can only get done when we do a go/v4 plugin. 

So, if we want to do that we need to: 
- Make a copy of https://github.com/kubernetes-sigs/kubebuilder/tree/master/pkg/plugins/golang/v3 to https://github.com/kubernetes-sigs/kubebuilder/tree/master/pkg/plugins/golang/v4
- Then, rename the plugin. info to go/v4 + ensure that it will be alpha1 version 
- We also need to began to scaffold samples for the go/v4 as we do for go/v3 under the testdata, see: https://github.com/kubernetes-sigs/kubebuilder/blob/master/test/testdata/generate.sh

<img width="377" alt="Screenshot 2022-03-18 at 15 45 03" src="https://user-images.githubusercontent.com/7708031/159035890-98aa8f54-2c21-4b8b-89ae-62cae62c6825.png">

Then, we can apply on this one everything that is under this milestone
Also, by default kubebuilder should still scaffold the go/v3 and it will be changed only when go/v4 be promoted to stable. 

I created an task for that, see: https://github.com/kubernetes-sigs/kubebuilder/issues/2547
