### ISSUE TITLE
Upgrade ginkgo to v2 for go/v4 plugin

### ISSUE THREAD

**Issue by haoxins** [kubernetes-sigs/kubebuilder#2532]
### What do you want to happen?

I just submitted a PR for upgrading ginkgo to `v2`, see https://github.com/kubernetes-sigs/kubebuilder/pull/2522
After some discussions we found it's a broken change for `go/v3`.
So I created this issue for tracking the upgrade and intend to be added to [v4 milestone](https://github.com/kubernetes-sigs/kubebuilder/milestone/26).

**Comment by camilamacedo86** [comment]
We checked in the review that changes in the scaffolds are required and that the previous code will not work with ginkgo v2 so it is a breaking change and then we cannot move forward in go/v3. We will need a go/v4 plugin to add this one.

See that the scaffolds require to be changed with the following migrations. 

https://onsi.github.io/ginkgo/MIGRATING_TO_V2#generating-custom-reports-when-a-test-suite-completes
https://onsi.github.io/ginkgo/MIGRATING_TO_V2#removed-async-testing
Also, you can check the policy: https://github.com/kubernetes-sigs/kubebuilder/blob/master/VERSIONING.md#introducing-changes-to-plugins

**Comment by camilamacedo86** [comment]
We update the CLI: https://github.com/kubernetes-sigs/kubebuilder/pull/2876
However, we need to update the scaffolds.
Also, since C+R and k8s made the update and their a dep we probably need to ensure the same for all scaffolds indeed go/v3

**Comment by camilamacedo86** [comment]
Hi @jakobmoellersap,

Are you able to help us update the scaffolds by doing the same changes in the scaffolds so we are able to do a new release with this change?

**Comment by jakMoeller** [comment]
Yup, was out the last few days. Will submit a draft today.

**Comment by camilamacedo86** [comment]
Done.
