### ISSUE TITLE
Create go/v4 plugin with alpha1 level to address changes which are breaking ones for go/v3

### ISSUE THREAD

**Issue by camilamacedo86** [kubernetes-sigs/kubebuilder#2547]
### What do you want to happen?

The goal of this task is to:
- Create go/v4 plugin with alpha1 level to address changes which are breaking ones for go/v3

Also, you can check the policy: https://github.com/kubernetes-sigs/kubebuilder/blob/master/VERSIONING.md#introducing-changes-to-plugins.

**What is required to:** 

- Make a copy of https://github.com/kubernetes-sigs/kubebuilder/tree/master/pkg/plugins/golang/v3 to https://github.com/kubernetes-sigs/kubebuilder/tree/master/pkg/plugins/golang/v4
- see that we define the level / version of the plugin in: https://github.com/kubernetes-sigs/kubebuilder/blob/master/pkg/plugins/golang/v3/plugin.go#L29-L31
- Then, rename the plugin. info to go/v4 + ensure that it will be alpha1 version 
- We also need to began to scaffold samples for the go/v4 as we do for go/v3 under the testdata, see: https://github.com/kubernetes-sigs/kubebuilder/blob/master/test/testdata/generate.sh

<img width="377" alt="Screenshot 2022-03-18 at 15 45 03" src="https://user-images.githubusercontent.com/7708031/159035890-98aa8f54-2c21-4b8b-89ae-62cae62c6825.png">

For go/v4 we do not need the sample v1beta1 since we will remove its support. See: https://github.com/kubernetes-sigs/kubebuilder/issues/2531

- By latest, we also will need the e2e tests for go/v4 see: https://github.com/kubernetes-sigs/kubebuilder/tree/master/test/e2e/v3

**Comment by Ankit152** [comment]
Hey @camilamacedo86 🙂 
I would like to work on this issue. Can you assign me this one?

**Comment by camilamacedo86** [comment]
that is great 👍 

/assign @Ankit152 

^ done

**Comment by Ankit152** [comment]
Thank you very much 🙂

**Comment by Ankit152** [comment]
Hey @NikhilSharmaWe 🙂 
Thank you for your interest on this but this issue is assigned to me.

**Comment by NikhilSharmaWe** [comment]
@Ankit152 Actually I was interested in working on https://github.com/kubernetes-sigs/kubebuilder/issues/2531 but we should add new go/v4 plugin before working on that.

You should join this thread https://kubernetes.slack.com/archives/CAR30FCJZ/p1647679086601079 and we can distribute our work.

**Comment by Ankit152** [comment]
@NikhilSharmaWe I totally understand but before moving forward with my assigned issue you could have asked me regarding this.

**Comment by NikhilSharmaWe** [comment]
@Ankit152 I think this is not an appropriate place for having a conversation like this (I assume you will understand).

**Comment by Ankit152** [comment]
Hey @camilamacedo86 🙂 
I think this issue should be assigned to @NikhilSharmaWe as he has done quite a lot of progress with his PR.

**Comment by camilamacedo86** [comment]
Based on the latest discussions on the Kubebuider and C+R meetings and the latest finds: 

a) To address the kustomize requirements we do not need a new base golang to go v4 alpha plugin. It needs to be done in the kustomize one. See: https://github.com/kubernetes-sigs/kubebuilder/pull/2583

b) Then, shows that we have not enough requirements yet to justify a new base go v4 plugin. The only things that we could address on this one are:
- https://github.com/kubernetes-sigs/kubebuilder/issues/2532
- https://github.com/kubernetes-sigs/kubebuilder/issues/2531

So that, at this moment it would add an extra cost for us to keep maintaining the projects which are not justified by the value that it brings. 

c) The only thing that we might want to still add currently would be a new go/v4-alpha plugin to help users begin to use the kustomize/v2-alpha after the PR  https://github.com/kubernetes-sigs/kubebuilder/pull/2583 get merged. 

That would mean 

we only change the cli to have:

```sh
	gov4Bundle, _ := plugin.NewBundle(golang.DefaultNameQualifier, plugin.Version{Number: 4, Stage: stage.Alpha},
		kustomizecommonv2.Plugin{}, // new alpha plugin
		golangv3.Plugin{}, // current language based plugin 
	)
```

And the test data scaffolds for this one. 
PS.: Looking in the PR: https://github.com/kubernetes-sigs/kubebuilder/issues/2547 that would mean not add all files under: https://github.com/kubernetes-sigs/kubebuilder/tree/master/pkg/plugins/golang/v4

However, IMO would be nice if we tried to do the above ^ change and discuss it with the other maintainers as well.

In this way, @NikhilSharmaWe I would like to recommend:
a) Let's wait for the PR https://github.com/kubernetes-sigs/kubebuilder/pull/2583 to get merged
b) Then, I'd suggest we change your PR to https://github.com/kubernetes-sigs/kubebuilder/issues/2547 as described above so that, we can easily show the results and bring this topic for others be able to opnieted about its pros and cons.
