### ISSUE TITLE
You cannot scaffold twice, see the error `Error: failed to create webhook: unable to inject the resource to "base.go.kubebuilder.io/v3": **webhook resource already exists**`

### ISSUE THREAD

**Issue by ka-keung** [kubernetes-sigs/kubebuilder#2555]
You cannot scaffold twice, see the error `Error: failed to create webhook: unable to inject the resource to "base.go.kubebuilder.io/v3": **webhook resource already exists**`
However, it might be a bug: (I cannot find the `--conversion` one)

```
  webhooks:
    defaulting: true
    validation: true
    webhookVersion: v1
```

I am closing this one since this repo is for the issues faced with controller-gen/controller-tools. 
Could you please open this issue against the KB project: https://github.com/kubernetes-sigs/kubebuilder/issues

_Originally posted by @camilamacedo86 in https://github.com/kubernetes-sigs/controller-tools/issues/659#issuecomment-1073176794_

**Comment by ka-keung** [comment]
@camilamacedo86  yet, i know i cannot scaffold twice,but it was a conversion webhook. follow the book , i should scaffold conversion webhook for v2. isn't it ? otherwise . the v2 directory haven't `cronjob_webhook.go` and no paragraph webhooks on PROJECT file

**Comment by camilamacedo86** [comment]
Hi @ka-keung,

It is required to check here (imo):
- The docs, we need to verify if in the tutorial we are scaffolding defaulting,  validation and conversion (I do not think so)
- In the plugin, should we allow have webhooks with all options for the same API? Would that actually work? What happens if we have many webhooks for the same API?

also, anyway, we might find a hall for improvements in its error message and/or docs.

**Comment by ka-keung** [comment]
@camilamacedo86 

another question is happend. once i has success run `make install && make deploy`  on cronjob v1 step ; and then now i have to deploy v2  and run  `make install && make deploy` ; it stuck and no any other response:

```
make install
/opt/kubebuilder/bin/controller-gen rbac:roleName=manager-role crd:maxDescLen=0 webhook paths="./..." output:crd:artifacts:config=config/crd/bases
/opt/kubebuilder/bin/kustomize build config/crd | kubectl apply -f -
```
