### ISSUE TITLE
metadata.annotations: Too long: must have at most 262144 bytes

### ISSUE THREAD

**Issue by ka-keung** [kubernetes-sigs/kubebuilder#2556]
### What broke? What's expected?

clone this project on the machine, an go to dir docs/book/src/multiversion-tutorial/testdata/project . `make install deploy`; then this error appear
```
 make install deploy
/var/tmp/kubebuilder-master/docs/book/src/multiversion-tutorial/testdata/project/bin/controller-gen rbac:roleName=manager-role crd webhook paths="./..." output:crd:artifacts:config=config/crd/bases
/var/tmp/kubebuilder-master/docs/book/src/multiversion-tutorial/testdata/project/bin/kustomize build config/crd | kubectl apply -f -
The CustomResourceDefinition "cronjobs.batch.tutorial.kubebuilder.io" is invalid: metadata.annotations: Too long: must have at most 262144 bytes
make: *** [install] Error 1
```

### KubeBuilder (CLI) Version

3.3.0

### PROJECT version

3

### Other versions

k8s:   v1.21.9
go:    1.16.2
kustomize: v4.5.2
centos: 3.10.0-693.el7.x86_64

**Comment by camilamacedo86** [comment]
hI @ka-keung, 

It shows that you added an metadata.annotations which is bigger than the value supported by K8s API. Not sure how it could be solved via these project KB (which is a CLI to scaffolds the project ) or controller-gen (which will help scaffolds the manifest).

**Comment by ka-keung** [comment]
> 

i had't do nothing but clone this repository and go to the dir `docs/book/src/multiversion-tutorial/testdata/project`  run  `make install deploy`

**Comment by ka-keung** [comment]
> hI @ka-keung,
> 
> It shows that you added an metadata.annotations which is bigger than the value supported by K8s API. Not sure how it could be solved via these project KB (which is a CLI to scaffolds the project ) or controller-gen (which will help scaffolds the manifest).

@camilamacedo86  i had't do nothing but clone this repository and go to the dir docs/book/src/multiversion-tutorial/testdata/project run make install deploy

**Comment by camilamacedo86** [comment]
Could you please test with go: 1.17+ < 1.18 just for we ensure that is not related? 
Also, the kustomize: v4.5.2 is not the version scaffold on it (https://github.com/kubernetes-sigs/kubebuilder/blob/master/testdata/project-v3/Makefile#L116) and from v3 to v4 it has breaking changes 

See: 
- https://book.kubebuilder.io/quick-start.html#versions-and-supportability

**Comment by ka-keung** [comment]
try again with version:

go: v1.17.8
kustomize: 3.8.7
controller-gen: v0.8.0

same result~.

my step:
```
git clone https://github.com/kubernetes-sigs/kubebuilder.git
cd kubebuilder/docs/book/src/multiversion-tutorial/testdata/project
make install
```

**Comment by ka-keung** [comment]
> Could you please test with go: 1.17+ < 1.18 just for we ensure that is not related? Also, the kustomize: v4.5.2 is not the version scaffold on it (https://github.com/kubernetes-sigs/kubebuilder/blob/master/testdata/project-v3/Makefile#L116) and from v3 to v4 it has breaking changes
> 
> See:
> 
> * https://book.kubebuilder.io/quick-start.html#versions-and-supportability

1.  `CRD_OPTIONS ?= "crd:maxDescLen=0"` in Makefile not work. that's why
2.  modify  Makefile manifests target . change crd => crd:maxDescLen=0 ; then `make install`; it solved 
```

.PHONY: manifests
manifests: controller-gen ## Generate WebhookConfiguration, ClusterRole and CustomResourceDefinition objects.
	$(CONTROLLER_GEN) rbac:roleName=manager-role crd:maxDescLen=0 webhook paths="./..." output:crd:artifacts:config=config/crd/bases

```

**Comment by camilamacedo86** [comment]
So, we need to check here:
- why the description is too long in the book sample? Is it because we are adding comments for the docs and those are going to the manifests? 
- Can we fix it without removing the info from the docs? if not, then we might be able to just update the sample with the workaround found and a comment on top explaining why the  `crd:maxDescLen=0` was added. 

WDYT? @ka-keung would you like to help on this one?
Would you like to help us solve this issue?

**Comment by ka-keung** [comment]
thankyou for your answer. i also would like to improve  this project , but now . i need more deep learn to find out what happend in those action @camilamacedo86

**Comment by laxmikantbpandhare** [comment]
As this issue is inactive for a long time. I will fix this. I was able to recreate it locally.

**Comment by laxmikantbpandhare** [comment]
Hi @camilamacedo86 -

I was able to recreate the issue. There are two ways through which we can fix this issue.

1. As mentioned in the issue,  modify the Makefile manifests target. change crd => crd:maxDescLen=0;
2. Change `kubectl apply to `kubectl replace --force` as mentioned [here](https://github.com/bugfest/tor-controller/pull/18#issuecomment-1179899925)

Please take a look and let me know your thoughts.

**Comment by jobcespedes** [comment]
Just adding that `kubectl apply --server-side=true -f` avoids metadata byte limit

**Comment by lorenzophys** [comment]
I am following the book one to one and I got the same problem. Fixed by @ka-keung . 
This should be fixed asap since it's literally the tutorial

**Comment by rattboi** [comment]
Also just ran into this working my way through the tutorial. Definitely should be fixed asap

**Comment by STX5** [comment]
Same here, when following the tutorial https://book.kubebuilder.io/cronjob-tutorial/running

`make install `throws this erro message : `The CustomResourceDefinition "cronjobs.batch.tutorial.kubebuilder.io" is invalid: metadata.annotations: Too long: must have at most 262144 bytes`

**Comment by hantonelli** [comment]
Could this be fixed? Why is this issue closed?

**Comment by bmarick** [comment]
I was able to resolve this issue in the cronjob example by making the following changes.
However, I don't know if this actually fixes the issue.

File: **_docs/book/src/cronjob-tutorial/testdata/project/Makefile_**
Lines: 45-53

```diff
##@ Development

.PHONY: manifests
manifests: controller-gen ## Generate WebhookConfiguration, ClusterRole and CustomResourceDefinition objects.
-	$(CONTROLLER_GEN) rbac:roleName=manager-role crd webhook paths="./..." output:crd:artifacts:config=config/crd/bases
+	$(CONTROLLER_GEN) rbac:roleName=manager-role crd:maxDescLen=0 webhook paths="./..." output:crd:artifacts:config=config/crd/bases

.PHONY: generate
generate: controller-gen ## Generate code containing DeepCopy, DeepCopyInto, and DeepCopyObject method implementations.
	$(CONTROLLER_GEN) object:headerFile="hack/boilerplate.go.txt" paths="./..."
```

**Comment by NickPak** [comment]
I solved this problem by adding comments.

```
	// Specifies the job that will be created when executing a CronJob.
	// +kubebuilder:pruning:PreserveUnknownFields
	// +kubebuilder:validation:Schemaless
	JobTemplate batchv1.JobTemplateSpec `json:"jobTemplate"`
```

**Comment by ofey404** [comment]
I encountered this issue too.

**Comment by mwienk** [comment]
This seems to happen because the `kubectl apply` from the `make install` step adds the `kubectl.kubernetes.io/last-applied-configuration` annotation. You can circumvent this behaviour by using a server-side apply. In the Makefile, replace the install with:

```
.PHONY: install
install: manifests kustomize ## Install CRDs into the K8s cluster specified in ~/.kube/config.
	$(KUSTOMIZE) build config/crd | $(KUBECTL) apply --server-side -f -
```

**Comment by mwienk** [comment]
@camilamacedo86 I'd change 

```
In ideal approach might use client-side apply might seem like the perfect solution since with the entire object configuration doesn't have to be stored as an annotation (last-applied-configuration) on the server. However, it's worth noting...
``` 
into
```
Although using a server-side apply approach might seem like the perfect solution as we don't need to keep track of the `last-applied-configuration`, it's worth noting...
```

I'm not really sure what/how it isn't supported though, everything seems to work fine when I use a server-side apply

**Comment by suqinglee** [comment]
i avoid this by: `kubectl create -f config/crd/bases/*`

**Comment by stan-is-hate** [comment]
Why is this closed if it's still not resolved? By simply following the tutorial from the book to the letter you'd run into this issue, can the tutorial be updated?

**Comment by camilamacedo86** [comment]
Hi @stan-is-hate 

It is closed because it has already been addressed.

a) The reason why it happens is described at: https://book.kubebuilder.io/faq#the-error-too-long-must-have-at-most-262144-bytes-is-faced-when-i-run-make-install-to-apply-the-crd-manifests-how-to-solve-it-why-this-error-is-faced

b) For the tutorial, we removed the description of the CRDs so this error does not occur anymore. Example: https://github.com/kubernetes-sigs/kubebuilder/blob/8c048fff94da8cc846b7efa6a3958160eafd8294/docs/book/src/cronjob-tutorial/testdata/project/Makefile#L44-L51

Therefore, has nothing else for us to do here

**Comment by nickgolob** [comment]
FYI, even after updating [kubebuilder/docs/book/src/cronjob-tutorial/testdata/project/Makefile](https://github.com/kubernetes-sigs/kubebuilder/blob/8c048fff94da8cc846b7efa6a3958160eafd8294/docs/book/src/cronjob-tutorial/testdata/project/Makefile#L44-L51), the tutorial user will still encounter the errors, since the tutorial guides the user through making a project from scratch with the DEFAULT Makerfile..
