### ISSUE TITLE
Define and doc an standard for the PR titles to make clear specific plugins changes 

### ISSUE THREAD

**Issue by camilamacedo86** [kubernetes-sigs/kubebuilder#2557]
### What do you want to happen?

IMO: We need to discuss in the community meeting what standard we would like to have to make clear in the release notes that the changes made are valid only for some specific plugin (to be easier for users to have this information by looking at the release notes). Then, we need to doc it out in: https://github.com/kubernetes-sigs/kubebuilder/blob/master/CONTRIBUTING.md (to make clear for contributes how that need to be done, when and why)

See the release notes: https://github.com/kubernetes-sigs/kubebuilder/releases

Some options/suggestions:

- `<icon indicating whether it's a> ( plugin/version ) : <description>`
- `<icon indicating whether it's a>  For plugin/version, : <description>`

See how we do it in the templates to generate the release notes in SDK:

https://github.com/operator-framework/operator-sdk/blob/master/changelog/fragments/00-template.yaml#L10-L14

**Comment by mariuskimmina** [comment]
May I suggest the 🔌 `:electric_plug:` Icon? Seems fitting 😄

**Comment by camilamacedo86** [comment]
The icons are used to define bug fixes, breaking changes and etc:

Every PR should be annotated with an icon indicating whether it's
a:

- Breaking change: :warning: (`:warning:`)
- Non-breaking feature: :sparkles: (`:sparkles:`)
- Patch fix: :bug: (`:bug:`)
- Docs: :book: (`:book:`)
- Infra/Tests/Other: :seedling: (`:seedling:`)
- No release note: :ghost: (`:ghost:`)

Not sure how the  🔌 :electric_plug: Icon would fit in this case.

**Comment by camilamacedo86** [comment]
Teh goal is to define a standard for the releases notes which are Breaking changes, Patch fix, etc but that does affect the specific plugin and not all. See the examples in the release notes with (go/v2 or go/v3) for example:  https://github.com/kubernetes-sigs/kubebuilder/releases

**Comment by Ankit152** [comment]
Hey @camilamacedo86 🙂 
I can work on this if this issue is not assigned to anyone.

**Comment by camilamacedo86** [comment]
HI @Ankit152, 

We will need first to check with the Community what the standard should be and what they think about it. Then, we can move forward. I am hoping we have this conversation in the next KB / C+R meeting : https://docs.google.com/document/d/1Ih-2cgg1bUrLwLVTB9tADlPcVdgnuMNBGbUl4D-0TIk/edit#heading=h.dp4gt7gj3cn

**Comment by camilamacedo86** [comment]
Done, It is added in the contribution guide now.
