### ISSUE TITLE
Do we consider to release version for arm64 of darwin

### ISSUE THREAD

**Issue by vincent-pli** [kubernetes-sigs/kubebuilder#2558]
### What do you want to happen?

I get a `kubebuild` binary with the content "Not Found" when I try to get `kubebuilder` with command:
`curl -L -o kubebuilder https://go.kubebuilder.io/dl/latest/$(go env GOOS)/$(go env GOARCH)`

**Comment by camilamacedo86** [comment]
Hi @vincent-pli, 

We accepted the contribution https://github.com/kubernetes-sigs/kubebuilder/issues/2505.
For the next release, all are working fine as expected that will get generated. 
We should be doing a new release soon.

**Comment by vincent-pli** [comment]
Thanks @camilamacedo86
