### ISSUE TITLE
V2: Implement solution for managing Schemes

### ISSUE THREAD

**Issue by pwittrock** [kubernetes-sigs/kubebuilder#256]
The current controller-platform libraries use the kubernetes client-go `schema.Scheme`.  Users should actually create their own and add the kubernetes scheme to the one they create.

**Comment by lichuqiang** [comment]
Wondering how it integrates with the existing code. I think it's the users that pass the scheme in.
So, maybe an independent function to help users construct scheme?

**Comment by droot** [comment]
This is addressed, so closing it.
