### ISSUE TITLE
Kustomize v3 does not provide bin for mac (arm64)

### ISSUE THREAD

**Issue by camilamacedo86** [kubernetes-sigs/kubebuilder#2566]
### What broke? What's expected?

In order to support go 1.18 (https://github.com/kubernetes-sigs/kubebuilder/pull/2486) we change the Makefile:

```
KUSTOMIZE = $(shell pwd)/bin/kustomize
kustomize: ## Download kustomize locally if necessary.
	$(call go-get-tool,$(KUSTOMIZE),sigs.k8s.io/kustomize/kustomize/v3@v3.8.7)
```

To use the script:

```
KUSTOMIZE_INSTALL_SCRIPT ?= "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh"
.PHONY: kustomize
kustomize: $(KUSTOMIZE) ## Download kustomize locally if necessary.
$(KUSTOMIZE):
	curl -s $(KUSTOMIZE_INSTALL_SCRIPT) | bash -s -- $(subst v,,$(KUSTOMIZE_VERSION)) $(LOCALBIN)
```

However, the v3 versions do not provide darwin arm64 binaries:

See https://github.com/kubernetes-sigs/kustomize/releases/tag/kustomize%2Fv3.10.0. (latest)
But it is provided for v4: https://github.com/kubernetes-sigs/kustomize/releases/tag/kustomize%2Fv4.5.3

Then, we need to:
a) verify if we have not another option to install kustomize v3
OR
b) revisit the option to update to kustomize v4 (it has breaking changes, see:  https://github.com/kubernetes-sigs/kubebuilder/pull/2498#issuecomment-1026698929. Also, see https://github.com/kubernetes-sigs/kubebuilder/pull/2498#issuecomment-1026772984)

### KubeBuilder (CLI) Version

master

### PROJECT version

3

### Plugin versions

```yaml
Default version 3
```

### Extra Labels

/kind regression

**Comment by camilamacedo86** [comment]
@ryantking we need to check this one.
It blocks the release.

**Comment by SkYNewZ** [comment]
Hi. I cannot use the kustomize alpha plugin.

```
❯ kubebuilder init --plugins=base.go/v3,kustomize/v4-alpha
Error: no plugin could be resolved with key "kustomize/v4-alpha" (plugin version is unstable, there may be an upgrade available: https://kubebuilder.io/migration/plugin/plugins.html)
❯ kubebuilder version
Version: main.version{KubeBuilderVersion:"HEAD-8ec681a", KubernetesVendor:"unknown", GitCommit:"8ec681ae5a7bf3751e2539a7b7b4677c255f6a0f", BuildDate:"2022-06-20T11:56:04Z", GoOs:"darwin", GoArch:"arm64"}

```

**Comment by camilamacedo86** [comment]
Hi @SkYNewZ, 

The plugin is only available on master, to call it you --plugins="kustomize/v2-alpha,base.go.kubebuilder.io/v3" (not v4-alpha)

Also, see; https://github.com/kubernetes-sigs/kubebuilder/pull/2758
After we merge this one the stable plugin (default scaffold done with kubebuilder init) will have the bump. However, the syntax done for it will still use for example vars and not replacements which works from 4x only.

**Comment by SkYNewZ** [comment]
Thanks you @camilamacedo86 !
