### ISSUE TITLE
scaffolds hub and spoke interfaces for conversion webhooks.

### ISSUE THREAD

**Issue by camilamacedo86** [kubernetes-sigs/kubebuilder#2589]
### What do you want to happen?

scaffolds hub and spoke interfaces for conversion webhooks.
With this change, users can either specify --conversion flag and implement
the interface on their own, or specify --hub and --spoke versions which
will scaffold the skeleton code for both the interfaces.

Follow up/finish the work which started : https://github.com/kubernetes-sigs/kubebuilder/pull/2084

**Comment by NikhilSharmaWe** [comment]
@camilamacedo86 What do we need to do here? 

- Do we need to open a new PR with the changes done in https://github.com/kubernetes-sigs/kubebuilder/pull/2084, working on the suggested changes in the PR, and rebasing it?

**Comment by NikhilSharmaWe** [comment]
@camilamacedo86 Could you please take a look at my previous comment.

**Comment by camilamacedo86** [comment]
Sure. Please, feel free to work on this one.

**Comment by camilamacedo86** [comment]
Yes, the goal of this task is to finalize the implementation done in the https://github.com/kubernetes-sigs/kubebuilder/pull/2084. So, you can get the changes made and address the comments. 

IN this way, this one seems a good fit for the good first issue.

**Comment by momom-i** [comment]
@camilamacedo86 Is it already done? If not, I'd like to work on this!

**Comment by camilamacedo86** [comment]
Hi @momom-i.

It is not. Please, feel free to work on this one. 
Your collaboration is very welcome.

Thx.

**Comment by ashutosh887** [comment]
I don't think it's still resolved
I would like to work on this now

/assign

**Comment by momom-i** [comment]
@ashutosh887 I’m working on this now. 
/assign

**Comment by ashutosh887** [comment]
Sure @momom-i 
Please let me know if you need any help

**Comment by ashutosh887** [comment]
Let me work on this @camilamacedo86 if @momom-i is unable to resolve

**Comment by lauchokyip** [comment]
For anyone who is interested in working on this PR, IMHO, I do not think it's a `good-first-issue`. It requires good amount of knowledge for Go, cli and Kubernetes Webhook. You would also need to read the design proposals to come up with the best practice. **Simply copy and paste the OP's PR will not work**.

Estimated time from understanding to coding to open an PR and to get it merged would require at least a month of effort

**Comment by camilamacedo86** [comment]
It was good first issue when the effort was follow up the work done.
However, now it is no longer the case.
So, this one will be hard for anyone to take.
I am working on this.

**Comment by camilamacedo86** [comment]
Done
