### ISSUE TITLE
Creating a resource named 'Run' is not possible as it collides with internals. 

### ISSUE THREAD

**Issue by surbas** [kubernetes-sigs/kubebuilder#259]
Not sure what best solution is but if you attempt to create a resource named Run it is impossible to build a working controller manager.

Steps to reproduce:
`kubebuilder init --domain foo.com`
`kubebuilder create resource --group core --version v1alpha1 --kind Run`
`GOBIN=${PWD}/bin go install ${PWD#$GOPATH/src/}/cmd/controller-manager`

OUTPUT:
> \#core/pkg/inject
> pkg/inject/zz_generated.kubebuilder.go:48:59: undefined: "core/pkg/controller/run".RunArguments

**Comment by Liujingfang1** [comment]
The problem comes from the name `Run`. Can you change it to a different name?

**Comment by surbas** [comment]
@Liujingfang1 already have :). Reporting this cause I think there may be a need to either blacklist certain names like `Run` or have kubebuilder mangle its internal namespace so naming collisions are harder. This of course may be the only name that causes this... so maybe a documentation fix is all that needed?

**Comment by pwittrock** [comment]
@surbas Thanks.  This should be addressed when we integrate the https://github.com/kubernetes-sigs/controller-runtime libraries.

**Comment by surbas** [comment]
Verified this is not an issue any more in v1! Closing.
