### ISSUE TITLE
[ci] - Stop to run all tests when changes are only in the docs

### ISSUE THREAD

**Issue by camilamacedo86** [kubernetes-sigs/kubebuilder#2591]
### What do you want to happen?

Currently, if we change a doc we still running all test
The goal of this task is to skip when possible the tests when the change is performed only in the MD files.

**Comment by NikhilSharmaWe** [comment]
@camilamacedo86 What is the approach for solving this kind of issue with testing? 
Could you please provide some code pointers for adding this feature.

**Comment by camilamacedo86** [comment]
You would need to check what files changed  ( git diff. ) then if is only files with the extension `*.md` you can ignore some jobs. In SDK we do that, see:
- we skip the job in the GitHub Action when we check that only docs were changed : https://github.com/operator-framework/operator-sdk/blob/master/.github/workflows/test-go.yml#L10
- See how: https://github.com/operator-framework/operator-sdk/blob/master/.github/workflows/test-go.yml#L15-L21
- look the shell: https://github.com/operator-framework/operator-sdk/blob/master/.github/workflows/check-docs-only.sh

**Comment by camilamacedo86** [comment]
We skipped the jobs in the Github actions. However, to skip the prow tests we probably need/to change the configure into the prow jobs it seems more complex.

The motivation here would try to spend a low effort for we do not do the test when not required and make things faster but the effort vs benefit to doing it does not seem to pay. Thank you @NikhilSharmaWe for investigating this one.

As we spoke seems that we can close this one as done ( where we could easily achieve the goal )
therefore in the future if we have a need that justifies this effort we can try to work on this again.
