### ISSUE TITLE
(For go/v3) : Add README template bollerplate 

### ISSUE THREAD

**Issue by camilamacedo86** [kubernetes-sigs/kubebuilder#2597]
### What do you want to happen?

This suggestion came from new users. The idea would be to provide by default a README to the projects so that, we could:
- encourage authors to create the README.md
- provide on the README.md the default make file targets and help skill up on how to use it 
- additionally, for other projects such as SDK which uses KB as lib and adds on top nice helpers; would be possible for it to supplement the README with default info such as "how to build/update and test the bundle with OLM"

Then, the suggested solution for Kubebuilder would be something like this: 

```
# <project-name>

// TODO(user): Add simple overview of use/purpose.

## Description

// TODO(user): An in-depth paragraph about your project and overview of use.

## Getting Started

Here could add all steps to run the project locally with the default make targets commands - see the KB quick start

**NOTE:** Run `make --help` to check all available targets. 

## Contributing 

### How it works

Maybe something like 

This project aims to follow the [Operator pattern](https://kubernetes.io/docs/concepts/extend-kubernetes/operator/) by creating [Controllers](https://kubernetes.io/docs/concepts/architecture/controller/) which provides a reconcile function responsible for synchronizing resources until the desired state is reached on the cluster. 

## License

We can scaffold here what comes from the boilerplate: https://github.com/kubernetes-sigs/kubebuilder/blob/master/pkg/plugins/golang/v3/scaffolds/internal/templates/hack/boilerplate.go
```

**Comment by everettraven** [comment]
Hi @camilamacedo86, I'd love to pick this issue up!
