### ISSUE TITLE
why my log time output is 1.649403363838766e+09

### ISSUE THREAD

**Issue by acechef** [kubernetes-sigs/kubebuilder#2606]
### What broke? What's expected?

why my log time output is 1.649403363838766e+09，how can I make it human readable

### KubeBuilder (CLI) Version

Version: main.version{KubeBuilderVersion:"3.3.0", KubernetesVendor:"unknown", GitCommit:"47859bf2ebf96a64db69a2f7074ffdec7f15c1ec", BuildDate:"2022-01-17T18:05:10Z", GoOs:"darwin", GoArch:"arm64"}

**Comment by camilamacedo86** [comment]
See that the logs are configured in the main.go: https://github.com/kubernetes-sigs/kubebuilder/blob/master/testdata/project-v3/main.go#L60-L62

So, you need to check the options to format the output as please you provided by zap lib.

Closing. this one. But feel free to re-open or raise others if you need.

**Comment by Hanyu96** [comment]
So how should I change it...

**Comment by Hanyu96** [comment]
```
	opts := zap.Options{
		Development: true,
		TimeEncoder: zapcore.ISO8601TimeEncoder,
	}
```

**Comment by acechef** [comment]
> ```
> 	opts := zap.Options{
> 		Development: true,
> 		TimeEncoder: zapcore.ISO8601TimeEncoder,
> 	}
> ```

OK, let me try
