### ISSUE TITLE
Unable to create new API in existing project if controller is for K8s resource

### ISSUE THREAD

**Issue by erikgb** [kubernetes-sigs/kubebuilder#2609]
### What broke? What's expected?

Trying to add a new API and controller in existing project using kubebuilder. The project currently contains **no APIs** and just one controller for K8s `v1.ServiceAccount`.

Trying to create the API using the command: `kubebuilder create api --group stas --version v1alpha1 --kind ClientCertificate` results in error message `failed to create API: unable to inject the resource to "base.go.kubebuilder.io/v3": multiple groups are not allowed by default, to enable multi-group visit https://kubebuilder.io/migration/multi-group.html`.

After having a look at the referenced docs, I try to run the command: `kubebuilder edit --multigroup=true` which results in the error message `failed to edit project: unable to scaffold with "base.go.kubebuilder.io/v3": can't find "COPY api/ api/"`

Expected behavior: The last command is successful, and the project is successfully migrated to multigroup layout.

### KubeBuilder (CLI) Version

3.3.0

### PROJECT version

3

### Plugin versions

```yaml
- go.kubebuilder.io/v3
```

**Comment by camilamacedo86** [comment]
The default scaffold has the line: https://github.com/kubernetes-sigs/kubebuilder/blob/master/testdata/project-v3/Dockerfile#L14 which was not found. 

Did you change that? 
Could you please share the project and your dockerfile file content?

**Comment by erikgb** [comment]
Yes, you are absolutely correct. I didn't realize that the error originates from my modifications of `Dockerfile`. Closing issue as invalid.
