### ISSUE TITLE
kubebuilder docs fails

### ISSUE THREAD

**Issue by lionelvillard** [kubernetes-sigs/kubebuilder#261]
I follow the quick start API documentation instructions and I get this error:

```
Unable to find image 'gcr.io/kubebuilder/brodocs:v0.1.11' locally
docker: Error response from daemon: manifest for gcr.io/kubebuilder/brodocs:v0.1.11 not found.
```

I tried installing `pwittrock/brodocs` from dockerhub, but no luck.

**Comment by pwittrock** [comment]
@lionelvillard looks like the image didn't get pushed.  I just pushed it and it should work now.  Re-open if there are any permissions issues.
