### ISSUE TITLE
Add support for go 1.17 and 1.18 in generated Makefile

### ISSUE THREAD

**Issue by fjammes** [kubernetes-sigs/kubebuilder#2613]
### What do you want to happen?

Starting in Go 1.17, installing executables with `go get` is deprecated. `go install` may be used instead, see https://go.dev/doc/go-get-install-deprecation.

`go-get-tools` macro in `pkg/plugins/golang/v3/scaffolds/internal/templates/makefile.go` should be update in order to use `go install`

**Comment by NikhilSharmaWe** [comment]
@fjammes I think that `go get` has been updated to use `go install` instead in `pkg/plugins/golang/v3/scaffolds/internal/templates/makefile.go` through this [commit](https://github.com/kubernetes-sigs/kubebuilder/commit/b0c7cd8cc17e5dcc48f314439f2c35a47da257a2). Could you please explain if I am not understanding the issue.

**Comment by camilamacedo86** [comment]
It will be available for the next release.
So far, kubebuilder does not support 1.18 and also see that the deps and go versions scaffold when we create a new project are with go 1.17. It is tracked already either for we upgrade all. 

So I am closing this one as sorted. However, please feel free to raise new issues if you see that you need or re-open this one.
