### ISSUE TITLE
Generated informer import uses wrong repo

### ISSUE THREAD

**Issue by grantr** [kubernetes-sigs/kubebuilder#262]
I have two resources defined: Foo and Bar. Each one was generated by `kubebuilder create resource`.

My Foo controller needs to list Bar resources, so I want to give it a Bar informer. I used these annotations:

```go
// +kubebuilder:controller:group=mygroup,version=v1alpha1,kind=Foo,resource=foos
// +kubebuilder:rbac:groups=mygroup,resources=bars,verbs=get;watch;list
// +kubebuilder:informers:group=mygroup,version=v1alpha1,kind=Bar
 type FooController struct {
```

The import path for the Bar informer is in my repo, so I expect this to generate an import like this:

```go
import (
  mygroupv1alpha1 "github.com/grantr/myrepo/pkg/apis/mygroup/v1alpha1"
)
```

But instead the generated import is:

```go
mygroupv1alpha1 "k8s.io/api/mygroup/v1alpha1"
```

Am I holding it wrong?

cc @pwittrock @mattmoor

**Comment by grantr** [comment]
I just realized the informers for all generated controllers are automatically instantiated, so the example above is sort of moot since there's no need to declare an informer (though the docs should be updated to make this clearer).

However, this is still an issue when importing resource types from other repositories. In my case, I use CRDs from Istio. I don't need to define a controller for these types, but I'd like to be able to generate informer instantiations and RBAC rules for them.

**Comment by droot** [comment]
> However, this is still an issue when importing resource types from other repositories. In my case, I use CRDs from Istio. I don't need to define a controller for these types, but I'd like to be able to generate informer instantiations and RBAC rules for them.

new `client` package in [controller-runtime](https://github.com/kubernetes-sigs/controller-runtime/tree/master/pkg/client) makes it easy to use k8s API types, you just need to import the `type` package (core or non-core doesn't matter) and it sets up the informer etc for you. Re: RBAC, we are coming up with piece-wise tooling which will help to generate just RBAC, CRD or config yaml etc. without having to use the other pieces.

**Comment by droot** [comment]
This should no longer be an issue with the new version of Kubebuilder, so closing it.
