### ISSUE TITLE
Kustomize Bin Not Downloading

### ISSUE THREAD

**Issue by moza88** [kubernetes-sigs/kubebuilder#2621]
### What broke? What's expected?

When I run make install it should add the Kustomize script to my bin folder and install my project.

### Reproducing this issue

I believe the order of running commands makes a huge difference.

The commands I ran were:
make all
make manifests
make generate
make build
make run

It can run fine, but when I try to install it, it has issues because it's missing kustomize in the bin folder. 

### KubeBuilder (CLI) Version

Version: main.version{KubeBuilderVersion:"3.3.0", KubernetesVendor:"1.23.1", GitCommit:"47859bf2ebf96a64db69a2f7074ffdec7f15c1ec", BuildDate:"2022-01-18T17:03:29Z", GoOs:"darwin", GoArch:"amd64"}

### PROJECT version

3

### Plugin versions

```yaml
- go.kubebuilder.io/v3
```

### Other versions

**go Version**: go version go1.18 darwin/amd64
**Controller-Runtime**: sigs.k8s.io/controller-runtime v0.11.0
**Kubernetes Version**

Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.5", GitCommit:"c285e781331a3785a7f436042c65c5641ce8a9e9", GitTreeState:"clean", BuildDate:"2022-03-16T15:51:05Z", GoVersion:"go1.17.8", Compiler:"gc", Platform:"darwin/amd64"}

Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.3", GitCommit:"816c97ab8cff8a1c72eccca1026f7820e93e0d25", GitTreeState:"clean", BuildDate:"2022-01-25T21:19:12Z", GoVersion:"go1.17.6", Compiler:"gc", Platform:"linux/amd64"}

**Comment by Sijoma** [comment]
This comes from the fact that Go 1.18 is used. Go 1.18 is not yet supported as far as I know.

**Comment by camilamacedo86** [comment]
The go version 1.18 is not supported yet.
So, it will not work with 1.18. If you are using the latest release then the go version compatible is 1.17+ < 1.18.

Closing this one as duplicated since we have an issue tracked already to add support for 1.18.

**Comment by moza88** [comment]
Just switching over to go 1.17 and running make install did the trick, thank you!
