### ISSUE TITLE
failed to initialize project: unable to scaffold with "base.go.kubebuilder.io/v3": exit status 1

### ISSUE THREAD

**Issue by twilight0620** [kubernetes-sigs/kubebuilder#2622]
### What broke? What's expected?

when i create project, it has error:
failed to initialize project: unable to scaffold with "base.go.kubebuilder.io/v3": exit status 1

I think the version is suitable according to the Quick Start docs, here is my software version:
go version go1.18.1 linux/amd64
KubeBuilderVersion:"3.3.0",
Docker Engine - Community  Version:    20.10.14
kubectl version:v1.23.5
gcc version 9.3.0 

And could anyone can help resolve the problem?

### KubeBuilder (CLI) Version

3.3.0

**Comment by SummerSunFlower** [comment]
@twilight0620 I have the same problem.Can you share the solution .

**Comment by twilight0620** [comment]
> @twilight0620 I have the same problem.Can you share the solution .

they do not support go version 1.18+, you can use the version 1.17+
