### ISSUE TITLE
go version not supprot 1.18, but docs does not say it.

### ISSUE THREAD

**Issue by twilight0620** [kubernetes-sigs/kubebuilder#2623]
### What broke? What's expected?

https://book.kubebuilder.io/quick-start.html#create-a-project:
go version v1.17+ (kubebuilder v3.3+)
it says go version 1.17+， but go 1.18 is not support yet, it should be explained in docs.

### KubeBuilder (CLI) Version

3.3.0

**Comment by camilamacedo86** [comment]
Hi @twilight0620, 

Would you like to collab with this one and update the docs? 
Could you check if it is updated on master?

**Comment by twilight0620** [comment]
ok i will add it to docs.
/assign
