### ISSUE TITLE
loop print the message Failed to watch resource after Reconcile completed create CR.

### ISSUE THREAD

**Issue by Telzeng** [kubernetes-sigs/kubebuilder#2629]
### What broke? What's expected?

Hi,

loop print the message Failed to watch resource after Reconcile completed create CR.

After the function Reconcile is completed create CR, found the log loop print the message like the following. During the reconciliation, it created one deployment and job resource successful.

Expected:
The message seems to be unuseful. how to remove them.

Thanks

0421 09:15:27.612725       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.23.0/tools/cache/reflector.go:167: Failed to watch *v1.Deployment: unknown (get deployments.apps)
E0421 09:15:29.486701       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.23.0/tools/cache/reflector.go:167: Failed to watch *v1.Deployment: unknown (get deployments.apps)
E0421 09:15:34.309882       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.23.0/tools/cache/reflector.go:167: Failed to watch *v1.Deployment: unknown (get deployments.apps)
E0421 09:15:42.339820       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.23.0/tools/cache/reflector.go:167: Failed to watch *v1.Deployment: unknown (get deployments.apps)
E0421 09:16:07.264970       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.23.0/tools/cache/reflector.go:167: Failed to watch *v1.Deployment: unknown (get deployments.apps)
E0421 09:16:15.993145       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.23.0/tools/cache/reflector.go:167: Failed to watch *v1.Job: unknown (get jobs.batch)

### KubeBuilder (CLI) Version

Version: main.version{KubeBuilderVersion:"3.2.0", KubernetesVendor:"1.22.1", GitCommit:"b7a730c84495122a14a0faff95e9e9615fffbfc5", BuildDate:"2021-10-29T18:32:16Z", GoOs:"linux", GoArch:"amd64"}

### Extra Labels

/kind feature

**Comment by camilamacedo86** [comment]
Hi @Telzeng,

The message cames from the client-go ( dep ), see: https://github.com/kubernetes/client-go/issues/829
It seems that you have no permissions to watch the deployments.apps.

Note that you must use the markers (https://book.kubebuilder.io/reference/markers.html) and run make generate then the controller-gen will generated the RBAC permissions to allow you to watch.

See the sample generated with the plugin deploy-image: https://github.com/kubernetes-sigs/kubebuilder/blob/master/testdata/project-v3-with-deploy-image/controllers/memcached_controller.go#L43-L51

In this way, I am closing this one. However, feel free to re-open or create new ones if you need.
