### ISSUE TITLE
InsertCode should return error when target is not found

### ISSUE THREAD

**Issue by asmacdo** [kubernetes-sigs/kubebuilder#2639]
### What broke? What's expected?

https://github.com/kubernetes-sigs/kubebuilder/blob/master/pkg/plugin/util/util.go#L74

If the target is not found, `strings.Index(string(contents), target)` returns -1 rather than an error, and kubebuilder proceeds to insert the code prior to the last character.

### KubeBuilder (CLI) Version

3.3.0

### PROJECT version

NA

### Plugin versions

```yaml
NA
```

**Comment by camilamacedo86** [comment]
That makes sense to me. Would you like to push the fix? 
WDYT?

**Comment by NikhilSharmaWe** [comment]
I would like to work on this issue. 
@camilamacedo86 Could you please inform me if I can.

**Comment by NikhilSharmaWe** [comment]
I would like to work on this.
/assign
