### ISSUE TITLE
Generated controllers don't match samples

### ISSUE THREAD

**Issue by grantr** [kubernetes-sigs/kubebuilder#264]
When I generate a controller with kubebuilder 0.1.11, I get this struct:

```go
type FooController struct {
	// INSERT ADDITIONAL FIELDS HERE
	fooLister mygroupv1alpha1lister.FooLister
	fooclient mygroupv1alpha1client.MyGroupV1alpha1Interface
	// recorder is an event recorder for recording Event resources to the
	// Kubernetes API.
	foorecorder record.EventRecorder
}
```

But the samples at https://github.com/kubernetes-sigs/kubebuilder/blob/10fc5c79a2a572b0d0898b1464708750f9d8dd8c/samples/full/controller/src/samplecontroller/pkg/controller/foo/controller.go and https://github.com/kubernetes-sigs/kubebuilder/blob/10fc5c79a2a572b0d0898b1464708750f9d8dd8c/samples/controller/controller.go use a different struct:

```go
// Controller is the controller implementation for Foo resources
type Controller struct {
	args.InjectArgs

	// recorder is an event recorder for recording Event resources to the
	// Kubernetes API.
	recorder record.EventRecorder
}
```

It looks like #132 changed the generated controllers but didn't update the samples.

What's the rationale for changing the generated controllers? Was there a problem with the old style?

**Comment by pwittrock** [comment]
@grantr There was some feedback that the new format was simpler and required less editing of boilerplate.

**Comment by pwittrock** [comment]
Will address this as part of integrating the https://github.com/kubernetes-sigs/controller-runtime libraries.

**Comment by droot** [comment]
This is outdated, so closing this bug.
