### ISSUE TITLE
Ability to specify `main.go` location

### ISSUE THREAD

**Issue by AlmogBaku** [kubernetes-sigs/kubebuilder#2640]
### What do you want to happen?

It could be nice to specify the location of the `main.go` file, ideally in the `PROJECT` file.

Many times, in large projects - things become complex and developers change the layout to `cmd/xxx/main.go`.
Allowing to specify the location could be helpful for these use-cases.

**Comment by camilamacedo86** [comment]
Hi @AlmogBaku,

I hope that you do not mind. I am closing this one in favor of https://github.com/kubernetes-sigs/kubebuilder/issues/932. ( it is duplicated )

The above task is created to allow us to provide a feature where would be possible customize the path of what is scaffolded by default.
