### ISSUE TITLE
make-test doesn't return full coverage after webhook boilerplate code is generated

### ISSUE THREAD

**Issue by Sher-Chowdhury** [kubernetes-sigs/kubebuilder#2645]
### What broke? What's expected?

It looks like I lose 100% unit test coverage right after I generate the webhook boilerplate code:

```
$ make test
/Users/sherchowdhury/operators/mysql-operator/bin/controller-gen rbac:roleName=manager-role crd webhook paths="./..." output:crd:artifacts:config=config/crd/bases
/Users/sherchowdhury/operators/mysql-operator/bin/controller-gen object:headerFile="hack/boilerplate.go.txt" paths="./..."
go fmt ./...
go vet ./...
KUBEBUILDER_ASSETS="/Users/sherchowdhury/Library/Application Support/io.kubebuilder.envtest/k8s/1.23.3-darwin-amd64" go test ./... -coverprofile cover.out
?       github.com/Sher-Chowdhury/mysql-operator        [no test files]
?       github.com/Sher-Chowdhury/mysql-operator/api/v1 [no test files]
ok      github.com/Sher-Chowdhury/mysql-operator/controllers    6.707s  coverage: 100.0% of statements


$ kubebuilder create webhook --group wordpress --version v1 --kind Mysql --defaulting --programmatic-validation 
Writing kustomize manifests for you to edit...
Writing scaffold for you to edit...
api/v1/mysql_webhook.go
Update dependencies:
$ go mod tidy
Running make:
$ make generate
/Users/sherchowdhury/operators/mysql-operator/bin/controller-gen object:headerFile="hack/boilerplate.go.txt" paths="./..."
Next: implement your new Webhook and generate the manifests with:
$ make manifests


$ make test                                                                                                     
/Users/sherchowdhury/operators/mysql-operator/bin/controller-gen rbac:roleName=manager-role crd webhook paths="./..." output:crd:artifacts:config=config/crd/bases
/Users/sherchowdhury/operators/mysql-operator/bin/controller-gen object:headerFile="hack/boilerplate.go.txt" paths="./..."
go fmt ./...
go vet ./...
KUBEBUILDER_ASSETS="/Users/sherchowdhury/Library/Application Support/io.kubebuilder.envtest/k8s/1.23.3-darwin-amd64" go test ./... -coverprofile cover.out
?       github.com/Sher-Chowdhury/mysql-operator        [no test files]
ok      github.com/Sher-Chowdhury/mysql-operator/api/v1 5.663s  coverage: 3.5% of statements
ok      github.com/Sher-Chowdhury/mysql-operator/controllers    6.201s  coverage: 100.0% of statements
```

For me, the bug is that for the `api/v1` folder it should be showing "100%", not 3.5%. 

It looks like it's because there are no tests that covers the `zz_generated.deepcopy.go` file. Although I'm a bit confused why this is happening in the first place, since I didn't add a zz_generated.deepcopy_test.go, so thought that autogenerated file should have got ignored during the `go test` run.

FYI, these are the two webhook boilerplate files that got added to the `api/v1` folder:

```
ls -l api/v1/
total 40
-rw-r--r--  1 sherchowdhury  staff  1218 21 Apr 19:04 groupversion_info.go
-rw-r--r--  1 sherchowdhury  staff  2365 21 Apr 19:04 mysql_types.go
-rw-------  1 sherchowdhury  staff  2720 28 Apr 14:18 mysql_webhook.go                    <= this one
-rw-------  1 sherchowdhury  staff  3712 28 Apr 14:18 webhook_suite_test.go             <= this one
-rw-r--r--  1 sherchowdhury  staff  3698 28 Apr 14:18 zz_generated.deepcopy.go
```

If I just delete the `rm api/v1/webhook_suite_test.go` and run `make test` again, then I get 100% (because of "[no test files]"):

```
$ rm api/v1/webhook_suite_test.go 

$ make test                                                                                                    
/Users/sherchowdhury/operators/mysql-operator/bin/controller-gen rbac:roleName=manager-role crd webhook paths="./..." output:crd:artifacts:config=config/crd/bases
/Users/sherchowdhury/operators/mysql-operator/bin/controller-gen object:headerFile="hack/boilerplate.go.txt" paths="./..."
go fmt ./...
go vet ./...
KUBEBUILDER_ASSETS="/Users/sherchowdhury/Library/Application Support/io.kubebuilder.envtest/k8s/1.23.3-darwin-amd64" go test ./... -coverprofile cover.out
?       github.com/Sher-Chowdhury/mysql-operator        [no test files]
?       github.com/Sher-Chowdhury/mysql-operator/api/v1 [no test files]
ok      github.com/Sher-Chowdhury/mysql-operator/controllers    6.610s  coverage: 100.0% of statements
``` 

So it seems to me that as soon as a `*_test.go` file is added to the `api/v1`, the `zz_generated.deepcopy.go` automatically get's check for coverage. 

My setup:

```
$ kubebuilder version                                                                                           
Version: main.version{KubeBuilderVersion:"3.3.0", KubernetesVendor:"1.23.1", GitCommit:"47859bf2ebf96a64db69a2f7074ffdec7f15c1ec", BuildDate:"2022-01-18T17:03:29Z", GoOs:"darwin", GoArch:"amd64"}

$ go version  
go version go1.17.8 darwin/amd64
```

### KubeBuilder (CLI) Version

3.3.0

### PROJECT version

version: "3"

### Other versions

$ go version  
go version go1.17.8 darwin/amd64

sigs.k8s.io/controller-runtime v0.11.0

kubectl version --short
Client Version: v1.22.1
Server Version: v1.22.3+ffbb954

**Comment by camilamacedo86** [comment]
Hi @Sher-Chowdhury,

That makes sense for me since the files like `zz_generated.deepcopy.go` are auto-generate.
The fix here shows we change the default scaffold to ignore these files in the coverage. 

You can check in Kubebuilder Makefile that we also ignore some files to this check.
So, WDYT? Would you like to push a PR with this change?
Could you contribute to this fix?

**Comment by Sher-Chowdhury** [comment]
@camilamacedo86 I can't find any examples of where files are set to be ignored in the Kubebuilder's make file. Also the make-target in question is:

```
.PHONY: test
test: manifests generate fmt vet envtest ## Run tests.
        KUBEBUILDER_ASSETS="$(shell $(ENVTEST) use $(ENVTEST_K8S_VERSION) -p path)" go test ./... -coverprofile cover.out
```


I thought one option would be to replace `test ./...` with `go test $(shell shell find . -type f -name "*.go" | grep -v zz_generated.deepcopy.go)`. But this time I geet this error:

```
make test
...
named files must all be in one directory; have ./mocks/ and ./test/
make: *** [test] Error 1
```

I think one possible solution could be to use tags - https://mickey.dev/posts/go-build-tags-testing/

But I couldn't get this tagging approach to work yet.

**Comment by NikhilSharmaWe** [comment]
@camilamacedo86 Is this approach reasonable?
- Add `// +build !skip` at top of [zz_generated.deepcopy.go](https://github.com/kubernetes-sigs/kubebuilder/blob/master/testdata/project-v3/api/v1/zz_generated.deepcopy.go) and add use `-t skip` in go test in the makefile. Please inform if this approach reasonable.

I have already made changes https://github.com/kubernetes-sigs/kubebuilder/pull/2668 to deal with the test coverage, please inform me whether the changes made are reasonable or not.

**Comment by Sher-Chowdhury** [comment]
@NikhilSharmaWe that `skip` tag approach sounds ideal to me. 

I tried something very similar. There's already a `// !ignore_autogenerated` at the top of the [zz_generated.deepcopy.go](https://github.com/kubernetes-sigs/kubebuilder/blob/master/testdata/project-v3/api/v1/zz_generated.deepcopy.go) So I tried using `-t ignore_autogenerated` but it didn't seem to work for me. I suspect it's something I'm doing wrong.

**Comment by camilamacedo86** [comment]
Hi @Sher-Chowdhury, 

I was looking at this case better. I understand that you desired to exclude from the coverage files that you do not need unit tests because they are autogenerated, and I can go along with the idea.

However, see that the generated files are required to implement the APIs, so we will be unable to exclude them from the test.  Also, Golang does not allow us to exclude files only from the coverage and not from the tests themselves. 

You can create a target or customize the Makefile of your project with @NikhilSharmaWe suggestion:

```
test-coverage: ## Run unit tests creating the output to report coverage
	cat cover.out | grep -v "zz_generated.deepcopy.go" > cover.out.tmp
	go tool cover -func cover.out
```

Then it will result in: 

```
$ make test-coverage
cat cover.out | grep -v "zz_generated.deepcopy.go" > cover.out.tmp
go tool cover -func cover.out
sigs.k8s.io/kubebuilder/testdata/project-v3/api/v1/admiral_types.go:63:			init		100.0%
sigs.k8s.io/kubebuilder/testdata/project-v3/api/v1/admiral_webhook.go:28:		SetupWebhookWithManager	100.0%
sigs.k8s.io/kubebuilder/testdata/project-v3/api/v1/admiral_webhook.go:41:		Default		0.0%
sigs.k8s.io/kubebuilder/testdata/project-v3/api/v1/captain_types.go:62:			init		100.0%
sigs.k8s.io/kubebuilder/testdata/project-v3/api/v1/captain_webhook.go:29:		SetupWebhookWithManager	100.0%
sigs.k8s.io/kubebuilder/testdata/project-v3/api/v1/captain_webhook.go:42:		Default		0.0%
sigs.k8s.io/kubebuilder/testdata/project-v3/api/v1/captain_webhook.go:54:		ValidateCreate	0.0%
sigs.k8s.io/kubebuilder/testdata/project-v3/api/v1/captain_webhook.go:62:		ValidateUpdate	0.0%
sigs.k8s.io/kubebuilder/testdata/project-v3/api/v1/captain_webhook.go:70:		ValidateDelete	0.0%
sigs.k8s.io/kubebuilder/testdata/project-v3/api/v1/firstmate_types.go:62:		init		100.0%
sigs.k8s.io/kubebuilder/testdata/project-v3/api/v1/firstmate_webhook.go:27:		SetupWebhookWithManager	0.0%
sigs.k8s.io/kubebuilder/testdata/project-v3/api/v1/zz_generated.deepcopy.go:29:		DeepCopyInto	0.0%
sigs.k8s.io/kubebuilder/testdata/project-v3/api/v1/zz_generated.deepcopy.go:38:		DeepCopy	0.0%
sigs.k8s.io/kubebuilder/testdata/project-v3/api/v1/zz_generated.deepcopy.go:48:		DeepCopyObject	0.0%
sigs.k8s.io/kubebuilder/testdata/project-v3/api/v1/zz_generated.deepcopy.go:56:		DeepCopyInto	0.0%
sigs.k8s.io/kubebuilder/testdata/project-v3/api/v1/zz_generated.deepcopy.go:70:		DeepCopy	0.0%
sigs.k8s.io/kubebuilder/testdata/project-v3/api/v1/zz_generated.deepcopy.go:80:		DeepCopyObject	0.0%
sigs.k8s.io/kubebuilder/testdata/project-v3/api/v1/zz_generated.deepcopy.go:88:		DeepCopyInto	0.0%
sigs.k8s.io/kubebuilder/testdata/project-v3/api/v1/zz_generated.deepcopy.go:93:		DeepCopy	0.0%
sigs.k8s.io/kubebuilder/testdata/project-v3/api/v1/zz_generated.deepcopy.go:103:	DeepCopyInto	0.0%
sigs.k8s.io/kubebuilder/testdata/project-v3/api/v1/zz_generated.deepcopy.go:108:	DeepCopy	0.0%
sigs.k8s.io/kubebuilder/testdata/project-v3/api/v1/zz_generated.deepcopy.go:118:	DeepCopyInto	0.0%
sigs.k8s.io/kubebuilder/testdata/project-v3/api/v1/zz_generated.deepcopy.go:127:	DeepCopy	0.0%
sigs.k8s.io/kubebuilder/testdata/project-v3/api/v1/zz_generated.deepcopy.go:137:	DeepCopyObject	0.0%
sigs.k8s.io/kubebuilder/testdata/project-v3/api/v1/zz_generated.deepcopy.go:145:	DeepCopyInto	0.0%
sigs.k8s.io/kubebuilder/testdata/project-v3/api/v1/zz_generated.deepcopy.go:159:	DeepCopy	0.0%
sigs.k8s.io/kubebuilder/testdata/project-v3/api/v1/zz_generated.deepcopy.go:169:	DeepCopyObject	0.0%
sigs.k8s.io/kubebuilder/testdata/project-v3/api/v1/zz_generated.deepcopy.go:177:	DeepCopyInto	0.0%
sigs.k8s.io/kubebuilder/testdata/project-v3/api/v1/zz_generated.deepcopy.go:182:	DeepCopy	0.0%
sigs.k8s.io/kubebuilder/testdata/project-v3/api/v1/zz_generated.deepcopy.go:192:	DeepCopyInto	0.0%
sigs.k8s.io/kubebuilder/testdata/project-v3/api/v1/zz_generated.deepcopy.go:197:	DeepCopy	0.0%
sigs.k8s.io/kubebuilder/testdata/project-v3/api/v1/zz_generated.deepcopy.go:207:	DeepCopyInto	0.0%
sigs.k8s.io/kubebuilder/testdata/project-v3/api/v1/zz_generated.deepcopy.go:216:	DeepCopy	0.0%
sigs.k8s.io/kubebuilder/testdata/project-v3/api/v1/zz_generated.deepcopy.go:226:	DeepCopyObject	0.0%
sigs.k8s.io/kubebuilder/testdata/project-v3/api/v1/zz_generated.deepcopy.go:234:	DeepCopyInto	0.0%
sigs.k8s.io/kubebuilder/testdata/project-v3/api/v1/zz_generated.deepcopy.go:248:	DeepCopy	0.0%
sigs.k8s.io/kubebuilder/testdata/project-v3/api/v1/zz_generated.deepcopy.go:258:	DeepCopyObject	0.0%
sigs.k8s.io/kubebuilder/testdata/project-v3/api/v1/zz_generated.deepcopy.go:266:	DeepCopyInto	0.0%
sigs.k8s.io/kubebuilder/testdata/project-v3/api/v1/zz_generated.deepcopy.go:271:	DeepCopy	0.0%
sigs.k8s.io/kubebuilder/testdata/project-v3/api/v1/zz_generated.deepcopy.go:281:	DeepCopyInto	0.0%
sigs.k8s.io/kubebuilder/testdata/project-v3/api/v1/zz_generated.deepcopy.go:286:	DeepCopy	0.0%
sigs.k8s.io/kubebuilder/testdata/project-v3/controllers/admiral_controller.go:49:	Reconcile	0.0%
sigs.k8s.io/kubebuilder/testdata/project-v3/controllers/admiral_controller.go:58:	SetupWithManage0.0%
sigs.k8s.io/kubebuilder/testdata/project-v3/controllers/captain_controller.go:49:	Reconcile	0.0%
sigs.k8s.io/kubebuilder/testdata/project-v3/controllers/captain_controller.go:58:	SetupWithManage0.0%
sigs.k8s.io/kubebuilder/testdata/project-v3/controllers/firstmate_controller.go:49:	Reconcile	0.0%
sigs.k8s.io/kubebuilder/testdata/project-v3/controllers/firstmate_controller.go:58:	SetupWithManage0.0%
sigs.k8s.io/kubebuilder/testdata/project-v3/controllers/laker_controller.go:47:		Reconcile	0.0%
sigs.k8s.io/kubebuilder/testdata/project-v3/controllers/laker_controller.go:56:		SetupWithManage0.0%
total:											(statements)	3.4%

```

However, I do **not** think that is something that should come in the default scaffolds. However, users can customise the Makefile as they please. 

We need to be conscious about what we add or **not** in the default scaffolds because we need to support them and try to keep only what is mainly required and for general use. 

The project has an appetite for a FAQ section in the docs (See: https://github.com/kubernetes-sigs/kubebuilder/issues?q=is%3Aissue+is%3Aopen+FAQ). However, it also seems more related to "How to skip go files from the go tests coverage" which is not under the domain of the responsibilities of Kubebuilder. I mean it shows more of a Golang question. So, for this case, I do not think that we should add in the docs.

Regards "Is it a bug?" I do not think so. It shows me an RFE for "Could we skip the files generated automatically?" 

In this, my vote is for we close this one as sorted out (because we checked your scenario and you tried our best to help how to address your need)  and as RFE deferred (since we do have not a good way to address this request in the default scaffolds). Is that make sense? Could we agree? WDYT?

c/c @NikhilSharmaWe

**Comment by Sher-Chowdhury** [comment]
Hi @camilamacedo86 

First off, I think there's a small typo in that `test-coverage` example in your comment, the last line should read `go tool cover -func cover.out.tmp` rather than `go tool cover -func cover.out`. 

I agree, excluding the generated files from coverage doesn't appear to be the solution for the reasons you've given above. I also agree with your suggestion about leaving it to the users to add in their own version of `test-coverage` rather than being added to the default scaffolds. But in my case, it's mainly because `test-coverage` is more of a work-around that makes up for the inadequacy of `make test`. I've actually taken @NikhilSharmaWe's `test-coverage` suggestion, and socialized with the rest of my team to accept `test-coverage` as the true indicator of coverage rather than what's reported by `make test`. 

However it has just occurred to me that we could tweak `make test` to look like:

```
.PHONY: test
test: manifests generate fmt vet envtest ## Run tests.
	KUBEBUILDER_ASSETS="$(shell $(ENVTEST) use $(ENVTEST_K8S_VERSION) -p path)" go test ./... -coverprofile cover.out > /dev/null
	cat cover.out | grep -v "zz_generated.deepcopy.go" > cover.out.tmp
	go tool cover -func cover.out.tmp
```

In this example, I'm essentially dismissing the output from `go test` by sending it to `/dev/null`, and replacing it with output from `go tool cover -func cover.out.tmp`.  (I wish I thought of this approach sooner!)

This gives an output that looks like:

```
$ make test
/Users/sherchowdhury/operators/mysql-operator/bin/controller-gen rbac:roleName=manager-role crd webhook paths="./..." output:crd:artifacts:config=config/crd/bases
/Users/sherchowdhury/operators/mysql-operator/bin/controller-gen object:headerFile="hack/boilerplate.go.txt" paths="./..."
go fmt ./...
go vet ./...
KUBEBUILDER_ASSETS="/Users/sherchowdhury/Library/Application Support/io.kubebuilder.envtest/k8s/1.23.3-darwin-amd64" go test ./... -coverprofile cover.out > /dev/null
cat cover.out | grep -v "zz_generated.deepcopy.go" > cover.out.tmp
go tool cover -func cover.out.tmp
github.com/Sher-Chowdhury/mysql-operator/api/v1/mysql_types.go:73:              init                    100.0%
github.com/Sher-Chowdhury/mysql-operator/api/v1/mysql_webhook.go:29:            SetupWebhookWithManager 100.0%
github.com/Sher-Chowdhury/mysql-operator/api/v1/mysql_webhook.go:42:            Default                 100.0%
github.com/Sher-Chowdhury/mysql-operator/api/v1/mysql_webhook.go:54:            ValidateCreate          100.0%
github.com/Sher-Chowdhury/mysql-operator/api/v1/mysql_webhook.go:62:            ValidateUpdate          100.0%
github.com/Sher-Chowdhury/mysql-operator/api/v1/mysql_webhook.go:70:            ValidateDelete          100.0%
github.com/Sher-Chowdhury/mysql-operator/controllers/mysql_controller.go:61:    Reconcile               100.0%
github.com/Sher-Chowdhury/mysql-operator/controllers/mysql_controller.go:101:   SetupWithManager        100.0%
github.com/Sher-Chowdhury/mysql-operator/controllers/mysql_controller.go:108:   deploymentForMysql      100.0%
total:                                                                          (statements)            100.0%
```


What do you and @NikhilSharmaWe think? 


Regarding whether this is "Is it a bug?" or RFE, I actually don't have a strong opinion on this to be honest. So happy to take your lead on this.

**Comment by camilamacedo86** [comment]
Hi @Sher-Chowdhury,

That is still a very specific need. However, if you or @NikhilSharmaWe see that it would be helpful for others I have no objection of we track it in a FAQ section. Feel free to push it.

But, based on all findings and discussions I think we can agree to close this one.
Please, feel free to re-open it if you see that it fits.
