### ISSUE TITLE
Kubebuilder-gen generates wrong import for pkg/inject/zz_generated.kubebuilder.go

### ISSUE THREAD

**Issue by JoelSpeed** [kubernetes-sigs/kubebuilder#265]
Using v0.1.11 when running `kubebuilder generate` the generated file `pkg/inject/zz_generated.kubebuilder.go` tries to import `"github.com/kubernetes/apimachinery/pkg/runtime/schema"` where instead it should be importing `"k8s.io/apimachinery/pkg/runtime/schema"`

**Comment by pwittrock** [comment]
@droot Would you TAL?

**Comment by pwittrock** [comment]
@JoelSpeed We are making some changes that should make this obsolete.

**Comment by droot** [comment]
@JoelSpeed yes, you are correct. It should be importing "k8s.io/apimachinery/pkg/runtime/schema"

**Comment by JoelSpeed** [comment]
So I've made a discovery, on the system I was building on when I found this bug, for some reason I had a copy of `kubernetes/apimachinery` checked out at `$GOPATH/src/github.com/kubernetes/apimachinery`, I've removed that and now I get the correct generated file.

I have no idea what was doing that resolution but making sure I don't have erroneous copies of the repo seems to have fixed the problem.

Should there be any import resolution as part of the generate phase?

**Comment by droot** [comment]
>Should there be any import resolution as part of the generate phase?

I don't think so. 

One edge case I can think of: if at any point, you saved the generated file in an editor and `goimports` got triggered and it might have resolved in this ?

**Comment by JoelSpeed** [comment]
Nope, this was happening without me even opening the file in any editor

**Comment by droot** [comment]
Closing this. Pl. reopen it if you observe it with current builds of Kubebuilder.
