### ISSUE TITLE
'create resource' with plural kind generates broken tests

### ISSUE THREAD

**Issue by marun** [kubernetes-sigs/kubebuilder#267]
Steps to reproduce: 

- `kubebuilder init --domain example.com`
- `kubebuilder create resource --group overrides --version v1alpha1 --kind Overrides --plural-kind`

Unexpected result:

Tests refer to `OverridesV1alpha1().Overrides("default")` instead of  `OverridesV1alpha1().Overrideses("default")`.  Also, 'Overrideses' is a surprising pluralization, and is still used even if `--resource overrides` is specified.

Should this work, or, as per https://github.com/kubernetes/kubernetes/issues/18622, should resources with plural names be avoided?

**Comment by droot** [comment]
Looking at the CLI commands suggests that this is an outdated bug, so closing this. Pl. reopen it if you encounter this with new version of Kubebuilder.
