### ISSUE TITLE
Is Go 1.18 supported by Kubebuilder 3.4.0?

### ISSUE THREAD

**Issue by DaviSoares454** [kubernetes-sigs/kubebuilder#2670]
### What broke? What's expected?

Hi, all. I'm starting a new project using Kubebuilder. I already used Kubebuilder before to build some operators, and I saw that there was a new version for Kubebuilder. I also saw that a new Go version was out, so I went to test it out with Kubebuilder.
I entered the Kubebuilder book website and searched for the Quick start page, and there I saw some prerequisites. Reading that, I got a bit confused, because it says: "go version v1.17+ < v1.18 (kubebuilder v3.3+).", so I didn't know if I was able to use 1.17 Go version or 1.18 because it doesn't use ">=" (higher or equal) to describe the version.

Therefore, I went to use Go version 1.18 with Kubebuilder 3.4.0. Created a basic project that plays with the created API and Controller, basically it manages fields values from the CR. Everything worked fine so far.

I would like to know if there's any specific problem by using this Go version (1.18) with this Kubebuilder version (3.4.0).
Thanks in advance!

### Reproducing this issue

Commands that I used to scaffold a project.

`go mod init github.com/test/mylocal`

`kubebuilder init --domain test.mylocal`

`kubebuilder create api --group tester --version v1alpha1 --kind HandsOn`

### KubeBuilder (CLI) Version

Version: main.version{KubeBuilderVersion:"3.4.0", KubernetesVendor:"1.23.5", GitCommit:"75241ab9ff9457de77e902645792cee41ba29fed", BuildDate:"2022-04-28T17:09:31Z", GoOs:"linux", GoArch:"amd64"}

### Extra Labels

/kind documentation

**Comment by camilamacedo86** [comment]
I am closing this as duplicated of: https://github.com/kubernetes-sigs/kubebuilder/issues/2559
See the comment https://github.com/kubernetes-sigs/kubebuilder/issues/2559#issuecomment-1106200994 to know what needs to be done for we can support.

The release 3.4.0 still does not support go 1.18.
