### ISSUE TITLE
Doc - Write documentation to allow the utils and how Kubebuilder LIB consumers can test their own plugins

### ISSUE THREAD

**Issue by camilamacedo86** [kubernetes-sigs/kubebuilder#2677]
### What do you want to happen?

The goal of this issue is we have a new section under : https://book.kubebuilder.io/plugins/plugins.html such as "Written tests for your own plugin".  

Kubebuilder can be used as lib to allow its consumers to create their own plugins. Also, Kubebuilder provides so utils to allow developers to build their e2e tests or samples to check their plugins.

- You can check the lib: https://github.com/kubernetes-sigs/kubebuilder/tree/master/test/e2e/utils

Then, you can check some examples:
- In SDK: https://github.com/operator-framework/operator-sdk/tree/master/test/e2e/go
- In KB: https://github.com/kubernetes-sigs/kubebuilder/tree/master/test/e2e/v3

(For the plugins phase 2): Any external plugins should have a way to be executed by themselves, which means using the Kubebuilder lib and doing the CLI implementation. Therefore, the external plugin should have it's binary and can indeed have a test data dir with samples such as we build in both projects. 

**Suggestion (Acceptence Criteria):**
- a new section "Written tests for your own plugin" under https://book.kubebuilder.io/plugins/plugins.html such as "Written tests for your own plugin".
- under this section, we could have 2 subsections with examples to describe how to write e2e tests and how to generate the samples under the testdata. 

### Extra Labels

/kind documentation

**Comment by Kavinjsir** [comment]
I can try for this if the task is currently not scheduled.

**Comment by camilamacedo86** [comment]
That would be great @Kavinjsir , please feel free to work on this one.
