### ISSUE TITLE
quick start error in my mac m1

### ISSUE THREAD

**Issue by xiao-jay** [kubernetes-sigs/kubebuilder#2683]
### What broke? What's expected?

fix this error

### Reproducing this issue

when i copy 
```
# download kubebuilder and install locally.
curl -L -o kubebuilder https://go.kubebuilder.io/dl/latest/$(go env GOOS)/$(go env GOARCH)
chmod +x kubebuilder && mv kubebuilder /usr/local/bin/
```
and pasete in my macbook m1,will get result
```
➜  ~ # download kubebuilder and install locally.
curl -L -o kubebuilder https://go.kubebuilder.io/dl/latest/$\(go env GOOS)/$(go env GOARCH)
chmod +x kubebuilder && mv kubebuilder /usr/local/bin/
```

before ```\(go env GOOS)``` is different,why will lead this problem.

### KubeBuilder (CLI) Version

none

### PROJECT version

none

### Plugin versions

```yaml
none
```

**Comment by camilamacedo86** [comment]
See: https://github.com/kubernetes-sigs/kubebuilder/issues/1932

We do not support arm64 yet, using the master branch, you might work around the kustomize issue with `kubebuilder init --plugins=kustomize/v2-alpha,base.go.kubebuilder.io/v3` now. But we are still unable to use the env test. 

Closing as duplicated of https://github.com/kubernetes-sigs/kubebuilder/issues/1932
