### ISSUE TITLE
Should the core.Events RBAC permissions be scaffold by default in config/rbac/leader_election_role.yaml 

### ISSUE THREAD

**Issue by camilamacedo86** [kubernetes-sigs/kubebuilder#2684]
### What do you want to happen?

For the leader election, we request permissions to core.Events. The idea of this task is to investigate if it is required or if adding the permission is a bug since it is not used/required by the default implementation. 

See: https://github.com/kubernetes-sigs/kubebuilder/blob/master/testdata/project-v3/config/rbac/leader_election_role.yaml#L31-L37

**Comment by camilamacedo86** [comment]
To check this out we can see the motivations for: https://github.com/kubernetes-sigs/kubebuilder/issues/1474

**Comment by camilamacedo86** [comment]
In the meeting today we discussed this one and would be nice if we:

- a) Check if we need or not to scaffold these permissions by default (for that we need to check the C+R code)
- b) Check if we have a doc to describe how to raise events (if not then, would be nice to track an issue for that)
- c) We might want to check the motivations of https://github.com/kubernetes-sigs/kubebuilder/issues/1474 to see if it should not be better addressed via docs instead.

**Comment by AlmogBaku** [comment]
We use it here https://github.com/kubernetes-sigs/controller-runtime/blob/b704f447ea7c8f7059c6665143a4aa1f6da28328/pkg/leaderelection/leader_election.go

**Comment by camilamacedo86** [comment]
closing this one.
