### ISSUE TITLE
remove the trailing space from the comments and the reduce the blank space

### ISSUE THREAD

**Issue by camilamacedo86** [kubernetes-sigs/kubebuilder#2716]
### What broke? What's expected?

It is regarding the changes made in: https://github.com/kubernetes-sigs/kubebuilder/pull/2596

The goal is only to remove the trailing space ( space at the of the comments ) and reduce the space between # to the text from 4 to 2. The comment should be updated with:

```
# leaderElectionReleaseOnCancel defines if the leader should step down volume
# when the Manager ends. This requires the binary to immediately end when the
# Manager is stopped, otherwise, this setting is unsafe. Setting this significantly
# speeds up voluntary leader transitions as the new leader doesn't have to wait
# LeaseDuration time first.
# In the default scaffold provided, the program ends immediately after
# the manager stops, so would be fine to enable this option. However,
# if you are doing or is intended to do any operation such as perform cleanups
# after the manager stops then its usage might be unsafe.
# leaderElectionReleaseOnCancel: true

```

Why? 

Molecule tests which have a lint check have been failing because of the format on SDK. https://github.com/operator-framework/operator-sdk/issues/5838

### Reproducing this issue

Call the molecule tests as it is done for the advanced mock scenario on SDK with these changes

### KubeBuilder (CLI) Version

master

**Comment by camilamacedo86** [comment]
@everettraven that is another place we did not solve this one with https://github.com/kubernetes-sigs/kubebuilder/pull/2721

**Comment by everettraven** [comment]
Oops, sorry I read the issue to quickly. Thanks @camilamacedo86 !
