### ISSUE TITLE
prow: upgrade the kind to 0.14

### ISSUE THREAD

**Issue by camilamacedo86** [kubernetes-sigs/kubebuilder#2722]
### What do you want to happen?

In the test/common.sh we need to upgrade the kind to 1.14.0.
Also, we need to ensure that the default scaffold will work with

**Comment by everettraven** [comment]
Kind already upgraded to 0.14.0 here: https://github.com/kubernetes-sigs/kubebuilder/commit/6eb0be108ae8ebabe477449d68487b80018c9b27

**Comment by camilamacedo86** [comment]
done
