### ISSUE TITLE
CI should test kubebuilder-created repo against a rule kubernetes

### ISSUE THREAD

**Issue by pmorie** [kubernetes-sigs/kubebuilder#274]
So that we can perform more detailed checks and real end-to-end test of, for example:

- That the generated crd.yaml matches the CRD the generated controller installs
- Controller functions correctly, or at least passes a basic smoke test of running against a real cluster

**Comment by droot** [comment]
> * That the generated crd.yaml matches the CRD the generated controller installs

In post 1.0.0 versions, controller no longer generates and install the CRD. Users run separate command `make install` to install the CRD manifests.

The generated tests uses a *real* kube-apiserver/etcd for integration.

So looks like post 1.0.0 we have addressed these issues, so closing this, pl. re-open if there are parts of this issue that needs to be addressed.
