### ISSUE TITLE
Is it the right time for a new release for the kubebuilder which includes go support for 1.18?

### ISSUE THREAD

**Issue by samyak-jn** [kubernetes-sigs/kubebuilder#2744]
### What do you want to happen?

Hi folks :hugs:,

Thank you for the awesome work, this is more of a support request to track the new release for kubebuilder which supports, the newer version of golang as well (go v1.18). The master branch from the [PR comment](https://github.com/kubernetes-sigs/kubebuilder/issues/2559#issuecomment-1149937677)  already show the feature. Hence, a release for the same will be very appreciated! :")

**Comment by camilamacedo86** [comment]
Hi @samyak-jn we are looking to a release soon. 
You can also follow up on the milestone: https://github.com/kubernetes-sigs/kubebuilder/milestone/30

**Comment by camilamacedo86** [comment]
@samyak-jn after we get merged what is tracked in : https://github.com/kubernetes-sigs/kubebuilder/milestone/30
I think we are good to do the release.

c/c @rashmigottipati @everettraven

**Comment by camilamacedo86** [comment]
Hi @samyak-jn,

🔈 Kubebuilder [v3.5.0](https://github.com/kubernetes-sigs/kubebuilder/releases/tag/v3.5.0) has been released!
This release includes a Kubernetes dependency bump to v1.24.1, controller-runtime v0.12.1 and controller-gen v0.9.0. Also, adds support for go version 1.18. For more info see the release page: https://github.com/kubernetes-sigs/kubebuilder/releases.
