### ISSUE TITLE
Asciinema blows through the last part

### ISSUE THREAD

**Issue by pmorie** [kubernetes-sigs/kubebuilder#275]
The asciinema is great at showing the basic dev flow but blows through the part where the controller is deployed. We should add a pause to the end to give people a chance to absorb what's happening.

**Comment by droot** [comment]
The asciinema gif is updated. It covers the dev workflow with notes etc. I think its in good shape as far as Kubebuilder intro is concerned.

Closing this issue, Pl. re-open it if you think we need to improve it.
