### ISSUE TITLE
Support kubebuilder v2 using controller-tools commands

### ISSUE THREAD

**Issue by pwittrock** [kubernetes-sigs/kubebuilder#277]
We want to switch kubebuilder to using controller-tools and controller-runtime libraries, but don't want to break existing users.

- [ ] On startup check if the PROJECT file exists and if the version is "2"
- [ ] If running `kubebuilder init project` default to using `controller-tools controller-scaffold/cmd.ProjectCmd`

- [ ] Otherwise check the project version - if the PROJECT file is found with version "2"
  - Don't register the kubebuilder old commands, and instead only register the controller-tools commands
  - `kubebuilder create api` -> `cmd.APICmd`

- [ ] If the PROJECT file is missing or version != 2, then register the old kubebuilder commands the same as before

**Comment by droot** [comment]
project-version support was added sometime back, so closing this issue.
