### ISSUE TITLE
EnvTest doc does not explain how to work with default options provided ( certmanager and prometheus )

### ISSUE THREAD

**Issue by camilamacedo86** [kubernetes-sigs/kubebuilder#2777]
### What do you want to happen?

https://book.kubebuilder.io/reference/envtest.html#environment-variables. The KB doc does not mention installing cert-manager and prometheus. We could add that here as an extension telling why we do so, and how we test webhooks and a running operator. This could be done in a follow up too.

**Comment by ishanip24** [comment]
Perhaps the documentation could at least have a link to: https://cert-manager.io/docs/installation/kubectl/

**Comment by camilamacedo86** [comment]
By looking at this issue, it was opened too long ago and it is might out of context. However, I think that we can add here:

See that the envtest is commonly used to test the controllers. It is an integration test to "unit" test the controller/reconcile implementation.

Therefore, we do not need to use the metrics or cert-manager to run these tests usually. For example, look: https://github.com/kubernetes-sigs/kubebuilder/blob/master/testdata/project-v3-with-deploy-image/controllers/busybox_controller_test.go

However, if you want to run the tests against a cluster where you have some configurations in place they can use the option to test using an existing cluster:

                testEnv = &envtest.Environment{
			UseExistingCluster: true,
		}
Note that we can link/share the ENV config options: https://pkg.go.dev/sigs.k8s.io/controller-runtime/pkg/envtest#Environment

Also, we can let the users know that by using the plugin deploy-image/v1-alpha they can check an example of the code generated to use env tests to test the controller implementation via a note. See:

- https://book.kubebuilder.io/quick-start.html#using-deploy-image-plugin-to-generate-apis-and-controllers-code
- https://github.com/kubernetes-sigs/kubebuilder/blob/master/testdata/project-v3-with-deploy-image/controllers/busybox_controller_test.go

On top of that, share that if they are using webhooks they might want to check the optional config options https://pkg.go.dev/sigs.k8s.io/controller-runtime/pkg/envtest#WebhookInstallOptions
