### ISSUE TITLE
CRD marker support x-kubernetes-validations

### ISSUE THREAD

**Issue by FingerLiu** [kubernetes-sigs/kubebuilder#2798]
### What do you want to happen?

Is there a plan to support x-kubernetes-validations in kubebuilder CRD marker, so that we can do more verification like this

```
type: string
enum: ["low", "medium", "high"]
x-kubernetes-validations:
- rule: "!(self == 'high' && oldSelf == 'low') && !(self == 'low' && oldSelf == 'high')"
  message: cannot transition directly between 'low' and 'high'

https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/#available-validation-functions
```

**Comment by camilamacedo86** [comment]
Hi @FingerLiu, 

The CRD validations markers supported are doc here: https://book.kubebuilder.io/reference/markers/crd-validation.html

Note that the implementation is one via controller-gen. [more info](https://book.kubebuilder.io/reference/controller-gen.html). Therefore, see that it has a validation for ENUM already:

> +kubebuilder:validation:Enum
any
specifies that this (scalar) field is restricted to the *exact* values specified here.

However, if that is not what exactly what you are looking for and what you want to achieve is not supported by controller-gen then, I'd like to kindly ask for you open issue against its repo: https://github.com/kubernetes-sigs/controller-tools

Thank you for your attention and I hope that you do not mind we close this one.

**Comment by mickvav** [comment]
I believe that there is (undocumented) XValidation option.
So you can do things like:
```
       // +kubebuilder:validation:XValidation:rule=(self == oldSelf)
```
that transforms into
```
                x-kubernetes-validations:
                - rule: (self == oldSelf)
```
in your CRD, @FingerLiu .

**Comment by mickvav** [comment]
However, the underlying feature (`x-kubernetes-validations`), although is present in documentation, is still beta even in 1.25 version of kubernetes - 
https://github.com/kubernetes/enhancements/issues/2876

**Comment by AlexanderYastrebov** [comment]
> I believe that there is (undocumented) XValidation option.

See also https://kubernetes.io/blog/2022/09/29/enforce-immutability-using-cel/ for more examples.
