### ISSUE TITLE
Create a simple command for downloading the apiserver + etcd binaries and running them

### ISSUE THREAD

**Issue by pwittrock** [kubernetes-sigs/kubebuilder#280]
`kubebuilder install`

- Install the apiserver and etcd binaries for the platform if they don't exist
- Check if binaries are latest version, if not ask the user if they want to update the versions
- Make sure the test framework libraries in controller-runtime will search the installed location without additional configuration
- Update controller-runtime to tell the user to install them with kubebuilder if the binaries don't exist.

`kubebuilder run-control-plane`

- Check if the binaries exist and prompt use to install if not
- Use the test framework libraries to bring up a control plane
- Use the test framework to bring down the control plane on exist
- If one does not exist, write out an entry to `~/.kube/config` for the control plane
- Ask the user if they want to switch to the `~/.kube/config` entry if it is not active

**Comment by droot** [comment]
Not sure if this issue is still relevant because we bundle the k8s/etcd binaries with each Kubebuilder release and tests bring up those. Closing this, pl. reopen if you think there are parts of this bug that needs to be addressed.
