### ISSUE TITLE
Better support for generating RBAC

### ISSUE THREAD

**Issue by pwittrock** [kubernetes-sigs/kubebuilder#281]
- [ ] Break out RBAC role and rolebinding generation as a separate command that can be called separately `kubebuilder generate rbac`
- [ ] Make sure it works even if Controllers aren't annotated - should work against any struct or function with the `// kubebuilder:rbac` annotation
- [ ] Create a separate file for each role + rolebinding pair with the name of the group - e.g. `apps_rbac.yaml`, `core_rbac.yaml`

**Comment by droot** [comment]
This has been addressed with controller-gen tool adding support for RBAC generation.
