### ISSUE TITLE
Makefile scaffolding should generate target to install Kustomize with go install

### ISSUE THREAD

**Issue by erikgb** [kubernetes-sigs/kubebuilder#2822]
### What do you want to happen?

Since version 4.5.2, Kustomize supports installation with `go install`, ref. https://github.com/kubernetes-sigs/kustomize/issues/3618.  As a workaround we used the official install script in https://github.com/kubernetes-sigs/kubebuilder/pull/2486.

Motivation: Even if using the official Kustomize install script, I try to avoid executing remotely downloaded shell scripts.

### Extra Labels

/kind cleanup

**Comment by camilamacedo86** [comment]
Hi @erikgb, 

By default Kubebuilder scaffolds the Bundle go/v3 which uses kustomize v3.

The plugin go/v3 is a composition of other 2 plugins:
- kutomize/v1 -> Responsable to scaffolds the kustomize files ( config/dir ) which can be as it is reused for other language base plugins in projects that use Kubebuilder as lib for example, in SDK we have plugins that help you create Operators using Ansible or Helm and have the same kustomize config.  
- base.golang v3 -> which scaffolds the golang files and the Makefile

Therefore, the kustomize version 4.5.5 is only used with go/v4-alpha ( and kustomize/v2-alpha ) (see the PR https://github.com/kubernetes-sigs/kubebuilder/pull/2785). In this way, we could only update the Makefile for the new alpha plugin. 

In this way, I am adding this one to the go/v4 milestone. 

Note, in the next release users will begin to be able use the new kustomize version by running `kubebuilder init --plugins=go/v4-alpha` (you can check it out with the master branch)

- To know more about the plugin design see: https://book.kubebuilder.io/plugins/plugins.html: 
- To understand why using kustomize v4.x on the stable go/v3 plugin is not possible and it is breaking change see: https://github.com/kubernetes-sigs/kubebuilder/pull/2583

**Comment by erikgb** [comment]
/remove-lifecycle stale

Still relevant

**Comment by camilamacedo86** [comment]
Yes, you can. Please feel free to check this one.

**Comment by Sajiyah-Salat** [comment]
I think there should be a link in ``this`` keyword.

**Comment by camilamacedo86** [comment]
The changes must be done in : https://github.com/kubernetes-sigs/kubebuilder/blob/master/pkg/plugins/golang/v4/scaffolds/internal/templates/makefile.go#L198-L206

You will do the change and run `make generate` to ensure that all samples under tesdata are properly updated to push the PR.

**Comment by Sajiyah-Salat** [comment]
The above info was a little hard to process. I got that ``go get`` can't be used we need to add ``go install`` in updated version of kubebuilder. controller-gen have ``go install``. Do I need to change like that?

**Comment by ashutosh887** [comment]
@lakshya8066 If you are not able to resolve this, I would like to take this up @camilamacedo86

**Comment by Sajiyah-Salat** [comment]
> The above info was a little hard to process. I got that `go get` can't be used we need to add `go install` in updated version of kubebuilder. controller-gen have `go install`. Do I need to change like that?

it may sound dumb. but can I get reply or reviews on this. i am eager to contribute here. help me.

**Comment by erikgb** [comment]
> > The above info was a little hard to process. I got that `go get` can't be used we need to add `go install` in updated version of kubebuilder. controller-gen have `go install`. Do I need to change like that?
> 
> it may sound dumb. but can I get reply or reviews on this. i am eager to contribute here. help me.

Not sure if I understand the question, but I assume using a similar approach that for the other CLI tools installations using `go install` would work (like `controller-gen`).

**Comment by Sajiyah-Salat** [comment]
Thank you @erikgb for your reply.

**Comment by Sajiyah-Salat** [comment]
Thank you @erikgb for your reply.

**Comment by Sajiyah-Salat** [comment]
> The above info was a little hard to process. I got that `go get` can't be used we need to add `go install` in updated version of kubebuilder. controller-gen have `go install`. Do I need to change like that?

Hello @camilamacedo86 need your reviews.

**Comment by camilamacedo86** [comment]
The scope for this task is only change how we obtain / install kustomize.
The idea is to use go install instead of the shell script only for go/v4 scaffold. 

See the target:

https://github.com/kubernetes-sigs/kubebuilder/blob/master/testdata/project-v4/Makefile#L138-L146

Then, see where the code changes should be done: 

https://github.com/kubernetes-sigs/kubebuilder/blob/master/pkg/plugins/golang/v4/scaffolds/internal/templates/makefile.go#L198-L206

Therefore, we should not touch in the controller-gen target at all to do this one.
I am not sure if we can use go install to obtain controller-gen but anyway that is not part of the scope of this issue.

**Comment by lauchokyip** [comment]
/assign

Will work on this 😃
