### ISSUE TITLE
Makefile: avoid running prerequisites more than once

### ISSUE THREAD

**Issue by FotiadisM** [kubernetes-sigs/kubebuilder#2843]
### What broke? What's expected?

In the Makefile, specifying prerequisites like so:
```Makefile
$(KUSTOMIZE): $(LOCALBIN)
	curl -s $(KUSTOMIZE_INSTALL_SCRIPT) | bash -s -- $(subst v,,$(KUSTOMIZE_VERSION)) $(LOCALBIN)
```
will trigger Kustomize whenever a file is created/changed in `$(LOCALBIN)`

This can easily be fixed with `$(KUSTOMIZE): | $(LOCALBIN)` (note the "|"  in between). More info can be found [here](https://www.gnu.org/software/make/manual/make.html#Prerequisite-Types)

### Reproducing this issue

```bash
kubebuilder init --domain tutorial.kubebuilder.io --repo tutorial.kubebuilder.io/project
make kustomize
make kustomize # it won't run
touch bin/hello
make kustomize # it will run again
```

### KubeBuilder (CLI) Version

3.4.1

### PROJECT version

v3, v2

**Comment by camilamacedo86** [comment]
@FotiadisM, 

What is the issue scenario faced by you that motivates you raise this one? Could you please clarify and let us know a little more about it? Could you please fill up:

#### What did you do?



#### What did you expect to see?



#### What did you see instead? Under which circumstances?

**Comment by FotiadisM** [comment]
#### What did you do?
```bash
kubebuilder init --domain tutorial.kubebuilder.io --repo tutorial.kubebuilder.io/project
make build
# mkdir -p /tmp/demo/bin
# GOBIN=/tmp/demo/bin go install sigs.k8s.io/controller-tools/cmd/controller-gen@v0.8.0
# /tmp/demo/bin/controller-gen object:headerFile="hack/boilerplate.go.txt" paths="./..."
# go fmt ./...
# go vet ./...
# go build -o bin/manager main.go
make build
# GOBIN=/tmp/demo/bin go install sigs.k8s.io/controller-tools/cmd/controller-gen@v0.8.0
# /tmp/demo/bin/controller-gen object:headerFile="hack/boilerplate.go.txt" paths="./..."
# go fmt ./...
# go vet ./...
# go build -o bin/manager main.go
```
#### What did you expect to see?
I expected to build my program without installing `controller-gen` again.

#### What did you see instead? Under which circumstances?
I saw `GOBIN=/tmp/demo/bin go install sigs.k8s.io/controller-tools/cmd/controller-gen@v0.8.0` despite having it installed already, The installation of `controller-gen` is triggered whenever the timestamp of the `bin` directory changes, which in turn happens whenever the contents of the directory changes (ex a new binary in created with `make build`).

This also happens for the installation of `kustomize` and `setup-envtest`.

Changing these lines in the Makefile
```
$(KUSTOMIZE): $(LOCALBIN)
...
$(CONTROLLER_GEN): $(LOCALBIN)
...
$(CONTROLLER_GEN): $(LOCALBIN)
```
to 
```
$(KUSTOMIZE): | $(LOCALBIN)
...
$(CONTROLLER_GEN): | $(LOCALBIN)
...
$(CONTROLLER_GEN): | $(LOCALBIN)
```
fixes the issue.

**Comment by camilamacedo86** [comment]
Hi @FotiadisM, 

See that it was fixed for Kustomize in the master : https://github.com/kubernetes-sigs/kubebuilder/pull/2774
So, I think we need the same fix for controller-gen and env-test, see: https://github.com/kubernetes-sigs/kubebuilder/blob/master/testdata/project-v3/Makefile#L124-L132
