### ISSUE TITLE
grafana/v1-alpha: Address small nits recommendations on the titles

### ISSUE THREAD

**Issue by camilamacedo86** [kubernetes-sigs/kubebuilder#2846]
### What do you want to happen?

grafana/v1-alpha: Address small nits recommendations on the titles, see the comments: https://github.com/kubernetes-sigs/kubebuilder/pull/2834

**Comment by Kavinjsir** [comment]
Thx for reminding! Have create a PR for this:
https://github.com/kubernetes-sigs/kubebuilder/pull/2847
