### ISSUE TITLE
GOPATH is a multi-value environment variable

### ISSUE THREAD

**Issue by abdennour** [kubernetes-sigs/kubebuilder#285]
I see you catch an error by this message:

```
2018/06/22 23:28:20 kubebuilder must be run from the project root under $GOPATH/src/package.
```

When `GOPATH=/Users/abd/go`, it works. and when `GOPATH=/Users/abd/v1/go:/Users/abd/v2/go`, it does not work.

I assume you didn't consider the multi-value aspect of `GOPATH`.

Indeed, you can append multiple values to `GOPATH` by separating them through `:`.

**Comment by surbas** [comment]
I ran into the same issue. I have taken a look at the code and I may be wrong but seems like an easy change to accommodate multiple directories in GOPATH. @pwittrock @Liujingfang1 would this be a valid issue to fix? Is there more to it? I would like to take it on myself.

**Comment by abdennour** [comment]
Great @surbas ! Please go ahead.

**Comment by pwittrock** [comment]
@surbas SGTM.  Please tae it on.

**Comment by surbas** [comment]
Will do! Will try to have a pull by end of weekend.

**Comment by fanzhangio** [comment]
@surbas. Thanks for your help. Please let me know if you need any help.

**Comment by FogDong** [comment]
Same issue😢, have you finished your PR? 😉@surbas

**Comment by luisdavim** [comment]
any updates on this one?

**Comment by luisdavim** [comment]
This is actually covered in https://github.com/kubernetes-sigs/controller-tools/blob/master/pkg/crd/util/util.go maybe we can use that.

**Comment by luisdavim** [comment]
I've opened a PR to address this issue, please let me know what you think.
