### ISSUE TITLE
Phase 2 Plugins - Allow Universe to modify Scaffolding that is created from Phase 1 / 1.5 Plugins

### ISSUE THREAD

**Issue by jakobmoellersap** [kubernetes-sigs/kubebuilder#2871]
### What do you want to happen?

When testing Phase 2 Plugins, I read through the Design Proposal and the Concept of the Universe. I also tested the Concept by writing a small Plugin and seeing how the requests come into the Plugin. I was mostly concerned with how the Request is filled for the `kubebuilder create api` command, as this would have been a great place for me to start extending a scaffolding.

My Use Case: I had hoped to inject myself into the kubebuilder api scaffolding lifecycle, adjust the generated `xxx_controller.go` files with some additional scaffolding in the Reconcile() Loop.
 
I noticed right away however, that the universe that is filled in the initial Plugin Request was empty. I think the reason for this is that the universe only gets build up in the Phase 2 Plugins, and we cannot interact with the Files generated from the Phase 1 / 1.5 Plugins (e.g. golang v3 / v4-alpha). 

Is my assumption correct or could I possibly have done something wrong / understood something wrong when interacting with my plugin?

**Comment by camilamacedo86** [comment]
Hi @jakobmoellersap, 

> My Use Case: I had hoped to inject myself into the kubebuilder api scaffolding lifecycle, adjust the generated xxx_controller.go files with some additional scaffolding in the Reconcile() Loop.

I think what you are looking for to do is exactly what we do in the new [deploy-image](https://github.com/kubernetes-sigs/kubebuilder/tree/master/pkg/plugins/golang/deploy-image/v1alpha1) plugin and with the declarative one. 

In this way, if you are looking to create an external plugin that will add code on top of what is scaffold by default with the create API see that we do that [in deploy-image here](https://github.com/kubernetes-sigs/kubebuilder/blob/master/pkg/plugins/golang/deploy-image/v1alpha1/api.go) and you have many ways to achieve this goal:

a) You can overwrite the scaffold done with the go/v3 (for example) by using this option: https://github.com/kubernetes-sigs/kubebuilder/blob/df1ed6ccf19df40bd929157a91eaae6a9215bfc6/pkg/plugins/golang/deploy-image/v1alpha1/scaffolds/internal/templates/api/types.go#L58

b) You can use the plugin utils to inject and/or replace code, see: https://github.com/kubernetes-sigs/kubebuilder/blob/master/pkg/plugins/golang/deploy-image/v1alpha1/scaffolds/api.go#L170-L266

c) Note that you can call create api --plugins=go/v3,yourplugin/v1 and just ensure that the create api subcommand will overwrite or you can import the code as we decide to do in the deploy image to allow re-use it and make eaiser for users just call create api --plugins=deploy.image/v1alpha1, see: https://github.com/kubernetes-sigs/kubebuilder/blob/master/pkg/plugins/golang/deploy-image/v1alpha1/scaffolds/api.go#L77-L98

Another option also is to use the Bundle Plugin which will build a new plugin done by composition that does the call in chain as we can do by --plugins=a/v1,b/v2 and, see: https://book.kubebuilder.io/plugins/creating-plugins.html

```go
  mylanguagev1Bundle, _ := plugin.NewBundle(language.DefaultNameQualifier, plugin.Version{Number: 1},
        kustomizecommonv1.Plugin{}, // extend the common base from Kuebebuilder
        mylanguagev1.Plugin{}, // your plugin language which will do the scaffolds for the specific language on top of the common base
    )
```

I hope that the info above helps you out. Also, please let us know if you still seem that the api needs to be changed. If so could, you please let us know the following info with an example so that it can help us better understand your case scenario:

- What did you do?
- What did you expect to see?
- What did you see instead? Under which circumstances?

**Comment by jakobmoellersap** [comment]
Thanks @camilamacedo86 for the response!

I am aware of the developments of deploy-image and also the scaffolding options in the API. This worked out fine (btw. kudos for the nice incode integration).

My use case is a bit different though in that I want to extend kubebuilder without integrating it into our own CLIs (in which case we would have to triage vulnerabilities and dependency management tasks for the kubebuilder deps, which we do not want). 
This makes it a different use case from the OLM-style extensibility story in which I would rebundle the CLI and scaffold our own plugins like you would have described from options a-c in different flavors

I was hoping to use the Phase 2 Plugins as a way to change existing scaffolds specifically without using any in-code dependency to kubebuilder machinery except for `sigs.k8s.io/kubebuilder/v3/pkg/plugin/external`. That way our development teams could use kubebuilder natively by using `kubebuilder create api` instead of `mycustomkubebuilder create api`, or install our plugin in the Phase 2 style and then make use of our extensions, without ever having to use a rebundled CLI or a different binary.

As such I would have hoped for the `Universe` struct in the external API to contain data in the `PluginRequest` already (see https://github.com/kubernetes-sigs/kubebuilder/pull/2810/files#diff-0090dfb8dfd88c5317d967a0b20eed6efbd6d2393e9edfe90c15db6bf669af1bR26). This would have allowed me to get the file contents, modify them (e.g. by parsing them with a Regex for a certain content to replace it with) and modifying the scaffolding dynamically with Shell/Python/Go. 
This also has disadvantages though, e.g. not having a fixed template contract like the incode scaffolding engine of the go plugins and the deploy-image plugin.

I think for now, we will evaluate again, if it makes sense to use the classic V1 style plugin extensibility mechanisms in the style of declarative (this is actually really close to our use case as we want to push an operator ecosystem that is not as abstracted as OLM but not as deep into the depths as native kubebuilder / controller-tools).

**Comment by camilamacedo86** [comment]
Hi @jakobmoellersap, 

> I am aware of the developments of deploy-image and also the scaffolding options in the API. This worked out fine (btw. kudos for the nice incode integration).

Thank you for the feedback. I am ping the student from Google Summer Code program to let him know @NikhilSharmaWe. :-)  

**About your scenario**

The whole advantage of you importing KB is that will make it eaiser for you to keep your code maintained. Therefore, you do not need to re-implement what is provided by KB as well and you can get the bug/fixes and improvements every time that you bump the dep.  See: 

<img width="858" alt="Screenshot 2022-08-15 at 09 09 23" src="https://user-images.githubusercontent.com/7708031/184599578-65f41323-3898-4eb2-b263-8b1876df3bb2.png">

On top of that, your help and contributions to the project are more than welcome. If you see that something needs to be fixed/changed you can contribute with KB to get it done. Also, you won with the additions/fixes done by others from the community as well. 

Regards: 

> My use case is a bit different though in that I want to extend kubebuilder without integrating it into our own CLIs (in which case we would have to triage vulnerabilities and dependency management tasks for the kubebuilder deps, which we do not want).

>  was hoping to use the Phase 2 Plugins as a way to change existing scaffolds specifically without using any in-code dependency to kubebuilder machinery except for sigs.k8s.io/kubebuilder/v3/pkg/plugin/external

Sorry, but I think that I can not properly follow the motivation. But I'd like to share that KB does not use too many dependencies. Ideally, our goal is to have few as possible. 

> PS.:We have a few more because of the command config-gen ( which we are looking for to see how to externalize this option from KB) ( it is something that required more discussions/planning but its initial authors agreed with already). 

Also, I do not know the difference of use one package or all in these cases. 

> As such I would have hoped for the Universe struct in the external API to contain data in the PluginRequest already (see https://github.com/kubernetes-sigs/kubebuilder/pull/2810/files#diff-0090dfb8dfd88c5317d967a0b20eed6efbd6d2393e9edfe90c15db6bf669af1bR26). This would have allowed me to get the file contents, modify them (e.g. by parsing them with a Regex for certain content to replace it with) and modifying the scaffolding dynamically with Shell/Python/Go.
This also has disadvantages though, e.g. not having a fixed template contract like the incode scaffolding engine of the go plugins and the deploy-image plugin.

What data would have by default? See that the external API does not have any template. 
It is only an option for you to call the plugin implementations. (such as --plugins flag)
About this one, we need to be generic and use interfaces.  

**Alternative option**

However, if you want to work with other languages and not Golang we can also for example has a dep the Kubebuilder binary. Then, you can have a Makefile target that download the kubebuilder and other like:

doActionX:
- call kb binary command A, B C
- call your plugin that will do things on top. 

I hope that can help you out. Also, based on your latest comment I think we can close this one. WDYT?

**Comment by jakobmoellersap** [comment]
Hey there, thanks for the detailed comments. I agree with all of the above and I think my expectations to the external plugins were skewed initially.

I just want to follow up on the Point regarding the `Universe`. Currently If i use exactly one external plugin, the Universe will not contain any data (that is, the map is empty). The Plugin Request is not filled with any data.
I think this is ideal for plugins that only want to specifically add new files or scaffolding content.

However I think that for modifying existing scaffold coding, the only valid approach IMO is to use kubebuilder as a dependency and change the scaffolding behavior. As far as I understand from all of the above, there is no way to modify resources from the v3 go plugin with an external plugin based on the Universe, only to replace it. (e.g. the xxx_controller files)

Nevertheless, your input helped me a lot and I will reposition us to instead aim for kubebuilder integration into our CLIs (I think your point about dependencies is correct and I misjudged that). That said, I agree we can close the issue with my original description not fitting.

**Comment by camilamacedo86** [comment]
Hi @jakobmoellersap, 

I tracked an issue for we improve the docs with the info, see: https://github.com/kubernetes-sigs/kubebuilder/issues/2874. Also, if you see any other hall for improvements in the API please feel free to raise an issue so we can properly track this one.

Also, please do not hesitate to push pull requests with suggestions and/or to contribute to the project
Your help is very welcome. In this way, based on your comment https://github.com/kubernetes-sigs/kubebuilder/issues/2871#issuecomment-1214933592 I am closing this one.
