### ISSUE TITLE
Help needed with the Tutorial Build Cronjob

### ISSUE THREAD

**Issue by gaedemischwarz** [kubernetes-sigs/kubebuilder#2885]
### What broke? What's expected?

Hello,

i have another Problem with the Tutorial for the Cronjob Example. I try to go trough this Step by Step. At Step 1.9 with the make deploy command. The Deployment search for a File "role.yaml". I cannot find this file in the desired Folders. Here is the Output of the make deploy:

`kustomize installed to /Users/gaedemi/Documents/Workspace/project/bin/kustomize
cd config/manager && /Users/gaedemi/Documents/Workspace/project/bin/kustomize edit set image controller=XXXXXXXXX/cronjob:latest
/Users/gaedemi/Documents/Workspace/project/bin/kustomize build config/default | kubectl apply -f -
Error: accumulating resources: 2 errors occurred:
	* accumulateFile error: "accumulating resources from '../rbac': '/Users/gaedemi/Documents/Workspace/project/config/rbac' must resolve to a file"
	* accumulateDirector error: "recursed accumulation of path '/Users/gaedemi/Documents/Workspace/project/config/rbac': accumulating resources: 2 errors occurred:\n\t* accumulateFile error: \"accumulating resources from 'role.yaml': evalsymlink failure on '/Users/gaedemi/Documents/Workspace/project/config/rbac/role.yaml' : lstat /Users/gaedemi/Documents/Workspace/project/config/rbac/role.yaml: no such file or directory\"\n\t* loader.New error: \"error loading role.yaml with git: url lacks orgRepo: role.yaml, dir: evalsymlink failure on '/Users/gaedemi/Documents/Workspace/project/config/rbac/role.yaml' : lstat /Users/gaedemi/Documents/Workspace/project/config/rbac/role.yaml: no such file or directory, get: invalid source string: role.yaml\"\n\n"`

did i missed to create a File, or should the be normally in the Folders already?

kind Regards 
Michael 

### KubeBuilder (CLI) Version

Version: main.version{KubeBuilderVersion:"3.5.0", KubernetesVendor:"unknown", GitCommit:"26d12ab1134964dbbc3f68877ebe9cf6314e926a", BuildDate:"2022-06-24T07:47:41Z", GoOs:"darwin", GoArch:"amd64"}

### PROJECT version

version: "3"

### Plugin versions

```yaml
the field is not existing
```

### Other versions

go version go1.18.5 darwin/amd64
sigs.k8s.io/controller-runtime v0.12.1

KUBECTL:
Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.3", GitCommit:"aef86a93758dc3cb2c658dd9657ab4ad4afc21cb", GitTreeState:"clean", BuildDate:"2022-07-13T14:21:56Z", GoVersion:"go1.18.4", Compiler:"gc", Platform:"darwin/amd64"}
Kustomize Version: v4.5.4
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.5", GitCommit:"c285e781331a3785a7f436042c65c5641ce8a9e9", GitTreeState:"clean", BuildDate:"2022-03-16T15:52:18Z", GoVersion:"go1.17.8", Compiler:"gc", Platform:"linux/amd64"}

**Comment by camilamacedo86** [comment]
Hi @gaedemischwarz,

The role file is scaffolded when you init the project and it will be updated after you add the markers and run make manifests. Could you please share your PROJECT file so that we can look at the plugins / used? Did you make any changes in the default project layout scaffolded? Are you following the tutorial by creating a new project or are you trying to do it in a pre-existent project?

**Comment by camilamacedo86** [comment]
Hi @gaedemischwarz,

The sample/tutorial uses the go/v3 project which does not support Kustomize Version: v4.5.4.
Kustomuze v4 is only support in the go/v4-alpha plugin

So, did you create the project a new project with KB 3.5.0 trying to follow up the steps OR are you trying to use the sample: https://github.com/kubernetes-sigs/kubebuilder/tree/master/docs/book/src/cronjob-tutorial/testdata ?

**Comment by gaedemischwarz** [comment]
Hello Camila,

i moved to Operator framework. Thanks for your help. But as i guess the operatorframework is using the Kubebuilder.
So let's see if i will get my Operator to Work with the Operator Framework.

Greets Michael
