### ISSUE TITLE
Lint check fails in groupversion_info.go

### ISSUE THREAD

**Issue by nikfot** [kubernetes-sigs/kubebuilder#2893]
### What broke? What's expected?

Some comments in the groupversion_info.go file do not end in "."(dot) causing golangci-lint checks to fail. It is minor but I am letting it here.
```
	// GroupVersion is group version used to register these objects
	GroupVersion = schema.GroupVersion{Group: "grow.upstreamsystems.com", Version: "v1alpha1"}

	// SchemeBuilder is used to add go types to the GroupVersionKind scheme
	SchemeBuilder = &scheme.Builder{GroupVersion: GroupVersion}
```
_The same happens for the spec comment of the created api._
### Reproducing this issue

It can be re produced by using the simple commands of `kubebuilder init` and `kubebuilder create api`

### KubeBuilder (CLI) Version

Version: main.version{KubeBuilderVersion:"v3.5.0", KubernetesVendor:"unknown", GitCommit:"26d12ab1134964dbbc3f68877ebe9cf6314e926a", BuildDate:"2022-08-23T12:55:30Z", GoOs:"linux", GoArch:"amd64"}

### PROJECT version

3

**Comment by camilamacedo86** [comment]
Hi @nikfot, 

This implementation is done in the controller tools. Could you please raise this issue there: https://github.com/kubernetes-sigs/controller-tools ? 

Also, please feel free to contribute with controller-tools by doing a PR to fix that. 
Your help is very welcome.

Cheers,

**Comment by camilamacedo86** [comment]
Closing this one since it needs to be done in the controller-gen instead.
