### ISSUE TITLE
[Docs] Document how to record events

### ISSUE THREAD

**Issue by AlmogBaku** [kubernetes-sigs/kubebuilder#2897]
### What do you want to happen?

Following up on: https://github.com/kubernetes-sigs/kubebuilder/issues/2684#issuecomment-1227503698

As discussed in the meeting, we think it might be a good idea to add a section about **event recording** to the documentation, similar to [what we had in v1](https://book-v1.book.kubebuilder.io/beyond_basics/creating_events.html).

**Comment by AlmogBaku** [comment]
It's also better to use the controller-runtime recorder over the raw client recorder: https://github.com/kubernetes-sigs/controller-runtime/blob/master/pkg/recorder/recorder.go

**Comment by camilamacedo86** [comment]
Following is some relevant info which would be important we cover in the doc:

(IMO) we could add a warning with:

Events should be raised in certain circumstances only and following this guideline acctually is not a good practice. See what the Kubernetes APIs convention describes when using them here: https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#events
Note that is  NOT recommended to emit events for all Operations. If authors raise too many events it brings bad UX experiences for those that are consuming the solutions on the cluster and they will not have attention to what they actually must be notified. 

**Also, we can share how to implement the solution to raise an event:**

- a) You need to pass the recorder when you set up the recorder for the controller when the event will be raised see: https://github.com/kubernetes-sigs/kubebuilder/blob/master/testdata/project-v4-with-deploy-image/main.go#L103
- b) You need to add the makers to add the RBAC permissions to allow your Operator/controller to raise the event see: https://github.com/kubernetes-sigs/kubebuilder/blob/master/testdata/project-v4-with-deploy-image/controllers/memcached_controller.go#L66 and run make manifests
- c) You can check an example of the event being called in: https://github.com/kubernetes-sigs/kubebuilder/blob/master/testdata/project-v4-with-deploy-image/controllers/memcached_controller.go#L299-L303

**Then, we can also create a note to let users know that the new deploy-image plugin raises events and can be used as an example:** 

> What is the purpose of this plugin?
> The deploy Image plugin allows users to scaffold API/Controllers to deploy and manage an Operand (image) on the cluster following the guidelines and best practices. It abstracts the complexities of achieving this goal while allowing users to customize the generated code. ([More info](https://master.book.kubebuilder.io/plugins/deploy-image-plugin-v1-alpha.html)).
> Demo: https://www.youtube.com/watch?v=UwPuRjjnMjY

Note that we have a doc in the old book version. So, we might use this content as a base and just ensure that we have the info properly updated: https://book-v1.book.kubebuilder.io/beyond_basics/creating_events.html

By last, I think we could add it under the Reference section.

**Comment by mjlshen** [comment]
I would like to work on this, /assign

**Comment by camilamacedo86** [comment]
Hi @mjlshen, 

Are you working on this one? If you need help please feel free to ping your questions into the kubebuilder slack channel.

**Comment by Sajiyah-Salat** [comment]
Hello @mjlshen can I take this on?

**Comment by ashutosh887** [comment]
I would like to work on this @camilamacedo86 

/assign

**Comment by ashutosh887** [comment]
@AlmogBaku Please guide me how should I proceed?

**Comment by Sajiyah-Salat** [comment]
Hey @ashutosh887 if you want we can work together.
/assign

**Comment by AlmogBaku** [comment]
take a look at how I do at [Raptor.ml](https://github.com/raptor-ml/raptor/blob/master/internal/operator/model_controller.go#L69)

In general, you should [inject the event recorder](https://github.com/raptor-ml/raptor/blob/master/cmd/core/internal/setup/raptor.go#L117) to the Reconciler when initializing it, then [record events](https://github.com/raptor-ml/raptor/blob/master/internal/operator/model_controller.go#L69)

**Comment by Sajiyah-Salat** [comment]
hello @almogBaku, in v1 docs it is given perfectly. I dont have depth so I dont know which things need to be updated. morever I have questions regarding to place a record event file. i think I should just open a pr with v1 doc record event file and after your reviews and suggestion we can make it ready for current version?

**Comment by Sajiyah-Salat** [comment]
> hello @AlmogBaku, in v1 docs it is given perfectly. I dont have depth so I dont know which things need to be updated. morever I have questions regarding to place a record event file. i think I should just open a pr with v1 doc record event file and after your reviews and suggestion we can make it ready for current version?

/cc @camilamacedo86

**Comment by ashutosh887** [comment]
Sure I've started working on it @camilamacedo86 
Thanks

**Comment by Sajiyah-Salat** [comment]
Hello @ashutosh887 are you still working on this. If yes, please link the pr.

**Comment by ashutosh887** [comment]
Yes I'm willing to take this forward @Sajiyah-Salat

**Comment by Sajiyah-Salat** [comment]
Have you made a pr

**Comment by Sajiyah-Salat** [comment]
> Following is some relevant info which would be important we cover in the doc:
> 
> (IMO) we could add a warning with:
> 
> Events should be raised in certain circumstances only and following this guideline acctually is not a good practice. See what the Kubernetes APIs convention describes when using them here: https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#events Note that is NOT recommended to emit events for all Operations. If authors raise too many events it brings bad UX experiences for those that are consuming the solutions on the cluster and they will not have attention to what they actually must be notified.
> 
> **Also, we can share how to implement the solution to raise an event:**
> 
> * a) You need to pass the recorder when you set up the recorder for the controller when the event will be raised see: https://github.com/kubernetes-sigs/kubebuilder/blob/master/testdata/project-v4-with-deploy-image/main.go#L103
> * b) You need to add the makers to add the RBAC permissions to allow your Operator/controller to raise the event see: https://github.com/kubernetes-sigs/kubebuilder/blob/master/testdata/project-v4-with-deploy-image/controllers/memcached_controller.go#L66 and run make manifests
> * c) You can check an example of the event being called in: https://github.com/kubernetes-sigs/kubebuilder/blob/master/testdata/project-v4-with-deploy-image/controllers/memcached_controller.go#L299-L303
> 
> **Then, we can also create a note to let users know that the new deploy-image plugin raises events and can be used as an example:**
> 
> > What is the purpose of this plugin?
> > The deploy Image plugin allows users to scaffold API/Controllers to deploy and manage an Operand (image) on the cluster following the guidelines and best practices. It abstracts the complexities of achieving this goal while allowing users to customize the generated code. ([More info](https://master.book.kubebuilder.io/plugins/deploy-image-plugin-v1-alpha.html)).
> > Demo: https://www.youtube.com/watch?v=UwPuRjjnMjY
> 
> Note that we have a doc in the old book version. So, we might use this content as a base and just ensure that we have the info properly updated: https://book-v1.book.kubebuilder.io/beyond_basics/creating_events.html
> 
> By last, I think we could add it under the Reference section.

The video you suggested is of v1. do you think we should add that?

**Comment by camilamacedo86** [comment]
It is done : https://book.kubebuilder.io/reference/raising-events

Closing this one.
