### ISSUE TITLE
Bump K8s 1.25

### ISSUE THREAD

**Issue by camilamacedo86** [kubernetes-sigs/kubebuilder#2908]
### What do you want to happen?

To bump to use Kubernetes version 1.25 we need to:

- [x] - Generate the envtools for it

The build is made from the branch [tools-releases](https://github.com/kubernetes-sigs/kubebuilder/tree/tools-releases). So, we need to create a PR to generate tools with the latest binaries version

- [ ] - bump controller-tools for a version using the k8s 1.25
- [x] - the declarative plugin usually also needs to be updated: https://github.com/kubernetes-sigs/kubebuilder/blob/master/pkg/plugins/golang/declarative/v1/api.go#L35 (we usually contribute with the project to ensure that is bumped to use the latest k8s version)
- [x] - bump controller-runtime latest release using k8s 1.25 (go/v3 plugin only)
- [x] - Update kubebuilder CLI to use the k8s 1.25
- [x] - Update the CI for we begin to test against k8s 1.25, see: https://github.com/kubernetes-sigs/kubebuilder/blob/master/CONTRIBUTING.md#where-the-ci-tests-are-configured

**Comment by oscr** [comment]
@camilamacedo86 With #2956 merged I think this is completed now. Thank you for all your guidance :pray:

**Comment by camilamacedo86** [comment]
Thank you for all your help @oscr.
You were amazing !!!
