### ISSUE TITLE
 go build -o bin/manager main.go error.

### ISSUE THREAD

**Issue by Ishmeet** [kubernetes-sigs/kubebuilder#2913]
### What broke? What's expected?

`kubebuilder create api --group plugin --version v1alpha1 --kind ApstraPlugin`

why is this error coming, during go build -o bin/manager main.go

Also, how can I scaffold resources and controllers under pkg directory?

```
go build -o bin/manager main.go
# ssd-x/xx/deployer/apis/plugin/v1alpha1
apis/plugin/v1alpha1/xxxxplugin_types.go:62:25: cannot use &ApstraPlugin{} (value of type *ApstraPlugin) as type runtime.Object in argument to SchemeBuilder.Register:
	*ApstraPlugin does not implement runtime.Object (missing DeepCopyObject method)
apis/plugin/v1alpha1/apstraplugin_types.go:62:42: cannot use &ApstraPluginList{} (value of type *ApstraPluginList) as type runtime.Object in argument to SchemeBuilder.Register:
	*ApstraPluginList does not implement runtime.Object (missing DeepCopyObject method)
make: *** [manager] Error 2
2022/09/07 02:23:24 failed to create API: exit status 2
```

### Reproducing this issue

`kubebuilder create api --group plugin --version v1alpha1 --kind ApstraPlugin`

### KubeBuilder (CLI) Version

2.3.1: Version: version.Version{KubeBuilderVersion:"2.3.1", KubernetesVendor:"1.16.4", GitCommit:"8b53abeb4280186e494b726edf8f54ca7aa64a49", BuildDate:"2020-03-26T16:42:00Z", GoOs:"unknown", GoArch:"unknown"}

### Other versions

go version go1.18 linux/amd64

### Extra Labels

/kind cleanup

**Comment by camilamacedo86** [comment]
Hi @Ishmeet,

See the error:

> 
> *ApstraPlugin does not implement runtime.Object (missing DeepCopyObject method)
> apis/plugin/v1alpha1/apstraplugin_types.go:62:42: cannot use &ApstraPluginList{} (value of type *ApstraPluginList) as type runtime.Object in argument to SchemeBuilder.Register:
> 	*ApstraPluginList does not implement runtime.Object (missing DeepCopyObject method) 

You probably have an invalid implementation in the API specs OR you did not call make manifests to use the controller-gen after implementing the API specs.

**Comment by Ishmeet** [comment]
worked with `make generate`
