### ISSUE TITLE
Clean up the tests and document test policy

### ISSUE THREAD

**Issue by camilamacedo86** [kubernetes-sigs/kubebuilder#2921]
### What do you want to happen?

As discussed and agreed in the KubeBuilder meeting on Sep 08 2022: (Meeting:[ https://youtu.be/GzVcNr_F1SY](https://youtu.be/GzVcNr_F1SY) we just need to support the latest 3 k8s releases and has no reason for we run the tests against so many versions as we do now see:
 
<img width="895" alt="Screenshot 2022-09-10 at 19 45 33" src="https://user-images.githubusercontent.com/7708031/189497418-a943dd95-48c1-490e-a78d-29e30ea965fd.png">

In this way, we need to:

- [x] - Create a PR to remove the k8s versions 1.18 to 1.22, See: https://github.com/kubernetes/test-infra/blob/master/config/jobs/kubernetes-sigs/kubebuilder/kubebuilder-presubmits.yaml#L112-L261
- [x] - Add to the Contribution guide in the CI/test section that every time that we add a new k8s version to be tested we should remove the old one since our policy to test the project is run against N -2. It can be noted under this section: https://github.com/kubernetes-sigs/kubebuilder/blob/master/CONTRIBUTING.md#where-the-ci-tests-are-configured
- [ ] - Clean up the e2e tests. We should remove all tests that are done only in old versions < 1.23:

Following the details
a) Remove all tests done with v1beta1:
* https://github.com/kubernetes-sigs/kubebuilder/blob/master/test/e2e/v3/plugin_cluster_test.go#L83-L111 
* https://github.com/kubernetes-sigs/kubebuilder/blob/master/test/e2e/v3/plugin_cluster_test.go#L134-L145
* https://github.com/kubernetes-sigs/kubebuilder/blob/master/test/e2e/v3/plugin_cluster_test.go#L172

(We also need to remove the option to pass version v1beta1)

b) Remove the conditions that will get obsolete
* https://github.com/kubernetes-sigs/kubebuilder/blob/master/test/e2e/v3/plugin_cluster_test.go#L148-L154
* https://github.com/kubernetes-sigs/kubebuilder/blob/master/test/e2e/v3/plugin_cluster_test.go#L161-L169

c) All tests now are done with restricted mode true then we can remove the test: https://github.com/kubernetes-sigs/kubebuilder/blob/master/test/e2e/v3/plugin_cluster_test.go#L172

d) The same changes need to be applied under tests/e2e/v4/, see: https://github.com/kubernetes-sigs/kubebuilder/tree/master/test/e2e/v4

e) we can also remove the skip conditions from : https://github.com/kubernetes-sigs/kubebuilder/blob/master/test/e2e/deployimage/plugin_cluster_test.go

  

### Extra Labels

/kind cleanup

**Comment by Eileen-Yu** [comment]
Hi @camilamacedo86 I'm very new to the community and is looking forward to join by contribution. 

See you've nicely come up with this good-first-issue, and kindly bring detailed instructions. 

So based on that, I tried to open 3 PR. Let me know if I'm missing anything.

**Comment by 26tanishabanik** [comment]
@camilamacedo86 , I would like to work on this issue

**Comment by camilamacedo86** [comment]
Hi @26tanishabanik, 

@Eileen-Yu is working on this one and is close to finishing.  
I assign the task to her to make clear. 

However, please feel free to choose any other task.
