### ISSUE TITLE
kube-apiserver version is not right in 0.1.11 and 0.1.12

### ISSUE THREAD

**Issue by gyliu513** [kubernetes-sigs/kubebuilder#297]
Why did the apiserver version is as follows?

```
root@gyliu-dev1:~/kubebuilder_0.1.11_linux_amd64/bin# ./kube-apiserver --version
Kubernetes v0.0.0-master+$Format:%h$
```
```
root@gyliu-dev1:~/kubebuilder_0.1.12_linux_amd64/bin# ./kube-apiserver --version
Kubernetes v0.0.0-master+$Format:%h$
```

A normal apiserver should have following version.
```
root@gyliu-icp-6:/opt/kubernetes# ./hyperkube apiserver --version
Kubernetes v1.10.0+icp-ee
```

**Comment by gyliu513** [comment]
Can anyone show some comments for how to check version of `kube-apiserver` and `kubectl` in kubebuilder?

**Comment by gyliu513** [comment]
@droot do you know why? Does this share same reason with https://github.com/awslabs/amazon-eks-ami/issues/3#issuecomment-406904816 ?

**Comment by gyliu513** [comment]
@droot thanks, will try to create a PR when have time later.

**Comment by tanweernoor** [comment]
@gyliu513 have you fixed this ? can you share spec file please ?

**Comment by gyliu513** [comment]
@tanweernoor not yet, as it is not priority now. You can probably create a PR if needed ;-)

**Comment by tanweernoor** [comment]
i will be happy to do it if someone can explain me what needs to be done ?

There are various ways to fix this. 
1) One way would be to fetch the pre-built binaries from the core kubernetes releases instead of building it from scratch.
2) what else ? 1) is not the fix :)

**Comment by gyliu513** [comment]
@tanweernoor  I think 1) is good enough for the fix, @droot , can you help confirm? Thanks.

**Comment by droot** [comment]
This is fixed a few releases back, so closing this. Pl. reopen this if you still encounter this issue.
