### ISSUE TITLE
kubebuilder init: fails with error "version 0 is not supported"

### ISSUE THREAD

**Issue by ahmetb** [kubernetes-sigs/kubebuilder#2971]
### What broke? What's expected?

Reading the https://book.kubebuilder.io/quick-start.html, it appears commands like

    kubebuilder init --domain my.domain --repo my.domain/guestbook --plugins=go/v4-alpha

are supposed to work but:

1. --domain flag doesn't exist  (per --help)
2. --repo flag doesn't exist (per --help)
3. command `./kubebuilder_darwin_arm64 init` with default flag values fails with error:

        2022/09/27 20:33:55 unable to load the configuration: unable to create config for version "0": version 0 is not supported

### Reproducing this issue

```
wget https://github.com/kubernetes-sigs/kubebuilder/releases/download/v3.7.0/kubebuilder_darwin_arm64
chmod +x kubebuilder_darwin_arm64
```

```
$ kubebuilder init --plugins=go.kubebuilder.io/v4-alpha
...
2022/09/27 20:34:30 unable to load the configuration: unable to create config for version "0": version 0 is not supported
```

```
$ kubebuilder init --plugins=go.kubebuilder.io --project-version=4
...
2022/09/27 20:34:30 unable to load the configuration: unable to create config for version "0": version 0 is not supported
```

### KubeBuilder (CLI) Version

can't print the version, the command fails with the same error as listed above (but I downloaded 3.7.0).

### PROJECT version

no such file

**Comment by camilamacedo86** [comment]
What is the go version used locally?
Could you please run `go version` and output the result here?
Also, are your Golang local env properly set up?

**Comment by ahmetb** [comment]
I think the Go environment does not matter here because the result is the same if I download the precompiled binary as well. Are you seeing a different result?

**Comment by laxmikantbpandhare** [comment]
For me, it's working

```
kubebuilder init --domain my.domain --repo my.domain/guestbook --plugins=go/v4-alpha
Writing kustomize manifests for you to edit...
Writing scaffold for you to edit...
Get controller runtime:
$ go get sigs.k8s.io/controller-runtime@v0.13.0
Update dependencies:
$ go mod tidy
Next: define a resource with:
$ kubebuilder create API
```

**Comment by camilamacedo86** [comment]
Hi @ahmetb, 

The Go version matter because this error seems to be the go version used. On top of that, we are unable to reproduce this issue, and it all leads to a wrong Golang setup in your local env. Then, without you providing all details and info it is regarded we are able to try to help you out.

**Comment by ahmetb** [comment]
Apologies, I was able to run the tool itself on an empty dir with go1.19.1. For whatever reason, in my module it gives an error. I'll try to troubleshoot that myself. Thanks for helping out and sorry for the false bug report.
/close
