### ISSUE TITLE
Update golang version and kube-builder

### ISSUE THREAD

**Issue by quentinalbertone** [kubernetes-sigs/kubebuilder#2991]
### What broke? What's expected?

Hi
I recently updated golang on my computer from `1.17` to `1.19`,
during the process I also updated the version of kube-builder (I just [reinstalled kubebuilder](https://book.kubebuilder.io/quick-start.html#installation)) from `3.3` to `3.7`.
But now I cannot generate code containing DeepCopy, DeepCopyInto, and DeepCopyObject method implementations.

```Bash
$> make generate
my_project_path/bin/controller-gen object:headerFile="hack/boilerplate.go.txt" paths="./..."
/usr/local/Cellar/go/1.19.1/libexec/src/sync/atomic/type.go:39:16: expected ']', found any
/usr/local/Cellar/go/1.19.1/libexec/src/sync/atomic/type.go:39:19: expected ';', found ']'
/usr/local/Cellar/go/1.19.1/libexec/src/sync/atomic/type.go:39:19: expected type, found ']'
/usr/local/Cellar/go/1.19.1/libexec/src/sync/atomic/type.go:45:34: expected declaration, found 'return'
/usr/local/Cellar/go/1.19.1/libexec/src/sync/atomic/type.go:39:16: expected ']', found any
/usr/local/Cellar/go/1.19.1/libexec/src/sync/atomic/type.go:39:19: expected ';', found ']'
/usr/local/Cellar/go/1.19.1/libexec/src/sync/atomic/type.go:39:19: expected type, found ']'
/usr/local/Cellar/go/1.19.1/libexec/src/sync/atomic/type.go:45:34: expected declaration, found 'return'
/usr/local/Cellar/go/1.19.1/libexec/src/sync/atomic/type.go:39:16: expected ']', found any
/usr/local/Cellar/go/1.19.1/libexec/src/sync/atomic/type.go:39:19: expected ';', found ']'
/usr/local/Cellar/go/1.19.1/libexec/src/sync/atomic/type.go:39:19: expected type, found ']'
/usr/local/Cellar/go/1.19.1/libexec/src/sync/atomic/type.go:45:34: expected declaration, found 'return'
Error: not all generators ran successfully
run `controller-gen object:headerFile=hack/boilerplate.go.txt paths=./... -w` to see all available markers, or `controller-gen object:headerFile=hack/boilerplate.go.txt paths=./... -h` for usage
make: *** [generate] Error 1
```

I suppose that it's link to this field in my struct
```Go
// +kubebuilder:validation:Optional
// +mapType:=atomic
// Specifies the node in which the capture must be deployed
// https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#nodeselector
NodeSelector map[string]string `json:"nodeSelector,omitempty"`
```
I'm pretty sure everything was alright before the update but I might be wrong

### KubeBuilder (CLI) Version

3.3.0

### PROJECT version

v3

### Plugin versions

```yaml
layout:
- go.kubebuilder.io/v3
```

### Other versions

```Bash
$> go version
go version go1.19.1 darwin/amd64
```

**Comment by camilamacedo86** [comment]
That is probably because of the controller-gen version used.
You are now using the latest version of the CLI but your project was scaffold using old versions.
I would recommend you upgrade the controller-gen version used (see your Makefile file) as the go.mod deps as you can check in the samples for the tag used, see: 

- Go.mod
https://github.com/kubernetes-sigs/kubebuilder/blob/3bfc84ec8767fa760d1771ce7a0cb05a9a8f6286/testdata/project-v3/go.mod#L3-L12

- And the Makefile: https://github.com/kubernetes-sigs/kubebuilder/blob/v3.7.0/testdata/project-v3/Makefile

**Comment by quentinalbertone** [comment]
Thanks I copy past the `makefile` as well as the `go.mod` a little `go mod tidy`and delete the `bin` directory and it works fine now.

I think it could be a good Idea to offer a way to scaffold again the project.

**Comment by camilamacedo86** [comment]
Hi @quentinalbertone,

> I think it could be a good Idea to offer a way to scaffold again the project.

Yes. That would be great and very desirable if we could have a solution via tooling that could update the projects. See https://github.com/kubernetes-sigs/kubebuilder/issues/2068#issuecomment-1211204061 and thought about how we could achieve that. 

We also have the PR (WIP): https://github.com/kubernetes-sigs/kubebuilder/pull/2895/files but I am not sure if @rumstead has been able to work on it. Please, if you would like to help out please feel free to do so and also propose any other solution that you see for us to achieve this goal. 

Regards this issue, I think we could address the need and I am closing this one. However, feel free to re-open if you see that would be required.
