### ISSUE TITLE
Windows release?

### ISSUE THREAD

**Issue by mattfarina** [kubernetes-sigs/kubebuilder#300]
There are releases for both Mac and Linux (appears to be POSIX based). Would it be possible to cross-compile to Windows and have a Windows release as well?

**Comment by droot** [comment]
I think cross-compiling Kubebuilder binary itself should be easy because we use `GoReleaser` to generate the builds, packaging the dependencies for Windows is going to require some more work here. Happy to help if anyone wants to take this up.

**Comment by p-bakker** [comment]
If you want to run this on Windows, you could also enable the Windows Linux Subsystem and install for example Ubuntu from the Windows App store and just install and run the Linux version of Kubebuilder

https://github.com/michaeltreat/Windows-Subsystem-For-Linux-Setup-Guide

**Comment by mattfarina** [comment]
@p-bakker It's worth noting that ~50% of devs use Windows and most don't use the subsystem for Linux.

**Comment by neelesh3710** [comment]
WSL does not fully support all development workflows. For example:

Can't run delve debugger on WSL: https://github.com/Microsoft/WSL/issues/2977

There is also issue running kubebuilder tests on WSL because etcd shipped with kubebuilder does not run under WSL.

Would be nice if the native windows version was available.

**Comment by alexeldeib** [comment]
@droot Could you elaborate on `packaging the dependencies for Windows is going to require some more work`? Do you mean e.g. etcd/kube-apiserver/kubectl for testing? The only dependency I could find which did not have a windows build available was kube-apiserver.

With the two diffs below, I'm able to build and use Kubebuilder natively on windows. I'm happy to take this task up and do the work necessary to it that into mergeable state.
 
https://github.com/kubernetes-sigs/controller-tools/pull/179
https://github.com/kubernetes-sigs/kubebuilder/pull/661

**Comment by alexeldeib** [comment]
For testing on windows, I used a container and volume mounted my dev directory so that I could run kube-apiserver. This is one of the areas that would require more work for a smooth experience.

**Comment by droot** [comment]
> Could you elaborate on packaging the dependencies for Windows is going to require some more work? Do you mean e.g. etcd/kube-apiserver/kubectl for testing? The only dependency I could find which did not have a windows build available was kube-apiserver.

Yes, thats what I meant.

**Comment by alexeldeib** [comment]
@droot I marked this as fixed in the PR which was a mistake 😦 could you reopen?

**Comment by DirectXMan12** [comment]
sorry for the terrifically long delay here

**Comment by DirectXMan12** [comment]
we still need help for this.  we'll want CI too

**Comment by chx** [comment]
Re https://github.com/kubernetes-sigs/kubebuilder/issues/300#issuecomment-467586524 about WSL, Microsoft gave up on trying to translating syscalls and WSL2 is a very lightweight VM so now truly all Linux programs will work. Just sayin'.

**Comment by alexeldeib** [comment]
I think it’s reasonable to tell windows users to run e2e tests agains kind, and set envtest to use existing cluster? 

I regularly work on windows and linux and use kubebuilder fine with this approach on both. Some random characters in help text but that’s my biggest complaint.

Rest of testing can probably be done in Go?

**Comment by Aarthisk** [comment]
I am starting off with kubebuilder on windows- is the easiest option to build by myself?

**Comment by alexeldeib** [comment]
That’s what I do

**Comment by DirectXMan12** [comment]
It'd be nice to at least have nightly builds using cross-compile, I think (if anyone wants to pitch in) and a test on prow/travis that tries to cross-compile.

**Comment by Adirio** [comment]
With both issues mentioned in https://github.com/kubernetes-sigs/kubebuilder/issues/300#issuecomment-480667169 merged, is it possible to compile for windows straight away or do I need to change anything?

The mentioned tests issues are with projects build with kubebuilder or with the kubebuilder cmd? The first is not an issue as they will be tested in my CI machines which are non-windows.

**Comment by alexeldeib** [comment]
You'll be fine. I did a sanity check right now:
```bash
git clone git@github.com:kubernetes-sigs/kubebuilder
cd kubebuilder
go build -o kubebuilder.exe ./cmd/
./kubebuilder.exe # works
```

**Comment by alexeldeib** [comment]
Elaborating on my original comment, the test issues are related to running e2e tests which depend on a full Kubernetes cluster natively on windows. On Linux, you can use the etcd/apiserver binaries and the `envtest` package to quickly spin up a real backend. On windows, you can't run the apiserver binary, so this doesn't work.

Using kind works well as a backing cluster for `envtest` on windows. This will let you run full e2e with controllers made using kubebuilder/controller-runtime on your windows machine.

**Comment by Adirio** [comment]
I have a running kubernetes on windows (docker-for-windows). Well its actually not windows somehow as it is pulling the linux images from the manifests, but all the kubernetes cluster is accessible with kubectl from the windows command. Shouldn't that be enough for e2e tests?

**Comment by alexeldeib** [comment]
See https://godoc.org/sigs.k8s.io/controller-runtime/pkg/envtest for requirements, that will probably work. I can't say without more certainty without trying 😄

**Comment by Adirio** [comment]
Which version of Golang are you using? I'm asking this to know if I must set go modules as I'm currently using 1.12.x which if I'm not mistaken is the last that doesn't have it turned on by default.

**Comment by alexeldeib** [comment]
Correct, the above requires go modules (I always enable them by default in my environment)

Barring windows specific issues on this thread, slack channel is probably a better forum for discussion + q/a 🙂

**Comment by Aarthisk** [comment]
@alexeldeib 
you said "Using kind works well as a backing cluster for envtest on windows. This will let you run full e2e with controllers made using kubebuilder/controller-runtime on your windows machine."

So forgive the novice question, but with a backing "real" k8s cluster, this should just work then? The issues you are pointing out are unit testing without a cluster which I can honestly live without.

**Comment by Adirio** [comment]
I'm finding some issues with the paths inside the generated Makefile for the projects. To achieve compatibility with Windows I guess this generated Makefile needs to be either generic or specific for the target OS.

**Comment by DirectXMan12** [comment]
happy to take fixes to make it windows-compatible (none of the core devs have windows machines, so it's a bit hard for us)

**Comment by chx** [comment]
As I mentioned above: this issue will be moot in five days when WSL2 rolls out. It's wasted effort trying to make a program of this size run with Windows. Windows Insiders already have ran WSL2 for months.

**Comment by MaxThom** [comment]
This is how I installed kubebuilder on WSL2.

```git clone https://github.com/kubernetes-sigs/kubebuilder.git```
```cd kubebuilder```
```make build```
Session Only: ```export PATH=$PATRH:*<path_to_kubebuilder>*```
On Reboot: ```sudo nano ~/.profile```
Add export path at the end of the file: ```export PATH=$PATRH:*<path_to_kubebuilder>*```

**Comment by ZynnLyr** [comment]
> You'll be fine. I did a sanity check right now:
> 
> ```shell
> git clone git@github.com:kubernetes-sigs/kubebuilder
> cd kubebuilder
> go build -o kubebuilder.exe ./cmd/
> ./kubebuilder.exe # works
> ```

@alexeldeib It works brilliant, however I am having issues when I use the command `kubebuilder create api`, which calls `make generate`. The problem is that, the `Makefile` used is written for Unix systems, so `make generate` reports error.

**Comment by THMAIL** [comment]
> 

it doesn't work at all !!!

I have tried , but when I execute "kubebuilder version", error occured and shows that
`time="2022-08-17T15:25:25+08:00" level=error msg="could not get plugins root: Host not supported: windows"
time="2022-08-17T15:25:25+08:00" level=error msg="Host not supported: windows"
Version: main.version{KubeBuilderVersion:"unknown", KubernetesVendor:"unknown", GitCommit:"$Format:%H$", BuildDate:"1970-01-01T00:00:00Z", GoOs:"unknown", GoArch:"unknown"}`

**Comment by camilamacedo86** [comment]
Closed in favor of : https://github.com/kubernetes-sigs/kubebuilder/issues/2940
