### ISSUE TITLE
Add target to build kubebuilder-tools for windows

### ISSUE THREAD

**Issue by camilamacedo86** [kubernetes-sigs/kubebuilder#3005]
### What do you want to happen?

Relate to : https://github.com/kubernetes-sigs/kubebuilder/pull/2984

**Comment by codablock** [comment]
@jmrodri May I ask why this was closed? I can not see the windows artefacts in the GCS bucket: https://storage.googleapis.com/kubebuilder-tools

**Comment by camilamacedo86** [comment]
Accepted since we approved the PR already we just need to have access to GPC to enable the build target.

**Comment by camilamacedo86** [comment]
Hi @codablock,

It is done now. You can check:

<img width="612" alt="Screenshot 2023-01-13 at 03 24 02" src="https://user-images.githubusercontent.com/7708031/212230068-79c6474a-c798-4d11-8781-6c2197982fbc.png">

Thank you a lot for your contribution.
