### ISSUE TITLE
Add an action for linting the YAML files that are generated during scaffolding

### ISSUE THREAD

**Issue by everettraven** [kubernetes-sigs/kubebuilder#3019]
### What do you want to happen?

**Description:**
We should add a GitHub Action to run lint checks against the YAML files that are generated as part of scaffolding out a project. 

A popular action seems to be: https://github.com/marketplace/actions/yaml-lint

**Motivation:**
Operator-SDK uses a `yamllint` check as part of the ansible plugin e2e molecule tests and it has failed a few times in the past due to trailing spaces or improper indenting from the YAML files generated by the kustomize plugin. In the past we have gone back and created PRs to fix the scaffolded files, but this becomes tedious to have to do every time we bump the Kubebuilder version we use.

It would be much nicer to have a validation check on Kubebuilder that ensures that the generate YAML passes lint checks that runs on all PRs so we can catch it earlier.

An example of a workaround the ansible plugin has had to implement due to a lint error from the YAML generated by Kubebuilder v3.7.0: https://github.com/operator-framework/operator-sdk/pull/6047#discussion_r995764399

**Comment by camilamacedo86** [comment]
Hi @everettraven,

Could you please push a PR to fix the yaml which has the lint issue?
Also, please feel free to push a PR which will add a CI test (GitHub action) to lint the yaml files generated in the testdata samples. I do not see any problem to do it.   

Indeed would be great if we are able to do the same check to lint the golang code generated with golangci-lint and we have an issue open for that, see: https://github.com/kubernetes-sigs/kubebuilder/issues/1887
