### ISSUE TITLE
Add support for scale subresource

### ISSUE THREAD

**Issue by Gimi** [kubernetes-sigs/kubebuilder#303]
Currently, kubebuilder only supports the "// +kubebuilder:subresource:status" status subresource comment directive. The scale subresource is missing.

Expect:
* Support "// +kubebuilder:subresource:scale" comment directive in apis/resource.

**Comment by droot** [comment]
@Gimi just an FYI, Kubebuilder's new release (soon-ish) will be making use of https://github.com/kubernetes-sigs/controller-runtime libraries which removes the need for generated clientset. Subresource support is not in the first version of the client libraries there, but will be added in subsequent release.

**Comment by droot** [comment]
@fanzhangio Can you investigate what all work will be required to add support for `Status` and `Scale` subresource on client library in https://github.com/kubernetes-sigs/controller-runtime

**Comment by fanzhangio** [comment]
Sure. @droot

**Comment by fanzhangio** [comment]
controller-tool now support ` subresource:scale` tags

https://github.com/kubernetes-sigs/controller-tools/pull/69
