### ISSUE TITLE
Update tutorial to no longer use  batch/v1beta1 API version of CronJob which is no longer be served in v1.25

### ISSUE THREAD

**Issue by camilamacedo86** [kubernetes-sigs/kubebuilder#3031]
### What do you want to happen?

Update tutorial to no longer use  batch/v1beta1 API version of CronJob which is no longer be served in v1.25

### Extra Labels

/kind cleanup

**Comment by krishnaindani** [comment]
hey, whuich version does this need to be updated with? Could I work on this?

**Comment by camilamacedo86** [comment]
Hi @krishnaindani, 

That is great. See https://kubernetes.io/docs/reference/using-api/deprecation-guide/#cronjob-v125 we need replace batch/v1beta1 with batch/v1 in the tutorial samples: https://github.com/kubernetes-sigs/kubebuilder/search?q=batch%2Fv1beta1

That means, replace:

```
batchv1beta1 "k8s.io/api/batch/v1beta1"
```

With:


 ```
batchv1 "k8s.io/api/batch/v1"
```

**Comment by krishnaindani** [comment]
Thanks, Could you assign this to me? Okay, I will start working on this.

**Comment by krishnaindani** [comment]
Have created a pr here, could you please review this and let me know if any changes needs to be done?
