### ISSUE TITLE
Proposal: Use `klog` as kubebuilder default logger

### ISSUE THREAD

**Issue by astraw99** [kubernetes-sigs/kubebuilder#3036]
### What do you want to happen?

Using the latest kubebuilder cli, quick start a new project based on the [official document](https://book.kubebuilder.io/quick-start.html).
After `make deploy IMG=xxx/xxx:tag`, the controller-pod log time is just long numbers (1.6656692709539523e+09):
```
1.6656692709539523e+09  INFO    controller-runtime.metrics      Metrics server is starting to listen    {"addr": "127.0.0.1:8080"}
1.665669270954326e+09   INFO    setup   starting manager
1.6656692709546785e+09  INFO    Starting server {"path": "/metrics", "kind": "metrics", "addr": "127.0.0.1:8080"}
1.6656692709546802e+09  INFO    Starting server {"kind": "health probe", "addr": "[::]:8081"}
I1013 13:54:30.954681       1 leaderelection.go:248] attempting to acquire leader lease demo/demo-controller-manager...
I1013 13:54:30.961182       1 leaderelection.go:258] successfully acquired lease demo/demo-controller-manager
1.6656692709613848e+09  INFO    Starting EventSource    {"controller": "demo", "controllerGroup": "demo.domain.com", "controllerKind": "Demo", "source": "kind source: *v1beta1.Demo"}
1.66566927096143e+09    INFO    Starting Controller     {"controller": "demo", "controllerGroup": "demo.domain.com", "controllerKind": "Demo"}
1.6656692709612472e+09  DEBUG   events  demo-controller-manager-5fdd9c945d-6dgmr_0bba29ee-109a-4ced-add9-d773c4ff839f became leader     {"type": "Normal", "object": {"kind":"Lease","namespace":"demo","name":"demo-controller-manager","uid":"dc9449e9-d589-4c2e-a0ab-5835f4ab96a4","apiVersion":"coordination.k8s.io/v1","resourceVersion":"130007662"}, "reason": "LeaderElection"}
1.665669271061787e+09   INFO    Starting workers        {"controller": "demo", "controllerGroup": "demo.domain.com", "controllerKind": "Demo", "worker count": 1}
```

Should make it human readable like:
```
I1013 13:54:30.954681       1 leaderelection.go:248] attempting to acquire leader lease demo/demo-controller-manager...
I1013 13:54:30.961182       1 leaderelection.go:258] successfully acquired lease demo/demo-controller-manager
```

Related issue: https://github.com/kubernetes-sigs/controller-runtime/issues/2024

With the latest PR merged: https://github.com/kubernetes-sigs/controller-runtime/pull/2029, tried using it got the log:
```
go get sigs.k8s.io/controller-runtime@090611b34874e78792f30a36d9fa20f2c6de9abb
make run

2022-10-22T18:06:01+08:00       INFO    controller-runtime.metrics      Metrics server is starting to listen    {"addr": ":8080"}
2022-10-22T18:06:01+08:00       INFO    setup   starting manager
2022-10-22T18:06:01+08:00       INFO    controller-runtime.webhook.webhooks     Starting webhook server
2022-10-22T18:06:01+08:00       INFO    Starting server {"path": "/metrics", "kind": "metrics", "addr": "[::]:8080"}
2022-10-22T18:06:01+08:00       INFO    Starting server {"kind": "health probe", "addr": "[::]:8081"}
2022-10-22T18:06:01+08:00       INFO    Stopping and waiting for non leader election runnables
2022-10-22T18:06:01+08:00       INFO    Stopping and waiting for leader election runnables
I1022 18:06:01.310466   82983 leaderelection.go:248] attempting to acquire leader lease demo/demo-controller-manager...
2022-10-22T18:06:01+08:00       INFO    Starting EventSource    {"controller": "demo", "controllerGroup": "demo.domain.com", "controllerKind": "Demo", "source": "kind source: *v1beta1.Demo"}
2022-10-22T18:06:01+08:00       INFO    Starting Controller     {"controller": "demo", "controllerGroup": "demo.domain.com", "controllerKind": "Demo"}
2022-10-22T18:06:01+08:00       INFO    Starting workers        {"controller": "demo", "controllerGroup": "demo.domain.com", "controllerKind": "Demo", "worker count": 1}
```
But the result log format (no file and line info) is not consistent with the klog format, as in the upper `leaderelection` line.
So propose to use `klog` to make it consistent with the K8s core components, like:
```
I1016 23:41:42.700531   61722 listener.go:44] "controller-runtime/metrics: Metrics server is starting to listen" addr=":8080"
I1016 23:41:42.701073   61722 main.go:115] "setup: starting manager"
I1016 23:41:42.701251   61722 internal.go:362] "Starting server" kind="health probe" addr="[::]:8081"
I1016 23:41:42.701255   61722 internal.go:362] "Starting server" path="/metrics" kind="metrics" addr="[::]:8080"
```

## Pros
- Make the log format human readable (with file and line info)
- Keep consistent with the K8s core components (kube-apiserver/controller-manager)
- Also support customized option flags by `klog.InitFlags(klogFlags)`
- Remove dependency on zap logger

## Cons
- Add a new klog dependency

**Comment by astraw99** [comment]
@camilamacedo86 @alvaroaleman @joelanford
c/c @jmrodri @varshaprasad96

**Comment by camilamacedo86** [comment]
Hi @astraw99,

By looking at your example using klog:  (proposed PR changes https://github.com/kubernetes-sigs/kubebuilder/pull/3033 )

```
I1016 23:41:42.700531   61722 listener.go:44] "controller-runtime/metrics: Metrics server is starting to listen" addr=":8080"
I1016 23:41:42.701073   61722 main.go:115] "setup: starting manager"
I1016 23:41:42.701251   61722 internal.go:362] "Starting server" kind="health probe" addr="[::]:8081"
I1016 23:41:42.701255   61722 internal.go:362] "Starting server" path="/metrics" kind="metrics" addr="[::]:8080"
```

- It is not logging the controllers/kind  that will be reconciled 
- it does not provide diff levels to allow admins to increase them to debug level for example
- it does not allow config by flags. 

Am I right?
So, could you please check that and see if would be possible to ensure that the same behaviours with as well? 

Note that the logs done by controller-runtime by default (as it is today) adopt the same k8s format.

**Comment by grzesuav** [comment]
@astraw99 for human readability you can adjust `zap` configuration it is very readable logger.

**Comment by grzesuav** [comment]
Currently in go ecosystem `logr` as interface is frequently used, zap also implements this - https://github.com/go-logr/zapr


Full list - https://github.com/go-logr/logr#implementations-non-exhaustive

Among the choices, `zap` is rather fast one - https://github.com/uber-go/zap#performance


IMO in scaffolding all places generic `logr` should be used as interface, with `zap` configured in init. It allows to easy change the logging backed if anyone need that.

**Comment by camilamacedo86** [comment]
Hi @grzesuav and @everettraven, 

> @camilamacedo86 reading through some of the comments here I really like the idea proposed by @grzesuav where we potentially change all logging instances in the default scaffold to use a logging interface (as @grzesuav mentioned logr seems to be pretty widely used). What do you think of this @camilamacedo86 ?

WDYT about creating a PR with the suggestions so that we can have a better idea and discuss the proposed solution?

**Comment by astraw99** [comment]
@grzesuav @camilamacedo86 @varshaprasad96 
From the current code:
https://github.com/kubernetes-sigs/kubebuilder/blob/15bd05e86b0ce71b0ca03b7d180c9a591d90403d/pkg/plugins/golang/v3/scaffolds/internal/templates/main.go#L232-L238

We can see the `ctrl.SetLogger(...)` already use `go-logr/zapr` as an basic interface, to let the user choose
which logger impl to use.

In this proposal, we just want to use the `klog` as the default logger impl, the pros and cons are listed above.
PTAL thanks.

**Comment by grzesuav** [comment]
@astraw99 

looking at what you wrote

> Make the log format human readable (with file and line info)

the log format should be machine readable, to be able to be parsed by logstash/kibana/etc

In case you need to change it to human readable in dev env, just run you code with flag
```
--zap-devel
```

> Keep consistent with the K8s core components (kube-apiserver/controller-manager)


Not sure why it is a pros, k8s komponent are in major refactoring to use structured logging, which isn't easy considering the codebase. Among logr compatibile loggers zap is more perfomant than klog

> Also support customized option flags by klog.InitFlags(klogFlags)

The same for zap - https://pkg.go.dev/sigs.k8s.io/controller-runtime/pkg/log/zap#Options.BindFlags

**Comment by grzesuav** [comment]
@varshaprasad96 @camilamacedo86 sure, will try to do it over the weekend

**Comment by grzesuav** [comment]
@camilamacedo86 @varshaprasad96 after looking onto code it seems there is no much to extract as as @astraw99 noticed the only place which require change is logger initialization and import.

However looking onto code it seems it can be parameterized (i.e. by default generate `zap` thing, but when some parameter is passed use `klog` instead)

I can add it, the changes in the template will be (I put `NEW MARKER FOR LOGGER...` in places requiring change)
```go
var mainTemplate = `{{ .Boilerplate }}

package main

import (
	"flag"
	"os"

	// Import all Kubernetes client auth plugins (e.g. Azure, GCP, OIDC, etc.)
	// to ensure that exec-entrypoint and run can make use of them.
	_ "k8s.io/client-go/plugin/pkg/client/auth"

	"k8s.io/apimachinery/pkg/runtime"
	utilruntime "k8s.io/apimachinery/pkg/util/runtime"
	clientgoscheme "k8s.io/client-go/kubernetes/scheme"
	ctrl "sigs.k8s.io/controller-runtime"
	"sigs.k8s.io/controller-runtime/pkg/log/zap"
        %s - NEW MARKER FOR LOGGER IMPORT
	"sigs.k8s.io/controller-runtime/pkg/healthz"
	%s
)

var (
	scheme = runtime.NewScheme()
	setupLog = ctrl.Log.WithName("setup")
)

func init() {
	utilruntime.Must(clientgoscheme.AddToScheme(scheme))

	%s
}

func main() {
{{- if not .ComponentConfig }}
	var metricsAddr string
	var enableLeaderElection bool
	var probeAddr string
	flag.StringVar(&metricsAddr, "metrics-bind-address", ":8080", "The address the metric endpoint binds to.")
	flag.StringVar(&probeAddr, "health-probe-bind-address", ":8081", "The address the probe endpoint binds to.")
	flag.BoolVar(&enableLeaderElection, "leader-elect", false,
		"Enable leader election for controller manager. " +
		"Enabling this will ensure there is only one active controller manager.")
{{- else }}
  var configFile string
	flag.StringVar(&configFile, "config", "", 
		"The controller will load its initial configuration from this file. " +
		"Omit this flag to use the default configuration values. " +
		"Command-line flags override configuration from this file.")
{{- end }}
	 %s - NEW MARKER FOR LOGGER INIT
	flag.Parse()

	ctrl.SetLogger(%s - NEW MARKER FOR LOGGER SETTING)
```


want to ask before going forward though

**Comment by grzesuav** [comment]
alternative would be to use `{{ .LoggerImport }}` `{{ .LOGGER_INIT }}` variables, should be more readable than code generation markers as the code placed there will be rather static

**Comment by everettraven** [comment]
@grzesuav Thanks for your analysis! Thinking about this a bit more and seeing what @astraw99 [commented](https://github.com/kubernetes-sigs/kubebuilder/issues/3036#issuecomment-1302902838) I *personally* feel like this should be a no-op.

With the default logging scaffold in the `main.go` file being:
```go
	opts := zap.Options{
		Development: true,
	}
	opts.BindFlags(flag.CommandLine)
	flag.Parse()

	ctrl.SetLogger(zap.New(zap.UseFlagOptions(&opts)))
```

It seems like it would pretty trivial to manually convert this to:
```go
	opts.BindFlags(flag.CommandLine)
	flag.Parse()


	ctrl.SetLogger(klog.New())
```

Since the default scaffolding has been `zap` for so long I feel like changing it to klog as the default would be considered a "breaking" change due to how many users Kubebuilder has and what their expectations of the default logger being used is. 

My suggestion would be that if it isn't made clear in the Kubebuilder documentation how to change the logger that we add a new section to the FAQ about how to do this.

@camilamacedo86 @varshaprasad96 WDYT?

**Comment by camilamacedo86** [comment]
I agree with @everettraven +1000.Also: 
- more than one user above comment that they prefer use zap instead of klog, see; https://github.com/kubernetes-sigs/kubebuilder/issues/3036#issuecomment-1293512725
- and how to use klog instead was added to a FAQ section already see: https://github.com/kubernetes-sigs/kubebuilder/blob/master/docs/book/src/faq.md#id-like-to-customize-my-project-to-use-klog-instead-of-the-zap-provided-by-controller-runtime-how-to-use-klog-or-other-loggers-as-the-project-logger

So, (ihmo) I think we could close this one as not accept. 

_PS.: However, if you folks see that community/users would prefer we scaffold klog by default instead of zap then, ihmo this change should be done only for go-v4/alpha._

**Comment by grzesuav** [comment]
sure thing. IMO changing to `klog` is easy enough, also as I stated `zap` is configurable enough with sensible defaults to production use, it can be configured to produce user-readable logs for development also.

Regarding maturity, as I mentioned earlier zap is faster , so changing to klog feels to me like going into wrong direction.

**Comment by astraw99** [comment]
OK, after discussion, we prefer to use `zap` as default logger.
Will close this proposal.
