### ISSUE TITLE
Bump k8s to 1.26

### ISSUE THREAD

**Issue by jmrodri** [kubernetes-sigs/kubebuilder#3054]
### What do you want to happen?

To bump to use Kubernetes version 1.26 we need to:

- [x] Generate the envtools for it (it is done)

The build is made from the branch [tools-releases](https://github.com/kubernetes-sigs/kubebuilder/tree/tools-releases). So, we need to create a PR to generate tools with the latest binaries version

- [x]  bump controller-tools for a version using the k8s 1.26 - https://github.com/kubernetes-sigs/kubebuilder/pull/3147

- [ ]  the declarative plugin usually also needs to be updated: https://github.com/kubernetes-sigs/kubebuilder/blob/master/pkg/plugins/golang/declarative/v1/api.go#L35 (we usually contribute with the project to ensure that is bumped to use the latest k8s version) 
- PR:  https://github.com/kubernetes-sigs/kubebuilder-declarative-pattern/pull/291/files

- [x]  bump controller-runtime latest release using k8s 1.26 (go/v3 and go/v4-alpha plugins only): https://github.com/kubernetes-sigs/kubebuilder/pull/3147

- [x]  Update kubebuilder CLI to use the k8s 1.26 -> it is no longer required because we remove the alpha option gen-config.

- [x]  Update the CI for we begin to test against k8s 1.26, see: https://github.com/kubernetes-sigs/kubebuilder/blob/master/CONTRIBUTING.md#where-the-ci-tests-are-configured

**Comment by akankshakumari393** [comment]
Hey I would like to work on this issue. Thanks.

**Comment by jmrodri** [comment]
@akankshakumari393 great. Thank you!

**Comment by camilamacedo86** [comment]
Hi @akankshakumari393, 

Are you working on this one?

**Comment by akankshakumari393** [comment]
Hey @camilamacedo86, yeah I am working on this.

**Comment by camilamacedo86** [comment]
This one is done and will be available in the next release
