### ISSUE TITLE
"owner" object support for admissions.Validator

### ISSUE THREAD

**Issue by stackbaek** [kubernetes-sigs/kubebuilder#3062]
### What do you want to happen?

I am writing a webhook for CRs, which I oftentimes need to reference/check against their owner CRs. I wanted to leverage `admission.Validator` as much as I can, but it doesn't allow passing in its owner object. Is there a plan for supporting owner CR as part of `admission.Validator` interface? 

I know there's CustomValidator, so I could technically pass in owner object as part of ctx, but it feels hacky and wondering if this can be done as a first class concept in the API.

**Comment by camilamacedo86** [comment]
Hi @stackbaek, 

For we better understand your request could you please let us know more about?
Could you please provide an example if possible with code snipt to answer the following questions? 
 
- a) What are you doing? 
- b) What is the current behaviour?
- c) What is your expected bahaviour?
- d) What do you expected to do ?
