### ISSUE TITLE
check for tool version in Makefile before installing

### ISSUE THREAD

**Issue by coriaedu** [kubernetes-sigs/kubebuilder#3068]
#### Describe the problem you need a feature to resolve.

The **Makefile** that is scaffolded for golang has two targets that will download [`controller-gen`](https://github.com/kubernetes-sigs/kubebuilder/blob/6f1f8c43cfbf260c971037ff039cca86a0980006/pkg/plugins/golang/v3/scaffolds/internal/templates/makefile.go#L205) and [`kustomize`](https://github.com/kubernetes-sigs/kubebuilder/blob/6f1f8c43cfbf260c971037ff039cca86a0980006/pkg/plugins/golang/v3/scaffolds/internal/templates/makefile.go#L200) tools, with the versions corresponding to `CONTROLLER_TOOLS_VERSION` and `KUSTOMIZE_VERSION` vars.

The recipes there are currently checking for file existence before installing the tool, but they don't confirm the version.

In my scenario, where I am upgrading the OSDK, I found this issue with the current Makefile:

* checkout clean branch with OSDK 1.24.0
* Run `make controller-gen` -> This will download controller-gen v0.9.2 at `$(LOCALBIN)`
* upgrade OSDK to 1.25.1
    * This includes updating the `CONTROLLER_TOOLS_VERSION` to `v0.10.0`
* Run any command that uses `controller-gen` thinking that `v0.10.0` will be used, but it is still running `0.9.2`

The same thing applies when I switch branches that have different OSDK versions

This applies to `kustomize` also.

#### Describe the solution you'd like.

I'd like the `controller-gen` and `kustomize` targets to check for version so we ensure that it matches the corresponding VERSION var.

**Comment by coriaedu** [comment]
Originally opened this at https://github.com/operator-framework/operator-sdk/issues/6173

**Comment by camilamacedo86** [comment]
+1 @coriaedu would you like to collab with?

**Comment by coriaedu** [comment]
> +1 @coriaedu would you like to collab with?

Yes, @camilamacedo86 . But as part of the [IBM Organization](https://github.com/IBM), I still need some approvals inside the company before I contribute to OSS. Hopefully it will be sorted out in a couple of days.
