### ISSUE TITLE
Generated CRD has error when subresources is used

### ISSUE THREAD

**Issue by Gimi** [kubernetes-sigs/kubebuilder#307]
To reproduce the issue:
1. prepare a k8s cluster that supports custom resource subresource
2. create a resource use `kubebuilder` cli
3. in the resource type file `pkg/apis/<group>/<version>/<resource>_type.go`, add the status subresource comment directive `// +kubebuilder:subresource:status`
4. run `kubebuilder generate`
5. build the controller manager, and run it against the k8s cluster prepared on step 1, and you will get error like this:
```
FATA[0000] Could not create CRDs:  blah blah blah ... if subresources for custom resources are enabled, only properties can be used at the root of the schema
```

To fix this, the generated CRD should not have `Type: "object"` in `OpenAPIV3Schema`.

**Comment by droot** [comment]
Can you also share the generated schema and expected schema highlighting the difference ?

**Comment by Liujingfang1** [comment]
This is related to subresources for CRD.  Maybe running it on a 1.11 cluster?

**Comment by mheese** [comment]
@droot , you have addressed this here if I see this correctly?

https://github.com/kubernetes-sigs/controller-tools/pull/72

**Comment by droot** [comment]
Yes, this should be fixed now, so closing this.

**Comment by sebgl** [comment]
It looks like this bug went back in: https://github.com/kubernetes-sigs/controller-tools/issues/296
I guess we may have lost code changes from https://github.com/kubernetes-sigs/controller-tools/pull/72?
