### ISSUE TITLE
Custom RBAC will be overwritten by `make manifests`

### ISSUE THREAD

**Issue by astraw99** [kubernetes-sigs/kubebuilder#3075]
### What broke? What's expected?

Firstly, we define the CRD resource by scaffolding `kubebuilder create api --group xxx --version xxx --kind xxx`.
Then do `make manifests` will generate controller related RBAC yamls in `config/rbac/*.yaml`.

But when we want to add custom RBAC rules appending the `role.yaml`, like below:
```
... # append role.yaml
- apiGroups:
    - batch
  resources:
    - jobs
    - cronjobs
  verbs:
    - '*'
```
Do `make manifests` again, the appended custom RBAC rules will be overwritten (deleted).

### Reproducing this issue

1. Do `kubebuilder create api --group xxx --version xxx --kind xxx`;
2. Do `make manifests`;
3. Add custom RBAC rules appending the `role.yaml`, like above;
4. Do `make manifests` again, the custom RBAC rules will be overwritten (deleted).

### KubeBuilder (CLI) Version

Version: main.version{KubeBuilderVersion:"3.7.0", KubernetesVendor:"1.24.1", GitCommit:"3bfc84ec8767fa760d1771ce7a0cb05a9a8f6286", BuildDate:"2022-09-20T17:21:57Z", GoOs:"darwin", GoArch:"amd64"}

**Comment by camilamacedo86** [comment]
Hi @astraw99,

To change the rules you ought to use the markers https://book.kubebuilder.io/reference/markers.html. You can also check the scaffold generated from deploy-image plugin as well:

https://github.com/kubernetes-sigs/kubebuilder/blob/bff13b2331e9727f1d255220a67ca51510ee8d5b/testdata/project-v3-with-deploy-image/controllers/busybox_controller.go#L63-L68

Therefore, it is not an issue. This files are auto generate/updated. You can add new ones if you wish in the directory.

Closing this one, however, feel free to re-open if you see that it is required.

**Comment by astraw99** [comment]
Got it, thanks.
