### ISSUE TITLE
ci merged a PR even though the test failed

### ISSUE THREAD

**Issue by coriaedu** [kubernetes-sigs/kubebuilder#3083]
### What broke? What's expected?

At issue https://github.com/kubernetes-sigs/kubebuilder/pull/3077, the **k8s-ci-robot** merged the pulled request even though testing failed, as detailed here: https://github.com/kubernetes-sigs/kubebuilder/pull/3077#issuecomment-1317613311

Opening an issue per request of @camilamacedo86 (https://github.com/kubernetes-sigs/kubebuilder/pull/3079#issuecomment-1317723838) to do a postmortem 

### KubeBuilder (CLI) Version

N/A

**Comment by camilamacedo86** [comment]
We need to check the configurations. Seems that are not tests configured as required tests when should be.

**Comment by camilamacedo86** [comment]
Hi @coriaedu, 

The problem is here: https://github.com/kubernetes/test-infra/blob/master/config/jobs/kubernetes-sigs/kubebuilder/kubebuilder-presubmits.yaml#L25. We need to update this optional:true with false instead.

Would you like to contribute with this one?

c/c@everettraven

**Comment by coriaedu** [comment]
@camilamacedo86 sure. I will create PR to change that value
