### ISSUE TITLE
Improve PROJECT file documentation

### ISSUE THREAD

**Issue by danaradg** [kubernetes-sigs/kubebuilder#3088]
### What do you want to happen?

The kubebuilder book has a page for the `PROJECT` file that documents its structure, but doesn't provide an overview of its purpose and effect.
Following [this](https://groups.google.com/g/kubebuilder/c/5c4_Xc3Fjx0/) discussion it was suggested to incorporate the answer into the documentation.

### Extra Labels

/kind documentation

**Comment by varshaprasad96** [comment]
@danaradg Thanks for raising the issue. Would you open to submitting a PR to fix this issue?

**Comment by danaradg** [comment]
I would love to contribute, but will probably need some time to ramp up and better understand the kubebuilder arch and plugins in general. If you don't mind waiting, I don't mind putting the effort. Would also love reading material recommendations.

**Comment by Sajiyah-Salat** [comment]
I have gone through the merged pr and google group conversation. is @danaradg working on this issue.

**Comment by danaradg** [comment]
Honestly, haven't gotten around to it. If you want to take over, feel free.

**Comment by Sajiyah-Salat** [comment]
Great. Thank you.
/assign

**Comment by ashutosh887** [comment]
Please let me work on this issue @camilamacedo86 @varshaprasad96

**Comment by camilamacedo86** [comment]
HI @Sajiyah-Salat,
 
Yes, this issue still valid. We need to improve the documentation with what was shared in the email thread.

**Comment by Sajiyah-Salat** [comment]
Sure. I will work on that shortly.

**Comment by Sajiyah-Salat** [comment]
can you please guide me to the file where you would like to seethe proejct information.

**Comment by varshaprasad96** [comment]
@Sajiyah-Salat you could add more details on what PROJECT config file is in here: https://book.kubebuilder.io/reference/project-config.html

**Comment by Sajiyah-Salat** [comment]
Hello @ashutosh887 you have worked well on this pr. congrats on this. I think the work is completed now. Should we close this pr? wdyt? @camilamacedo86

**Comment by ashutosh887** [comment]
Yes the PR is merged as well @Sajiyah-Salat @camilamacedo86

**Comment by Sajiyah-Salat** [comment]
I know that.

**Comment by ashutosh887** [comment]
Let's close this then 😄🙌🏻
