### ISSUE TITLE
Parallelize the tests

### ISSUE THREAD

**Issue by droot** [kubernetes-sigs/kubebuilder#309]
Observed in travis that test.sh is taking close to 20~25 mins which is very slow.

I am sure there are some low hanging fruits to speed up the tests for ex. being able to run them in parallel. So this task is to investigate how we can speed up the tests and also remove invalid tests (if there are any).

**Comment by droot** [comment]
cc @mengqiy

**Comment by fanzhangio** [comment]
It seems like `init project with dep ensure` are executed multiple times, which is major overhead. It requires to have better scheduled.

**Comment by mengqiy** [comment]
One thing we can do to get speeding up a lot is:
init the project (including dep ensure) once and then copy the project directory to all other tests.
Then other tests can run in parallel w/o `dep ensure`.

**Comment by fanzhangio** [comment]
I am thinking if we can cache the dependencies in a static dir, and refer to reuse it.

**Comment by mengqiy** [comment]
Yeah, that's another way to do that.

**Comment by droot** [comment]
We probably don't need this now. Closing it.
