### ISSUE TITLE
defined field cannot get the value

### ISSUE THREAD

**Issue by zhujintao** [kubernetes-sigs/kubebuilder#3092]
### What broke? What's expected?

type:

```go
type DeploysSpec struct {
AppConf map[string]map[string][]string json:"appConf,omitempty"
}
```
yaml:
appConf:
  core:
    b2b-plus:
    bps-core:

spec:
  appConf:
     core: {}

### Reproducing this issue

How to get spec.appConf.core key name b2b-plus 、 bps-core

### KubeBuilder (CLI) Version

Version: main.version{KubeBuilderVersion:"3.7.0", KubernetesVendor:"1.24.1", GitCommit:"3bfc84ec8767fa760d1771ce7a0cb05a9a8f6286", BuildDate:"2022-09-20T17:21:57Z", GoOs:"linux", GoArch:"amd64"}

**Comment by zhujintao** [comment]
@varshaprasad96 
no  b2b-plus  , bps-core in crd spec.appConf.core

```
  appConf:
    core:
      b2b-plus:
      bps-core: 

```

this syntax can， ok
```
  appConf:
    core:
      b2b-plus: []
      bps-core: []

**Comment by varshaprasad96** [comment]
@zhujintao in general a CR's spec can be accessed by `.spec.<key>`. Based on whether the value is a string, array or map, we can access the objects as we would in normal go language. Were you able to solve the issue, or would you like us to look at any specific CR?

**Comment by camilamacedo86** [comment]
Closing this one since we have had no interactions so far. 
However, feel free to raise new issues if you need.
