### ISSUE TITLE
About the RABC

### ISSUE THREAD

**Issue by Diwan9527** [kubernetes-sigs/kubebuilder#3105]
### What broke? What's expected?

when I  run as the Quickstart, I met a problem with the  rabc. why it  does't add job.batch automatic ? All the code I copy from the  https://book.kubebuilder.io/cronjob-tutorial/cronjob-tutorial.html . Kindly anybody help? 

<img width="1269" alt="image" src="https://user-images.githubusercontent.com/114134539/204765096-143b7cde-36cf-4c0f-84bd-4f5124f59fb2.png">

 manager: Container log
E1130 09:49:18.202269       1 reflector.go:140] pkg/mod/k8s.io/client-go@v0.25.0/tools/cache/reflector.go:169: Failed to watch *v1.Job: failed to list *v1.Job: jobs.batch is forbidden: User "system:serviceaccount:test-operator-system:test-operator-controller-manager" cannot list resource "jobs" in API group "batch" in the namespace "test-operator-system"
W1130 09:49:25.068788       1 reflector.go:424] pkg/mod/k8s.io/client-go@v0.25.0/tools/cache/reflector.go:169: failed to list *v1.Job: jobs.batch is forbidden: User "system:serviceaccount:test-operator-system:test-operator-controller-manager" cannot list resource "jobs" in API group "batch" in the namespace "test-operator-system"
E1130 09:49:25.068815       1 reflector.go:140] pkg/mod/k8s.io/client-go@v0.25.0/tools/cache/reflector.go:169: Failed to watch *v1.Job: failed to list *v1.Job: jobs.batch is forbidden: User "system:serviceaccount:test-operator-system:test-operator-controller-manager" cannot list resource "jobs" in API group "batch" in the namespace "test-operator-system"
W1130 09:49:38.234719       1 reflector.go:424] pkg/mod/k8s.io/client-go@v0.25.0/tools/cache/reflector.go:169: failed to list *v1.Job: jobs.batch is forbidden: User "system:serviceaccount:test-operator-system:test-operator-controller-manager" cannot list resource "jobs" in API group "batch" in the namespace "test-operator-system"
E1130 09:49:38.234754       1 reflector.go:140] pkg/mod/k8s.io/client-go@v0.25.0/tools/cache/reflector.go:169: Failed to watch *v1.Job: failed to list *v1.Job: jobs.batch is forbidden: User "system:serviceaccount:test-operator-system:test-operator-controller-manager" cannot list resource "jobs" in API group "batch" in the namespace "test-operator-system"

### KubeBuilder (CLI) Version

3.7

### PROJECT version

v1

### Extra Labels

/kind documentation

**Comment by varshaprasad96** [comment]
@Diwan9527 The `role.yaml` is generated from the kubebuilder markers which are defined in `controller.go`. The user can specify the rbac for specific groups through kubebuilder markers (https://book.kubebuilder.io/reference/markers/rbac.html?highlight=rbac#rbac). These are usually added on `controller.go`, similar to https://github.com/kubernetes-sigs/kubebuilder/blob/master/testdata/project-v3/controllers/admiral_controller.go#L36-L38. I realized we have some better documentation around these in Operator SDK - https://sdk.operatorframework.io/docs/building-operators/golang/tutorial/#specify-permissions-and-generate-rbac-manifests

**Comment by Diwan9527** [comment]
I had add it at the controllers as below ,but is won't  work.

//+kubebuilder:rbac:groups=batch.tutorial.kubebuilder.io,resources=cronjobs,verbs=get;list;watch;create;update;patch;delete
//+kubebuilder:rbac:groups=batch.tutorial.kubebuilder.io,resources=cronjobs/status,verbs=get;update;patch
//+kubebuilder:rbac:groups=batch.tutorial.kubebuilder.io,resources=cronjobs/finalizers,verbs=update
//+kubebuilder:rbac:groups=batch,resources=jobs,verbs=get;list;watch;create;update;patch;delete
//+kubebuilder:rbac:groups=batch,resources=jobs/status,verbs=get;update;patch
//+kubebuilder:rbac:groups=batch,resources=jobs,verbs=update

**Comment by qingwave** [comment]
> I had add it at the controllers as below ,but is won't work.
> 
> //+kubebuilder:rbac:groups=batch.tutorial.kubebuilder.io,resources=cronjobs,verbs=get;list;watch;create;update;patch;delete //+kubebuilder:rbac:groups=batch.tutorial.kubebuilder.io,resources=cronjobs/status,verbs=get;update;patch //+kubebuilder:rbac:groups=batch.tutorial.kubebuilder.io,resources=cronjobs/finalizers,verbs=update //+kubebuilder:rbac:groups=batch,resources=jobs,verbs=get;list;watch;create;update;patch;delete //+kubebuilder:rbac:groups=batch,resources=jobs/status,verbs=get;update;patch //+kubebuilder:rbac:groups=batch,resources=jobs,verbs=update

@Diwan9527 I think you should run `make manifests` again to generate new rbac config and apply this in the k8s.
