### ISSUE TITLE
Change sufix testdata and fix samples

### ISSUE THREAD

**Issue by camilamacedo86** [kubernetes-sigs/kubebuilder#3110]
### What do you want to happen?

In the latest meeting, we agreed that we would replace the name of `project-v4-with-metrics` with `project-v4-with-grafana`. The change needs to be done at: https://github.com/kubernetes-sigs/kubebuilder/blob/master/test/testdata/generate.sh

Also, see that the declarative sample should not call the grafana/v1-alpha plugin. We can fix this issue this nit as well.

**Comment by jason1028kr** [comment]
Made #3111 to address the specified nits. But, let me know if I've missed something. Thanks!

**Comment by camilamacedo86** [comment]
Hi @jason1028kr,

That is great! thank you for your contribution.

It is just missing one detail. Could you please also update the name in the tests: https://github.com/kubernetes-sigs/kubebuilder/blob/d887e25e0a62eae1fd5882267bc3a53535198c6d/test/testdata/test.sh#L47

**Comment by ShivamTyagi12345** [comment]
/ assign
