### ISSUE TITLE
Changes in the docs not merged in master branch

### ISSUE THREAD

**Issue by camilamacedo86** [kubernetes-sigs/kubebuilder#3116]
### What broke? What's expected?

The changes addressed in the PR: https://github.com/kubernetes-sigs/kubebuilder/pull/2857/files are not in the master branch. We need to cherry-pick it to the master branch and ensure we have them there.

### Reproducing this issue

Check master branch and book-v3

### KubeBuilder (CLI) Version

master

**Comment by ShivamTyagi12345** [comment]
Hey @camilamacedo86  I am a bit new to this so its taking a while, Apologies for in activeness.

**Comment by camilamacedo86** [comment]
It is all fine @ShivamTyagi12345,

Note that the goal is to ensure the same content on master branch.
You can do that by cherry-pick such as:

- git checkout -b mybranch
- git cherry-pick 33c275b6f6106a0594b3a5879f8546ae0d6533c0

OR 

Just create the branch and copy and paste the content .

**Comment by ShivamTyagi12345** [comment]
I had to copy paste . Hope the changes are right in my PR

**Comment by camilamacedo86** [comment]
Closing this one as done. Thank you.
