### ISSUE TITLE
Make go/v4-alpha and kustomize/v2-alpha to be stable and the default CLI scaffold

### ISSUE THREAD

**Issue by camilamacedo86** [kubernetes-sigs/kubebuilder#3117]
### What do you want to happen?

The following is what needs to get done:

- [x] : check if we can move forward and get this one merged: https://github.com/kubernetes-sigs/kubebuilder/pull/2985
- [x] : check if we can close as deferred: https://github.com/kubernetes-sigs/kubebuilder/issues/615 (convey added on the issue)
- [x] : release as alpha. Then, ask for the community to check it out (if significant issues are found, we need to release it as beta)
- [x] : make the plugins stable and update the docs to no more extended reference it as alpha https://github.com/kubernetes-sigs/kubebuilder/pull/3237 and https://github.com/kubernetes-sigs/kubebuilder/pull/3234
- [x] : make the plugins stable and make them the default CLI scaffold https://github.com/kubernetes-sigs/kubebuilder/pull/3278
- [x] : update readme and quick start since now we will support darwin/arm64 by default, and we do not need to say for people use go/v4-alpha anymore
- [x] : deprecated go/v3 and kustomize/v1 - https://github.com/kubernetes-sigs/kubebuilder/pull/3235 and https://github.com/kubernetes-sigs/kubebuilder/pull/3238
- [x] : deprecated packages to let consumers informed https://github.com/kubernetes-sigs/kubebuilder/pull/3284
- [x] : update tutorials to use go/v4 https://github.com/kubernetes-sigs/kubebuilder/pull/3280, https://github.com/kubernetes-sigs/kubebuilder/pull/3281, https://github.com/kubernetes-sigs/kubebuilder/pull/3282

**Comment by joejulian** [comment]
There are operators that have been built using upstream controllers. Moving these controllers to internal breaks downstream projects.
