### ISSUE TITLE
Ensure the quality of the projects scaffolded within kubuilder

### ISSUE THREAD

**Issue by camilamacedo86** [kubernetes-sigs/kubebuilder#3119]
## What is the requirement?

USE CASE: I am as a developer using Kubebuilde,  I'd like that Kubebuilder to provide in the scaffold all that could be required and are common practices to ensure the quality of my project so that I do not need to implement these common needs, and I can leverage them in KB. (to speed up and skill up)

The projects scaffolded with Kubebuilder do not provide common needs:

- Does not use golangci-lint https://github.com/kubernetes-sigs/kubebuilder/issues/1887 (We could have target for that)
- Does not provide e2e tests (Kubebuilder as lib could be used to address this need). Example implementation that could be scaffolded (we need to remove the utils and ensure that we provide them via Kubebuilder as lib instead): https://github.com/operator-framework/operator-sdk/tree/master/testdata/go/v4-alpha/memcached-operator/test
- Does not provide github actions calling the e2e and unit tests 

## Proposed solution(s):

**Option A (Addressing this needs via a plugin to allow users opt-in or not by)**

Create a new plugin (qa/v1-alpha) that would:
- scaffold the golangci-lint config file ( same config used by KB ) and a new target 
- scaffold the e2e tests such as https://github.com/operator-framework/operator-sdk/tree/master/testdata/go/v4-alpha/memcached-operator/test 
- ensure that Kubebuilder can be used as lib ( exporting the same utils used in KB tests ) to allow authors perform the e2e tests (we should not scaffold the lib features as utils as in the above example)
- scaffold GitHub actions to call unit tests ( done within envtest and which are scaffolded by default ) and the e2e tests added above 
- scaffold dependabot to ensure that projects are properly updated regards their dependencies (i.e https://github.com/kubernetes-sigs/kubebuilder/blob/master/.github/dependabot.yml)

**Option B (Addressing this needs in the default scaffolds)**

In this case, the default go scaffolds would be incorporated to address the above by default.

**Comment by Kavinjsir** [comment]
I think it is a very good idea to support quality assurance. 👍🏼 
I vote for the individual plugin focusing on this feature.

Some thoughts below:
1. Considering on the fact that `golangci-lint` and `e2e tests` can be language specific, what about we create under `pkg/plugins/golang/qa/v1-alpha`?
2. One point not sure to me is the position that `kubebuilder lib` gets scaffolded. Does it depend on the existing layout of the project? (e.g: `./lib` vs `./pkg/lib`)
3. Can we expose the lib from the kubebuilder origin package where the user can import from, so that they don't necessarily have to scaffold the `lib` package?

**Comment by varshaprasad96** [comment]
Based on the discussion in community meeting, my understanding is to add this in the Kubebuilder's Makefile (https://github.com/kubernetes-sigs/kubebuilder/blob/master/Makefile) and call it in the CI so that the entire code delivered by KB developers will be checked by linter.

**Comment by Kavinjsir** [comment]
Hey @camilamacedo86 
I guess one typical question when attempting to apply the lint to scaffolded projects is:
It is likely to have unused variables in the code block.
If we run `golangci-lint` , they will be caught.
If we want them get  bypass, we may add `// nolint ...`

However, `// nolint ...` is only a matter of `golangci-lint`, which is a 3rd-party tool.
Consider on that, are these comments recommended to appear in our plugins' code template?

On the other hand, if we don't add such comments, is there a way to bypass the lint error?
OR should we change the code template to avoid lint errors such as `unused variables`?

cc: @camilamacedo86 @Eileen-Yu

**Comment by camilamacedo86** [comment]
I think it is fine we scaffold nolint ... 
It will NOT harm, create any problem for the end users.

**Comment by Eileen-Yu** [comment]
So to be more direct, the errors found are mainly `lll`, undeclared name, unused var/params, return value not checked, duplicate lines and TLS related.

For example:
<img width="1920" alt="Screen Shot 2023-02-20 at 15 00 24 PM" src="https://user-images.githubusercontent.com/48944635/220189750-36cf374b-c928-4f97-aebe-37b7812ae97b.png">

**Comment by camilamacedo86** [comment]
Hun, I see. That is a very good point because I think the annotations for example would need to be ignored.
That means, would be great if we could warn in the PRs but not block the PR merged based on it.

**Comment by Eileen-Yu** [comment]
> **Option A**
> 
> If we could warn in the PRs but not block the merge, then we could check the errors to sort them out without the need to use // nolint to ignore some scenarios.
> 
> **Option B**
> 
> We add a new target to the scaffolds using golangci-lint which would make it easier and would allow us to use the annotations. The bad side is just that it would be a new third-party added to the projects.


I would vote for the first option 👍 Updated the PR base on this.

**Comment by ashutosh887** [comment]
I would like to work on this issue @varshaprasad96  Ma'am

**Comment by ashutosh887** [comment]
@camilamacedo86  Let me work on this issue if still not resolved

**Comment by Kavinjsir** [comment]
Hey @ashutosh887 we have PRs working on this, so you can review if you wish:
- https://github.com/kubernetes-sigs/kubebuilder/pull/3216

**Comment by ashutosh887** [comment]
Sure would have a look
Thanks

**Comment by ashutosh887** [comment]
Any updates on the PR @Kavinjsir
