### ISSUE TITLE
:bug: Minor spelling and grammar typos in scaffolded README.md

### ISSUE THREAD

**Issue by mdb** [kubernetes-sigs/kubebuilder#3121]
### What broke? What's expected?

👋 Hello - thanks for your work on `kubebuilder`! It seems to me that the scaffolded project `README.md` seeded by `kubebuilder` (I believe via files in https://github.com/kubernetes-sigs/kubebuilder/tree/master/pkg/plugins/golang/v3 and https://github.com/kubernetes-sigs/kubebuilder/tree/master/pkg/plugins/golang/v4 ) has a few minor typos and grammar errors, namely:

* "until" is misspelled
* "UnDeploy the controller to the cluster" should probably read "UnDeploy the controller from the cluster"
* punctuation is missing from various sentences
* there's some trailing whitespace that could probably be cleaned up

Stay tuned; I'd be happy to attempt a PR to clean this up :) 

### KubeBuilder (CLI) Version

3.8.0

### PROJECT version

3

**Comment by camilamacedo86** [comment]
Done,
