### ISSUE TITLE
err: "no kind is registered for the type x in scheme" when use func runtime.Encode

### ISSUE THREAD

**Issue by zerunhu** [kubernetes-sigs/kubebuilder#3126]
### What broke? What's expected?

```go
sidecarSet := &setv1alpha1.SidecarSet{}
err := r.Get(context.TODO(), req.NamespacedName, sidecarSet)
if err != nil {
...
}

sc := sidecarSet.DeepCopy()
patchCodec1 := scheme.Codecs.LegacyCodec(setv1alpha1.GroupVersion)
_, err = runtime.Encode(patchCodec1, sc)
klog.Info("-----------------e: ", err)
return ctrl.Result{}, nil
```
The code will generate a "no kind is registered for the type v1alpha1.SidecarSet in scheme "pkg/runtime/scheme.go:100" error. 
But I am using a scaffold generated by kubebuilder, all the schema is already registered and I have not made any changes.
I see a similar problem but no solution #1810
**main.go**
```go
var (
	scheme   = runtime.NewScheme()
)
func init() {
	utilruntime.Must(clientgoscheme.AddToScheme(scheme))
	utilruntime.Must(setv1alpha1.AddToScheme(scheme))
	//+kubebuilder:scaffold:scheme
}
```
**api/sidecarset_types.go**
```go
func init() {
	SchemeBuilder.Register(&SidecarSet{}, &SidecarSetList{})
}
```
**api/groupversion_info.go**
```go
var (
	// GroupVersion is group version used to register these objects
	GroupVersion = schema.GroupVersion{Group: "set.kubezr.io", Version: "v1alpha1"}

	// SchemeBuilder is used to add go types to the GroupVersionKind scheme
	SchemeBuilder = &scheme.Builder{GroupVersion: GroupVersion}

	// AddToScheme adds the types in this group-version to the given scheme.
	AddToScheme = SchemeBuilder.AddToScheme
)
```

### Reproducing this issue

I reproduced my environment using a minimum of steps and code.

1. `go mod init sidecarset`
2. `kubebuilder init --domain kubezr.io`
3. `kubebuilder create api --group set --version v1alpha1 --kind SidecarSet`
4. Add the following code to the **Reconcile** function in **controller/sidecarset_controller.go**, No other code does anything
```go
func (r *SidecarSetReconciler) Reconcile(ctx context.Context, req ctrl.Request) (ctrl.Result, error) {
	_ = log.FromContext(ctx)

	// TODO(user): your logic here

	sidecarSet := &setv1alpha1.SidecarSet{}
	err := r.Get(context.TODO(), req.NamespacedName, sidecarSet)
	if err != nil {
		return reconcile.Result{}, err
	}

	sc := sidecarSet.DeepCopy()
	patchCodec1 := scheme.Codecs.LegacyCodec(setv1alpha1.GroupVersion)
	_, err = runtime.Encode(patchCodec1, sc)
	if err != nil {
		klog.Info("-----------------e: ", err)
		return reconcile.Result{}, err
	}
	return ctrl.Result{}, nil
}
```
5. `make docker-build docker-push IMG=xxx`
6. `make install && make deploy IMG=xxx`
7. Add a line `foo: test` in config/samples/set_v1alpha1_sidecarset.yaml
8. `k apply -f config/samples/set_v1alpha1_sidecarset.yaml`
9. `k logs -f xx -n xx-system` You can see the error **-----------------e: no kind is registered for the type v1alpha1.SidecarSet in scheme "pkg/runtime/scheme.go:100**

### KubeBuilder (CLI) Version

```

### PROJECT version

_No response_

### Plugin versions

_No response_

### Other versions

_No response_

### Extra Labels

_No response_

**Comment by zerunhu** [comment]
```
kubebuilder version
Version: main.version{KubeBuilderVersion:"3.2.0", KubernetesVendor:"1.22.1", GitCommit:"b7a730c84495122a14a0faff95e9e9615fffbfc5", BuildDate:"2021-10-29T18:32:16Z", GoOs:"linux", GoArch:"amd64"}
```
**go.mod**
```
module sidecarset

go 1.16

require (
        github.com/onsi/ginkgo v1.16.4
        github.com/onsi/gomega v1.15.0
        k8s.io/apimachinery v0.22.1
        k8s.io/client-go v0.22.1
        k8s.io/klog/v2 v2.9.0
        sigs.k8s.io/controller-runtime v0.10.0
)
```
```
kubectl version
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.6", GitCommit:"ad3338546da947756e8a88aa6822e9c11e7eac22", GitTreeState:"clean", BuildDate:"2022-04-14T08:49:13Z", GoVersion:"go1.17.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.4-tke.14", GitCommit:"c93cd0e4cfd27c8216a9ee2b6f1969a9d1294c5c", GitTreeState:"clean", BuildDate:"2021-08-18T11:09:02Z", GoVersion:"go1.15.10", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.23) and server (1.18) exceeds the supported minor version skew of +/-1
```

**Comment by qingwave** [comment]
Hi @zerunhu,

It's not a bug of kubebuilder, but a wrong usage of scheme. 

In the `Reconcile`, the `scheme.Codecs` the k8s default Codecs, does not contain your CRDs, you should use the `serializer.NewCodecFactory(r.Scheme)` replace
```golang
patchCodec1 := scheme.Codecs.LegacyCodec(setv1alpha1.GroupVersion)
# change to 
patchCodec1 := serializer.NewCodecFactory(r.Scheme).LegacyCodec(setv1alpha1.GroupVersion)
```

**Comment by zerunhu** [comment]
> Hi @zerunhu,
> 
> It's not a bug of kubebuilder, but a wrong usage of scheme.
> 
> In the `Reconcile`, the `scheme.Codecs` the k8s default Codecs, does not contain your CRDs, you should use the `serializer.NewCodecFactory(r.Scheme)` replace
> 
> ```go
> patchCodec1 := scheme.Codecs.LegacyCodec(setv1alpha1.GroupVersion)
> # change to 
> patchCodec1 := serializer.NewCodecFactory(r.Scheme).LegacyCodec(setv1alpha1.GroupVersion)
> ```

@qingwave  Can I add my crd in `scheme.Codecs` ? Instead of creating a new
