### ISSUE TITLE
Discovery of plugin binary on OSX not working

### ISSUE THREAD

**Issue by rocrisp** [kubernetes-sigs/kubebuilder#3129]
### What broke? What's expected?

What happened :
$kubebuilder init --plugins=sampleexternalplugin/v1 --domain example.com
"no plugin could be resolved with key "sampleexternalplugin/v1"

What's expected : 
Adding external plugin: sampleexternalplugin

### Reproducing this issue

1. add the plugin (binary)
                to ~/Library/Application Support/kubebuilder/plugins/sampleexternalplugin/v1.
2. In your project directory, run : 
                 kubebuilder init --plugins=sampleexternalplugin/v1 --domain example.com
    

### KubeBuilder (CLI) Version

Version: main.version{KubeBuilderVersion:"3.6.0", KubernetesVendor:"1.24.1", GitCommit:"f20414648f1851ae97997f4a5f8eb4329f450f6d", BuildDate:"2022-08-03T11:47:17Z", GoOs:"darwin", GoArch:"amd64"}

### PROJECT version

Not available

### Plugin versions

```yaml
Not available
```

### Other versions

go version go1.19.3 darwin/amd64

### Extra Labels

/kind documentation

**Comment by camilamacedo86** [comment]
Hi @rocrisp,

Thank you for reaching out. 

Could you do the same test within the latest release and let us know if you face the same problem? 
Also, could you please describe it step by step so we can reproduce it?

1. Run X
2. Do Y
3. Then, ....

We need also to know how you build the example plugin and etc>
 
c/c @everettraven

**Comment by rocrisp** [comment]
I will! and let you know my results.

**Comment by rocrisp** [comment]
The problem went away when I ran with latest version of Kubebuilder "3.8.0".

1. Verify kubebuilder version

$ kubebuilder version
INFO[0000] Adding external plugin: sampleexternalplugin
Version: main.version{KubeBuilderVersion:"3.8.0", KubernetesVendor:"1.25.0", GitCommit:"184ff7465947ced153b031db8de297a778cecf36", BuildDate:"2022-12-04T18:17:10Z", GoOs:"darwin", GoArch:"amd64"}

2. Initialize project using kubebuilder with the plugin.

$ kubebuilder init --plugins sampleexternalplugin/v1
INFO[0000] Adding external plugin: sampleexternalplugin

2. Verify command above created initFile.txt

$ ls
PROJECT		initFile.txt

**Comment by camilamacedo86** [comment]
HI @rocrisp, 

Thank you for provide the info.
Note that this plugin is not shipped with Kubebuilder and it is only an example over how can you create your own plugins to use within Kubebuilder. therefore, the sample must be build and configured accordingly to be used with the CLI..

 So, how are you building the  `sampleexternalplugin`?

**Comment by rocrisp** [comment]
make build

**Comment by camilamacedo86** [comment]
Hi @rocrisp 

Are you running `make build` in the root dir of the Kubebuilder project? If so, that builds Kubebuilder CLI and not the sample plugin. Or are you running make build under: https://github.com/kubernetes-sigs/kubebuilder/blob/master/docs/book/src/simple-external-plugin-tutorial/testdata/sampleexternalplugin/v1/? 

Hi @everettraven, 

have we any doc that describes how to test the sample? If so, could you please add it here? If not, and if possible, could you please add the steps here so we might get some help to add it to the docs as a follow-up? 

c/c @rashmigottipati

**Comment by camilamacedo86** [comment]
Hi @rocrisp,

> Hi @camilamacedo86 Not sure if you saw my post earlier but the sample external plugin is working after I upgraded to the latest kubebuilder.

So, that is great 🎉 . It is sorted out in the latest kubebuilder verson.

> I created my own project instead of using https://github.com/kubernetes-sigs/kubebuilder/blob/master/docs/book/src/simple-external-plugin-tutorial/testdata/sampleexternalplugin/v1/?

That is cool. We have few things that we still need to address about this one. (tutorial and e2e tests mainly). See: https://github.com/kubernetes-sigs/kubebuilder/issues/2600

Please, feel free to contribute with it and if you have any suggestion, improvements and we would love to know more about. Please, raise new issues and/or PRs for those. You help is very welcome. 

Regards this specific issue, I understand that we can close it out as sorted out within the latest kubebuilder release. Am I right?

**Comment by camilamacedo86** [comment]
Closing this one as sorted out. However, feel free to re-open if you see that something is still required to get done here.
