### ISSUE TITLE
User-added rules in Gopkg.toml not retained when updating vendor

### ISSUE THREAD

**Issue by liyinan926** [kubernetes-sigs/kubebuilder#313]
I noticed that user-added rules in `Gopkg.toml` after the comment `# Users add deps lines here` were not retained after running `kubebuilder update vendor` as suggested in http://book.kubebuilder.io/beyond_basics/upgrading_kubebuilder.html. They seemed deleted from `Gopkg.toml`, although `Gopkg.lock` seemed to include them.  This causes IDE such as intellij idea (with the dep plugin) to complain about out of sync for vendored dependencies.

**Comment by droot** [comment]
Can you share an example Gopkg.toml file from your project ?

@fanzhangio can you pl. take a look at this one ?

**Comment by liyinan926** [comment]
My `Gopkg.toml` looks like the following:

```
# Users add deps lines here

[[constraint]]
  name = "github.com/fsnotify/fsnotify"
  version = "1.4.7"

[[constraint]]
  name = "github.com/caarlos0/env"
  version = "3.2.0"

[[constraint]]
  name = "github.com/prometheus/client_golang"
  version = "0.8.0"

[[constraint]]
  branch = "master"
  name = "github.com/kubernetes-sigs/application"

[prune]
  go-tests = true
  #unused-packages = true

# Note: Stanzas below are generated by Kubebuilder and may be rewritten when
# upgrading kubebuilder versions.

# DO NOT MODIFY BELOW THIS LINE.

[[override]]
name="cloud.google.com/go"
version="v0.21.0"
......
```

After running `kubebuilder update vendor`, the dependencies I added at the top are gone.

**Comment by fanzhangio** [comment]
@liyinan926 Thanks for your feedback. I am looking into it. Quick question, may I know which version of kubebuilder you are using for this issue. We have v0, and v1 at this moment.

**Comment by liyinan926** [comment]
@fanzhangio I'm using v0.1.12 at https://github.com/kubernetes-sigs/kubebuilder/releases/tag/v0.1.12.

**Comment by liyinan926** [comment]
@fanzhangio Adding the flag `--overwrite-dep-manifest` gave me the same behavior for both values of `true` and `false`.

**Comment by droot** [comment]
@liyinan926 Thanks for the gopkg.toml file, I am able to reproduce it in my setup. Looking in to it.

@fanzhangio this is not related to `--overwrite-dep-manifest`. That flag is to override the Gopkg.toml file which is not the intent in this case.

**Comment by droot** [comment]
@liyinan926 this should be available anytime for the release from master. You can follow instructions on this [page](http://book.kubebuilder.io/getting_started/installation_and_setup.html) for installing latest master release.

**Comment by liyinan926** [comment]
Awesome! Thanks, @droot!
