### ISSUE TITLE
Doc: FAQ should be after Plugins and at the same level

### ISSUE THREAD

**Issue by camilamacedo86** [kubernetes-sigs/kubebuilder#3130]
### What do you want to happen?

Move FAQ from: https://book.kubebuilder.io/faq.html

<img width="295" alt="Screenshot 2022-12-17 at 12 13 06" src="https://user-images.githubusercontent.com/7708031/208241284-8f613011-4159-488e-93a6-7a22aea35103.png">

To be after Plugin:

<img width="305" alt="Screenshot 2022-12-17 at 12 13 33" src="https://user-images.githubusercontent.com/7708031/208241300-66ae25e7-6649-40ad-ae8b-b5c4aff8fb9c.png">

And a new section like Plugin. Look at the code to know how to do that.

**Comment by inFocus7** [comment]
Hi! Can I pick this up? 🤚🏼👀
