### ISSUE TITLE
Docs about webhook is out of date

### ISSUE THREAD

**Issue by Duncan-tree-zhou** [kubernetes-sigs/kubebuilder#3136]
### What broke? What's expected?

in doc file: [《Deploying Admission Webhooks》](https://github.com/kubernetes-sigs/kubebuilder/blob/master/docs/book/src/cronjob-tutorial/running-webhook.md#deploy-webhooks)

line #38 and line #44, the include files is no longer exists.

{{#include ./testdata/project/config/default/kustomization.yaml}}

{{#include ./testdata/project/config/crd/kustomization.yaml}}

### Reproducing this issue

goto [《Deploying Admission Webhooks》](https://github.com/kubernetes-sigs/kubebuilder/blob/master/docs/book/src/cronjob-tutorial/running-webhook.md#deploy-webhooks) 

### KubeBuilder (CLI) Version

master

### PROJECT version

master

**Comment by camilamacedo86** [comment]
Hi @Duncan-tree-zhou,

Definitely, we should link. We should to do as it is done for v2 : https://book-v2.book.kubebuilder.io/
To achieve this goal, the PR change needs to be against book-v1 branch . Would you like to collab with this one?

**Comment by impact-maker** [comment]
@camilamacedo86 I would like to collab and make some valuable contributions.

**Comment by camilamacedo86** [comment]
Hi @impact-maker 

In this case you need to push a PR against the book-v1 branch with the same content. If you have doubts please feel free to reach out in the channel.

**Comment by impact-maker** [comment]
Hi @camilamacedo86 Added the PR #3159 
Kindly review it and let me know if any changes are required on my end.

**Comment by ashutosh887** [comment]
@camilamacedo86 I would like to work on this
Please consider

**Comment by ashutosh887** [comment]
@camilamacedo86 Should I start working if the PR is not approved?

**Comment by Duncan-tree-zhou** [comment]
@ashutosh887 you can see the PR #3159, it's already closed.

**Comment by ashutosh887** [comment]
The issue is still open @Duncan-tree-zhou 
I would like to work

**Comment by camilamacedo86** [comment]
Hi @Duncan-tree-zhou,  

> @ashutosh887 you can see the PR https://github.com/kubernetes-sigs/kubebuilder/pull/3159, it's already closed.

The PR was not accepted because it was against the v1 docs, which is legacy. 

If @impact-maker will not work on this one (which seems not like) then,  @ashutosh887 please feel free to work on this one.

**Comment by ashutosh887** [comment]
Sure I'll start on this now

**Comment by Sajiyah-Salat** [comment]
hello @ashutosh887 are you still working on this. If yes link the pr. I want to review the content. if not, I am interested in working on this issue. Thank you.
