### ISSUE TITLE
"Available Plugins" mislinked in documentation.

### ISSUE THREAD

**Issue by protosam** [kubernetes-sigs/kubebuilder#3138]
I'm not really sure what to do about this, because there is clearly a bug with how the markdown is being rendered on Github as well as the Git book.

When reading through the documentation about plugins, I found that the generated documentation has a broken link here: https://github.com/kubernetes-sigs/kubebuilder/blob/master/docs/book/src/plugins/creating-plugins.md?plain=1#L24

The markdown is as follows:
```markdown
Kubebuilder provides a set of plugins to scaffold the projects, to help you extend and re-use its implementation to provide additional features.
For further information see [Available Plugins][available-plugins].
```

The rendered output seen [here on github](https://github.com/kubernetes-sigs/kubebuilder/blob/a99b1519f0022c134447e9ec492ffb6a5a77b01f/docs/book/src/plugins/creating-plugins.md#how-the-plugins-can-be-used) and [the git book here](https://book.kubebuilder.io/plugins/creating-plugins.html#how-the-plugins-can-be-used) links to a creating a pull request in Github:
```html
Kubebuilder provides a set of plugins to scaffold the projects, to help you extend and re-use its implementation to provide additional features.
For further information see <a href="https://github.com/kubernetes-sigs/kubebuilder/pull/available-plugins.md">Available Plugins</a>.
```

**Comment by camilamacedo86** [comment]
Hi @protosam,

Thank you. It is bug and we need to fix the link:

[available-plugins]: https://github.com/kubernetes-sigs/kubebuilder/pull/available-plugins.md

It should be relative to the others that can be found in the docs and should be for the page: https://book.kubebuilder.io/plugins/available-plugins.html

Your help is very welcome. Please, feel free to push a PR to fix this one.

Thank you.

**Comment by tan-i-ham** [comment]
Hi @protosam @camilamacedo86,
May I work on this issue?

**Comment by protosam** [comment]
I think the CLA would be a blocker for me making a commit, so feel free to work on this @tan-i-ham.
