### ISSUE TITLE
Installation Docs is outdated. 

### ISSUE THREAD

**Issue by Sajiyah-Salat** [kubernetes-sigs/kubebuilder#3152]
### What do you want to happen?

https://book-v1.book.kubebuilder.io/getting_started/installation_and_setup.html 
I am new to kubebuilder and I dont get any particular brief guide about kubebuilder install. The latest stable version that is given in docs is 1.x and from github repo we can see that it 3.x . I would like to work on this issue. I want some help from contributors for installing kubebuilder. Thank you.

### Extra Labels

/kind documentation, /kind cleanup

**Comment by camilamacedo86** [comment]
Hi @Sajiyah-Salat,

The link `https://book-v1.book.kubebuilder.io/getting_started/installation_and_setup.html` regards the kubebuilder v1 (very old version). Where did you find that? 

You can check in the readme and contributing guide that the link that you should use is: https://book.kubebuilder.io/

**Comment by Sajiyah-Salat** [comment]
I just searched kubebuilder install Ubuntu and got this as my first link.

**Comment by Sajiyah-Salat** [comment]
I think because this is old SEO ranks it first and I think many beginners would be confused can we add a link of new page on old page.

**Comment by Sajiyah-Salat** [comment]
hey camilla, can I work on this?

**Comment by camilamacedo86** [comment]
Hi @Sajiyah-Salat,

Feel free to assign any to yourself any issue and push a pull request with the change.
Your help is more than welcome !!! Feel free to ping me if you need help with reviews.

**Comment by Sajiyah-Salat** [comment]
I would like to know where the old page live in kubebuilder repo.

**Comment by camilamacedo86** [comment]
It is described here: https://github.com/kubernetes-sigs/kubebuilder/blob/master/CONTRIBUTING.md#how-to-contribute-to-docs

You need to do a PR against the old book branches.

**Comment by camilamacedo86** [comment]
I am closing this one because we can check that it is properly done:

<img width="1257" alt="Screenshot 2023-02-14 at 06 45 19" src="https://user-images.githubusercontent.com/7708031/218659899-3e60f600-d351-4cea-826c-04059e42efbd.png">

**Comment by Sajiyah-Salat** [comment]
It was not there at first. Who added it?

**Comment by camilamacedo86** [comment]
Hi @Sajiyah-Salat,

> It was not there at first. Who added it?

You can look for the change in the code, use the blame and check when/who added it. 
However, it seems added prior you got this task.

It is a good idea prior try to solve check if the problem exist yet. 
It is possible an issue be solved previously or as a good side effected of another change and etc. 

PS.: Just for you know. Also, see that I made a comment in your PR: https://github.com/kubernetes-sigs/kubebuilder/pull/3225#issuecomment-1427706878. The away that you also tried to address would not sorted out it as expected.
