### ISSUE TITLE
dep ensure error on fsnotify

### ISSUE THREAD

**Issue by bwarminski** [kubernetes-sigs/kubebuilder#316]
I was able to successfully init a project last night, but tonight for some reason the `dep ensure` step done upon init was failing with:

```
panic: version queue is empty, should not happen
```

Based on Google searching kube dep ensure, I saw this issue: https://github.com/golang/dep/issues/1799, reran `dep ensure -v` and verified that it was erroring on 
```
(35)  ? attempt gopkg.in/fsnotify.v1 with 1 pkgs; 0 versions to try
panic: version queue is empty, should not happen
```

Adding this to Gopkg.toml resolved the issue:

```
[[override]]
  name = "gopkg.in/fsnotify.v1"
  source = "https://github.com/fsnotify/fsnotify.git"
```

**Comment by bwarminski** [comment]
Looks like this will be resolved with https://github.com/kubernetes-sigs/kubebuilder/commit/50adf534b559f15683c54aa947d2bdd942d321b1. Can we backport to the most recent release?

**Comment by 1ForA11** [comment]
using `dep ensure -v` after adding the override then executing `kubebuilder init` works but I can see that the hack yamls are missing.

**Comment by droot** [comment]
We will be doing a release today. Unfortunately, affected projects will have to use the workaround for now.

**Comment by bwarminski** [comment]
Can confirm, init works great on this release. Thanks.

**Comment by vhosakot** [comment]
I saw the same `panic: version queue is empty, should not happen` error for the `fsnotify.v1` package when I ran `dep ensure` and adding the following in `Gopkg.toml ` resolved the error for me and then `dep ensure` worked fine:

```
[[override]]
  name = "gopkg.in/fsnotify.v1"
  source = "https://github.com/fsnotify/fsnotify.git"
```

My `kubebuilder`, `dep` and `go` versions:

```
$ kubebuilder version
Version: version.Version{KubeBuilderVersion:"2.0.0-alpha.1", KubernetesVendor:"1.14.1", GitCommit:"a39cc1a586046d50a74455da6c44da734d2fb8fc", BuildDate:"2019-05-17T23:21:23Z", GoOs:"unknown", GoArch:"unknown"}

$ dep version
dep:
 version     : devel
 build date  : 
 git hash    : 
 go version  : go1.12.4
 go compiler : gc
 platform    : linux/amd64
 features    : ImportDuringSolve=false

$ go version
go version go1.12.4 linux/amd64
```

**Comment by DirectXMan12** [comment]
KB v2 projects use scaffolding v2 by default, which uses go modules.  Are you scaffolding a v1 or v2 project (what does the `PROJECT` file say)?
