### ISSUE TITLE
file name should be specified.

### ISSUE THREAD

**Issue by Sajiyah-Salat** [kubernetes-sigs/kubebuilder#3162]
### What do you want to happen?

Hello, I am trying to follow this project and I am a beginner in kubebuilder. In [this]( https://book.kubebuilder.io/cronjob-tutorial/api-design.html) page a code is written as a block which is good but there is no name of the file mentioned where we need to put the file. if file name is given at left corner of code block it would be helpful for a beginner to understand. IF maintainer allows I would like to work on this issue and help upcoming beginners. Thank you. 

### Extra Labels

/kind documentation

**Comment by camilamacedo86** [comment]
Hi @Sajiyah-Salat,

Thank you for raising the issue.

Please, feel free to push the pull request with the changes you see that would make it better. Your help is more than welcome.

**Comment by Sajiyah-Salat** [comment]
Yeah I will surely work on this

**Comment by camilamacedo86** [comment]
Hi @Sajiyah-Salat, 

I was rechecking this one and see that the file name is added with link on top of the example code:  

<img width="792" alt="Screenshot 2023-01-26 at 11 42 23" src="https://user-images.githubusercontent.com/7708031/214827225-d323129a-a1d8-44c4-b359-adb0bc352d8c.png">

So, I am closing this one. But if you see hall to improvements in the docs and in any area please feel free to push a PR with the proposed changes.
