### ISSUE TITLE
Doc: Migration guide. Fix layout issue.

### ISSUE THREAD

**Issue by camilamacedo86** [kubernetes-sigs/kubebuilder#3167]
### What broke? What's expected?

See : https://book.kubebuilder.io/migration/manually_migration_guide_gov3_to_gov4.html

<img width="871" alt="Screenshot 2023-01-16 at 19 27 07" src="https://user-images.githubusercontent.com/7708031/212753086-7b76b4f2-8963-4c32-8eda-77ea9074b24c.png">

We just need to fix the layout. 

### KubeBuilder (CLI) Version

latest release and master branch

**Comment by Kasambx** [comment]
Hey can I work on this one?

**Comment by camilamacedo86** [comment]
Hi @Kasambx,

Sure. Your help is very welcome. Please, feel free to push the PR with the fix. 
In this case would be great also cherry-pick the solution against the branch book-v3 to get it fix in prod as well afterwords.

**Comment by Sajiyah-Salat** [comment]
Hello @Kasambx are you still working on this issue.

**Comment by Sajiyah-Salat** [comment]
hello @camilamacedo86 can you please give me the exact location of file. I am new and confused.

**Comment by Kasambx** [comment]
Yes I am

**Comment by camilamacedo86** [comment]
It seems sorted out by https://github.com/kubernetes-sigs/kubebuilder/pull/3176. So, I am closing this one.
