### ISSUE TITLE
r.Update updating the boolean field incorrectly

### ISSUE THREAD

**Issue by sbijendra** [kubernetes-sigs/kubebuilder#3174]
### What broke? What's expected?

Hi All- I am experiencing a weird issue with the r.Update command, where update call is updating one of the boolean field back to default that is defined in the CRD.

If you see the Privileged field under,`spec.securityContext.priviledged `it is set to false and this is what is supplied while creating the CR.

**Spec after GET and before Update**

     `Spec:
    Security Context:
      Privileged:    false
      Run As Group:  100
      Run As User:   0`
      
Now I ran the below code where In the Get call I am getting the above value. But After calling the update in the below code without changing anything in the object. In response I got the updated object with `spec.securityContext.priviledged ` turned to true which is the default value set in CRD. 

     `aviController := &aviclusterinstallerv1alpha1.AviClusterInstaller{}
	err := r.Get(ctx, req.NamespacedName, aviController)
	if err != nil {
		if errors.IsNotFound(err) {
			r.aviLogger.logInfo(req.NamespacedName.Name, req.NamespacedName.Namespace, "No Custom resource")
			return ctrl.Result{}, nil
		}
		r.aviLogger.logError(req.NamespacedName.Name, req.NamespacedName.Namespace, err, "Unable to get resource instance")
		return ctrl.Result{}, err
	}

	if err := r.Update(ctx, aviController); err != nil {
		return ctrl.Result{}, err
	}`
**Spec After update Call.**

	 `Spec:
    Security Context:
      Privileged:    true
      Run As Group:  100
      Run As User:   0
    `
    
 Could you please check if this is a bug or if am I doing something wrong here?

### KubeBuilder (CLI) Version

3.7.0

### PROJECT version

3

### Plugin versions

```yaml
go.kubebuilder.io/v3
```

### Other versions

sigs.k8s.io/controller-runtime v0.11.2
k8s.io/client-go v0.24.2

`go version go1.19 darwin/amd64`

kubectl Version:

`Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.13", GitCommit:"a43c0904d0de10f92aa3956c74489c45e6453d6e", GitTreeState:"clean", BuildDate:"2022-08-17T18:22:57Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.7", GitCommit:"b56e432f2191419647a6a13b9f5867801850f969", GitTreeState:"clean", BuildDate:"2022-02-16T11:43:55Z", GoVersion:"go1.16.14", Compiler:"gc", Platform:"linux/amd64"}`

**Comment by camilamacedo86** [comment]
I would recommend you log the value `aviController` before to do the update so that you can ensure that it was not true already. Also, I am not sure how are you using `spec.securityContext.priviledged` in the CR. I would recommend you check that was well because its value might be true by default and that might be the reason.

**Comment by sbijendra** [comment]
Hi @camilamacedo86 - I did log the value of `aviController` before doing the update and I found it to be correct i.e the one that I am setting in the CR while doing the kubectl apply. After the update, I did log it again and found it changed.
