### ISSUE TITLE
Externalize declarative plugin 

### ISSUE THREAD

**Issue by camilamacedo86** [kubernetes-sigs/kubebuilder#3186]
### What do you want to happen?

Kubebuilder introduces the plugin phase 2 implementation. One way we have a great example of how the community can leverage Kubebuilder to create your plugins would be by achieving the goal of moving the declarative plugin to its repository. See: https://github.com/kubernetes-sigs/kubebuilder-declarative-pattern/issues/293

This task is to track the need to work toward this goal.

**Comment by aimuz** [comment]
At present, there seem to be many shortcomings in external plug-ins. For example, I want to implement a Layout plug-in. I refer to the implementation of go in the code, and cannot be well ported to external plug-ins. For now, I found that it relies on InjectConfig, but external plug-ins cannot provide

**Comment by camilamacedo86** [comment]
Hi @aimuz,

To address this need @em-r began to work on it. See: https://github.com/kubernetes-sigs/kubebuilder-declarative-pattern/issues/293. The question raised on  https://github.com/kubernetes-sigs/kubebuilder/issues/3186#issuecomment-1407894107 seems specific to the API and its capabilities and would fit better in a new issue. Therefore, I created this i one : https://github.com/kubernetes-sigs/kubebuilder/issues/3245 (let's discuss it there)

**Comment by em-r** [comment]
@camilamacedo86 I think this is a bit similar to our discussion in https://github.com/kubernetes-sigs/kubebuilder/issues/3214#issuecomment-1432284801
if it is worth it, I can look into adding support for injecting config into external plugins as part of https://github.com/kubernetes-sigs/kubebuilder/issues/3245

**Comment by camilamacedo86** [comment]
Hi @em-r,

> if it is worth it, I can look into adding support for injecting config into external plugins as part of https://github.com/kubernetes-sigs/kubebuilder/issues/3245
I think we could improve to parse and inject it as well. Yes, please feel free your help is more than welcome !!!

**Comment by camilamacedo86** [comment]
We are deprecating the plugin in kubebuilder. 
Also, I think we should keep the whole conversation about the new plugin externalized into the declarative project: https://github.com/kubernetes-sigs/kubebuilder-declarative-pattern/issues/293
