### ISSUE TITLE
Verify the kustimze v5 breaking changes and check if we should not upgrade the migration guide and kustomize v2-alpha plugin docs

### ISSUE THREAD

**Issue by camilamacedo86** [kubernetes-sigs/kubebuilder#3200]
### What do you want to happen?

We bumped kustomize v5 on kustomize/v2-alpha which is used by go/v4-alpha.
So, we need to verify what are the breaking changes between v4 and v5 and ensure that we properly updated the docs
- migration guide from go/v3 to go/v4
- and kustomize/v2-alpha plugin; https://github.com/kubernetes-sigs/kubebuilder/blob/master/docs/book/src/plugins/kustomize-v2-alpha.md (see that we try to help out users letting them know when they can or not use the latest version)

**Comment by swastik959** [comment]
@camilamacedo86 hi again I want to contribute to this issue can you explain it to me

**Comment by camilamacedo86** [comment]
HI @swastik959,

We need to:
a) check the kustomize release notes  (v5), It is a major bump so has breaking changes
b) We need to supplement the migration and kustomize/v2-alpha doc to add new breaking changes and its link
c) see that the doc says when you should use or not the new version we might need to add new info as well

I hope that clarifies the idea of this one.

**Comment by Sajiyah-Salat** [comment]
if I find anything that is somewhat looks like a breaking change I will let you know. Some things I have found are:
``
Remove deprecated alpha cfg and fn commands
Duplicate fields in Kustomization files will now result in an error
``
Other than that they have fixed remote urls, Drop support for a very old, legacy style of patches, Drop support for using gh: as a host, Remove a potential build-time side-effect in ConfigMapGenerator and SecretGenerator, etc.

**Comment by Sajiyah-Salat** [comment]
I have checked the breaking changes. and I dont have depth of kubebuilder so I dont know which thing will be proved as a breaking change. kindly let me know that. Also i am referring to this [link](https://github.com/kubernetes-sigs/kustomize/releases)

**Comment by Sajiyah-Salat** [comment]
Should I also check the dependencies?

**Comment by ashutosh887** [comment]
@camilamacedo86 @varshaprasad96 Please assign this issue to me

**Comment by Sajiyah-Salat** [comment]
> if I find anything that is somewhat looks like a breaking change I will let you know. Some things I have found are: `Remove deprecated alpha cfg and fn commands, Duplicate fields in Kustomization files will now result in an error` Other than that they have fixed remote urls, Drop support for a very old, legacy style of patches, Drop support for using gh: as a host, Remove a potential build-time side-effect in ConfigMapGenerator and SecretGenerator, etc.

Hello @camilamacedo86 need your reviews on that. so I can start my work.

**Comment by varshaprasad96** [comment]
We need to check if any other action item is remaining on this, if not we can close this.

**Comment by camilamacedo86** [comment]
This doc is updated already.
So we can close this one as sorted out.
