### ISSUE TITLE
[Doc] - Create doc with common suggestions and overview

### ISSUE THREAD

**Issue by camilamacedo86** [kubernetes-sigs/kubebuilder#3203]
### What broke? What's expected?

The info shared in https://github.com/kubernetes-sigs/kubebuilder/issues/3196#issuecomment-1415494809 be properly documented in Kubebuilder docs since they are very common questions. 

### KubeBuilder (CLI) Version

master

### Extra Labels

/kind documentation

**Comment by Sajiyah-Salat** [comment]
Hello @camilamacedo86 I have gone through the reference issue. There you have explained things in detail.Do we need to add that in docs?

**Comment by camilamacedo86** [comment]
Hi @Sajiyah-Salat, 

I think would be great we have this info in the docs because those are common questions.

**Comment by Sajiyah-Salat** [comment]
Should we add this as faq or a docs page?

**Comment by camilamacedo86** [comment]
HI @Sajiyah-Salat,

> Should we add this as faq or a docs page?

 Give a look at https://github.com/kubernetes-sigs/kubebuilder/issues/3196#issuecomment-1415494809. The suggestion about where and how to add the info is described there as well.

**Comment by octonawish-akcodes** [comment]
are you working on this? @Sajiyah-Salat

**Comment by Sajiyah-Salat** [comment]
Yes, I am

**Comment by ashutosh887** [comment]
@camilamacedo86  Please assign this issue to me

**Comment by ashutosh887** [comment]
@camilamacedo86 @varshaprasad96 @Kavinjsir 
Does this PR resolve this issue?
I wanted to contribute

**Comment by varshaprasad96** [comment]
#3247 does have some open reviews which needs to be addressed before merging them.

**Comment by ashutosh887** [comment]
Okay @varshaprasad96 
Thanks for the update

**Comment by camilamacedo86** [comment]
After seeing the questions raised, I realized that this one does not fit a good first issue. So, I am changing the label to help wanted.
