### ISSUE TITLE
Doc: Finish the PR to add documentation about external types and dependencies 

### ISSUE THREAD

**Issue by camilamacedo86** [kubernetes-sigs/kubebuilder#3210]
### What do you want to happen?

It would be great get a help to finish the PR: https://github.com/kubernetes-sigs/kubebuilder/pull/3055

**Comment by Sajiyah-Salat** [comment]
Hello @Kavinjsir Are you working on this if not can I take this up?

**Comment by Kavinjsir** [comment]
@Sajiyah-Salat Sure thing! Glad if you are willing to up with this!
I am going to unassign myself and switch to you 🏓

**Comment by Kavinjsir** [comment]
@Sajiyah-Salat Based on the previous context https://github.com/kubernetes-sigs/kubebuilder/pull/3055, I'm wondering if this might result in many works with documentation.
Feel free to break it down into small PRs if you find it more comfortable. I'm not sure how much I can help, but let me know if you have any concerns or questions.

**Comment by Sajiyah-Salat** [comment]
It would be good if we can connect 1:1 as you have suggested last time

**Comment by camilamacedo86** [comment]
It id done now 
ia m closing this one
