### ISSUE TITLE
Increase the test coverage with unit tests

### ISSUE THREAD

**Issue by camilamacedo86** [kubernetes-sigs/kubebuilder#3211]
### What do you want to happen?

By looking at the coveralls reports we can see that we have some implementations which could be better covered. We do not cover 100% of the code but would be great increase the coverage and ensure that we have no red and orange files/dirs, see: https://coveralls.io/github/kubernetes-sigs/kubebuilder?branch=master

Example: 

We could add more tests for cmd_helpers.go, completiton.go and version.go:

<img width="494" alt="Screenshot 2023-02-08 at 14 17 13" src="https://user-images.githubusercontent.com/7708031/217554971-70c9a9c5-0d6a-47f9-8fdc-c653cb44ad83.png">

**Comment by ashutosh887** [comment]
@camilamacedo86  Please let me work on this issue now

**Comment by ashutosh887** [comment]
Should I work on it @camilamacedo86 ?
I've set up the code
