### ISSUE TITLE
move webhooks away from api folder

### ISSUE THREAD

**Issue by malt3** [kubernetes-sigs/kubebuilder#3215]
### What do you want to happen?

This may be seen as an extension to #2627. I want projects to not place webhook handlers and envtests in the api folder.

Instead, webhooks should be moved into the controllers folder (or into a completely separate folder).
This allows external projects to import the api module without importing envtest libraries.

**Comment by camilamacedo86** [comment]
Hi @malt3,

I recommend you read the PR https://github.com/kubernetes-sigs/kubebuilder/pull/3055 and the comment https://github.com/kubernetes-sigs/kubebuilder/issues/2627#issuecomment-1247579546 as https://github.com/kubernetes-sigs/kubebuilder/issues/2627#issuecomment-1271492741.

You can see that those who raise the idea after their experiment realize that it is not a good option and decide that it would be better addressed by documentation.

**Comment by malt3** [comment]
Hello,

I will try to answer the open questions.

> Are webhook controllers? So, why should it be in the controller's folder?

You are right. Depending on your viewpoint, webhooks may not be seen as controllers. However, webhooks have handlers (private implementation only used by the operator that is not required for other projects that may import the api folder). Placing the implementation and tests of webhooks into a new folder may also be an option.

> When you say envtest, I understand that you are speaking about the webhook tests so they must to be kept with the webhooks.

I agree. The webhook envtests should live in the same folder as the webhooks. This means they should be moved together, away from the api folder.

> a) What would you like to do that is impossible with the current layout?

Have operators that use multiple `go.mod` files (one just for the api folder), and import the api folder of one operator in the implementation of another operator. This does not have to be the default, but should be possible.
Currently, this means I have to upgrade a lot of dependencies for all of my operators in sync, since I have to import envtest and other dependencies that are not required for the actual API structs I want to import.

> b) Why/when do you think that changing the layout would be beneficial? For what use case?

For operators that use kubebuilder and also use go workspaces. And to allow imports of API modules of other open source operators without having to also depend on their version of envtest and other imports that are currently in the api folder.

> c) What would be the technical/good practice argumentation to have the webhooks in another folder? Could you please provide some references?

A general best practice for go packages: If a package/module is meant to be imported by other modules, it should only import what is needed by to consume the public api.

The package/module `api` holds structs that form the public api of the operator. Currently, this folder also holds the implementation and tests of webhooks.

The reconcile loops for custom resources live in `controllers` so this is already designed well for this part of the implementation.

d) How could this change be beneficial for all standard cases? what would be the pros and cons?

This would have negligible impact for the standard case (only one go.mod).

Pros:

- separation between public API  <--> webhook handlers / webhook envestests
- allows users of go workspaces to only inherit required dependencies for struct definitions

Cons:

- existing operators will have to migrate to the new layout

**Comment by camilamacedo86** [comment]
Hi @n1r1,

It is a very interesting thought. However, we just released go/v4 stable. Therefore, any change in the layout (breaking change) like this one can only be addressed in the new version, which would be go/v5.  

I am adding this one to the go/v5 milestone, and when we have a significant number of changes that justify we getting started with the new layout, we can discuss this request. I hope that can be fine.

**Comment by camilamacedo86** [comment]
It seems the others are either looking for this one: https://github.com/kubernetes-sigs/kubebuilder/issues/3721#issuecomment-1891036910

c/c @@nathanperkins

**Comment by nathanperkins** [comment]
Thanks for bringing this up. I want to stress how important this kind of change is to the community health at large. When projects include controller-runtime code in their public API packages, any breaking change in the controller-runtime code creates a version barrier in which projects on either side of the barrier can't import each other.

The suggested change here is the only way to fix the issue so that it doesn't reoccur whenever there are breaking changes.

**Comment by camilamacedo86** [comment]
I am closing this one in favor of https://github.com/kubernetes-sigs/kubebuilder/issues/4062
where we are better centralizing all motivations.
