### ISSUE TITLE
Introduce CEL as a method of validation in Kubebuilder 

### ISSUE THREAD

**Issue by camilamacedo86** [kubernetes-sigs/kubebuilder#3222]
### What do you want to happen?

With the k8s 1.25 release, CEL (Common Expression Language) was introduced. Prior to this, in order to validate a custom resource definition, the commonly used approach was to utilize admission webhooks. Developing and maintaining an admission webhook is a complex task and can increase load on the api server for every webhook call. As a solution for this CEL based validation was introduced that can implement common immutability checks for a custom resource definition. 
Documentation on using CEL with Kubebuilder: https://kubernetes.io/blog/2022/09/29/enforce-immutability-using-cel/#project-setup

One other area which is less explored wherein CEL based validation can be used is in conversion webhooks. An example of the same was explored in the KCP project. We can shed more light on this and find a way to enable this with Kubebuilder. Highlighting some points:

Instead of having a hub and spoke version in a conversion webhook, the idea here is to have conversion rules for multiple versions which can be in any order. For example:

V1 —> v2 —-> v3 —> v4 —> v5
|                                    |
|__________________|

The conversion logic will involve finding the shortest path in the graph to convert from one version to another. For ex - v1 to v5, can be done in 3 steps. This is not fully supported, but a prototype of the same was created by Andy Goldstein in KCP to convert API versions.

Andy’s demo: https://www.youtube.com/watch?v=Fc52Eo_WDf4

**What would be expected here:**
- Provide a design solution as a helper for users opt-in to use CEL with webhooks
- Deliver the CEL helper with e2e tests and documentation 
- Discuss with the community and gathering feedbacks
- Demostrate the helper produced, the demo will be used in the docs and shared with the community

**Comment by varshaprasad96** [comment]
The current procedure to use CEL based validations with Kubebuilder already exists:  https://kubernetes.io/blog/2022/09/29/enforce-immutability-using-cel/#project-setup. 

The idea proposed here of using CEL for conversion webhook is still nascent. I would even go a step further to say that if the feature of CEL is to be used as conversion webhooks it should be done in upstream k8s and not here. Doing this would be way more involved process and not a use-case of KB imo.

cc: @camilamacedo86 @Kavinjsir
