### ISSUE TITLE
External plugins discovery fails when XDG_CONFIG_HOME is set

### ISSUE THREAD

**Issue by em-r** [kubernetes-sigs/kubebuilder#3224]
### What broke? What's expected?

On Ubuntu, when specifying an external plugin to any subcommand (e.g. `init`) through the `--plugins` flag, the subcommand fails if `XDG_CONFIG_HOME` is set to its default value `$HOME/.config`, with the following error:

`2023/02/11 15:35:25 no plugin could be resolved with key "myexternalplugin/v1"`

The subcommands eventually run successfully after unsetting `XDG_CONFIG_HOME`.

### Reproducing this issue

1. Set XDG_CONFIG_HOME variable in the shell: `export XDG_CONFIG_HOME=$HOME/.config`
2. Create a folder for an external plugin: `mkdir -p $XDG_CONFIG_HOME/kubebuilder/plugins/myexternalplugin/v1`
3. Copy the plugin binary to the directory created in 2).
4. Initialize a new project: `kubebuilder init --plugins=myexternalplugin/v1`
5. Notice how the execution will exit with an error, and `myexternalplugin` won't appear in the available plugins table.

### KubeBuilder (CLI) Version

3.9.0

### Other versions

Go version: 1.19.4 linux/amd64
OS version: Ubuntu 22.04.1 LTS

**Comment by em-r** [comment]
Looking at the code, I believe this issue occurs because Kubebuilder concatenates the outcome of [`getHomeDir`](https://github.com/kubernetes-sigs/kubebuilder/blob/master/pkg/cli/options.go#L291) (which maybe $XDG_CONFIG_HOME) to `.config/kubebuilder` (see  [options.go#L191](https://github.com/kubernetes-sigs/kubebuilder/blob/master/pkg/cli/options.go#L191))

So, when `XDG_CONFIG_HOME` is set, Kubebuilder will try to find external plugins in the directory `$XDG_CONFIG_HOME/.config/kubebuilder`.
For example, if `XDG_CONFIG_HOME` is set to its default value (`$HOME`), then Kubebuilder will lookup external plugins in `$HOME/.config/.config/kubebuilder`.

**Comment by em-r** [comment]
I'll be happy to send a PR with a fix if this gets accepted.

**Comment by camilamacedo86** [comment]
Hi @em-r,

All issues that you find if you either be able to contribute with the fix that is amazing !!! please feel free to move forward  !!!
