### ISSUE TITLE
Add to the PROJECT file the CLI tag version used to do the scaffold

### ISSUE THREAD

**Issue by camilamacedo86** [kubernetes-sigs/kubebuilder#3229]
### What do you want to happen?

The idea of this task is for we start to track in the PROJECT file what was the Kubebuilder version used to do the scaffold so that for proposed features like https://github.com/kubernetes-sigs/kubebuilder/pull/3221 or for support purpose for example this info can be helpful in the long term.

**Comment by camilamacedo86** [comment]
@yashsingh74 this one might be a good one for you. You need to ensure that we will have in the Project file (config) this new field and that when we init a project, that will be filled with the kubebuilder version info.

**Comment by yashsingh74** [comment]
Sure, will look into this.
/assign

**Comment by ashutosh887** [comment]
@camilamacedo86 Let me work on this now if it's still needed
/assign

**Comment by camilamacedo86** [comment]
Hi @ashutosh887 and @yashsingh74 , 

Are you working on this one? if not, could you please remove your self from the assign so others might be able to do this one?

**Comment by ashutosh887** [comment]
Yes I'm willing to work on this @camilamacedo86 

Can you guide me a bit how to approach this?

**Comment by yashsingh74** [comment]
@ashutosh887 you can work on this.

**Comment by ashutosh887** [comment]
You may continue @yyy1000 🙂

**Comment by camilamacedo86** [comment]
I want to clarify that I identified this issue based on a request made by a community member in the Slack channel when we shared the proposed solution for a command tool that could re-scaffold projects. The member suggested using the tool for a three-way scaffold merge to automate the process as a subsequent step in the implementation.

It was flagged as a good first issue, as it seemed to be a change that new contributors could handle.

However, after examining the draft proposal and giving it more thought, I'm starting to think that we should not pursue this idea, at least for now. Here's why:

- If we track the CLI version used to scaffold the project, it doesn't necessarily have to be the same version used for plugin scaffolding. This would require tracking on a per-plugin basis.
- Managing multiple different versions used for scaffolding could complicate the future command tool implementation.
- Addressing this issue now might not add value, as the resulting values might not be useful and could lead to premature optimization.

Given these concerns, I would like to mark this issue as deferred and allow us to reconsider how we can move forward and improve the proposed idea of providing a helper to re-scaffold projects once it's completed and we have the opportunity to test it.

@yyy1000 your PR: https://github.com/kubernetes-sigs/kubebuilder/pull/3387 was helpful for us better think about this one. Do you mind if we close both as deferred?

**Comment by yyy1000** [comment]
It's OK to defer these.

**Comment by camilamacedo86** [comment]
Great, I am closing this one based on the comment https://github.com/kubernetes-sigs/kubebuilder/issues/3229#issuecomment-1537293699, but we can look into it in the future.
