### ISSUE TITLE
JSONSchemaProps Not Generated If Key Contains Numbers

### ISSUE THREAD

**Issue by adambkaplan** [kubernetes-sigs/kubebuilder#323]
Version: v1.0.0
OS: macOS 10.13.6 (High Sierra)

If an object's JSON key contains a number, kubebuilder does not generate the appropriate JSONSchemaProp entry.

**Expected behavior**
The objects generated `zz_generated.kubebuilder.go` contains JSONSchemaProps entries for all properties defined in the API struct.

**Actual Behavior**
Generated object does not contain entries for properties whose JSON key contains numbers.

**Steps to reproduce**

1. In a CRD's API package, create a type as such:

```
type Data struct {
    Base64 string `json:"base64"`
    OkayName string `json:"badName23,omitempty"`
}
```

2. Run `kubebuilder generate`

Resulting generated code will have an empty map where the JSONSchemaProp entries should be.

**Comment by droot** [comment]
@fanzhangio Can you pl. take a look.

**Comment by fanzhangio** [comment]
@adambkaplan. Thanks for your feedback. I can reproduce it, looking into it.

**Comment by DirectXMan12** [comment]
closing as no longer relevant
