### ISSUE TITLE
etcd should not be assumed to be in /usr/local/kubebuilder/bin/etcd

### ISSUE THREAD

**Issue by cflewis** [kubernetes-sigs/kubebuilder#326]
I installed the Kubebuilder binaries in a personal folder:

```shell
/usr/local/home/cflewis/bin/kubebuilder/etcd
```

Kubebuilder assumes that `etcd` is in `/usr/local/kubebuilder/bin/etcd`

```shell
$ make test
go generate ./pkg/... ./cmd/...
go fmt ./pkg/... ./cmd/...
go vet ./pkg/... ./cmd/...
go run vendor/sigs.k8s.io/controller-tools/cmd/controller-gen/main.go all
CRD manifests generated under '/usr/local/home/cflewis/src/go/src/github.com/cflewis/kubebuilder-demo/config/crds' 
RBAC manifests generated under '/usr/local/home/cflewis/src/go/src/github.com/cflewis/kubebuilder-demo/config/rbac' 
go test ./pkg/... ./cmd/... -coverprofile cover.out
?       github.com/cflewis/kubebuilder-demo/pkg/apis    [no test files]
?       github.com/cflewis/kubebuilder-demo/pkg/apis/ships      [no test files]
2018/07/20 14:11:56 fork/exec /usr/local/kubebuilder/bin/etcd: no such file or directory
FAIL    github.com/cflewis/kubebuilder-demo/pkg/apis/ships/v1beta1      0.199s
?       github.com/cflewis/kubebuilder-demo/pkg/controller      [no test files]
2018/07/20 14:11:56 fork/exec /usr/local/kubebuilder/bin/etcd: no such file or directory
FAIL    github.com/cflewis/kubebuilder-demo/pkg/controller/sloop        0.186s
?       github.com/cflewis/kubebuilder-demo/cmd/manager [no test files]
Makefile:9: recipe for target 'test' failed
make: *** [test] Error 1
```

My grepping found this:

```shell
./vendor/sigs.k8s.io/controller-runtime/pkg/envtest/server.go:  defaultEtcdBin          = "/usr/local/kubebuilder/bin/etcd"
```

As long as `etcd` is in the user's path, things should work. Is there a reason a full path was hardcoded?

**Comment by fanzhangio** [comment]
kubebuilder needs to be unzipped or linked to default directory which is ‘/usr/local/kubebuilder’ as instructed in document. Kubebuilder uses binaries from it

**Comment by foolusion** [comment]
This is definitely not ideal. Why should the installation directory matter.

**Comment by errordeveloper** [comment]
Yes, I also find this  rather very surprising.

**Comment by chrigl** [comment]
With this commit https://github.com/kubernetes-sigs/controller-runtime/commit/c5e5439a4953c1a2cab7975cab74cedc0dde3da2 (which is included at least in 1.0.5) we can use the envvar `KUBEBUILDER_ASSETS` to pass the bin-directory explicitly.

```
export KUBEBUILDER_ASSETS=~/sdk/kubebuilder_1.0.5_linux_amd64/bin/
```

Worked for me with the getting-started example (Except for struggling because of #359).

**Comment by errordeveloper** [comment]
That sounds okay to me, shall we close?

**Comment by abbi-gaurav** [comment]
Please consider adding the information to 
```
export KUBEBUILDER_ASSETS = <path of kubebuilder/bin>
```

in the kubebuilder book.

**Comment by vhosakot** [comment]
I saw the same error when I ran `make test` in the workspace created using kubebuiler due to missing `/usr/local/kubebuilder/bin/etcd` file on the host:

```
go test ./api/... ./controllers/... -coverprofile cover.out
...
2019-05-22T16:25:21.837Z	ERROR	controller-runtime.test-env	unable to start the controlplane	{"tries": 0, "error": "fork/exec /usr/local/kubebuilder/bin/etcd: no such file or directory"}
```

The following steps resolved the error for me and then `make test` worked fine:

```
wget https://github.com/kubernetes-sigs/kubebuilder/releases/download/v2.0.0-alpha.1/kubebuilder_2.0.0-alpha.1_linux_amd64.tar.gz
tar -zxvf  kubebuilder_2.0.0-alpha.1_linux_amd64.tar.gz
sudo mv kubebuilder_2.0.0-alpha.1_linux_amd64 /usr/local/kubebuilder

$ find /usr/local/kubebuilder
/usr/local/kubebuilder
/usr/local/kubebuilder/bin
/usr/local/kubebuilder/bin/etcd
/usr/local/kubebuilder/bin/kube-apiserver
/usr/local/kubebuilder/bin/kubebuilder
/usr/local/kubebuilder/bin/kubectl

workspace_directory$ $ make test
go fmt ./...
go vet ./...
go test ./api/... ./controllers/... -coverprofile cover.out
ok  	redacted/api/v1alpha1	7.420s	coverage: 2.4% of statements
ok  	redacted/controllers	5.816s	coverage: 0.0% of statements
```

**Comment by DirectXMan12** [comment]
You can also set the KUBEBUILDER_ASSETS environment variable, for posterity

**Comment by mayyyyying** [comment]
> 
export KUBEBUILDER_ASSETS=<path of kubebuilder/bin>

probably remove the "space" on the both sides of the equal sign will be better

**Comment by dineshba** [comment]
We can use [setup-envtest](https://pkg.go.dev/sigs.k8s.io/controller-runtime/tools/setup-envtest#section-readme) tool to download which version of assets we need and use like below:
```sh
export KUBEBUILDER_ASSETS=$(setup-envtest use 1.25.0 -p path)
```

**Comment by kristianjaeger** [comment]
Good morning, or good day, good evening. This is a bit strange to assume where the binaries are.  The quick start itself refers to `/usr/local/bin/kubebuilder` - https://book.kubebuilder.io/quick-start . Sounds like there's a workaround at least... Cheers.
