### ISSUE TITLE
[CI] doc check ci is blocking bot merges

### ISSUE THREAD

**Issue by camilamacedo86** [kubernetes-sigs/kubebuilder#3268]
### What broke? What's expected?

We are with an issue related to the job to check if the changes were done only on the docs and skip the other tests, see:

<img width="1147" alt="Screenshot 2023-03-07 at 14 37 47" src="https://user-images.githubusercontent.com/7708031/223454434-5482ba64-e3ae-435d-a7e5-1f3b8de20011.png">

Therefore, we need to fix the issue OR remove this check. 

### Reproducing this issue

Look at the PRs sometimes it has been failing

### KubeBuilder (CLI) Version

master

**Comment by ashutosh887** [comment]
I would like to inspect the Issue and contribute

**Comment by ashutosh887** [comment]
As far can I see, this needs some modifications in GitHub Actions workflow?
Please guide me @camilamacedo86 @varshaprasad96

**Comment by camilamacedo86** [comment]
We need to remove the code to skip the tests when only changes on the docs were performed.
Therefore, this issue now is for we are able to re-implement / re-add the checks to skip running the tests when only docs are changed.

**Comment by Sajiyah-Salat** [comment]
i was working on one doc isssue in kubernetes other repo. And there members found same problem. if its not fixed till now. I will try to fix it in kubebuilder.

**Comment by NikhilSharmaWe** [comment]
PR which added the [CI] doc check: https://github.com/kubernetes-sigs/kubebuilder/pull/2608
It was previously working fine, need to find what changes were in the GitHub workflow which made it not work as expected.

**Comment by camilamacedo86** [comment]
> PR which added the [CI] doc check: https://github.com/kubernetes-sigs/kubebuilder/pull/2608
It was previously working fine, need to identify the changes which were in the GitHub workflow that resulted it not working as expected.

We reverted all changes done and it is still broken.
It seems that we need to change because of some deprecations.

**Comment by Kavinjsir** [comment]
Wondering about the status of this issue? Looks like CI is working well.

**Comment by NikhilSharmaWe** [comment]
It is because the changes made for adding the check docs only https://github.com/kubernetes-sigs/kubebuilder/pull/2608 which were causing the blocking are now reverted.
