### ISSUE TITLE
CRD generation fails when spec contains a map

### ISSUE THREAD

**Issue by calind** [kubernetes-sigs/kubebuilder#328]
__Steps to reproduce:__

```sh
kubebuilder init --domain presslabs.org --owner "Pressinfra SRL"
kubebuilder create api --group wordpress --version v1alpha1 --kind Wordpress
```

Edit `pkg/apis/wordpress/v1alpha1/wordpress_types.go` and set `WordpressSpec` to:
```go
// WordpressSpec defines the desired state of Wordpress
type WordpressSpec struct {
    // +optional
    IngressAnnotations map[string]string `json:"ingressAnnotations,omitempty"`
}
```

Now run
```sh
make
```

It fails with:
```
CustomResourceDefinition.apiextensions.k8s.io "wordpresses.wordpress.presslabs.org" is invalid: spec.validation.openAPIV3Schema.properties[spec].properties[ingressAnnotations].additionalProperties: Forbidden: additionalProperties cannot be set to false
```

__Versions:__
kubebuilder: `Version: version.Version{KubeBuilderVersion:"1.0.0", KubernetesVendor:"1.10", GitCommit:"9c4c6c213a8d17f8c21cf4f1aa9cefb99fbbf5ca", BuildDate:"2018-07-19T23:21:03Z", GoOs:"unknown", GoArch:"unknown"}`
go version:  `go version go1.10.3 darwin/amd64`

**Comment by calind** [comment]
As a workaround I've edited the `Makefile` and changed `manifests` target from
```make
# Generate manifests e.g. CRD, RBAC etc.
manifests:
	go run vendor/sigs.k8s.io/controller-tools/cmd/controller-gen/main.go all
```
to:

```make
# Generate manifests e.g. CRD, RBAC etc.
manifests:
	go run vendor/sigs.k8s.io/controller-tools/cmd/controller-gen/main.go rbac
	go run vendor/sigs.k8s.io/controller-tools/cmd/controller-gen/main.go crd --skip-map-validation
```

**Comment by droot** [comment]
@calind Thanks for posting the workaround. I am impressed that you dig into the codebase to figure out the workaround :)

**Comment by droot** [comment]
This should be fixed now. Newer projects will automatically get the latest `controller-tools`. 

@calind you can update the controller-tools deps by running `dep ensure -update sigs.k8s.io/controller-tools` and undo the workaround. Latest `controller-gen` tools have the fix. Pl. re-open if you the issue still persists.
