### ISSUE TITLE
:sparkles:  new subcommand :kubebuilder delete webhook --group xxx --version xx --kind xxx 

### ISSUE THREAD

**Issue by xiao-jay** [kubernetes-sigs/kubebuilder#3288]
### What do you want to happen?

when i create a webhook ,but i want to delete it one day,i should delete file 
```
api/xxx_webhook.go
api/webhook_suite_info.go
config/certmanager/*
config/webhook/*
config/crd/patches/webhook_in_xxx.yaml
config/default/webhookcainjection_patch.yaml
config/default/manager_webhook_patch.yaml
```
change file
```
PROJECT
main.go
```

So many file need to delete or change manually. So, i think Is it possible to have a command with as little manual work as possible.

## Design docs
This is a design draft, there must be many imperfections, hope to give me more suggestions.
subcommand example : `kubebuilder delete webhook --group xxx --version xx --kind xxx --nobackup`
### 1、pre-check
checkout webhook existed  in PROJECT 
### 2、backup project to ./.backup/
because `kubebuilder delete webhook`may have some bug ,delete some importmant file.
### 3、delete webhook file
```
api/xxx_webhook.go
api/webhook_suite_info.go
config/certmanager/*
config/webhook/*
config/crd/patches/webhook_in_xxx.yaml
config/default/webhookcainjection_patch.yaml
config/default/manager_webhook_patch.yaml
```
delete webhook in PROJECT,may be change main.go should manually.
### 4、delete backup
```
ask user delete backup file (Yes/No)
```

**Comment by ashutosh887** [comment]
Does this Issue need some work? I would like work on it then. @xiao-jay

**Comment by xiao-jay** [comment]
@ashutosh887  Thank you for your interesting, Please working on a proposal for that firstly.This subcommand need community discussion.

**Comment by ashutosh887** [comment]
Where can I have a look at the Community discussions on this (if public)?

**Comment by xiao-jay** [comment]
`kubebuilder delete webhook` may be need to analyse golang code and kustomize config ,It's not easy to do,so I decide to close this issue.
