### ISSUE TITLE
Deprecate the current method API to build bundles and create new version to work with Options

### ISSUE THREAD

**Issue by camilamacedo86** [kubernetes-sigs/kubebuilder#3307]
### What do you want to happen?

Currently, we have the following: https://github.com/kubernetes-sigs/kubebuilder/blob/master/pkg/plugin/bundle.go#L33-L59
Therefore, this task is for us to deprecate the func used currently in favour of something like:
```go
func NewBundle(opts ...BundleOptions) (Bundle, error)
```
and new bundles could be created like:
```go
bundle, err := NewBundle(
  WithName("name"),
  WithVersion(plugin.Version{Number: 4}),
  WithPlugins(plugins ...Plugin),
  WithDeprecationMessage("Deprecated!"),
)
```

requester @everettraven see: https://github.com/kubernetes-sigs/kubebuilder/pull/3276#discussion_r1134064332

**Comment by NikhilSharmaWe** [comment]
I would like to work on it.
