### ISSUE TITLE
Is it possible to use custom storage?

### ISSUE THREAD

**Issue by jwierzbo** [kubernetes-sigs/kubebuilder#332]
I've build already extension api-server with separate etcd storage using apiserver-builder.
Is it possible to attach separate datastore (etcd) for my resources in kubebuilder (as I know CRD by design doesn't allow for external datasource)?

**Comment by droot** [comment]
> Is it possible to attach separate datastore (etcd) for my resources in kubebuilder (as I know CRD by design doesn't allow for external datasource)?

No, it is not.
