### ISSUE TITLE
Document: Adding release version dropdown for book-v1,v2,v3

### ISSUE THREAD

**Issue by pratikmota** [kubernetes-sigs/kubebuilder#3320]
### What do you want to happen?

 Kubebuilder documentation has 3 versions. Book-v1,v2 and v3.
**Problem:**

1.  Right now legacy documentation (v2 and v1) URL is given in the introduction. If someone directly checks other pages then might not get from where they can open different version documentation.
2. Difficult to find different version documentation for new users in first glance.
3. In the future if different versions v4, v5 etc will come then it will be difficult to maintain and for a new user it will be difficult to find an old version of the documentation.

**Solution**
1. We need to add a book versions list in Menu
2. User can just hover and check different versions like v3-book, v2-book and v1-book
4. By click on particular version, it will open in new tab
5. By this solution it will be very easy for new users to find different versions of documentation and also easy to maintain different versions for future use cases.
![image](https://user-images.githubusercontent.com/5825319/230728113-277aacf8-634e-450f-80ae-cdc73d432d28.png)

### Extra Labels

/kind documentation

**Comment by motapratik** [comment]
@camilamacedo86   / @varshaprasad96 : Can you please check if this change request will be useful for the community? I have done local changes related to it. If the request looks fine, Can you please assign it to me? I will raise MR.

**Comment by pratikmota** [comment]
PR: https://github.com/kubernetes-sigs/kubebuilder/pull/3321

**Comment by pratikmota** [comment]
PR for master branch: https://github.com/kubernetes-sigs/kubebuilder/pull/3332
