### ISSUE TITLE
Kubebuilder fails to deal with slice type in resource definition.

### ISSUE THREAD

**Issue by medinatiger** [kubernetes-sigs/kubebuilder#333]
Kubebuilder fails to generate test and/or sample for resource containing slide type.

xxxx.cloud.google.com "foo" is invalid: []: Invalid value: map[string]interface {}{
"kind":"VirtualMachine","apiVersion":"xxxx.cloud.google.com/v1alpha1", "metadata":map[string]interface {}{
"creationTimestamp":"2018-07-26T18:22:58Z", "generation":1, "uid":"ec1a0fbd-9100-11e8-ab65-a08cfdecd7cb", "selfLink":"", "clusterName":"", "name":"foo", "namespace":"default"}, 
"spec":map[string]interface {}{"zone":"", "machineType":"", "os":"", "disks":interface {}(nil)}, 
"status":map[string]interface {}{}}: validation failure list:spec.disks in body must be of type array: "null"

type xxxxSpec struct {
  // Other types
 //Disks []Disk `json:"disks"`
}

**Comment by feloy** [comment]
Hi,

That sounds normal to me.

If you have for example a string field in the Spec, when you create the structure omitting to declare the value of this field, it is set with its zero value, which is an empty string, and this is a valid value for your custom resource.

But when you use a slice field, its zero value is nil, which is not a valid value for the Custom Resource.

A solution would be to define you []Disk field as an empty array when you instantiates your struct during test:
{
 Disks: []Disk{},
}

Another solution would be to declare your Disks field as non-required with the omitempty tag:

type xxxxSpec struct {
// Other types
//Disks []Disk `json:"disks:omitempty"`
}
