### ISSUE TITLE
3.10.0 release was not completed

### ISSUE THREAD

**Issue by chenrui333** [kubernetes-sigs/kubebuilder#3336]
👋 it looks like the 3.10.0 release was not marked as latest release even though [the release job was done](https://github.com/kubernetes-sigs/kubebuilder/actions/runs/4706808882). Create this issue to raise some awareness. Thanks!

relates to https://github.com/Homebrew/homebrew-core/pull/128464

**Comment by camilamacedo86** [comment]
It is intentionally flagged as pre-release.

**Comment by camilamacedo86** [comment]
We can close it now. Thank you,

**Comment by chenrui333** [comment]
I see, thanks for the help in here!
