### ISSUE TITLE
Webhooks manifests has been scaffolded when a project has not webhooks created

### ISSUE THREAD

**Issue by camilamacedo86** [kubernetes-sigs/kubebuilder#3367]
### What broke? What's expected?

Currently, the default scaffold will add the patches and the customizartion for webhooks. 
Therefore, ideally would be great we just add the files for webhooks when the tool scaffold webhook.

That means the following code should only be added to the project when the first WebHook is scaffolded

- Update the scaffolds to insert into `config/crd/kustomization.yaml`:

```
# [WEBHOOK] To enable webhook, uncomment all the sections with [WEBHOOK] prefix.
# patches here are for enabling the conversion webhook for each CRD
#- patches/webhook_in_installers.yaml
#+kubebuilder:scaffold:crdkustomizewebhookpatch

# the following config is for teaching kustomize how to do kustomization for CRDs.
configurations:
- kustomizeconfig.yaml

```

- Also, add `config/crd/kustomizeconfig.yaml`

### Reproducing this issue

Create a new project and check the webhooks manifests will be scaffolded by default in the patches when no wekbhooks were yet added to the project

### KubeBuilder (CLI) Version

3.10.0

### PROJECT version

3

### Plugin versions

```yaml
go/v4
```

**Comment by Sajiyah-Salat** [comment]
Hello @yyy1000 Are you working on this? If not let me know. I would love to take this. else link your pr and I will try to review your pr. Thank you.

**Comment by Sajiyah-Salat** [comment]
Hello @camilamacedo86 I understood the issue. But still confused in the implementation part. Can you please help me with that?

**Comment by camilamacedo86** [comment]
- **The problem is:** We are scaffolding files that are ONLY useful when we create webhooks (kb create webhook)
- **Solution**: Instead of scaffold this file when we run kb init we will check if we can change the tool implementation to do it when we call kb create webhook

PS.: The files are described in the description of the issue but as part of the task is required to analyse if has not other manifests which fails in the same condition.
