### ISSUE TITLE
With no CRDs installed, the controller fails with confusing error message

### ISSUE THREAD

**Issue by sttts** [kubernetes-sigs/kubebuilder#337]
```
2018/07/27 20:49:20 Registering Components.
2018/07/27 20:49:20 no matches for kind "Foo" in version "foo.k8s-go.openshift.org/v1beta1"
```

There is no indication that this is due to missing installation of the CRD.

**Comment by interma** [comment]
It's ok, thanks, I will open a PR later.

**Comment by interma** [comment]
The above controller-tools fix is not appropriate.

Opened a new fix in controller-runtime:
https://github.com/kubernetes-sigs/controller-runtime/pull/129
