### ISSUE TITLE
(kustomize/v2) - Remove the deprecation 

### ISSUE THREAD

**Issue by camilamacedo86** [kubernetes-sigs/kubebuilder#3372]
### What do you want to happen?

See that the default scaffolds:

> # Warning:
> 'patchesStrategicMerge' is deprecated. Please use 'patches' instead. Run
> "kustomize edit fix' to update
> your Kustomization automatically.

Therefore we should replace patchesStrategicMerge by patches in the kustomize/v2 templates code. PS.: Update the code and use make generate to update the samples under testdata.

**Comment by Sajiyah-Salat** [comment]
I am ready to work on this.

**Comment by Sajiyah-Salat** [comment]
I have tried finding the file where changes needed. unfortunately didnt get it. Let me know the file where changes needed.

**Comment by camilamacedo86** [comment]
Hi @Sajiyah-Salat,

This one seems a good issue !
Follow the steps to do this one.

1 - Follow up the quick start (https://book.kubebuilder.io/quick-start.html) and check the warning when you run make install

2 - Do the change 

You will need to replace : patchesStrategicMerge
With : patches
In the file: https://github.com/kubernetes-sigs/kubebuilder/blob/master/pkg/plugins/common/kustomize/v2/scaffolds/internal/templates/config/crd/kustomization.go#L113

3 - Now, let's test

- Run make install in the project root dir to generate another Kubebuilder CLI binary from your source code. 
- Then, create a directory like test (mkdir test) and do the test again to ensure that the above replace will sort out the warning 

4 - Run make generate to regenerate all (samples) under testdata  and docs within yout change prior send the PR 

**Acceptance criteria**  

- you should no longer see the warning or any new error after the change
- you also should check in `config/crd/kustomization` that the value patchesStrategicMerge was replaced by pacthes
- this change should only be made for the plugin kustomize/v2 (https://github.com/kubernetes-sigs/kubebuilder/blob/master/pkg/plugins/common/kustomize/v2) and should ONLY be reflected in the testdata projects which are built within go/v4 layout (see project-v4-*)

**Comment by Sajiyah-Salat** [comment]
I have tried making directory test and it exits already. also I got three deprecation notice in make generate. still I have tried my best to follow the steps.
