### ISSUE TITLE
Commands should not fail when/if hack/license is not present

### ISSUE THREAD

**Issue by camilamacedo86** [kubernetes-sigs/kubebuilder#3373]
### What broke? What's expected?

- Users should be able to use the tool without setting the license in all files. 

### Reproducing this issue

- Create a new project
- Remove the hack/boilerplate.go.txt
- Try to create an API

Then , you would will see the following error: 
```
2023/04/29 12:50:07 failed to create API: unable to scaffold with "base.go.kubebuilder.io/v4": error scaffolding API/controller: unable to load boilerplate: open hack/boilerplate.go.txt: no such file or directory

````
**Aceptence Criteria**

- If hack/boilerplate.go.txt is not present, then we should not fail as described above

The fix is here: https://github.com/kubernetes-sigs/kubebuilder/blob/7aa151a9ed9200a2c73e279506474f56d10e2135/pkg/plugins/golang/v4/scaffolds/api.go#L67-L70 (If cannot find the file then, we pass an empty string like “”)

### KubeBuilder (CLI) Version

3.10.0

### PROJECT version

3

**Comment by ashutosh887** [comment]
Let me work on this 
/assign

**Comment by camilamacedo86** [comment]
This bug should only be fixed for go/v4 plugin

**Comment by yyy1000** [comment]
When I check #3377, I found this issue. I'm glad to help with this together. :)
/assign

**Comment by yyy1000** [comment]
I think we can close this since #3378 is merged?
