### ISSUE TITLE
Bump k8s 1.27

### ISSUE THREAD

**Issue by camilamacedo86** [kubernetes-sigs/kubebuilder#3376]
### What do you want to happen?

To bump to use Kubernetes version 1.27 we need to:

- [x] Generate the envtools for it (it is done)

The build is made from the branch [tools-releases](https://github.com/kubernetes-sigs/kubebuilder/tree/tools-releases). So, we need to create a PR to generate tools with the latest binaries version

- [x]  bump controller-tools for a version using the k8s 1.27 - 
- [x]  the declarative plugin usually also needs to be updated: https://github.com/kubernetes-sigs/kubebuilder/blob/master/pkg/plugins/golang/declarative/v1/api.go#L35 (we usually contribute with the project to ensure that is bumped to use the latest k8s version) 

- [x]  bump controller-runtime latest release using k8s 1.27 : https://github.com/kubernetes-sigs/controller-runtime/pull/2189

- [x]  Update kubebuilder CLI to use the k8s 1.27 

- [x]  Update the CI for we begin to test against k8s 1.27, see: https://github.com/kubernetes-sigs/kubebuilder/blob/master/CONTRIBUTING.md#where-the-ci-tests-are-configured

**Comment by yashsingh74** [comment]
@camilamacedo86 can I help in this.

**Comment by NikhilSharmaWe** [comment]
@camilamacedo86 [controller-tools](https://github.com/kubernetes-sigs/controller-tools) has been updated with k8s 1.27, PTAL: https://github.com/kubernetes-sigs/controller-tools/pull/798.
There is also an open issue for a new release: https://github.com/kubernetes-sigs/controller-tools/issues/806

**Comment by camilamacedo86** [comment]
Done
