### ISSUE TITLE
lincense type none is scaffolding a header

### ISSUE THREAD

**Issue by camilamacedo86** [kubernetes-sigs/kubebuilder#3377]
### What broke? What's expected?

If we create a new project and use the flag option --license=none instead of not adding any license, it still scaffolds the boilerplate with header content `Copyright 2023 The {{ .owner }} authors.`. Therefore, this issue would be to fix this function by:

**I, as the user, would like to know to have any header added to my files when I use the option --license=none** 

In this case, the solution here is:

- Ensure that when this option is used, we will not scaffold hack/boilerplate.txt files
- Ensure when this option is used in the Makefile, we will scaffold the generate target within `object` instead of `object:headerFile="hack/boilerplate.go.txt"`: 

```
.PHONY: generate
generate: controller-gen ## Generate code containing DeepCopy, DeepCopyInto, and DeepCopyObject method implementations.
	$(CONTROLLER_GEN) object:headerFile="" paths="./..."
````
**I am a user. I would like to have the current behaviour done when I select none for a new optional flag with a name that make s it clearer (`copyright`)**

Following the places where the change needs to be made. See:
- https://github.com/kubernetes-sigs/kubebuilder/blob/7aa151a9ed9200a2c73e279506474f56d10e2135/pkg/plugins/golang/v4/scaffolds/internal/templates/hack/boilerplate.go#L100-L111
- https://github.com/kubernetes-sigs/kubebuilder/blob/7aa151a9ed9200a2c73e279506474f56d10e2135/pkg/plugins/golang/v4/init.go#L87-L89

See that this one is a follow-up of : https://github.com/kubernetes-sigs/kubebuilder/issues/3373

### KubeBuilder (CLI) Version

3.10.0

### Plugin versions

```yaml
go/v4
```

**Comment by camilamacedo86** [comment]
This bug should only be fixed for go/v4 plugin

**Comment by yyy1000** [comment]
I'd like to work on it. :)
/assign
