### ISSUE TITLE
Remove social support banner (Black Lives Matter) from header of documentation

### ISSUE THREAD

**Issue by camilamacedo86** [kubernetes-sigs/kubebuilder#3380]
### What do you want to happen?

We would like to announce that after careful consideration, we have made the decision to remove the Black Lives Matter header from Kubebuilder. We want to emphasize that our support for the movement remains unwavering. We added the header during a critical moment, as we have done in other projects. Our decision to remove it is not intended to reflect a diminished support for the cause, but rather to reaffirm our commitment to promoting diversity, inclusion, and equal opportunity within our team and community.

We understand that this decision may be disappointing for some members of our community. We want to reassure you that we remain dedicated to creating a welcoming and inclusive environment in the Kubebuilder community. We will continue to have meaningful conversations, educate ourselves, and work towards promoting equality and social justice. We appreciate your understanding and support in this matter, and we welcome any questions or concerns you may have.

**Comment by ashutosh887** [comment]
I would like to take up this issue and remove the Banner @camilamacedo86 

I believe it's only in the Docs website?

**Comment by Sajiyah-Salat** [comment]
Hello ashutosh, The issue was originally presented by me to Camilla. Therefore I would like to work on this. We intended to keep this topic between members. Kindly understand. Thank you.

**Comment by ashutosh887** [comment]
Hey @Sajiyah-Salat I didn't knew about it
I've already created PR #3381 for the same

cc: @camilamacedo86
