### ISSUE TITLE
Upgrade Kubernetes binaries to 1.11

### ISSUE THREAD

**Issue by gyliu513** [kubernetes-sigs/kubebuilder#339]
Kubernetes 1.11 has been release and it has some fix for crd resources, it is better to upgrade Kubernetes to 1.11 for kubebuilder to resolve those crd issues.

/cc @pmorie

**Comment by droot** [comment]
@gyliu513 Are we talking about some critical fixes or nice-to-have here ? Info will help us prioritize this.

**Comment by gyliu513** [comment]
@droot The registration of CRDs with status in 1.10 does not work, which sort of works in 1.11.

Please checkout https://github.com/kubernetes/kubernetes/pull/63598 for detail.

**Comment by wstrange** [comment]
I think I hit this issue trying the kubebuilder quick start on 1.11.2.

The generated crd does not validate with the server:

``kubectl apply -f config/crds
error: error validating "config/crds/ds_v1beta1_directory.yaml": error validating data: [ValidationError(CustomResourceDefinition.status): missing required field "conditions" in io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.CustomResourceDefinitionStatus, ValidationError(CustomResourceDefinition.status): missing required field "storedVersions" in io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.CustomResourceDefinitionStatus]; if you choose to ignore these errors, turn validation off with --validate=false`

```

**Comment by mheese** [comment]
I can confirm this, alternatively one can just remove the whole status section

**Comment by droot** [comment]
1.0.3 release ships with k8s 1.11 binaries and controller-runtime/tools have also moved to k8s 1.11. so closing this.
