### ISSUE TITLE
'make generate' can't work without kubebuilder binary

### ISSUE THREAD

**Issue by yyy1000** [kubernetes-sigs/kubebuilder#3390]
### What broke? What's expected?

If we don't set the kubebuilder binary in our system PATH, the 'make generate' command will fail.
Error message:

> ERRO[0000] error Initializing the project: kubebuilder init --domain tutorial.kubebuilder.io --repo tutorial.kubebuilder.io/project --license apache2 --owner The Kubernetes authors --plugins=go/v4 --component-config failed with error: (exec: "kubebuilder": executable file not found in $PATH) 

And even we set the path, the result is not as we expect. Cause it would not use the lastest binary we compile when 'make generate'.

I think it's because the lastest PR: 
https://github.com/kubernetes-sigs/kubebuilder/pull/3231/files#diff-14a46a8334eccfba24cd4de8c126e3fc9ecf705935586be96d3b665ff403c010L37:~:text=binaryPath%20%3A%3D%20%22/tmp/kubebuilder/bin/kubebuilder%22

### Reproducing this issue

1. Fork the repo
2. Run 'make generate'

### KubeBuilder (CLI) Version

3.10

**Comment by yyy1000** [comment]
I think the PR #3391 will also fix this one.

**Comment by camilamacedo86** [comment]
I think we can close this one.
The issue here was that the dev environment was not setup as described in the Contributing guide: https://github.com/kubernetes-sigs/kubebuilder/blob/master/CONTRIBUTING.md#how-to-build-kubebuilder-locally
