### ISSUE TITLE
Kubernetes and Kubebuilder use different mechanisms to generate plurals

### ISSUE THREAD

**Issue by mrueg** [kubernetes-sigs/kubebuilder#3402]
### What broke? What's expected?

Kubernetes uses a custom mechanism to guess and generate plurals for CRDs in https://github.com/kubernetes/apimachinery/blob/master/pkg/api/meta/restmapper.go#L126

Kubebuilder uses https://github.com/gobuffalo/flect which has its own custom set of rules. https://github.com/kubernetes-sigs/kubebuilder/blob/6c11f05e39d25767a953878255ffd6f7d24822c5/pkg/model/resource/utils.go#L72

Although one could argue that the method kubernetes uses is broken and not ideal, it would be great if kubebuilder could apply the same default mechanism to generate plurals so it is easier for kubernetes clients to resolve a resourceplural from a GroupVersionKind mapping.

### KubeBuilder (CLI) Version

3.10.0

**Comment by camilamacedo86** [comment]
It has a proposed solution in : https://github.com/kubernetes-sigs/kubebuilder/pull/3408
It seems very reasonable ask.

**Comment by lauchokyip** [comment]
There are still some discussions happening on this thread https://github.com/kubernetes/kube-state-metrics/pull/2065, should we wait until the consensus is made ?

**Comment by rexagod** [comment]
Boiling down that thread, the overall ask is to have a de-facto way of pluralizing that helps keep the resource names consistent throughout the ecosystem. I believe using the same logic as apimachinery should allow us to achieve that.

**Comment by Kavinjsir** [comment]
Hey @mrueg @rexagod , would you provide some cases/code snippets that come with such an attempt to make the plural consistent? I'm trying to understand how the consistent plural system can help *kubernetes clients to resolve a resourceplural from a GroupVersionKind mapping.*

**Comment by rexagod** [comment]
We've had to [extract](https://github.com/kubernetes/kube-state-metrics/pull/1851/files#diff-916e6863e1245c673b4e5965c98dc27bafbd72650fdb38ce65ea73ee6304e027R58) and [match](https://github.com/kubernetes/kube-state-metrics/pull/1851/files#diff-916e6863e1245c673b4e5965c98dc27bafbd72650fdb38ce65ea73ee6304e027R133) plurals to avoid instances where there may be [discrepancies](https://github.com/open-policy-agent/gatekeeper/issues/2751) between the expected and actual plurals.

**Comment by rexagod** [comment]
Enforcing a common "de-facto" standard through `kubebuilder` will solve such cases to a great extent.

**Comment by ashutosh887** [comment]
Should I take this up? @Kavinjsir @varshaprasad96 @camilamacedo86

**Comment by Sajiyah-Salat** [comment]
Hello @camilamacedo86 It looks like code issue. Should I work on this? 
I have gone through the pr. understood somewhat maybe. I would give it  a try if possibe. 
If there is anything else I should know or refer to let me know.

**Comment by joelanford** [comment]
I'm -1 on this change. From an objective grammatical perspective, Kubebuilder's implementation is clearly better than apimachinery's based on the test case changes in the PR.  If I'm a kubebuilder user and I see Kubebuilder generate an incorrect plural, I would expect to either notice and fix it myself OR have a reviewer notice it and ask me to fix it, thus adding friction that just gets us back to where things are now.

The GoDoc for the apimachinery function says:
> // UnsafeGuessKindToResource converts Kind to a resource name.
> // Broken. This method only "sort of" works when used outside of this package.  It assumes that Kinds and Resources match
> // and they aren't guaranteed to do so.

So "Unsafe" is in the name of the function, and "Broken" is in the GoDoc. It also admits that the function only sort of works when used outside that package. Kubebuilder is outside that package. Why would we want to use it?

> Although one could argue that the method kubernetes uses is broken and not ideal, it would be great if kubebuilder could apply the same default mechanism to generate plurals so it is easier for kubernetes clients to resolve a resourceplural from a GroupVersionKind mapping.

But that function is unsafe and broken. Kubebuilder has been in the wild for years generating different plurals. IMO no client should ever expect to correctly resolve a resourceplural from a GVK unless they are using a REST mapper.
