### ISSUE TITLE
Bug in docs around component config and using a custom type

### ISSUE THREAD

**Issue by hsyed-dojo** [kubernetes-sigs/kubebuilder#3418]
### What broke? What's expected?

I found a problem trying to switch my project to [component config](https://book.kubebuilder.io/component-config-tutorial/tutorial.html). I need to provide a custom type as I'd like to configure further facets of my operator using this mechanism.

The [documentation](https://book.kubebuilder.io/component-config-tutorial/updating-main.html#updating-main) suggests that a custom type needs to be registered with the scheme in `main.go`. If I do this manager startup fails with:

```
ERROR	setup	unable to load the config file	{"error": "could not decode file into runtime.Object"}
```

If I do not register my custom type with the scheme the new type deserializes correctly and everything works.

Some feedback on the component config process and potentially improving the docs. The docs suggest creating a new API for the config using kubebuilder. This forces the user to turn the project into a multi-group project. This seems to be unnecessary since the type does not need to be registered with the scheme. It might be simpler for the user to just plop a config struct somewhere in their codebase manually ? 

### Reproducing this issue

Create a hello world operator with kubebuilder, follow the docs exactly to enable component config and add a custom type. Deploy the operator somewhere. 

### KubeBuilder (CLI) Version

3.10.0

### PROJECT version

v1

### Plugin versions

```yaml
- go.kubebuilder.io/v4-alpha
```

### Other versions

1.20.4
sigs.k8s.io/controller-runtime v0.14.1

### Extra Labels

/kind documentation

**Comment by hsyed-dojo** [comment]
![image](https://github.com/kubernetes-sigs/kubebuilder/assets/91477794/656eff7e-f99f-495d-b9ca-b6e2fe45a15f)

I just updated controller-runtime to `0.14.4` in my operators and the documented approach for wiring up the component config  is now using deprecated APIs. 

I feel like going back to command line flags for configuring the controller-runtime and just loading my custom config file outside of the kubuilder rails via a configmap because this stuff does not seem stable yet.

**Comment by camilamacedo86** [comment]
Thank you for raising this one.
We will need to look out on this.

It seems that we just need to address the deprecation or did I missed something on this one?
