### ISSUE TITLE
`kubebuilder create` doesn't generate files that compile, missing DeepCopyObject

### ISSUE THREAD

**Issue by cflewis** [kubernetes-sigs/kubebuilder#344]
I can't seem to get Kubebuilder release 1.0.0 to actually create valid API files.

```shell
$ rm -rf vendor
$ dep ensure
$ make test

go generate ./pkg/... ./cmd/...
go fmt ./pkg/... ./cmd/...
go vet ./pkg/... ./cmd/...

pkg/apis/bar/v1beta1/foo_types.go:63:45: cannot use Foo literal (type *Foo) as type runtime.Object in argument to SchemeBuilder.Register:
        *Foo does not implement runtime.Object (missing DeepCopyObject method)
<SNIP>
```

What's wrong here?

**Comment by droot** [comment]
Looks like deepcopy-gen hasn't generated the file which implements the DeepCopy methods for the type.
Can you run `tree pkg/apis` and paste here to examine directory tree ?

**Comment by cflewis** [comment]
I deleted everything and reinstalled following the instructions exactly (not doing #326 ) which seems to have fixed it.

Sorry for the noise 😞
