### ISSUE TITLE
kubebuilder generate multiple roles in multiple namespace

### ISSUE THREAD

**Issue by ddjjia** [kubernetes-sigs/kubebuilder#3455]
### What do you want to happen?

// +kubebuilder:rbac:groups="",namespace=ns1,resources=rs1,verbs=get;list;patch;update;watch;create
// +kubebuilder:rbac:groups="",namespace=ns2,resources=rs2,verbs=get;list;watch

with above annotation, and command `rbac:roleName=manager-role`, two roles are generated with the same role name. Can we somehow configure different role name according to different namespaces?

**Comment by camilamacedo86** [comment]
Hi @ddjjia,

The rules are all generated under the roles file. (config/rbac/role) example: https://github.com/kubernetes-sigs/kubebuilder/blob/master/testdata/project-v4-with-deploy-image/config/rbac/role.yaml

The manifests with view and edit in the name which are generate under config/rbac has the purpose to be helpers for the admins create permissions and are not used by the project itself. They will always be updated accordingly. 

So, I am closing this one. 
However, if you see that is required please feel free to re-open this issue.
