### ISSUE TITLE
Update Kubebuilder documentation with steps to add custom configurations

### ISSUE THREAD

**Issue by varshaprasad96** [kubernetes-sigs/kubebuilder#3457]
### What do you want to happen?

This is a documentation issue.

With the [deprecation](https://github.com/kubernetes-sigs/controller-runtime/issues/895) of `component-config` based scaffolding in controller-runtime (v0.15.0), Kubebuilder has also taken the action to deprecate it in the upcoming release (https://github.com/kubernetes-sigs/kubebuilder/pull/3442).

An alternative to using `component-config` is to pass the customizations through `manager.Options` struct in controller-runtime. 

A detailed reference and the steps are provided in the following places:
1. https://github.com/kubernetes-sigs/kubebuilder/pull/3442#discussion_r1224479086 and also in 
2. https://github.com/kubernetes-sigs/kubebuilder/pull/3421#issuecomment-1574202576

The Kubebuilder documentation needs to be updated with this information as an alternative. 

### Extra Labels

/kind documentation

**Comment by mjlshen** [comment]
I'm interested in working on this one :D

**Comment by ashutosh887** [comment]
Let me work on this

/assign

**Comment by varshaprasad96** [comment]
This seems to be completed from #3577. I'm going to close it, @ashutosh887 let me know if there is anything else remaining on this.
