### ISSUE TITLE
Fix lint warnings (remove deprecated checks)

### ISSUE THREAD

**Issue by camilamacedo86** [kubernetes-sigs/kubebuilder#3465]
### What broke? What's expected?

By running make lint or make lint-fix we can check the following warnings. Therefore, we meed to remove the checks following checks from the `.golangci.yml` file in the root dir:

```
/Users/camiladeomacedo/go/src/sigs.k8s.io/kubebuilder/bin/golangci-lint run --fix
WARN [runner] The linter 'varcheck' is deprecated (since v1.49.0) due to: The owner seems to have abandoned the linter. Replaced by unused. 
WARN [runner] The linter 'golint' is deprecated (since v1.41.0) due to: The repository of the linter has been archived by the owner. Replaced by revive. 
WARN [runner] The linter 'maligned' is deprecated (since v1.38.0) due to: The repository of the linter has been archived by the owner. Replaced by govet 'fieldalignment'. 
WARN [runner] The linter 'scopelint' is deprecated (since v1.39.0) due to: The repository of the linter has been deprecated by the owner. Replaced by exportloopref. 
WARN [runner] The linter 'deadcode' is deprecated (since v1.49.0) due to: The owner seems to have abandoned the linter. Replaced by unused. 
WARN [runner] The linter 'structcheck' is deprecated (since v1.49.0) due to: The owner seems to have abandoned the linter. Replaced by unused. 
WARN [runner] The linter 'interfacer' is deprecated (since v1.38.0) due to: The repository of the linter has been archived by the owner.  
```

### KubeBuilder (CLI) Version

master

**Comment by mjlshen** [comment]
Many of these were removed a while ago https://github.com/kubernetes-sigs/kubebuilder/commit/88c78ddfda6a865baefa6a2d51dda804856c5ffb - at least I don't see them presently anymore

**Comment by camilamacedo86** [comment]
HI @rayowang,

To see the warnings run `make lint` for kubebuilder project.
We need to fix the warnings for the Kubebuilder itself and not for the projects built with.

**Comment by mjlshen** [comment]
From the `master` branch I get no errors:

```
❯ make lint
/Users/mshen/git/mjlshen/kubebuilder/bin/golangci-lint run

❯ make lint-fix
/Users/mshen/git/mjlshen/kubebuilder/bin/golangci-lint run --fix

❯ echo $?     
0
```

**Comment by camilamacedo86** [comment]
Hi @rayowang,

It is not about errors but about warnings. 

By running the command you will see as described in the issue:

/Users/camiladeomacedo/go/src/sigs.k8s.io/kubebuilder/bin/golangci-lint run --fix
WARN [runner] The linter 'varcheck' is deprecated (since v1.49.0) due to: The owner seems to have abandoned the linter. Replaced by unused. 
WARN [runner] The linter 'golint' is deprecated (since v1.41.0) due to: The repository of the linter has been archived by the owner. Replaced by revive. 
WARN [runner] The linter 'maligned' is deprecated (since v1.38.0) due to: The repository of the linter has been archived by the owner. Replaced by govet 'fieldalignment'. 
WARN [runner] The linter 'scopelint' is deprecated (since v1.39.0) due to: The repository of the linter has been deprecated by the owner. Replaced by exportloopref. 
WARN [runner] The linter 'deadcode' is deprecated (since v1.49.0) due to: The owner seems to have abandoned the linter. Replaced by unused. 
WARN [runner] The linter 'structcheck' is deprecated (since v1.49.0) due to: The owner seems to have abandoned the linter. Replaced by unused. 
WARN [runner] The linter 'interfacer' is deprecated (since v1.38.0) due to: The repository of the linter has been archived by the owner.  

**See the WARN. We need to remove the depreacations**

**Comment by camilamacedo86** [comment]
Hi @rayowang,

It seems sorted out. I just tested now:

 ```
 $ make lint
golangci/golangci-lint info checking GitHub for tag 'v1.51.2'
golangci/golangci-lint info found version: 1.51.2 for v1.51.2/darwin/arm64
golangci/golangci-lint info installed /Users/camiladeomacedo/go/src/sigs.k8s.io/kubebuilder/bin/golangci-lint
/Users/camiladeomacedo/go/src/sigs.k8s.io/kubebuilder/bin/golangci-lint run
```

So, we can close this one.
Thank you a lot for your collaboration.

**Comment by ashutosh887** [comment]
Yes @camilamacedo86 
Even I applied and got the sponsor but my membership wasn't approved I don't know why 😞
