### ISSUE TITLE
{resource)_controller_test.go doesn't fail when it should

### ISSUE THREAD

**Issue by eastlondoner** [kubernetes-sigs/kubebuilder#347]
Using v1.0.0
When a controller is created the corresponding test includes this code:
```
	// The instance object may not be a valid object because it might be missing some required fields.
	// Please modify the instance object by adding required fields and then remove the following if statement.
	if apierrors.IsInvalid(err) {
		t.Logf("failed to create object, got an invalid object error: %v", err)
		return
	}
```

The problem with that is it the test passes (logging a message and then returning is not a test failure).
In many cases the log is not visible (e.g. if you run `make test`).

This should simply be
```
	if apierrors.IsInvalid(err) {
		t.Fatalf("failed to create object, got an invalid object error: %v", err)
	}
```

I would submit a PR but I can't figure out where this test code is actually generated.

**Comment by eastlondoner** [comment]
bump - this doesn't seem complicated, if someone can point me at where this code comes from I can make a PR

**Comment by pwittrock** [comment]
@eastlondoner 

Thanks for the offer.  This is the file that needs to be updated:

https://github.com/kubernetes-sigs/controller-tools/blob/master/pkg/scaffold/controller/controllertest.go
