### ISSUE TITLE
Support logging only Errors and reconciliation fails to stderr

### ISSUE THREAD

**Issue by abergmeier** [kubernetes-sigs/kubebuilder#3476]
### What broke? What's expected?

All log output should go to stdout.
Only errors should go to stderr.

This is especially important for software like GKE which expect this kind of behavior and tries to parse stderr.

### Reproducing this issue

I tried to change logging to:

```go
	opts := zap.Options{
		Development: true,
	}
	opts.DestWriter = os.Stdout
	opts.BindFlags(flag.CommandLine)
	flag.Parse()

	zr := zap.NewRaw(zap.UseFlagOptions(&opts))
	zr = zr.WithOptions(uzap.ErrorOutput(os.Stderr))

	ctrl.SetLogger(zapr.NewLogger(zr))
```

but `logger.Error` calls then are printed to stdout

### KubeBuilder (CLI) Version

Version: main.version{KubeBuilderVersion:"3.10.0", KubernetesVendor:"1.26.1", GitCommit:"0fa57405d4a892efceec3c5a902f634277e30732", BuildDate:"2023-04-15T08:10:35Z", GoOs:"linux", GoArch:"amd64"}

### PROJECT version

3

### Plugin versions

```yaml
go.kubebuilder.io/v4
```

### Extra Labels

/kind feature

**Comment by camilamacedo86** [comment]
This option came from controller-runtime https://github.com/kubernetes-sigs/controller-runtime. Could you please open an issue in the respective repository? 

Also, please feel free to contribute with Kubebuilder docs if you would like to supplement how to work within afterwords. Therefore, I am closing this one. However, please feel free to re-open if you see that would be required.
