### ISSUE TITLE
make docker-image doesn't work on mac

### ISSUE THREAD

**Issue by eastlondoner** [kubernetes-sigs/kubebuilder#348]
The sed command in the makefile isn't valid for the bsd version of sed that ships with OSX:

```
sed -i 's@image: .*@image: '"controller:latest"'@' ./config/default/manager_image_patch.yaml
sed: 1: "./config/default/manage ...": invalid command code .
```

**Comment by droot** [comment]
@eastlondoner  Can you share tweaked version of this command that works ?

Happy to review the code and get it in if you would like to submit a PR for it.

**Comment by droot** [comment]
Kubebuilder uses scaffolding tools from https://github.com/kubernetes-sigs/controller-tools this repo. So the fix needs to be made there and vendor deps needs to be updated in Kubebuilder.

**Comment by eastlondoner** [comment]
thanks @droot I've made a PR there

**Comment by eastlondoner** [comment]
lol, realised I should check that changing the controller-tools repo has fixed this

**Comment by droot** [comment]
We will have to update the controller-tools deps in kubebuilder repo to pick up the fixes in controller-tools.

Steps to update the controller-tools deps:
```
# cd to <kubebuilder-repo>cmd
dep ensure -update sigs.k8s.io/controller-tools

# run test.sh locally
# make a PR
```
