### ISSUE TITLE
kubebuilder book lists wrong options for rbac generator

### ISSUE THREAD

**Issue by ltsonov-cb** [kubernetes-sigs/kubebuilder#3481]
### What broke? What's expected?

(Not sure if this is the proper place to log this; please shout if not)

I noticed in the kubebuilder book that one can add a headerFile or year to the generated files. However, when I try to do so locally, controller-gen only recognizes the `roleName` option and errors out if any of the others are provided. 

```
// +rbac
generates ClusterRole objects.
headerFile string
specifies the header text (e.g. license) to prepend to generated files.
roleName string
sets the name of the generated ClusterRole.
year string
specifies the year to substitute for " YEAR" in the header file.
```
Source: https://book.kubebuilder.io/reference/controller-gen.html?highlight=rbac:roleName#generators 

Is this a bug in the documentation (the options should be removed) or a bug with the tools (the options should work) ? I guess the latter would go into controller-tools instead. 

Also, is there a supported way to ensure that generated files have some prefix added (for example, "DO NOT EDIT MANUALLY") ?

### Reproducing this issue

Try to run the generator:
`controller-gen rbac:roleName=manager-role,headerFile="AUTOGENERATED, DO NOT EDIT MANUALLY" paths="./..." output:crd:artifacts:config=config/crd/bases`  and observe the error:

```
unable to parse option "rbac:roleName=manager-role,headerFile=AUTOGENERATED, DO NOT EDIT MANUALLY": [unknown argument "headerFile" (at <input>:1:33) extra arguments provided: "AUTOGENERATED, DO NOT EDIT MANUALLY" (at <input>:1:34)]

```

### KubeBuilder (CLI) Version

N/A as this is a doc issue for kubebuilder

### PROJECT version

3

### Plugin versions

```yaml
go.kubebuilder.io/v3
```

### Other versions

controller-gen --version: v0.9.0

### Extra Labels

/kind documentation

**Comment by camilamacedo86** [comment]
Hi @ltsonov-cb,

The controller-gen option allow you inform the path of the file with the header as it is scaffolded in the projects created with Kubebuilder by default, see:

https://github.com/kubernetes-sigs/kubebuilder/blob/4f7751a1e357f49ec5ff17273342ca4b3094ac2c/testdata/project-v4/Makefile#L51-L53

If you would like to check some examples over how to use the rbac see the code scaffold by using the plugin Deploy Image (https://book.kubebuilder.io/plugins/deploy-image-plugin-v1-alpha), example in the sample:

https://github.com/kubernetes-sigs/kubebuilder/blob/66f3fbc7ae349e8ee31f1c6eb8d55d5b1c78ce52/testdata/project-v4-with-deploy-image/internal/controller/busybox_controller.go#L63-L68

In this way, I am closing this one as sorted out.
However, if you see that it would still need to be open please feel free to re-open 

Also, feel free to collaborate with the docs by pushing a PR with improvements if you see that should fit.

**Comment by ltsonov-cb** [comment]
Hi @camilamacedo86  

I guess I didn't explain properly the issue originally, I will try again.

Using `object:headerFile` only populates boilerplate on the generated `*.go` files. However, it does not populate it on generated yaml files.

One such yaml file is the RBAC definition, which is derived from various `//+kubebuilder:rbac:*` directives. I would like to be able to add placeholder headers to these generated files as well; otherwise they are lost on every re-generate. 

The question here is - is kubebuilder supposed to support this or not?

The `kubebuilder` book seems to say "YES" and that using `rbac:headerFile="hack/boilerplate.yaml.txt"` should do the trick. However it does not work in practice as `controller-gen` does not support `rbac:headerFile`

If it is supposed to work, I guess it's a change in the gen tools. 
If it is not supposed to work, then the book should not mention the `rbac:headerFile` option. 

I can probably open a PR in the latter case, not sure about the former.
