### ISSUE TITLE
quick start error deploying sample CR

### ISSUE THREAD

**Issue by csantanapr** [kubernetes-sigs/kubebuilder#3499]
### What broke? What's expected?

Following the quickstart https://book.kubebuilder.io/quick-start.html#install-instances-of-custom-resources

The command produce error
```
kubectl apply -f config/samples/
```
The error
```
guestbook.webapp.my.domain/guestbook-sample created
error: error validating "config/samples/kustomization.yaml": error validating data: [apiVersion not set, kind not set]; if you choose to ignore these errors, turn validation off with --validate=false
```

Workaround use `-k`
```
kubectl apply -k config/samples/
```

### KubeBuilder (CLI) Version

Version: main.version{KubeBuilderVersion:"3.11.1", KubernetesVendor:"1.27.1", GitCommit:"1dc8ed95f7cc55fef3151f749d3d541bec3423c9", BuildDate:"2023-07-03T13:10:56Z", GoOs:"linux", GoArch:"arm64"}

### Extra Labels

/kind documentation

**Comment by Kavinjsir** [comment]
I think this is a good catch!

To keep consistency, maybe we can consider applying the code line `kubectl apply -k` also in:
1. https://github.com/kubernetes-sigs/kubebuilder/blob/v3.11.1/pkg/plugins/golang/v3/scaffolds/internal/templates/readme.go#L48
2. https://github.com/kubernetes-sigs/kubebuilder/blob/v3.11.1/pkg/plugins/golang/v4/scaffolds/internal/templates/readme.go#L48

**Comment by camilamacedo86** [comment]
See your error: error validating data: [apiVersion not set, kind not set]; if you choose to ignore these errors, turn validation off with --validate=false

You probably did not executed make manifests to properly generate the manifests,
I am unable to reproduce the error by following ALL steps described in the quick start

We also do the same steps in the e2e tests and no issues are found.

@Kavinjsir,

Are you able to reproduce this issue?

**Comment by Kavinjsir** [comment]
> See your error: error validating data: [apiVersion not set, kind not set]; if you choose to ignore these errors, turn validation off with --validate=false
> 
> You probably did not executed make manifests to properly generate the manifests, I am unable to reproduce the error by following ALL steps described in the quick start
> 
> We also do the same steps in the e2e tests and no issues are found.
> 
> @Kavinjsir,
> 
> Are you able to reproduce this issue?

@camilamacedo86 Yes, from my local, I can get a similar error when running `kubectl apply -f config/sample` under `testdata/project-v4`:
<img width="1609" alt="Screenshot 2023-07-21 at 12 20 29 PM" src="https://github.com/kubernetes-sigs/kubebuilder/assets/18136486/874a45ef-ed5e-4adb-a944-72f596d3c2ec">

To me, it looks good to replace flag `-f` with `-k` as `-k` typically handles a kustomization directory.
