### ISSUE TITLE
Update Contributing Guide

### ISSUE THREAD

**Issue by droot** [kubernetes-sigs/kubebuilder#350]
Contributing guide is out of date and mentions using container-builder-local for build steps etc. Task is to update the guide

- Describe the dependency on controller-runtime, controller-tools repos
- Steps to make changes in the codebase or dependencies and build and test it.
- Any special instructions about the pull-request etc.

**Comment by interma** [comment]
@droot Yes, I build as the guide but failed. And I solved them, looks some steps need to be updated.
e.g.
```
$ container-builder-local --config=build/cloudbuild_local.yaml --dryrun=false \
  --write-workspace=$OUTPUT .
2018/08/08 15:19:16 WARNING: container-builder-local is deprecated. Please run `gcloud install cloud-build-local` to install its replacement.
```
If you don't mind, I will open a PR later to improve some parts of the guide, to solve the issues which I encountered.

Thanks.
