### ISSUE TITLE
CRD generation tool panics when a type references another type

### ISSUE THREAD

**Issue by droot** [kubernetes-sigs/kubebuilder#351]
Reported by @jpeeler 

The controller-tools parser doesn't seem to like referencing a vendored kubebuilder project: "panic: Found multiple apis directory paths: github.com/jpeeler/podpreset-crd/pkg/apis and github.com/jpeeler/podpresetbinding-crd/pkg/apis.  Do you have a +resource tag on a resource that is not in a version directory?"

The following project can be used to reproduce the issue: 
https://github.com/jpeeler/podpresetbinding-crd/

**Comment by fanzhangio** [comment]
@droot  I have debugged this issue. This is a resource filter bug. I sent out a PR to fix it.

@jpeeler After the PR fix get merged, you have to add an annotation 
```golang
// +kubebuilder:resource:path=podpresetbindings
```
before this line:
https://github.com/jpeeler/podpresetbinding-crd/blob/master/pkg/apis/podpreset/v1alpha1/podpresetbinding_types.go#L48
