### ISSUE TITLE
kubebuilder make docker-buildx  net/http: TLS handshake timeout

### ISSUE THREAD

**Issue by yueyueaa** [kubernetes-sigs/kubebuilder#3516]
`make docker-buildx`
[linux/amd64 builder 3/9] COPY go.mod go.mod                                                                                                                                                                                    0.1s
[linux/amd64 builder 4/9] COPY go.sum go.sum                                                                                                                                                                                        0.2s
ERROR [linux/amd64 builder 5/9] RUN go mod download                                                                                                                                                                                91.6s
CANCELED [linux/amd64->arm64 builder 5/9] RUN go mod download                                                                                                                                                                      91.6s
 [linux/amd64 builder 5/9] RUN go mod download:
91.55 go: github.com/beorn7/perks@v1.0.1: Get "https://goproxy.cn/github.com/beorn7/perks/@v/v1.0.1.mod": net/http: TLS handshake timeout

`go env`
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOENV="/root/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/root/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/root/go"
GOPRIVATE=""
GOPROXY="goproxy.cn,direct"
GOROOT="/snap/go/current"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/snap/go/current/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.20.6"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="0"
GOMOD="/root/go/src/projects/go.mod"
GOWORK=""
CGO_CFLAGS="-O2 -g"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-O2 -g"
CGO_FFLAGS="-O2 -g"
CGO_LDFLAGS="-O2 -g"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -fno-caret-diagnostics -Qunused-arguments -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build2274952084=/tmp/go-build -gno-record-gcc-switches"

go get no problem
`go get -u golang.org/x/lint/golint`
go: downloading golang.org/x/lint v0.0.0-20210508222113-6edffad5e616
go: downloading golang.org/x/tools v0.11.1
go: downloading golang.org/x/net v0.12.0
go: downloading golang.org/x/term v0.10.0
go: upgraded golang.org/x/lint v0.0.0-20190930215403-16217165b5de => v0.0.0-20210508222113-6edffad5e616
go: upgraded golang.org/x/net v0.10.0 => v0.12.0
go: upgraded golang.org/x/sys v0.8.0 => v0.10.0
go: upgraded golang.org/x/term v0.8.0 => v0.10.0
go: upgraded golang.org/x/text v0.9.0 => v0.11.0
go: upgraded golang.org/x/tools v0.9.1 => v0.11.1

`echo $HTTP_PROXY && echo $http_proxy` and `echo $HTTPS_PROXY && echo $https_proxy` is null

Can I deal with the issue?

**Comment by yueyueaa** [comment]
https://github.com/ko-build/ko    
But use `ko` can package the image
`KO_DOCKER_REPO=localhost:5000 ko build cmd/main.go`

**Comment by liangyuanpeng** [comment]
Seems like it's the problem of proxy.cn and your network?

**Comment by yueyueaa** [comment]
> Seems like it's the problem of proxy.cn and your network?

yeah，it works fine after I changed the dns conf. (`vim /etc/resolv.conf`)
`nameserver 127.0.0.53` to `114.114.114.114`
