### ISSUE TITLE
Docs and scaffold should  contain same commands

### ISSUE THREAD

**Issue by Sajiyah-Salat** [kubernetes-sigs/kubebuilder#3522]
## Description :
Following on: https://github.com/kubernetes-sigs/kubebuilder/pull/3475
The goal of this issue is to check if 
[docs quick start](https://book.kubebuilder.io/quick-start.html)
 [readme.md](https://github.com/kubernetes-sigs/kubebuilder/blob/master/docs/book/src/cronjob-tutorial/testdata/project/README.md)
[readme.go](https://github.com/kubernetes-sigs/kubebuilder/blob/master/pkg/plugins/golang/v4/scaffolds/internal/templates/readme.go)
files are alligned together. Also readme.go is used to scaffold projects so we just want to check the command.
We cant make it same as readme.md but command should be the same and thats the goal

**Comment by Sajiyah-Salat** [comment]
https://github.com/kubernetes-sigs/kubebuilder/blob/d08f9d7f1c25bccecec2249ec91cd888eed2665e/pkg/plugins/golang/v4/scaffolds/internal/templates/readme.go#L48C24-L48C24
is used to apply kustomization files. In config samples we have two files one is kustomization file and other is simple yaml file
Why we are using -k ?
When I made a operator and test it out on kind I have used kubectl apply -f

**Comment by Sajiyah-Salat** [comment]
https://github.com/kubernetes-sigs/kubebuilder/blob/d08f9d7f1c25bccecec2249ec91cd888eed2665e/pkg/plugins/golang/v4/scaffolds/internal/templates/readme.go#L82
Why do we have %s here. 
How code works here. How can  I debug the code?

**Comment by camilamacedo86** [comment]
Hi @Sajiyah-Salat,

If I am not wrong I answered it in another place.
However, following here again.

See that it is a string const.
Therefore, when we use `%s` we can replace it with any string value.
We usually use it when more than one value could fit in according to some condition.

IN this case, we are replacing the values of this const/template with the commands in: https://github.com/kubernetes-sigs/kubebuilder/blob/d08f9d7f1c25bccecec2249ec91cd888eed2665e/pkg/plugins/golang/v4/scaffolds/internal/templates/readme.go#L47-L56. Why not put the commands directly?

In this case, it seems that was a choice of preference to try make easier to know the commands, has not a real reason to do so. 

Therefore, I am closing this one as sorted out. 
However, feel free to re-open if you see that fits.
