### ISSUE TITLE
Bump K8s dependencies to 1.28 

### ISSUE THREAD

**Issue by varshaprasad96** [kubernetes-sigs/kubebuilder#3549]
### What do you want to happen?

Creating this issue to track the bumping of K8s dependencies to 1.28.

Controller-runtime (https://github.com/kubernetes-sigs/controller-runtime/releases/tag/v0.16.0) and controller-tools (https://github.com/kubernetes-sigs/controller-tools/releases/tag/v0.13.0) have released a version with 1.28 releases of k8s dependencies. 

Things to do:
- [ ] Bump deps in Kubebuilder binary 
- [ ] Bump reps in all the plugins 
- [ ] Bump deps in KB declarative pattern (the PR to deprecate and remove it is still in progress)

Refer to https://github.com/kubernetes-sigs/kubebuilder/pull/3444 to know how it was done for k8s 1.27 bumps.

**Comment by camilamacedo86** [comment]
Just to provide further info:

To bump to use Kubernetes version 1.28 we need to:

- [] Generate the envtools for it (it is done)

The build is made from the branch [tools-releases](https://github.com/kubernetes-sigs/kubebuilder/tree/tools-releases). So, we need to create a PR to generate tools with the latest binaries version

- []  bump controller-tools for a version using the k8s 1.28 - 
- []  the declarative plugin usually also needs to be updated: https://github.com/kubernetes-sigs/kubebuilder/blob/master/pkg/plugins/golang/declarative/v1/api.go#L35 (we usually contribute with the project to ensure that is bumped to use the latest k8s version) 

- []  bump controller-runtime latest release using k8s 1.28 : https://github.com/kubernetes-sigs/controller-runtime/pull/2189


- []  Update kubebuilder CLI to use the k8s 1.28 

- []  Update the CI for we begin to test against k8s 1.28, see: https://github.com/kubernetes-sigs/kubebuilder/blob/master/CONTRIBUTING.md#where-the-ci-tests-are-configured

Example: https://github.com/kubernetes-sigs/kubebuilder/issues/3376#issue-1690463127

**Comment by Kavinjsir** [comment]
Can someone help with reviewing: https://github.com/kubernetes/test-infra/pull/30523 please?

I'm trying to update the Kubernetes versions based on:
https://github.com/kubernetes-sigs/kind/releases/tag/v0.20.0

cc: @camilamacedo86 @varshaprasad96
