### ISSUE TITLE
Book ERROR   setup   problem running manager {"error": "open /tmp/k8s-webhook-server/serving-certs/tls.crt: no such file or directory"}

### ISSUE THREAD

**Issue by csantanapr** [kubernetes-sigs/kubebuilder#3559]
### What broke? What's expected?

Following the book tutorial in ordered steps, when getting to this page https://book.kubebuilder.io/cronjob-tutorial/running

At this point of the tutorial the user doesn't want to run the webhooks, just test with `make run` and disable the webhooks.

It intructs the user to skip the webhook with environment variable
```shell
export ENABLE_WEBHOOKS=false
make run
```
I expect to not see any errors.
The previous page https://book.kubebuilder.io/cronjob-tutorial/webhook-implementation
Doesn't mention at all that the main.go needs be modified from:
```go
	if err = (&batchv1.CronJob{}).SetupWebhookWithManager(mgr); err != nil {
		setupLog.Error(err, "unable to create webhook", "webhook", "CronJob")
		os.Exit(1)
	}
```
Modified to:
```go
	if os.Getenv("ENABLE_WEBHOOKS") != "false" {
		if err = (&batchv1.CronJob{}).SetupWebhookWithManager(mgr); err != nil {
			setupLog.Error(err, "unable to create webhook", "webhook", "CronJob")
			os.Exit(1)
		}
	}
```

### Reproducing this issue

Follow tutorial in order up to this page Following the book tutorial in ordered steps, when getting to this page https://book.kubebuilder.io/cronjob-tutorial/running

It intructs the user to skip the webhook with environment variable
```shell
export ENABLE_WEBHOOKS=false
make run
```

When running I get the following error 
```
2023-08-25T17:57:51Z    ERROR   setup   problem running manager {"error": "open /tmp/k8s-webhook-server/serving-certs/tls.crt: no such file or directory"}
main.main
        /workspaces/kubebuilder-book-club-aws/cmd/main.go:116
runtime.main
        /usr/local/go/src/runtime/proc.go:250
```

### KubeBuilder (CLI) Version

3.11.1

### PROJECT version

3

### Extra Labels

/kind documentation

**Comment by camilamacedo86** [comment]
Hi @csantanapr,

Thank you for pointing this out. You're absolutely right. The tutorial is structured with the assumption that readers are progressing step by step and have completed the preceding sections, as seen here: https://book.kubebuilder.io/cronjob-tutorial/main-revisited

However, for the benefit of those who might land directly on this specific page, I believe it would be beneficial to include a "note" or "warning" highlight. This way, readers are informed about the prerequisites and can navigate the tutorial more effectively.

Would you like to work on this one?
WDYT about push a PR to update this doc? 

- The change would be in : https://github.com/kubernetes-sigs/kubebuilder/blob/master/docs/book/src/cronjob-tutorial/running.md
- The suggestion would to be to create a warning note like: https://github.com/kubernetes-sigs/kubebuilder/blob/master/docs/book/src/plugins/deploy-image-plugin-v1-alpha.md?plain=1#L37-L48

**Comment by lowang-bh** [comment]
Hi, @csantanapr and  @camilamacedo86 , I reproduce this error using master branch code with following steps and found the generated code in `main.go` does not check the `ENABLE_WEBHOOKS` env:
1. `make install` to install master kuberbuilder
2. following the [quick start](https://book.kubebuilder.io/quick-start) docs to create a app
3. use `kubebuilder create webhook` to gen a webhook and run `make  manifests; make install` to update
4. run `export ENABLE_WEBHOOKS=false; make run` 

<img width="1134" alt="image" src="https://github.com/kubernetes-sigs/kubebuilder/assets/21003791/48864021-aa69-49b0-b5a6-b8dd07c914b5">

<img width="749" alt="image" src="https://github.com/kubernetes-sigs/kubebuilder/assets/21003791/29279643-26cb-421c-a912-64f8754063f6">
