### ISSUE TITLE
Allow configuring memory and cpu resource requests and limits for generated pod template

### ISSUE THREAD

**Issue by font** [kubernetes-sigs/kubebuilder#356]
The pod template for the generated controller-manager specifies the following default resource requests and limits for CPU and memory:

https://github.com/kubernetes-sigs/kubebuilder/blob/581c0cb64b7e79a49708698ea6f0970edd52a2c6/cmd/kubebuilder/create/config/gen.go#L263-L272

Suggestions:
1. These requests and limits should be configurable when invoking kubebuilder.
2. They should be removed entirely so that default requests and limits via LimitRange or ResourceQuota API objects can be used instead.

**Comment by droot** [comment]
@font This sort of customization is a good use case for using [`kustomize`](https://github.com/kubernetes-sigs/kustomize). In `v1` version of Kubebuilder, we scaffold a default [`kustomization.yaml`](https://github.com/kubernetes-sigs/controller-tools/blob/master/test/config/default/kustomization.yaml) file for the project. We patch the controller manager image using [patch](https://github.com/kubernetes-sigs/controller-tools/blob/master/test/config/default/manager_image_patch.yaml)

You can create a similar patch for customizing the CPU and memory for controller-manager and add it to Kustomization.yaml file.

You may also find [this blogpost](https://testingclouds.wordpress.com/2018/07/20/844/) relevant.

I am closing the issue for now. Feel free to re-open it if you think this doesn't address the use-case.

**Comment by font** [comment]
That would work, thanks @droot!
