### ISSUE TITLE
Documentation for "Watching Externally Managed Resources" No longer matches implementation

### ISSUE THREAD

**Issue by SimonStiil** [kubernetes-sigs/kubebuilder#3583]
### What broke? What's expected?

Seems like there have been a few updates to the controller-runtime that have not been added in the documentation for 
https://kubebuilder.io/reference/watching-resources/externally-managed

This means if you use the examples in the documentation you get compilation issues 
```go
func (r *ConfigDeploymentReconciler) findObjectsForConfigMap(configMap client.Object) []reconcile.Request {
```
Should now be 
```go
func (r *ConfigDeploymentReconciler) findObjectsForConfigMap(ctx context.Context, configMap client.Object) []reconcile.Request {
```

```go
        Watches(
            &source.Kind{Type: &corev1.ConfigMap{}},
            handler.EnqueueRequestsFromMapFunc(r.findObjectsForConfigMap),
            builder.WithPredicates(predicate.ResourceVersionChangedPredicate{}),
        ).
```
Should now be 
```go
        Watches(
            &corev1.ConfigMap{},
            handler.EnqueueRequestsFromMapFunc(r.findObjectsForConfigMap),
            builder.WithPredicates(predicate.ResourceVersionChangedPredicate{}),
        ).
```

### Reproducing this issue

Create new kubebuilder project using 
KubeBuilderVersion:"3.11.1" 
sigs.k8s.io/controller-runtime v0.15.0

try to implement watching externally managed resources using existing documentation
https://kubebuilder.io/reference/watching-resources/externally-managed

### KubeBuilder (CLI) Version

3.11.1

### PROJECT version

3

### Plugin versions

```yaml
- go.kubebuilder.io/v4
```

### Other versions

go version go1.21.0 linux/amd64

sigs.k8s.io/controller-runtime v0.15.0

### Extra Labels

/kind documentation

**Comment by camilamacedo86** [comment]
Hi @SimonStiil,

Please, feel free to push a PR with the fix.
Your help is more than welcome

**Comment by camilamacedo86** [comment]
For who will take this one, please just confirm that the change is required / accurate.

**Comment by ashutosh887** [comment]
Let me take this ahead @camilamacedo86 

/assign

**Comment by camilamacedo86** [comment]
Hi @ashutosh887,

Are you working in this one? If so, please, feel free to ping us if you face any challenge to achieve this one.  If not, please unassigned it from you so others might able to work on it. 

Thank you a lot for all your contributions 🥇 and help in make kubebuilder better for the community.

**Comment by omerxx** [comment]
This is very much needed I was battling with my own code that just worked a few months back

**Comment by ashutosh887** [comment]
@camilamacedo86 @varshaprasad96 
What needs to be done in this please guide a bit!!!
