### ISSUE TITLE
Update Docs around creating a Webhook for Core types

### ISSUE THREAD

**Issue by phenixblue** [kubernetes-sigs/kubebuilder#3604]
### What do you want to happen?

[The Example for creating an Admission Webhook for Core Types](https://book.kubebuilder.io/reference/webhook-for-core-types) seems to be outdated. The usage of controller-runtime 0.15.0 in the go/v4 plugin have removed the `InjectDecoder` method, so the decoder has to be explicitly loaded when the webhook is added to the Manager.

I would like to update the documents to reflect this change.

### Extra Labels

/kind documentation

**Comment by phenixblue** [comment]
I'm happy to do a PR for this if I can get a 👍 from a project maintainer

**Comment by camilamacedo86** [comment]
HI @phenixblue,

Your PR's to contribute with the project are more than welcome. 
Please, feel free to propose changes in the default scaffold and/or docs to address this one.
