### ISSUE TITLE
The logs has been output with [0000] so we should disable the timestamp  

### ISSUE THREAD

**Issue by camilamacedo86** [kubernetes-sigs/kubebuilder#3608]
### What broke? What's expected?

The logs has been output such as:

INFO[0000] Writing kustomize manifests for you to edit... 
INFO[0000] Writing scaffold for you to edit...          
INFO[0000] api/v1alpha1/memcached_webhook.go            
INFO[0000] api/v1alpha1/webhook_suite_test.go           
INFO[0000] Update dependencies:

When we would like to have 

INFO Writing kustomize manifests for you to edit... 
INFO Writing scaffold for you to edit...          
INFO api/v1alpha1/memcached_webhook.go            
INFO api/v1alpha1/webhook_suite_test.go           
INFO Update dependencies:

To achieve this goal we can disable the Timestamp, such as:

```go
logger := logrus.New()
	// Disable timestamps on the default TextFormatter
	logger.SetFormatter(&logrus.TextFormatter{
		DisableTimestamp: true,
	})
```

However, we must to looking for to check if we could not do this change centralised so that we would not need to do the same code across the whole project. 

### KubeBuilder (CLI) Version

master

**Comment by suhail34** [comment]
I would like to take work on this one

**Comment by AryanSharma9917** [comment]
Hey @camilamacedo86, I would like to work on this issue. 
/assign
