### ISSUE TITLE
Gif in the README is outdated

### ISSUE THREAD

**Issue by camilamacedo86** [kubernetes-sigs/kubebuilder#3609]
### What broke? What's expected?

The Gif in the README is outdated. Therefore, this issue is for we record a new gif using the latest release doing exactly the same steps. 

See: https://github.com/kubernetes-sigs/kubebuilder#getting-started

### KubeBuilder (CLI) Version

master

**Comment by ashutosh887** [comment]
I'll do this
Please share the SVG @camilamacedo86

**Comment by camilamacedo86** [comment]
HI @ashutosh887 

That is great news. Not sure if I understand your comment.
See that we have a GIF now: https://github.com/kubernetes-sigs/kubebuilder#getting-started
Therefore, the task would to be to record a new one (updated) and then replace the current one for the new one.

**Comment by ashutosh887** [comment]
Okay I thought I'll get a GIF from community

**Comment by Sajiyah-Salat** [comment]
So what commands can we run in the gif.

**Comment by ashutosh887** [comment]
Yeah that's what I was asking if not available @camilamacedo86

**Comment by camilamacedo86** [comment]
Hi @ashutosh887 and @Sajiyah-Salat,

> @camilamacedo86 So what commands can we run in the gif.
> Yeah that's what I was asking if not available @camilamacedo86

Did you check the GIF that we have today in the README (https://github.com/kubernetes-sigs/kubebuilder/blob/master/docs/gif/kb-demo.v2.0.1.svg)?  

So the idea here would be run exactly the same commands but with the latest version since the layout and etc is no longer the same.

However, if you wish propose for example extend and also add a step at the end to show the plugins I think could be nice. We can for example create an API with the deploy image, example:

kubebuilder create api --group example.com --version v1alpha1 --kind Busybox --image=busybox:1.28 --plugins="deploy-image/v1-alpha" . And show that the code is generate in the controller to deploy and manage the image informed. 

WDYT?
Is that make sense?

**Comment by ashutosh887** [comment]
Yes that makes a sense @camilamacedo86

**Comment by ashutosh887** [comment]
@MaGaroo Which tool did you use to generate SVG/this snippet?

**Comment by MaGaroo** [comment]
> @MaGaroo Which tool did you use to generate SVG/this snippet?

As described in `scripts/demo/README.md`, `asciinema` is used for recording and `svg-term` is used for conversion to svg.
