### ISSUE TITLE
Bump controller-runtime 0.16.2

### ISSUE THREAD

**Issue by camilamacedo86** [kubernetes-sigs/kubebuilder#3621]
### What do you want to happen?

We need update the controller-runtime version used.
See that we do that only for go/v4.

- Update the version in : https://github.com/kubernetes-sigs/kubebuilder/blob/689360500f8c218f69f2aa47aaa26da26b179e16/pkg/plugins/golang/v4/scaffolds/init.go#L34
- Run make generate to update all files 

Push the PR.

**Comment by MaGaroo** [comment]
I'm interested in this issue.
Let me know if you think I can do it.

**Comment by lowang-bh** [comment]
It has been done in PR #3597
