### ISSUE TITLE
Add doc about Operator and CRD scope

### ISSUE THREAD

**Issue by camilamacedo86** [kubernetes-sigs/kubebuilder#3623]
### Context and Motivation

The Kubebuilder docs does not explain the Operator and CRD scope.
Therefore, we have questions like https://github.com/kubernetes-sigs/kubebuilder/discussions/3155

### The goal of the task

The goal of this task is to create those documentations under reference.
See that is well documented in the Operator-SDK documentation:

- Operator Scope: https://sdk.operatorframework.io/docs/building-operators/golang/operator-scope/
- CRD scope: https://sdk.operatorframework.io/docs/building-operators/golang/crds-scope/

We can use the content available there to create a documentation in Kubebulder but we should not link Operator-SDK docs. 

### How to do it:
- Create a PR to add the doc under the section reference
- Update either the summury
- Verify your changes using the doc preview available when you push the PR

### Extra Labels

/kind documentation

**Comment by lowang-bh** [comment]
Hi, @camilamacedo86 , does this issue need to add two docs with contents to explain the scope of operator and CRD? Just follow other references.

**Comment by camilamacedo86** [comment]
Hi @lowang-bh,

2 docs under the reference, one for each case shows great. 
Please, feel free to propose the additional as you see that it will better fit.

**Comment by lowang-bh** [comment]
> Hey @lowang-bh! are you still working on this?

Sorry, have no time recently. I have unassigned.

**Comment by rakshitgondwal** [comment]
Thank you for the update @lowang-bh 
/assign

**Comment by camilamacedo86** [comment]
That is done I am closing
