### ISSUE TITLE
Add doc about finalizers

### ISSUE THREAD

**Issue by camilamacedo86** [kubernetes-sigs/kubebuilder#3624]
### Context and Motivation

The Kubebuilder docs does not explain how and when use finalizers then it is not clear for users. Example: https://github.com/kubernetes-sigs/kubebuilder/discussions/2760

### The goal of the task

The goal of this task is to create those documentations under reference to address this need. As reference we can use the content available in the Operator-SDK documentation:

- We should like the k8s doc: https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/#finalizers
- We should let users know that Deploy Image plugin provide a finalizer and let them check it as example: https://github.com/kubernetes-sigs/kubebuilder/blob/v3.12.0/testdata/project-v4-with-deploy-image/internal/controller/busybox_controller.go#L121-L192

### How to do it:
- Create a PR to add the doc under the section reference
- Update either the summary
- Verify your changes using the doc preview available when you push the PR

### Extra Labels

/kind documentation

**Comment by ashutosh887** [comment]
Working on this 

/assign

**Comment by camilamacedo86** [comment]
Hi @ashutosh887,

Are you working in this one? If so, please, feel free to ping us if you face any challenge to achieve this one.  If not, please unassigned it from you so others might able to work on it. 

Thank you a lot for all your contributions 🥇 and help in make kubebuilder better for the community.

**Comment by BalaadityaPatanjali** [comment]
I'd like to work on this ! @camilamacedo86

**Comment by camilamacedo86** [comment]
Hi @ashutosh887,

I removed the sign since it has been without interactions for a long period. See: https://github.com/kubernetes-sigs/kubebuilder/issues/3624#issuecomment-1809762526

Hi @BalaadityaPatanjali

you might want to try ping here via Slack, but I think your help here will be very welcome.

**Comment by BalaadityaPatanjali** [comment]
@camilamacedo86 I'd love work on this !

**Comment by camilamacedo86** [comment]
The doc was added already 
https://book.kubebuilder.io/reference/using-finalizers
 
we need to shape / review this one. But that was not the goal of this task so I am closing it and we can track another afterwords to improve it accordingly.
