### ISSUE TITLE
Patches for webhooks has been created for any API

### ISSUE THREAD

**Issue by camilamacedo86** [kubernetes-sigs/kubebuilder#3630]
### What broke? What's expected?

Patches for conversion webhook has been created for any API.
See the file: config/crd/kustomization.yaml

We should only have pacthes for APIS when we webhooks for the specific api

### Reproducing this issue

- Create a project and add more than one API
- Now, create a conversion webhook for only one API and not all of them
- Now check the patches for webhooks in config/crd/kustomization.yaml

### KubeBuilder (CLI) Version

master

**Comment by matrus2** [comment]
I would like to take a look.
/assign

**Comment by camilamacedo86** [comment]
Hi @matrus2,

To solve another issue I identify that the solution also close this one.
So, I hope that is fine. The PR to fix it is: https://github.com/kubernetes-sigs/kubebuilder/pull/3647

**Comment by camilamacedo86** [comment]
@matrus2 

I could sort this one as part of another fix, I hope that you do not mind see; https://github.com/kubernetes-sigs/kubebuilder/pull/3647
