### ISSUE TITLE
🐛 Cannot show help for external plugins

### ISSUE THREAD

**Issue by tomasaschan** [kubernetes-sigs/kubebuilder#3644]
### What broke? What's expected?

If I run `kubebuilder --help`, it [shows me this message](https://github.com/kubernetes-sigs/kubebuilder/blob/master/pkg/cli/root.go#L69-L71)
```
For more specific help for the init command of a certain plugins and project version
configuration please run:
    kubebuilder init --help --plugins=<PLUGIN KEYS> [--project-version=<PROJECT VERSION>]
```
However, if I run that and set `--plugins` to an external plugin I'm building, it first logs `INFO[0000] Adding external plugin: myplugin/v1` but then doesn't seem to acknowledge the fact that I've set `--plugins` at all:
```
λ kubebuilder init --help --plugins myplugin/v1
INFO[0000] Adding external plugin: myplugin 
Initialize a new project.

For further help about a specific plugin, set --plugins.

Usage:
  kubebuilder init [flags]

Examples:
  # Help for initializing a project with version "2"
  kubebuilder init --project-version="2" -h

  # Help for initializing a project with version "3"
  kubebuilder init --project-version="3" -h

Flags:
  -h, --help                     help for init
      --project-version string   project version (default "3")

Global Flags:
      --plugins strings   plugin keys to be used for this subcommand execution
```
However, _something_ is different, because if I just run `kubebuilder init --help` without setting `--plugins`, I get different output.

I also observe with my plugin that it is not actually invoked for the help call; if I write its input to a file, that file is never created, and if I panic as the first thing that happens upon invoking the plugin, `kubebuilder` does not seem to notice.

I'm not sure if what needs to change is the help text for how to invoke help for a plugin, or the mechanisms by which plugin help is invoked, but currently they don't match - and that is really confusing...

### KubeBuilder (CLI) Version

Version: main.version{KubeBuilderVersion:"0.0.0-SNAPSHOT-fc59b56", KubernetesVendor:"1.23.5", GitCommit:"fc59b569ced3a2942b87ce20db39043be1bf8352", BuildDate:"2022-05-18T10:55:28Z", GoOs:"linux", GoArch:"amd64"}

### Extra Labels

/kind documentation

**Comment by camilamacedo86** [comment]
Hi @Eileen-Yu, @rashansmith @everettraven 

Could you please give a hand one this one?

**Comment by Eileen-Yu** [comment]
Hi @tomasaschan

The `--help` flag is an optional subcommand to display info/example specially for the external plugin you built.

You can choose to implement this function by dealing with `pluginRequest.command == metadata` and setting corresponding `pluginResponse.metadata`

Here's the go example:
https://github.com/kubernetes-sigs/kubebuilder/blob/d2fa79c922614cf0edd02f96b4305f1e1bac89ca/docs/book/src/simple-external-plugin-tutorial/testdata/sampleexternalplugin/v1/cmd/cmd.go#L82-L83
and
https://github.com/kubernetes-sigs/kubebuilder/blob/master/docs/book/src/simple-external-plugin-tutorial/testdata/sampleexternalplugin/v1/cmd/metadata.go#L54-L67


You may also refer to [kubebuilder book](https://book.kubebuilder.io/plugins/external-plugins) for tutorial and examples in other languages.

**Comment by camilamacedo86** [comment]
Hi @tomasaschan,

I am closing this one as sorted out based in the comment:  https://github.com/kubernetes-sigs/kubebuilder/issues/3644#issuecomment-1743706850

If you face issues following this guidance please open an issue describing what you are doing, what you expected to see and what you see instead. 

Thank you a lot for your collaboration and understanding.
