### ISSUE TITLE
Reference to deprecated MultiNamespacedCacheBuilder in docs

### ISSUE THREAD

**Issue by buraksekili** [kubernetes-sigs/kubebuilder#3662]
### What broke? What's expected?

In the Kubebuilder documentation (https://book.kubebuilder.io/cronjob-tutorial/empty-main.html#every-journey-needs-a-start-every-program-needs-a-main), there is a reference to the deprecated `cache.MultiNamespacedCacheBuilder`. However, as of the controller-runtime v0.15.0 release (refer to https://github.com/kubernetes-sigs/controller-runtime/pull/2157 and release notes: https://github.com/kubernetes-sigs/controller-runtime/releases/tag/v0.15.0), this function is deprecated.

The documentation needs an update to replace the deprecated usage with the new refactored `cache.Options` for configuring namespaces in caches.

### KubeBuilder (CLI) Version

3.12.0

### Extra Labels

/kind documentation

**Comment by camilamacedo86** [comment]
HI @buraksekili,

Would you like to contribute with this one pushing a PR for us to update the docs?

**Comment by buraksekili** [comment]
Thank you @camilamacedo86, I raised #3664.
