### ISSUE TITLE
Document CRD design for the usecase of having mandatory fields within an optional struct field in the CRD spec.

### ISSUE THREAD

**Issue by kgoutham93** [kubernetes-sigs/kubebuilder#3671]
### What do you want to happen?

Currently, Kubebuilder docs does not capture the common scenario of having mandatory (required) fields within an optional struct  field in the CRD spec.

Consider the following silly example, I want `ShippingAddress` to be an _optional_ spec field, but if user provides a `ShippingAddress` then I want them to mandatorily speicify `AddressType`.
```
type CustomerSpec struct {
	// +kubebuilder:validation:Required
       CustomerId string `json:"customerId"`

	// +kubebuilder:validation:Optional
	ShippingAddress Address `json:"shippingAddress,omitempty"`
}

type Address struct {
	// +kubebuilder:validation:Optional
	AddressLine string `json:"address,omitempty"`

	// +kubebuilder:validation:Required
	// +kubebuilder:validation:Enum=HOME;OFFICE
	AddressType AddressType `json:"addressType"`
}

type AddressType string

const (
	AddressTypeHome   AddressType = "HOME"
	AddressTypeOffice AddressType = "OFFICE"
)
```
[Futher discussion on Slack](https://kubernetes.slack.com/archives/CAR30FCJZ/p1697563033985809)

As it turns out, we can achieve the above requirement by changing `ShippingAddress` to a pointer type. 

### Not so silly example

`VirtualHost`  is optional in [`HttpProxySpec`](https://github.com/projectcontour/contour/blob/6917d85ce41f3050107994c06e6bb5b7039c99ed/apis/projectcontour/v1/httpproxy.go#L26) in Coutour project. But `Fqdn` ([a field in VirtualHost](https://github.com/projectcontour/contour/blob/6917d85ce41f3050107994c06e6bb5b7039c99ed/apis/projectcontour/v1/httpproxy.go#L301)) is mandatory and should adhere to a specific regex pattern. 

### Extra Labels

/kind documentation

**Comment by kgoutham93** [comment]
Working on this

/assign

**Comment by camilamacedo86** [comment]
Please feel free to open a PR with you suggestion.
Your help is more than welcome 🎉
