### ISSUE TITLE
Watching Externally Managed Resources: source.Kind is a function but it's used as a type in example in kubebuilder book

### ISSUE THREAD

**Issue by hmoazzem** [kubernetes-sigs/kubebuilder#3698]
### What broke? What's expected?

In https://github.com/kubernetes-sigs/controller-runtime/blob/2154ffbc22e26ffd8c3b713927f0df2fa40841f2/pkg/source/source.go#L61, `Kind` is a function but it's used as a type in  https://github.com/kubernetes-sigs/kubebuilder/blob/26ee6711f7cd126d3490f1dfb8e2e648ddc60fac/docs/book/src/reference/watching-resources/testdata/external-indexed-field/controller.go#L171

### KubeBuilder (CLI) Version

3.13.0

### PROJECT version

3

### Plugin versions

```yaml
go.kubebuilder.io/v4
```

### Other versions

go1.21.0 darwin/arm64
sigs.k8s.io/controller-runtime v0.16.3

**Comment by camilamacedo86** [comment]
What the example is trying to the is the same of: https://github.com/kubernetes-sigs/kubebuilder/blob/26ee6711f7cd126d3490f1dfb8e2e648ddc60fac/docs/book/src/reference/watching-resources/testdata/external-indexed-field/controller.go#L171 OR OF https://github.com/kubernetes-sigs/controller-runtime/blob/main/example_test.go#L123 .

**Comment by hmoazzem** [comment]
This https://github.com/kubernetes-sigs/controller-runtime/blob/main/example_test.go#L123 is what I was trying to achieve, ie, restart workload depending on mounted Secret or ConfigMap change. This particular issue can be closed, except the fact that apparently example in kubebuilder book (https://master.book.kubebuilder.io/reference/watching-resources/externally-managed.html) is outdated for current controller-runtime version (v0.16.3).

**Comment by sdemura** [comment]
Why was this issue closed as completed when there's clearly a documentation bug?

**Comment by hmoazzem** [comment]
@sdemura if i remember i got my use-case resolved (workaround) using the links provided by Camila; I maybe felt the bug wasn’t issue-worthy. Feel free to re-open if you think useful. I'd be happy to lookup and submit a fix.

**Comment by camilamacedo86** [comment]
Hi @hmoazzem 

This doc about watch were updated recently. See: https://master.book.kubebuilder.io/reference/watching-resources
However, if you see something is wrong, please open an issue so we try to fix it.

**Comment by jokuniew** [comment]
I believe the issue in doc is still there @camilamacedo86 

![Image](https://github.com/user-attachments/assets/2deb6e8e-dbc5-4237-9cab-7d0011c65eb6)
https://github.com/kubernetes-sigs/kubebuilder/blob/master/docs/book/src/reference/watching-resources/secondary-resources-not-owned.md?plain=1#L42

It's my first take with watching, so I'm not sure how it should be fixed (yet)
