### ISSUE TITLE
knative example

### ISSUE THREAD

**Issue by nrshrivatsan** [kubernetes-sigs/kubebuilder#370]
- Please provide a knative example for integrating kube-builder CI+CD.

**Comment by droot** [comment]
@nrshrivatsan Can you elaborate more on what should the example do ?

**Comment by nrshrivatsan** [comment]
# Background
- CI + CD platforms are in plenty
- Jenkins, Travis , Circle CI and many more
- The tool chain for CI + CD is a simple [DAG](https://en.wikipedia.org/wiki/Directed_acyclic_graph) of processes Pipe-ing one after the other

# Proposal
- Kubernetes DAG jobs via kubebuilder - pipeline SHOULD become AND be the Cloud-Native way to build
- An Point-of-Refernece example of an End-to-End build  + delivery pipeline for an Open Source Project could be that stepping stone toward a KNative Pipeline.

Your thoughts @droot ?

**Comment by nrshrivatsan** [comment]
@droot When you get time, kindly take a look at the above comment https://github.com/kubernetes-sigs/kubebuilder/issues/370#issuecomment-419667580

**Comment by DirectXMan12** [comment]
@nrshrivatsan can you propose something a bit more concrete?  As far as I can tell, you're either suggesting that a) we have an example of how to build and run CI on a kubebuilder-generated project with knative, or b) generate knative build steps using kubebuilder.  I could be misunderstanding you though -- I'm having trouble parsing what you're suggesting through the dogmatic capitalization.
