### ISSUE TITLE
Avoid usage of newly deprecated webhook.Validator and webhook.Defaulter interfaces

### ISSUE THREAD

**Issue by nathanperkins** [kubernetes-sigs/kubebuilder#3721]
### What do you want to happen?

In [this controller-runtime issue](https://github.com/kubernetes-sigs/controller-runtime/issues/2596), it was decided to deprecate the webhook.Validator and webhook.Defaulter interfaces, due to issues they cause with project upgrades by requiring controller-runtime import in API packages. Those functions are planned to be removed later.

We should update the Kubebuilder generated code and the docs to use admission.CustomValidator and admission.CustomDefaulter instead.

### Jan 13th edit:

We also need to implement this interface outside of the API packages so that the API packages are not coupled with controller-runtime versions (see the issue above for context). The docs should be updated to warn the reader about the dangers of implementing this on the API types.

**Comment by nathanperkins** [comment]
@alvaroaleman thank you for moving this! I thought I made it in kubebuilder but I must have mixed my tabs up.

**Comment by camilamacedo86** [comment]
Thank you for raising this one. 
It is very helpful. 

It would be amazing if we could track issues to fix those breaking changes and desecrations in controller-runtime always. 
Thank you for moving it @alvaroaleman !!!

**Comment by camilamacedo86** [comment]
**What is required to do here:**

1  - Replace `Defaulter` with  `CustomDefaulter` - https://github.com/search?q=repo%3Akubernetes-sigs%2Fkubebuilder%20%20Defaulter&type=code
2 - `Validator` with  `CustomValidator` - https://github.com/search?q=repo%3Akubernetes-sigs%2Fkubebuilder++Validator&type=code

The change must be done for the docs/examples and default scaffold for the go/v4 plugin only.
We also need to ensure that the example/tutorial works well with the new example and perform all required caveats if necessary to make it work with the interface.

**Comment by jonas-jonas** [comment]
Hi, would love to provide a PR for this, if it's not yet taken. Looking at your comment @camilamacedo86 and the code base, it seems like a pretty straight forward change.

However, there haven't been any changes to the generated files since last year, meaning all generated files will be touched (2023 -> 2024). Would be happy to provide a separate PR just updating the timestamps if that better suits the workflow here. Let me know what you prefer.

**Comment by camilamacedo86** [comment]
Hi @jonas-jonas,

> Would be happy to provide a separate PR just updating the timestamps

That is a good point. Please feel free just to run make, generate and push a PR if that is not done yet and ping me out. I am more than happy to approve this one. 

Also, feel free to push the PR for remove the deprecation and ping me out as well.

**Comment by nathanperkins** [comment]
Sorry I didn't specify in the original post. We also need to implement the interface on some type outside of `apis/` and update the docs to suggest as such. The purpose of this change is to reduce coupling between the APIs package and controller-runtime code.

**Comment by nathanperkins** [comment]
@jonas-jonas, please check the comment above. I will add some comments to the PR as well.

**Comment by nathanperkins** [comment]
@camilamacedo86 we probably need somebody from the kubebuilder team to let @jonas-jonas know what is the appropriate place to implement this interface so that it is not part of the API packages which are commonly imported by other projects.

**Comment by camilamacedo86** [comment]
HI @nathanperkins, 

Thank you for add your input, please see my comment: https://github.com/kubernetes-sigs/controller-runtime/issues/2596#issuecomment-1890900992

> The purpose of this change is to reduce coupling between the API package and controller-runtime code.

I am not sure if I go along with the purpose here since each API should have its own webhook.
How can you have a generic webhook interface implementation that is decoupled from the API Kind? 
Did I misunderstood something here or are you proposing that we have a pkg/webhook?

**Comment by camilamacedo86** [comment]
Hi @nathanperkins,

> @camilamacedo86, we probably need somebody from the kubebuilder team to let @jonas-jonas know the appropriate place to implement this interface so that it is not part of the API packages commonly imported by other projects.

I understand that we have two issues/tasks here.

- a) No longer scaffolding the deprecated code. (goal of this task) 
- b) You want to decouple the webhooks from the API to allow you to import API/ dir from one project to another. Therefore, you are suggesting changing the layout, for we no longer have the webhooks scaffolded under the API/ directory.  (https://github.com/kubernetes-sigs/kubebuilder/issues/3215 <- another task)

**Unless I misunderstand something, we do not need to change the layout to no longer use deprecated.**  
Therefore, the second change/RFE (b) is a breaking change tracked in https://github.com/kubernetes-sigs/kubebuilder/issues/3215 and can be made as a follow-up. So, let's discuss it in another issue. Is that OK? 

 c/c @varshaprasad96 ^

**Comment by nathanperkins** [comment]
>Unless I misunderstand something, we do not need to change the layout to no longer use deprecated.
Therefore, the second change/RFE (b) is a breaking change tracked in https://github.com/kubernetes-sigs/kubebuilder/issues/3215 and can be made as a follow-up. So, let's discuss it in another issue. Is that OK?

Totally reasonable, in that case the PR is fine from my perspective!

**Comment by troy0820** [comment]
The PR for controller-runtime to remove the deprecated interfaces is https://github.com/kubernetes-sigs/controller-runtime/pull/2877.  Linking to this issue if more discussion is necessary.
