### ISSUE TITLE
Getting started guide various small typos/fixes

### ISSUE THREAD

**Issue by nemethloci** [kubernetes-sigs/kubebuilder#3725]
### What broke? What's expected?

The getting started guide can't be followed as is due to a couple of small issues:

https://book.kubebuilder.io/getting-started#create-the-memcached-api-crd
  - group should be 'cache' not example.com
  
https://book.kubebuilder.io/getting-started#define-your-api
  - make manifests it to be used instead of make generate

https://book.kubebuilder.io/getting-started#in-the-context-of-our-example
  - testdata/project-v4-with-deploy-image/internal/controller/memcached_controller.go -> $GOPATH/memcached-operator/internal/controller/memcached_controller.go
 
https://book.kubebuilder.io/getting-started#setting-the-rbac-permissions
  - make manifests it to be used instead of make generate

Will submit a merge request for this.

### Reproducing this issue

Try to run the getting started sample.

### KubeBuilder (CLI) Version

3.13.0

**Comment by nemethloci** [comment]
Reference to pull request: https://github.com/kubernetes-sigs/kubebuilder/pull/3726

**Comment by camilamacedo86** [comment]
Hi @nemethloci 

thank you for raising this one. 
Please, see the comments in the PR https://github.com/kubernetes-sigs/kubebuilder/pull/3726

**Comment by camilamacedo86** [comment]
Hi @nemethloci 

Thank you for raising this one.
Some changes were addressed in the latest version.

Please, feel free to check and if you see anything else that should be changed please open a new issue with the references. Also, your help is more than welcome.
