### ISSUE TITLE
Development: automate squash commits

### ISSUE THREAD

**Issue by mateusoliveira43** [kubernetes-sigs/kubebuilder#3728]
I noticed the project follows a standard of squashing the commits prior to merge (which is fine). The problem is that this process is manual. I think this creates 2 problems:
- One more step for developers
- Harder to review PRs (I can not easily see what a developer did after I suggested a change, for example, by looking at his/her next commit, as the commit is now grouped with all other changes from the PR)

I believe this can achieved with the repository settings.

Example of what I do in personal projects
![Screenshot from 2024-01-15 10-15-00](https://github.com/kubernetes-sigs/kubebuilder/assets/66965232/56fb97b4-fc6e-40dd-901f-66df6f12396b)

**Comment by camilamacedo86** [comment]
Hi @mateusoliveira43,

I wanted to share some insights regarding the project configuration and our adherence to the practices established by Kubernetes. You can find detailed guidelines at [Kubernetes Contributor Guide](https://www.kubernetes.dev/docs/guide/contributing/).

**To maintain consistency and efficiency in our project, we follow these key practices:**

- **Single Commit per PR:** Each Pull Request (PR) should contain only one commit. This approach simplifies tracking changes and makes the history more readable.
- **One Issue per PR:** Each PR should address a single specific issue or need. This helps in streamlining our workflow and makes it easier to identify and resolve problems.

These practices not only enhance our git history for better clarity but also facilitate easier reverting of changes when necessary, and reduce the likelihood of conflicts.

> PS.: We have this configuration suggested by you already but the git history does not endup in the same way. You can check it by comparing / reviwing the commits with gItHub UI by looking some case scenario where 2 commits or more were merged when should not. 

Additionally, I believe it would be beneficial to include this information in our contribution guidelines. The relevant section of the [Kubebuilder CONTRIBUTING.md](https://github.com/kubernetes-sigs/kubebuilder/blob/master/CONTRIBUTING.md) file seems like an appropriate place for these details.

**Comment by camilamacedo86** [comment]
PR: https://github.com/kubernetes-sigs/kubebuilder/pull/3732

In so cases, might be acceptable an exception of this rule. But that is analysed case by case.

**Comment by mateusoliveira43** [comment]
Checked Kubernetes Contributor Guide, and they have a command (`/label tide/merge-method-squash`) to avoid doing it manually. Reference:   https://www.kubernetes.dev/docs/contributor-cheatsheet/#squashing-commits

Do you know if the bots are the same?

If so, maybe it has a configuration that always squash the commits for us
