### ISSUE TITLE
Switch book publishing to GitHub pages

### ISSUE THREAD

**Issue by DirectXMan12** [kubernetes-sigs/kubebuilder#373]
We should switch the book publishing to GitHub pages to make it a bit easier for maintainers to administer.

Addtionally, we should consider the following:
- Netlify for previews
- Travis to publish a "book based on latest master" in addition a manually published "stable" book

**Comment by droot** [comment]
We have moved book to Netlify which supports PR previews and also deploys master on every commit. So closing this issue.
