### ISSUE TITLE
Support for IBM Z (s390x architecture)

### ISSUE THREAD

**Issue by ShivangGoswami** [kubernetes-sigs/kubebuilder#3740]
### What do you want to happen?

kubebuilder project is available for IBM power(ppc64le) but not on IBM Z(s390x).operators are available on both platform and there is a need for kubebuilder project on s390x as well

**Comment by camilamacedo86** [comment]
All latest is available for it now, and in the next release we should have the Kubebuilder CLI itself. (https://github.com/kubernetes-sigs/kubebuilder/issues/2298#issuecomment-1912461019)

So, we can close this one. 

Thank you for raising it and for your help.
