### ISSUE TITLE
Document example/usage of status subresource

### ISSUE THREAD

**Issue by droot** [kubernetes-sigs/kubebuilder#378]
Add a section under `beyond basic` in kubebuilder book describing the following:

- How to annotate types to generate status subresource section in CRD definition
- How to use method from `client` pkg for updating the status subresource. Preferably using an example code.

**Comment by droot** [comment]
Book has a section on this now https://book.kubebuilder.io/basics/status_subresource.html so closing this.

**Comment by vhosakot** [comment]
https://book.kubebuilder.io/basics/status_subresource.html does not exist anymore, use https://book-v1.book.kubebuilder.io/basics/status_subresource.html instead.
