### ISSUE TITLE
Document how to use finalizers with examples

### ISSUE THREAD

**Issue by droot** [kubernetes-sigs/kubebuilder#379]
Add a section under `Beyond basics` in kubebuilder book describing details of `finalizers` and how to use them with example code. 

Also investigate if we can do something during `scaffolding` steps and includes comments to guide users about it.

**Comment by droot** [comment]
We have a section on [`using finalizers`](https://book.kubebuilder.io/beyond_basics/using_finalizers.html) , so closing this.

**Comment by gordonbondon** [comment]
This link now goes to 404 and I was not able to find this info in repo. Any idea where I find this info?

**Comment by gordonbondon** [comment]
For anyone like me still looking for this doc, looks like it was deleted during migration to new gitbook for v2. Here is the last version of finalizer doc https://github.com/kubernetes-sigs/kubebuilder/blob/e46e06eb12dab4c83ad54f27a02344a1e70857fe/docs/book/beyond_basics/using_finalizers.md

**Comment by DirectXMan12** [comment]
That should still exist in the v1 book: https://book-v1.book.kubebuilder.io/beyond_basics/using_finalizers.html.  We're working on adding it to the next version of the book -- in the mean time it's a help-wanted.

/help-wanted
