### ISSUE TITLE
Kubebuilder should uses controller-runtime logging lib instead of log

### ISSUE THREAD

**Issue by mengqiy** [kubernetes-sigs/kubebuilder#380]
Kubebuilder should generate project that uses logging library in controller-runtime instead of golang built-it `log` library.
This requires changes to the scaffolding code in `controller-tools`. For example, https://github.com/kubernetes-sigs/controller-tools/blob/110fef43ab12deecdf7b55c0977d58f824075b39/pkg/scaffold/manager/cmd.go#L46

**Comment by mengqiy** [comment]
cc: @DirectXMan12 @droot

**Comment by DirectXMan12** [comment]
just noticed this the other day.  definitely :+1: from me.

**Comment by interma** [comment]
I will take this, thanks for code review.
