### ISSUE TITLE
Error to scaffold conversion webhooks

### ISSUE THREAD

**Issue by camilamacedo86** [kubernetes-sigs/kubebuilder#3825]
### What broke? What's expected?

By running the following commands we will face an issue to generate the manifests.
I would expected the scaffolds be done accurately and no issue be faced

```
  kubebuilder init --plugins="go/v4" --domain=tutorial.kubebuilder.io --project-version=3 --repo=tutorial.kubebuilder.io/project --license apache2 --owner "The Kubernetes authors"
  kubebuilder create api --group batch --version v1 --kind CronJob --resource --controller --make=false
  kubebuilder create webhook --group batch --version v1 --kind CronJob --defaulting --programmatic-validation
  kubebuilder create webhook --group batch --version v1 --kind CronJob --conversion --force
  kubebuilder create api --group batch --version v2 --kind CronJob --resource=true --controller=false
  kubebuilder create webhook --group batch --version v2 --kind CronJob --defaulting --programmatic-validation
  kubebuilder create webhook --group batch --version v2 --kind CronJob --conversion --force
  go mod tidy
  make
```

### Reproducing this issue

Please run the commands provided above. To solve this task, analyze the results and determine the ideal scaffold needed for a fix. Note that resolving this bug involves investigating and understanding the correct approach to working with webhook conversions.

Ask for help in kubebuilder and controller-runtime channels.
Also, ask for review in both channels when you be able to provide a solution

### KubeBuilder (CLI) Version

master

### PROJECT version

3

### Plugin versions

```yaml
go/v4
```

### Extra Labels

/kind regression

**Comment by Kavinjsir** [comment]
From my local reproducing, the error is:
```
INFO Running make:
$ make generate
/Users/tonyjin/pro/tmp/kb/bin/controller-gen-v0.14.0 object:headerFile="hack/boilerplate.go.txt" paths="./..."
Next: implement your new Webhook and generate the manifests with:
$ make manifests
/Users/tonyjin/pro/tmp/kb/bin/controller-gen-v0.14.0 rbac:roleName=manager-role crd webhook paths="./..." output:crd:artifacts:config=config/crd/bases
tutorial.kubebuilder.io/project/api/v1:-: CRD for CronJob.batch.tutorial.kubebuilder.io has no storage version
Error: not all generators ran successfully
run `controller-gen rbac:roleName=manager-role crd webhook paths=./... output:crd:artifacts:config=config/crd/bases -w` to see all available markers, or `controller-gen rbac:roleName=manager-role crd webhook paths=./... output:crd:artifacts:config=config/crd/bases -h` for usage
make: *** [manifests] Error 1
```

I think it is a similar issue to:
https://github.com/kubernetes-sigs/kubebuilder/issues/1196

So, when following https://book.kubebuilder.io/multiversion-tutorial/api-changes.html#storage-versions, adding `//+kubebuilder:storageversion` can help:
<img width="1216" alt="Screenshot 2024-03-31 at 9 13 42 PM" src="https://github.com/kubernetes-sigs/kubebuilder/assets/18136486/ca8cc67e-7b19-4549-b84f-08c4026527d1">

**Comment by camilamacedo86** [comment]
This are the steps to build our tutorial https://github.com/kubernetes-sigs/kubebuilder/tree/master/docs/book/src/multiversion-tutorial sample.

After add the store it still failing in the e2e test regards the tests added for the webhook.
So, here in this task we need to
- Find the solution and fix it in the scaffolds
- Manually update the tutorial by running the script https://github.com/kubernetes-sigs/kubebuilder/blob/master/docs/book/src/multiversion-tutorial/testdata/generate_multiversion.sh (sadly it still not done with the make generate which is the last step that we need to close https://github.com/kubernetes-sigs/kubebuilder/issues/2510) and then compare master branch with our changes to manually add on top the docs info and code implementation of examples
- Then, push the PR and ensure that it will pass in all tests. See that we have e2e tests to validate the book samples with basic stuff and that fails. So, we need also address any required change in the sample and/or scaffold to ensure that all works fine and pass in the CI tests. 

It could be a good first issue for someone that would like to spend so effort and get something that is not so trivial and requires investigation.

Help here is very welcome !!!!

**Comment by camilamacedo86** [comment]
Hi @Kavinjsir 

You are 100% . It is the same: https://github.com/kubernetes-sigs/kubebuilder/issues/1196.

The problem that I was facing was with the default tests scaffold for the the controller . It was missing declare the resource properly. See; https://github.com/kubernetes-sigs/kubebuilder/actions/runs/8844368662/job/24286141139?pr=3875

I could fix this one, but the tests for the controller still failing
I will raise I new issue with a better description
We need to implement the tests for the controller to ensure that the reconciliation of the sample is accurate.
