### ISSUE TITLE
`make deploy` is broken due to kustomize dropped support for glob

### ISSUE THREAD

**Issue by mengqiy** [kubernetes-sigs/kubebuilder#385]
Currently the generated `kustomization.yaml` looks like:
```
# Adds namespace to all resources.
namespace: {{.Prefix}}-system

# Value of this field is prepended to the
# names of all resources, e.g. a deployment named
# "wordpress" becomes "alices-wordpress".
# Note that it should also match with the prefix (text before '-') of the namespace
# field above.
namePrefix: {{.Prefix}}-

# Labels to add to all resources and selectors.
#commonLabels:
#  someName: someValue

# Each entry in this list must resolve to an existing
# resource definition in YAML.  These are the resource
# files that kustomize reads, modifies and emits as a
# YAML string, with resources separated by document
# markers ("---").
resources:
- ../rbac/*.yaml
- ../manager/*.yaml

patches:
- manager_image_patch.yaml
```
It won't work with the latest `kustomize` (v1.0.7).

A workaround is that manually change
```
- ../rbac/*.yaml
- ../manager/*.yaml
```
to
```
- ../rbac/rbac_role.yaml
- ../rbac/rbac_role_binding.yaml
- ../manager/manager.yaml
```

The fix will be in next Monday and we will do a new kubebuilder release.

**Comment by Liujingfang1** [comment]
Glob support was added in Kustomize 1.0.3 and removed in version 1.0.6. The reason of removing this support is docuemnted https://github.com/kubernetes-sigs/kustomize/blob/master/docs/eschewedFeatures.md#globs-in-kustomization-files

If your kustomize version is 1.0.3, 1.0.4 or 1.0.5, you should be fine. If you want to update to any version later than 1.0.6, make sure to change /*.yaml to the full list of resource files.

**Comment by mengqiy** [comment]
kubebuilder v1.0.4 has been released with the fix.
