### ISSUE TITLE
cannot be handled as a CronJob unknown field 

### ISSUE THREAD

**Issue by doing-cr7** [kubernetes-sigs/kubebuilder#3858]
i flowling Mutil-Version API post step by step 

 

✗ kubectl create -f config/samples/batch_v2_cronjob.yaml 
Error from server (BadRequest): error when creating "config/samples/batch_v2_cronjob.yaml": CronJob in version "v2" cannot be handled as a CronJob: strict decoding error: unknown field "spec.schedule.concurrencyPolicy", unknown field "spec.schedule.jobTemplate", unknown field "spec.schedule.startingDeadlineSeconds"

**Comment by camilamacedo86** [comment]
We need someone following up the tutorials to ensure that all is fine.
but according to the description you might did not run `make manifests` to generate the manifests and apply the CRDs with the fields on the cluster.

**Comment by camilamacedo86** [comment]
It seems that the CRD was not applied.
So, I am closing this one.
However, if you see that it should be re-opened please feel free to do so.
