### ISSUE TITLE
Remove the kubebuilder v0 support after deprecating it since v1.0.0

### ISSUE THREAD

**Issue by mengqiy** [kubernetes-sigs/kubebuilder#386]

**Comment by mengqiy** [comment]
cc @droot @Liujingfang1

**Comment by mengqiy** [comment]
#250 is a bug in v0. It will be gone if we remove v0 support.

**Comment by fanzhangio** [comment]
It's better to add the deprecation announcement in Gitbook and README as well.

**Comment by droot** [comment]
`v0` will be no longer supported with the new version `v1.0.5`, support already dropped on master, so closing it.
