### ISSUE TITLE
Support +enum tags in k8s APIs

### ISSUE THREAD

**Issue by alculquicondor** [kubernetes-sigs/kubebuilder#3861]
### What do you want to happen?

Kubernetes APIs include an `enum` tag such as this one:

https://github.com/kubernetes/kubernetes/blob/be4b7176dc131ea842cab6882cd4a06dbfeed12a/staging/src/k8s.io/api/core/v1/types.go#L3506-L3507

which translates to the following OpenAPIv3:

```
          "effect": {
            "description": "Required. The effect of the taint on pods that do not tolerate the taint. Valid effects are NoSchedule, PreferNoSc>
            "type": "string",
            "default": "",
            "enum": [
              "NoExecute",
              "NoSchedule",
              "PreferNoSchedule"
            ]
```

However, kubebuilder doesn't recognize them when using these types in another project.

Example in Kueue, for the code in https://github.com/kubernetes-sigs/kueue/blob/34bfbe0f359b8439b737f07c3f3e5da92c7d0d67/apis/kueue/v1beta1/resourceflavor_types.go#L68
The rendered CRD lacks the enum information:
https://github.com/kubernetes-sigs/kueue/blob/34bfbe0f359b8439b737f07c3f3e5da92c7d0d67/config/components/crd/bases/kueue.x-k8s.io_resourceflavors.yaml#L87-L89

**Comment by camilamacedo86** [comment]
HI @alculquicondor 

This one should be raised against `controller-tools`. See: https://github.com/kubernetes-sigs/controller-tools

Can you please transfer this issue to their repo? 

Thank you for your attention and time.

**Comment by tenzen-y** [comment]
I transferred this issue to https://github.com/kubernetes-sigs/controller-tools/issues/933 on behalf of the kueue maintainers.

**Comment by camilamacedo86** [comment]
HI @tenzen-y 

The CRDs are generated by controller-tools not Kubebuilder.
I do not know who ware `kueue` maintainers
Is that a project?

**Comment by tenzen-y** [comment]
> HI @tenzen-y
> 
> The CRDs are generated by controller-tools not Kubebuilder. I do not know who ware `kueue` maintainers What is `kueue `

If you are confused, sorry for that. I just wanted to say that I transferred this issue instead of Aldo.
