### ISSUE TITLE
Always adding `crd-install` annotation for CRD resources

### ISSUE THREAD

**Issue by gyliu513** [kubernetes-sigs/kubebuilder#387]
Helm 2.10 introduced a new hook as described here https://docs.helm.sh/developing_charts/#defining-a-crd-with-the-crd-install-hook , and this can make sure all CRDs can be installed first before install other resources and make chart CRD management more easy.

Most people are now trying to use helm to install applications, it is better to enable all of the CRDs generated by Kubebuilder include the annotation for `crd-install`. This can make sure if the CRDs are included in helm chart, then those CRDs can be created first before other resources.

```
annotations:
  "helm.sh/hook": crd-install
```

/cc @pmorie

**Comment by gyliu513** [comment]
Related with Federation V2 helm chart https://github.com/kubernetes-sigs/federation-v2/pull/245

**Comment by fanzhangio** [comment]
Thanks for your feedback. After editing type scheme, user has to run `make` for generating manifest. CRD yaml files can be found in `config/crds`, user can modify the yaml files as wish, including above annotations for helm. 
I think it could not be necessary to force add helm annotations for all crds since there are still some use-case do not apply it.

**Comment by gyliu513** [comment]
@fanzhangio I would suggest we add this annotation, because:

1) It has no side effect to the CRD resources.
2) It can help facilitate the translation of YAML template to helm chart as helm chart is becoming the installation standard for Kubernetes resources.
3) It is not convenient for user to update the kubebuilder generated YAML template, as the user need to update the YAML template each time when the YAML template was generated.

Comments? Thanks.

**Comment by fanzhangio** [comment]
Looks good to me. It should be good to consider supporting helm chart in kubebuilder. I think kubebuilder could have a flag in `controller-gen` for generating this stuff. 
What do you think? @droot

**Comment by droot** [comment]
@gyliu513 I was thinking more about it and realized that its a good usecase for using [`kustomize`](https://github.com/kubernetes-sigs/kustomize) for adding that annotation to the generated CRD. 
Newer version of Kubebuilder generated default kustomization which a project owner can tweak to this use case. Let me know if you have any questions.

**Comment by gyliu513** [comment]
@droot so how to add this annotation to the CRD? Any example command you can share with me with `kubebuilder`? How `kubebuilder` use `kustomize` to customize those CRD? Thanks.
