### ISSUE TITLE
"kubebuilder create config" do not support only create sts/deployment

### ISSUE THREAD

**Issue by gyliu513** [kubernetes-sigs/kubebuilder#388]
Look at the help of `kubebuilder create config`:

```
root@gyliu-dev1:~/go/src/github.com/kubernetes-sigs/federation-v2# kubebuilder create config --hel
Error: unknown flag: --hel
Usage:
  kubebuilder create config [flags]

Examples:
# Generate config to install controller-manager and CRDs into a cluster
kubebuilder create config --controller-image myimage:v1 --name myextensionname

# Generate config to install only CRDs
kubebuilder create config --crds

# Generate config to install controller-manager and CRDs using a Deployment
kubebuilder create config --controller-image myimage:v1 --name myextensionname --controller-type deployment

# Generate config file at a specific location
kubebuilder create config --crds --output myextensionname.yaml



Flags:
      --controller-image string   name of the controller container to run.
      --controller-type string    either statefulset or deployment. (default "statefulset")
      --crd-namespace string      if set, install CRDs to this namespace.
      --crds                      if set to true, only generate crd definitions
      --name string               name of the installation.  used to generate the namespace and resource names.
      --output string             location to write yaml to (default "hack/install.yaml")
      --skip-map-validation       if set to true, skip generating validation schema for map type in CRD. (default true)
```

There is no option for me to generate the YAML template for sts/deployment. The use case is that I want to generate the CRDs and sts/deployment templates separately so as to help me create a helm chart. Any suggestions for me to achieve this? Thanks.

/cc @pmorie

**Comment by fanzhangio** [comment]
It should be mentioned that the `kubebuilder` in above issue comment is deprecating (v0 version). 
https://github.com/kubernetes-sigs/kubebuilder/issues/386
Could you please download and reinstall the lastest kubebuilder ?

For your use case, could you provide more details information? Thanks.

**Comment by gyliu513** [comment]
Thanks @fanzhangio , this is related to https://github.com/kubernetes-sigs/federation-v2/pull/245

The background is as follows: I want to create a helm chart based on the file `hack/install.yaml` generated by kubebuilder, but the problem here is that kubebuilder is generating a whole YAML template and does not split the files to different files, like including CRD YAML, sts YAML, deployment YAML etc, so here I want to check if kubebuilder can help me build different configuration files, such as I can use `kubebuilder create config --crds` to build all CRD resources, but there is no command which can enable me to build YAML templates without CRD resources.

> It should be mentioned that the kubebuilder in above issue comment is deprecating (v0 version).
#386
Could you please download and reinstall the lastest kubebuilder ?

Not quite catch what do your mean, do you mean that the latest kubebuilder has fixed the issue and enable me to generate a YAML template without CRDs?

**Comment by droot** [comment]
@gyliu513 we have tried to split the generated manifests in separate YAML files for newer versions. So in newer version, manifests are grouped as follows under `config` directory:

- crds
- sample
- manager
- rbac

I think what you are looking for are the manifests under `config/manager`. You can see an example project here --> https://github.com/kubernetes-sigs/controller-tools/tree/master/test/config

We have dropped the support for legacy project version, so I am marking this issue irrelevant, feel free to re-open this for latest version if your use-case is not supported.
