### ISSUE TITLE
Update the Multi-Version tutorial programatically when we run `make generate` 

### ISSUE THREAD

**Issue by camilamacedo86** [kubernetes-sigs/kubebuilder#3880]
## Context:

The code that appears in the docs/tutorial came from real samples under: https://github.com/kubernetes-sigs/kubebuilder/tree/master/docs/book/src

When we do changes we need to ensure that the samples are updated with the latest changes made in the PR. Therefore, when we run `make generate` target which is required to push any PR it will call   `make generate-docs` see:

https://github.com/kubernetes-sigs/kubebuilder/blob/7af3a37557c695f936b3cbde13db15a31ef521f1/Makefile#L66-L69

This target calls: https://github.com/kubernetes-sigs/kubebuilder/blob/master/hack/docs/generate.sh

which will:
- a) Use kubebuilder CLI bin with the latest changes to re-generate the samples, see for example the code used to re-generate the cronjob sample used in its tutorial (https://book.kubebuilder.io/cronjob-tutorial/cronjob-tutorial): https://github.com/kubernetes-sigs/kubebuilder/blob/master/hack/docs/internal/cronjob-tutorial/generate_cronjob.go#L66-L94
- b) Replace/Add the code for the example on top, see for example that we have a file with consts for each part: https://github.com/kubernetes-sigs/kubebuilder/blob/master/hack/docs/internal/cronjob-tutorial/webhook_implementation.go and then we use the utils commands to insert/replace the content like here: https://github.com/kubernetes-sigs/kubebuilder/blob/master/hack/docs/internal/cronjob-tutorial/generate_cronjob.go#L146-L231

## What do we want :

We are re-generating all samples used in the tutorials already. However, we still automate this process for the Multi-Version sample in : https://github.com/kubernetes-sigs/kubebuilder/tree/master/docs/book/src/multiversion-tutorial/testdata/project which is used in the tutorial https://book.kubebuilder.io/multiversion-tutorial/tutorial

Currently, we do it manually by:
- a) Executing the shell script: https://github.com/kubernetes-sigs/kubebuilder/blob/master/docs/book/src/multiversion-tutorial/testdata/generate_multiversion.sh
- b) Comparing the local branch with master branch and re-adding manually on top again the code implementations as the cronjob conversion : https://github.com/kubernetes-sigs/kubebuilder/blob/master/docs/book/src/multiversion-tutorial/testdata/project/api/v1/cronjob_conversion.go

Therefore, the acceptance criteria of this task is to ensure that when we run `make generate` / `make generate-docs` we should re-generate the sample in https://github.com/kubernetes-sigs/kubebuilder/tree/master/docs/book/src/multiversion-tutorial/testdata/project and have all code examples on top of it again automatically 

## How to do it
- 1) Ensure that the sample is updated with the latest changes, you might do this process manually once to check how it works (see above the description over how we do it manually)

- 2) See that we might not properly calling all required commands with the shell script since the conversion cronjob needs to be re-added manually. So, we must follow the tutorial https://book.kubebuilder.io/multiversion-tutorial/tutorial to ensure that we are properly generating it with the tool. Note that the Multivesion sample is the CronJob one: https://github.com/kubernetes-sigs/kubebuilder/tree/master/docs/book/src/cronjob-tutorial/testdata/project generated within https://github.com/kubernetes-sigs/kubebuilder/tree/master/hack/docs/internal/cronjob-tutorial but with more one api and the conversion webhook added. The docs content which are comment in the docs are not the same either. 

- 3) The code implementation should be like the other examples so you will need to create a new dir under the hack/docs/internal and ensure that the automation is implemented there.

**Comment by camilamacedo86** [comment]
No, but that will b very helpful for us

**Comment by sarthaksarthak9** [comment]
![Screenshot from 2024-08-11 18-19-59](https://github.com/user-attachments/assets/39320dba-017c-499a-b83a-b5bdcbe4ff0a)
hi @camilamacedo86 . I try to manually run the script, and the above error are coming. I try to troubleshoot  and  verified that storage is false for both api v1 and v2. Could you pls look into this

**Comment by camilamacedo86** [comment]
Hi @sarthaksarthak9,

The error is OK, we faced that always because if you're using multiple versions, you need to mark one as storage, as noted here: https://book.kubebuilder.io/multiversion-tutorial/api-changes.html#storage-versions.


However, all scaffolds were done, so after the error we:
- compare the local branch with master
- add the missing code, and update the code on top again
- then, we run make all

and all works.

**Comment by camilamacedo86** [comment]
@sarthaksarthak9 

I am working in the upgrade of it now. See the PR: https://github.com/kubernetes-sigs/kubebuilder/pull/4069
(I need to validate if we still needing to have the FIXME or not) but that is it.

**Comment by sarthaksarthak9** [comment]
Hi @camilamacedo86,  Pls give some pointers.

Step I followed.

1) Manually generate the code by running the https://github.com/kubernetes-sigs/kubebuilder/blob/master/docs/book/src/multiversion-tutorial/testdata/generate_multiversion.sh.

2) Check the tutorial and ig the commands are calling properly.

3) Created a multiversion-tutorial dir under hack/docs/internal and ig now, I have to write generate_multiversion.go. But I don't find multiversion package here ?

Also, I have update generate.sh and generate_sample.go

**Comment by camilamacedo86** [comment]
Hi @sarthaksarthak9 

> Created a multiversion-tutorial dir under hack/docs/internal and ig now, I have to write generate_multiversion.go. But I don't find multiversion package [here](https://pkg.go.dev/sigs.k8s.io/kubebuilder/v4@v4.1.1/hack/docs/internal) ?

That is the goal of this task.
Implement the logic like we have to the others so that we will have the docs automatically update when we run make generate-docs
