### ISSUE TITLE
can not init project, because of the error "subpackage k8s.io/client-go/restmapper is missing"

### ISSUE THREAD

**Issue by asdfsx** [kubernetes-sigs/kubebuilder#389]
I init the project using the command
```
/usr/local/kubebuilder/kubebuilder init --domain k8s.io --license apache2 --owner "The Kubernetes Authors"
```
and receive the following error
```
dep ensure
Solving failure: No versions of k8s.io/client-go met constraints: 
        v8.0.0: Could not introduce k8s.io/client-go@v8.0.0, as it is not allowed by constraints from the following projects:
        kubernetes-1.10.1 from (root)
        kubernetes-1.10.1 from sigs.k8s.io/controller-runtime@master
......
        kubernetes-1.10.1: Could not introduce k8s.io/client-go@kubernetes-1.10.1, as its subpackage k8s.io/client-go/restmapper is missing. (Package is required by sigs.k8s.io/controller-runtime@master.) 
......
```

**Comment by mengqiy** [comment]
It seems you are not using a relatively old version of kubebuilder. Can you please try with the latest one?

**Comment by fanzhangio** [comment]
@asdfsx Did you happen to the same issue again by [kubebuilder v1](https://github.com/kubernetes-sigs/kubebuilder/releases/tag/v1.0.4)

**Comment by lblackstone** [comment]
I was seeing the same problem with `v1.0.1`, but it worked with `v1.0.4`.

FWIW, the code snippet in the [installation docs](https://book.kubebuilder.io/getting_started/installation_and_setup.html) has `1.0.1` listed, and I initially assumed that was automatically updated with the latest tag.
