### ISSUE TITLE
Watching and syncing resources created to support CRD objects

### ISSUE THREAD

**Issue by liyinan926** [kubernetes-sigs/kubebuilder#39]
I have a use case that as part of handling a newly added CRD object, a `StatefulSet` gets created and owned by the CRD object (through an `OwnerReference` added on the `StatefulSet`). The generated controller code for the CRD resource allows me to add a watch on `StatefulSet`s. But how can I register/add functions that react to events on the `StatefulSet`s and reconcile them?

Also it appears to me that watches with custom label selectors are not yet supported.

**Comment by crimsonfaith91** [comment]
@pwittrock 
Does kubebuilder provide the framework to register or add functions that react to _specific_ events on the StatefulSets? From my experience, I have to manually implement all logic in the `Reconcile` function.

**Comment by pwittrock** [comment]
@liyinan926  Not sure I understand the question.  Do you want a controller for the StatefulSet itself or for the CRD that creates it?  For most cases you should reconcile the CRD that created the controller and use the functions to map this to the controller - such as [WatchControllerOf](https://godoc.org/github.com/kubernetes-sigs/kubebuilder/pkg/controller#GenericController.WatchControllerOf).  If you really want a second controller just for the statefulset, then you should be able to create one using the controller libraries directly and registering the GenericController in the inject package.

**Comment by liyinan926** [comment]
@pwittrock Thanks for answering! My use cause needs watching the `StatefulSet`s created by the CRD controller and reacts to events on the `StatefulSet`s. For example, if such a `StatefulSet` was deleted accidentally by the user, a new replacement StatefulSet needs to be created. Thanks for the pointer to `WatchControllerOf`. It seems that I can use `WatchControllerOf` to map the `StatefulSet` to the controller CRD object and reconcile the CRD object.
