### ISSUE TITLE
pull controller image failed

### ISSUE THREAD

**Issue by Jerry-yz** [kubernetes-sigs/kubebuilder#3921]
### What broke? What's expected?

when i install controller-manager, i have err:
Failed to pull image "controller:latest": failed to pull and unpack image "docker.io/library/controller:latest": failed to resolve reference "docker.io/library/controller:latest": pull access denied, repository does not exist or may require authorization: server message: insufficient_scope: authorization failed
How do i use it

### Reproducing this issue

i use `docker pull controller:latest`, it recurrent

### KubeBuilder (CLI) Version

KubeBuilderVersion:"v3.15.0-1-gce113d256"

### Other versions

go version 1.22
kubectl version v1.30.1

**Comment by camilamacedo86** [comment]
Hi @Jerry-yz 

The command  `docker pull controller:latest` will not work at all.
This image is not published in any place.

You need to push the image for an register or "load" in your k8s cluster

I would like to suggest follow up the quick start: https://book.kubebuilder.io/quick-start.html#run-it-on-the-cluster

See that you will use the command `make docker-build docker-push IMG=<some-registry>/<project-name>:tag` to build and push the image for your register. The `<some-registry>` can be for example a public repo in dockerhub.io.

I hope that helps you out.
I am closing it as sorted out.

**Comment by Jerry-yz** [comment]
> Hi @Jerry-yz
> 
> The command `docker pull controller:latest` will not work at all. This image is not published in any place.
> 
> You need to push the image for an register or "load" in your k8s cluster
> 
> I would like to suggest follow up the quick start: https://book.kubebuilder.io/quick-start.html#run-it-on-the-cluster
> 
> See that you will use the command `make docker-build docker-push IMG=<some-registry>/<project-name>:tag` to build and push the image for your register. The `<some-registry>` can be for example a public repo in dockerhub.io.
> 
> I hope that helps you out. I am closing it as sorted out.

ok, thanks
