### ISSUE TITLE
kustomize: strategicMergePatch clobbers patched arrays

### ISSUE THREAD

**Issue by joelanford** [kubernetes-sigs/kubebuilder#3934]
### What broke? What's expected?

When I enabled the `manager_metrics_patch.yaml` in `config/default/kustomization.yaml`, it wiped out the arguments that I had setup in the `config/manager/manager.yaml`.

### Reproducing this issue

Initialize project and build manifests with and without metrics patch commented:
```
kubebuilder init --plugins go/v4 --domain example.org --owner "Your name" --repo example.org/test-project
make kustomize && bin/kustomize-v5.3.0 build config/default > default.yaml
sed -i 's/#- path: manager_metrics_patch.yaml/- path: manager_metrics_patch.yaml/' config/default/kustomization.yaml
make kustomize && bin/kustomize-v5.3.0 build config/default > metrics-patch.yaml
```

Diff the manifests:
```
diff default.yaml metrics-patch.yaml
151,153c151
<         - --leader-elect
<         - --health-probe-bind-address=:8081
<         - --metrics-bind-address=0
---
>         - --metrics-bind-address=0.0.0.0:8080
```

### KubeBuilder (CLI) Version

v3.15.0

### PROJECT version

v3

### Plugin versions

```yaml
go.kubebuilder.io/v4
```

**Comment by camilamacedo86** [comment]
Hi @joelanford,

For now I think the best is we ensure that it is as it was before: https://github.com/kubernetes-sigs/kubebuilder/pull/3937
 I tracked an issue for we analyse the suggestion to use Pod instead: https://github.com/kubernetes-sigs/kubebuilder/issues/3936
