### ISSUE TITLE
GitHub page link update

### ISSUE THREAD

**Issue by DaliborLabudovicGP** [kubernetes-sigs/kubebuilder#3935]
### What broke? What's expected?

The link to installation instructions under Github readme page. 

### Reproducing this issue

Click the link

### KubeBuilder (CLI) Version

NA

### PROJECT version

NA

**Comment by camilamacedo86** [comment]
Hi @DaliborLabudovicGP 

I think your request is because you could not have access to the link. 

The docs are down. It seems that the infra is trying to move the DNS.
Sorry, for the inconvenience it should be sorted out up tomorrow.

**Comment by camilamacedo86** [comment]
Until there you can use the PR docs previous to check what you need from the master branch, see: https://deploy-preview-3937--kubebuilder.netlify.app/quick-start#installation

**Comment by camilamacedo86** [comment]
Closing this one since seems that it was opened due the docs are down.
However, if we misunderstood this one please feel free to re-open this one.
Please, if that be the case, provide further information for we see how we can better help you out.
