### ISSUE TITLE
RFE: Replace ServiceMonitor for PodMonitor

### ISSUE THREAD

**Issue by camilamacedo86** [kubernetes-sigs/kubebuilder#3936]
### What do you want to happen?

It was suggested by @erikgb :

> Less resources is better IMO, so I suggest adding an additional port to the manager service or use PodMonitor instead of ServiceMonitor.

Reason: We need to keep the args in manager and in the patch otherwise when the patch is made they are lost. More info; https://github.com/kubernetes-sigs/kubebuilder/issues/3934

The goal of this task is to analyse this possibility and see if we can came with a better solution.

**Comment by joelanford** [comment]
One thing came to mind after we chatter about this. Would `PodMonitor` be a problem for multi-replica controllers that use leader election? https://github.com/prometheus-operator/prometheus-operator/issues/3119#issuecomment-631409690

Probably need to try it out, but I wonder if `PodMonitor` and `ServiceMonitor` would result in different sets of scrape targets in our situation. Do controller-runtime non-leader replicas report liveness? And if not, I assume they are excluded from the scrape targets of `ServiceMonitor`. Is the same true for `PodMonitor`?

**Comment by camilamacedo86** [comment]
We changed how we scaffold it in the PR: https://github.com/kubernetes-sigs/kubebuilder/pull/3937
So, the motivation also is addressed. however, it still positional :-( 
We need to add a comment to clarify for users that they need to keep the bind metrics flag at the first position.

**Comment by camilamacedo86** [comment]
In the latest changes, following the @joelanford great ideas and suggestions I think we could either sorted the motivation here now we can add new args without the need to duplicate them in 2 files so I think we can close this one. However, if anyone think that is valid persue this idea please feel free to re-open and add your thoughts with why we would need to do so. 

Thank you for all collaboration !!!

**Comment by erikgb** [comment]
> One thing came to mind after we chatter about this. Would `PodMonitor` be a problem for multi-replica controllers that use leader election? [prometheus-operator/prometheus-operator#3119 (comment)](https://github.com/prometheus-operator/prometheus-operator/issues/3119#issuecomment-631409690)

No, non-leaders will also run as normal - seen from the outside of the Pod. Runnables that are leader-election aware will have to wait to become leader. This mainly applies to controllers AFAIK.
 
> Probably need to try it out, but I wonder if `PodMonitor` and `ServiceMonitor` would result in different sets of scrape targets in our situation. Do controller-runtime non-leader replicas report liveness? And if not, I assume they are excluded from the scrape targets of `ServiceMonitor`. Is the same true for `PodMonitor`?

Non-leader also reports liveness/readiness. If you have configured webhooks, all the ready replicas will lay behind the webhook Service. Both ServiceMonitor and PodMonitor uses labels to select pods, so the set of scrape target should be the same.
