### ISSUE TITLE
book.kubebuilder.io no longer reachable / dns record issing

### ISSUE THREAD

**Issue by ecerulm** [kubernetes-sigs/kubebuilder#3942]
### What broke? What's expected?

The documentation site at https://book.kubebuilder.io  no longer works 

I've checked in several tools and there is no DNS record for book.kubebuilder.io 

the web is still accessible as https://kubebuilder.io though. 

But google result still point to the now non-existing book.kubebuilder.io.

### Reproducing this issue

try to open https://book.kubebuilder.io

### KubeBuilder (CLI) Version

N/A

### PROJECT version

N/A

**Comment by detro** [comment]
Was the same almost all day yesterday too.

What's up folks? We need the lovely book :)

**Comment by omerxx** [comment]
We're waiting anxiously for a fix :)

**Comment by camilamacedo86** [comment]
We apologize for the inconvenience.

Our infrastructure team is currently working on transferring the domain to facilitate better management. This process is expected to be completed within the next 24 hours.

For more details, please refer to the Slack discussion: [Link to Slack Thread](https://kubernetes.slack.com/archives/CCK68P2Q2/p1716244720415899?thread_ts=1716187409.029509&cid=CCK68P2Q2).

In the meantime, you can access the documentation from the preview of PRs in the master branch here: [Preview Documentation](https://deploy-preview-3943--kubebuilder.netlify.app/).

Thank you for your patience and understanding.

**Comment by camilamacedo86** [comment]
Solved
