### ISSUE TITLE
Create testdata sample for samples in the reference links

### ISSUE THREAD

**Issue by camilamacedo86** [kubernetes-sigs/kubebuilder#3974]
### What do you want to happen?

**Context:**

In the hack/ dir we have a code that generate the samples and then add the code on top of this, see:

- a) Use kubebuilder CLI bin with the latest changes to re-generate the samples, see for example the code used to re-generate the cronjob sample used in its tutorial (https://book.kubebuilder.io/cronjob-tutorial/cronjob-tutorial): https://github.com/kubernetes-sigs/kubebuilder/blob/master/hack/docs/internal/cronjob-tutorial/generate_cronjob.go#L66-L94

- b) Replace/Add the code for the example on top, see for example that we have a file with consts for each part: https://github.com/kubernetes-sigs/kubebuilder/blob/master/hack/docs/internal/cronjob-tutorial/webhook_implementation.go and then we use the utils commands to insert/replace the content like here: https://github.com/kubernetes-sigs/kubebuilder/blob/master/hack/docs/internal/cronjob-tutorial/generate_cronjob.go#L146-L231

## Problem that we want to solve

The code under references in the docs are not in samples generate with real projects which means they are not tested and can easily get outdated. 

## How we want to solve

We would like to have a sample testdata that is generated and we can use the code. 
We might could have a controller-per reference instead of one project for each reference. 

ALso, by doing that we can test out the sample for each PR which will help us out ensure that all still valid when we update and move forward. 

Example: See https://kubebuilder.io/reference/watching-resources/externally-managed

This sample could be in a project and we could indeed test it out with e2e tests.

**Comment by BalaadityaPatanjali** [comment]
I would like to work on this !

**Comment by BalaadityaPatanjali** [comment]
> @BalaadityaPatanjali  Are you working on this issue?

No, you can work on it !

**Comment by camilamacedo86** [comment]
We've been reviewing the docs, and for the tutorials, we already have all samples generated. For the reference sections, however, it might not be as straightforward.

I think we’ll only be able to move forward if we create individual issues for each area where this effort is needed. So, I’d like to apologize if I’ve caused anyone to spend time on this particular task.

**I hope that nobody mind, but, for now, I'm closing this one**. However, if anyone has already reviewed an area that could benefit from a sample and has started working on it, please feel free to open a PR or raise a specific issue for that section.

Again, I apologize for any inconvenience, and thank you all for your help and understanding.
