### ISSUE TITLE
v2 vs v3 page is TODO

### ISSUE THREAD

**Issue by worr** [kubernetes-sigs/kubebuilder#3981]
Hey,

We're trying to evaluate the work for moving a kubebuilder project from v2 layout to v3. In looking a the migration options, the in-place migration document reads:

> Make sure you understand the [differences between Kubebuilder v2 and v3](https://book.kubebuilder.io/migration/v2vsv3.html) before continuing

However, https://book.kubebuilder.io/migration/v2vsv3.html leads to a TODO page, making it a lot harder for us to evaluate whether or not this is a safe path or what the implications are.

Thanks

**Comment by camilamacedo86** [comment]
Thank you for raising this one.
We probably lost the content in the cleanups to push v4.

You can check it here: https://book-v3.book.kubebuilder.io/migration/legacy/v2vsv3

We should fix this one by adding back the content which is in: https://github.com/kubernetes-sigs/kubebuilder/blob/v3.15.1/docs/book/src/migration/legacy/v2vsv3.md

So, to close this issue we just need to:
- Add the file  https://github.com/kubernetes-sigs/kubebuilder/blob/v3.15.1/docs/book/src/migration/legacy/v2vsv3.md in https://github.com/kubernetes-sigs/kubebuilder/tree/master/docs/book/src/migration

Please, feel free to open a PR to fix this one.

Thank you for your collab.

**Comment by camilamacedo86** [comment]
Closed with: https://github.com/kubernetes-sigs/kubebuilder/pull/3983

**Comment by worr** [comment]
Thanks a ton!!

13 jun 2024 17:43:08 Camila Macedo ***@***.***>:
