### ISSUE TITLE
Fail do "kubebuilder init" in 4.0.0

### ISSUE THREAD

**Issue by pantianying** [kubernetes-sigs/kubebuilder#3984]
### What broke? What's expected?

kubebuilder init --domain demo.so --repo gitlab.com/demo
```
INFO Writing kustomize manifests for you to edit...
INFO Writing scaffold for you to edit...
INFO Get controller runtime:
$ go get sigs.k8s.io/controller-runtime@v0.18.2
go: downloading go1.22 (darwin/arm64)
go: download go1.22 for darwin/arm64: toolchain not available
Error: failed to initialize project: unable to scaffold with "base.go.kubebuilder.io/v4": exit status 1

```

### Reproducing this issue

just do kubebuilder init
i found that go.mod use go 1.22 ; but the The correct spelling is 1.22.0
https://github.com/golang/go/issues/65568

### KubeBuilder (CLI) Version

4.0.0

**Comment by mateusoliveira43** [comment]
I had a similar problem with go.1.21

I believe you just need to update your Go version to it work (I am using go1.22.3 at the moment)

**Comment by camilamacedo86** [comment]
Hi @pantianying 

Thank you for raise it but that is extensively tested in each PR. 
We have no issue to run kubebuilder init in 4.0.0
For example, you can check that all projects in: https://github.com/kubernetes-sigs/kubebuilder/tree/master/testdata were generated within. 

We never added go 1.y.x in the go.mod in any kuebebuilder version.
You can check here for example it for v3: https://github.com/kubernetes-sigs/kubebuilder/blob/v3.15.1/testdata/project-v4/go.mod#L3

As you can see in the issue linked by you: https://github.com/golang/go/issues/65568#issuecomment-1932646496 the issue that you probably faced is related to Golang config in your env.

So, if you do not mind I am closing this one.
However, if you need any help please feel free to raise new issues.
