### ISSUE TITLE
Allow Custom Marker Prefix

### ISSUE THREAD

**Issue by beatrausch** [kubernetes-sigs/kubebuilder#3990]
### What do you want to happen?

Hi,

we are using kubebuilder as library and looking for a way to define markers with custom names like:

````go
var (
  conversionMarker = machinery.NewMarkerWithPrefixFor("+myprefix", kustomizationFile, "conversion")
)
````
What do you think?

Regards,

**Comment by beatrausch** [comment]
Hi,

I prepared the change on a [branch](https://github.com/beatrausch/kubebuilder/blob/b9601f011f49e281f36f72970436e9ae4210bd16/pkg/machinery/marker.go#L49). Just let me know if I should create a PR. 

Regards

**Comment by camilamacedo86** [comment]
Hi @beatrausch,

Thank you for bringing this to our attention. Your suggestion sounds interesting! 
**Please feel free to submit your proposed changes through a pull request so we can review them in detail.**

Assuming your changes do not alter the default behavior and are well-supported by tests, I see no reason why we wouldn't accept them.

Thank you once again for your valuable contribution.

Best regards,
