### ISSUE TITLE
kubebuilder should use 1.22.0 instead of 1.22

### ISSUE THREAD

**Issue by caozhuozi** [kubernetes-sigs/kubebuilder#4005]
### What do you want to happen?

Currently, the `go` directive in the [`go.mod` template](https://github.com/kubernetes-sigs/kubebuilder/blob/master/pkg/plugins/golang/v4/scaffolds/internal/templates/gomod.go#L48) for initializing a Kubebuilder project uses `1.22` instead of `1.22.0`. This causes the generated `go.mod` file to automatically include an unsightly `toolchain` directive, as Kubernetes ecosystem dependencies like `controller-runtime` actually use `1.22.0` in their `go.mod`.

```
INFO Get controller runtime:
$ go get sigs.k8s.io/controller-runtime@v0.18.2
go: upgraded go 1.22 => 1.22.0
go: added toolchain go1.22.2
```

Almost all of the Kubernetes ecosystem (projects in `kubernetes-sigs` or other popular projects like Istio) and Kubernetes itself now use `1.22.0` instead of `1.22` when updating the version.

I believe it would be better to align the `go` directive of the generated project (and kubebuilder itself) with the rest of the Kubernetes ecosystem.

If you agree that this is a good idea, I'm willing to raise a PR to apply the change ;-)

**Comment by camilamacedo86** [comment]
Hi @caozhuozi 

Please, feel free to push a PR with your suggestion
The change would be in: https://github.com/kubernetes-sigs/kubebuilder/blob/master/pkg/plugins/golang/v4/scaffolds/internal/templates/gomod.go#L48

Please, do not forget to run `make generate` to generate all samples under testdata and those used in the docs.

Thank you for you collaboration

**Comment by caozhuozi** [comment]
you are so quick. originally Im going to do this at weekend
