### ISSUE TITLE
Improved test support for 3rd party apps

### ISSUE THREAD

**Issue by beatrausch** [kubernetes-sigs/kubebuilder#4006]
### What do you want to happen?

Hi,

to provide better testing support for apps that use kubebuilder as a library, I propose the following small changes:

1. Set the file system as CLI option
```go
func WithFilesystem(fs machinery.Filesystem) Option {
	return func(cli *CLI) error {
		cli.fs = fs
		return nil
	}
}
```

2. Allow access to root command
```go
func (c CLI) Cmd() *cobra.Command {
	return c.cmd
}
```

This changes would help to build integration tests like:

```go
func TestInitIntegration(t *testing.T)  {
	actual := afero.NewMemMapFs()
	expected := afero.NewOsFs()

	root, err := myapp.BuildRootCli(actual)
	if err != nil {
		t.Error(err)
	}
	root.Cmd().SetArgs([]string{
		"init", "--domain", "example.org", "--module-name", "example.org/example/operator", "--project-name", "example-operator",
	})

	err := root.Run()
	if err != nil {
		t.Error(err)
	}

	err := compare(actual, expected, "./testdata/init-int-integration")
	if err != nil {
		t.Error(err)
	}
}
```

What do you think? 

Regards

**Comment by camilamacedo86** [comment]
Hi @beatrausch 

Please, feel free to push any PR that you seem fit to help you out use Kubebuilder as a lib.
Unless we have a real/good reason for not accept that, we will more than happy to have those merged.
If they are helpful to you probably will be helpful to others. 

Your collaboration is very appreciated and  welcome !!!

**Comment by beatrausch** [comment]
Great! I will prepare the code and create the PR.
