### ISSUE TITLE
update webhook marker docs

### ISSUE THREAD

**Issue by davidxia** [kubernetes-sigs/kubebuilder#4009]
### What broke? What's expected?

The [webhook markers doc](https://book.kubebuilder.io/reference/markers/webhook) doesn't have `url` even though recent versions of kubebuilder supports it. Does this page need to be refreshed or regenerated from the Golang source in some way?

### Reproducing this issue

Latest kubebuilder release 4.1.0 [uses controller-tools 0.15.0](https://github.com/kubernetes-sigs/kubebuilder/blob/release-4.1/pkg/plugins/golang/v4/scaffolds/init.go#L40) which [supports the `path` marker](https://github.com/kubernetes-sigs/controller-tools/blob/release-0.15/pkg/webhook/parser.go#L135). But the webhook marker doc page doesn't mention it.

### KubeBuilder (CLI) Version

4.1.0

### PROJECT version

3

### Plugin versions

```yaml
go.kubebuilder.io/v4
```

### Other versions

go 1.22.2

### Extra Labels

/kind documentation

**Comment by camilamacedo86** [comment]
Hi @davidxia 

Thank you for raising this one. Just to share:

- The page is defined in : https://github.com/kubernetes-sigs/kubebuilder/blob/master/docs/book/src/reference/markers/webhook.md?plain=1#L3-L7
- See that we have `{{#markerdocs Webhook}}` <- which generates the markers
- Here is the implementation for the Markerdocs: https://github.com/kubernetes-sigs/kubebuilder/blob/master/docs/book/utils/markerdocs/main.go
- Here is the script which calls this one: https://github.com/kubernetes-sigs/kubebuilder/blob/master/docs/book/markerdocs.sh
- Then, you can check that is called in https://github.com/kubernetes-sigs/kubebuilder/blob/master/docs/book/book.toml#L17

If someone have a time to look on that please feel free.

**Comment by camilamacedo86** [comment]
Acctualy, I think that I found already.
This PR should sort it out: https://github.com/kubernetes-sigs/kubebuilder/pull/4010
We will need to update the book-v3 to make the result appears in prod.
