### ISSUE TITLE
Support generating Role from kubebuilder rbac annotation

### ISSUE THREAD

**Issue by mengqiy** [kubernetes-sigs/kubebuilder#401]
kubebuilder currently only support generating ClusterRole, but there are use cases that we may only want a Role which restrict the permission to certain namespace.

**Comment by mengqiy** [comment]
cc: @droot @fanzhangio

**Comment by cvgw** [comment]
Any updates on this? Would be a very helpful feature for us as well

**Comment by mengqiy** [comment]
`controller-gen` in `controller-tools` can support an optional `namespace` marker for rbac generation.

**Comment by DirectXMan12** [comment]
we should move this issue over to the controller-tools repo, if people are still interested.

**Comment by mengqiy** [comment]
opened https://github.com/kubernetes-sigs/controller-tools/issues/225 to track in CT.
