### ISSUE TITLE
[Typo]: migration_guide_gov3_to_gov4.md doc

### ISSUE THREAD

**Issue by Gearheads** [kubernetes-sigs/kubebuilder#4014]
### What do you want to happen?

Hello, I think there might be a small typo on this doc?
https://github.com/kubernetes-sigs/kubebuilder/blob/master/docs/book/src/migration/migration_guide_gov3_to_gov4.md?plain=1#L133

The current sentence is:
```
you need to ensure that them can work with
```

I believe it should be:
```
you need to ensure that they can work with
```

I would be happy to help and create a PR. 😄 

Please let me know if I am mistaken.

### Extra Labels

/kind documentation

**Comment by camilamacedo86** [comment]
Please, feel free to push the PR with the fix.
