### ISSUE TITLE
"@[" in scaffolded Makefile results in `bash: line 1: @[: command not found`

### ISSUE THREAD

**Issue by davidxia** [kubernetes-sigs/kubebuilder#4017]
### What broke? What's expected?

This line https://github.com/kubernetes-sigs/kubebuilder/blob/c3a5806ad5de1803c366f84262c515281eb8b6d6/pkg/plugins/golang/v4/scaffolds/internal/templates/makefile.go#L268 of the scaffolded Makefile results in a warning when running `make controller-gen` and downloading the `bin/controller-gen-vX.Y.Z` executable.

```
make manifests

mkdir -p /Users/dxia/src/ghe.spotify.net/hendrix/raycluster-webhook/bin
test -s /Users/dxia/src/ghe.spotify.net/hendrix/raycluster-webhook/bin/controller-gen-v0.15.0 && /Users/dxia/src/ghe.spotify.net/hendrix/raycluster-webhook/bin/controller-gen-v0.15.0 --version | grep -q v0.15.0 || \
	@[ -f /Users/dxia/src/ghe.spotify.net/hendrix/raycluster-webhook/bin/controller-gen-v0.15.0 ] || { set -e; package=sigs.k8s.io/controller-tools/cmd/controller-gen@v0.15.0 ; echo "Downloading ${package}" ; GOBIN=/Users/dxia/src/ghe.spotify.net/hendrix/raycluster-webhook/bin go install ${package} ; mv "$(echo "/Users/dxia/src/ghe.spotify.net/hendrix/raycluster-webhook/bin/controller-gen-v0.15.0" | sed "s/-v0.15.0$//")" /Users/dxia/src/ghe.spotify.net/hendrix/raycluster-webhook/bin/controller-gen-v0.15.0 ; }
bash: line 1: @[: command not found
...
```

I expect no warning. No warning is shown once the `controller-gen-vX.Y.Z` executable exists on subsequent `make controller-gen` runs.

### Reproducing this issue

create a new kubebuilder project and run `make controller-gen`

1. `kubebuilder init --domain tutorial.kubebuilder.io --repo tutorial.kubebuilder.io/project`
2. `kubebuilder create api --group batch --version v1 --kind CronJob`
3. `make controller-gen`

### KubeBuilder (CLI) Version

4.1.0

### PROJECT version

3

### Plugin versions

```yaml
go.kubebuilder.io/v4
```

### Other versions

go version go1.22.4
sigs.k8s.io/controller-runtime v0.18.4
kubectl v1.29.3

happens on both

* Apple silicon with macOS Sonoma 14.5 with bash GNU bash, version 5.2.26(1)-release (aarch64-apple-darwin23.2.0)
* and Ubuntu 20.04.6 focal with bash GNU bash, version 5.0.17(1)-release (x86_64-pc-linux-gnu)

**Comment by davidxia** [comment]
I think `@[` was [released in 3.14.0](https://github.com/kubernetes-sigs/kubebuilder/blob/v3.14.0/pkg/plugins/golang/v4/scaffolds/internal/templates/makefile.go#L270) and introduced by #3718 [here](https://github.com/kubernetes-sigs/kubebuilder/pull/3718/files#diff-e5d6d4f9d67174f1f3764674eb786688353c77cef8514e24d1323e55e5a4a7e8R275).

**Comment by camilamacedo86** [comment]
Hi @davidxia 

Could you please try to check if the same issue is faced in the master branch?
If not, then we can consider it sort out.

**Comment by davidxia** [comment]
I can't repro on master. It's probably a local issue.
