### ISSUE TITLE
kubebuilder should support generated clientset for types

### ISSUE THREAD

**Issue by droot** [kubernetes-sigs/kubebuilder#403]
In `v1` version, we stopped generating clientset because controller-runtime provides `dynamic client` which works with any type. However, having capability to generate clientset will help migrating existing projects to Kubebuilder easier.

**Comment by guanchao-yang** [comment]
@droot  I can't agree more

**Comment by DirectXMan12** [comment]
closing.  It's doubtful that we'll add this -- it adds a lot of headaches, and runs counter to the [design of KubeBuilder](https://github.com/kubernetes-sigs/kubebuilder/blob/master/DESIGN.md)

**Comment by Cryptophobia** [comment]
This has been the most frustrating thing for me for the past 2 days. Inherited a tool that uses kubernetes CRDs that were obviously built with code-generator. Now I can't recreate the clients/informers/listers for the APIs to adhere to the new client-go versions...

Where in the design principles does it say that generating clients to access your APIs is against the design of Kubebuilder? Kubebuilder is a project generator but it's against the design principles to generate the clients to access your APIs and keep them steady across versions? 

> Prefer using go interfaces and libraries over relying on code generation

**_If you are designing to use steady and extendible interfaces, does it not mean you probably shouldn't be scared of code-generation..._**

So you generate a project and API, but then you are the mercy of using the Kubernetes clients at whatever version the clients care to use? 

> "Libraries Over Code Generation" 

Literally people have been hacking around this to make kubebuilder and code-generator work together: https://www.fatalerrors.org/a/writing-crd-by-mixing-kubeuilder-and-code-generator.html

Maybe that should be a sign that your design principle are not very practical....

**Comment by thesuperzapper** [comment]
I think the recommended way for users to consume CRDs in Go apps is to use the [`client.Client`](https://pkg.go.dev/sigs.k8s.io/controller-runtime/pkg/client) from [`controller-runtime`](https://github.com/kubernetes-sigs/controller-runtime) (even outside of Kubebuilder apps).

This then lets you simply import the generated CRD interface types from the Kubebuilder app, and you also get the benefit of being able to use [`cache.Cache`](https://pkg.go.dev/sigs.k8s.io/controller-runtime/pkg/cache) if you want to avoid making requests to the Kubernetes API, at the expense of caching them in memory using a ListWatch.

That is, there is not really a need for explicitly generated client sets anymore.
