### ISSUE TITLE
support shortNames field for auto-generated CRDs

### ISSUE THREAD

**Issue by crimsonfaith91** [kubernetes-sigs/kubebuilder#404]
The CRDs are auto-generated by running `make install`. However, the auto-generated CRDs do not have `shortNames` field. The CRD files are overwritten each time running `make install`, so manually changing the files is infeasible.

@droot

**Comment by cbrgm** [comment]
I'd love to see this feature too!

**Comment by bbc88ks** [comment]
Would be nice to have. We had to use a kustomize hack to make it work.
