### ISSUE TITLE
Using go.mod semantic versions don't work

### ISSUE THREAD

**Issue by fostercraig** [kubernetes-sigs/kubebuilder#4051]
### What broke? What's expected?

In https://github.com/kubernetes-sigs/kubebuilder/pull/4012 the versions were changed but I get this error: 

```

$ kubebuilder init --domain example.com --repo github.com/example/noderemoval-operator
INFO Writing kustomize manifests for you to edit... 
INFO Writing scaffold for you to edit...          
INFO Get controller runtime:
$ go get sigs.k8s.io/controller-runtime@v0.18.4 
go: errors parsing go.mod:
/Users/craig.foster/Downloads/noderemoval-operator/go.mod:3: invalid go version '1.22.0': must match format 1.23
Error: failed to initialize project: unable to scaffold with "base.go.kubebuilder.io/v4": exit status 1
```

Looks similar to issues like: https://github.com/jeremylong/DependencyCheck/issues/6052

If I revert the PR commit, I don't encounter the issue with the resulting binary. 

### KubeBuilder (CLI) Version

v4.1.1

**Comment by camilamacedo86** [comment]
Hi @fostercraig 

What is the go version installed locally?
Can you run `go version`?
I am betting that the issue here is that you have go 1.23 which is not support so far.

You must to use go version 1.22+ < 1.23

**Comment by fostercraig** [comment]
Ah, so I was at 1.19.11 and then I upgraded to 1.22.5 and saw the same error. 

Current: 

```
$ go version 

go version go1.22.5 darwin/arm64
```

**Comment by camilamacedo86** [comment]
Check your Go path and env
Ensure that the version configured in the go path is the version 1.22

Please, note that it is tested a lot and the error is not faced
Scaffold new projects is tested every time that we push a new change
- To generate the samples in the docs (See: https://github.com/kubernetes-sigs/kubebuilder/tree/master/hack/docs/internal)
- To generate the samples under testdata : https://github.com/kubernetes-sigs/kubebuilder/tree/master/testdata
- To generate the projects used in the e2e tests: https://github.com/kubernetes-sigs/kubebuilder/tree/master/test/e2e



So, it definitely works well if you are using a go version supported and has no issues in your Golang setup.

**Comment by fostercraig** [comment]
Well my toolchain is configured correctly but I do have a workaround, which is don't use that commit though I can definitely reinstall everything and try again.

**Comment by fostercraig** [comment]
So I tested with a golang Docker image and it works out of the box. I'll close this issue as unfortunately it's something in my env. Thanks!
