### ISSUE TITLE
can not create api

### ISSUE THREAD

**Issue by bearslyricattack** [kubernetes-sigs/kubebuilder#4059]
### What broke? What's expected?

I hope to create an API, but I am unable to succeed，Even if I have already reset Gobin, the Gobin issue still persists
![image](https://github.com/user-attachments/assets/d66b1718-f88e-4a44-a345-88c10cd5195d)

### KubeBuilder (CLI) Version

4.1.1

### Other versions

go 1.22.4

**Comment by camilamacedo86** [comment]
Hi @bearslyricattack 

What is the SO that you are using?

**Comment by camilamacedo86** [comment]
I am imagining that you could find the issue with your Golang env.
But if you see a hall for improvements in kubebuilder or still needing help please feel free to re-open this one.

I am closing this for now.
