### ISSUE TITLE
LeaderElection in the scaffolding generated by kubebuilder supports Callbacks

### ISSUE THREAD

**Issue by gagraler** [kubernetes-sigs/kubebuilder#4064]
### What do you want to happen?

The scaffolding code generated by kubebuilder currently does not directly support LeaderElection Callbacks, which is in the "k8s.io/client-go/tools/leaderelection" package. I would like to know how to do it. Thank you

**Comment by camilamacedo86** [comment]
Hi @gagraler,

Kubebuilder uses [controller-runtime](https://github.com/kubernetes-sigs/controller-runtime). If it doesn’t directly support LeaderElection Callbacks from the `k8s.io/client-go/tools/leaderelection` package and you’d like to see this feature added, you can raise a (RFE) in the controller-runtime project.

Thanks for understanding—I’ll go ahead and close this issue.

Best regards,
