### ISSUE TITLE
Make Kubebuilder `go install`-able

### ISSUE THREAD

**Issue by AndersBennedsgaard** [kubernetes-sigs/kubebuilder#4079]
### What do you want to happen?

(I couldn't find any mentions about this, but feel free to close this if it is a duplicate)

I would like to add a target in my Makefile to install `kubebuilder` locally, such that all developers of our operator uses the same version of it.
https://book.kubebuilder.io/quick-start#installation doesn't explain how to install a specific version of Kubebuilder (you actually can't just change the version from `latest` in `https://go.kubebuilder.io/dl/latest/$(go env GOOS)/$(go env GOARCH)`) so I use the Github releases directly: `curl -L -o $(KUBEBUILDER) "https://github.com/kubernetes-sigs/kubebuilder/releases/download/$(KUBEBUILDER_VERSION)/kubebuilder_$(GOOS)_$(GOARCH)"`

This does work, but I would really prefer to just use `go install` since that is much simpler (doesn't require setting `GOOS` and `GOARCH`), I can make use of the `go-install-tool` helper, and it works even when you don't have `curl` and `chmod` installed such as on Windows.

By making Kubebuilder `go install`-able the installation steps for all distributions could be changed to use this, since it would be better (in my opinion) than the existing steps. It would also fix the installation steps for Windows in https://github.com/kubernetes-sigs/kubebuilder/issues/2940

**Comment by camilamacedo86** [comment]
Hi @AndersBennedsgaard 

Thank you for raise this one. See that you can create a Makefile to download the binary as follows:

```
# Variables
KUBEBUILDER_VERSION ?= v4.1.1.  # Change to the desired version
KUBEBUILDER_BIN = $(HOME)/bin/kubebuilder
GOOS = $(shell go env GOOS)
GOARCH = $(shell go env GOARCH)
KUBEBUILDER_URL = https://github.com/kubernetes-sigs/kubebuilder/releases/download/$(KUBEBUILDER_VERSION)/kubebuilder_$(GOOS)_$(GOARCH).tar.gz

# Targets
.PHONY: all install-kubebuilder

all: install-kubebuilder

install-kubebuilder:
	@echo "Installing Kubebuilder version $(KUBEBUILDER_VERSION)..."
	@mkdir -p $(HOME)/bin
	@curl -L -o kubebuilder.tar.gz $(KUBEBUILDER_URL)
	@tar -xzf kubebuilder.tar.gz -C $(HOME)/bin/
	@rm kubebuilder.tar.gz
	@echo "Kubebuilder installed at $(KUBEBUILDER_BIN)"
	@$(KUBEBUILDER_BIN)/kubebuilder version

```

> It I would really prefer to just use go install since that is much simpler (doesn't require setting GOOS and GOARCH), I can make use of the go-install-tool helper, and it works even when you don't have curl and chmod installed such as on Windows.

We would need to check what are the changes required to do so.
But if you do not want to use curl you can also git clone the project and run make install from the root dir
That will install the project from the source., In this case the Makefile would be something like

```
# Variables
KUBEBUILDER_VERSION ?= v4.1.1 # Change to the desired version
KUBEBUILDER_REPO = https://github.com/kubernetes-sigs/kubebuilder.git
KUBEBUILDER_DIR = kubebuilder
KUBEBUILDER_BIN = $(HOME)/bin/kubebuilder

# Targets
.PHONY: all install-kubebuilder clean

all: install-kubebuilder

install-kubebuilder:
	@echo "Installing Kubebuilder version $(KUBEBUILDER_VERSION)..."
	@mkdir -p $(HOME)/bin
	@if [ -d "$(KUBEBUILDER_DIR)" ]; then \
		cd $(KUBEBUILDER_DIR) && git fetch --tags && git checkout $(KUBEBUILDER_VERSION); \
	else \
		git clone $(KUBEBUILDER_REPO) $(KUBEBUILDER_DIR) && cd $(KUBEBUILDER_DIR) && git checkout $(KUBEBUILDER_VERSION); \
	fi
	@cd $(KUBEBUILDER_DIR) && make install
	@echo "Kubebuilder installed at $(KUBEBUILDER_BIN)"
	@$(KUBEBUILDER_BIN) version
```

However, we need to share that Windows is not an officially supported env.
You might able to use Kuebuilder using tools like  Windows Subsystem for Linux (WSL). However, I do not know if all will work well. You might either want to just have a container and work on it. 
See the PR: https://github.com/kubernetes-sigs/kubebuilder/pull/4078

By last, if you want to push a PR with the required changes to allow go install we can review it and see if we can or not accepted the change.

**Comment by camilamacedo86** [comment]
I am closing this one.

But if anyone have interest to propose a solution to attend this request please feel free to push a PR or a design doc(if that br too big). I am not sure as described above if it would be achievable.

**Comment by migueleliasweb** [comment]
I can see 3 ways to address this issue:

1. Move the main.go file to the root of the repository, so then the final binary gets the name of the repository which is the expected behaviour 
2. Rename the `cmd` folder to `kubebuilder` 
3. Add a subfolder inside `cmd` called `kubebuilder`

Currently, the `go install` command doesn't allow changing the name of the binary and afaik, it relies on the name of the folder the binary is in to determine its final name.

None of these changes would impact users that rely on  `kubebuilder` as a library. At the same time, for the users that only use the cli directly, no breaking changes are expected.
