### ISSUE TITLE
Support for selectable fields for custom resources

### ISSUE THREAD

**Issue by everesio** [kubernetes-sigs/kubebuilder#4085]
### What do you want to happen?

Kubernetes 1.31 introduces the ability to define field selectors for custom resources.
You can find more details in the official documentation [crd-selectable-fields](https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/#crd-selectable-fields)

This issue is a feature request to add support for this functionality to Kubebuilder, including the addition of a new generator annotation and extending the documentation to explain how the feature should be used.

**Comment by camilamacedo86** [comment]
Hi @everesio 

The CRDs and markers are implemented in controller-tools : https://github.com/kubernetes-sigs/controller-tools
You can see your Makefile that when you run `make manifest` the controller-gen binary will be downloaded and used.

So, this RFE must be applied to this project. Then, when do a release with a new marker supporting it kubebuilder will be able to consume and generate the docs accordingly with the explanations defined in their source code. 

cc/ @sbueringer  ^

**Comment by everesio** [comment]
Hi @camilamacedo86,
I've just created a new [issue](https://github.com/kubernetes-sigs/controller-tools/issues/1039) in the controller-tools.
