### ISSUE TITLE
Enhance the e2e test scaffolding and add a GitHub Action to demonstrate their usage

### ISSUE THREAD

**Issue by camilamacedo86** [kubernetes-sigs/kubebuilder#4088]
## What we would like to do here:

- Create a GitHub Action that will execute the e2e tests, similar to the one we use in [this example](https://github.com/kubernetes-sigs/kubebuilder/blob/master/.github/workflows/test-sample-go.yml).
- Scaffold this GitHub Action in the project, making it clear how it should be used.
- Add comments in the scaffolded e2e tests and the GitHub Action to clarify their intentions and purposes.

## Motivation:

https://github.com/kubernetes-sigs/kubebuilder/issues/3971

**Comment by camilamacedo86** [comment]
c/c @TAM360

I think you are working in this one.
Let's split to make it simple.

**Comment by TAM360** [comment]
@camilamacedo86 couple of points:

1. I get the point the E2E tests should be executed in isolated, and disposable environment. In the original post, they were talking about running them on some existing (QA) cluster. **What if someone doesn't want to use Kind and GH Action, and instead wants to test just on actual cluster (EKS, AKS etc) for some specific reason(s)?** 
2. Not everyone is using GH Actions as CI/CD platform. Adding a GH Action template won't help them. They will probably start opening new issues for the support of other CI/CD platforms like Gitlab, Circle CI etc. IMO we should be avoiding vendor specific implementation, if possible.
3. As mentioned by others in the issue, adding a simple guard rail for checking the K8s cluster context can help them in avoiding the disaster that they described. This can be as simple as simple as running Kubectl command (`kubectl config current-context`), or using Go SDK to getting the current context from `~/.kube/config` file.

**Comment by camilamacedo86** [comment]
Hi @TAM360 

> What if someone doesn't want to use Kind and GH Action, and instead wants to test just on actual cluster (EKS, AKS etc) for some specific reason(s)?

They are able to do that as it is today.
By adding GitHub action to demonstrate how they can use the e2e tests does not either remove this possibility. 

> Not everyone is using GH Actions as CI/CD platform. Adding a GH Action template won't help them. They will probably start opening new issues for the support of other CI/CD platforms like Gitlab, Circle CI etc. IMO we should be avoiding vendor specific implementation, if possible.

That is true. But GitHub is what we use for Kubebuilder
My thought is in the future move this scaffold + the GitHub Workspace for a plugin
So, people can opt in or not for.

Also, the whole point is demonstrate how to do.
The idea of the e2e tests it to use it call in the CI to validate the PR changes in the project
We have other issues asking how to do that. 

> As mentioned by others in the issue, adding a simple guard rail for checking the K8s cluster context can help them in avoiding the disaster that they described.

We do not do that for any command.
If we run kubectl it will use the default context that is expected bahaviour 

The problem in the issue https://github.com/kubernetes-sigs/kubebuilder/issues/3971 was caused for someone running make test-e2e against an env that they should not and without know what the target does. Also, seems that they are distributing the source code which is something that they should not do as well. 

While there's always room for improvement, there are limits to what we can do if users run commands against production environments without first understanding what they do or reading the documentation. We do our best to help upskill, but some level of common sense and knowledge is expected from developers when they are adopting any framework/tool.

**Comment by TAM360** [comment]
> We do not do that for any command. Why it is a problem with the e2e-test and not with the deploy or install and etc?
All makefile targets uses the default context. (that is an expected behavior)

Out of curiosity: Does it always has to be KInd's cluster context? If we somehow allow the end user to change the context before running any of the tests, will it work?

**Comment by camilamacedo86** [comment]
Hi @TAM360 

> Out of curiosity: Does it always has to be KInd's cluster context? If we somehow allow the end user to change the context before running any of the tests, will it work?

That is how k8s/kubectl works.
If you are using terraform, and you use terraform kubectl exec that will use the default context.
if you run kubectl get nodes that will use the default context
If you call a makefile target with
    kubectl dosomething that will use the default context

**Comment by camilamacedo86** [comment]
Hi @TAM360 

Due https://github.com/kubernetes-sigs/kubebuilder/issues/4088#issuecomment-2302696731 I have no idea how to prevent someone to run `make do something` expecting that the makefile target will reach out the k8s context A when the person has setup k8s context B. If you or anyone have suggestions about it please feel free to push a PR with.

**Comment by TAM360** [comment]
@camilamacedo86 I think the simplest approach would be to:

- Introduce flag like `context` that passes the specific K8s cluster context. It should have a default context point to `Kind` cluster.
- If custom value is passed, then Makefile should run the command `kubectl config use-context <context-name>` before executing the tests.
- Same context will work for each of the tests (like the current implementation).

Again this will require some level of vigilance from the end user because if they accidentally pass the wrong context, the end result would be the same as OP mentioned in the issue.

**Comment by camilamacedo86** [comment]
Hi @TAM360 

> Introduce flag like context that passes the specific K8s cluster context to the makefile. It should have a default context point to Kind cluster.

Not all users have more than a context locally.
In Kubebuilder we look for the simplicity and work as any other tool. (KISS)

However, if the person has more than a context then this person can decide how he/she prefer to manage it.
For example, (I never use the flag for all commands because it is pitiful). 
It is not a good approach at all.

Due this reason none tool does that.

**Comment by TAM360** [comment]
@camilamacedo86 I agree that having a flag increase the complexity. Ultimately, flag usage would still be based on the assumption that the end user knows how to use it, which doesn't solve the OP's problem.
