### ISSUE TITLE
Enhance E2E Test Scaffold with Optional Prometheus and Cert-Manager Installation

### ISSUE THREAD

**Issue by camilamacedo86** [kubernetes-sigs/kubebuilder#4089]
### What do you want to happen?

Projects are scaffolded with e2e tests, which by default, should be executed in a specific environment. The common practice is to spin up an environment, run the tests, and then tear down the environment to ensure the tests are executed in isolation.

However, some users might prefer to run these tests in an environment where Prometheus and Cert-Manager are already installed, or in cases where their project does not require these tools. Users should still be able to customize their scaffold as needed. (Motivation: https://github.com/kubernetes-sigs/kubebuilder/issues/3971)

To facilitate this, we can add a logic that uses an environment variable to skip the installation of these tools, such as INSTALL_PROMETHEUS_E2E_TEST=false.

The changes should be made in the following section of the code:

https://github.com/kubernetes-sigs/kubebuilder/blob/94d8fce49227f87f7a4e79f9c5d121e1e942b5bf/testdata/project-v4/test/e2e/e2e_test.go#L32-L43

Additionally, we have a practice of adding `TODO(user): comments`. We must ensure that this code includes comments explaining how the tests should be used and describing the ability to disable the installation of Prometheus and Cert-Manager in the e2e tests.

**Comment by TAM360** [comment]
@camilamacedo86 I would also like to work on this as it is linked with the other task too.

**Comment by camilamacedo86** [comment]
> @camilamacedo86 so by default the steps to install, and delete Prometheus, and Cert Manager would be commented in a new project, and if anyone who wants to use it would have un-comment the relevant lines first?

**Honest, I do not know how much value comment it will bring or if it will bring more pain**
Because either install the solution in a cluster where it should not be done will cause problems.

Note that if someone scaffold webhooks then need install cert-manager
Also, we would need to uncomment either our tests: https://github.com/kubernetes-sigs/kubebuilder/blob/master/.github/workflows/test-sample-go.yml

In this way, wdyt about we try to do first: https://github.com/kubernetes-sigs/kubebuilder/issues/4088
Then, we revisit this one again to see if still fit and if it would make sense.

**Comment by camilamacedo86** [comment]
Hi @TAM360 

Furthermore, users need to customize the implementation according to their needs.
But, lets think here what we can do to help out.
