### ISSUE TITLE
Can't run `kubebuilder init` with a non-official go release

### ISSUE THREAD

**Issue by grantr** [kubernetes-sigs/kubebuilder#412]
#353 added a Go version check that bails if it can't parse the version string:

https://github.com/fraenkel/kubebuilder/blob/8a8b76fb4a56c67e4f799fcf035ee22006e3011d/cmd/kubebuilder/initproject/init.go#L136-L139

This makes users with installed go versions like `1.11rc2` completely unable to create kubebuilder projects. I'm not sure if that was the intent or not, but regardless it's a blocker for corporate developers using a custom or mandated golang version.

Since it seems like the purpose of the version check is to ensure that go is at least 1.10, I suggest adding a flag that allows users to skip the go version check and mentioning that flag in the fatal error message:

```
Couldn't parse Go version '1.11rc2'. Kubebuilder requires at least Go 1.10. You can skip
this check using the --skip-go-version-check flag.
```

**Comment by AndrewLapin95** [comment]
Can I work on the issue?

**Comment by AndrewLapin95** [comment]
Can I work on this?
