### ISSUE TITLE
CRD generation should support validation schema for optional struct

### ISSUE THREAD

**Issue by droot** [kubernetes-sigs/kubebuilder#413]
Kubebuilder generated validation schema in CRD doesn't support optional struct. It specifies the optional field with `type: object` that prevents the input manifest for a CR to omit it completely.

One of the ways to represent optional struct in validation schema would be:
```yaml
"anyOf:
- type: null
- type: object
```

refer: https://github.com/kubernetes/apiextensions-apiserver/issues/25

**Comment by apelisse** [comment]
Alternatively, you could use oneOf, but it really doesn't make a difference.

**Comment by DirectXMan12** [comment]
This is what `// +nullable` would be for, but it should be under CT.
