### ISSUE TITLE
Broken Link in Book

### ISSUE THREAD

**Issue by guettli** [kubernetes-sigs/kubebuilder#4178]
### What broke? What's expected?

On https://book.kubebuilder.io/ I click on [5.13. Manager and CRDs Scope](https://book.kubebuilder.io/reference/scopes) 

And I see an almost empty page

> # Manager and CRDs Scope

This seems broken.

### Reproducing this issue

.

### KubeBuilder (CLI) Version

.

**Comment by camilamacedo86** [comment]
Hi @guettli 

Thank you. It is fixed on master and the prod docs will be fixed after the next release, see:
https://master.book.kubebuilder.io/reference/scopes

Closing this one,
