### ISSUE TITLE
Add Helper for Kubebuilder alpha generate Command

### ISSUE THREAD

**Issue by camilamacedo86** [kubernetes-sigs/kubebuilder#4192]
### What do you want to happen?

We need to create a helper function to streamline the execution of the alpha generate command. This helper will encapsulate key logic and make it easier to maintain and extend the command functionality in the future.

For reference see the code implementation in: https://github.com/kubernetes-sigs/kubebuilder/pull/4180

**Comment by sandipanpanda** [comment]
I'd like to give this a try. Please let me know how I can get started.
/assign

**Comment by camilamacedo86** [comment]
Sure, please feel free 
Just keep in the mind we are proposing the changes: https://github.com/kubernetes-sigs/kubebuilder/pull/4180
You might want to use this PR / Commit as base to quick start your work

**Comment by Bharadwajshivam28** [comment]
Hey @camilamacedo86 I think @sandipanpanda is not working on this so can I give it a try?

**Comment by Bharadwajshivam28** [comment]
@camilamacedo86 what I see that creating a new function that has the main logic of the generate command. This function will include all the steps in the Generate method and in command.go we will call the new function.

**Comment by camilamacedo86** [comment]
@Bharadwajshivam28 

Help us validate that it is fixed for the latest release 4.3.0
So, I am closing this one

Thank you a lot for your contribution !!!
