### ISSUE TITLE
Add Input Validations for Command Flags for the command `alpha generate`

### ISSUE THREAD

**Issue by camilamacedo86** [kubernetes-sigs/kubebuilder#4193]
### What do you want to happen?

Currently, the alpha generate command lacks proper input validation for its flags. This issue aims to add robust validation to ensure that invalid flag values are caught early, improving the user experience and preventing potential runtime errors.

**Acceptance Criteria:**

1. Implement input validations for all flags in the alpha generate command.
2. Return meaningful error messages when invalid flags are provided.

For reference see its code in: https://github.com/kubernetes-sigs/kubebuilder/pull/4180

**Comment by architlatkar27** [comment]
Hi, I am interested in contributing to kubebuilder and would like to take this up as my first issue. 
Can i have a crack at it?

**Comment by camilamacedo86** [comment]
Yes, sure!! 
That seems a very good first issue.

**Comment by architlatkar27** [comment]
thanks a lot
/assign

**Comment by architlatkar27** [comment]
Hi, i would like some guidance on starting on this issue. As i understand this depends on the #4180 PR that you have created. 
On that branch i went through the generate command, which currently has two flags (--input-dir and --output-dir) for which the validation has been implemented. Are there more flags that i am missing?

**Comment by camilamacedo86** [comment]
Hi @architlatkar27,

In this case, we need to add validations for the flags. (see that we are using COBRA) These are the only flags available in the command:

- For both -input-dir and --output-dir, check if the directories exist. (Please, verify whether the directory is being created by the command or if it requires the directory to exist in advance before implement the check for `output-dir` )
- For -input-dir, ensure the PROJECT file exists within the directory.
- Additionally, the --output-dir should be empty before running the command.

Let me know if you need further clarification!

**Comment by camilamacedo86** [comment]
Hi @architlatkar27 

I checked this one.
The required checks are in place already now, see: https://github.com/kubernetes-sigs/kubebuilder/blob/f7a02ad0c98659d3e4de24dda55d7ef652d28a25/pkg/cli/alpha/internal/generate.go#L87-L110

So, I am closing this one since it is done already. 
Thank you
