### ISSUE TITLE
Improve E2E Test Coverage for Webhooks (Defaulting, Validation, Conversion) and Cert-Manager CA Injection

### ISSUE THREAD

**Issue by camilamacedo86** [kubernetes-sigs/kubebuilder#4202]
### What do you want to happen?

The current e2e tests for webhooks in the Kubebuilder repository cover basic webhook creation and validation. However, several important scenarios remain untested. To ensure comprehensive coverage, we propose expanding the tests to include:

- Defaulting Webhooks: Ensure defaulting webhooks apply resource defaults as expected.
- Validation Webhooks: Confirm that invalid resources are rejected by validation webhooks and validation logic is enforced.
- Conversion Webhooks: Verify conversion webhooks work when converting resources between different versions of CRDs.
- Cert-Manager CA Injection: Ensure cert-manager correctly injects CA certificates into all webhook types (defaulting, validation, and conversion), and verify that these webhooks function properly in a cluster.

Context:
There are existing tests for webhooks, such as in:

- [plugin_cluster_test.go](https://github.com/kubernetes-sigs/kubebuilder/blob/master/test/e2e/v4/plugin_cluster_test.go#L74-L78)
- [generate_test.go](https://github.com/kubernetes-sigs/kubebuilder/blob/master/test/e2e/v4/generate_test.go#L51-L56)
- [webhooks.go](https://github.com/kubernetes-sigs/kubebuilder/blob/f2a389780b0c068200d14d356283edf04021ed0b/test/e2e/utils/webhooks.go#L27-L79)

These tests can be added under a new directory in e2e tests or, if more convenient, integrated into the existing [go/v4](https://github.com/kubernetes-sigs/kubebuilder/tree/master/test/e2e/v4) test suite.

**Comment by awgrass** [comment]
If this is an easy one, I am happy to take it over. It would be my first contribution.

**Comment by Bharadwajshivam28** [comment]
@awgrass are you working on this?

**Comment by camilamacedo86** [comment]
Hi @awgrass and @Bharadwajshivam28,

I apologize; that was totally my fault.

As you can see, we’re already validating the injection here:

https://github.com/kubernetes-sigs/kubebuilder/blob/e02bbd46b0a4c3b0fed5025210a0419c718b49b0/test/e2e/v4/plugin_cluster_test.go#L242-L263

So, this step isn't necessary. What we need instead is an e2e test to validate the conversion from one version to another using the webhook. We can implement the necessary code in the sample, and potentially add it here:

https://github.com/kubernetes-sigs/kubebuilder/blob/master/docs/book/src/multiversion-tutorial/testdata/project/test/e2e/e2e_test.go

I’ll open a new issue to provide more details, and your assistance would be greatly appreciated!

**I'll go ahead and close this one as it’s already complete / not required.**

**Comment by camilamacedo86** [comment]
Hi @awgrass and @Bharadwajshivam28,

Please take a look at the issue here: https://github.com/kubernetes-sigs/kubebuilder/issues/4255.

Your assistance would be greatly appreciated, and feel free to collaborate if that works best for both of you!
