### ISSUE TITLE
404 for "https://book.kubebuilder.io/basics/what_is_a_resource.html"

### ISSUE THREAD

**Issue by miyadav** [kubernetes-sigs/kubebuilder#4205]
while navigating from - https://release-0-1.cluster-api.sigs.k8s.io/common_code/architecture , in order to read about resource in the background information section seeing 404 error , Please help to link it .

Both links broken 
1.https://book.kubebuilder.io/basics/what_is_a_resource.html
2.https://book.kubebuilder.io/basics/what_is_a_controller.html

**Comment by mateusoliveira43** [comment]
Issue should have been opened in this repo https://github.com/kubernetes-sigs/cluster-api, right? 

And to fix issue there, links could be changed to https://book-v1.book.kubebuilder.io/basics/what_is_a_resource and https://book-v1.book.kubebuilder.io/basics/what_is_a_controller

**Comment by camilamacedo86** [comment]
Hi @miyadav,

@mateusoliveira43 is correct.

It seems like you need to contact the maintainers of [this page](https://release-0-1.cluster-api.sigs.k8s.io/common_code/architecture). They will need to address the broken links in their documentation.

For reference, the latest release of the Kubebuilder CLI is version 4.x (currently 4.2.0), and the most up-to-date documentation is available at: https://book.kubebuilder.io/.

However, older versions of the documentation are hosted separately:

- v1: https://book-v1.book.kubebuilder.io/
- v2: https://book-v2.book.kubebuilder.io/
- v3: https://book-v3.book.kubebuilder.io/

For more details on contributing to the docs, see our [Contributing Guide](https://github.com/kubernetes-sigs/kubebuilder/blob/master/CONTRIBUTING.md#how-to-contribute-to-docs).

Regarding the broken links, they appear to be pointing to the v1 documentation, which is quite outdated:

https://book-v1.book.kubebuilder.io/basics/what_is_a_resource
https://book-v1.book.kubebuilder.io/basics/what_is_a_controller

If the page you're referencing is for an older release (v1), they might want to update those links accordingly.

Therefore, I hope that you do not mind.
We are closing this one but please feel free to raise new issues if you need to or re-open it if you see that fit.
