### ISSUE TITLE
Watcher does not support Unstructured objects

### ISSUE THREAD

**Issue by crimsonfaith91** [kubernetes-sigs/kubebuilder#422]
I spent a full day working on getting the watcher works for `Unstructured` objects, but failed to do any progress, so I deduce the watcher does not work for `Unstructured` objects.

For example,
```
err = controller.Watch(&source.Kind{Type: someUnstructuredResource.DeepCopyObject()}, &handler.EnqueueRequestForOwner{
	IsController: true,
	OwnerType:    &operatorv1alpha1.SomeOwnerResource{},
})
```

`.DeepCopyObject()` is a generated function returning a `runtime.Object`. When I modify an instance of `someUnstructuredResource`, the sync loop is not triggered.

To verify watcher does not work, I change `someUnstructuredResource.DeepCopyObject()` to `&corev1.Pod{}` and modify the pod. The sync loop is triggered.

@pwittrock 
@droot

**Comment by droot** [comment]
@shawn-hurley Can you pl. here since your are the most familiar with unstructured codebase.

**Comment by shawn-hurley** [comment]
@droot will take a look either today or tomorrow. 

I am personally using watches with unstructured objects right now. I wonder if you are setting the GVK for the unstructured object?

**Comment by shawn-hurley** [comment]
>  currently register the watcher within the sync loop (Reconcile function)

So it sounds like you are attempting to call `controller.Watch` during an already started controller. 

I am seeing the same blocking behavior if I use unstructured or `&v1.Pod{}` in a watch triggered inside a loop. This is because the start method of the controller takes the lock and does not let go until it is stopped.

This will not work for any scenario, unstructured or otherwise AFAIK. @droot @DirectXMan12 can you verify that is the case?

**Comment by droot** [comment]
>This is because the start method of the controller takes the lock and does not let go until it is stopped.

Correct. we just verified that from the code. Taking a deep look at it to see how we can support this use-case.

**Comment by crimsonfaith91** [comment]
@droot @shawn-hurley Sorry for not making it clearer in my previous comment.

I am aware of `Start` function of controller has a mutex lock too, so the mutex block should be a deadlock. However, this is not my main concern - I am only able to know about GVK of the unstructured object after controller starts. This means that I can only call `controller.Watch` dynamically in the sync loop (i.e., after the controller has started).

What I want to achieve is the ability to watch an object with dynamic type. I debugged by temporarily un-comment the mutex codes of `controller.Watch` function so that I can call the function within the sync loop. I then tried to watch a pod and the unstructured object - the pod's change triggered resync, but not the unstructured object. I think there may be a bug that the watcher does not handle unstructured objects (I may be wrong), but everything looks great after having a closer look to field of the unstructured object.

**Comment by DirectXMan12** [comment]
Pretty much any type you want to work with has to be registered with discovery.  If a given resource is not available in discovery, we can't work with it.  It doesn't necessarily need to be registered in the scheme, but if you can't find it at the `/apis` endpoint, then you will see that error

**Comment by crimsonfaith91** [comment]
@DirectXMan12 Oops, this problem has resolved. I will close it now. 

To fix the problem, it requires adding the scheme dynamically apart from this [change](https://github.com/kubernetes-sigs/controller-runtime/pull/178).
