### ISSUE TITLE
Fix CSS issue with navigation bar narrowing after mdBook upgrade to v0.4.40

### ISSUE THREAD

**Issue by camilamacedo86** [kubernetes-sigs/kubebuilder#4240]
## Description
After upgrading the mdBook version from v0.4.34 to v0.4.40, the navigation bar appears to have narrowed, resulting in reduced readability and usability. This change is evident when comparing the pre- and post-upgrade appearances (see screenshots below). 

**Before (i.e https://book.kubebuilder.io/architecture)**
![Screenshot 2024-10-29 at 12 07 48](https://github.com/user-attachments/assets/4283e104-504c-45a3-ac85-ca09df4df858)

**After update (https://deploy-preview-4239--kubebuilder.netlify.app/)**
![Screenshot 2024-10-29 at 12 07 34](https://github.com/user-attachments/assets/ce136984-9855-4c23-a1f2-1e6270ed5b0e)

See the PR: https://github.com/kubernetes-sigs/kubebuilder/pull/4239

## Steps to Reproduce
1. Check the docs preview of the PR: https://github.com/kubernetes-sigs/kubebuilder/pull/4239
2. Observe the narrower navigation bar on the left side, which restricts the space for the menu items.

## Expected Behavior
The navigation bar should maintain its previous width as it did in v0.4.34, allowing sufficient space for menu items and improving readability.

**Comment by thiha-min-thant** [comment]
Hi @camilamacedo86 , I would like to take this issue.
