### ISSUE TITLE
We should use pointer in the gitbhook example

### ISSUE THREAD

**Issue by mengqiy** [kubernetes-sigs/kubebuilder#434]
We should use a pointer. i.e. *int32 instead of int32.
~~https://github.com/kubernetes-sigs/kubebuilder/blob/master/docs/book/basics/simple_resource.md#containersetspec~~
~~Maybe same for the string field.~~

Using a pointer can avoid a lot of tricky problems, we should use that in our gitbhook example.

EDIT: It's in https://github.com/kubernetes-sigs/kubebuilder/blob/book-v1/docs/book/basics/simple_resource.md

**Comment by mengqiy** [comment]
cc: @droot

**Comment by vikramk7** [comment]
I can take this one.

**Comment by nzoueidi** [comment]
This too need to be closed as we don't have simple_resource.md in the book folder

**Comment by mengqiy** [comment]
@nzoueidi I updated the URL

**Comment by nzoueidi** [comment]
Thank you @mengqiy I can work on this. So, we just need to use *int32 instead of int32. Same applies for string, right?

**Comment by mengqiy** [comment]
Let's do it for replica field.
You will need to update 1) the type definition and 2) the controller reconciliation code.

**Comment by mengqiy** [comment]
Closed by #760
