### ISSUE TITLE
Add doc to book for resource generation annotations

### ISSUE THREAD

**Issue by pmorie** [kubernetes-sigs/kubebuilder#437]
On this page: https://book.kubebuilder.io/basics/simple_resource.html

The link to the old, pre-v1 API package is broken: https://godoc.org/github.com/kubernetes-sigs/kubebuilder/pkg/gen/apis

We should probably just have a page in the book that documents and contextualizes what the different annotations do.

**Comment by nzoueidi** [comment]
This should be closed, while the kubebuilder/pkg/gen/apis in godoc have been removed.
