### ISSUE TITLE
(helm/v1alpha1): Prometheus integration is not working well when enabled in the Chart

### ISSUE THREAD

**Issue by camilamacedo86** [kubernetes-sigs/kubebuilder#4378]
### What broke? What's expected?

We need to add in our GitHub action to test the Helm Chart: 
https://github.com/kubernetes-sigs/kubebuilder/pull/4377/files#diff-c93a79ad917924bb6a8d743a2c2b36706eeb045ed2e6b42b67b7928da9e7726aR108-R117

Then, we need to:
- We need to ensure that we replace prometheus: false with true in the values.yaml for the CI
- We need to fix the issue

```
Run helm install my-release ./dist/chart --create-namespace --namespace test-project-system
Error: INSTALLATION FAILED: unable to build kubernetes objects from release manifest: resource mapping not found for name: "test-project-controller-manager-metrics-monitor" namespace: "test-project-system" from "": no matches for kind "ServiceMonitor" in version "monitoring.coreos.com/v1"
ensure CRDs are installed first
Error: Process completed with exit code 1.
```

### KubeBuilder (CLI) Version

master

### Other versions

c/c @monteiro-renato

**Comment by monteiro-renato** [comment]
Hey 👋 
This is "expected" if the [CRD](https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/design.md#servicemonitor) hasn't been deployed to the cluster first. 
That has been mentioned in the [design doc](https://github.com/kubernetes-sigs/kubebuilder/blob/ab96f9a0ed8cb9cda2f1d5a9fccf001b697d50ac/designs/helm-chart-autogenerate-plugin.md?plain=1#L126-L133) as well.

**Comment by monteiro-renato** [comment]
I can add the missing bits to the Github Action.
Simply installing the CRDs as a dependency should fix the problem.
There's an [helm for the CRDs](https://github.com/prometheus-community/helm-charts/pkgs/container/charts%2Fprometheus-operator-crds), no need to install the bundle.

**Comment by monteiro-renato** [comment]
Ready for review!
