### ISSUE TITLE
`base.go.kubebuilder.io/v4` plugin help

### ISSUE THREAD

**Issue by mateusoliveira43** [kubernetes-sigs/kubebuilder#4395]
### What broke? What's expected?

When running CLI help commands, noticed that help for `base.go.kubebuilder.io/v4` and `go.kubebuilder.io/v4` are the same.

If you run `kubebuilder init -h --plugins=base.go.kubebuilder.io/v4`
```
Initialize a new project including the following files:
  - a "go.mod" with project dependencies
  - a "PROJECT" file that stores project configuration
  - a "Makefile" with several useful make targets for the project
  - several YAML files for project deployment under the "config" directory
  - a "cmd/main.go" file that creates the manager that will run the project controllers

Usage:
  kubebuilder init [flags]

Examples:
  # Initialize a new project with your domain and name in copyright
  kubebuilder init --plugins go/v4 --domain example.org --owner "Your name"

  # Initialize a new project defining a specific project version
  kubebuilder init --plugins go/v4 --project-version 3

...
```
you will note 2 mistakes:
1. it tells that config folder will be created
2. examples use `go.kubebuilder.io/v4` plugin and not `base.go.kubebuilder.io/v4`

**Note:** `go.kubebuilder.io/v4` is a bundle plugin created in `cmd/main.go`. Changing help for `base.go.kubebuilder.io/v4` also changes help for it. Need to create a way to bundle plugin to have a separate help

### Reproducing this issue

Run `kubebuilder init -h --plugins=base.go.kubebuilder.io/v4` and `kubebuilder init -h --plugins=go.kubebuilder.io/v4` 

### KubeBuilder (CLI) Version

built from master branch

### Extra Labels

/kind documentation

**Comment by camilamacedo86** [comment]
Hi @mateusoliveira43,

> base.go.kubebuilder.io/v4 and go.kubebuilder.io/v4

go.kubebuilder.io/v4 is an composition of  base.go.kubebuilder.io/v4 + kustomize/v2
They are not the same. 
the kustomize plugins scaffold all that is under config/ dire
base.go.kubebuilder.io/v4 - scaffold all that is related to Go outside of the config
that is done to allow other tools to create plugins using the same base but for other languages, such as Operator-SDK does for Ansible and Helm. 

> kubebuilder init -h --plugins=base.go.kubebuilder.io/v4

It should not say that the config/ dir will be created 
So, in its helper is required to remove

`  - several YAML files for project deployment under the "config" directory`

But `go.kubebuilder.io/v4` should. We need to see if that is possible to fix now.

**Comment by camilamacedo86** [comment]
I am closing this one.
I hope that the above explanation clarify how it works
Thank you for looking on that and all your help in the project.
