### ISSUE TITLE
https://book.kubebuilder.io/ is not sync?

### ISSUE THREAD

**Issue by bells17** [kubernetes-sigs/kubebuilder#441]
https://book.kubebuilder.io/ is not sync?

Github html is below:
https://github.com/kubernetes-sigs/kubebuilder/blob/d1fc6f75e6bcc465d6ed57c5ceb9c85db551a2c0/docs/book/public/getting_started/installation_and_setup.html#L685

Gitbook site is below:
https://book.kubebuilder.io/getting_started/installation_and_setup.html
![installation_and_setup_ _the_kubebuilder_book](https://user-images.githubusercontent.com/2158863/46903813-72acf300-cf15-11e8-99f6-39aeb4c839ef.png)

**Comment by droot** [comment]
Thanks for reporting it. This should be in sync now.
