### ISSUE TITLE
Generated openapi validation does not properly handle intstr.IntOrString

### ISSUE THREAD

**Issue by alvaroaleman** [kubernetes-sigs/kubebuilder#442]
When executing `go run vendor/sigs.k8s.io/controller-tools/cmd/controller-gen/main.go crd ` on a CRD that has a field of type [`intstr.IntOrString`](https://github.com/kubernetes-sigs/cluster-api/blob/70dec6624df750599dbf25b206020dca640fc761/pkg/apis/cluster/v1alpha1/machinedeployment_types.go#L100), the generated openAPI validation for that field will declare it as  [`type: Object`](https://github.com/kubernetes-sigs/cluster-api/blob/70dec6624df750599dbf25b206020dca640fc761/config/crds/cluster_v1alpha1_machinedeployment.yaml#L48).

This makes the validation always fail for that field, as `intstr.IntOrString` results in _either_ an int or a a string but not an object that holds a string and/or an int.

**Comment by lionelvillard** [comment]
same problem when the field type is `*int64` (which gets translated into `type: number`) and `*runtime.RawExtension`

**Comment by droot** [comment]
@sohankunkerkar can you pl. investigate this ?
