### ISSUE TITLE
kubebuilder init failed on a fresh project

### ISSUE THREAD

**Issue by magicsong** [kubernetes-sigs/kubebuilder#446]
When I follow the step in doc, I failed in the first step. The following is the logs:
```
dep ensure
Running make...
make
go generate ./pkg/... ./cmd/...
../../vendor/k8s.io/code-generator/cmd/deepcopy-gen/main.go:54:2: cannot find package "k8s.io/code-generator/cmd/deepcopy-gen/args" in any of:
        /usr/local/go/src/k8s.io/code-generator/cmd/deepcopy-gen/args (from $GOROOT)
        /home/magicsong/go/src/k8s.io/code-generator/cmd/deepcopy-gen/args (from $GOPATH)
../../vendor/k8s.io/code-generator/cmd/deepcopy-gen/main.go:55:2: cannot find package "k8s.io/code-generator/pkg/util" in any of:
        /usr/local/go/src/k8s.io/code-generator/pkg/util (from $GOROOT)
        /home/magicsong/go/src/k8s.io/code-generator/pkg/util (from $GOPATH)
../../vendor/k8s.io/code-generator/cmd/deepcopy-gen/main.go:51:2: cannot find package "k8s.io/gengo/args" in any of:
        /usr/local/go/src/k8s.io/gengo/args (from $GOROOT)
        /home/magicsong/go/src/k8s.io/gengo/args (from $GOPATH)
../../vendor/k8s.io/code-generator/cmd/deepcopy-gen/main.go:52:2: cannot find package "k8s.io/gengo/examples/deepcopy-gen/generators" in any of:
        /usr/local/go/src/k8s.io/gengo/examples/deepcopy-gen/generators (from $GOROOT)
        /home/magicsong/go/src/k8s.io/gengo/examples/deepcopy-gen/generators (from $GOPATH)
``` 

go version:
 go version go1.10.3 linux/amd64

**Comment by droot** [comment]
I am not able to reproduce it. Are you still facing this issue ?

**Comment by MagicSong** [comment]
> I am not able to reproduce it. Are you still facing this issue ?

Yes, I'm still struggling with it. My laptop is windows, I use WSL(windows subsystem for linux) to develop go program, and I use symbolic link in `GOPATH`(Because i need to map windows `GOPATH` to linux `GOPATH` so I can use IDE in windows and  build in linux). Everything is OK with other go program that not use 'go generate'。However it failed in kubebuilder, it seems `go generate` does not lookup the `vendor` of my project(you can see the output above).

**Comment by ffledgling** [comment]
Ran into exactly this issue today as well. `kubebuilder init` fails with:

```
Running make...                                                                                                             
make                                                                                                                       
go generate ./pkg/... ./cmd/...                                                                                               
../../vendor/k8s.io/code-generator/cmd/deepcopy-gen/main.go:54:2: cannot find package "k8s.io/code-generator/cmd/deepcopy-gen/args" in any of:
        /usr/local/go/src/k8s.io/code-generator/cmd/deepcopy-gen/args (from $GOROOT)                                           
        /home/anhad/go/src/k8s.io/code-generator/cmd/deepcopy-gen/args (from $GOPATH)                                  
../../vendor/k8s.io/code-generator/cmd/deepcopy-gen/main.go:55:2: cannot find package "k8s.io/code-generator/pkg/util" in any of:
        /usr/local/go/src/k8s.io/code-generator/pkg/util (from $GOROOT)                                         
        /home/anhad/go/src/k8s.io/code-generator/pkg/util (from $GOPATH)                                                   
../../vendor/k8s.io/code-generator/cmd/deepcopy-gen/main.go:50:2: cannot find package "k8s.io/gengo/args" in any of:
        /usr/local/go/src/k8s.io/gengo/args (from $GOROOT)                                                                       
        /home/anhad/go/src/k8s.io/gengo/args (from $GOPATH)                                                          
../../vendor/k8s.io/code-generator/cmd/deepcopy-gen/main.go:51:2: cannot find package "k8s.io/gengo/examples/deepcopy-gen/generators" in any of:
        /usr/local/go/src/k8s.io/gengo/examples/deepcopy-gen/generators (from $GOROOT)                                    
        /home/anhad/go/src/k8s.io/gengo/examples/deepcopy-gen/generators (from $GOPATH)                                                       
../../vendor/k8s.io/code-generator/cmd/deepcopy-gen/main.go:52:2: cannot find package "k8s.io/klog" in any of:
        /usr/local/go/src/k8s.io/klog (from $GOROOT)                         
        /home/anhad/go/src/k8s.io/klog (from $GOPATH)                       
pkg/apis/apis.go:17: running "go": exit status 1                                 
make: *** [Makefile:45: generate] Error 1                                                                                                   ```

**Comment by ffledgling** [comment]
fwiw, I found a "fix", but not quite sure what the underlying cause is.
In my case (and @magicsong's as well), it would seem we were symlinking our git repository into the `GOPATH` tree, something somewhere doesn't like this at all and causes things to break.

I switched the link around from `$GOPATH/src/ffledgling/myrepo -> some/path` to `some/path -> $GOPATH/src/ffledgling/myrepo`, so that the actual directory always lies in under the `$GOPATH` tree, and that fixed it. I also downgraded my golang version from `1.12` to `1.11.5` just in case because I see changelog shows `bump go version to 1.11`, so I'm not sure if the current version of kubebuilder supports `v1.11+` or just `v1.11.x`

**Comment by l10xbin** [comment]
Also, meet a similar issue:

Kubebuilder version:
Version: version.Version{KubeBuilderVersion:"1.0.8", KubernetesVendor:"1.13.1", GitCommit:"1adf50ed107f5042d7472ba5ab50d5e1d357169d", BuildDate:"2019-01-25T23:14:29Z", GoOs:"unknown", GoArch:"unknown"}

Golang version:
go version go1.11.2 linux/amd64

Error log:

kubebuilder init --domain my.domain
Run `dep ensure` to fetch dependencies (Recommended) [y/n]?
y
dep ensure
Running make...
make
go generate ./pkg/... ./cmd/...
go: creating new go.mod: module github.com/l10xbin/kb-sample
go: copying requirements from Gopkg.lock
go: github.com/peterbourgon/diskv@v0.0.0-20190425080511-0be1b92a6df0: go.mod has post-v0 module path "github.com/peterbourgon/diskv/v3" at revision 0be1b92a6df0
go: finding golang.org/x/tools v0.0.0-20190515035509-2196cb7019cc
go: finding golang.org/x/tools v0.0.0-20190206041539-40960b6deb8e
go: finding golang.org/x/exp v0.0.0-20190312203227-4b39c73a6495
go: finding golang.org/x/exp v0.0.0-20190125153040-c74c464bbbf2
go: finding github.com/remyoudompheng/bigfft v0.0.0-20170806203942-52369c62f446
go: finding gonum.org/v1/netlib v0.0.0-20190313105609-8cb42192e0e0
go: finding modernc.org/mathutil v1.0.0
go: finding modernc.org/xc v1.0.0
go: finding modernc.org/strutil v1.0.0
go: finding modernc.org/cc v1.0.0
go: finding modernc.org/golex v1.0.0
go: error loading module requirements
Makefile:45: recipe for target 'generate' failed
make: *** [generate] Error 1
2019/05/15 06:58:57 exit status 2

**Comment by l10xbin** [comment]
After I upgrade the golang version to go version go1.12.5 linux/amd64, the `init` works.

**Comment by DirectXMan12** [comment]
Scaffolding version 1 should not be used with `go modules` -- use scaffolding v2 instead -- it looks like go's trying to use modules there.  You'll need to make sure modules are off with v1 (if Go thinks you're in a GOPATH then that should work).  Otherwise, try scaffolding v2 in the v2.0.0 alpha.
