### ISSUE TITLE
Move code/cmd of ApiServer from api-builder project

### ISSUE THREAD

**Issue by cmoulliard** [kubernetes-sigs/kubebuilder#449]
Is it planned to move the code of the `apiserver-boot [1]` part of the project `github.com/kubernetes-incubator/apiserver-builder` within kubebuilder ?

[1] https://github.com/kubernetes-incubator/apiserver-builder/blob/master/cmd/apiserver-boot/boot/run/local.go

**Comment by droot** [comment]
>How could we now extend the API to expose a new operation (= /export) in order to let a client (oc, kubectl, ....) to call the API and to get all the k8s resources associated to a Component CRD ?

One way to model such operations would be as another resource say `ExportRequest` under the same group-version. `Status` field in `ExportRequest` can be used to track the progress of the operation.
