### ISSUE TITLE
Add version support for CRD in kubebuilder

### ISSUE THREAD

**Issue by fanzhangio** [kubernetes-sigs/kubebuilder#451]
Kubebuilder needs to add version support of CRD
https://kubernetes.io/docs/tasks/access-kubernetes-api/custom-resources/custom-resource-definition-versioning/

**Comment by jsriram7** [comment]
"Retweet" - Basically, when we add multiple versions, kubebuilder should render the crd definition something like 
versions:
  - name: v1beta1
    # Each version can be enabled/disabled by Served flag.
    served: true
    # One and only one version must be marked as the storage version.
    storage: true
  - name: v1
    served: true
    storage: false

Reference - above documentation

Also, it would be interesting to see how controller would mutate to support multi feature when this feature integrates

**Comment by DirectXMan12** [comment]
Fixed with CT v0.2.x
