### ISSUE TITLE
Namespace inconsistency issue

### ISSUE THREAD

**Issue by liyinan926** [kubernetes-sigs/kubebuilder#453]
It seems that kustomize stopped appending the name prefix (as specified in `namePrefix`) to the namespace name where the manager gets installed. However, the generated `kustomization.yaml` still uses the prefixed namespace name as specified by `namespace`, e.g., `foo-system`. So when used with the kustomize installed from head, the namespace created is the default `system`, instead of the correct one whose name has the prefix. This cause `make deploy` to fail to create the resources including the StatefulSet running the manager.

kubebuilder version: 1.0.4
go version: 1.10

**Comment by droot** [comment]
@Liujingfang1 @mengqiy we need to be careful in introducing breaking changes to `kustomize`. Can we pl. fix this.

**Comment by Liujingfang1** [comment]
Recently Kustomize made two following change:
- stop adding nameprefix to namespace resources 
- create namespace resource specified in `kustomization.yaml` if not found a matched one

This issue should only be seen in the period between the two changes.  After the two changes, kubebuilder projects will work with Kustomize head. The only impact is that kustomize will create an extra namespace resource `foo-system`.

**Comment by droot** [comment]
> Recently Kustomize made two following change:
> 
> * stop adding nameprefix to namespace resources
> * create namespace resource specified in `kustomization.yaml` if not found a matched one
> 
> This issue should only be seen in the period between the two changes. After the two changes, kubebuilder projects will work with Kustomize head. The only impact is that kustomize will create an extra namespace resource `foo-system`.

Thanks for clarification. so looks like @liyinan926 was unlucky and picked up the `Kustomize` in that window. @liyinan926 I would suggest using tagged `Kustomize` release instead of head to confirm if you are still facing this issue.

**Comment by Liujingfang1** [comment]
@liyinan926 @mengqiy @droot Those two change causes more problems than the it solves. I'll revert both of them. We're not going to touch this part before we have a really good solution for all usage. Sorry for changing this back and forth.

**Comment by droot** [comment]
closing it now. @liyinan926 pl. reopen it if you are still running in to issues.
