### ISSUE TITLE
Separate kubernetes service account for controller manager

### ISSUE THREAD

**Issue by eLco** [kubernetes-sigs/kubebuilder#454]
Currently generated yaml for controller manager rely on default kubernetes service account that is created in namespace.
Maybe it is better to use separate Service Account for role binding.

**Comment by janetkuo** [comment]
Agree that controller manager shouldn't use default service account. Any workload will by default also inherit their permissions. These permissions should be intentionally assigned, not assigned through omission.

**Comment by janetkuo** [comment]
One question that I have is how to customize namespace and name prefix of the service account  subject in a `ClusterRoleBinding`:

https://github.com/kubernetes-sigs/kubebuilder/blob/eabb3ddfca48c19521cd98f37bd31d4400913792/pkg/scaffold/v2/mgrrolebinding.go#L49-L52

`kustomize` doesn't seem to support that.

**Comment by DirectXMan12** [comment]
> Agree that controller manager shouldn't use default service account. Any workload will by default also inherit their permissions. 

We scaffold out with the assumption that your controller is running in its own namespace, so using the default SA is fine.

> One question that I have is how to customize namespace and name prefix of the service account subject in a ClusterRoleBinding. kustomize doesn't seem to support that.

I believe it does, since that should be getting turned into `name: default, namespace: <project>-system`.  I think that may be one of the things we had to tell kustomize about, but I don't remember off the top of my head.  cc @mengqiy

**Comment by mengqiy** [comment]
> One question that I have is how to customize namespace and name prefix of the service account subject in a ClusterRoleBinding. kustomize doesn't seem to support that.

This is supported in the latest `kustomize`.

The change should be straightforward:
- scaffold a new service account
- change the roleBindings to use the new service account

**Comment by camilamacedo86** [comment]
Hi, @DirectXMan12 and @mengqiy the PR was closed with info that let me believe that it should not be done. Am I right? So, should not this issue be closed as well?

**Comment by DirectXMan12** [comment]
yeah
