### ISSUE TITLE
book.kubebuilder.io out of date: kubebuilder create api

### ISSUE THREAD

**Issue by Kashomon** [kubernetes-sigs/kubebuilder#456]
I was going through http://book.kubebuilder.io, and came across numerous cases referring to `kubebuilder create api`. I think this has been replaced with `kubebuilder create resource` but it's rather confusing for getting started.

**Comment by droot** [comment]
`kubebuilder create api` is the right command. We should no longer we using `kubebuilder create resource` in the docs. Can you point the occurrences of `create resource` ?

**Comment by HagaiBarel** [comment]
@droot you can find a reference here - https://book.kubebuilder.io/beyond_basics/generating_documentation.html at the code sample. It's outdated, afaik the docs don't work for kubebuilder 1.* but the section about documentation is still there.
Also, in `build/test.sh` there's a reference to `create resource`
