### ISSUE TITLE
[feature] exponential backoff

### ISSUE THREAD

**Issue by Huang-Wei** [kubernetes-sigs/kubebuilder#460]
/kind feature

Right now, kubebuilder supports re-enqueuing current `reconcile.Request`, with a fixed time duration:

```go
return reconcile.Result{Requeue: true, RequeueAfter: time.Second * 1}, nil
```

It would be sweet if exponential backoff can be provided, so that the re-enqueuing can happen in 1s, 2s, 4s, ... Until a condition is met and then aborted.

Similar implementation in k8s is sth. like this:

https://github.com/kubernetes/kubernetes/blob/1355e6b27713bbbdd3e5975e6fa815368f205c5d/staging/src/k8s.io/apimachinery/pkg/util/wait/wait.go#L192

**Comment by DirectXMan12** [comment]
For reference: `Requeue: true` already does this.
