### ISSUE TITLE
'Dep is not installed' error with dep in $PATH

### ISSUE THREAD

**Issue by geoffmore** [kubernetes-sigs/kubebuilder#471]
I tried following the kubebuilder getting started guide at https://book.kubebuilder.io/quick_start.html, but
kubebuilder incorrectly shows the error "Dep is not installed. Follow steps at: https://golang.github.io/dep/docs/installation.html". dep was installed via the curl-to-shell method at https://github.com/golang/dep
My environment is:
```
kubebuilder version: 1.0.5
dep version: 0.5.0
path to dep: ~/go/bin/dep
path to kubebuilder:  ~/.local/kubebuilder/bin/kubebuilder
os: Fedora 28 (Workstation Edition)
go version:  go1.10.4 linux/amd64
```
What's strange is that installing dep via the official dnf package ```dep.x86_64                             0.4.1-2.fc28``` allowed kubebuilder to function correctly. the dnf package installs dep at ```/usr/bin/dep```
My objective is to define this behaviour and add the dnf installation method to kubebuilder docs, if possible.

**Comment by BradfordMedeiros** [comment]
is ~/go/bin/dep on your path?
/usr/bin/dep almost undoubtedly would be, ~/go/bin/dep might not be, i don't know your system to tell for sure.

**Comment by DirectXMan12** [comment]
closing as per no follow-up
