### ISSUE TITLE
How to test if individual calls were made?

### ISSUE THREAD

**Issue by alvaroaleman** [kubernetes-sigs/kubebuilder#472]
The testing infrastructure generated by kubebuilder allows using an ephemeral test etcd+apiserserver, which has many advantages. What is not possible anymore thought is to test the individual calls which were made like it was possible with a `fakeClientset.Actions()`.

What is the suggested path going forward to be able to test this? Is this something that has been considered already?

**Comment by roberthbailey** [comment]
/cc @pwittrock @droot 

This is something that we lost during the apiserver-builder --> kubebuilder transition and we'd really like to have some way to recreate this functionality to enhance our testing.
