### ISSUE TITLE
Document how to represent time and dates in types.

### ISSUE THREAD

**Issue by erictune** [kubernetes-sigs/kubebuilder#476]
KRM convention for storing dates is to set`type: string` and `format: date` in the openAPI. 

For date-times it is to use `type: string` and `format: date-time`.

This is RFC3339, and you can refer this reference: https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md#data-types.

Suggest putting this in the KubeBuilder book.  I didn't find the terms `date-time` or `RFC3339` when searching the kubebuilder book.

**Comment by DirectXMan12** [comment]
We talk a bit about using `metav1.Time`, which does this for us.  We could do better with documenting it, but users shouldn't have to care about using RFC3339, etc since we have `metav1.Time` support in CT.

**Comment by camilamacedo86** [comment]
This shows another one nice to the FAQ section such as : 
- https://github.com/kubernetes-sigs/kubebuilder/issues/1723

**Comment by Sajiyah-Salat** [comment]
hello, why this issue is still open.

**Comment by camilamacedo86** [comment]
Hi @Sajiyah-Salat,

Did you find this info documented already?
If so, could you please add here the link for it?

If not, we need to address it via documentation.
The FAQ section shows a good place to do so.

**Comment by Sajiyah-Salat** [comment]
According to @DirectXMan12 we have metav1.Time we just need to document it. Can I get some resources from which I can get idea of what and how to add? I think this is a document issue. Thank you.

**Comment by ashutosh887** [comment]
@camilamacedo86 @varshaprasad96 
DO we still need to fix this or it can be closed now?

**Comment by Sajiyah-Salat** [comment]
Hello @camilamacedo86 I didnt find this info documented though. I would like to take this up?
https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.1.0.md#data-types
Should we add the whole datatype block in documentation or we should extract data on our own and tweak it. what say?
