### ISSUE TITLE
update doc and scaffold for optional fields

### ISSUE THREAD

**Issue by Liujingfang1** [kubernetes-sigs/kubebuilder#479]
We need to update the kubebuilder book for optional fields. Make sure that users add `omitempty` for that field.
We also need to update the scaffolding. When `omitempty` is seen on a field, add the // +optional as well to that field.

**Comment by erictune** [comment]
Users who read core types may see that they do:
```
type SomeCoreResource struct {
    metav1.TypeMeta
    // +optional
    metav1.ObjectMeta
```

whereas the KubeBuilder book does:

```
type ContainerSet struct {
    metav1.TypeMeta   `json:",inline"`
    metav1.ObjectMeta `json:"metadata,omitempty"`
```

In these examples, I think that `json: "omitempty"` and `//+optional mean the same thing.  But I wasn't sure.

I'm assuming the reason the core types don't need to say `json: "inline"` and `json:"metadata"` is that the core converters handle it magically?

**Comment by erictune** [comment]
Never mind last comment: I was looking at the internal type not the versioned type.

**Comment by zlcnju** [comment]
@Liujingfang1 As you describe, json: "omitempty" and `//+optional mean the same thing? However, there are difference  when we want to have different logic for an optional field which is not provided vs. provided with empty values to have different logic for an optional field which is not provided vs. provided with empty values.[Optional vs. Required](https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#optional-vs-required)

**Comment by angelotinho** [comment]
Say I have a struct `type ResourceDescription struct {
	CpuCount     int `json:"cpu_count,omitempty"`
	MemoryBytes  int `json:"memory_bytes,omitempty"`
	StorageBytes int `json:"storage_bytes,omitempty"`
	GpuCount     int `json:"gpu_count,omitempty"`
}
`
How do I mark some of the fields using annotations as optional? Should I also add +optional to the top of each field?

**Comment by DirectXMan12** [comment]
yes, adding `+optional` would mark them as non-required in the openapi.
