### ISSUE TITLE
kubernetes docs - coming soon

### ISSUE THREAD

**Issue by cmoulliard** [kubernetes-sigs/kubebuilder#483]
## Doc issue

The documentation of kubebuilder details how to document the [API](https://book.kubebuilder.io/beyond_basics/generating_documentation.html) but unfortunately the command is not yet available

```
kubebuilder version
Version: version.Version{KubeBuilderVersion:"master", KubernetesVendor:"1.11", GitCommit:"002c18b2eced18628703fe43f41de725daf78b4a", BuildDate:"2018-11-12T21:15:09Z", GoOs:"unknown", GoArch:"unknown"}
kubebuilder docs   
Coming soon.
```

See code of the command : https://github.com/kubernetes-sigs/kubebuilder/blob/master/cmd/docs.go#L30

**Comment by jimmidyson** [comment]
@pwittrock Any plans for this? What are your thoughts on how to implement this?

**Comment by fanzhangio** [comment]
I am going to implement this feature. 😄

**Comment by fanzhangio** [comment]
#530 

API document reference involves `create example` and `create resource` subcommand. Do we take these subcommand implementation into consideration with docs ?

@droot @pwittrock

**Comment by DirectXMan12** [comment]
see also https://github.com/ahmetb/gen-knative-api-reference-docs (basic docs that has a similar goal).  We probably want to make sure that we support usecases that it supports (simple to run, can generate markdown, can generate links to main Kubernetes docs, etc)

**Comment by DirectXMan12** [comment]
we probably want to move some of the agnostic parts to controller-tools
