### ISSUE TITLE
Could append task to Makefile what run a generate-groups.sh?

### ISSUE THREAD

**Issue by bells17** [kubernetes-sigs/kubebuilder#488]
Hi.  Could append task to Makefile what run a generate-groups.sh?
Because I created kubernetes operator with kubebuilder, but at first I didn't know generate-groups.sh command.
So I took a long time what investigate about kubernetes code generator.
I'm happy if add task to Makefile what run a generate-groups.sh.
I thought it would be nice if the following task were added to Makefile template:

```makefile
GROUP ?=
VERSION ?=

...

# Generate client code
genclient:
	./vendor/k8s.io/code-generator/generate-groups.sh all \
		{{ .Repo }}/pkg/client \
		{{ .Repo }}/pkg/apis \
		${GROUP}:${VERSION}
```

**Comment by droot** [comment]
@bells17 Thanks for sharing the instructions for generating client. 

Do you mind sharing reasons for using the generated client over the one provided by controller-runtime ?

**Comment by bells17** [comment]
@droot Thanks for the reply. And sorry, I hadn't understood about controller-runtime client...
I fixed my operator to use the one provided by controller-runtime as below:
https://github.com/bells17/common-network-policy-operator/pull/8
