### ISSUE TITLE
CRDs cannot watch other CRDs

### ISSUE THREAD

**Issue by gerred** [kubernetes-sigs/kubebuilder#491]
I have a controller that is managing the lifecycle of other CRDs. Given the following code:

```go
	err = c.Watch(&source.Kind{Type: &v1beta1.CustomResourceDefinition{}}, &handler.EnqueueRequestForOwner{
		IsController: true,
		OwnerType:    &maestrov1alpha1.Framework{},
	})
```

kubebuilder fails to register controllers for the manager with the following error:

```
{"level":"error","ts":1542781339.090334,"logger":"entrypoint","caller":"manager/main.go:63","msg":"unable to register controllers to the manager","error":"no kind is registered for the type v1beta1.CustomResourceDefinition","stacktrace":"github.com/kubernetes-sigs/kubebuilder-maestro/vendor/github.com/go-logr/zapr.(*zapLogger).Error\n\t/Users/gerred/go/src/github.com/kubernetes-sigs/kubebuilder-maestro/vendor/github.com/go-logr/zapr/zapr.go:128\nmain.main\n\t/Users/gerred/go/src/github.com/kubernetes-sigs/kubebuilder-maestro/cmd/manager/main.go:63\nruntime.main\n\t/usr/local/Cellar/go/1.11.2/libexec/src/runtime/proc.go:201"}
```

I tried updating controller-runtime to 0.1.7 and controller-tools to 0.1.6 by hand, this didn't seem to help. The stack trace was a little unhelpful. Any pointers in tracking this down would be greatly appreciated.

FWIW, I also could not use ReconcileFramework's client. I get the same error (albeit in a different way). I had to pull in apiextensionsclient by hand to use in the Reconcile step.

**Comment by gerred** [comment]
^ Also getting bit by PropagationPolicy here. Going to close, I think I can solve this from an implementation side in a cleaner way.

**Comment by zillani** [comment]
@DirectXMan12 hugs! thank you so much!!!
