### ISSUE TITLE
Support go modules

### ISSUE THREAD

**Issue by kuroneko25** [kubernetes-sigs/kubebuilder#506]
now that https://github.com/golang/go/wiki/Modules is a thing do we plan to switch from `dep` to go modules?

**Comment by droot** [comment]
`Go modules` do look promising, but still experimental in Go 1.11, we will wait for them to become stable and default in Go 1.12 before switching over.

**Comment by j-vizcaino** [comment]
FWIW `deepcopy-gen` seems to be facing issues generating files outside of `$GOPATH`: https://github.com/kubernetes/code-generator/issues/57

**Comment by easeway** [comment]
All my projects are using go modules today. I'm looking forward to the tools supporting go module ASAP. Otherwise, developing Kubernetes controllers will be a pain for me.

**Comment by ekarlso** [comment]
Really no idea on this one?

**Comment by DirectXMan12** [comment]
We need to fix our tooling issues (in progress) and make sure that Go modules properly work with the way we use transitive pinning.

**Comment by DirectXMan12** [comment]
> Really no idea on this one?

also, I'm not sure if this was your intent, but you kind-of ended up sounding snarky/exasperated, which is not a great way to contribute to a conversation here.  Prefer language like "what's left blocking this?" or "is there a timeline on addressing the blockers?" or even "how can I help with this?"

**Comment by birdayz** [comment]
i would also really love, if this could be addressed. i'm running a monorepo with gomodules, but i have to keep my operator in a separate repo :(

**Comment by andreykaipov** [comment]
I took a stab at moving Kubebuilder over to use Go modules. It's a pretty smooth transition, apart from some of the tooling breaking. The only one I had an issue with was https://sigs.k8s.io/controller-tools/cmd/controller-gen, and I think the fix for that to handle Go modules is tracked by https://github.com/kubernetes-sigs/controller-tools/issues/120.

**Comment by tangxusc** [comment]
现在golang 1.12 已经发布了,kubebuilder 在什么时候支持go module呢,有详细的计划吗? 现在一起使用kubebuilder和go module是非常难受的体验,我也将持续关注kubebuilder对于go module的支持,也感谢你们的奉献
Now that Golang 1.12 has been released, when will Kubebuilder support go module? Do you have a detailed plan? It's a very difficult experience to use Kubebuilder and go module together. I will continue to focus on Kubebuilder's support for go module and thank you for your dedication.

**Comment by DirectXMan12** [comment]
We've switch controller-tools over, we still need to fix deepcopy-gen (WIP as part of the controller-gen refactor), and we're working on switching CR over, but we wouldn't mind some help on the CR side.

**Comment by DirectXMan12** [comment]
closing as per v2 (which has native go modules support!)
