### ISSUE TITLE
kubebuilder what command

### ISSUE THREAD

**Issue by monopole** [kubernetes-sigs/kubebuilder#509]
I just came back to a kubebuilder managed project I haven't touched in months, and don't remember what all this stuff is and what steps i can take.

Would like to enter 
```
kubebuilder what
```
and get some kind of status
* list of files i wrote and what for (e.g. i have a config dir, with subdirs crds, default, manager, rbac, samples, and would like a reminder about kubectl apply order)
* list of files that are purely generated
* what i need to do to clean thoroughly, then create and push new images
* Are the images in cluster up to date with current state of code?

**Comment by DirectXMan12** [comment]
`man 7 kubebuilder-project` or similar might be useful here.
