### ISSUE TITLE
Generation doesn't work if GOPATH is unset

### ISSUE THREAD

**Issue by DirectXMan12** [kubernetes-sigs/kubebuilder#526]
Our code generation generation assumes `GOPATH` is set.  If `GOPATH` isn't set (i.e. the user is using the default of `~/go`), we'll generate at the wrong location, and fail to build.  We'll prob need to fix this in controller-tools, but I haven't had the chance to double check to make sure it's not something weird with how we're invoking controller-tools here instead.

Encountered this with a user today, and it's super-non-obvious when it happens.

cc @droot @mengqiy

**Comment by DirectXMan12** [comment]
cc @anthonydahanne

**Comment by fanzhangio** [comment]
If the `GOPATH` is not set particularly, or running `kubebuilder` in a different path other than `$GOPATH/src/<package>`, it will prompt the error message: 

```
$ kubebuilder init --domain k8s.io
2018/12/13 20:10:35 kubebuilder must be run from the project root under $GOPATH/src/<package>.
Current GOPATH=/root/go.
Current directory=/workspace/test-project
```

So user should either set up an `GOPATH` to align with current working directory or change the project to `default` path. I think we could add more illustration in the error message for this.

**Comment by DirectXMan12** [comment]
it seemed to work fine *if* running under `$GOPATH/src/<package>` when $GOPATH was unset (meaning `go env` showed a gopath of `~/go`, but `$GOPATH` was empty)

**Comment by easeway** [comment]
#506 Hope this will support go modules soon! Currently I have to opt-out kubebuilder as my projects are using go modules.

**Comment by DirectXMan12** [comment]
We now have gomodule support in v2.0.0 via scaffolding v2.  Closing.
