### ISSUE TITLE
Document the steps for registering external/vendor types

### ISSUE THREAD

**Issue by janetkuo** [kubernetes-sigs/kubebuilder#538]
@DirectXMan12

**Comment by DirectXMan12** [comment]
Those instructions need some cleaning-up -- you don't necessarily need an extra controller, for example

**Comment by davyodom** [comment]
It would be good to talk about dependency implications with these style approaches.  For example, I'm running into a lot of complexity when importing an external type declared in a project I don't own.  That project was using a different version of controller-runtime and even had other kubernetes overrides.  The only way I could get it to work was to match versions exactly and regen my kubebuilder project.  Would you recommend this approach in your docs, usage of the generic client instead, or something different altogether?

**Comment by DirectXMan12** [comment]
It's hard to say w/o specific knowledge, but if the kubernetes packages are technically compatible, it's often sufficient to use *overrides* (not constraints) in Gopkg.toml to convince them that they dependencies are ok.  If the kubernetes packages aren't compatible, then you're in for some issues.

**Comment by DirectXMan12** [comment]
actually, the cronjob tutorial talks about this.  closing for now
