### ISSUE TITLE
kubebuilder does not accept "Cat" as a valid Kind.

### ISSUE THREAD

**Issue by richardmarshall** [kubernetes-sigs/kubebuilder#539]
When creating an api type named `Cat` the `kubebuilder create api` sub-command rejects the name due to a failed camel case validation.

```
$ kubebuilder create api --group pets --version v1beta1 --kind Cat
Create Resource under pkg/apis [y/n]?
y
Create Controller under pkg/controller [y/n]?
y
Writing scaffold for you to edit...
pkg/apis/pets/v1beta1/cat_types.go
pkg/apis/pets/v1beta1/cat_types_test.go
2018/12/19 21:32:29 Kind must be camelcase (expected CAT was Cat)
$ echo $?
1
```

This seems to be due to the [inflect](https://github.com/markbates/inflect) package considering the word "cat" as an acronym and expecting the camelized version to be "CAT". I would consider this to be unexpected behavior as cats of the fluffy variety are more common on the internet than computerized axial tomography.

The newer replacement of the dependency [flect](https://github.com/gobuffalo/flect) does not behave in this way and could serve as a cat friendly replacement for the current package.

Thoughts on updating this dependency? Happy to submit a PR for this.

**Comment by BenTheElder** [comment]
+1, the repo description for https://github.com/markbates/inflect says:

> DEPRECATED: use github.com/gobuffalo/flect instead https://github.com/gobuffalo/flect

I took a quick stab at this, but ran into https://github.com/kubernetes-sigs/kubebuilder/issues/675#issuecomment-484281126

The code diff is pretty small, but vendor management is broken currently :(

https://github.com/kubernetes-sigs/kubebuilder/compare/master...BenTheElder:flect?expand=1

**Comment by mengqiy** [comment]
Closing this as dup of #784.
