### ISSUE TITLE
Make create resource copy create a controller struct that has InjectArguments instead of individual fields

### ISSUE THREAD

**Issue by pwittrock** [kubernetes-sigs/kubebuilder#54]
The created code would be simpler if it just uses the InjectArguments directly

**Comment by pwittrock** [comment]
@fanzhangio Re assigning to @lichuqiang since you have a few issues assigned to already

**Comment by lichuqiang** [comment]
Trying to address the issue

**Comment by pwittrock** [comment]
Closing this for now
