### ISSUE TITLE
Field Selector spec.nodeName does not work

### ISSUE THREAD

**Issue by mohnishkodnani** [kubernetes-sigs/kubebuilder#547]
```
fieldSelector := "spec.nodeName=minikube"
listOptions := &client.ListOptions{}
    if fieldSelector != "" {
        listOptions.SetFieldSelector(fieldSelector)
    }
    listOptions.Namespace = namespace
    podList := &corev1.PodList{}
    err := r.List(context.TODO(), listOptions, podList)
```

This returns the error 

```Index with name field:spec.nodeName does not exist```

I tried to trace through and see the following in cachedReader.

The indexName = field:spec.nodeName and indexKey = <ns>/minikube

In thread_safe_store.go

```func (c *threadSafeMap) ByIndex(indexName, indexKey string) ([]interface{}, error) {
	c.lock.RLock()
	defer c.lock.RUnlock()

	indexFunc := c.indexers[indexName]
	if indexFunc == nil {
		return nil, fmt.Errorf("Index with name %s does not exist", indexName)
	}
```

I see that the index is only on the namespace. How do i fix this or get around so that the index exists for the fields ?

**Comment by coderanger** [comment]
The only index created by default is on `namespace`. While you can manually add additional indexers to the same cache, it is likely easier to use an uncached client for those specific requests.

**Comment by mcristina422** [comment]
Following the logic in the book https://book.kubebuilder.io/cronjob-tutorial/controller-implementation.html#setup

Add this to your `SetupWithManager`
```golang
if err := mgr.GetFieldIndexer().IndexField(&corev1.Pod{}, "spec.nodeName", func(rawObj runtime.Object) []string {
		pod := rawObj.(*corev1.Pod)
		return []string{pod.Spec.NodeName}
	}); err != nil {
		return err
	}
```

**Comment by hbqhzx** [comment]
error: Index with name field:involvedObject.name does not exist

support controller-time‘s client get definite pod event
`_ = mgr.GetFieldIndexer().IndexField(context.Background(), &corev1.Event{}, "involvedObject.name", func(rawObj runtime.Object) []string {
		event := rawObj.(*corev1.Event)
		return []string{event.InvolvedObject.Name}
	})

fieldSelector, err := fields.ParseSelector("involvedObject.name" + "=" + "zx-demo-8658bdb788-65h8c")
if err != nil {
	fmt.Println(err.Error())
}
if err := mgr.GetClient().List(context.Background(), &events, client.MatchingFieldsSelector{fieldSelector}); err != nil {
	fmt.Println(err.Error())
}`

**Comment by hbqhzx** [comment]
error: Index with name field:involvedObject.name does not exist
support controller-time‘s client get definite pod event

```
_ = mgr.GetFieldIndexer().IndexField(context.Background(), &corev1.Event{}, "involvedObject.name", func(rawObj runtime.Object) []string {
event := rawObj.(*corev1.Event)
return []string{event.InvolvedObject.Name}
})

fieldSelector, err := fields.ParseSelector("involvedObject.name" + "=" + "zx-demo-8658bdb788-65h8c")
if err != nil {
fmt.Println(err.Error())
}
if err := mgr.GetClient().List(context.Background(), &events, client.MatchingFieldsSelector{fieldSelector}); err != nil {
fmt.Println(err.Error())
}
```
