### ISSUE TITLE
No way to get event recorder instance

### ISSUE THREAD

**Issue by narayanasamyr** [kubernetes-sigs/kubebuilder#549]
I could see Recorder instance set for sigs.k8s.io/controller-runtime/pkg/internal/controller in "sigs.k8s.io/controller-runtime/pkg/controller"  'New' method, 
But there is no way to use that recorder instance in my controller because 'sigs.k8s.io/controller-runtime/pkg/internal/controller' is internal package which I could not import in my controller

Even though the recorder set for controller through New method, I have to call manager.GetRecorder() again from my controller to get the recorder instance

**Comment by DirectXMan12** [comment]
closing as per the above answer

**Comment by akanso** [comment]
this link is dead: https://book.kubebuilder.io/beyond_basics/creating_events.html

but here's an example of creating events:

first in your project directory, go to  `/controllers/yourKind_controller.go` and add the `recorder` to your `Reconciler` struct:

```go
type AssessmentReconciler struct {
	client.Client
	Log      logr.Logger
	Scheme   *runtime.Scheme
	recorder record.EventRecorder
}
```

in the `SetupWithManager` method, make sure to set the `recorder`

```go
// SetupWithManager acts of the types we control/monitor
func (r *AssessmentReconciler) SetupWithManager(mgr ctrl.Manager) error {

        // add this line
	r.recorder = mgr.GetEventRecorderFor("Assessment")

	return ctrl.NewControllerManagedBy(mgr).
		For(&auditv1alpha1.Assessment{}).
		Complete(r)
}
```

then, to create events use:

```go
	r.recorder.Event(&assessment, core.EventTypeNormal, "Updated", "Updated assessment")
```

where `core` and `record` are:

```go
import (
core "k8s.io/api/core/v1"
"k8s.io/client-go/tools/record"

)
```

make sure to replace `Assessment` with `YourKind`

**Comment by dgkanatsios** [comment]
this is need as well, on top of your Reconcile method
```
//+kubebuilder:rbac:groups="",resources=events,verbs=create;patch
```

**Comment by adyanth** [comment]
This is the sole documentation available for creating Events. Spent quite a while getting here from https://github.com/kubernetes-sigs/kubebuilder/issues/1659. Linking for better visibility.
