### ISSUE TITLE
generate swagger.json from CRD

### ISSUE THREAD

**Issue by runzexia** [kubernetes-sigs/kubebuilder#559]
Hi I want to ask about the 1.0 roadmap related to the kubebuilder docs function?
At v0.x, it seems to support kubebuilder docs. Currently, the related functions of v0.x version are no longer available, but v1.0 version does not provide this function.

I want to generate swagger.json from CRD and finally generate multi k8s language's client.
What should I do for my needs? Can you give me some advice?

**Comment by runzexia** [comment]
https://github.com/kubeflow-incubator/genspec
https://github.com/kubeflow-incubator/gen
Some useful examples

**Comment by runzexia** [comment]
I did some experiments and it seems that there are some problems. kubeflow uses the 1.9/1.10 version of apimachinery, while controller-runtime and controller-tools use 1.12.x and 1.13.x apimachinery, which are not compatible.

**Comment by camilamacedo86** [comment]
HI @zhucan, @[runzexia](https://github.com/runzexia)

Could you please clarify why you re-open this one?
Also, I am not sure if I can follow properly the question raised here.  

> I want to generate swagger.json from CRD and finally generate multi k8s language's client.
> What should I do for my needs? Can you give me some advice?

What relation it would have with Kubebuilder? 
What do you mean with multi k8s language's client?
What is the problem that are you trying to solve

**Comment by zhucan** [comment]
@camilamacedo86 Hello, kubebuilder can generate swagger.json from crd?
