### ISSUE TITLE
Add ability to install via homebrew

### ISSUE THREAD

**Issue by maguro** [kubernetes-sigs/kubebuilder#562]
It would be nice if Homebrew could be used to install kubebuilder.

**Comment by yashbhutwala** [comment]
Any updates on this?

**Comment by stevemcquaid** [comment]
@yashbhutwala & @maguro - waiting on this to merge: https://github.com/Homebrew/homebrew-cask/pull/63639

👍 would be appreciated if you are able!

**Comment by halfcrazy** [comment]
ref https://github.com/Homebrew/homebrew-core/pull/40186

**Comment by DirectXMan12** [comment]
closing as per the above
