### ISSUE TITLE
Unable to access book.kubebuilder.io via chrome

### ISSUE THREAD

**Issue by runzexia** [kubernetes-sigs/kubebuilder#565]
![image](https://user-images.githubusercontent.com/31230341/51011145-4a737580-1592-11e9-8df9-ba231fe907d4.png)

**Comment by droot** [comment]
Are you still running in to this issue ? because I am able to access `https` on chrome just fine. It might be broken last week because we were switching kubebuilder book hosting, but it should be stable now.

**Comment by droot** [comment]
cc @mengqiy

**Comment by mengqiy** [comment]
That happened for a few hours during the migration.
I'm aware of that issue.
It should have be fixed last week :)
@runzexia Let know if you still see something strange.

**Comment by runzexia** [comment]
No problem now.
