### ISSUE TITLE
Documentation for generated informers is wrong

### ISSUE THREAD

**Issue by yanniszark** [kubernetes-sigs/kubebuilder#568]
According to the documentation, adding a generated informer to the manager is done with:

```go
err := mgr.Add(manager.RunnableFunc(func(s <-chan struct{}) error {
    generatedInformers.Start(s)
    return nil
}))
```

However, that code will result in the manager immediately exiting. This is because `generatedInformers.Start` returns immediately. To work correctly we must block on the stop channel:

```go
err := mgr.Add(manager.RunnableFunc(func(s <-chan struct{}) error {
    generatedInformers.Start(s)
    // Block on the stop channel
    <-s
    return nil
}))
```

Many thanks to @DirectXMan12 for figuring that one out, I spent a day looking for the cause.
I have reproduced the bug in this repo: https://github.com/yanniszark/kubebuilder-generated-informers-bug
To run, just do:
 ```bash
git clone https://github.com/yanniszark/kubebuilder-generated-informers-bug.git
make install && make run
```

**Comment by jimmidyson** [comment]
Thank you @yanniszark for opening this issue - saved me some time figuring out what the issue was!
