### ISSUE TITLE
Documentation for installing kubebuilder might be outdated?

### ISSUE THREAD

**Issue by verult** [kubernetes-sigs/kubebuilder#570]
I followed the instructions here:
https://book.kubebuilder.io/getting_started/installation_and_setup.html

but running kubebuilder leads to these errors:
```
kubebuilder must be run from the project root under $GOPATH/src/<package>. 
Current GOPATH=[my gopath]
Current directory=[my current directory]
```

**Comment by droot** [comment]
@verult can you share the complete output ? `Current GOPATH` and `Current Directory` ? because kubebuilder expects to be run in a directory under subtree rooted at GOPATH.

**Comment by aviweit** [comment]
Hello, I just encountered same issue. After following https://book.kubebuilder.io/getting_started/installation_and_setup.html
I can not invoke any kubebuilder sub-command. I can not see setting GOPATH being mentioned in the documentation.

```
$ kubebuilder version
2019/03/13 16:49:31 kubebuilder must be run from the project root under $GOPATH/src/<package>.
Current GOPATH=/home/weit/go.
Current directory=/home/weit
```

**Comment by aweis89** [comment]
Same issue here:
```
kubebuilder init --domain k8s.io --license apache2 --owner "The Kubernetes Authors"
2019/04/18 13:28:51 kubebuilder must be run from the project root under $GOPATH/src/<package>.
Current GOPATH=/Users/aaron/go.
Current directory=/Users/aaron/go/test
```

**Comment by DirectXMan12** [comment]
Should be fixed as of kb v2.  let us know if there's still an issue.

**Comment by abrennan89** [comment]
@DirectXMan12 I'm having this same issue when I try to run the `download-binaries` script. See output below.

# versions:
#   kubectl:        Client Version: v1.13.1
#   kubebuilder:    2019/06/28 18:48:57 kubebuilder must be run from the project root under $GOPATH/src/<package>. 
Current GOPATH=/root/go.  
Current directory=/home/abrennan
Error downloading assets

**Comment by DirectXMan12** [comment]
which version of kubebuilder are you using?

**Comment by huangyajie-Git** [comment]
Im having the same issue ~My version is 1.0.8 , I also install the Go , Do you have some solutions?

> [root@localhost go]# kubebuilder init
> 2020/06/05 21:23:49 kubebuilder must be run from the project root under $GOPATH/src/<package>. 
> Current GOPATH=/root/go.  
> Current directory=/usr/local/go
