### ISSUE TITLE
Support custom templates

### ISSUE THREAD

**Issue by j-vizcaino** [kubernetes-sigs/kubebuilder#585]
I'd like to be able to provide templates for API and controller code generation.
It seems the templates are hardcoded and there's no way to provide those from the command-line.

**Comment by droot** [comment]
Can you share more context about the use-case ?

**Comment by j-vizcaino** [comment]
Sure! Sorry about the lack of details.

I bootstrapped a manager using Kubebuilder and it gave me everything needed to start hacking: code for API type and its associated controller. Pleasant experience.

Now, in the same project, I need to bootstrap other API types and associated controllers but those need to leverage common logic and interfaces my generic engine provides. As a result, the default templates no longer match what my new API types and controller need to implement.

Out of what Kubebuilder currently generates, I would estimate 50% of the source code still being valid for my use-case while the other part needing further manual editing.

I could very well use a simple template engine for my use-case but I would really like to keep on using Kubebuilder for the API type and controller bootstrapping as it gives a nice and unified dev experience.

**Comment by droot** [comment]
Thanks for sharing the context.

**Comment by teddyking** [comment]
I'd like to add a +1 for this. The specific use case I have in mind is to allow for custom test files to be generated.

**Comment by DirectXMan12** [comment]
/remove-lifecycle stale

we'll want this eventually

**Comment by DirectXMan12** [comment]
we're working on a plugin system (see #943), so stay tuned.
