### ISSUE TITLE
Convert scaffolding to use new builder

### ISSUE THREAD

**Issue by DirectXMan12** [kubernetes-sigs/kubebuilder#588]
controller-runtime has a nice builder pattern that simplifies a lot of the common cases, and is sufficiently expressive as to capture most cases.  This dramatically simplifies setting up (and reading) controller initialization and watch initialization code, so we should make use of it.

**Comment by cizixs** [comment]
Is there any document or link to the new builder? And what features it provides?

**Comment by gaocegege** [comment]
@cizixs I think the doc is here https://godoc.org/github.com/kubernetes-sigs/controller-runtime/pkg/builder

**Comment by DirectXMan12** [comment]
There's also a [design doc](https://github.com/kubernetes-sigs/kubebuilder/blob/master/designs/simplified-scaffolding.md) in the designs/ folder the root of the repo
