### ISSUE TITLE
Documentation for Finalizers does not return error

### ISSUE THREAD

**Issue by weters** [kubernetes-sigs/kubebuilder#590]
In the [using_finalizers.md](https://github.com/kubernetes-sigs/kubebuilder/blame/master/docs/book/beyond_basics/using_finalizers.md#L42) page of the kubebuilder book, the example returns a nil error when an error occurs.

I think it should be the following instead since they both should requeue the request, but actually returning an error when an error occurs seems like it's the more correct solution.

```
                        if err := r.Update(context.Background(), instance); err != nil {
-                               return reconcile.Result{Requeue: true}, nil
+                               return reconcile.Result{}, err
                        }
```

**Comment by droot** [comment]
The PR is merged, so closing this.

**Comment by justinsb** [comment]
/close

(I presume)
