### ISSUE TITLE
Create watch on other CRDS

### ISSUE THREAD

**Issue by jakesjohn** [kubernetes-sigs/kubebuilder#594]
I am new to Kubebuilder and it looks very interesting in developing CRDs. I was going through the docs. In https://book.kubebuilder.io/beyond_basics/controller_watches.html, it describes the apis to create a watch on a existing resource. 
My use case is slightly different. I am trying to use kubebuilder to implement a CRD C1.  I have to create a watch on another CRD C2 in order to take actions on its events . The problem is that C2 might not be available during the init of C1 but may be installed at a later time by the user.  If I create a watch on C2 before it is created, watch fails.   How can I create a watch dynamically on C2 whenever it  is installed by the user?  What is the recommended way to handle this situation? 
 Just to highlight, user can add/delete C2 at any time and it is independent of the life cycle of C1.

**Comment by jakesjohn** [comment]
Any help?

**Comment by Ghostbaby** [comment]
you can use this package "k8s.io/client-go/dynamic" .

**Comment by Adirio** [comment]
\triage support
Jake that sounds like a really bad design. You should not have a controller watching for a resource of a kind that still doesn't exist. The resource should exist, even if no instance of it is created. Think of a `ReplicaSet` that is watching `Pod`s. If `Pod` API was not defined that wopuld make no sense at all. That does NOT mean that you need to have the instance of those resources created before the controllers are set up. First apply your CRDs, then launch the controllers and at last instantiate as many resources from those CRDs as you want.

**Comment by jakesjohn** [comment]
@Adirio I get the idea what you are saying. However,  there are situations where user does not need C2 at all. In such a case, user will prefer not to install C2.  Since C2 and C1 are totally independent(and separate entities),  user can't be forced to install C2 if he is not interested in using it.  So, ReplicaSet-Pod is not the right example matching my use case.  You can assume that C2 is a extra feature provided to the user if he wants it.

**Comment by Adirio** [comment]
Jakes I really suggest you to reconsider your design. I can not offer more help as you are not providing any information about the real use case. You can see kubernetes resources as a type in a strongly-typed language. You can not refer to a type that does not exist.

**Comment by DirectXMan12** [comment]
more concretely -- if the resource doesn't exist yet, we can't look up kind <--> resource information to know how to watch it.  You could always add the watch later, though

**Comment by dean7474** [comment]
@DirectXMan12 How can we add a watch later?
