### ISSUE TITLE
Vendor directory contains non-go files

### ISSUE THREAD

**Issue by teddyking** [kubernetes-sigs/kubebuilder#596]
When generating a new project using `kubebuilder init` we noticed that our vendor directory was quite large at 133mb and contained a lot of unnecessary files, e.g. some large PDFs:

```
$ find . -name *.pdf | xargs -n1 du -h
 11M    ./vendor/github.com/petar/GoLLRB/doc/Sedgewick-Talk-Penn2008.pdf
804K    ./vendor/github.com/petar/GoLLRB/doc/Sedgewick-LLRB.pdf
```

So we decided to modify `Gopkg.toml` to ignore these:

```
[prune]
  go-tests = true
  non-go = true
```

After which the size of the vendor dir dropped to 86mb. The tests still pass and the binary can still be built and generation can still occur. Is there any reason not to do this by default? Happy to submit a PR if you think that'd be useful.

We also tried to use `unused-packages = true` however this caused `kubebuilder create api` to fail. Could we be more explicit on the dependencies required for generation and ignore the rest of the unused packages?

Thanks,
Ed & @samze

**Comment by DirectXMan12** [comment]
yep, need to clean some stuff up.  It on my list of tasks to generally audit our Gopkg.toml files, but I'd be happy to take a PR with `non-go = true` as long as we're sure that it doesn't break anything.

**Comment by DirectXMan12** [comment]
We're not using vendor anymore with scaffolding v2, so I think we can close this.
