### ISSUE TITLE
Use of NotTo(gomega.HaveOccurred()) in generated tests is confusing

### ISSUE THREAD

**Issue by michaelbannister** [kubernetes-sigs/kubebuilder#598]
I am quite new to Go and it took me a while to understand the generated tests' use of `NotTo(gomega.HaveOccurred())`. For example:
```go
// Delete the Deployment and expect Reconcile to be called for Deployment deletion
g.Expect(c.Delete(context.TODO(), deploy)).NotTo(gomega.HaveOccurred())
```
Eventually I worked out that this was the same as
```go
g.Expect(c.Delete(context.TODO(), deploy)).To(gomega.Succeed())
```
I think this reads more obviously in the case where the `g.Expect()` is not obviously acting on an `error`.
Whereas this example is obviously the right use:
```go
g.Expect(err).NotTo(gomega.HaveOccurred())
```

I'd be happy to have a go at submitting a PR for this if maintainers agree. Or if there's some subtle difference I'm missing, I'd be glad to have it explained!

**Comment by Samze** [comment]
We actually thought the same and fixed it, but just hadn't gotten around to submitting the PR. We just opened #599 to address this.
