### ISSUE TITLE
CRD apiGroup option

### ISSUE THREAD

**Issue by lluunn** [kubernetes-sigs/kubebuilder#604]
We want to create a CRD with spec:
```
apiVersion: kubeflow.org/v1alpha1
kind: Notebook
```

However, IIUC we can't achieve this with kubebuilder now because
- kubebuilder defines an "Org" in PROJECT file, default to k8s.io
- when creating api, we specify a Group
- and then apiGroup will be Org.Group

The group name will be the dir name under pkg/apis, so we chose "notebook". Our org is "kubeflow.org". So the generated CRD is:
```
apiVersion: notebook.kubeflow.org/v1alpha1
kind: Notebook
```

Is there any way to generate the CRD so that apiGroup is "kubeflow.org"?

Thanks!

**Comment by Adirio** [comment]
TLDR: no

You should not use `"notebook"` as your group name. It is the resource kind not the group name. You should find a group name that you feel confortable with and use that (e.g. `"machinelearning"`).

**Comment by lluunn** [comment]
I know notebook should not be the group name.

But the problem is, we want the apiGroup to be "kubeflow.org", and there is no way to achieve that.

**Comment by Adirio** [comment]
As said, the short answer is: no, it can not be done.

Some nice group names you may consider are:
- `api.kubeflow.org`: this is my favorite.
- `resources.kubeflow.org`: similar to the previous, but I like better the former.
- `machine-learning.kubeflow.org`: according to your webpage that is what you do. Any variations replacing the `-` by a `.` or just removing it could also be nice.

**Comment by jschlichtholz** [comment]
Leaving a warning here: `api` will not work as a group name. It seems to confuse the CRD generation (it replaces `api` with the version leaving you with something like `alphav1.example.com` as a group name).

**Comment by DirectXMan12** [comment]
@jschlichtholz that sounds like a bug that we need to fix.

P.S. This should now be doable with controller-tools -- it'll take a bit of manual editing, but it should work fine.
