### ISSUE TITLE
Proposal: add remote debug capability to generated makefile, dockerfile, and yaml

### ISSUE THREAD

**Issue by alegacy** [kubernetes-sigs/kubebuilder#610]
In the course of using Kubebuilder to build a set of custom controllers I needed to debug several issues in my containerized development environment.  To reduce the iteration time required to add logs, build an image, push, restart my pods, etc I used remote debugging using Delve (https://github.com/go-delve/delve).   To do this I had to make some relatively minor modifications to the Makefile, Dockerfile, and yaml generated by Kubebuilder.    I was able to debug my application using the debug capabilities in my IDE (GoLand).  

I opened this issue to see whether there would be any interest in me updating Kubebuilder to modify the generated Makefile, Dockerfile, and yaml in order to make remote debugging available to others out-of-the-box.  If so, I can open move my custom changes into Kubebuilder's scaffolding without too much trouble.

**Comment by droot** [comment]
@alegacy this definitely sounds useful. Can you pl. share the changes (or point to the project if public) to understand what it looks like ?

**Comment by alegacy** [comment]
@droot give me a day or two and i will submit a PR.

**Comment by alegacy** [comment]
@droot  i pushed a commit to my own fork to show how this can be done.   I only changed the test/project scaffolding as a shortcut rather than waste time writing the actual scaffolding code.  I can do that there is consensus on how to setup remote debug.  The approach that I have taken works for me but I am open to suggestions.   

My usage of this is as follows:

```bash
DEBUG=yes IMG=127.0.0.1:5000/alegacy/my-controller:debug make docker-push
```

https://github.com/alegacy/kubebuilder/commit/8323901f1b823362d4582d9dfbed3338bd62e23b

**Comment by droot** [comment]
Thanks. I will take a look (today looks difficult, so early next week, will definitely have feedback).

**Comment by alegacy** [comment]
Perfect.  Thanks.

**Comment by alegacy** [comment]
@droot  Not sure if you have had time to have a look yet, but over the course of last week I realized that I could optimize the Dockerfile layout a little so that the dlv debugger does need to be rebuilt on each docker build.  I pushed a new commit into that same repo rather than a force push because I didn't want to lose the comments I added to the commit in case you had not seen them yet.

**Comment by alegacy** [comment]
@droot fyi... my private repo has been updated with some enhancements from using this extensively during the past months.  

https://github.com/alegacy/kubebuilder/commits/issue610

**Comment by DirectXMan12** [comment]
Ooh, this looks neat.  Sorry about having not had a chance to take a look -- so much to do, so little time :-/

**Comment by alegacy** [comment]
I have decided to abandon the idea of trying to fit this into the automatic scaffolding.  I converted our project to use a helm chart to package up the yaml and parameterized controlling whether remote debugging is enabled or not via a helm override.   If anyone finds this thread and is trying to enable remote debugging for their application they can have a look at the helm chart definition at:

https://github.com/Wind-River/titanium-deployment-manager/tree/master/helm/titanium-deployment-manager

**Comment by guettli** [comment]
> I have decided to abandon the idea of trying to fit this into the automatic scaffolding. I converted our project to use a helm chart to package up the yaml and parameterized controlling whether remote debugging is enabled or not via a helm override. If anyone finds this thread and is trying to enable remote debugging for their application they can have a look at the helm chart definition at:
> 
> https://github.com/Wind-River/titanium-deployment-manager/tree/master/helm/titanium-deployment-manager

@alegacy the link is broken. I am interested in learning how to debug controllers.

**Comment by alegacy** [comment]
@guettli 

I no longer work for that company, but it looks like the directory that was referenced was renamed.  If you navigate to the parent directory you’ll see the new directory name.  

helm/wind-river-cloud-platform-deployment-manager
