### ISSUE TITLE
Kubebuilder support for controller flags / command line arguments

### ISSUE THREAD

**Issue by eytan-avisror** [kubernetes-sigs/kubebuilder#611]
I am trying to find a way to pass command line flags to my generated controller, is there an established pattern for doing so without making too many changes to scaffolded code?

My use case is very simple, I would like to mount a config map on the controller as part of the installation, and pass a command line flag that provides that path to the controller so that it can load it (prefer to not hardcode that path) - this is a standard pattern in kubernetes controllers - as well as passing other flags that make sense for your controller.

Is there some way to do this with kubebuilder?
from what I can see, `main.go` (manager) does not provide an straightforward way to pass flags to my generated controller/reconciler code.

**Comment by DirectXMan12** [comment]
this is a known issue with the current scaffolded code.  we're working to change the scaffolding to provide a simpler model that's more amenable to this usecase.

**Comment by eytan-avisror** [comment]
Thanks guys, is there a different issue for this feature that I should track? or can I track this issue?

**Comment by DirectXMan12** [comment]
https://github.com/kubernetes-sigs/kubebuilder/issues/588 is the base issue, and I'll make sure everything gets linked in there.

**Comment by gaocegege** [comment]
Hi, is there any progress? We are looking forward to the awesome feature! Is there anything I can do to help you?

**Comment by DirectXMan12** [comment]
We've got work in process, but it'll take a bit to overhaul our generation system so that we don't break existing users.

cc @droot

**Comment by droot** [comment]
@gaocegege This is still in progress https://github.com/kubernetes-sigs/kubebuilder/pull/632. You can refer to to the [simplified scaffolding design ](https://github.com/kubernetes-sigs/kubebuilder/pull/632), it will give you an overall idea about the approach.

**Comment by gaocegege** [comment]
Thanks, I will take a look! :tada:

**Comment by droot** [comment]
Closing this since 2.0.0 includes new scaffolding structure which makes it easy to setup reconciler. 
/cc @gaocegege

**Comment by gaocegege** [comment]
Thanks, I tried the new scaffolding and it works for me.

**Comment by CamelCaseNotation** [comment]
@droot or @gaocegege can y'all point me to an example where I can provide flags to my controller like the OP mentioned?

**Comment by albrechtsimon** [comment]
In my project I just used go flags like this:

**Comment by gaocegege** [comment]
@CamelCaseNotation You can define flags like https://github.com/gaocegege/ray-operator/blob/master/main.go#L50 and use them in your reconcile initialization.
