### ISSUE TITLE
Define how to express uri and email forms (Renamed)

### ISSUE THREAD

**Issue by mattfarina** [kubernetes-sigs/kubebuilder#62]
Is there a way to specify validation for things just as email and URL/URI?

**Comment by pwittrock** [comment]
@mattfarina Good question.  This is all done through the openAPI v3 validation supported by CRDs. Do you know what the CRD validation supports?  I may need to add an extra hook.

I am not totally clear from this document about what validation is supported by openAPI v3: https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md.  It mentions uuid and email as formats but says they are undefined by the spec.

If nothing else, you may be able to use "Pattern".

**Comment by mattfarina** [comment]
@pwittrock Two things...

1. How do I specify a custom data type such as email? What's the right annotation? https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md#data-types
2. What's the right annotation to set the pattern?

**Comment by pwittrock** [comment]
@mattfarina

1. This may not be supported today, but should be possible to add with relatively little work if the CRD validation supports this use case.

2. Sorry about this.  I'll update the [godoc documentation](https://godoc.org/github.com/kubernetes-sigs/kubebuilder/pkg/gen/apis) to include Pattern and the other supported types.  For now this should work.  *Remember to run kubebuilder generate* afterward.

> // +kubebuilder:validation:Pattern=^[a-z]+$

**Comment by mattfarina** [comment]
@pwittrock Thanks. You can consider my question answered. I'll leave this open in case you want to keep it open until you've updated the godocs. Or, you can close it if not.
