### ISSUE TITLE
Need a way to set OpenAPIv3 type property

### ISSUE THREAD

**Issue by admilazz** [kubernetes-sigs/kubebuilder#623]
I have a spec struct that includes the following field:

    VolumeSize resource.Quantity `json:"volumeSize"`

This is emitted with `type: object` in the CRD, but resource.Quantity has a JSON marshaler and is intended to be represented as a string in JSON. This causes erroneous validation failures.

My current workaround is to manually edit the CRD after running `make install` and run `kubectl apply -f config/crds/` again, but it's a pain and is not sustainable.

I suggest allowing us to override the type field, perhaps like this:

    // +kubebuilder:validation:Type=string
    VolumeSize resource.Quantity `json:"volumeSize"`

**Comment by DirectXMan12** [comment]
this was fixed a while ago (both fixing the specific case of `resource.Quantity` and the general case of the `Type` marker)
