### ISSUE TITLE
Add e2e test framework SDK for users' controller

### ISSUE THREAD

**Issue by magicsong** [kubernetes-sigs/kubebuilder#625]
Most wanted features:
1. dynamic client to CURD kubernetes resources and CRs
2. controller/CRD install/autoclean
3. integrated with `kubectl` 
3. Useful shortcuts like get pod log, `kubectl`command output

**Comment by magicsong** [comment]
cc @mengqiy

**Comment by DirectXMan12** [comment]
> dynamic client to CURD kubernetes resources and CRs

controller-runtime's client does this

> controller/CRD install/autoclean

 envtest does this, and we've been discussing getting similar working with kind (cc @mengqiy )

> integrated with kubectl
> Useful shortcuts like get pod log, kubectlcommand output

unclear as to what you mean by this

**Comment by gaocegege** [comment]
I am using kubebuilder 2.0.0 (controller-runtime actually) + kind to run e2e tests for some controllers.

You can enable this with 

```
	testEnv = &envtest.Environment{
		UseExistingCluster: true,
		CRDDirectoryPaths:  []string{filepath.Join("..", "config", "crd", "bases")},
	}
```

And set the KUBECONFIG to `$(kind get kubeconfig-path --name="kind")`

**Comment by magicsong** [comment]
find what i want. https://github.com/operator-framework/operator-sdk/blob/master/doc/test-framework/writing-e2e-tests.md

**Comment by gaocegege** [comment]
@magicsong I think using `UseExistingCluster`, we can implement the similar test cases just as operator-sdk does.

**Comment by magicsong** [comment]
@gaocegege mostly but not all. I cannot test the built-in metric server using `UseExistingCluster`. The tests provided by kubebuilder is much like `intergration testing` other than `e2e-testing`.

**Comment by DirectXMan12** [comment]
closing in favor of #882
