### ISSUE TITLE
Cannot access kubebuilder-tools tarball

### ISSUE THREAD

**Issue by paulfantom** [kubernetes-sigs/kubebuilder#626]
According to CONTRIBUTING.md developer should run `./test.sh` to test changes. However this script fails due to permissions issue on kubebuilder-tools GCS bucket. 

```
$ ./test.sh
preparing staging dir
fetching tools

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
```

```
$ curl https://storage.googleapis.com/kubebuilder-tools/kubebuilder-tools-1.13.1-linux-amd64.tar.gz
<?xml version='1.0' encoding='UTF-8'?><Error><Code>AccessDenied</Code><Message>Access denied.</Message><Details>Anonymous caller does not have storage.objects.get access to kubebuilder-tools/kubebuilder-tools-1.13.1-linux-amd64.tar.gz.</Details></Error>
```

Steps to reproduce:
1. Clone repo
2. Run `./test.sh`

**Comment by DirectXMan12** [comment]
Fixed.  Sorry about that -- we switched over some of the permissions to allow listing objects in the bucket, and the direct object read permissions got lost in the process somehow.  Should be fixed now.
