### ISSUE TITLE
Building this repo is unclear

### ISSUE THREAD

**Issue by BradfordMedeiros** [kubernetes-sigs/kubebuilder#633]
In contributing.md it says  you can simply run 
~~~~
go build -o /output/path/kubebuilder ./cmd
~~~~
to build kubebuilder. 

My immediate output is 
~~~~
# command-line-arguments
cmd/main.go:58:3: undefined: newInitProjectCmd
cmd/main.go:59:3: undefined: newAPICommand
cmd/main.go:61:3: undefined: newDocsCmd
cmd/main.go:62:3: undefined: newVendorUpdateCmd
cmd/main.go:63:3: undefined: newAlphaCommand
~~~~

I've found go always finicky in this area, but given the dependencies, the use of dep alongside bazel, it's really not super obvious how to do this or what the proper way of building this repo is. 

Could this be standardized on a single command.
For example, in the past I've standard on a single top-level make build, or maybe just documented. 

Also, I'm seeing dependencies on go, dep, i see bazel in here, etcd.   There's a whole set of implicit dependencies in this project.  I don't say it shouldn't have these, but I do wonder if we should include a docker file in this or some way to get guaranteed behavior.

**Comment by prometherion** [comment]
@BradfordMedeiros I totally agree, also because I'm trying to build it on my own to solve an issue with generation of cluster-scoped CRD.

After cloned the repo I proceed with the build overwriting the binary provided by the release:

```bash
go build -a -o /usr/local/kubebuilder/bin/kubebuilder ./cmd
```

I added the flag `-a` to get _everything_ built.

**Comment by DirectXMan12** [comment]
I'm unable to reproduce your issue with building -- `go build -o kubebuilder ./cmd` worked fine for me.  That should be all you need to actually build the project.  We should add a note about how to use dep (like we have in controller-runtime), but with any luck, that'll be replaced by Go modules in a few weeks.

Beyond the strange failure of `go build` (can you clarify OS, go version, etc), is there some specific thing that was confusing to you?
