### ISSUE TITLE
Scaffolded controller test needs fixing

### ISSUE THREAD

**Issue by janetkuo** [kubernetes-sigs/kubebuilder#639]
The scaffolded controller test has several issues:

* It uses cached client `mgr.GetClient()` instead of a client that directly reads from apiserver. 
https://github.com/kubernetes-sigs/kubebuilder/blob/e904181797467ca55eeaa9ddaf80e25b2a571aa3/pkg/scaffold/controller/controllertest.go#L106
* ~Expect reconcile doesn't really do anything -- it should be removed. We only need to check some condition to happen, instead of a reconcile.~ Updated: Allow users to test a condition to eventually happen without having to expect Reconcile to happen first.
https://github.com/kubernetes-sigs/kubebuilder/blob/e904181797467ca55eeaa9ddaf80e25b2a571aa3/pkg/scaffold/controller/controllertest.go#L128
* Logger should be set in TestMain
https://github.com/kubernetes-sigs/kubebuilder/blob/e904181797467ca55eeaa9ddaf80e25b2a571aa3/pkg/scaffold/controller/controllersuitetest.go#L67
* It doesn't use `ginkgo`.

@DirectXMan12

**Comment by Ready305** [comment]
Ready

**Comment by janetkuo** [comment]
Actually, we cannot remove the "expect reconcile" part, because the scaffolded test reconciler writes requests to a request channel:
https://github.com/kubernetes-sigs/kubebuilder/blob/e904181797467ca55eeaa9ddaf80e25b2a571aa3/pkg/scaffold/controller/controllersuitetest.go#L83-L93

This will cause problems when Reconcile loop fails and requeues. While writing tests, we don't know whether the Reconcile will return an error or not; for example, we cannot expect an object's status to be updated after a single Reconcile -- it may eventually happen, but just not at the first Reconcile. 

It's possible to write tests to workaround this issue, by making sure Reconcile never fails in the test, but that's pretty limiting and makes tests less robust. 

cc @mengqiy @droot

**Comment by cizixs** [comment]
To overcome cached client issue, I added several `time.Sleep` statement for now. I wonder if there is a non-cached client for `mgr`?

@janetkuo @DirectXMan12

**Comment by mengqiy** [comment]
> I wonder if there is a non-cached client for mgr?

@cizixs It is supported. Please check https://github.com/kubernetes-sigs/controller-runtime/pull/327.

**Comment by DirectXMan12** [comment]
We no longer scaffold controller tests at the moment.  Closing this, we'll keep it in mind as we add those back in.
