### ISSUE TITLE
[feature request] leader selection

### ISSUE THREAD

**Issue by ZYecho** [kubernetes-sigs/kubebuilder#640]
is there a plan for supporting leader selection?
related to #230

**Comment by DirectXMan12** [comment]
please address all functionality requests that don't deal with scaffolding to either controller-runtime (for runtime stuff like this) or controller-tools (for CRD YAML generation).  FWIW, support for leader election merged into CR a while ago -- just use the most recent version of CR.

**Comment by cizixs** [comment]
@ZYecho leader election is already supported by this PR: https://github.com/kubernetes-sigs/controller-runtime/pull/118.

@DirectXMan12 Maybe we should add how to use election election in document?
