### ISSUE TITLE
support group change

### ISSUE THREAD

**Issue by crimsonfaith91** [kubernetes-sigs/kubebuilder#643]
If a user specifies the group as `a.example.com` and later wishes to change to `b.example.com`, s/he has to create the second group and move the codes accordingly. Ideally, we should support "group replacement" feature.

@droot

**Comment by DirectXMan12** [comment]
I'm not sure we'll ever actually "fix" this.  It's just a matter of editing `PROJECT` and `groupversion_info.go` though.

**Comment by DirectXMan12** [comment]
(the reason being that editing existing code is *really* tricky, and easy to get wrong)
