### ISSUE TITLE
upgrading kube-builder

### ISSUE THREAD

**Issue by itaysk** [kubernetes-sigs/kubebuilder#650]
Is there an upgrade story for kube-builder? the gitbook talks about updating dependencies, but much of what kube-builder is is what's being scaffolded.
I don't know threre's a good colution for this but at least document changes so that people can manually apply.

**Comment by DirectXMan12** [comment]
it's not particularly intended that people update their scaffolding (the scaffolding is one-time setup, or is supposed to be), but when we do the scaffolding v2 release, we'll be providing migration instructions if you want to move over to the simplified format.

Does that answer your question?

**Comment by itaysk** [comment]
I asked this question because the scaffolding did in fact change over time and I had an issue that was fixed and I had to dig through issues and commit diffs to find how to manually apply the changes. Are changes to the scaffold such rare? (I mean, you guys know better then me, I'm just sharing from my experience)

**Comment by DirectXMan12** [comment]
Scaffolding changes should be relatively rare, and it's not intended that we change scaffolding without reving the version if it's a breaking change.  I'm curious as to which change you had to apply manually.

**Comment by itaysk** [comment]
This is one issue that I remember of: https://github.com/kubernetes-sigs/kubebuilder/issues/595

**Comment by DirectXMan12** [comment]
ah, yeah... we don't really have a good story for dealing with that right now, unfortunately.  I'm certainly open to suggestions though.

**Comment by DirectXMan12** [comment]
We've got a section for migration in the docs now.  I don't foresee scaffolding changes being automatic, so closing for now.
