### ISSUE TITLE
Generated SetupTestReconcile should write to requests channel before calling inner reconcile

### ISSUE THREAD

**Issue by Samze** [kubernetes-sigs/kubebuilder#651]
Currently the generated test helper SetupTestReconciler function records calls to reconcile on the requests channel only after the inner reconcile is called. We expected it to write to the channel immediately and then call the inner reconcile - this way seems more appropriate since it is recording requests to reconcile. Is there a reason it is this way around?

We found this odd behaviour when we wrote tests that did assertions on reconcile calls with a slow inner reconcile loop.

We expected this:
```
func SetupTestReconcile(inner reconcile.Reconciler) (reconcile.Reconciler, chan reconcile.Request) {
	requests := make(chan reconcile.Request)
	fn := reconcile.Func(func(req reconcile.Request) (reconcile.Result, error) {
		result, err := inner.Reconcile(req)
		requests <- req
		return result, err
	})
	return fn, requests
}
```

To be this:
```
func SetupTestReconcile(inner reconcile.Reconciler) (reconcile.Reconciler, chan reconcile.Request) {
	requests := make(chan reconcile.Request)
	fn := reconcile.Func(func(req reconcile.Request) (reconcile.Result, error) {
		requests <- req
		result, err := inner.Reconcile(req)
		return result, err
	})
	return fn, requests
}
```

Cheers,
Sam & @teddyking

**Comment by DirectXMan12** [comment]
We're considering dropping this entirely from our new test scaffolding, because it causes all sorts of weird issues, and prevents you from easily writing multi-iteration setups (e.g. ones where you use requeue to re-rerun on purpose). see #639

**Comment by DirectXMan12** [comment]
closing, we've dropped this in v2.
