### ISSUE TITLE
kubebuilder init creates structure incompatible with kustomize

### ISSUE THREAD

**Issue by danielorf** [kubernetes-sigs/kubebuilder#654]
When running `kubebuilder init`, a project structure is created which places the kustomization.yaml file in the 'config/default' folder which refers to other yaml files in 'config/rbac' and 'config/manager'.  This is now a problem because in kustomize v2, kustomization.yaml can only refer to files in the same directory or in subdirectories (see more details [here](https://github.com/kubernetes-sigs/kustomize/issues/776#issuecomment-461459130)).

This problem cropped up when working through the [tutorial](https://book.kubebuilder.io/basics/project_creation_and_structure.html) and running the following command:   `make deploy`.  This resulted in the following error:
```
Error: rawResources failed to read Resources: Load from path /rbac/rbac_role.yaml failed: security; file '/rbac/rbac_role.yaml' is not in or below '/Users/dorf/go/src/dorf/config/default'

error: no objects passed to apply
```

I temporarily resolved it by moving 'config/rbac' and 'config/manager' to 'config/default' and changing the paths in kustomization.yaml to refer to the new location (e.g. `./rbac/rbac_role.yaml` instead of `../rbac/rbac_role.yaml`).

**Comment by DirectXMan12** [comment]
cc @mengqiy presumably the new kustomize structure (#644) fixes this?

/kind bug
/priority important-soon

**Comment by mengqiy** [comment]
This issue should already fixed on HEAD by https://github.com/kubernetes-sigs/kubebuilder/pull/614.

**Comment by DirectXMan12** [comment]
closing as per the referenced issue
