### ISSUE TITLE
Get a 0-length response in CI

### ISSUE THREAD

**Issue by magicsong** [kubernetes-sigs/kubebuilder#655]
In my CI enviroment , there is a chance  I got a 0-length response from the integrated apiserver. For example<https://travis-ci.com/kubesphere/porter/builds/106467451>. After searching, i found the it was fixed in https://github.com/kubernetes/kubernetes/pull/72856. How do i upgrade the kubebuilder `apiserver` ?

**Comment by DirectXMan12** [comment]
We'll do a release of the bundled tools.

cc @mengqiy

**Comment by mengqiy** [comment]
https://github.com/kubernetes-sigs/kubebuilder/issues/686 should help with this issue.

**Comment by droot** [comment]
We release 2.0.0-alpha.1 recently that has k8s 1.14. Upgrade to new release should fix this issue, so closing it.

**Comment by marccampbell** [comment]
Are there instructions to upgrade an existing 1.x kubebuilder project to 2?

**Comment by mengqiy** [comment]
> Are there instructions to upgrade an existing 1.x kubebuilder project to 2?

We are actively working on the documents.
You can expect an upgrade|migration guide when we release the stable version of v2 for controller-runtime, controller-tools and kubebuilder.
