### ISSUE TITLE
Update controller-runtime to use client.Patch

### ISSUE THREAD

**Issue by pytimer** [kubernetes-sigs/kubebuilder#656]
I use `kubebuilder` to create a controller to manage CRD, i want to use `r.Patch()` in controller `Reconcile` function, but i found the `controller-runtime` version is `v0.1.1`, it does not have `Patch` function. 

The latest controller-runtime already implement Patch method, https://github.com/kubernetes-sigs/controller-runtime/pull/235.
I want to ask, how to do if i want use the latest controller-runtime?

I already run `dep ensure -v --update sigs.k8s.io/controller-runtime sigs.k8s.io/controller-tools`, but it still `v0.1.1` version.

### kubebuilder version

```sh
$ kubebuilder version
Version: version.Version{KubeBuilderVersion:"1.0.8", KubernetesVendor:"1.13.1", GitCommit:"1adf50ed107f5042d7472ba5ab50d5e1d357169d", BuildDate:"2019-01-25T23:14:29Z", GoOs:"unknown", GoArch:"unknown"}
```

**Comment by DirectXMan12** [comment]
Set your controller-runtime to the appropriate version in `Gopkg.toml` (in this case, you'd need to use `branch="master"`  since that commit hasn't been released yet.

**Comment by DirectXMan12** [comment]
(closing for now, feel free to comment if you have more questions)

**Comment by pytimer** [comment]
Thanks for you reply. I change controller-runtime use the master branch, it's ok.
