### ISSUE TITLE
Failed to run `kubebuilder init` with `undefined: SYS_CLOCK_GETTIME`

### ISSUE THREAD

**Issue by shotarohorai** [kubernetes-sigs/kubebuilder#658]
The latest change of one of the dependent libraries, `golang/sys`, might have a bad influence on `kubebuilder init` (also `kubebuilder create api`). I did succeed in running `kubebuilder init` yesterday (before the commit of `golang/sys` was made).
https://github.com/golang/sys/commit/e4093980e83e70784fc393a93d5620e2654097f0#diff-08c4f775ef2d1d06670dc2f2414bee96R687

Here is the output when I run the command with an error `undefined: SYS_CLOCK_GETTIME`.
```
$ kubebuilder init --domain xx.xx --license apache2 --owner "xxx"
Run `dep ensure` to fetch dependencies (Recommended) [y/n]?
y
dep ensure
Running make...
make
go generate ./pkg/... ./cmd/...
go fmt ./pkg/... ./cmd/...
go vet ./pkg/... ./cmd/...
# xxx/xxx/redis-operator/vendor/golang.org/x/sys/unix
vendor/golang.org/x/sys/unix/zsyscall_darwin_amd64.1_11.go:687:22: undefined: SYS_CLOCK_GETTIME
make: *** [vet] Error 2
2019/04/02 17:38:59 exit status 2
```

My environment:
- OS 
Mac Sierra Version 10.12.6

- Kubebuilder 
```
Version: version.Version{KubeBuilderVersion:"1.0.8", KubernetesVendor:"1.13.1", GitCommit:"1adf50ed107f5042d7472ba5ab50d5e1d357169d", BuildDate:"2019-01-25T23:14:29Z", GoOs:"unknown", GoArch:"unknown"}
```
- Go
```
go version go1.11 darwin/amd64
```

**Comment by shotarohorai** [comment]
It is passed when I switched go version into `go1.12.1 darwin/amd64`.

**Comment by DirectXMan12** [comment]
(closing as per the above comment)
