### ISSUE TITLE
Kubebuilder default log print to stderr, can we use other logger implementation which can log rolling ?

### ISSUE THREAD

**Issue by guanchao-yang** [kubernetes-sigs/kubebuilder#666]
Now, default log is 

```
flag.Parse()
	logf.SetLogger(logf.ZapLogger(false))
	log := logf.Log.WithName("entrypoint")
```

can only print to stderr, can use other logger implementation which can log rolling？

**Comment by mengqiy** [comment]
`logf.ZapLogger(false)` is our default logger implementation.
You can definitely plugin your own logger implementation as long as it implements the interface https://github.com/go-logr/logr/blob/master/logr.go#L119-L151

```
myAwesomeLogger := AwesomeLogger{} // your implementation.
logf.SetLogger(myAwesomeLogger)
log := logf.Log.WithName("entrypoint")
```

**Comment by guanchao-yang** [comment]
@mengqiy Thanks very much . 

Do you have some best practice using log  logger implementation in kubebuilder ?

**Comment by mengqiy** [comment]
https://github.com/kubernetes-sigs/controller-runtime/blob/8c0b8057b44f906d55d0e61f06e633d00eed73c4/TMP-LOGGING.md talks about why we use structured logging in kubebuilder by default.
One way you can try with minimum efforts is
- use kubebuilder's default logger
- redirect stdout and stderr to a file
- use another tool to rotate the logs

**Comment by guanchao-yang** [comment]
@mengqiy  OK, Thanks

**Comment by DirectXMan12** [comment]
closing as per the question being answered
