### ISSUE TITLE
Create NameSpace Before Resource Creation

### ISSUE THREAD

**Issue by angelotinho** [kubernetes-sigs/kubebuilder#669]
/kind question

Is it possible to create a namespace before the reconcile functions starts? I want to create a different namespace for each instance of a CRD that I create. kubebuilder currently expects a crd in some namespace prior to checking the state.

**Comment by DirectXMan12** [comment]
huh?  Can you clarify a bit what the issue is here or what you're trying to do, if you're still encountering the issue?

**Comment by DirectXMan12** [comment]
closing with no response
