### ISSUE TITLE
How to contribute with new vendored archives?

### ISSUE THREAD

**Issue by prometherion** [kubernetes-sigs/kubebuilder#671]
/kind bug

Few hours ago has been released this new [commit](https://github.com/kubernetes-sigs/kubebuilder/commit/5dbed55124f5efdff779888f63f379f2b0bd6395) that prevents me to just run `dep ensure` to test the package.

I tried to follow the `CONTRIBUTING.md` file, installing `gir-lfs` and untarring archives in the `test/project` and `test/project_v2` folders but even after this, dep cannot solve dependencies probably due to multiple conflicting dependencies.

The unique way to make it works has been to get rid of `test/project_v2` folder and the `ensure` both in the top level repository and in the scaffolded project.

**Comment by droot** [comment]
>prevents me to just run dep ensure to test the package. 

which package are your trying to test in this case ? 

which directory are your running `dep ensure` in ?

**Comment by droot** [comment]
If this is about generating new vendor archive, I added `generate_vendor.sh` script to do so.

**Comment by prometherion** [comment]
I'm going to close the issue: pulling `master@22344ac4ac1926ecb4083f31c1e6d51717da367b` solved the issue.
