### ISSUE TITLE
quickstart fails during go vet step

### ISSUE THREAD

**Issue by alejandrox1** [kubernetes-sigs/kubebuilder#675]
So i'm on a mac trying to go through the [quickstart](https://book.kubebuilder.io/quick_start.html).
I installed kubebuilder following the instructions but I get the following error during `kubebuilder init`:
```
$ kubebuilder init --domain k8s.io --license apache2 --owner "The Kubernetes Authors"
Run `dep ensure` to fetch dependencies (Recommended) [y/n]?
y
dep ensure
Solving failure: package k8s.io/client-go/kubernetes/typed/admissionregistration/v1alpha1 does not exist within project k8s.io/client-go
2019/04/17 17:48:45 exit status 1
```

Then I cloned the client-go repo to `$GOPAHT/src/k8s.io/` and tried again, only this time I got:
```
$ kubebuilder init --domain k8s.io --license apache2 --owner "The Kubernetes Authors"
Run `dep ensure` to fetch dependencies (Recommended) [y/n]?
y
dep ensure
Running make...
make
go generate ./pkg/... ./cmd/...
go fmt ./pkg/... ./cmd/...
go vet ./pkg/... ./cmd/...
# k8s.io/client-go/rest
../../../../../pkg/mod/k8s.io/client-go@v11.0.0+incompatible/rest/request.go:598:31: not enough arguments in call to watch.NewStreamWatcher
	have (*versioned.Decoder)
	want (watch.Decoder, watch.Reporter)
make: *** [vet] Error 2
2019/04/17 17:52:50 exit status 2
```

/kind bug

**Comment by BenTheElder** [comment]
note that `dep ensure` does not appear to work even in this repo currently :disappointed:

**Comment by alejandrox1** [comment]
so after spending an entire day figuring out the dependency graph between code-generator, client-go, apimachinery, etc. etc. I think the solution for this is to disable go modules. Otherwise, it seems like the dep ensure step is trying to pick up the dependencies from client-so's latest release (v11.0). Which I guess makes sense /shrug

@BenTheElder do you have go modules enabled as well?

**Comment by BenTheElder** [comment]
`export GO111MODULE="off"`made not difference. I didn't think dep was aware of this.

**Comment by mengqiy** [comment]
It appears the `dep` doesn't always work well.
We are actively working on enable `go modules` for all 3 kubebuilder repos.

**Comment by runyontr** [comment]
I had this issue and was able to fix with with go-modules by having my `go.mod` file contain:

```
go 1.12

replace (
	k8s.io/api => k8s.io/api v0.0.0-20190222213804-5cb15d344471
	k8s.io/apiextensions-apiserver => k8s.io/apiextensions-apiserver v0.0.0-20190221221350-bfb440be4b87
	k8s.io/apimachinery => k8s.io/apimachinery v0.0.0-20190221213512-86fb29eff628
	k8s.io/client-go => k8s.io/client-go v10.0.0+incompatible
)
```

**Comment by kevingimbel** [comment]
Came here from getting a similar issue when trying to build the kubernetes client-go examples (https://github.com/kubernetes/client-go/blob/master/examples/in-cluster-client-configuration/main.go).

The version from @runyontr work for me!

**Comment by DirectXMan12** [comment]
Can people confirm that v2 with native go module support works fine?

**Comment by gmlp** [comment]
@runyontr solves client go issue but I'm getting this error now:
vendor/sigs.k8s.io/controller-tools/cmd/controller-gen/main.go:170:8: undefined: webhook.ManifestOptions.

**Comment by DirectXMan12** [comment]
@gmlp which version of kubebuilder are you using? Which scaffolding version?

**Comment by gmlp** [comment]
Hi @DirectXMan12 , I'm using this setup:
go version go1.12.5 darwin/amd64
KubeBuilderVersion:"2.0.0-alpha.2
KustomizeVersion:v2.0.4-kubebuilder-special-edition
dep version     : v0.5.3
Scaffolding version: 1

**Comment by DirectXMan12** [comment]
@gmlp scaffolding version 1 doesn't support go modules

**Comment by jsravn** [comment]
I'm hitting this error when trying to use kubebuilder 2.1.0 on a fresh project.  Is it supposed to work on a fresh project (empty `go.mod`)?

I tried doing
```
require (
k8s.io/api kubernetes-1.15.3
k8s.io/apimachinery kubernetes-1.15.3
k8s.io/client-go kubernetes-1.15.3
)
```

which seems to allow it to compile but not sure this is the correct approach.

**Comment by DirectXMan12** [comment]
Make sure you have the latest version of KB, and then it should work on an empty go.mod file.

**Comment by jsravn** [comment]
I had to blow away `go/pkg/mod`, then it worked. I don't understand go modules well enough to know why this worked though.

**Comment by DirectXMan12** [comment]
huh.  That's like the universal package manager trick: "when in doubt, clear the package cache".
