### ISSUE TITLE
Resource named `test` breaks codegen

### ISSUE THREAD

**Issue by pbarker** [kubernetes-sigs/kubebuilder#680]
/kind bug

Hey we recently we're trying to use kubebuilder for our project and we have a resource named `Test`, however when we generate out the API for that we get files named `add_test.go` and such that are then mistaken as go test files.

**Comment by droot** [comment]
This is interesting, never saw that was coming :) This will get fixed with the new scaffolding structure.

**Comment by pbarker** [comment]
thank you!

**Comment by DirectXMan12** [comment]
closing -- it should be fixed in scaffolding v2
