### ISSUE TITLE
v1.book.kubebuilder.io errors with 404: not found

### ISSUE THREAD

**Issue by sethp-nr** [kubernetes-sigs/kubebuilder#699]
I went to follow the link at the top of the introduction for the v1 book, and it took me to https://v1.book.kubebuilder.io/, which produced a "Not found" 404 response.

Looking at #698, I discovered https://book-v1.book.kubebuilder.io/ which seems to be the v1 book content. None of the urls I tried seemed to redirect me from `v1` to `book-v1`, though.

/kind bug

**Comment by droot** [comment]
Docs have been updated to point to https://book-v1.book.kubebuilder.io/
