### ISSUE TITLE
Figure out canonical story for CRD generation from goidl

### ISSUE THREAD

**Issue by pwittrock** [kubernetes-sigs/kubebuilder#70]
The team working on apply is running into this same issue.  We should work together to make sure we solve it once in a canonical fashion.  Lets work with the folks building CRDs to come up with a design doc for the canonical way to generate CRDs from goidl.

- How to reference core API types without inlining / generating them
- How to deal with recursive types / self-referencing types (e.g. type has a field which is a pointer to itself)
- How to declare validation and format (already exists, but make sure this is the canonical way)
- How to declare openapi extensions and which extensions exist
- ???

**Comment by Liujingfang1** [comment]
A related feature request https://github.com/kubernetes/kubernetes/issues/54579
