### ISSUE TITLE
Quickstart installation fails (no v2.0.0)

### ISSUE THREAD

**Issue by ekuefler** [kubernetes-sigs/kubebuilder#700]
The quickstart at https://book.kubebuilder.io/quick-start.html fails when installing kubebuilder. This seems to be because it suggests installing v2.0.0, but the latest released version on github is 1.0.8: https://github.com/kubernetes-sigs/kubebuilder/releases

/kind bug

**Comment by DirectXMan12** [comment]
fixed by #710
