### ISSUE TITLE
Emoji checker in Prow

### ISSUE THREAD

**Issue by DirectXMan12** [kubernetes-sigs/kubebuilder#712]
The Prow maintainers for the k8s org seem to be amenable to an emoji checker bot, so we should write one that makes sure PRs have an appropriate emoji in the title for release notes, as per the versioning docs

**Comment by DirectXMan12** [comment]
currently getting by with GH actions (but that broke a couple of days ago), but we're still interested in this.

/remove-lifecycle stale
/lifecycle frozen

**Comment by camilamacedo86** [comment]
done in : https://github.com/kubernetes-sigs/kubebuilder/pull/1704
