### ISSUE TITLE
Create api command references removed pkg directory in v2

### ISSUE THREAD

**Issue by abursavich** [kubernetes-sigs/kubebuilder#717]
The `create api` command asks users if they would like to create resources and controllers under the `pkg` directory, which seems to have been removed in the v2 structure.  Not that big of a deal, but it was confusing.

```
$ kubebuilder create api --version v1alpha1 --group foo --kind Bar
Create Resource under pkg/apis [y/n]?
y
Create Controller under pkg/controller [y/n]?
y
Writing scaffold for you to edit...
api/v1alpha1/bar_types.go
controllers/bar_controller.go
```

/kind bug

**Comment by nirnanaaa** [comment]
can i start working on this? wanted to get started contributed and this seems like a pretty low hanging fruit to me?
