### ISSUE TITLE
Awesome Kubebuilder

### ISSUE THREAD

**Issue by luxas** [kubernetes-sigs/kubebuilder#724]
As per contrib summit, cc @DirectXMan12 
/kind feature

**Comment by droot** [comment]
@luxas Can you pl. add more info to understand what is needed to be done ?

**Comment by luxas** [comment]
Add a list of projects using Kubebuilder, e.g. in the readme

**Comment by gaocegege** [comment]
We are using kubebuilder in [kubeflow/katib](https://github.com/kubeflow/katib/) and some other projects in [Kubeflow](https://github.com/kubeflow). Glad to list projects in Kubeflow using kubebuilder in the README.
