### ISSUE TITLE
Implement k8s conversion fuzzing and testing libraries.

### ISSUE THREAD

**Issue by luxas** [kubernetes-sigs/kubebuilder#725]
This kind of stuff will soon be around in k8s.io/component-base ref: https://github.com/kubernetes/kubernetes/pull/75689
/kind feature

**Comment by DirectXMan12** [comment]
This should be migrated to an issue in controller-runtime, moving there.

**Comment by DirectXMan12** [comment]
closing in favor of kubernetes-sigs/controller-runtime#456
