### ISSUE TITLE
main.go should be updated when creating another CRD with existing Group Kind

### ISSUE THREAD

**Issue by mengqiy** [kubernetes-sigs/kubebuilder#740]
Steps to reproduce:
- kubebuilder init --project-version 2 --domain testproject.org --license apache2 --owner "The Kubernetes authors"
- kubebuilder create api --group crew --version v1 --kind Captain --controller=true --resource=true --make=false
- kubebuilder create api --group crew --version v2 --kind Captain --controller=false --resource=true --make=false

We get
```
import (
       ...
	crewv1 "sigs.k8s.io/play-kubebuilder/api/v1"
	// +kubebuilder:scaffold:imports
)
...
func init() {

	crewv1.AddToScheme(scheme)
	// +kubebuilder:scaffold:scheme
}
```

`crewv2` should be there as well.

/kind bug

**Comment by droot** [comment]
This will be fixed by https://github.com/kubernetes-sigs/kubebuilder/pull/744
