### ISSUE TITLE
Non-namespaced resource CRD gets generated as scope: Namespaced

### ISSUE THREAD

**Issue by akrausesap** [kubernetes-sigs/kubebuilder#741]
/kind bug

 #322 Unfortunately I have the same issue as 322 with `KubeBuilderVersion:"2.0.0-alpha.2"`. Neither `// +genclient:nonNamespaced` nor `kubebuilder create api --group bigthicket --kind EphemeralEnvironment --namespaced false --version v1alpha1`or  `--namespaced=false` generated non-namespaced CRD. 

Please help

**Comment by mengqiy** [comment]
@akrausesap You need to use `// +kubebuilder:resource:path=ephemeralEnvironments,scope=Cluster`.

Your `types.go` should look like:
```
// +kubebuilder:object:root=true
// +kubebuilder:resource:path=ephemeralEnvironments,scope=Cluster

type EphemeralEnvironment struct {
    ...
}
```

**Comment by mengqiy** [comment]
This is a documentation issue that our v2 doc doesn't cover every features yet.

**Comment by DirectXMan12** [comment]
It's actually(not a doc bug, I believe -- we need to update `--namespaced` to emit the `scope` argument to `// +kubebuilder:resource`.

**Comment by DirectXMan12** [comment]
https://github.com/kubernetes-sigs/kubebuilder/pull/763 was handling it, but I think is on hold a bit.

**Comment by akrausesap** [comment]
Manually adding `scope=Cluster` does not work. unfortunately I an error for: 

```
// +kubebuilder:object:root=true
// +kubebuilder:resource:path=connectorInstances,scope=Cluster
// +kubebuilder:subresource:status
type ConnectorInstance struct {
```
```
/.../api/v1/connectorinstance_types.go:71:1: unknown argument "scope"
/.../api/v1/connectorinstance_types.go:71:1: extra arguments provided: "Cluster"
```
Do you suggest upgrading from 2.0.0-alpha.2 would fix this?

**Comment by mengqiy** [comment]
I was using controller-tools [v0.2.0-beta.2](https://github.com/kubernetes-sigs/controller-tools/releases/tag/v0.2.0-beta.2)  and it works for me.
So please try to upgrade it. You can remove the `controller-gen` binary and then run `go get sigs.k8s.io/controller-tools/cmd/controller-gen@v0.2.0-beta.2`.

**Comment by akrausesap** [comment]
thanks @mengqiy, this gets me one step further. First failure is that I need to write // `+kubebuilder:resource:path=connectorinstances,scope=Cluster`with small caps instances (otherwise the test fails (` ../controllers/suite_test.go:60`)):

```
CustomResourceDefinition.apiextensions.k8s.io "connectorInstances.openconnectors.incubator.kyma-project.io" is invalid: [metadata.name: Invalid value: "connectorInstances.openconnectors.incubator.kyma-project.io": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*'), spec.names.plural: Invalid value: "connectorInstances": a DNS-1035 label must consist of lower case alphanumeric characters or '-', start with an alphabetic character, and end with an alphanumeric character (e.g. 'my-name',  or 'abc-123', regex used for validation is '[a-z]([-a-z0-9]*[a-z0-9])?')]
  occurred
``` 

After doing that `../openconnectors/api/v1/connectorinstance_types_test.go:67`fails: 
[Fail] ConnectorInstance Create API [It] should create an object successfully 

Do you know why?

**Comment by droot** [comment]
This PR https://github.com/kubernetes-sigs/kubebuilder/pull/864 fixes it, so closing it.

**Comment by kvaps** [comment]
Just faced with this issue, I found that I had mistake in setting comments, I added two separate comments, while they should be specified inline:

```
-//+kubebuilder:resource:scope=Cluster
-//+kubebuilder:resource:shortName={"cvmi","cvmimage","cvmimages"}
+//+kubebuilder:resource:scope=Cluster,shortName={"cvmi","cvmimage","cvmimages"}
```
