### ISSUE TITLE
Undefined: controllers

### ISSUE THREAD

**Issue by GTB3NW** [kubernetes-sigs/kubebuilder#742]
/kind bug

```bash
$ kubebuilder version
Version: version.Version{KubeBuilderVersion:"2.0.0-alpha.2", KubernetesVendor:"1.14.1", GitCommit:"22344ac4ac1926ecb4083f31c1e6d51717da367b", BuildDate:"2019-05-23T20:31:12Z", GoOs:"unknown", GoArch:"unknown"}
```
`go mod init gitlab.com/Foo/Bar/example.git`
`kubebuilder init --domain crd.example.io`
`kubebuilder create api --group example --version v1 --kind Example`

An error should generate:

```
# gitlab.com/Foo/Bar/example.git [gitlab.com/Foo/Bar/example.git.test]
./main.go:54:10: undefined: controllers
make: *** [Makefile:40: vet] Error 2
```

Resolution:

Add import

```
$ grep -n controllers main.go
23:	"gitlab.com/Foo/Bar/example.git/controllers"
55:	err = (&controllers.ExampleReconciler{
```

Footnote:

It just looks like the import is missing. Presumably a straight forward fix. I'm surprised this wasn't caught in an E2E test?

**Comment by DirectXMan12** [comment]
hmm... I wonder if that's a `goimports` bug?  I sounds like it.  Need to poke around a bit.

**Comment by DirectXMan12** [comment]
does this happen for every module, or just one?  I've successfully run this workflow and it's worked fine.

**Comment by GTB3NW** [comment]
> does this happen for every module, or just one? I've successfully run this workflow and it's worked fine.

It's a bit late here so I'll do some test tomorrow most likely. I'm not too familiar with the way the file is generated, useful to know goimports is what adds the imports, I would have thought it was generated code. Thanks for taking a look so far :)

**Comment by Deepakkothandan** [comment]
@GTB3NW  @DirectXMan12  I had the same problem as above and Inited a new kubebuilder project inside my gopath. 

Starting from scratch again inside my gopath with `GO111MODULE=on` set to on, the above import issue did not occur.

**Comment by DirectXMan12** [comment]
hmm, @Deepakkothandan was that with a v2 scaffolding project?  v2 scaffolding requires go modules

**Comment by Deepakkothandan** [comment]
@DirectXMan12 yes that was v2 scaffolding.  The bug report above also states v2 .

**Comment by DirectXMan12** [comment]
> The bug report above also states v2 .

Sorry, triaging too fast.  If it's cause by having `GO111MODULE` on vs off, it's probably a bug with goimports removing or adding things because it can't find something
