### ISSUE TITLE
kubebuilder adds redundant rules to config/rbac/role.yaml

### ISSUE THREAD

**Issue by ekuefler** [kubernetes-sigs/kubebuilder#743]
If I have several controllers that operate on the same resource, I'm likely to have the same or similar `kubebuilder:rbac:groups` annotations in each controller. When I run the code generator, it puts one item in the rules in `config/rbac/role.yaml` for each such annotation, which leads to a lot of redundant rules in this file.

I think the right thing to do here is to take a union of the verbs for each apiGroup/resource to ensure that each apiGroup/resource pair appears only once.

/kind bug

**Comment by haiyanmeng** [comment]
I will take a look at this.
