### ISSUE TITLE
Generated makefiles should run `go env GOBIN` instead of assuming `$GOPATH/bin`

### ISSUE THREAD

**Issue by DirectXMan12** [kubernetes-sigs/kubebuilder#746]
The generated Makefile assumes compiled binaries from `go get` end up in `$GOPATH/bin`, but if you've overridden `$GOBIN`, they could end up elsewhere.  We should run `go env GOBIN` instead.

/good-first-issue
/kind bug

**Comment by nirnanaaa** [comment]
`GOBIN` might be empty. Should we use `GOPATH/bin` as a default if `GOBIN` is not set?

**Comment by DirectXMan12** [comment]
yeah, that seems reasonable.  I'm kinda surprised that `go env GOBIN` doesn't do that step for us.

**Comment by nirnanaaa** [comment]
any reason not to use which in any case and get rid of gopath entirely, like so:

```Make
ifeq (, $(shell which controller-gen))
	go get sigs.k8s.io/controller-tools/cmd/controller-gen@v0.2.0-beta.1
endif
CONTROLLER_GEN=$(shell which controller-gen)
```

**Comment by DirectXMan12** [comment]
that's a good suggestion :-)  PRs welcome
