### ISSUE TITLE
Generated RBAC rules are insecure

### ISSUE THREAD

**Issue by sttts** [kubernetes-sigs/kubebuilder#748]
Kubebuilder generates RBAC rules which include:

* cluster wide read access to secrets
* write access to admission webhooks.

Both means root access to the cluster.

We should promote a tool like https://github.com/liggitt/audit2rbac instead of generating insecure rules by default.

/kind bug

**Comment by droot** [comment]
I agree with promoting tool like audit2rbac for this purpose. 

>cluster wide read access to secrets

We should be able to restrict this to the namespace where controller-manager is running. /cc @mengqiy same goes with the configmap as well.

>write access to admission webhooks.

This should no longer be needed with `2.0.0`. @sttts I am assuming you are using `1.0.0` release.

**Comment by sttts** [comment]
> I am assuming you are using `1.0.0` release.

Yes, the stable release. If that's fixed already, very good. I saw a webhook installer mentioned somewhere in the 1.0 docs. I guess that was the reason for the rule.

**Comment by DirectXMan12** [comment]
Yeah, we removed all of that in 1.0.0, since it was not, as you mentioned, super secure.  v2 doesn't require access to either.

**Comment by DirectXMan12** [comment]
removing from the milestone since it's a v1 scaffolding issue

**Comment by mhausenblas** [comment]
Perfect, thanks for confirming this @DirectXMan12. Can you talk to what your strategy for v2 will be? Will it leverage something like `audit2rbac` to generate the appropriate permissions?

**Comment by DirectXMan12** [comment]
well, for the moment the broad permissions aren't needed any more.  But yeah, eventually we'd like to have information on how to use something like audit2rbac

**Comment by mengqiy** [comment]
The 2 issues are fixed in v2.

>cluster wide read access to secrets

It only mount and read the secret from the same namespace.

>write access to admission webhooks

No longer self-registering the webhook config.
