### ISSUE TITLE
switch to kustomize `images` field from patch

### ISSUE THREAD

**Issue by pwittrock** [kubernetes-sigs/kubebuilder#754]
kustomize supports `images` as a first class transformer, so we should use that instead of creating a patch.

/kind feature

**Comment by hpandeycodeit** [comment]
would like to work on this. Any pointers/more details on this will be helpful.

**Comment by mengqiy** [comment]
Here is kustomize image transformer doc: https://github.com/kubernetes-sigs/kustomize/blob/master/examples/image.md

Here is how we generate image patch: https://github.com/kubernetes-sigs/kubebuilder/blob/master/pkg/scaffold/project/kustomize_image_patch.go
