### ISSUE TITLE
Formatting issues in simple_resource.md file

### ISSUE THREAD

**Issue by nzoueidi** [kubernetes-sigs/kubebuilder#756]
Looks like there are some issues with the formatting syntax into the markdown file[0]. 
E.g ({% sample lang="go" %}, {% endmethod %}, {% endpanel %}, etc..).

Whether we could remove them, or just fix them using the formatting syntax[1] provided by Github.

[0] https://github.com/kubernetes-sigs/kubebuilder/blob/book-v1/docs/book/basics/simple_resource.md
[1] https://help.github.com/en/articles/basic-writing-and-formatting-syntax

**Comment by DirectXMan12** [comment]
This isn't a formatting issue -- it's that our book software for the v1 book (gitbook) uses special syntax that's non-standard.  They don't show up normally in github, but should render fine on https://book-v1.book.kubebuilder.io/basics/simple_resource.html
