### ISSUE TITLE
One of the `kind` do not render rbac stuff in rbac/role.yaml

### ISSUE THREAD

**Issue by vincent-pli** [kubernetes-sigs/kubebuilder#762]
I have create two `api` with `kubebuilder` and modify one of them after rendering.
then I run `make manifests` to render configuration files and I noticed there is only one `kind`(the one I leave there, do not touch after render) rendered the rbac stuff.

I try to add `+kubebuilder:rbac:groups...` to the `*_types.go`, no help.

There is not any error/exception. So I hope someone could hint about: What could stop the rbac stuff render?

BTW, the `manager/controller` is already running with the `permission deny` exception.

**Comment by mengqiy** [comment]
I assume you are using the new v2 kubebuilder scaffolding.
The markers for generating rbac are in controller files. e.g. https://github.com/kubernetes-sigs/kubebuilder/blob/e096922dc5bbb7ca3df338bf3bd187856fcd7ae5/testdata/project-v2/controllers/captain_controller.go#L35-L36

Can you check if you have the markers in the controller files?

**Comment by vincent-pli** [comment]
@mengqiy 
Thanks for replay, I find the root cause, but still confuse 😄 
https://github.com/kubernetes-sigs/controller-tools/issues/221
