### ISSUE TITLE
Reference link is missing in Quick start 

### ISSUE THREAD

**Issue by gautamkmr** [kubernetes-sigs/kubebuilder#773]
In the Quick start guide https://book.kubebuilder.io/quick-start.html. The reference link is broken in below snippet

**Optional**: Edit the API definition or the reconcilation business logic. For more on this see [What is a Controller](https://book.kubebuilder.io/todo) and [What is a Resource](https://book.kubebuilder.io/todo)

**Comment by droot** [comment]
PR is merged, so closing it.
