### ISSUE TITLE
Figure out how to sync code in book

### ISSUE THREAD

**Issue by mengqiy** [kubernetes-sigs/kubebuilder#782]
Currently we have a complete code project in the book.
It may be out-of-date when kubeubilder evolves.
We need to figure out how to sync the code and can also have a CI test to type-checking it.
One approach is:
1. we re-generate the code and config.
2. rebase our own document change on top of it.
There are other approaches.

/kind feature

**Comment by camilamacedo86** [comment]
The proposed solution to address this need is detailed in: https://github.com/kubernetes-sigs/kubebuilder/issues/2510 now.
