### ISSUE TITLE
Remove deprecated API : inflect

### ISSUE THREAD

**Issue by hpandeycodeit** [kubernetes-sigs/kubebuilder#784]
Description: 

The API: [inflect](https://github.com/markbates/inflect) is deprecated and it is recommended to use [flect](https://github.com/gobuffalo/flect) instead ( As per the message on the github repo)

`inflect` is used in kubebuilder and mostly for `Pluralize` function. We can replace this with `flect` and update the required dependencies. 

/kind cleanup

**Comment by dpandhi-git** [comment]
would like to work on it

**Comment by dgkanatsios** [comment]
#539 contains relevant info

**Comment by mengqiy** [comment]
> would like to work on it

@dpandhi-git Sure. Feel free to ask us questions.

**Comment by dpandhi-git** [comment]
Thanks @mcristina422 for the PR.
