### ISSUE TITLE
Is the cronjob example fully available in github?

### ISSUE THREAD

**Issue by smolina74** [kubernetes-sigs/kubebuilder#785]
the book is difficult to follow, it would be nice if the whole code is available, not just snippets

**Comment by mengqiy** [comment]
The whole code is actually available at https://github.com/kubernetes-sigs/kubebuilder/tree/master/docs/book/src/cronjob-tutorial/testdata/project.
We need to mention it in the tutorial.
cc: @DirectXMan12

**Comment by leodotcloud** [comment]
The docs are definitely not easy to follow, feels like a WIP. It's not clear to which file the snippets have to be added.

**Comment by mengqiy** [comment]
cc: @DirectXMan12

**Comment by DirectXMan12** [comment]
Unless otherwise noted, each page corresponds to a single file (which is generally talked about in the title), but we could definitely make it clearer.

Do you have specific places you found it unclear?  It would help to know which pages to focus on.

> The first difference to notice is that kubebuilder has added the new API group’s package (kbatchv1beta1) to our scheme. This means that we can use those objects in our controller.

That's been fixed -- it was a typo.

**Comment by DirectXMan12** [comment]
(also, in general, please don't hijack unrelated issues)
