### ISSUE TITLE
Unknown flag --group in kubebuilder create api command

### ISSUE THREAD

**Issue by devdattakulkarni** [kubernetes-sigs/kubebuilder#787]
Following the steps from Kubebuilder book. Here is the error that we get:

$ kubebuilder create api --group webapp --version v1 --kind Guestbook
Error: unknown flag: --group
Usage:
  kubebuilder create [flags]
  kubebuilder create [command]

Examples:
Create new resource "Bee" in the "insect" group with version "v1beta"
 Will also create a test, controller and controller test for the resource
kubebuilder create resource --group insect --version v1beta --kind Bee

Available Commands:
  config      Generate installation config for the API
  example     Create the docs example scaffolding for an API
  resource    Creates an API group, version and resource

Use "kubebuilder create [command] --help" for more information about a command.

2019/06/15 14:17:04 unknown flag: --group

**Comment by devdattakulkarni** [comment]
Was working with previous version of kubebuilder.

**Comment by DirectXMan12** [comment]
You're going to have to be more specific on the version of kubebuilder that you're using -- I cannot reproduce this.

**Comment by devdattakulkarni** [comment]
@DirectXMan12 This is not an issue anymore. As I mentioned in the comment, I was using a very early version of Kubebuilder. With the latest version this is no longer an issue. So I closed the bug.
