### ISSUE TITLE
Default scheme should registered builtin types

### ISSUE THREAD

**Issue by mengqiy** [kubernetes-sigs/kubebuilder#797]
Default scheme scaffolded by the kubebuilder should have builtin types all registered, which is what we did in v1. This reduce users burden of understanding and manage the scheme.

/kind feature

**Comment by DirectXMan12** [comment]
We should also see if we can make this error clearer, since it's not obvious unless you already know the problem.

**Comment by functicons** [comment]
I was trying to create a Deployment from my reconciler, then I got this error:

```no kind is registered for the type v1.Deployment in scheme pkg/runtime/scheme.go:101```

Is this issue related? Where can I find an example to fix it?

**Comment by mengqiy** [comment]
Yes
What you need to add is this line.
https://github.com/kubernetes-sigs/kubebuilder/blob/b18a4e3b8f83d7d0ca461c28794aa7ac92c278ef/testdata/project-v2/main.go#L40

**Comment by functicons** [comment]
@mengqiy Does `clientgoscheme.AddToScheme(scheme)` register all builtin types? I used `appsv1.AddToScheme(scheme)` and it worked.

**Comment by mengqiy** [comment]
> Does clientgoscheme.AddToScheme(scheme) register all builtin types?

Yes. 

> If so, why does it also calls corev1.AddToScheme(scheme)?

This is scaffolded by kubeubilder. KB currently is not smart enough to skip it for builtin types. AFAIK registering it twice should not have any side effects.
