### ISSUE TITLE
initial error

### ISSUE THREAD

**Issue by dongwangdw** [kubernetes-sigs/kubebuilder#801]
I just following the gitbook to create a helloworld app. But I got the error as below:

`
    #~/g/s/g/myapp# kubebuilder init --domain my.domain

    Run `dep ensure` to fetch dependencies (Recommended) [y/n]?
    y
    dep ensure
    Running make...
    make
    go generate ./pkg/... ./cmd/...
    go: creating new go.mod: module github.com/myapp
    go: copying requirements from Gopkg.lock
    go: github.com/peterbourgon/diskv@v0.0.0-20190425080511-0be1b92a6df0: go.mod has post-v0 
    module path "github.com/peterbourgon/diskv/v3" at revision 0be1b92a6df0
    go: error loading module requirements
    Makefile:45: recipe for target 'generate' failed
    make: *** [generate] Error 1
    2019/06/19 00:20:06 exit status 2
`

OS: amd64 ubuntu
go: 12.5
And it is under go path.
/kind bug

**Comment by mengqiy** [comment]
What version of kubebuilder are you using?
It seems you are using an old version, since it use `dep ensure`.

**Comment by mengqiy** [comment]
expected output looks like:
```
$ kubebuilder init --domain my.domain
go mod tidy
Running make...
make
/usr/local/google/home/mengqiy/work/golang/src/sigs.k8s.io/controller-tools/bin/controller-gen object:headerFile=./hack/boilerplate.go.txt paths=./api/...
go fmt ./...
go vet ./...
go build -o bin/manager main.go
Next: Define a resource with:
$ kubebuilder create api
```

**Comment by dongwangdw** [comment]
@mengqiy Thanks so much for responding.
I checked the version, and it is 2.0 alpha. yes, it worked now after I installed the release from github.
The version from gitbook is too old.

**Comment by dongwangdw** [comment]
sorry, I closed it by accident.

**Comment by dongwangdw** [comment]
I reinstalled it and it worked as expected. It is so weird. I perhaps got some silly mistake. I will close this then.
