### ISSUE TITLE
How Controller-runtime client can get RESTClient to run a command

### ISSUE THREAD

**Issue by HenryXie1** [kubernetes-sigs/kubebuilder#803]
we have built an operator via kubebuilder 2.0 successfully. 
In this operator, we need to run a cmd in a pod
before we use  k8s.io/client-go/kubernetes.Clientset which it grabs restconfig and run like
```
    execReq := o.clientset.CoreV1().RESTClient().Post().
	    Resource("pods").
		Name(Podname).
		Namespace("default").
		SubResource("exec")

    execReq.VersionedParams(&corev1.PodExecOptions{
		Command:   SqlCommand,
		Stdin:     true,
		Stdout:    true,
		Stderr:    true,
		}, scheme.ParameterCodec)

	exec, err := remotecommand.NewSPDYExecutor(o.restConfig, "POST", execReq.URL())
	if err != nil {
		return fmt.Errorf("error while creating Executor: %v", err)
	}

	err = exec.Stream(remotecommand.StreamOptions{
			Stdin:  os.Stdin,
			Stdout: os.Stdout,
			Stderr: os.Stderr,
			Tty:    false,
		})
	if err != nil {
		return fmt.Errorf("error in Stream: %v", err)
	} else {
		return nil
	}
```
In the controller-runtime world,  I can't find any RESTClient  from client of controller-runtime.
https://godoc.org/sigs.k8s.io/controller-runtime/pkg/client
I wonder how we can execute a cmd in a  pod from an operator  ?
It would be great if we have restclient in controller-runtime.
It could be PR

thank you
/kind feature

**Comment by DirectXMan12** [comment]
https://godoc.org/sigs.k8s.io/controller-runtime/pkg/client/apiutil#RESTClientForGVK is the function that you're looking for.

**Comment by vijay-dcrust** [comment]
> we have built an operator via kubebuilder 2.0 successfully.
> In this operator, we need to run a cmd in a pod
> before we use k8s.io/client-go/kubernetes.Clientset which it grabs restconfig and run like
> 
> ```
>     execReq := o.clientset.CoreV1().RESTClient().Post().
> 	    Resource("pods").
> 		Name(Podname).
> 		Namespace("default").
> 		SubResource("exec")
> 
>     execReq.VersionedParams(&corev1.PodExecOptions{
> 		Command:   SqlCommand,
> 		Stdin:     true,
> 		Stdout:    true,
> 		Stderr:    true,
> 		}, scheme.ParameterCodec)
> 
> 	exec, err := remotecommand.NewSPDYExecutor(o.restConfig, "POST", execReq.URL())
> 	if err != nil {
> 		return fmt.Errorf("error while creating Executor: %v", err)
> 	}
> 
> 	err = exec.Stream(remotecommand.StreamOptions{
> 			Stdin:  os.Stdin,
> 			Stdout: os.Stdout,
> 			Stderr: os.Stderr,
> 			Tty:    false,
> 		})
> 	if err != nil {
> 		return fmt.Errorf("error in Stream: %v", err)
> 	} else {
> 		return nil
> 	}
> ```
> 
> In the controller-runtime world, I can't find any RESTClient from client of controller-runtime.
> https://godoc.org/sigs.k8s.io/controller-runtime/pkg/client
> I wonder how we can execute a cmd in a pod from an operator ?
> It would be great if we have restclient in controller-runtime.
> It could be PR
> 
> thank you
> /kind feature

How did you use the RESTClientforGVK. How do you build the arguments to pass to it.

**Comment by akirillov** [comment]
@vijay-dcrust, here's what worked for me. Hope this saves some time for others facing this issue.

Create a REST Client in `main.go` and pass it to the controller alongside the REST Config required to build a request:
```
gvk := schema.GroupVersionKind{
	Group:   "",
	Version: "v1",
	Kind:    "Pod",
}

restClient, err := apiutil.RESTClientForGVK(gvk, false, mgr.GetConfig(), serializer.NewCodecFactory(mgr.GetScheme()))
if err != nil {
	setupLog.Error(err, "unable to create REST client")
}

if err = (&MyReconciler{
	Client:     mgr.GetClient(),
	RESTClient: restClient,
	RESTConfig: mgr.GetConfig(),
	Scheme:     mgr.GetScheme(),
}).SetupWithManager(mgr); err != nil {
	setupLog.Error(err, "unable to create controller")
	os.Exit(1)
}
```
and in `controller.go` which takes the created client as a parameter:
```
type MyReconciler struct {
	client.Client
	RESTClient rest.Interface
	RESTConfig *rest.Config
	Scheme     *runtime.Scheme
}

func (r *MyReconciler) Reconcile(ctx context.Context, req ctrl.Request) (ctrl.Result, error) {
  execReq := r.RESTClient.
  	Post().
  	Namespace("namespace").
  	Resource("pods").
  	Name("name").
  	SubResource("exec").
  	VersionedParams(&corev1.PodExecOptions{
  		Container: "container",
  		Command:   []string{"sh", "-c", "sleep 1"},
  		Stdin:     true,
  		Stdout:    true,
  		Stderr:    true,
  	}, runtime.NewParameterCodec(r.Scheme))

  exec, err := remotecommand.NewSPDYExecutor(r.RESTConfig, "POST", execReq.URL())
  if err != nil {
  	return ctrl.Result{}, fmt.Errorf("error while creating remote command executor: %v", err)
  }

  err = exec.Stream(remotecommand.StreamOptions{
  	Stdin:  os.Stdin,
  	Stdout: os.Stdout,
  	Stderr: os.Stderr,
  	Tty:    false,
  })
}
```
