### ISSUE TITLE
Documentation Status V2 vs V1

### ISSUE THREAD

**Issue by daviddyball** [kubernetes-sigs/kubebuilder#806]
/kind bug

The https://book.kubebuilder.io/ URL currently displays V2 docs by default and says that V1 is deprecated. The issue is that there is no stable release of V2 and it feels like a number of features (or at least the documentation for features) is still missing from Version 2.

It would be helpful for the community to have a bit more clarification around the state of V2 vs V1. This could be more docs, another notice on the docs saying that V2 is actually in alpha or something else.

**Comment by mustafaakin** [comment]
And advice on whether or not to use v1 would be appreciated.

**Comment by DirectXMan12** [comment]
I personally would recommend starting with the v2 beta for new projects.  That being said, we haven't actually said that v1 is deprecated that I recall.  Where did you read that?

**Comment by DirectXMan12** [comment]
But yes, clarifying that v2 is alpha would be a good idea until we finish the stable release

**Comment by daviddyball** [comment]
![screenshot](https://user-images.githubusercontent.com/1235844/59884361-fde95d00-93af-11e9-9957-449c3e0b175d.png)

Granted it doesn't say "deprecated", but this section on the front page is misleading to anyone who visits. Having Half-baked V2 documentation as the default while V2 is still in alpha just seems wrong. Why can't it default to V1 docs and link to "Alpha V2 Documentation [here]". That would be far more intuitive.

**Comment by dongwangdw** [comment]
When I followed the doc from gitbook and installed v2 alpha, I got some issues. But I installed the release version from github release [link](https://github.com/kubernetes-sigs/kubebuilder/blob/master/RELEASE.md). It worked. I got an [issue](https://github.com/kubernetes-sigs/kubebuilder/issues/801).

So my questions which version is newer?

**Comment by DirectXMan12** [comment]
> Why can't it default to V1 docs and link to "Alpha V2 Documentation [here]"

Mainly trivial technical reasons (the "base" documentation is built off of master, not off the release branch -- would need to figure out how to set up netlify the other way around.).

We also (incorrectly) planned for a quicker release of the stable version, and figured (again incorrectly) that that message would be acceptable until then.  That's evidently not the case :-/, and we should clarify.

**Comment by ghostsquad** [comment]
@DirectXMan12 You said:

> I personally would recommend starting with the v2 beta for new projects.

I'm assuming that was a typo, and you meant "v2 alpha"?

What are the differences between v1 & v2? I'm new to building controllers, so it's been a bit confusing trying to figure out what I'm doing and what's missing. As an example, in several articles (referenced below), they talk about "informers" as the way to let the controller know about changes to objects.

https://itnext.io/under-the-hood-of-kubebuilder-framework-ff6b38c10796

https://medium.com/@trstringer/create-kubernetes-controllers-for-core-and-custom-resources-62fc35ad64a3

https://github.com/kubernetes/sample-controller/blob/master/controller.go

even from this repo:
https://github.com/kubernetes-sigs/kubebuilder/issues/253

But in the v2 book, nothing talks about informers. I'm confused about how this works! Any help would be appreciated.

**Comment by silasb** [comment]
I don't the differences from v1 & v2, but I know that informers aren't used much anymore.  Essentially, they were super low-level which `controller-runtime` people decided not to keep and start using one `reconcile` method instead [see [1]].

Please correct me if I'm wrong, but this is what I'm generally reading around the web.

[1]: https://github.com/kubernetes-sigs/controller-runtime/blob/master/FAQ.md#q-how-do-i-have-different-logic-in-my-reconciler-for-different-types-of-events-eg-create-update-delete

**Comment by ghostsquad** [comment]
Without informers how to you set up "watchers" for different resource types?

**Comment by silasb** [comment]
@ghostsquad look here: https://github.com/kubernetes-sigs/controller-runtime/blob/master/examples/builtins/main.go#L61 which sets up the watcher for two different resources.

**Comment by ghostsquad** [comment]
@silasb ah cool. thanks! for the insight. I'm looking forward to using this. What's the best way to provide additional feedback on v2? Just find/post an issue here?

**Comment by DirectXMan12** [comment]
I think we've made this pretty clear at this point.  Feel free to comment if you're still uncertain
