### ISSUE TITLE
[Question] Where can I find the document for 1.0.8?

### ISSUE THREAD

**Issue by gyliu513** [kubernetes-sigs/kubebuilder#807]
/kind bug

I found the default document is using v2.0, but 2.0 is still in rc and I want to use v1.0.8 instead, but found that the 1.0.8 document link are broken. Can anyone show some link for how I can access the 1.0.8 document? Thanks!

**Comment by droot** [comment]
Legacy documentation is available at --> https://book-v1.book.kubebuilder.io/

> 1.0.8 document link are broken
Which link are you referring to ? because `Legacy Documentation` link on https://book.kubebuilder.io/ seems to be working fine.

**Comment by gyliu513** [comment]
Thanks @droot ;-)
