### ISSUE TITLE
Use of internal package is not allowed

### ISSUE THREAD

**Issue by ourstart** [kubernetes-sigs/kubebuilder#811]
i want to reconcile object every N minutes, like HPA works.
`workqueue.NewNamedRateLimitingQueue(NewDefaultHPARateLimiter(resyncPeriod), "horizontalpodautoscaler")`

so,my solution is to change "controller.New()" like HPA.

`

	if options.Reconciler == nil {

		return nil, fmt.Errorf("must specify Reconciler")

	}

	if len(name) == 0 {

		return nil, fmt.Errorf("must specify Name for Controller")

	}

	if options.MaxConcurrentReconciles <= 0 {

		options.MaxConcurrentReconciles = 1

	}

	if err := mgr.SetFields(options.Reconciler); err != nil {

		return nil, err

	}

	c := &controllerinternal.Controller{

		Do:       options.Reconciler,

		Cache:    mgr.GetCache(),

		Config:   mgr.GetConfig(),

		Scheme:   mgr.GetScheme(),

		Client:   mgr.GetClient(),

		Recorder: mgr.GetRecorder(name),

		Queue:    workqueue.NewNamedRateLimitingQueue(workqueue.DefaultControllerRateLimiter(), name),

		MaxConcurrentReconciles: options.MaxConcurrentReconciles,

		Name: name,

	}

	return c, mgr.Add(c)

}`

but i occur "Use of internal package is not allowed" warning
can someone help me or give me any solutions? 
tks

**Comment by droot** [comment]
@ourstart You should use [Channel Source](https://godoc.org/github.com/kubernetes-sigs/controller-runtime/pkg/source#Channel) for this use case.
