### ISSUE TITLE
Comprehensive doc for kubebuilder annotations

### ISSUE THREAD

**Issue by estroz** [kubernetes-sigs/kubebuilder#815]
There should be a doc with a comprehensive list of `+kubebuilder` (and other) annotations available to users, especially considering the `controller-runtime` and `controller-tools` v0.2.0 releases coming up. If one does not exist already, are there plans to add one to `docs/` or the `controller-tools` repo?

**Comment by DirectXMan12** [comment]
yep! I'm tackling this from the CT side so that we also get command-line help as well.  stay tuned :-)

**Comment by estroz** [comment]
@DirectXMan12 awesome. Let me know if I can help in any way!
