### ISSUE TITLE
Getting an error running kubebuilder version from a directory that is not in GOPATH

### ISSUE THREAD

**Issue by yashbhutwala** [kubernetes-sigs/kubebuilder#829]
/kind bug

`2019/07/02 21:14:25 error finding current repository: could not determine repository path from module data, package data, or by initializing a module: go: cannot determine module path for source directory ... (outside GOPATH, no import comments)`

**Comment by yashbhutwala** [comment]
Fixed by #904

**Comment by sbose78** [comment]
What's the workaround to get this working?

**Comment by DirectXMan12** [comment]
upgrade your version of kubebuilder to one that includes #904

**Comment by sbose78** [comment]
The latest release was 26 days ago. The above commit was 15 days ago :(

**Comment by DirectXMan12** [comment]
we're doing a release today, so that should help.  Alternatively, kubebuilder is buildable from source with `go build ./cmd/` if you ever need to pick up the latest changes.

**Comment by mithuns** [comment]
I still get the same error

```
mithuns-MBP  ~  kubebuilder init --domain operator1.msingh.kubebuilder.io
2019/12/18 13:41:25 error finding current repository: could not determine repository path from module data, package data, or by initializing a module: go: cannot determine module path for source directory /Users/mithuns (outside GOPATH, module path must be specified)

Example usage:
	'go mod init example.com/m' to initialize a v0 or v1 module
	'go mod init example.com/m/v2' to initialize a v2 module

Run 'go help mod init' for more information.
 ✘ mithuns-MBP  ~  kubebuilder version
Version: version.Version{KubeBuilderVersion:"2.2.0", KubernetesVendor:"1.15.5", GitCommit:"0824a139f59e109c9e418a0b6e71a53c6e9e144f", BuildDate:"2019-11-20T00:00:24Z", GoOs:"unknown", GoArch:"unknown"}

```

Other than installing from source, is there any other way ?

**Comment by DirectXMan12** [comment]
If you're not actually in a place that `go mod init` can autodiscover, you'll have to run `go mod init` first.  Please see the book for more information: https://book.kubebuilder.io/quick-start.html#create-a-project

**Comment by mithuns** [comment]
I think the problem was that the folder name had a period in it.

**Comment by abdennour** [comment]
When running kubebuilder init, you can specify the module path using the --repo flag:

```
kubebuilder init --domain company.lan --repo company.lan/my-operator
```
