### ISSUE TITLE
Support low level webhook scaffolding

### ISSUE THREAD

**Issue by mengqiy** [kubernetes-sigs/kubebuilder#833]
From https://github.com/kubernetes-sigs/kubebuilder/pull/816#discussion_r297416634

We may want to do some scaffolding besides the `Defaulter` and `Validator` interfaces.
Presumably it looks like [the builtin types example](https://github.com/kubernetes-sigs/controller-runtime/tree/master/examples/builtins) in controller runtime.

This is mainly for tracking purpose, since we may want to have some feedback before doing it.

/kind feature

**Comment by camilamacedo86** [comment]
This one seems outdated. So, I am closing.
However, if anyone see that it should be re-opened please do it and/or open a new one providing further info
