### ISSUE TITLE
Changes to Gitbook business model that may affect this project

### ISSUE THREAD

**Issue by pires** [kubernetes-sigs/kubebuilder#838]
This project seems to rely on Gitbook to generate and serve documentation. Recently, a new version of [Gitbook (v2) dropped support for serving the resources locally](https://docs.gitbook.com/v2-changes/important-differences) which I think will at least affect how developers interact with the tool and the resources managed by it. Did anyone here look into this already?

**Comment by pires** [comment]
Actually, I was mislead by https://github.com/kubernetes-sigs/kubebuilder/tree/master/docs. @DirectXMan12 already moved to something called `mdbook`. Cool!

**Comment by DirectXMan12** [comment]
For posterity:

I caught wind of this too, and, coupled with some frustrations I had getting the gitbook CLI to run (`npm install --three-quarters-of-all-node-packages-in-existence --fail-halfway-through`), I switched things over to a tool called [mdBook](https://github.com/rust-lang-nursery/mdbook), which was written for and used by the Rust language team for their various book-like things.  It's works like gitbook, but with an "external process" plugin model and a single binary to install.
