### ISSUE TITLE
controller-managers needs RBAC permissions for creating events

### ISSUE THREAD

**Issue by droot** [kubernetes-sigs/kubebuilder#848]
I discovered following in controller manager log which indicates we are missing RBAC permissions for posting events.

E0709 19:36:26.336740       1 event.go:191] Server rejected event '&v1.Event{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"controller-leader-election-helper.15afd444799e0dc2", GenerateName:"", Namespace:"project-system", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:v1.Time{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, DeletionTimestamp:(*v1.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Initializers:(*v1.Initializers)(nil), Finalizers:[]string(nil), ClusterName:"", ManagedFields:[]v1.ManagedFieldsEntry(nil)}, InvolvedObject:v1.ObjectReference{Kind:"ConfigMap", Namespace:"project-system", Name:"controller-leader-election-helper", UID:"d73ccef6-a280-11e9-bbbe-42010a8001af", APIVersion:"v1", ResourceVersion:"15112", FieldPath:""}, Reason:"LeaderElection", Message:"project-controller-manager-5f6bf96944-fff2b_d73ae7ff-a280-11e9-aa58-4654a5bc6366 became leader", Source:v1.EventSource{Component:"project-controller-manager-5f6bf96944-fff2b_d73ae7ff-a280-11e9-aa58-4654a5bc6366", Host:""}, FirstTimestamp:v1.Time{Time:time.Time{wall:0xbf41590e90ef49c2, ext:3337109171, loc:(*time.Location)(0x20c6aa0)}}, LastTimestamp:v1.Time{Time:time.Time{wall:0xbf41590e90ef49c2, ext:3337109171, loc:(*time.Location)(0x20c6aa0)}}, Count:1, Type:"Normal", EventTime:v1.MicroTime{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, Series:(*v1.EventSeries)(nil), Action:"", Related:(*v1.ObjectReference)(nil), ReportingController:"", ReportingInstance:""}': 'events is forbidden: User "system:serviceaccount:project-system:default" cannot create resource "events" in API group "" in the namespace "project-system"' (will not retry!)
2019-07-09T19:36:26.403Z        INFO    controller-runtime.controller   Starting workers        {"controller": "disk", "worker count": 1}

/kind bug

**Comment by mengqiy** [comment]
From the log, it looks like the leader election bits doesn't have the necessary permissions to publish events.
