### ISSUE TITLE
Better workflow for integrating with existing Go APIs

### ISSUE THREAD

**Issue by alexkreidler** [kubernetes-sigs/kubebuilder#863]
Our team would love to build a set of CRDs around an existing Golang API that we have. However, support for this workflow, aka using existing/external APIs in kubebuilder is not great, which means we either have to duplicate code and maintain it separately or modify our upstream existing API to accomodate `kubebuilder` quirks.

For a few more details: We have a Go API in its own repo with a bunch of struct types, some of which include embedded structs, and some of which refer to other types in our API. Our hope is to literally pass these API type definitions as the `Spec` in our Kubebuilder project (in a separate repo) so that the user can pass all of the same fields as inputs to the CRD, and our controller can recieve those types and then immediately make a request to our other API server. We effectively want to build a wrapper around our existing control-plane API using CRDs and the Operator pattern. 

However, we've run into a few limitations:
1. Support for embedded structs is _slightly_ lacking (it seems the only option is to modify the upstream API to include a `json:",inline"` tag): See https://github.com/kubernetes-sigs/controller-tools/issues/244
2. Dealing with required/optional fields in our API is difficult: e.g. we want 3 identifying fields to be required, and the rest to be optional. However, manipulating the upstream api by adding a `omitempty` tag is not a choice for us because of complicated existing implementations. However, it seems that we'll have much greater control over this with https://github.com/kubernetes-sigs/controller-tools/pull/211, albeit requiring us add modifications and annotations to our existing upstream API
3. Killer issue: `DeepCopy()` implementation generation for all subtypes. We realized that using a type alias: e.g. `type MyCluster api.Cluster` would allow `controller-gen` to generate the required `DeepCopy` functions for the immediate child type. However, since all our types reference subtypes: e.g. `api.Cluster` includes a field of type `api.Instances`, and these are all stored in an external API repo and package, and a core Go issue is that you [can't add functions to existing structs in a different package](https://stackoverflow.com/a/28800807), we're really limited. One option would be to add `controller-gen` to our workflow in the upstream API repo so it automatically generates requisite `DeepCopy` implementations. However, this is a big change to one of our most important repos, so it is effectively a last resort for us. I'd love to hear any feedback or thoughts on how to fix this, or if you all have any workflow ideas for dealing with an existing well-established API.

Nevertheless, this is an awesome tool. I couldn't imagine building a CRD extension without `kubebuilder`. I hope that you all keep existing APIs in mind when working on the next versions of `kubebuilder`. Thanks!

/kind feature

**Comment by droot** [comment]
@alexkreidler Thanks for such a detailed feedback. This is super valuable. 

Regarding second issue, ability to specify raw OpenAPI schema for a field/type using a `crd marker` might help here. It's a way of saying, we are referencing/embedding these external types, and we want to bring their own OpenAPI schema ?

Will think about the `DeepCopy()` one and share some ideas about it.

**Comment by alexkreidler** [comment]
@droot that's an interesting idea and could be really useful. I'm sure many teams would love the flexibility of using the more of the OpenAPI spec (although to be honest I haven't looked into what fields kubernetes actually uses for validation). I believe we also already have a regular REST OpenAPI schema, which we could use for porting descriptions or examples.

Also, after some more thought I've realized the real advantage of kubebuilder is that one repo is a single source of truth for the CRDs, and in our case, also our API. So I've realized it wouldn't honestly be that bad to add the annotations and/or tags to our upstream repo, which I guess means 1 and 2 are less relevant, but could still apply (e.g. if you're trying to wrap or consume an API you don't maintain)

Thanks for the feedback, we really appreciate it!

**Comment by DirectXMan12** [comment]
There's a reason for some of those.  Mostly, it's to prevent people from writing things that aren't actually compatible with Kubernetes APIs.  For background:

If `1` isn't true, you can run into issues with other forms of serialization, IIRC (I *think* YAML is one, but it's been a while since I checked on the exact details), and in general requiring the json tags avoids a common footgun where you add new fields, forget the JSON tag, and get an incorrectly capitalized field.

For `2`, you need *some* way of marking that things are optional.  What would you suggest?

For `3`, that's a genuinely tough one.  One option of the top of my head is a handwritten deepcopy function on a type alias that doesn't call out to individual methods -- it just deepcopies the entire tree.  Alternatively, something reflection-based might do the trick, but would be slower.

**Comment by aceamarco** [comment]
@alexkreidler Were you able to solve this? I'm also trying to extend an existing api and am using Kubebuilder to make it.

**Comment by alexkreidler** [comment]
No, I'm no longer working on that project and I'm not sure if any further progress has been made with it. Best of luck to you!
