### ISSUE TITLE
Generate suggested Roles for CR users

### ISSUE THREAD

**Issue by erictune** [kubernetes-sigs/kubebuilder#886]
/kind feature

Today, KB use some static roles and it generates a dynamic Role from the `//+kubebuilder:rbac:...` comments.  These cover the permissions the controller needs.

These are _not_ the ones this feature request is talking about.

KB should also generate ClusterRoles to be used by end users who want to CRUD CRs defined by the CRDs in the KB project.

Say my KB project defines something called `admirals`.
KB should defined a ClusterRole called `admiral-editor` and `admiral-viewer`.
These should be something the consumer of the operator is recommended to install.  

The consumer of the operator (usually different from the KB user) would be responsible for making any bindings between their users and these Roles.

**Comment by mengqiy** [comment]
Reopen this since we may want to revise it per https://github.com/kubernetes-sigs/kubebuilder/pull/1165#discussion_r347689204
