### ISSUE TITLE
Makefile install/deploy targets update

### ISSUE THREAD

**Issue by jgustie** [kubernetes-sigs/kubebuilder#900]
/kind bug

The v2 Makefile install and deploy targets could be updated to reflect the latest Kustomization structure: e.g. `install` could be changed to `kustomize build config/crd | kubectl apply -f -` and `deploy` no longer needs to directly apply `config/crd/bases` (since `default` already includes it).

**Comment by DirectXMan12** [comment]
cc @mengqiy

**Comment by droot** [comment]
We want to check if we have multi-version CR without the conversion webhook specified, will api-server rejects.

**Comment by mengqiy** [comment]
Closed by #934
