### ISSUE TITLE
CRD GA support

### ISSUE THREAD

**Issue by droot** [kubernetes-sigs/kubebuilder#903]
CRDs are being promoted to GA in 1.16 release --> https://github.com/kubernetes/enhancements/blob/master/keps/sig-api-machinery/20180415-crds-to-ga.md

The task is to identify the features/enhancements to be done in controller-tools/runtime/kubebuilder to ensure we have support for all the CRD features supported by Kubernetes.

**Comment by DirectXMan12** [comment]
# PRs

- CRD v1 support (partial): https://github.com/kubernetes-sigs/controller-tools/pull/321
- Defaulting support: https://github.com/kubernetes-sigs/controller-tools/pull/321

**Comment by DirectXMan12** [comment]
oh, yeah, go ahead please.  The tools are on a separate branch.  Just look at the previous commit to see what you have to do.

**Comment by vincepri** [comment]
It's all done :) tools have been published and master updated as well

**Comment by DirectXMan12** [comment]
ah, cool :-)

**Comment by DirectXMan12** [comment]
I think we can close this now -- everything is done afaik
