### ISSUE TITLE
Can't use `kubectl apply` with sufficiently large CRDs

### ISSUE THREAD

**Issue by DirectXMan12** [kubernetes-sigs/kubebuilder#906]
We use `kubectl apply` to install CRDs.  When using client-side apply (which is what almost everyone is doing), any sufficiently large CRD (probably any multi-version CRD) will blow the annotation size limit (caused by storing last apply configuration in an annotation).

We'll need to switch to get/create/replace or something.

/kind bug
/priority critical-urgent

For repro, try running `kubectl apply` on the new CronJob version of the multiversion tutorial if it hasn't been run yet.

**Comment by droot** [comment]
xref: https://github.com/kubernetes-sigs/controller-tools/issues/288

**Comment by droot** [comment]
xref: https://github.com/kubernetes-sigs/controller-tools/pull/299

**Comment by DirectXMan12** [comment]
Let's see if this also fixes the "uses all my CPU" issue too.

**Comment by DirectXMan12** [comment]
Nope!  Re-opening

**Comment by DirectXMan12** [comment]
Issue: https://github.com/kubernetes/kubectl/issues/698

**Comment by DirectXMan12** [comment]
fix posted for above issue
closing this out.
