### ISSUE TITLE
Imports lowercased

### ISSUE THREAD

**Issue by wstrange** [kubernetes-sigs/kubebuilder#91]
Same issue as code-generator:

https://github.com/kubernetes/code-generator/issues/20 

I can work around it with a simple script that does a search/replace

**Comment by pwittrock** [comment]
We need to see if it is possible to get rid of this code generation completely.

**Comment by n3wscott** [comment]
I am fixing here: https://github.com/kubernetes/kubernetes/pull/63892/commits

**Comment by pwittrock** [comment]
@n3wscott Awesome.  Will update the deps to use your change once it is merged if the code gen versions are compatible with 1.10.

**Comment by pwittrock** [comment]
Switching from code generation to dynamic clients should resolve this.
