### ISSUE TITLE
envtest.Start() failed when "--allow_privileged=true" is added

### ISSUE THREAD

**Issue by 27149chen** [kubernetes-sigs/kubebuilder#917]
/kind bug

envtest.Start() failed when "--allow_privileged=true" is added to KubeAPIServerFlags, reporting "timeout waiting for process kube-apiserver (and also etcd) to start".
The KubeAPIServerFlags is 
```
                "--etcd-servers={{ if .EtcdURL }}{{ .EtcdURL.String }}{{ end }}",
		"--cert-dir={{ .CertDir }}",
		"--insecure-port={{ if .URL }}{{ .URL.Port }}{{ end }}",
		"--insecure-bind-address={{ if .URL }}{{ .URL.Hostname }}{{ end }}",
		"--secure-port={{ if .SecurePort }}{{ .SecurePort }}{{ end }}",
		"--admission-control=AlwaysAdmit",
		"--allow_privileged=true",
```
OS is mac
kubebuilder version is
```
$ kubebuilder version
Version: version.Version{KubeBuilderVersion:"master", KubernetesVendor:"1.14.1", GitCommit:"9e4a759bcb4b532362b3c4026e127ed8e34ed28f", BuildDate:"2019-08-01T17:37:52Z", GoOs:"unknown", GoArch:"unknown"}
```
controller-runtime v0.1.12

**Comment by DirectXMan12** [comment]
can you run with `KUBEBUILDER_ATTACH_CONTROL_PLANE_OUTPUT=true` and see what errors are logged from your API server startup?

**Comment by 27149chen** [comment]
@DirectXMan12 , sorry forgot to tell you, for some reason I use controller-runtime v0.1.12, which don't have this setting

**Comment by DirectXMan12** [comment]
That's not a valid flag on Kubernetes 1.14.1.  You'll want `--allow-privileged` (try running kube-apiserver manually).

**Comment by akutz** [comment]
I'm curious why this was closed. I'm also hitting the same issue.

**Comment by DirectXMan12** [comment]
This was closed because the user was trying to pass a flag to the kubernetes API server that was not a valid flag for that version of the Kubernetes API server.

**Comment by akutz** [comment]
Hi @DirectXMan12,

FWIW, I hit the issue because, while I was passing the correct `allow-privileged` flag, I didn't realize that you had to manually specify the default set if you specify additional flags. Once I did that, it all worked. Thanks!
