### ISSUE TITLE
LastScheduleTime is updated wrongly in cronjob-tutorial

### ISSUE THREAD

**Issue by khchan123** [kubernetes-sigs/kubebuilder#919]
Hi, I am looking at the [cronjob_controller.go](https://github.com/kubernetes-sigs/kubebuilder/blob/master/docs/book/src/cronjob-tutorial/testdata/project/controllers/cronjob_controller.go) in cronjob-tutorial. The `LastScheduleTime` of `cronJob` is evaluated from latest `getScheduledTimeForJob()` function among all the child jobs. I found it's not updating correctly and promptly in the same `Reconcile` call. I haven't dig into the cause yet but I found the `LastScheduleTime` sometimes it's in the future (i.e. next minute) and causing job creation skipped at the next minute.

Besides, why don't we just update the `LastScheduleTime` after creating the `Job`?

Updates: I found the cause. In function `getNextSchedule()`, the returned pointer of `lastMissed` is indeed a reference of the internal loop iterable `t`. The value of `t` leaving the internal loop is actually *passed beyond* the current time (i.e. the next Schedule). So the pointed time `lastMissed` appears popped to the next Schedule in the future instead of the current unmet schedule when leaving the loop.

/kind bug

**Comment by mariantalla** [comment]
@kubernetes-sigs/kubebuilder-maintainers would it be ok for me to have a look at this? 👀

**Comment by mengqiy** [comment]
cc: @DirectXMan12

**Comment by DirectXMan12** [comment]
ah, yeah, if you want to submit a fix, go ahead.

**Comment by khchan123** [comment]
Thanks everyone. I managed to work on a fix and created #929.

**Comment by khchan123** [comment]
This issue could be closed after #929 merged to `master`.
