### ISSUE TITLE
Testing Examples & Reference

### ISSUE THREAD

**Issue by DirectXMan12** [kubernetes-sigs/kubebuilder#920]
We should have a section on testing the CronJob controller, and reference documentation on our recommended ways of testing controllers.

/kind documentation
/priority important-soon

**Comment by johanneswuerbach** [comment]
Is there any documentation on controller testing to be found somewhere? Is the recommended testing strategy in v1 largely different from v2?

We would love to get started writing a new CRD with v2, but are currently struggling on finding more details around controller testing.

**Comment by DirectXMan12** [comment]
It's on my list of things to write down, but we're still gathering a bit more information.  We found that the existing v1 tests were a) confusing to many, and b) didn't actually follow some of our recommendations (checking the exact reconcile sequence discourages re-queuing, for instance), so we decided to re-evaluate a bit.

In the mean time, the controller tests in controller-runtime can offer some guidance.  Additionally, these tests follow a decent layout: https://github.com/microsoft/azure-databricks-operator/blob/0f722a710fea06b86ecdccd9455336ca712bf775/controllers/secretscope_controller_test.go

Those look a lot like what we'll probably end up documenting/offering to scaffold out:

1. Set up testenv
2. Run controller
3. Use client to set up preconditions
4. Use eventually to evaluate expected outcome

However, both of those really only interact with a kubernetes API server, so they don't match your case exactly.

For bits that aren't a kube apiserver, I'd recommend creating an interface around your AWS client, or breaking up your reconciler into "pure" functions that return some output that you can test against.

 **Is there anything that was specifically unclear**?

**Comment by briantopping** [comment]
"Is there anything that was specifically unclear?"

Before finding this issue, I searched for projects using `v2`, over 50 in all. I found only one that was doing testing at https://github.com/govargo/sample-controller-kubebuilder. The code there is not nearly as advanced as the code you shared in the previous link. 

What I'd like to see is a narrative on the use of `EventRecorder` as in https://github.com/microsoft/azure-databricks-operator/blob/0f722a710fea06b86ecdccd9455336ca712bf775/controllers/suite_test.go#L103-L109 and any caveats or alternate patterns around static reconcilers, such as anything besides `Recorder` that would be envisioned for common use. 80/20 rule here, just looking to prime the pump.

My own use case is trying to convert the `v1` testing code at https://github.com/briantopping/freeipa-operator/tree/master/pkg/controller/ipacluster to `v2`. I saw #639 from another issue and it didn't really explain how to get around reconcile testing that was previously scaffolded with channels. 

Are there any cool tricks that are missing in the azure-databricks-operator? Those would be helpful to understand as well. What could they learn from you to write a better operator?

Thanks for all your work! I'm really looking forward to using it!!

**Comment by briantopping** [comment]
Also, I think it might be helpful to get people started with in-process vs. full container configuration, even if it's just links to where people might find that stuff. I had figured this stuff out a few months ago when I was first working on it and had forgotten it by now, wondering why apiserver was accepting objects and they weren't showing up in the cluster I was watching. Well duh, it's a different process!

I kind of remember some manner of turning on logs for the in-process (default) configuration, that's another trick that would be helpful to document.

**Comment by DirectXMan12** [comment]
split that last one out into its own doc item

**Comment by DirectXMan12** [comment]
also merged a PR to add at least a note about that example to the book, but going to keep this open to track other stuff

**Comment by camilamacedo86** [comment]
The tests docs were improved. See:  https://book.kubebuilder.io/cronjob-tutorial/writing-tests.html 
So, shows that we need re-check this one to see what still missing described and then, add the info.

**Comment by camilamacedo86** [comment]
Closing it as solved https://book.kubebuilder.io/cronjob-tutorial/writing-tests.html
