### ISSUE TITLE
Typo in book: int64 should be marked as allowed

### ISSUE THREAD

**Issue by daneharrigan** [kubernetes-sigs/kubebuilder#921]
The kubebuilder 2.0 book says ints should be `int32`, but `StartingDeadlineSeconds` is an `int64` in `CronJobSpec`.

/kind bug

**Comment by mengqiy** [comment]
> Fields may use most of the primitive types. Numbers are the exception: for API compatibility purposes, we accept two forms of numbers: int32 for integers, and resource.Quantity for decimals.

I guess you mean this.
`int32 for integers` is a little misleading. `int64` is allowed. @DirectXMan12 We should fix it.

**Comment by daneharrigan** [comment]
@mengqiy yes, that's exactly what I was referring to. If int64 is allowed, my related PR doesn't make sense anymore. I'm happy to open a new one with an update to the doc.

**Comment by DirectXMan12** [comment]
I can't seem to find the spot that said "you should use int32" in the [api conventions](https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md), so yeah, we can fix the docs and the comment in the source.

**Comment by daneharrigan** [comment]
@DirectXMan12 I'm having a hard time following your suggestion to comment in the source. Which source, the cronjob-tutorial or kubebuilder?

**Comment by DirectXMan12** [comment]
"comment in the source" --> there's a comment in the schema generator that talks about disallowed types (right above the code that works with them), so we'll want to fix that up.

**Comment by dlespiau** [comment]
Can this be closed now that both PRs are merged?
