### ISSUE TITLE
Multi group support for v2 scaffolding

### ISSUE THREAD

**Issue by DirectXMan12** [kubernetes-sigs/kubebuilder#923]
We should have proper multi-group support in the v2 scaffolding.  We won't scaffold it by default, and migrating to it will always be a manual change, but once you've enabled it, we should be able to scaffold API versions in a per-group directory.

Presumably, this would look like adding a `multigroup: true` stanza to the `PROJECT` file, and the KubeBuilder would generate new groups at

`apis/<group>/<version>` instead of `api/<version>`.

/kind feature

**Comment by paroxp** [comment]
I assume this won't be as part of the initial stable kubebuilder release? :(

**Comment by DirectXMan12** [comment]
automated scaffolding for multi-group repos will most likely be part of v2.1.0.  That being said, we've gone to a lot of effort to ensure that the underlying tooling and libraries work with pretty much any directory layout, so you should still be able to use the corresponding controller-runtime and controller-tools v0.2.0 releases to support a multi-group setup.

**Comment by DirectXMan12** [comment]
rewriting import paths like that is "scary" since it can contain unintended changes or miss things but still works.  That's why we wouldn't have automatic migration.  There's also no guarantee that things haven't been reworked, files haven't been added, etc since the user did the scaffolding.  We generally follow the principle that scaffolding is one-off, so we don't try to change it (with a couple of small exceptions in main.go).

If you're generating from scratch on a new project, sure, but you'd have to "migrate" your existing project by hand so that we don't mess it up, then we could easily start scaffolding in the new setup.
