### ISSUE TITLE
Multiple failures if building a controller for a non-custom resource

### ISSUE THREAD

**Issue by johnharris85** [kubernetes-sigs/kubebuilder#925]
/kind bug

If creating a controller for something like Ingress (or any other built-in Kind) there is no `/api` directory generated and `make docker-image` fails on the `COPY api/ api/` step. This probably needs to be conditional based on whether the user choose to create a resource during `kubebuilder create api...`. 

`make generate` also fails (missing `./api` path) so `Makefile` may need some logic to skip that if it doesn't exist?

**Comment by DirectXMan12** [comment]
ah, good catches

**Comment by DirectXMan12** [comment]
`make generate` fix should be `controller-gen paths=./api/...` --> `controller-gen paths=./...`.  `deepcopy-gen` should just skip everything that's not marked package-level as deepcopy-enabled.

**Comment by DirectXMan12** [comment]
not sure what to do on the dockerfile :-/.  Maybe buildkit's mount option?  Alternatively, bypass dockerfile syntax some other way.

**Comment by johnharris85** [comment]
Ye by conditional I meant have a conditional in the go code / template for the Dockerfile to include that instruction or not. Or maybe just generate an empty `api` directory anyway :p

**Comment by DirectXMan12** [comment]
empty `api` seems "meh" to me, but we might have to, at least in the short term :-/.  The problem with checking at generation time is that you could add something that adds `api` directories later.

**Comment by johnharris85** [comment]
Haha ye always adding `api` was a semi-in-jest suggestion :p In the second scenario you'd still always re-run the `create api` though right to generate? Is there any reason folks would modify the dockerfile out of band of the scaffolding? Maybe a flow like:

- If user wants to create resources, create api dir and Dockerfile as is
- If user doesn't create, only add `COPY api` to Dockerfile if the `api` dir already exists (this accommodates the use case of running once without, then running again with so we make sure we still COPY `api`)

**Comment by DirectXMan12** [comment]
`Dockerfile` is generated as part of the initial scaffolding, not as part of `create api`, at least currently.  Users might modify to include additional packages that they need, for instance.  We generally assume we can't edit anything scaffolded out *expect* for a couple cases in main.go.

**Comment by johnharris85** [comment]
Ah OK fair enough. I'm not sure there's anything in buildkit that would help us here. Maybe just being more liberal with the COPY at the expense of inefficient cache busting? Emtpy `api` looks more attractive now :joy:

**Comment by DirectXMan12** [comment]
I've played around with the experimental buildkit frontend for docker build (18.06+), and we could just use that to mount in the entire workdir without the overhead of copying over the other files.  Alternatively, we could just copy everything.

**Comment by DirectXMan12** [comment]
we'll be conservative for the moment and not introduce buildkit, but I want to think about that in the future.

**Comment by DirectXMan12** [comment]
I think for moment, we'll just add a note to change the dockerfile.  We can explore more options in the future.  It's the lowest friction path for the moment.

re: the makefile, that's an easy fix, and I'll get that in shortly
