### ISSUE TITLE
Skaffold + Kubebuilder + BuildKit

### ISSUE THREAD

**Issue by chainlink** [kubernetes-sigs/kubebuilder#927]
I put together a small write-up/repo [here](https://github.com/chainlink/kubebuilder-skaffold/tree/make-it-work) on getting started with kubebuilder, skaffold and docker buildkit for faster iteration. Is this something you would be interested in integrating into the project docs?

**Comment by DirectXMan12** [comment]
@mengqiy on the kustomize thing -- that just looks like a change we need to do on our our part.

**Comment by DirectXMan12** [comment]
Oof, that skaffold bug.

I'm not sure that this belongs in the main kubebuilder book, except perhaps for that buildkit trick.  We might want to pull that in (although, I've seen similar things give *terrible* performance on Docker for Mac, so maybe just as a tip in the book).

**Comment by chainlink** [comment]
Yeah, agree all are more on the tips and tricks end of things vs the happy path core docs. Maybe we could add a tips/workarounds section in the docs?

**Comment by DirectXMan12** [comment]
> Maybe we could add a tips/workarounds section in the docs?

Yeah, that sounds fine.  PRs welcome :-)

**Comment by mengqiy** [comment]
The issue with kustomize has been fixed on HEAD. We will do a kubebuilder release soon-ish.

**Comment by chainlink** [comment]
Thanks all!

**Comment by camilamacedo86** [comment]
Hi @mengqiy, 

Could we not close this one since shows sort out in the master branch?
