### ISSUE TITLE
Is there the "tutorial.kubebuilder.io/project/api/v1" into the cronjob_controller.go we need to manually add it into requirements?

### ISSUE THREAD

**Issue by Aisuko** [kubernetes-sigs/kubebuilder#931]
/kind help wanted

Thanks for your guys awesome work on kubebuilder. I'm learning on this. Also, the kubebuilder book didn't show the same example with the API was created by kubebuilder. So, we need manually add this to our project requirements? 
Any feedback would be good.

https://github.com/kubernetes-sigs/kubebuilder/blob/17f261aa333ab1361b63a217ca574d5a081653d8/docs/book/src/cronjob-tutorial/testdata/project/controllers/cronjob_controller.go#L40

**Comment by DirectXMan12** [comment]
that's the project itself -- if you look at `go.mod`, you'll see `tutorial.kubebuilder.io/project` is the name of the sample project module.

**Comment by DirectXMan12** [comment]
That also matches what's noted under `go.mod` in the book.

Can you clarify what you mean by:

> Also, the kubebuilder book didn't show the same example with the API was created by kubebuilder

**Comment by Aisuko** [comment]
Thanks for your reply sir, I mean I follow the official document address https://book.kubebuilder.io/cronjob-tutorial/controller-overview.html , and saw the `emptycontroller.go` has been imported "tutorial.kubebuilder.io/project/api/v1", but the controller created by the `kubebuilder create command ` didn't include this package.

**Comment by DirectXMan12** [comment]
Oh, you look like you're running KubeBuilder v1.  What does `kubebuilder version` say?

**Comment by Aisuko** [comment]
I was followed the install step like below

```
version=1.0.8 # latest stable version
arch=amd64

# download the release
curl -L -O "https://github.com/kubernetes-sigs/kubebuilder/releases/download/v${version}/kubebuilder_${version}_darwin_${arch}.tar.gz"

# extract the archive
tar -zxvf kubebuilder_${version}_darwin_${arch}.tar.gz
sudo mv kubebuilder_${version}_darwin_${arch} /usr/local/kubebuilder

# update your PATH to include /usr/local/kubebuilder/bin
export PATH=$PATH:/usr/local/kubebuilder/bin
```

The kubebuilder version below:
```
Version: version.Version{KubeBuilderVersion:"1.0.8", KubernetesVendor:"1.13.1", GitCommit:"1adf50ed107f5042d7472ba5ab50d5e1d357169d", BuildDate:"2019-01-25T23:14:29Z", GoOs:"unknown", GoArch:"unknown"}
```

**Comment by DirectXMan12** [comment]
where did you get those instructions?  Those look like the old verion install instructions

**Comment by Aisuko** [comment]
I found the legacy documentation `Using Kubebuilder v1? Check the legacy documentation` on the https://book-v1.book.kubebuilder.io/getting_started/installation_and_setup.html. Oh, I need to install `kubebuilder version 2.0.0-beta.0.x` and follow the latest instructions, thank you sir.❤️
