### ISSUE TITLE
Set preserveUnknownFields to false in the CRD conversion webhook patch

### ISSUE THREAD

**Issue by mengqiy** [kubernetes-sigs/kubebuilder#933]
kube-apiserver requires `spec.preserveUnknownFields` to be `false` when `conversion.strategy` is `Webhook`.
Ref: https://github.com/kubernetes/kubernetes/blob/1d812991b63f42485d5f2aa8c883f142445fd09a/staging/src/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/validation/validation.go#L265

> CustomResourcesDefinition conversion via Web Hooks is promoted to beta. Note that you must set spec.preserveUnknownFields to false.

See release note in https://github.com/kubernetes/kubernetes/pull/78426

/kind bug

**Comment by mengqiy** [comment]
cc: @droot

**Comment by pires** [comment]
This seems to also affect clusters that enable `CustomResourceDefaulting` feature-gate when using `+kubebuilder:default` marker.

**Comment by DirectXMan12** [comment]
yes, defaulting requires the v1 CRD and a structural schema.  We could document this better in the defaulting marker docs and the book

**Comment by camilamacedo86** [comment]
/assing @camilamacedo86 

c/c @estroz

**Comment by ttlv** [comment]
`
# The following patch enables conversion webhook for CRD
# CRD conversion requires k8s 1.13 or later.
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: nodedeployments.edge.harmonycloud.cn
spec:
  preserveUnknownFields: false
  conversion:
    strategy: Webhook
    webhookClientConfig:
      # this is "\n" used as a placeholder, otherwise it will be rejected by the apiserver for being blank,
      # but we're going to set it later using the cert-manager (or potentially a patch if not using cert-manager)
      caBundle: Cg==
      service:
        namespace: system
        name: webhook-service
        path: /convert
`
I think it's better to add  preserveUnknownFields: false when use kubebuilder to generate.
