### ISSUE TITLE
make run failed with KUBECONFIG 

### ISSUE THREAD

**Issue by adoyle-h** [kubernetes-sigs/kubebuilder#936]
kubebuilder version: version.Version{KubeBuilderVersion:"2.0.0-beta.0", KubernetesVendor:"1.14.1", GitCommit:"b12371ccabd1bc8de7ec7ec1a1ca7bfabe567701", BuildDate:"2019-07-19T19:02:15Z", GoOs:"unknown", GoArch:"unknown"}

I have set `KUBECONFIG=/Users/adoyle/.kube/config:/Users/adoyle/.kube/work-dev.config:/Users/adoyle/.kube/work-test.config` for [Configure Access to Multiple Clusters](https://kubernetes.io/docs/tasks/access-application-cluster/configure-access-multiple-clusters/#set-the-kubeconfig-environment-variable).
It failed to `make run`, and only works with `KUBECONFIG=/Users/adoyle/.kube/config`.

![image](https://user-images.githubusercontent.com/1998490/62921755-328bfa80-bddc-11e9-8805-0c3a3bad0f3c.png)

**Comment by DirectXMan12** [comment]
/priority important-soon

We need to go over the rules in `clientcmd` again -- it appears to have changed a decent amount since I last looked at it.

**Comment by DirectXMan12** [comment]
I've re-filed this against controller-runtime, which is the correct location.
