### ISSUE TITLE
clean content of go.mod

### ISSUE THREAD

**Issue by gaogaoSpark** [kubernetes-sigs/kubebuilder#937]
first Suggestions :
1.Dependence on chaos,

2. Suggestions for managing packages
questtion:
kubebuilder init  clean content of go.mod

**Comment by DirectXMan12** [comment]
> Dependence on chaos

I'm not sure what you mean here

> kubebuilder init clean content of go.mod

can you clarify what you mean here as well?

**Comment by gaogaoSpark** [comment]
Sorry, I misunderstood it.
