### ISSUE TITLE
kubebuilder init failed on creating a new project

### ISSUE THREAD

**Issue by sarjeet2013** [kubernetes-sigs/kubebuilder#955]
➜  estest curl -sL https://go.kubebuilder.io/dl/2.0.0-rc.0/${os}/${arch} | tar -xz -C /tmp/
➜  estest sudo mv /tmp/kubebuilder_2.0.0-rc.0_${os}_${arch} /usr/local/kubebuilder
➜  estest export PATH=$PATH:/usr/local/kubebuilder/bin

➜  estest kubebuilder init --domain test.com
go mod tidy
go: finding sigs.k8s.io/controller-runtime v0.2.0-rc.0
go: sigs.k8s.io/controller-runtime@v0.2.0-rc.0: unknown revision v0.2.0-rc.0
go: error loading module requirements
2019/08/21 18:01:44 exit status 1

➜  estest sw_vers
ProductName:	Mac OS X
ProductVersion:	10.14.6
BuildVersion:	18G87

Let me know if there is any additional information needed?

/kind bug

**Comment by sarjeet2013** [comment]
➜  estest kubebuilder version
Version: version.Version{KubeBuilderVersion:"2.0.0-rc.0", KubernetesVendor:"1.14.1", GitCommit:"45cbf7174d58867d97a100e52971b7e6a2fc9131", BuildDate:"2019-08-16T00:25:53Z", GoOs:"unknown", GoArch:"unknown"}

**Comment by DirectXMan12** [comment]
works fine for me.  Are you using a module proxy or something?

**Comment by DirectXMan12** [comment]
closing due to no response
