### ISSUE TITLE
KubeBuilder needs a logo

### ISSUE THREAD

**Issue by droot** [kubernetes-sigs/kubebuilder#960]
I think it's high time that we should have a KubeBuilder logo.

/cc @DirectXMan12 

/kind feature

**Comment by afirth** [comment]
Here's my 10 minute crack
![kubebuilder](https://user-images.githubusercontent.com/1820656/64050134-6b1b2a80-cb77-11e9-9b15-e0b834c84b7f.png)
[SVG gist](https://gist.github.com/afirth/4e2dcb652959f357b4bec623161395f4)

**Comment by DirectXMan12** [comment]
We have a logo now, just trying to extricate it from storage :-)
