### ISSUE TITLE
Publish packages for multi-arch

### ISSUE THREAD

**Issue by mkumatag** [kubernetes-sigs/kubebuilder#966]
This issue to publish kubebuilder binaries for all the possible architectures like arm, ppc, s390x etc..

/kind feature

**Comment by DirectXMan12** [comment]
/help

PRs welcome.  You'll have to update our cloudbuild configs to do the various builds, plus make sure that `kube-apiserver` and such build properly for the vraious platforms.

I suspect this won't just be one contributor doing this, so folks should fee free to chime in if they have expertise on a binary.

I'll keep a checklist here of what's got a PR already:

- [x] arm64 #979 
- [x] ppc64le #979 
- [ ] s390x
- [ ] YOUR PLATFORM HERE

**Comment by estroz** [comment]
I'm going to re-open this since an arm64 control plane would be really nice to have.

/open

**Comment by camilamacedo86** [comment]
Hi @estroz, 

> I'm going to re-open this since an arm64 control plane would be really nice to have.

It was previously close with the PR: https://github.com/kubernetes-sigs/kubebuilder/pull/979/files.  
So, ` arm64` shows already in place, see:

<img width="402" alt="Screen Shot 2021-02-09 at 16 13 20" src="https://user-images.githubusercontent.com/7708031/107392592-c170f480-6af1-11eb-90ad-a9e9d41d11a3.png">

in this way, could you please clarify what is missing done here?

**Comment by estroz** [comment]
@camilamacedo86 there are no envtest tools tarballs for arm64/ppc64le. https://github.com/kubernetes-sigs/kubebuilder/pull/1992 fixes that.

**Comment by estroz** [comment]
@DirectXMan12 can you close this issue once platform variables are updated in gcloud?

**Comment by Adirio** [comment]
I think this was already updated, closing it. Reopen if it still hasn't been updated.

/close

**Comment by ToMe25** [comment]
The platform variables for kube-rbac-proxy don't seem to be updated correctly in the google cloud.
The arch is set as `amd64` for all four images, and the os is set to `linux` for all of them.
This release can be found [here](https://console.cloud.google.com/gcr/images/kubebuilder/GLOBAL/kube-rbac-proxy@sha256:a06e7b56c5e1e63b87abb417344f59bf4a8e53695b8463121537c3854c5fda82/details?tab=info)

This is the full version 0.8.0(latest) manifest:
```
{
   "schemaVersion": 2,
   "mediaType": "application/vnd.docker.distribution.manifest.list.v2+json",
   "manifests": [
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 739,
         "digest": "sha256:34e8724e0f47e31eb2ec3279ac398b657db5f60f167426ee73138e2e84af6486",
         "platform": {
            "architecture": "amd64",
            "os": "linux"
         }
      },
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 739,
         "digest": "sha256:5a9f8e2f60fc4d02e364fa0192c01c79e8fac7e0c6a01cbc5b17152d6f21deae",
         "platform": {
            "architecture": "amd64",
            "os": "linux"
         }
      },
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 739,
         "digest": "sha256:17c7b8012f6648bc45a1667eb63f29b6cbe172e53f7c9b4c0f316ee13b6219ba",
         "platform": {
            "architecture": "amd64",
            "os": "linux"
         }
      },
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 739,
         "digest": "sha256:257deb7abac3138fb5497cddd3bc85b14d9de5188f6cfe70e0e0c7c4741583a6",
         "platform": {
            "architecture": "amd64",
            "os": "linux"
         }
      }
   ]
}
```

**Comment by mkumatag** [comment]
even I have noticed this,! manifest is not populated properly.

**Comment by ToMe25** [comment]
If this would get fixed, would it get fixed for version 0.8.0, or is the earliest it might be fixed the next build?

**Comment by ToMe25** [comment]
Should I make a separate issue about this invalid manifest, or hope it fixes itself if there ever is a later release?

**Comment by estroz** [comment]
This has been fixed: https://console.cloud.google.com/gcr/images/kubebuilder/GLOBAL/kube-rbac-proxy@sha256:db06cc4c084dd0253134f156dddaaf53ef1c3fb3cc809e5d81711baa4029ea4c/details?tab=info

**Comment by ToMe25** [comment]
Thanks for fixing this, and thanks for letting me know.
I may just not have noticed if this got update earlier, because my old here link still links to the old version.
