### ISSUE TITLE
PersistentVolume operations with kubebuilder

### ISSUE THREAD

**Issue by champak** [kubernetes-sigs/kubebuilder#971]
Hi folks, I have run into issues listing/accessing PersistentVolumes/PersistentVolumeClaims via the client.List api. I was expecting something on the lines of:
getmyPVs := &corev1.PersistentVolumeList{}
err := <ref to client.Client>.List(context, getmyPVs, <namespace>)

would get the list of PVs but does not seem to work. I am guessing others must have used PV/PVCs with kubebuilder apis but did not turn up any examples. Does the kubebuilder client support PV/PVC operations ? I was going on the assumption that the client can handle any type of resource including PV/PVCs. Thanks for any clarification !

**Comment by champak** [comment]
I found that listing PersistentVolumeClaims (as opposed to PersistentVolumes) in the same manner as above worked OK. Perhaps the issue is not with kubebuilder but rather the type of PV/PVCs that I am using. In any case would love to hear how PV/PVCs have worked for others with kubebuilder.

**Comment by mcristina422** [comment]
I ran into a similar problem and was confused util I remembered that PVs are cluster scoped.

[Persistent Volumes](https://kubernetes.io/docs/concepts/storage/persistent-volumes/) are not namespaced while Persistent Volume Claims are. So make sure you are not setting a namespace in your request

```golang
var pv corev1.PersistentVolume
err = a.client.Get(ctx, types.NamespacedName{
	Name:      pvc.Spec.VolumeName,
}, &pv)
```

**Comment by DirectXMan12** [comment]
@champak if you don't have any options, the following should just work:

```go
var myPVs corev1.PersistentVolumeList
err := cl.List(context.Background(), &myPVs)
```

(basically what you listed), unless you don't have permissions to fetch cluster-scoped objects with whatever you're using to connect to the cluster

**Comment by champak** [comment]
@mcristina422  & @DirectXMan12  Thanks for the pointers ! I had been passing in a namespace to the List API and like Michael pointed out, PVs do not have a namespace association. Getting rid of it worked for me.
