### ISSUE TITLE
Question: Reconciling on v1.Event objects

### ISSUE THREAD

**Issue by eytan-avisror** [kubernetes-sigs/kubebuilder#974]
I've been trying to follow the docs on this one, but guess I am doing something wrong - appreciate any suggestions.

My current reconciler triggers on watch events of my custom resource `MyResource`.

```
func (r *MyResourceReconciler) SetupWithManager(mgr ctrl.Manager) error {
	return ctrl.NewControllerManagedBy(mgr).
		For(&v1alpha.MyResource{}).
		Complete(r)
}
```

I would also like to trigger a reconcile of `MyResource` on specific v1.Events (e.g. a watch on "Events" with field selector).

The event object is not owned by the `MyResource` controller, and is published by a different controller.

The event will contain data that will allow the controller to discover the namespaced name of `MyResource` and get it.

The reason I would like to use this mechanism (i.e. Events instead of simply updating the CR of `MyResource`), is because i'd like to keep the relationship between the two controllers generic in nature, and using Events seems like a great way to achieve this.

What is the best way to implement this considering the scaffolding for Kubebuilder v2?
Is there a way I can trigger reconcile for `MyResource` for a `v1.Event` with field selector?

**Comment by eytan-avisror** [comment]
Was able to do this using `Watches()`, looks like it was not working because my cluster had a wrong version of the CRD and it was throwing a panic.

**Comment by cheyang** [comment]
@eytan-avisror Is there any example of using `watches` ?
