### ISSUE TITLE
Is there a way to include License header in generated YAML files?

### ISSUE THREAD

**Issue by functicons** [kubernetes-sigs/kubebuilder#982]
Is there a way to include License header in generated YAML files (e.g., `config/rbac/role.yaml`)? I know for Go files, it automatically includes the license header from `hack/boilerplate.go.txt`. I tried adding a `hack/boilerplate.yaml.txt`, but it didn't work.

/kind feature

**Comment by DirectXMan12** [comment]
/priority backlog

not yet -- that code is currently specific to the deepcopy-gen code.  We could potentially standardize and extend this.
