### ISSUE TITLE
[QuickStart] - Missing information - Unable to follow all steps

### ISSUE THREAD

**Issue by camilamacedo86** [kubernetes-sigs/kubebuilder#984]
/kind bug

Following the steps in https://book.kubebuilder.io/quick-start.html#create-a-project it is missing tell to the user:

- create the project dir and going inside of it before run the init command
- If should answer y, y when the API is created
- provide an example over what should/could be added in the spec and status since is unable to continue without adding something there and say to run make in the dir
- explain how and where to edit them to run `"kubectl apply -f config/samples/"``

Also, note that the `Test It Out Locally` should be after the `Install Samples` which shows be a requirement for it. 

IMHO: Users should be able to get something running and perform all steps by following it.

**Comment by DirectXMan12** [comment]
These steps are provided more explicitly in the tutorial, especially the bits about `config/samples` and spec and status.  The quickstart should maybe be renamed or reworded a bit, but example edits shouldn't go there.

**Comment by camilamacedo86** [comment]
Hi @DirectXMan12, 

In POV, users will start to follow the Quick Start just to check how it works instead of reading and follows the big tutorial. Small changes could make these steps already described easier to be understanding as avoid initial mistakes.

**Comment by camilamacedo86** [comment]
Hi @DirectXMan12,

I did a PR with the small changes that I believe which will be very helpful to me and for other new users. I hope that you like it: https://github.com/kubernetes-sigs/kubebuilder/pull/1008. 

Thank you for your attention.

**Comment by DirectXMan12** [comment]
thanks!  I've left some feedback, but the general ideas are good.  We've also got some more suggestions over @ #1034 which line up with a lot of what you were saying :-).  I think we might want an intermediate section, or collapsible bits.

**Comment by camilamacedo86** [comment]
/assign @camilamacedo86

Hi @DirectXMan12,

Tks for your review and time. I will address your comments and try to address what was requested in the  #1034  as well 👍

**Comment by camilamacedo86** [comment]
Closing it with the merge of the PR: https://github.com/kubernetes-sigs/kubebuilder/pull/1008
