### ISSUE TITLE
Command make could create/update the specs in the CR example

### ISSUE THREAD

**Issue by camilamacedo86** [kubernetes-sigs/kubebuilder#987]
WHAT: Update the CR files
WHEN: The make command is executed after the specs and status be added in the *_type.go

**Comment by DirectXMan12** [comment]
I'm not entirely clear what you're asking for here, can you provide an an example of what you want?

**Comment by camilamacedo86** [comment]
Hi @DirectXMan12, 

Thank you for your reply. I checked that it is already working on this way which is great. Really tks. Sorry for raise it. We can ignore this one.
