### ISSUE TITLE
.gitignore added in the scaffold project

### ISSUE THREAD

**Issue by camilamacedo86** [kubernetes-sigs/kubebuilder#988]
WHAT: Add .gitignore in the scaffold project
WHY: ignore by default built files and make the lifer easier for its user. e.g bin

**Comment by DirectXMan12** [comment]
/good-first-issue
/priority backlog

Although not everyone is using Git, those that aren't are probably in the minority, and this could be fairly useful.

**Comment by DirectXMan12** [comment]
already exists: https://github.com/kubernetes-sigs/kubebuilder/blob/4f7807c6d611b4f99521379eb52ad98d1fe02d0e/pkg/scaffold/project.go#L127
