### ISSUE TITLE
unable to create the namespace where please me by default

### ISSUE THREAD

**Issue by camilamacedo86** [kubernetes-sigs/kubebuilder#989]
The manager.yaml is created with the ` namespace: system` by default. I as a user, I would like to define where the operator will be applied in the cluster. 

Suggestion: 
- remove the ` namespace: system` 
- let it be applied in the current namespace or where in the namespace defined in the kubectl command. E.g `kubectl apply -f config/manager/manager.yaml -n memcached-kubebuilder`

**Comment by DirectXMan12** [comment]
if you actually install with `make install` (or by using kustomize), the kustomization sets a name prefix which installs elsewhere.  You should be able to update the kustomization file to change to install where you want.
