### ISSUE TITLE
Unable to use the install commands because "kustomization" files are not working

### ISSUE THREAD

**Issue by camilamacedo86** [kubernetes-sigs/kubebuilder#991]
## What did you do? 
Following the quick started and try to use the make install 

## what did you expect? 
the main files are applied in the cluster with success ( manager, sample, crd, rbca )

##  what did you face? 
issues because of the kustomization files

**Comment by DirectXMan12** [comment]
@camilamacedo86 can you please paste the *exact* errors that you get?

For instance, if I run `make generate install` in testdata/project-v2, everything is fine.  Do you have kustomize installed as per the [Installation Instructions](https://book.kubebuilder.io/quick-start.html#installation)?

```bash
sollyross@G💻 ~[go:sigs.k8s.io/kubebuilder]/testdata/project-v2 $ make install
go get sigs.k8s.io/controller-tools/cmd/controller-gen@v0.2.0
go: finding sigs.k8s.io v0.2.0
go: finding sigs.k8s.io/controller-tools/cmd/controller-gen v0.2.0
go: finding sigs.k8s.io/controller-tools/cmd v0.2.0
/home/sollyross/dev/gopath/bin/controller-gen "crd:trivialVersions=true" rbac:roleName=manager-role webhook paths="./..." output:crd:artifacts:config=config/crd/bases
kustomize build config/crd | kubectl apply -f -
customresourcedefinition.apiextensions.k8s.io/admirals.crew.testproject.org created
customresourcedefinition.apiextensions.k8s.io/captains.crew.testproject.org created
customresourcedefinition.apiextensions.k8s.io/firstmates.crew.testproject.org created
```

**Comment by camilamacedo86** [comment]
Hi @DirectXMan12, 

You are correct, after install kustomize it worked.  Closing it tks.
