### ISSUE TITLE
go mod tidy messes up deps when calling init in an existing project

### ISSUE THREAD

**Issue by skonto** [kubernetes-sigs/kubebuilder#993]
When initializing a project `go mod tidy` should be optional. 
In my case I get: 
```
go: k8s.io/kubernetes@v1.15.3 requires
	k8s.io/api@v0.0.0: reading k8s.io/api/go.mod at revision v0.0.0: unknown revision v0.0.0
2019/09/12 01:54:00 exit status 1
```
Probably due to this: https://github.com/kubernetes/kubernetes/issues/79384
but even using the trick here https://github.com/networkservicemesh/networkservicemesh/pull/1519 this does not work. Not sure what k8s deps controller runtime brings in btw.
From what I checked in project v1 you could avoid deps ensure https://github.com/kubernetes-sigs/kubebuilder/blob/v2.0.0/pkg/scaffold/project.go#L62, nothing similar for project v2.

**Comment by DirectXMan12** [comment]
IIRC, we no longer make it optional because all operations effectively require doing similar actions anyway.

Is this new?  Does it only happen if you depend on `k8s.io/kubernetes` directly (that should almost never be a thing that you do)

**Comment by camilamacedo86** [comment]
Hi @DirectXMan12 and @mengqiy,

Shows that it can be closed anyway. unable to reproduce the issue with the master branch. -1 👍
