### ISSUE TITLE
Pattern for adding Controller Watch Functions

### ISSUE THREAD

**Issue by champak** [kubernetes-sigs/kubebuilder#994]
Hi, I am interested in adding watches on a few resource types e.g Pods. I found pointers to the APIs to use at https://book-v1.book.kubebuilder.io/beyond_basics/controller_watches.html. I am trying to add these APIs to the generated main() which was already armed with the (<controller>.<reconciler>{Client, Log, Scheme}).SetupWithManager() invocation among other things. I was expecting some APIs around adding the watch functions in. 

Looking around at other threads I saw mention of APIs like AddToManager etc. which sound like what I would want. My generated code did not seem to have such APIs. I used kubebuilder version KubeBuilderVersion:"2.0.0-beta.0" BuildDate:"2019-07-19T19:02:15Z and built the scaffolding with the sample instructions (kubebuilder create/init ..). Do I need to do anything more to get additional APIs for plugging in Watches into the controller/manager initialization path ? I am unclear after reading the docs on whether watching for core resources in addition to the CRD requires a separate controller for the core resource and then registering all applicable controllers with the manager. Thanks for any clarification.

**Comment by champak** [comment]
Adding a controller for watching Pods in the "main()" init path worked to some degree. I had something on the lines of:
// Instaniate manager (from scaffolding)
// instantiate my reconciler off controller.() (from scaffolding)
// SetupWithManager.. (from scaffolding)
// instantiate a controller for pods with controller.New()
// Add a watch on the Pods
// mgr.Start(..SetupSignalHandler()) (from scaffolding)

EnqueueRequestForOwner is what I had wanted to use since I only want to care for Pods my CRD reconcile loop creates. That has not yet worked. Using EnqueueRequestForObject{} worked OK but I am ending up seeing all Pods. Is is possible to pass in a selector to this API. Also not sure what EnqueueRequestForOwner needs to filter for objects created by the CRD reconciler. Thanks.

**Comment by DirectXMan12** [comment]
First, I'd reccomend following the current iteration of the book, not the v1 book.

Secondly, generally, in controller-runtime (the runtime library that KubeBuilder projects use to manage things), watches generally don't live on their own -- they're part of a controller.

The high-level interface for that is [Builder](https://godoc.org/sigs.k8s.io/controller-runtime#Builder), and the next lower-level interface is [Controller](https://godoc.org/sigs.k8s.io/controller-runtime/pkg/controller#Controller).

We generally think about controllers from the perspective of "it reconciles type A directly, and owns types B, C, D, etc".  So, in your case, you'd reconcile your CRD directly (`.For(&yourapi.YourCRD{})`), which owns pods (`.Owns(&corev1.Pods{})`).

The `SetupWithManager` function just sets up a controller.  If you don't want that controller, you can remove or change the contents of that.

All of this is detailed in the book: https://book.kubebuilder.io/cronjob-tutorial/cronjob-tutorial.html.  I'd recommend following that, and if you're still unclear, come back here.

**Comment by champak** [comment]
Thanks for the pointers! Two related aspects that I am still looking for info on are:
- Is it possible to "own" more than one of the core resource type ? e.g. Would the infra support .Owns(&corev1.Pods{}) and .Owns(&corev1.Service{}) with the same instance of a controller or is the pattern to have separate ones for each "own"-ed resource type

- I am doing a diff on the spec of the Pod resources  to figure if anything I am interested in has changed. Would be nice to be able to have mask/template to pass into DeepEqual so that only the fields that I am interested in are checked for equality. Barebones DeepEqual does not seem to have that facility. Perhaps that is outside the scope of kubebuilder.

**Comment by DirectXMan12** [comment]
> Is it possible to "own" more than one of the core resource type

Yep!  A given resource can "own" any number of other resources.  For instance, a "Website" CRD might "own" deployments (for running the webserver) and services (for exposing the webserver).

> I am doing a diff

You might be able to use the "semantic deep equal" machinery in apimachinery: https://github.com/kubernetes/apimachinery/blob/master/pkg/conversion/deep_equal.go

An example is here: https://github.com/kubernetes/apimachinery/blob/master/pkg/api/equality/semantic.go

**Comment by champak** [comment]
Thanks for the tips ! I noticed one curious thing with created services and pods. When I delete the CRD the services seem to get auto cleaned up without any action from the reconcile logic ! Pods were not cleaned up and I added some cleanup for them. I am guessing the kube builder infra is maintaining references to the created core resources  (I had explicitly invoked SetControllerReference() ..) and in some case cleans up.

**Comment by DirectXMan12** [comment]
KubeBuilder doesn't automatically maintain references -- you have to explicitly call `SetControllerReference`.  Whenever you do so, the standard Kubernetes garbage collector will clean up after you -- kubebuilder isn't involved.

**Comment by champak** [comment]
@DirectXMan12 Thanks again ! For anyone checking out the thread the garbage collection on maintained references worked fine.  I tried looking for api-server logs to see if there were traces of the garbage collection logic and did not find any but that could have been due to the logging level.

**Comment by DirectXMan12** [comment]
garbage collection is done by a GC controller.  You'll prob need to look at the controller-manager logs

**Comment by mouradmourafiq** [comment]
@DirectXMan12 thanks for the support and sorry to revive this thread. 

Is it possible to own: `.Owns(&unstructured.Unstructured{})`? if not what would be the right way to watch changes of `Unstructured` objects.

**Comment by derekperkins** [comment]
@mouradmourafiq did you figure out if that works for owning unstructured objects?

**Comment by mouradmourafiq** [comment]
@derekperkins yes it works similar to owning the schema, there's a bit more work, but it works, [see](https://github.com/polyaxon/polyaxon/blob/master/operator/controllers/operation_controller.go#L126)

**Comment by rufreakde** [comment]
> @derekperkins yes it works similar to owning the schema, there's a bit more work, but it works [see](https://github.com/polyaxon/polyaxon/blob/master/operator/controllers/operation_controller.go#L126)

this example code (link is broken) of a complete scenario would be helpful for others encountering smilar problems. Can you share the code in full here
